/* GRADE GAIN — ENT QB.pdf — CHAPTER 3 (THROAT), TOPIC 6: "Neck Masses"
   Book pp.132-136 (PDF 141-145). Verbatim transcription of all 32 printed questions, Q301-Q332.
   Read page by page 2026-08-12; no page sampled. Keys from book p.136.
   ⚠️ ZERO EXPLANATION BOXES — p.136 is a bare key list, Q301-Q332 complete on one page.          */
var GGT6_STAGED = [
{ n:301, key:1, stem:'A 3-year-old child presents with a neck mass since about 3 days with fever and pain. What is the best next investigation?', opts:['CT','CBC','MRI','Biopsy'] },
{ n:302, key:0, stem:'50-year-old patient complaining of a painless neck mass since about 7 months but enlarging in the last 2 months and begin to compress and becoming hard. What is the best next step in management?', opts:['CT','CBC','bronchoscopy','Biopsy'] },
{ n:303, key:3, stem:'Which of the following is NOT true about Embryogenesis of the neck?', opts:['true neck is visible at 12th week.','pharynx separates head from heart at 5th week','constriction between head & thorax at 7th week','Adult Neck exists in embryo'] },
{ n:304, key:0, stem:'What is the commonest midline congenital neck mass in children?', opts:['Thyroglossal cyst','dermoid cyst','Chondroma','Cystic Hygroma'] },
{ n:305, key:3, stem:'All of the following are true about neck except:', opts:['Anterior triangle is from midline till the anterior border of sternomastoid','Posterior triangle is between sternomastoid and trapezius','The upper border of the neck courses along the mandible','80% of neoplastic masses are benign'] },
{ n:306, key:1, stem:'Which structure is responsible for the formation of lateral neck structures?', opts:['Foramen cecum','Branchial apparatus','Hyoid bone','Thyroid gland'] },
{ n:307, key:1, stem:'Which of the following is NOT true about Thyroglossal cyst?', opts:['Commonest congenital neck swellings','If infected, perform incision and drainage','It moves with tongue protrusion','It is removed with its tract'] },
{ n:308, key:1, stem:'What is the most common branchial apparatus pathology?', opts:['First branchial cyst','Second branchial cyst','Third branchial cyst','Fourth branchial sinus'] },
{ n:309, key:0, stem:'All of the following are true about branchial cleft anomalies except:', opts:['1st branchial cleft is related to hyoid bone','2nd branchial cleft develops at sternomastoid muscle','2nd branchial cleft cysts present in the third decade of life','2nd branchial track may connect with tonsil'] },

{ n:310, key:3, stem:'Which of the following is NOT true about congenital neck mass?', opts:['Thymus arises from 3rd Branchial arch','CT is mandatory in hemangioma','2nd Branchial cyst is anterior to SCM','Cystic hygroma has distinct border'] },
{ n:311, key:3, stem:'Which of the following is NOT true about laryngocele?', opts:['cystic dilatation of laryngeal saccule','it may be external or internal','it is at level of hyoid bone','It’s low in the neck'] },
{ n:312, key:2, stem:'Which of the following is true about Zenker’s Diverticulum?', opts:['It is felt before enlargement','Lateral, anterior and deeper than laryngocele','It causes halitosis','It is a midline neck mass'] },
{ n:313, key:0, stem:'Which of the following is a feature of chronic lymphadenitis?', opts:['Associated with tuberculosis','Painful swelling','Resolves within a week','No need for investigation'] },
{ n:314, key:1, stem:'Which of the following is a feature of lymphoma in the neck?', opts:['Solitary lymph node','Matted lymph nodes','Cystic consistency','Moves with tongue protrusion'] },
{ n:315, key:2, stem:'What is the most sensitive diagnostic tool for evaluating a neck mass?', opts:['X-ray','Ultrasound','CT scan','MRI'] },
{ n:316, key:2, stem:'Which of the following is a feature of a cystic hygroma?', opts:['Well-defined borders','Moves with tongue protrusion','Lymphatic obstruction','Located in the midline'] },
{ n:317, key:3, stem:'Upper neck border involves all of the following except:', opts:['Mandible','Mastoid bone','External occipital protuberance','Hyoid bone'] },
{ n:318, key:2, stem:'A newborn infant presented with a midline cystic swelling that was found immediately following birth. What is the most common etiology for this mass?', opts:['Malignancy','Benign – inflammatory','Benign – congenital','Benign – developmental'] },
{ n:319, key:0, stem:'Which of the following is the most readily available and informative investigation for the majority of neck masses?', opts:['US','X ray','CT','MRI'] },
{ n:320, key:2, stem:'Which of the following is the most common neck swelling?', opts:['Thyroglossal cyst','Goiter','Lymph node enlargement','Dermoid cyst'] },

{ n:321, key:1, stem:'Cervical LNs receive metastases from which of the following primary tumors most commonly?', opts:['Occult primary','Head and neck primary','Distant primary','Constitutional primary'] },
{ n:322, key:2, stem:'A 35-year-old male presents with severe swelling and pain in the submandibular region and difficulty swallowing. On examination, there is bilateral swelling of the submandibular area. A diagnosis of Ludwig’s angina is made. Which of the following is NOT true in the management of this patient?', opts:['Immediate airway management is a priority.','Intravenous antibiotics and anti-inflammatory drugs should be started promptly.','Incision and drainage should be performed as it is a cellulitis.','Surgical intervention may be required if an abscess forms.'] },
{ n:323, key:2, stem:'A 65-year-old immunocompromised female presents with a progressive, painful swelling under the mandible. She reports difficulty swallowing, a muffled voice, and fever. On examination, there is bilateral swelling of the submandibular region, and the floor of the mouth is tender. The patient appears toxic and is in respiratory distress. What is the most likely diagnosis in this case?', opts:['Branchial cyst','Thyroglossal cyst','Ludwig’s angina','Submandibular sialadenitis'] },
{ n:324, key:1, stem:'Which of the following tumors mostly sends metastasis to upper deep cervical lymph nodes?', opts:['Breast cancer','Nasopharyngeal carcinoma','Hepatocellular carcinoma','Renal sarcoma'] },
{ n:325, key:2, stem:'Which of the following is a characteristic feature of a laryngocele?', opts:['Midline neck swelling that moves with swallowing','Hard, fixed mass in the posterior triangle','Lateral compressible neck swelling at the level of the hyoid bone','Painful, erythematous swelling in the submandibular region'] },
{ n:326, key:3, stem:'A 7-year-old boy presented with a lateral neck mass. His parents reported that he suffered from a severe common cold infection 5 days ago. Examination revealed firm mass mobile with fingers and tender on pressure. Which of the following is the most likely diagnosis of this neck mass?', opts:['Thyroid cancer','Thyroglossal cyst','Branchial cleft cyst','Acute lymphadenitis'] },
{ n:327, key:1, stem:'A 56-year-old female patient comes with a lateral neck mass that appeared 9 months ago and increased in size gradually. What’s the next step to managing this patient?', opts:['ultrasound','CT with contrast','Re-examination','Pet scan'] },

{ n:328, key:2, stem:'A 35-year-old male, who is a professional saxophone player, presents with a compressible lateral neck swelling that increases in size during playing. He reports no pain or difficulty in swallowing. On examination, the swelling is soft, reducible, and located in the lateral neck region. There is no associated lymphadenopathy or fever. What is the most likely diagnosis?', opts:['Thyroglossal duct cyst','Branchial cleft cyst','Laryngocele','Cervical lymphadenopathy','Thyroid nodule'] },
{ n:329, key:1, stem:'What is the treatment in the previous case?', opts:['Antibiotic therapy','Surgical excision','Observation only','Steroid injection','Radiation therapy'] },
{ n:330, key:4, stem:'Regarding Ludwig’s angina, all of the following are true except:', opts:['It occurs in immunocompromised individuals','Infection in submental and submandibular spaces','Dental infection may be a cause','Stridor may develop rapidly','The tonsil is pushed medially'] },
{ n:331, key:2, stem:'Which of the following is true about laryngocele?', opts:['An air containing sac in the larynx of certain professions (glassblowers & trumpeter)','A retention cyst arising from laryngeal ventricle secondary to ventricle malignancy','Both of the above','None of the above'] },
{ n:332, key:0, stem:'A secondary laryngocele is secondary to which of the following?', opts:['Ventricular malignancy','Tuberculous laryngitis','Recurrent respiratory papillomatosis','Laryngo-scleroma'] }
];
