/* Grade Gain — Neurology topic 08 "Epilepsy" — Part A, Q141-Q158 (18 entries)
 * Entry objects only, comma-separated, no wrapper array, no var. The hub splices this directly.
 * Questions book pp.31-33, answers book pp.35-36 (Q141-146 answered p.35, Q147-158 answered p.36).
 * All 18 filed `nr-epilepsy`. 5 boxed (141,142,143,157,158) take NO authored marker; the other 13
 * carry it.
 * Grounded throughout against the course lecture `L4) Seizures_Epilepsy`
 * (content\neuro\lectures\L4) Seizures_Epilepsy.txt), which covers status-epilepticus staging and
 * drug protocol, absence epilepsy and its AED table, provoked-vs-unprovoked seizures, and the
 * seizure/syncope/PNES differential directly. Claims outside that lecture are tagged "not taken
 * from the course material" per standing rule.
 * Part B (Q159-Q176) is a sibling agent's file, gg-nr-t08.draft-B.js — not read or touched here.
 */

{
  id:'npqb-nr-141', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'An unconscious 35-year-old man is brought to the ER by his wife. She explains that the patient takes Phenytoin for chronic epilepsy. An hour ago, the patient had a seizure but did not regain consciousness. Physical examination reveals that his T is 38.5°C, blood pressure is 95/40 mm Hg, pulse is 110/min, and RR is 20/min. During the examination, the physician observes the sudden onset of tonic-clonic convulsions. Which of the following is the most common precipitating cause of this emergency?',
  options:['Alcohol withdrawal','Drug noncompliance','Head trauma','Hypoxia','Intracranial infection'],
  answer:1,
  explanation:'**The bank prints an explanation box for this question, transcribed here verbatim:**\n\n> The most frequent precipitating factor in adults with a diagnosis of epilepsy is drug noncompliance. Alcohol withdrawal (choice A), head trauma (choice C), hypoxia (choice D), intracranial infection (choice E), intracranial tumor, and metabolic alterations are other precipitating factors for status epilepticus.\n\nThe vignette is status epilepticus under the course lecture\'s own definition — a seizure lasting five minutes or more, or repeated seizures without recovery of consciousness between them — since the patient convulses again without regaining consciousness after the first seizure (`L4) Seizures_Epilepsy`). That lecture\'s own protocol is airway-breathing-circulation, then IV diazepam, then IV phenytoin; it does not itself rank precipitating causes, so the box\'s ranking of drug noncompliance above the other listed causes is not taken from the course material. Clinically, a missed dose removing a previously adequate drug level is the everyday reason a known epileptic reaches the ER in status, which is why noncompliance outranks the other listed precipitants.\n\nAlcohol withdrawal (choice A) triggers seizures through a different mechanism and timeline — GABA-receptor downregulation and NMDA-receptor upregulation from chronic use unmasked roughly 24-48 hours after the last drink — with no chronic-AED history to explain it here. Head trauma (choice C) falls under the lecture\'s own symptomatic/structural causes of epilepsy alongside infection and vascular disease, but this is an established chronic epileptic already controlled on phenytoin, and the vignette gives no history of a new injury. Hypoxia (choice D) is more often a consequence of a prolonged convulsion with unprotected airway than its initial trigger — which is exactly the danger this patient is now in as he convulses again. Intracranial infection (choice E) belongs to the lecture\'s infectious causes of epilepsy (meningitis, encephalitis), and would be expected to show meningism or a clearer infective picture rather than the tachycardia and low-grade fever that sustained convulsive activity itself produces.\n\nThe lecture\'s own status-epilepticus timeline is the next step here regardless of cause: 0-5 minutes airway, breathing, circulation, oxygen, IV access, glucose check and ECG; 5-10 minutes IV diazepam 10 mg in adults (0.1-0.3 mg/kg in children) over 15 seconds; 10-30 minutes IV phenytoin 1000 mg in adults (18-20 mg/kg in children), or IV levetiracetam 3000 mg if phenytoin is unavailable; beyond 30 minutes, refractory status needs IV thiopental, propofol or a midazolam infusion in ICU, aiming for burst suppression (`L4) Seizures_Epilepsy`).',
  objective:'Drug noncompliance is the leading precipitant of status epilepticus in a known epileptic; the case itself meets the lecture\'s own definition of status by duration and lack of recovery between seizures.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.31 (answer p.35, explanation box printed). The bank prints "3 5-year-old" and "pulse is 1 10/min"; corrected here to 35-year-old and 110/min.'
},

{
  id:'npqb-nr-142', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'A 16 year-old male presents with a five-year history of absence seizures with three recent generalized convulsions. Which one of the following drugs, given as monotherapy, is most likely to control his fits?',
  options:['Clonazepam','Ethosuximide','Gabapentin','Sodium Valproate','Topiramate'],
  answer:3,
  explanation:'**The bank prints an explanation box for this question. It is transcribed here with two corrected print garbles and one defect held exactly as printed, because correcting the third would silently change the claim — see source for all three:**\n\n> Absences, generalized tonic clonic seizures and myoclonus are features of primary &generalized epilepsy. The treatment of choice includes Na valproate, lamotrigine. Clonazepam is useful in myoclonus, Ethosuximide in isolated absences\n\nThis patient has both absence seizures and generalized tonic-clonic convulsions, which the box terms "primary &generalized epilepsy" as printed — held verbatim rather than resolved to the standard clinical term "primary generalized epilepsy", since the ampersand\'s origin is unclear and correcting it would be an interpretation, not a transcription. The course lecture\'s own AED table gives sodium valproate as first line for generalized tonic-clonic, absence and myoclonic seizures alike (`L4) Seizures_Epilepsy`), which is exactly why it is the one drug able to cover both seizure types in this patient as monotherapy. Ethosuximide (option b) controls absences alone and does nothing for the tonic-clonic component; it is the lecture\'s own first choice for pure absence epilepsy but not for a mixed picture. Clonazepam (option a) is a myoclonus drug, gabapentin (option c) has no established role in generalized epilepsy, and topiramate (option e) is second-line.\n\nThe lecture\'s own case of childhood absence epilepsy gives sodium valproate the same 15-20 mg/kg/day dosing it gives ethosuximide, underlining that the two are treated as interchangeable first-line agents for pure absence disease; valproate is preferred here only because this patient\'s mixed picture needs the drug that also covers the tonic-clonic component (`L4) Seizures_Epilepsy`). Lamotrigine, the lecture\'s own second-line choice "if valproate contraindicated", is not on this option list, but the reason it exists as an alternative — valproate\'s teratogenicity in women of reproductive age — is a caution this male patient does not raise. Topiramate is a genuine generalized tonic-clonic prophylactic in the lecture\'s AED table, which is why it is a plausible-looking distractor rather than a random name, but it sits second-line behind valproate for this seizure type and has no listed role in absence seizures at all.',
  objective:'Sodium valproate is the monotherapy of choice when a patient has both absence and generalized tonic-clonic seizures; ethosuximide only covers pure absence epilepsy.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.31 (answer p.35, explanation box printed). The box prints three defects inside the box text: "ate features" for "are features" and "myoclonus,.Ethosuximide" for "myoclonus, Ethosuximide", both corrected here; and "primary &generalized epilepsy", held exactly as printed because dropping the ampersand would silently change "primary & generalized" into the single compound term "primary generalized epilepsy" — not corrected.'
},

{
  id:'npqb-nr-143', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'A 27-year-old man presents with a two years\' history of intermittent tingling sensation involving his left side. It starts in his fingers and spreads in 10-20 seconds to affect the whole arm and leg on the same side. The attacks only last for one minute. What is the most likely diagnosis?',
  options:['Hyperventilation','Migraine with aura','Multiple sclerosis','Somatosensory seizures','Transient ischemic attacks'],
  answer:3,
  explanation:'**The bank prints an explanation box for this question, transcribed here with one repair — the printed "syn1ptoms" corrected to "symptoms" (printed form noted in source):**\n\n> Positive symptoms (jerking, tingling) usually signify epilepsy. Negative symptoms (weakness, numbness) are usually caused by transient focal ischemia. Spread of symptoms (\'marching\') indicates migraine (in 5-20 minutes) or seizures (in seconds). The usual source of somatosensory seizures is the parietal lobe\n\nThe course lecture classifies exactly this kind of seizure — tingling that marches from the hand up the same-sided arm and leg — as a focal aware (simple partial) seizure with a sensory semiology, listing sensory phenomena such as tingling among the non-motor manifestations of a focal seizure arising from one hemisphere (`L4) Seizures_Epilepsy`); a focal aware seizure is by definition one the patient stays conscious through and can recall, which fits the one-minute attack described here. The box\'s seconds-scale march versus the minutes-scale march of a migraine aura is not covered in the lecture and is not taken from the course material.\n\nHyperventilation (option a) produces bilateral perioral and distal-limb tingling from acute respiratory alkalosis, not a spreading unilateral march confined to one side. Migraine with aura (option b) is the closest distractor because it too can march, but the box\'s own timescale — minutes rather than seconds — and the lecture\'s classification of migraine\'s tempo as "progression over seconds to minutes" separates a slow aura from this patient\'s 10-20 second spread (`L4) Seizures_Epilepsy`); migraine aura is also typically visual before it is sensory, and would usually be followed by headache, which this vignette does not mention. Multiple sclerosis (option c) can cause unilateral sensory symptoms but as a fixed or slowly evolving deficit over hours to days from demyelination, not a stereotyped one-minute paroxysm that recurs identically. Transient ischemic attack (option e) produces negative symptoms — numbness, weakness — from a sudden loss of blood flow, not the positive, marching, jerking or tingling quality the box assigns to epilepsy; a TIA also does not repeat with the same stereotyped march each time the way this two-year history does.',
  objective:'A rapid, seconds-scale, positive, unilateral march of sensory symptoms with preserved consciousness is a focal sensory seizure; a slower, minutes-scale march favours migraine aura, and negative symptoms favour ischemia.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.31 (answer p.35, explanation box printed). The bank prints "1 0-20 seconds" and the box prints "syn1ptoms"; corrected here to 10-20 seconds and symptoms respectively.'
},

{
  id:'npqb-nr-144', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'Best treatment for absence epilepsy:',
  options:['Carbamazepine','Ethosuximide','Phenobarbital'],
  answer:1,
  explanation:'**Ethosuximide is the first-choice drug for absence (petit mal) epilepsy**, and the course lecture states this directly in its AED-matching table: for absence seizures, first line is ethosuximide, with sodium valproate as an alternative when generalized tonic-clonic seizures coexist (`L4) Seizures_Epilepsy`). Ethosuximide works by blocking the T-type calcium channels in thalamocortical neurons that generate the 3 Hz spike-wave rhythm of absence seizures, and unlike valproate it has no useful action against any other seizure type, which is why it is reserved for pure absence epilepsy *(the channel mechanism is not taken from the course material)*.\n\nCarbamazepine and phenobarbital are both wrong for the opposite reason: the lecture\'s own table marks carbamazepine as never to be used for absence seizures, because sodium-channel blockers can worsen generalized absence and myoclonic seizures, and phenobarbital has no place in first-line absence treatment either — it belongs to status epilepticus and neonatal seizure management, not absence epilepsy. The lecture\'s own worked case of childhood absence epilepsy confirms the dosing in practice: ethosuximide 15-20 mg/kg/day, with sodium valproate at the same 15-20 mg/kg/day range as the alternative when tonic-clonic seizures coexist, and lamotrigine held in reserve for when valproate is contraindicated (`L4) Seizures_Epilepsy`). Phenobarbital appears in the lecture only within the wider AED landscape, not the absence-specific table; its own established niches are neonatal seizures and, at loading dose, refractory status epilepticus, neither of which this question is asking about. Ethosuximide\'s own most-cited side effects are gastrointestinal upset and, less commonly, drowsiness and headache *(not taken from the course material)*, a tolerable profile that is part of why it remains first choice for a disorder that otherwise needs no other seizure coverage.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'Ethosuximide is first-line for pure absence epilepsy; carbamazepine is contraindicated because it can worsen absence and myoclonic seizures.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.31 (answer p.35). Prints only three options.'
},

{
  id:'npqb-nr-145', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'Which is diagnostic of epilepsy?',
  options:['EEG','History taking','MRI brain'],
  answer:1,
  explanation:'**History taking is the diagnostic tool, and the course lecture is explicit about it**, naming history the number-one diagnostic tool and stating outright that diagnosis is clinical, with EEG and MRI supporting rather than replacing the history (`L4) Seizures_Epilepsy`). A witnessed account of what actually happened — the aura, the stereotyped movements, the post-ictal confusion — is what separates a seizure from its mimics, and no single test substitutes for it.\n\nEEG (option a) is the closest distractor because it is the test most associated with epilepsy in a student\'s mind, but the same lecture warns that it may be normal between seizures — an interictal EEG can be entirely normal in a genuine epileptic and can occasionally show nonspecific abnormalities in someone who has never had a seizure. It supports classification; it does not make the diagnosis. MRI brain (option c) detects a structural cause once epilepsy is already suspected; it cannot itself establish that an event was a seizure. The lecture ranks the tests in the same order for a reason: video-EEG monitoring, which captures the clinical event and the electrical discharge together, is its own stated gold standard, and even that is a tool for confirming what the history has already made likely, not a replacement for taking the history in the first place (`L4) Seizures_Epilepsy`). A home video recorded by a witness is the lecture\'s own practical substitute where video-EEG is not available — it lets a clinician see the exact semiology the history is trying to describe.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'Epilepsy is a clinical diagnosis made from the history; EEG and MRI support the diagnosis and classify it but do not replace a good eyewitness account.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.31 (answer p.35). Prints only three options.'
},

{
  id:'npqb-nr-146', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'A 20-year-old male with a long history of epilepsy presents with 3 generalized seizures in the past 90 minutes, during which he does not regain consciousness between seizures. His epilepsy was poorly controlled on phenytoin and carbamazepine. Yesterday, the patient visited a friend who advised him to stop all anti-epileptic medications and start herbal treatment. What is the most likely diagnosis?',
  options:['Status epilepticus','Generalized tonic-clonic seizure','Epileptic encephalopathy','Convulsive syncope'],
  answer:0,
  explanation:'**This is status epilepticus by definition, and stopping his AEDs for herbal treatment is the precipitant.** The course lecture defines status epilepticus as a seizure lasting five minutes or more, or two or more seizures without recovery, and this patient has had three seizures in 90 minutes with no return of consciousness between them, which meets the definition directly (`L4) Seizures_Epilepsy`). The same lecture lists having no chronic AED treatment among the causes it teaches for acute symptomatic seizures, which fits the friend\'s advice to stop phenytoin and carbamazepine outright.\n\nA single generalized tonic-clonic seizure (option b) would not explain three attacks with no recovery of consciousness between them. Epileptic encephalopathy (option c) describes a chronic syndrome in which the epileptiform activity itself impairs development or cognition, not an acute emergency like this one. Convulsive syncope (option d) is a brief myoclonic jerk during a faint from global cerebral hypoperfusion, not a sustained series of generalized convulsions with impaired consciousness.\n\nThe lecture\'s status-epilepticus definition has two independent routes to the same diagnosis — a single seizure lasting five minutes or more, *or* repeated seizures without recovery in between — and this patient satisfies the second route explicitly, since three seizures in 90 minutes with no return of consciousness is by definition "without recovery", regardless of how long any one convulsion itself lasted (`L4) Seizures_Epilepsy`). The lecture also flags that status epilepticus carries a real risk of permanent neuronal injury once it passes 30 minutes, which is what makes the precipitant — and the drug protocol that follows in Q147 — urgent rather than incidental detail. On the precipitant itself, the lecture\'s treatment framework distinguishes provoked from unprovoked seizures and lists "no chronic AED treatment" among the causes of an acute symptomatic seizure in a patient who already has epilepsy; stopping two established antiepileptics — phenytoin and carbamazepine — outright for an unproven herbal remedy is exactly that provoking event, and it explains why a "poorly controlled" epileptic decompensates into status on this particular day rather than any other.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'Repeated generalized seizures without recovery of consciousness between them is status epilepticus by definition; abrupt AED withdrawal is a recognised precipitant.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.31 (answer p.35). The bank prints "poorly controlled on phenytoin and carbamazepine. yesterday The patient visited"; capitalisation and punctuation normalised to read "...carbamazepine. Yesterday, the patient visited...".'
},

{
  id:'npqb-nr-147', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'In previous case, what is the first-line pharmacological treatment you should administer to this patient?',
  options:['IV diazepam 10–20 mg','IV lorazepam 10 mg','IV diazepam 0.3 mg/kg','IV phenytoin 0.1 mg/kg'],
  answer:0,
  explanation:'**This continues `npqb-nr-146`\'s patient — the 20-year-old man who stopped his phenytoin and carbamazepine for herbal treatment and reached status epilepticus — and IV diazepam is the first-line drug the course lecture\'s own protocol names.** Its status-epilepticus timeline runs airway, breathing and circulation first, then IV diazepam at the 5-10 minute mark, then IV phenytoin from 10-30 minutes if seizures continue (`L4) Seizures_Epilepsy`). This entry is the pharmacological step that immediately follows the diagnosis reached in the previous case: Q146 established the diagnosis, Q147 asks the next action, and neither question answers itself.\n\nIV lorazepam (option b) is a genuine alternative benzodiazepine used in status epilepticus in wider practice, but it is not the drug this lecture names first. The two remaining options misstate the correct drugs\' own dosing: "IV diazepam 0.3 mg/kg" (option c) inflates the lecture\'s own paediatric-range dose beyond what an adult status protocol calls for, and "IV phenytoin 0.1 mg/kg" (option d) is both the wrong drug for this step and far below phenytoin\'s actual loading dose, which the lecture gives as 18-20 mg/kg.\n\nThe lecture\'s adult diazepam dose is 10 mg given over 15 seconds, which is what option a states; its paediatric dose is 0.1-0.3 mg/kg, the range option c misapplies to an adult (`L4) Seizures_Epilepsy`). If seizures persist past 10 minutes despite diazepam, the lecture\'s own next step is IV phenytoin 1000 mg in adults (18-20 mg/kg in children) infused slowly over about 20 minutes, or IV levetiracetam 3000 mg if phenytoin is unavailable — the step this patient has not yet reached at the point Q147 asks its question. Only the IV route is used for any of these drugs during active convulsive status; oral or intramuscular dosing is reserved for when IV access cannot be obtained, using rectal diazepam or IM midazolam instead.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'IV diazepam is the first pharmacological step in status epilepticus, given after the initial airway, breathing and circulation phase; IV phenytoin follows if seizures continue.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.32 (answer p.36).'
},

{
  id:'npqb-nr-148', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'Which of the following is true regarding febrile convulsions?',
  options:['Epilepsy, not seizures','Seizures, not epilepsy','Always a sign of underlying brain pathology'],
  answer:1,
  explanation:'**Febrile convulsions are seizures, not epilepsy, and the course lecture\'s own definitions make exactly this distinction.** It defines a provoked, acute symptomatic seizure as one occurring in close temporal relationship with a systemic insult such as fever, and states plainly that these do not constitute epilepsy (`L4) Seizures_Epilepsy`). Epilepsy itself requires an enduring predisposition to unprovoked seizures; a convulsion tied to a febrile illness in an otherwise normal child is the provoked event the lecture is describing, and it does not, on its own, earn the diagnosis of epilepsy.\n\nOption a inverts the correct relationship. Option c is also wrong: the great majority of simple febrile convulsions occur in neurologically normal children and carry no evidence of structural brain disease; only atypical, complex febrile seizures — prolonged, focal, or recurrent within the same illness — raise that concern, and even then investigation is what confirms or excludes pathology rather than the seizure itself proving it *(the simple-versus-complex distinction is not taken from the course material)*. The lecture\'s own broader point about provoked seizures generalises directly to this question: seizures occurring in close temporal relationship with a systemic insult such as fever do not, on their own, earn the label of epilepsy, no matter how alarming a single febrile convulsion looks to a parent (`L4) Seizures_Epilepsy`). The distinction matters practically because a child with simple febrile convulsions is managed by treating the fever and reassuring the family, not by starting long-term antiepileptic therapy, which is reserved for a genuinely unprovoked, recurrent seizure disorder.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'A febrile convulsion is a provoked seizure, not epilepsy, and simple febrile seizures do not by themselves indicate underlying brain pathology.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.32 (answer p.36). Prints only three options.'
},

{
  id:'npqb-nr-149', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'A 5-year-old child presents with complaints of recurrent episodes of lapse of consciousness. During these episodes, the child freezes, has periods of staring, and blinks repeatedly. The episodes last for a few seconds and occur every 10 minutes, with the child being unaware of the event. The mother has noticed that the child does not respond during these episodes but quickly returns to baseline afterwards, with no confusion. What is the most likely diagnosis?',
  options:['Absence epilepsy','Temporal lobe epilepsy','Tonic-clonic seizures','Hypoglycemic episode'],
  answer:0,
  explanation:'**This is textbook childhood absence epilepsy, and it matches the course lecture\'s own worked case almost feature for feature.** The lecture\'s first case, a seven-year-old with staring spells, brief eye-rolling, no post-ictal confusion, and no injury or incontinence, is diagnosed there as childhood absence epilepsy (`L4) Seizures_Epilepsy`); this vignette\'s freezing, staring, repetitive blinking, few-second duration, frequent recurrence and prompt return to baseline with no confusion is the same clinical picture. Absence seizures characteristically have no post-ictal phase, which is exactly what separates them from every other option here.\n\nTemporal lobe epilepsy (option b) typically produces focal impaired-awareness seizures with automatisms and post-ictal confusion lasting minutes, not the abrupt clean return to baseline described here. Tonic-clonic seizures (option c) involve convulsive movements and a genuine post-ictal period, neither of which this child has. A hypoglycemic episode (option d) would not resolve this quickly, this repeatedly, or this cleanly, and would typically show autonomic and adrenergic symptoms rather than staring alone *(this last comparison is not taken from the course material)*.\n\nThe lecture\'s own case, Mariam, is a seven-year-old with staring spells 50-100 times a day lasting 5-10 seconds each, eyes rolling up briefly, no post-ictal confusion and no injury or incontinence — confirmed as childhood absence epilepsy by a 3 Hz spike-wave EEG and a normal MRI (`L4) Seizures_Epilepsy`). This child\'s "every 10 minutes" frequency, freezing with repetitive blinking, and prompt clean return to baseline are the same picture in miniature, and the lecture is explicit that all generalized seizures involve complete loss of consciousness except myoclonic and atonic — absence seizures are on the complete-loss side of that rule, which is why the child is fully unresponsive during the spell despite it lasting only seconds. The lecture\'s bottom-line teaching point for this exact case — never use carbamazepine or phenytoin in absence seizures, because they can worsen them — is worth carrying into the two questions that follow, which continue this same case.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'Brief staring spells with automatisms, no post-ictal confusion, and frequent recurrence in a young child is the classic presentation of childhood absence epilepsy.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.32 (answer p.36).'
},

{
  id:'npqb-nr-150', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'In previous case, what investigation would you order to confirm the diagnosis?',
  options:['EEG','Brain MRI','Blood glucose','Head CT scan'],
  answer:0,
  explanation:'**Continuing the child from `npqb-nr-149` — the 5-year-old with brief staring-and-blinking spells every ten minutes and no post-ictal confusion, diagnosed there with absence epilepsy — EEG is the confirmatory test, and the course lecture names the exact signature to look for.** It lists generalized spike-wave activity as the EEG signature of absence epilepsy, and its own worked case is confirmed with a 3 Hz spike-wave EEG and a normal MRI (`L4) Seizures_Epilepsy`). The classic 3 Hz generalized spike-and-wave discharge is specific enough to confirm absence epilepsy once the clinical picture already points that way, and the back-reference is clean: Q149 reached the diagnosis, Q150 asks how it is confirmed, and the two do not answer each other in a circular way.\n\nBrain MRI (option b) looks for a structural cause and is typically normal in idiopathic, genetic absence epilepsy, as it was in the lecture\'s own case; it does not confirm the electroclinical diagnosis. Blood glucose (option c) screens for a provoked, hypoglycemic cause, which this child\'s stereotyped, effort-free, recurrent episodes do not suggest. A head CT scan (option d) adds nothing over MRI for this indication and is not part of the routine absence work-up.\n\nThe lecture lists generalized spike-wave discharge among its named EEG signatures, distinct from the focal spikes of a localized epileptogenic cortex, the polyspike-wave of juvenile myoclonic epilepsy, or the hypsarrhythmia of severe infantile epilepsy — each pattern points to a different seizure category, and 3 Hz generalized spike-wave points specifically to absence (`L4) Seizures_Epilepsy`). The lecture treats EEG as diagnosis-supporting rather than diagnosis-making in general, but for a syndrome defined electroclinically like absence epilepsy, a normal MRI paired with this characteristic discharge is what turns a strong clinical suspicion into a confirmed syndrome, which is precisely the sequence its own worked case follows.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'EEG showing 3 Hz generalized spike-and-wave discharge confirms childhood absence epilepsy; MRI is typically normal because the disorder is idiopathic.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.32 (answer p.36).'
},

{
  id:'npqb-nr-151', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'What is the first-line treatment in this patient?',
  options:['Valproate','Ethosuximide','Carbamazepine','Lamotrigine'],
  answer:1,
  explanation:'**Continuing the child from `npqb-nr-149` and `npqb-nr-150` — whose staring-and-blinking spells were confirmed as absence epilepsy on EEG — ethosuximide is first-line, exactly as the course lecture\'s AED table gives it for pure absence seizures.** The table names ethosuximide as the first choice for absence, with valproate as an alternative, and separately gives the same two drugs for its own worked case (`L4) Seizures_Epilepsy`). Because this child\'s picture is pure absence with no coexisting generalized tonic-clonic seizures, ethosuximide is preferred over valproate, which becomes the first choice instead when tonic-clonic seizures coexist — as in Q142 — because it, unlike ethosuximide, also covers the convulsive seizure type. This entry is an implicit continuation of the Q149-Q150 case rather than an explicit "In previous case" wording, and it is consistent with both without answering either of them.\n\nValproate (option a) is a genuine alternative but not the first choice for pure absence seizures once ethosuximide is on the list. Carbamazepine (option c) is explicitly marked never to be used for absence seizures in the lecture\'s own table because sodium-channel blockers can worsen them. Lamotrigine (option d) is listed as second-line for absence, used chiefly when valproate is contraindicated.\n\nThe lecture\'s own case gives concrete dosing for both first-line agents — ethosuximide 15-20 mg/kg/day or sodium valproate 15-20 mg/kg/day — which is the level of detail this bank favours across the absence questions in this topic (`L4) Seizures_Epilepsy`). The reason ethosuximide is preferred by name over valproate whenever both would work is that ethosuximide has no other seizure-type coverage and correspondingly a narrower, more tolerable side-effect profile for a drug given purely to suppress 3 Hz spike-wave discharges, whereas valproate\'s broader spectrum is only needed once a second seizure type is in the picture, as it was for the mixed absence-and-tonic-clonic patient in Q142.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'Ethosuximide is first-line for pure childhood absence epilepsy; valproate is preferred instead only when generalized tonic-clonic seizures coexist, and carbamazepine must never be used.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.32 (answer p.36).'
},

{
  id:'npqb-nr-152', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'A patient has received trauma to the head and immediately develops a seizure after the injury. What type of seizure is this?',
  options:['Provoked seizure','Unprovoked seizure','Secondary epilepsy','Status epilepticus'],
  answer:0,
  explanation:'**A seizure occurring in close temporal relationship with head trauma is a provoked, acute symptomatic seizure, and the course lecture names trauma as exactly this kind of trigger.** It defines provoked seizures as those occurring in close temporal relationship with a systemic insult such as fever, a metabolic shift, or trauma, and states that these do not constitute epilepsy (`L4) Seizures_Epilepsy`).\n\nUnprovoked seizure (option b) is the opposite category — one with no identifiable acute trigger, which is what counts toward a diagnosis of epilepsy after a second occurrence. Secondary epilepsy (option c) is not the correct term for a single immediate post-traumatic seizure; epilepsy requires an enduring predisposition to recurrent unprovoked seizures, which a single acute event immediately after trauma does not establish. Status epilepticus (option d) describes a seizure lasting five minutes or more, or repeated seizures without recovery, a duration-and-repetition criterion this single brief seizure does not meet.\n\nThe lecture makes the same point with its own neonatal case, teaching that neonatal seizures in particular are "provoked until proven otherwise" and that the correct approach is to find the cause and treat it, after which the seizures often resolve without the child ever earning a diagnosis of epilepsy (`L4) Seizures_Epilepsy`). The same logic applies to this adult: a seizure immediately after trauma prompts treatment of the head injury, not a lifelong antiepileptic, and it is only a second seizure occurring later without an acute provoking insult that would begin to raise the question of epilepsy.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'A seizure occurring immediately after an acute insult such as head trauma is a provoked seizure, not epilepsy; epilepsy requires unprovoked, recurrent seizures.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.32 (answer p.36).'
},

{
  id:'npqb-nr-153', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'A patient present with status epilepticus. What is the most appropriate drug to treat this condition initially?',
  options:['IM diazepam','IV diazepam','Thiopental','Oral phenytoin'],
  answer:1,
  explanation:'**IV diazepam is the initial drug, exactly as the course lecture\'s status-epilepticus protocol gives it: airway, breathing and circulation first, then diazepam by the IV route at the 5-10 minute mark** (`L4) Seizures_Epilepsy`). The same lecture states the route rule directly: only the IV route is used in convulsive status, and neither the oral nor the intramuscular route is used during active convulsions, unless there is no IV access, in which case rectal diazepam or IM midazolam are the stated fallbacks.\n\nThat rule disposes of both distractors sharing diazepam\'s name or class: IM diazepam (option a) is explicitly excluded as a route in active convulsive status because intramuscular absorption is too slow and erratic for an emergency. Oral phenytoin (option d) fails the same route rule and is also the wrong drug for this stage — the lecture\'s protocol gives IV phenytoin only later, at 10-30 minutes, once diazepam has been given. Thiopental (option c) belongs to the refractory stage, past 30 minutes, when an anaesthetic infusion and ICU admission are needed, rather than to the initial step. The lecture\'s own adult dose for this initial step is IV diazepam 10 mg given over 15 seconds, distinct from the 0.1-0.3 mg/kg paediatric dosing (`L4) Seizures_Epilepsy`), and it is worth remembering that "initially" in this question maps onto the lecture\'s 5-10 minute window, which only opens once the 0-5 minute airway-breathing-circulation, oxygen, IV access, glucose and ECG bundle is already under way.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'The initial drug treatment of status epilepticus is IV diazepam; oral and intramuscular routes are excluded during active convulsions, and thiopental is reserved for the refractory stage.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.32 (answer p.36).'
},

{
  id:'npqb-nr-154', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'Treatment of status epilepticus includes intravenous injection of all of the following EXCEPT:',
  options:['Carbamazepine','Phenytoin','Phenobarbitone','Diazepam','Lorazepam'],
  answer:0,
  explanation:'**Carbamazepine is the exception because it has no intravenous formulation in routine use, unlike the other four drugs.** The course lecture\'s own status-epilepticus protocol names IV diazepam and IV phenytoin explicitly as sequential steps (`L4) Seizures_Epilepsy`); it does not itself enumerate phenobarbitone or lorazepam by name, but both are standard parenteral drugs used in status epilepticus in wider clinical practice — phenobarbitone as an alternative or add-on loading agent, and lorazepam as an alternative first-line benzodiazepine to diazepam *(this detail is not taken from the course material)*.\n\nCarbamazepine, by contrast, is formulated for oral use; it has no established IV role in acute seizure emergencies, which is precisely why it is singled out here as the exception rather than treated as interchangeable with the other four. This is also why carbamazepine plays no part anywhere in the lecture\'s own status-epilepticus timeline — its place in the lecture\'s AED table is as an oral, chronic, first-line drug for focal seizures, a maintenance role that has nothing to do with terminating an ongoing convulsion (`L4) Seizures_Epilepsy`). The distinction the question is really testing is formulation, not efficacy: several oral-only antiepileptics are excellent chronic drugs yet cannot be reached for in an emergency precisely because no parenteral form exists. Phenytoin makes the point sharpest by contrast — it shares carbamazepine\'s sodium-channel-blocking mechanism and its role as a focal-seizure drug, yet it has a genuine IV formulation with the lecture\'s own loading dose of 1000 mg in adults (18-20 mg/kg in children), which is exactly why phenytoin appears in the status protocol at 10-30 minutes while carbamazepine never does (`L4) Seizures_Epilepsy`).\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'Diazepam, phenytoin, phenobarbitone and lorazepam are all given intravenously in status epilepticus; carbamazepine is an oral-only drug with no established IV role in the emergency.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.32 (answer p.36).'
},

{
  id:'npqb-nr-155', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'A father presents to the ER with his son, who has been experiencing generalized tonic-clonic seizures for the past 40 minutes. The child has a history of epilepsy and has missed the past 3 doses of his antiepileptic drug. The boy is cyanosed. What is the most important complication to check for now?',
  options:['Hypoxia','Hyperglycemia','Brain edema','Hypotension'],
  answer:0,
  explanation:'**Cyanosis during a prolonged convulsive seizure is the clinical sign of hypoxia, and it is the complication the course lecture\'s own first management step is built to catch.** The status-epilepticus protocol opens with airway, breathing and circulation, oxygen, IV access, a glucose check and an ECG, all before any drug is given (`L4) Seizures_Epilepsy`), because a seizure lasting 40 minutes — well past the five-minute definition of status epilepticus — impairs ventilation and airway protection throughout, and cyanosis is the visible marker that oxygenation has already failed.\n\nHyperglycemia (option b) is not a recognised complication of a convulsive seizure; if anything, prolonged muscular activity and poor intake push glucose the other way. Brain edema (option c) can follow prolonged status epilepticus from sustained neuronal injury, but it is a later, less immediately actionable concern than the airway and oxygenation problem signalled by cyanosis right now. Hypotension (option d) is not the sign this vignette describes; cyanosis points specifically to oxygenation failure, not to a circulatory one.\n\nThe lecture\'s own seizure-versus-syncope teaching reinforces why cyanosis is expected here rather than being an alarming outlier: true seizures are typically flushed or cyanosed, in direct contrast to the pallor of syncope, because a tonic-clonic convulsion drives sustained muscular contraction against a chest wall that cannot ventilate normally, while syncope\'s pallor comes from the falling blood pressure that caused the faint in the first place (`L4) Seizures_Epilepsy`). This boy\'s picture also meets status epilepticus by duration alone — 40 minutes is far past the five-minute definition — and the lecture\'s own timeline puts a seizure of this length well into the window where permanent neuronal injury becomes a risk, which is exactly why the airway and oxygenation check is not a formality but the step that determines whether the brain is still being perfused with oxygenated blood while the drug protocol proceeds. The missed AED doses noted in the history are the same acute-symptomatic precipitant seen in Q146\'s adult case, underlining that this is a recognised, not an incidental, way for a known epileptic to decompensate into status.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'Cyanosis in a prolonged convulsive seizure signals hypoxia, and airway, breathing and oxygenation are checked before any anticonvulsant is given.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.33 (answer p.36). The bank prints "The boy is cyanosed What is the most important complication" as a run-on; a full stop is inserted after "cyanosed".'
},

{
  id:'npqb-nr-156', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'In previous case, which of the following will be given via IV route?',
  options:['Diazepam','Phenytoin','Phenobarbital','The missed dose of the antiepileptic drug'],
  answer:0,
  explanation:'**Continuing the boy from `npqb-nr-155` — the cyanosed child with a 40-minute convulsion after missing three antiepileptic doses, in whom hypoxia was the complication to check for — diazepam is the drug given via IV route at this step, matching the course lecture\'s own protocol order** — airway, breathing and circulation first, then IV diazepam at 5-10 minutes (`L4) Seizures_Epilepsy`), with IV phenytoin reserved for the following stage if seizures persist. The back-reference is clean: Q155 identified hypoxia as the complication to check for, Q156 asks the next drug step, and the question does not answer itself.\n\nPhenytoin (option b) is a genuine IV status-epilepticus drug, but it belongs to the next step in the sequence, not this one — it is wrong only because the question asks what comes first. Phenobarbital (option c) is not the lecture\'s named first step either. The missed dose of the antiepileptic drug (option d) is a distractor built from the vignette\'s own detail about non-compliance, but simply restarting his usual oral maintenance drug does nothing to abort a seizure already in progress and is not given by the IV route in an emergency. Even if it were given, phenytoin\'s own oral absorption is too slow to abort an ongoing 40-minute convulsion, which is exactly why the lecture reserves the IV, not the oral, formulation for status epilepticus (`L4) Seizures_Epilepsy`). The lecture\'s own adult diazepam dose at this step is 10 mg IV over 15 seconds, the same figure that answers Q147 and Q153 for their own patients — the drug and dose do not change between vignettes, only the surrounding clinical picture does.\n\nWritten for this bank — neuropsychiatry & neurosurgery qb.pdf prints no explanation here.',
  objective:'IV diazepam is the drug given at this step of status epilepticus management, ahead of IV phenytoin; simply restarting the patient\'s usual oral antiepileptic does not abort an ongoing seizure.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.33 (answer p.36).'
},

{
  id:'npqb-nr-157', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'In previous case, what is the first lab investigation to perform?',
  options:['Random blood sugar','Na-K levels','Drug blood concentration','Urea and creatinine'],
  answer:0,
  explanation:'Continuing `npqb-nr-155` and `npqb-nr-156` — the cyanosed boy with a 40-minute convulsion after missing three antiepileptic doses, already given IV diazepam.\n\n**The bank prints an explanation box for this question, transcribed here verbatim:**\n\n> Random blood sugar is the first lab test to perform in a patient with status epilepticus to rule out hypoglycemia (a common cause of seizures) and metabolic disturbances that may precipitate or worsen seizure activity\n\nThis matches the course lecture\'s own first management step for status epilepticus, which lists a glucose check alongside airway, breathing, circulation, IV access and ECG in the very first five minutes, before any anticonvulsant is given (`L4) Seizures_Epilepsy`). Continuing the boy from Q155-156, a rapid bedside glucose is checked immediately because hypoglycemia is both a readily reversible cause of ongoing seizures and immediately correctable — a delay to obtain sodium and potassium levels, drug levels, or renal function costs time against a treatable cause that a finger-prick glucose answers at once. The chain from Q155 through Q157 is sequential and none of the three answers itself.\n\nNa-K levels (option b) matter in this workup too — the lecture separately lists hyponatremia among the causes it teaches for a provoked seizure — but glucose is checked first because point-of-care testing gives an answer in seconds where electrolytes require the lab to turn the sample around. Drug blood concentration (option c) would be relevant to confirm whether this particular boy\'s missed doses have left a subtherapeutic phenytoin or carbamazepine level, but that result changes management later, not in the first minutes. Urea and creatinine (option d) screen for a metabolic contributor over a longer time frame and carry no urgency to match a reversible hypoglycaemic cause.',
  objective:'A bedside random blood glucose is the first laboratory step in status epilepticus, taken alongside airway, breathing and circulation, to rule out a rapidly reversible hypoglycaemic cause.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.33 (answer p.36, explanation box printed).'
},

{
  id:'npqb-nr-158', bank:'gradegain', module:'neuropsych', chapter:'nr-epilepsy',
  stem:'Pallor is commonly found in:',
  options:['Focal motor seizures with retained consciousness','Syncope','Absence seizures','Generalized tonic-clonic seizures'],
  answer:1,
  explanation:'**The bank prints an explanation box for this question, transcribed here verbatim:**\n\n> Pallor is commonly seen in syncope because it is often related to a sudden drop in blood pressure\n\nThe course lecture\'s own collapse-differential table draws the same skin-colour contrast directly: true seizures are flushed or cyanosed, while syncope is pale (`L4) Seizures_Epilepsy`), because syncope is a transient loss of consciousness from global cerebral hypoperfusion — the same falling blood pressure that produces the pallor also causes the faint. A seizure, by contrast, is a hyperexcitable electrical event that typically flushes or cyanoses the patient rather than draining colour from the skin.\n\nFocal motor seizures with retained consciousness (option a), absence seizures (option c), and generalized tonic-clonic seizures (option d) are not associated with pallor as a defining feature in the lecture\'s own table; the tonic-clonic seizure, in particular, is the one most often cyanosed rather than pale.\n\nThis skin-colour contrast is one leg of a wider checklist the lecture builds for exactly this discrimination: syncope also brings flaccid muscle tone (against a seizure\'s tonic rigidity or rhythmic jerking), a lightheadedness-tunnel-vision-sweating prodrome (against a seizure\'s aura of foul smells or deja-vu), and a very rapid recovery of full orientation (against a seizure\'s post-ictal confusion or Todd\'s paralysis) (`L4) Seizures_Epilepsy`). Cyanosis during status epilepticus in Q155 and pallor in syncope here are therefore two ends of the same clinical sign, both driven by the underlying haemodynamics — sustained convulsive muscular work impairing ventilation in one case, and falling cerebral perfusion pressure in the other.',
  objective:'Pallor is the skin sign of syncope, driven by the same hypotension that causes the faint; seizures more typically flush or cyanose the patient.',
  source:'neuropsychiatry & neurosurgery qb.pdf p.33 (answer p.36, explanation box printed). Option d prints "Generalized tonic colonic seizures"; corrected here to Generalized tonic-clonic seizures.'
}
