/*
 * "Neuro endpoint.pdf" - Model Final Exam 5: 43 pairs read, 24 folded as duplicates of
 * already-spliced material (13 exact, 3 REORDERED, 1 respelled cross-bank, 1 reworded/
 * dropped-filler-option, 4 near-exact with OCR typos treated as exact, 2 from the book's
 * duplicate-numbering-42 defect) — source notes appended to the 24 survivors in
 * app/data/questions.neuro.js. 19 genuinely new rows remain here for splice.
 */

{ id:'npep-fe5-19', bank:'endpoint', module:'neuropsych', chapter:'nr-stroke',
  stem:'What is the first line of treatment for aneurysmal subarachnoid hemorrhage?',
  options:['Induction of hypertension.', 'Surgical clipping of the aneurysm', 'Hemoconcentration', 'Antiplatelet agents'],
  answer:1,
  explanation:'Surgical clipping of the aneurysm is the printed first-line treatment because it definitively secures the ruptured aneurysm and prevents recurrent bleeding. In contemporary practice, aneurysm occlusion may be achieved by microsurgical clipping or endovascular coiling depending on aneurysm anatomy, patient factors, and local expertise (not taken from the course material). The key point tested is early definitive exclusion of the bleeding aneurysm from the circulation.\n\nInduction of hypertension is not the initial treatment for an unsecured ruptured aneurysm, because raising blood pressure can increase the risk of rebleeding. Induced hypertension may be used selectively for delayed cerebral ischemia from vasospasm after the aneurysm has been secured and after other measures are considered (not taken from the course material). Hemoconcentration is not first-line treatment; it was historically associated with hypervolemic, hypertensive, hemodilution-related approaches to vasospasm, but it does not secure the aneurysm and is not routine contemporary management (not taken from the course material). Antiplatelet agents are inappropriate as first-line therapy for aneurysmal subarachnoid hemorrhage because they can worsen bleeding risk and do not treat the ruptured aneurysm. Initial supportive care, blood-pressure management, nimodipine, and treatment of complications are also important, but they do not replace urgent aneurysm-securing treatment (not taken from the course material). Written for this bank — the endpoint file prints no explanation here.',
  objective:'A ruptured aneurysm causing subarachnoid hemorrhage requires definitive aneurysm securing by surgical clipping.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q19, p.2044 (answer p.2045)'
},

{ id:'npep-fe5-21', bank:'endpoint', module:'neuropsych', chapter:'nr-backpain',
  stem:'What is the presentation of far lateral L3-L4 disc prolapse?',
  options:['Positive reversed straight leg raising test.', 'Sensory loss of little toe', 'Knee clonus', 'Weakness of planter flexors'],
  answer:0,
  explanation:'The printed key is option a, Positive reversed straight leg raising test. A far lateral L3-L4 disc prolapse compresses the exiting L3 nerve root rather than the traversing L4 root (not taken from the course material). The reversed straight leg raising test, also called the femoral nerve stretch test, is used to provoke upper lumbar radicular pain and may be positive with L2, L3, or L4 root irritation (not taken from the course material). This therefore fits the expected presentation of a far lateral L3-L4 lesion.\n\nOption b, sensory loss of little toe, is wrong because sensation over the little toe is principally associated with the S1 dermatome (not taken from the course material), not L3 radiculopathy. Option c, knee clonus, is wrong because clonus is an upper motor neuron sign related to corticospinal tract dysfunction (not taken from the course material); a lumbar root compression causes lower motor neuron-pattern radicular findings instead. Option d, weakness of planter flexors, is wrong because plantar flexion is mainly supplied by S1 through the tibial nerve (not taken from the course material). L3 involvement more typically affects functions such as knee extension through the quadriceps, with possible anterior-thigh sensory symptoms (not taken from the course material). The bank’s marked answer is therefore the reversed straight leg raising test.\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Identify the clinical presentation of a far lateral L3-L4 disc prolapse.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q21, p.2048 (answer p.2049)'
},

{ id:'npep-fe5-22', bank:'endpoint', module:'neuropsych', chapter:'nr-coma',
  stem:'What is the characteristic of moderate traumatic brain injury?',
  options:['Glasgow Coma Score more than 13', 'Focal neurological deficits', 'Manifestations of post-concussion', 'Brain herniation.'],
  answer:3,
  explanation:'The printed key is Brain herniation. Moderate traumatic brain injury is generally classified by an initial Glasgow Coma Scale score of 9–12, whereas severe injury may cause raised intracranial pressure, mass effect, and eventual brain herniation. (not taken from the course material) The bank has printed brain herniation as the characteristic option, so it remains the key for this question.\n\nGlasgow Coma Score more than 13 is not the usual definition of moderate traumatic brain injury; scores of 13–15 are generally classified as mild traumatic brain injury. (not taken from the course material) Focal neurological deficits can occur after traumatic brain injury when there is a localized lesion, such as contusion or intracranial hemorrhage, but they are not the defining characteristic of moderate injury. (not taken from the course material) Manifestations of post-concussion are more often associated with concussion or mild traumatic brain injury and may include headache, dizziness, cognitive symptoms, and sleep disturbance. (not taken from the course material) Brain herniation is a dangerous complication caused by markedly increased intracranial pressure and is generally associated with severe brain injury rather than moderate injury. (not taken from the course material) Thus, although general teaching would not usually identify herniation as a defining feature of moderate traumatic brain injury, the endpoint file visibly prints option d as correct.\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Identify the bank-keyed characteristic of moderate traumatic brain injury.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q22, p.2050 (answer p.2051)'
},

{ id:'npep-fe5-31', bank:'endpoint', module:'neuropsych', chapter:'nr-nerve',
  stem:'What is the most common cause of entrapment neuropathy?',
  options:['Ulnar neuropathy at the cubital fossa', 'Entrapment of the lateral cutaneous nerve of the thigh', 'Carpal tunnel syndrome', 'Radial nerve entrapment at the spiral groove'],
  answer:2,
  explanation:'Carpal tunnel syndrome is the printed correct answer. It is caused by compression of the median nerve as it passes through the carpal tunnel at the wrist and is generally taught to be the most common entrapment neuropathy (not taken from the course material). Typical symptoms include numbness, tingling, or pain in the thumb, index finger, middle finger, and radial half of the ring finger, sometimes with thenar weakness in more advanced cases (not taken from the course material).\n\nUlnar neuropathy at the cubital fossa is not the best answer because, although compression around the elbow is a common upper-limb entrapment neuropathy, it is less common overall than carpal tunnel syndrome (not taken from the course material). Entrapment of the lateral cutaneous nerve of the thigh produces meralgia paraesthetica, with sensory symptoms over the outer thigh (not taken from the course material). It is a focal sensory nerve entrapment, but it is not generally the most common entrapment neuropathy. Radial nerve entrapment at the spiral groove can cause radial neuropathy and wrist drop, often after sustained external compression or humeral injury (not taken from the course material). This is also less common than median nerve compression in the carpal tunnel.\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Identify carpal tunnel syndrome as the most common entrapment neuropathy.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q31, p.2063 (answer p.2064)'
},

{ id:'npep-fe5-32', bank:'endpoint', module:'neuropsych', chapter:'nr-nerve',
  stem:'A 38-year-old patient was subjected to a stab wound in the proximal forearm of the right upper limb. On examination, the patient cannot bring the distal phalanx of the thumb and index finger together. Which nerve is injured in this patient?',
  options:['Radial', 'Posterior interosseous', 'Anterior interosseous.', 'ulnar'],
  answer:2,
  explanation:'The printed key is Anterior interosseous. Injury to the anterior interosseous nerve produces weakness of flexor pollicis longus and the radial half of flexor digitorum profundus, including the tendon flexing the distal phalanx of the index finger (not taken from the course material). Consequently, the patient cannot flex the thumb interphalangeal joint and index distal interphalangeal joint sufficiently to bring their distal phalanges together, producing an abnormal pinch or “OK” sign (not taken from the course material). This branch arises in the proximal forearm, fitting the site of the stab wound (not taken from the course material).\n\nRadial nerve injury would mainly impair extension at the wrist, fingers, and thumb, classically causing wrist drop when the lesion is proximal enough (not taken from the course material). It does not selectively account for loss of flexion of the thumb and index distal phalanges. Posterior interosseous nerve injury is a motor branch of the radial nerve and chiefly causes weakness of finger and thumb extension; wrist extension may be relatively preserved (not taken from the course material). It therefore does not explain the described pinch deficit. Ulnar nerve injury affects many intrinsic hand muscles and may impair finger abduction and adduction, with characteristic clawing in some lesions (not taken from the course material), but it does not cause this specific loss of flexion of the thumb and index distal phalanges.\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Identify anterior interosseous nerve injury from inability to bring the distal phalanges of the thumb and index finger together.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q32, p.2065 (answer p.2066)'
},

{ id:'npep-fe5-33', bank:'endpoint', module:'neuropsych', chapter:'nr-cranial',
  stem:'A 35-year female patient presented with absent menstruation and milky nipple discharge. Her prolactin level was 2000 ng/dl (normal value is less than 20 ng\\dl). her visual examination showed normal vision field and acuity. Her MRI brain showed seller space occupying lesion. What is the best management plan for this patient?',
  options:['Endonasal endoscopic transsphenoidal excision', 'Gama knife radiosurgery', 'Sub frontal craniotomy for tumor removal', 'Dopamine agonist medical care and observation'],
  answer:3,
  explanation:'The bank keys dopamine agonist medical care and observation. The combination of amenorrhea, galactorrhea, markedly elevated prolactin, and a sellar space-occupying lesion is consistent with a prolactin-secreting pituitary adenoma (not taken from the course material). Dopamine agonists, such as cabergoline or bromocriptine, are generally first-line treatment because they lower prolactin concentrations, restore gonadal function, and commonly reduce tumour size (not taken from the course material). Her visual fields and acuity are normal, so the question does not describe visual compromise needing urgent decompression (not taken from the course material). Observation includes clinical, hormonal, visual, and MRI follow-up (not taken from the course material).\n\nEndonasal endoscopic transsphenoidal excision is not the initial usual choice for this presentation because surgery is generally reserved for medication resistance or intolerance, apoplexy, cerebrospinal-fluid leak, or threatening visual/neurological compression (not taken from the course material). Gamma knife radiosurgery is not first-line because its hormonal effect is delayed and it is usually considered for persistent or recurrent disease after other management (not taken from the course material). Sub frontal craniotomy for tumor removal is also inappropriate as routine initial management: it is a more invasive approach and is generally reserved for selected lesions not suitably managed by medication or transsphenoidal surgery (not taken from the course material). The visible printed key therefore supports option d.\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Tests first-line management of a prolactin-secreting sellar lesion without visual impairment.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q33, p.2067 (answer p.2068)'
},

{ id:'npep-fe5-34', bank:'endpoint', module:'neuropsych', chapter:'nr-backpain',
  stem:'From this syndrome choose the matching clinical sign Foot drop?',
  options:['L5 root syndrome.', 'Complete cord syndrome', 'Central cord syndrome', 'S1 root syndrome', 'Brown-Séquard syndrome'],
  answer:0,
  explanation:'Foot drop is the matching sign for L5 root syndrome. The L5 root contributes importantly to ankle and great-toe dorsiflexion; weakness of these movements can make the forefoot drag during walking. (not taken from the course material) L5 radiculopathy may also produce sensory symptoms over the lateral leg and dorsum of the foot. (not taken from the course material)\n\nComplete cord syndrome causes loss of motor, sensory and autonomic function below the level of a complete spinal cord lesion, rather than an isolated foot-drop pattern. (not taken from the course material) Central cord syndrome classically produces motor weakness more marked in the upper limbs than the lower limbs, often after cervical hyperextension injury, so it is not the best match. (not taken from the course material) S1 root syndrome more typically affects plantar flexion and may reduce the ankle jerk; it is not the usual root lesion for dorsiflexion weakness causing foot drop. (not taken from the course material) Brown-Séquard syndrome is a spinal cord hemisection pattern with ipsilateral motor and dorsal-column deficits and contralateral pain-and-temperature loss below the lesion, not an isolated L5-pattern foot drop. (not taken from the course material)\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Foot drop is associated with L5 root syndrome.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q34, p.2069 (answer p.2070)'
},

{ id:'npep-fe5-6', bank:'endpoint', module:'neuropsych', chapter:'nr-cranial',
  stem:'In the previous case what is the finding in MRI of this patient that necessitate neurosurgery interference?',
  options:['Vascular loop of artery or vein.', 'Hydrocephalus', 'Brain Herniation', 'Cut injury of nerve'],
  answer:0,
  explanation:'The printed key is option a, “Vascular loop of artery or vein.” This question continues the previous case (Q5), the patient with recurrent seconds-long lancinating facial pain who became refractory to medical treatment and was referred to neurosurgery after MRI — the classic presentation of trigeminal neuralgia. When trigeminal neuralgia fails maximal medical therapy, MRI is used to look for a structural cause, and the most common finding that prompts neurosurgical referral for microvascular decompression is a vascular loop, most often from the superior cerebellar artery, compressing the trigeminal nerve at its root entry zone in the posterior fossa (not taken from the course material). Demonstrating this compression on MRI is what specifically triggers surgical rather than continued medical management.\n\nOption b is wrong because hydrocephalus is enlargement of the ventricular system from impaired CSF circulation; it is not the structural finding linked to trigeminal neuralgia surgery (not taken from the course material).\n\nOption c is wrong because brain herniation is a life-threatening mass-effect emergency, not the incidental structural finding sought on an MRI worked up for refractory facial pain (not taken from the course material).\n\nOption d is wrong because a cut injury of the nerve is a traumatic lesion, not something an MRI would newly reveal in a patient with a several-month history of medically treated facial pain; it also would not typically be treated by referral for compressive decompression surgery (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'MRI showing a vascular loop compressing the trigeminal nerve is the finding that prompts neurosurgical referral in refractory trigeminal neuralgia.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q6, p.2018 (answer p.2019)'
},

{ id:'npep-fe5-8', bank:'endpoint', module:'neuropsych', chapter:'ps-geri',
  stem:'What is/are the main pathophysiological mechanism/s of Alzheimer\'s disease?',
  options:['increased serotonergic and gamma-aminobutyric acid activity', 'Increased activity of the hypothalamic-pituitary-adrenal axis', 'Synthesis of cytokines in the brain', 'Amyloidosis and tau-related neurodegeneration.'],
  answer:3,
  explanation:'The printed key is option d, “Amyloidosis and tau-related neurodegeneration.” Alzheimer\'s disease is characterised pathologically by extracellular deposition of beta-amyloid plaques and intracellular neurofibrillary tangles composed of hyperphosphorylated tau protein, which together drive progressive neuronal and synaptic loss (not taken from the course material). This amyloid-and-tau model is the core pathophysiological mechanism taught for Alzheimer\'s disease.\n\nOption a is wrong because increased serotonergic and gamma-aminobutyric acid activity does not describe Alzheimer\'s pathology; if anything, Alzheimer\'s disease is more classically linked to loss of cholinergic neurons and reduced acetylcholine activity, not increased serotonin or GABA signalling (not taken from the course material).\n\nOption b is wrong because increased hypothalamic-pituitary-adrenal axis activity is a feature discussed in mood and stress-related disorders such as depression, not the defining pathophysiology of Alzheimer\'s disease (not taken from the course material).\n\nOption c is wrong because, although neuroinflammation and cytokine release can accompany Alzheimer\'s disease, cytokine synthesis is a secondary/contributory process rather than the main pathophysiological mechanism taught for the disease; amyloid and tau pathology are the defining processes (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Alzheimer\'s disease pathophysiology is defined by amyloid deposition and tau-related neurodegeneration.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q8, p.2022 (answer p.2023)'
},

{ id:'npep-fe5-9', bank:'endpoint', module:'neuropsych', chapter:'nr-stroke',
  stem:'A patient presented with acute onset aphasia and severe right sided hemiparesis which started on 10:30 am during breakfast. The patient presented to the ER at 04:30 pm. Blood pressure was 150/90 mmHg. CT brain showed normal findings and CT angiography showed occlusion of the left middle cerebral artery. What is the best next step in the management?',
  options:['intravenous thrombolysis combined with mechanical thrombectomy', 'Decompressive craniectomy and surgical removal of the clot', 'Intravenous heparin infusion', 'Mechanical thrombectomy.'],
  answer:3,
  explanation:'The printed key is option d, “Mechanical thrombectomy.” The stroke began at 10:30 am and the patient reached the ER at 04:30 pm, a symptom-to-presentation interval of six hours. Standard intravenous thrombolysis windows are generally taught as up to 4.5 hours from clearly known symptom onset, so this patient falls outside the window for intravenous thrombolysis (not taken from the course material). Mechanical thrombectomy for large-vessel occlusions such as this proximal left middle cerebral artery occlusion has a substantially longer treatment window — up to roughly 6-24 hours in appropriately selected patients — so thrombectomy remains an appropriate next step even though thrombolysis is no longer an option (not taken from the course material). The normal non-contrast CT brain excludes haemorrhage and shows no established large infarct, supporting a patient who can still benefit from endovascular clot retrieval.\n\nOption a is wrong because it requires intravenous thrombolysis, and this patient already presented beyond the standard thrombolysis window (not taken from the course material).\n\nOption b is wrong because decompressive craniectomy is a treatment for malignant, life-threatening cerebral oedema/mass effect after a completed large infarct, not the immediate next step for a patient who still has a salvageable large-vessel occlusion and normal CT brain (not taken from the course material).\n\nOption c is wrong because intravenous heparin is not standard acute management of an ischaemic stroke from large-vessel occlusion and does not address the mechanical clot causing the occlusion (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'A large-vessel ischaemic stroke presenting outside the thrombolysis window but within the endovascular window is managed with mechanical thrombectomy.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q9, p.2024 (answer p.2025)'
},

{ id:'npep-fe5-11', bank:'endpoint', module:'neuropsych', chapter:'nr-backpain',
  stem:'Which urinary symptom is considered due to neurogenic cause?',
  options:['Stress incontinence', 'Frequent micturition', 'Overflow incontinence.', 'Hesitancy'],
  answer:2,
  explanation:'The printed key is option c, “Overflow incontinence.” Overflow incontinence results from a bladder that cannot empty properly and becomes overdistended, classically from a lower motor neuron/neurogenic lesion causing an atonic, areflexic detrusor muscle — as seen with cauda equina or conus medullaris lesions — so urine leaks passively once the bladder is overfull (not taken from the course material). This mechanism is specifically neurogenic, unlike the other listed symptoms.\n\nOption a is wrong because stress incontinence is typically due to weakness of the pelvic floor/urethral sphincter mechanism, a structural/mechanical problem rather than a primary neurogenic one (not taken from the course material).\n\nOption b is wrong because frequent micturition (urinary frequency) has many non-neurogenic causes, such as urinary tract infection, diabetes, or an overactive bladder from local bladder pathology, and is not specific to a neurogenic cause (not taken from the course material).\n\nOption d is wrong because hesitancy can occur with non-neurogenic outflow obstruction, such as prostatic enlargement, as well as with neurogenic disease, so it is not the symptom singled out here as specifically neurogenic (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Overflow incontinence from an atonic, areflexic bladder is the urinary symptom specifically attributed to a neurogenic cause.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q11, p.2028 (answer p.2029)'
},

{ id:'npep-fe5-17', bank:'endpoint', module:'neuropsych', chapter:'nr-stroke',
  stem:'A 58-year-old male patient presented to BR with aneurysmal rupture. Coiling of the aneurysm was done, but the patient was comatosed for 10 days. Respiratory distress and tense lower limb edema were observed. What is the recommended investigation?',
  options:['CT brain', 'ECG', 'Echo', 'Doppler study of lower limb veins'],
  answer:3,
  explanation:'The printed key is Doppler study of lower limb veins. Ten days of coma after aneurysm coiling means prolonged immobilisation, which is a major risk factor for deep vein thrombosis; new tense lower limb edema together with respiratory distress raises concern for DVT with possible pulmonary embolism, and Doppler ultrasound of the lower limb veins is the direct investigation used to confirm or exclude DVT (not taken from the course material).\n\nCT brain is wrong because the aneurysm has already been secured by coiling, and the new findings described (respiratory distress, tense limb edema) are not neurological symptoms that a repeat CT brain would be expected to explain (not taken from the course material). ECG is wrong because, while it has a role in general cardiac and PE work-up, it is not the targeted test for tense unilateral or bilateral lower limb edema (not taken from the course material). Echo is wrong because it assesses cardiac structure and function or looks for an embolic source, but it does not directly investigate the swollen limb itself the way Doppler venous ultrasound does (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Prolonged immobilisation after aneurysm treatment raises the risk of DVT; tense limb edema with respiratory distress should prompt a Doppler study of the lower limb veins.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q17, p.2040 (answer p.2041)'
},

{ id:'npep-fe5-23', bank:'endpoint', module:'neuropsych', chapter:'nr-backpain',
  stem:"Which of the following is a sign of C7-T1 disc prolapse?",
  options:["Positive Hoffman's sign", 'Weak finger flexors', 'Impaired sensation of the thumb', 'Dampened biceps reflex'],
  answer:1,
  explanation:"The printed key is Weak finger flexors. A C7-T1 disc prolapse compresses the exiting C8 nerve root. C8 supplies the long finger flexors and the intrinsic hand muscles, so its compression characteristically produces weak finger flexors and grip weakness (not taken from the course material).\n\nImpaired sensation of the thumb is wrong because thumb sensation is carried mainly by the C6 dermatome, not C8, so it does not fit a C7-T1 level lesion (not taken from the course material). Dampened biceps reflex is wrong because the biceps reflex tests the C5-C6 myotome, which is unrelated to a C8 root lesion at C7-T1 (not taken from the course material). Positive Hoffman's sign is wrong because it is an upper motor neuron (pyramidal) sign that indicates cervical cord compression/myelopathy from the corticospinal tract, not a lower motor neuron finding produced by a single nerve-root level disc prolapse (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.",
  objective:'A C7-T1 disc prolapse compresses the C8 root and characteristically weakens the finger flexors.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q23, p.2052 (answer p.2053)'
},

{ id:'npep-fe5-28', bank:'endpoint', module:'neuropsych', chapter:'nr-coma',
  stem:'What is the most common brain tumor in pediatrics?',
  options:['Meningioma', 'Craniopharyngioma.', 'Hemangioblastoma', 'hemangiopericytoma'],
  answer:1,
  explanation:'The printed key is option b, Craniopharyngioma. Craniopharyngioma is a benign, slow-growing tumour arising from remnants of Rathke’s pouch epithelium in the suprasellar region, and it is a classic paediatric intracranial tumour, often presenting with visual field defects, growth failure, and endocrine disturbance from its proximity to the optic chiasm, pituitary, and hypothalamus (not taken from the course material).\n\nNote: many curricula instead teach pilocytic astrocytoma as the single most common paediatric brain tumour overall, with craniopharyngioma more specifically taught as the most common suprasellar/non-glial tumour of childhood. The bank’s printed and highlighted key is followed as marked (not taken from the course material).\n\nMeningioma is wrong because it is a tumour of meningothelial cells that is characteristically a disease of adulthood and is rare in the paediatric age group (not taken from the course material). Hemangioblastoma is wrong because it is a vascular tumour, classically of the cerebellum and associated with von Hippel-Lindau disease, that is more typical of adults and is not the standard answer for the commonest paediatric brain tumour (not taken from the course material). Hemangiopericytoma is wrong because it is a rare, aggressive mesenchymal tumour that occurs predominantly in adults and is not a standard paediatric brain tumour (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Craniopharyngioma is a classic suprasellar paediatric brain tumour arising from Rathke’s pouch remnants.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q28, p.2056 (answer p.2057)'
},

{ id:'npep-fe5-29', bank:'endpoint', module:'neuropsych', chapter:'nr-nerve',
  stem:'Which nerve can be used as a graft?',
  options:['Sural nerve', 'Lateral femoral cutaneous nerve', 'Posterior interosseous nerve', 'Anterior interosseous'],
  answer:0,
  explanation:'The printed key is option a, Sural nerve. The sural nerve is a purely sensory nerve running in the posterior calf that is the classic donor nerve for peripheral nerve grafting, because it is expendable (its sensory loss over the lateral foot is well tolerated), superficial and easily accessible, and long enough to bridge sizeable nerve gaps (not taken from the course material).\n\nLateral femoral cutaneous nerve is wrong because, although it is also a purely sensory nerve, it is not the classic graft donor; it is more often discussed in the context of meralgia paraesthetica than as a harvested graft (not taken from the course material). Posterior interosseous nerve is wrong because it is a deep motor branch of the radial nerve supplying the forearm extensors; sacrificing a motor nerve for grafting would create a significant donor deficit, and it is not the standard graft source (not taken from the course material). Anterior interosseous is wrong for the same reason: it is a motor branch of the median nerve supplying deep forearm flexors, not a disposable sensory nerve suited to grafting (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'The sural nerve is the classic donor nerve used for peripheral nerve grafting.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q29, p.2059 (answer p.2060)'
},

{ id:'npep-fe5-35', bank:'endpoint', module:'neuropsych', chapter:'nr-coma',
  stem:'A male child presented to the R with recurrent its. He had a history of hydrocephalous and ventriculo-atrial shunt insertion. Examination revealed temperature 37.2 degrees, normal funds and functioning Pudenz valve. What is the most appropriate treatment?',
  options:['endoscopic third ventriculostomy', 'shunt revision', 'Antiepileptics prescription', 'shunt removal'],
  answer:2,
  explanation:'The printed key is option c, Antiepileptics prescription. On examination the Pudenz valve (his ventriculo-atrial shunt) is described as functioning, fundoscopy is normal (no papilloedema, i.e. no evidence of raised intracranial pressure), and his temperature is essentially normal — together these argue against shunt malfunction or shunt infection as the cause of his recurrent fits. Because the hardware itself is working and there is no sign of raised intracranial pressure or infection, the recurrent seizures are managed as seizures in their own right, with antiepileptic medication, rather than by intervening on a shunt that is functioning normally (not taken from the course material).\n\nEndoscopic third ventriculostomy is wrong because it is an alternative primary procedure for diverting CSF in selected forms of hydrocephalus; it is not indicated here since his existing shunt is already functioning and there is no evidence it has failed (not taken from the course material). Shunt revision is wrong because revision is indicated when the shunt is malfunctioning, typically signalled by raised-pressure features such as papilloedema, which are absent here (not taken from the course material). Shunt removal is wrong because it is considered for shunt infection or when the shunt is no longer needed, neither of which is supported by his normal temperature and functioning valve (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Recurrent seizures with a normal fundus, normal temperature, and a functioning shunt valve are treated as seizures, not as shunt malfunction.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q35, p.2071 (answer p.2072)'
},

{ id:'npep-fe5-36', bank:'endpoint', module:'neuropsych', chapter:'nr-coma',
  stem:'The patient in the previous question refused intervention and after 24 hours became comatose. A follow-up CT brain shows a malignant infarction with midline shift. What is the appropriate treatment?',
  options:['Therapeutic heparin', 'Excision of necrotic brain tissue', 'Decompressive craniotomy', 'Physiotherapy'],
  answer:2,
  explanation:'The printed key is option c, Decompressive craniotomy. A malignant infarction causing coma and midline shift reflects life-threatening cerebral oedema with impending or ongoing herniation. Decompressive craniotomy (hemicraniectomy) is the established emergency surgical intervention for malignant infarction with significant mass effect, removing a portion of the skull to give the swollen brain room to expand and relieve intracranial pressure, which has been shown to reduce mortality in this setting (not taken from the course material).\n\nTherapeutic heparin is wrong because full anticoagulation is not indicated in an acute large-territory infarct with mass effect, where it would raise the risk of haemorrhagic transformation, and it does nothing to relieve herniation. Excision of necrotic brain tissue is wrong because the standard surgical approach to malignant infarction is decompression by bone removal, not resection of the infarcted tissue itself. Physiotherapy is wrong because it is a supportive rehabilitation measure, not an emergency treatment for life-threatening raised intracranial pressure and mass effect (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Decompressive craniotomy is the emergency treatment for malignant infarction causing coma and midline shift.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q36, p.2073 (answer p.2074)'
},

{ id:'npep-fe5-37', bank:'endpoint', module:'neuropsych', chapter:'nr-coma',
  stem:'A 35-year-old patient experienced head injury that was managed conservatively over 3 weeks. The CT brain showed frontal contusion with brain herniation. The patient has no localizing signs and no lateralization. What is most probably the type of this herniation?',
  options:['Tonsillar', 'Sub-falcine.', 'Uncal', 'Central'],
  answer:1,
  explanation:'The printed key is Sub-falcine herniation. Subfalcine (cingulate) herniation occurs when a hemispheric mass lesion pushes the cingulate gyrus under the free edge of the falx cerebri, and it is the most common type of brain herniation; early on it characteristically produces few or no clear localising or lateralising signs, which fits this patient’s CT evidence of herniation despite a normal focal examination (not taken from the course material).\n\nTonsillar herniation is wrong because it describes downward displacement of the cerebellar tonsils through the foramen magnum, which typically produces brainstem compression and respiratory compromise rather than a silent presentation, and is more a feature of posterior-fossa or diffusely raised pressure than an isolated frontal contusion. Uncal herniation is wrong because medial temporal lobe (uncus) herniation through the tentorial notch classically produces an early ipsilateral third-nerve palsy with a dilated pupil, a lateralising sign that contradicts the stem’s “no lateralization.” Central (transtentorial) herniation is wrong because it describes downward displacement of the diencephalon through the tentorial notch, more typically from diffuse or bilateral pathology, producing a progressive rostral-caudal deterioration rather than the picture described with a focal frontal contusion (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'A hemispheric mass lesion with no localizing or lateralizing signs points to sub-falcine (cingulate) herniation, the most common herniation type.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q37, p.2075 (answer p.2076)'
},

{ id:'npep-fe5-45', bank:'endpoint', module:'neuropsych', chapter:'ps-mood',
  stem:'In the previous case how could the recent manifestation of this patient be managed?',
  options:['Increase the dose of the initial drug', 'Refer the patient for receiving psychotherapy', 'Order magnetic resonance imaging', 'Order nerve conduction study'],
  answer:2,
  explanation:'The printed key is option C, "Order magnetic resonance imaging." The recent manifestation in the previous case is the patient\'s new headache together with the intracranial mass lesion demonstrated on CECT. Once a structural lesion has been identified, further characterization with MRI, which offers superior soft-tissue resolution and lesion delineation compared with CT, is the appropriate next step to define the lesion and guide further management, such as neurosurgical referral (not taken from the course material).\n\nIncrease the dose of the initial drug is wrong because simply escalating the antidepressant dose does not address the newly identified structural intracranial pathology, and his headache and imaging findings need dedicated neurological work-up rather than further psychiatric dose adjustment (not taken from the course material).\n\nRefer the patient for receiving psychotherapy is wrong for the same reason: psychotherapy addresses the psychiatric symptom complex but does not investigate or manage a demonstrated intracranial mass (not taken from the course material).\n\nOrder nerve conduction study is wrong because nerve conduction studies assess peripheral nerve function and are not relevant to evaluating an intracranial space-occupying lesion (not taken from the course material).\n\nWritten for this bank — the endpoint file prints no explanation here.',
  objective:'Once an intracranial mass lesion is found on CT, the next step is MRI to further characterize it, not escalating psychiatric treatment.',
  source:'Neuro endpoint.pdf, Model Final Exam 5, Q45, p.2093 (answer p.2094)'
}
