{
  id:'pedep-gi-35', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 6-week-old baby boy presents to the emergency department with a history of vomiting, the vomiting has been present since the third week of life but has suddenly increased in violence and frequency over the preceding 3 days. The baby is well but hungry and failing to thrive. The most useful next step is?',
  options:['Take an accurate feeding history and decrease feed volumes','Take a blood gas','Perform a septic screen','Start intensive gastro-oesophageal reflux therapy','Refer surgically immediately'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> The baby’s presentation is classic for infantile hypertrophic pyloric stenosis. The immediate priority is to check a blood gas to detect the typical hypochloremic, hypokalemic metabolic alkalosis and correct it before surgery. Definitive treatment is pyloromyotomy once the infant is stabilized.\n\n---\n\n**Why a blood gas comes before anything else.** `22)Vomiting.txt` places pyloric stenosis at 2-8 weeks of age, with non-bilious vomiting that increases in frequency and forcefulness over time and becomes projectile — exactly this baby\'s course, vomiting since week 3 now suddenly more violent and frequent, hungry but failing to thrive. The same lecture names the metabolic signature directly: repeated vomiting of acidic, chloride-rich stomach contents produces a hypochloraemic, hypokalaemic metabolic alkalosis, and it states that pyloromyotomy follows correction of this acid-base and electrolyte imbalance, which "may take more than 24 hours of intravenous fluid rehydration." A blood gas is therefore the step that both confirms the expected derangement and starts the clock on safe surgical timing.\n\n**Why each distractor is wrong.** *Feeding history and reduced feed volumes* would be reasonable for simple overfeeding or uncomplicated reflux, but this baby\'s worsening violence and frequency of vomiting with failure to thrive is the pyloric-stenosis trajectory, not an overfeeding one; reducing volumes does not fix a mechanical gastric-outlet obstruction. *A septic screen* is the right instinct for any vomiting infant who looks unwell, but the vignette describes a well, hungry baby with a textbook pyloric-stenosis story rather than a lethargic, septic-looking one, so it is not the most useful next step here. *Intensive reflux therapy* targets the wrong diagnosis and would delay recognising the obstruction. *Immediate surgical referral*, without first checking and correcting the metabolic alkalosis, risks anaesthetising a baby who is not yet safe for theatre — the lecture is explicit that correction comes first.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A vomiting infant with a pyloric-stenosis history needs a blood gas to detect and correct the hypochloraemic, hypokalaemic alkalosis before surgery, not immediate referral.',
  source:'Pediatrics endpoint part1.pdf p.483'
},

{
  id:'pedep-gi-36', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A 9-month-old infant presents with vomiting and crying. On examination she is afebrile and has a diffusely tender abdomen. No masses are palpable. Which one of the following diagnoses is the most important to exclude?',
  options:['Gastroenteritis','Intussusception','Mesenteric adenitis','Hirschsprung’s disease','Colic'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Intermittent abdominal pain with crying in an infant is a red flag for intussusception, which requires urgent diagnosis and management.\n\n---\n\n**Why intussusception is the one that cannot be missed.** `24)Abdominal pain.txt` names intussusception as invagination of proximal bowel into a distal segment, most often ileum passing into the caecum, and states it is "the most common cause of intestinal obstruction in infants after the neonatal period," with a peak age of 3 months to 2 years — this infant is squarely in that window. The classic triad of colicky pain, a palpable sausage-shaped mass and redcurrant-jelly stool is a late finding; a still-early presentation can look exactly like this — vomiting, crying and a diffusely tender abdomen with no mass yet felt — which is precisely why it must be actively excluded rather than assumed absent just because the textbook signs are not all present.\n\n**Why each distractor is a lower priority to exclude.** *Gastroenteritis* is a plausible cause of vomiting but does not typically cause the intermittent, crying-with-pain pattern described, and it is not the diagnosis that carries a risk of bowel ischaemia if missed. *Mesenteric adenitis* is explicitly benign in the same lecture, with pain that "resolves in 24-48 hours" and is milder than a surgical process — it does not need urgent exclusion. *Hirschsprung\'s disease* classically declares itself in the neonatal period with delayed passage of meconium and chronic constipation, not an acute vomiting-and-crying picture at 9 months. *Colic* is a diagnosis of infancy that typically resolves by 3-4 months and does not produce a diffusely tender abdomen on examination, so it does not fit either the age or the exam findings as well as intussusception does.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Vomiting with crying in an infant aged 3 months to 2 years must actively exclude intussusception, even before the classic mass or redcurrant-jelly stool appears.',
  source:'Pediatrics endpoint part1.pdf p.485'
},

{
  id:'pedep-gi-37', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 5-year-old girl has had a persistent nocturnal cough for over 2 years that has not responded to Rx including inhaled steroids & bronchodilators. The cough tends to be paroxysmal & is associated with vomiting, disturbing her sleep virtually every night. She is happy & normally active during the day & did not have any exercise intolerance. In other respects, she has been well with no significant past history. There is no family Hx of asthma/eczema/allergy. Clinically, her weight was on the 75th centile & her height on the 50th centile. Examinations were normal. CXR & CBC – normal range. CRP, PEF 99%, Mantoux negative. The next most useful test that will aid the diagnosis is?',
  options:['Bronchoscopy','CT scan of thorax','Ambulatory esophageal pH study','Barium meal','Spirometry'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Chronic nocturnal cough with vomiting and normal respiratory evaluation suggests gastroesophageal reflux; pH monitoring is diagnostic.\n\n---\n\n**Why pH monitoring is the next step.** `22)Vomiting.txt` lists 24-hour oesophageal pH monitoring as the investigation used "to quantify the degree of acid reflux," with a probe passed into the lower oesophagus, and names recurrent pulmonary aspiration — presenting as recurrent pneumonia, cough or wheeze — among the complications of gastro-oesophageal reflux disease. This girl has failed a full asthma work-up (no response to inhaled steroids and bronchodilators, normal CXR, normal PEF, no atopic family history), which argues against asthma and toward an alternative driver of a nocturnal, paroxysmal cough with vomiting: silent reflux irritating the airway. Her normal growth (weight even above height centile) argues against a systemic or malabsorptive illness and is consistent with a chronic but non-wasting process like reflux.\n\n**Why each distractor is not the next useful test.** *Bronchoscopy* and *CT of the thorax* look for structural or endobronchial airway disease, but her CXR is already normal and her presentation does not suggest a mass, foreign body or bronchiectasis. *Barium meal* is explicitly ruled out by the same lecture, which states a contrast study of the upper gastrointestinal tract "is not recommended to diagnose or assess the severity of gastro-oesophageal reflux disease." *Spirometry* re-tests airway function she has essentially already had assessed (PEF 99%, no exercise intolerance) and will not identify reflux as the cause of a cough that has already failed asthma therapy.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A chronic nocturnal cough with vomiting that has failed asthma therapy and has a normal chest work-up points to reflux, confirmed by ambulatory oesophageal pH monitoring, not a barium study.',
  source:'Pediatrics endpoint part1.pdf p.487'
},

{
  id:'pedep-gi-38', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'An 8-month-old infant has had watery diarrhoea for 4 days. There has been no recent travel. Her 2-year-old sibling has recently had a similar illness, though less severe. She is drinking her normal formula milk well and is not dehydrated. What is the diagnosis?',
  options:['Viral gastro-enteritis','Bacterial dysentery','Lactose intolerance','Giardiasis'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Self-limited watery diarrhea in a well-hydrated infant with a household contact points to a viral cause; supportive care is sufficient.\n\n---\n\n**Why viral gastro-enteritis fits.** `23).1) Acute diarrhea.txt` defines acute watery diarrhoea (acute gastroenteritis) as "passage of frequent loose or watery stools without visible blood," constituting about 80% of diarrhoea cases, and names viruses as the cause in roughly 70% of those — far ahead of bacteria (10-20%) or protozoa (under 10%). It also notes the illness "begins acutely" and "lasts less than 14 days (usually less than 7 days)," which matches this 4-day watery, non-bloody course. A sibling with a similar, milder illness is the classic person-to-person spread pattern of a viral pathogen (rotavirus and norovirus being the leading examples), and the infant remaining well hydrated and feeding normally fits an uncomplicated, self-limited process.\n\n**Why each distractor is wrong.** *Bacterial dysentery* is defined by the same lecture around blood in the stool, tenesmus and severe abdominal pain from large-bowel involvement — none of which is described, and the watery (not bloody) character argues against it. *Lactose intolerance* is a chronic or recurring problem tied to milk exposure, not an acute 4-day illness that coincides with a sick sibling. *Giardiasis*, a protozoal cause making up under 10% of cases, more typically produces a persistent or malabsorptive picture rather than this acute, short, household-clustered watery illness.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Acute, non-bloody, self-limited watery diarrhoea with a sick household contact is viral gastroenteritis, the cause of roughly 70% of acute infectious diarrhoea.',
  source:'Pediatrics endpoint part1.pdf p.489'
},

{
  id:'pedep-gi-39', bank:'endpoint', module:'pediatrics', chapter:'neonatal-sepsis',
  stem:'A 2-week-old infant develops fever 38.9 °C, vomiting, and irritability. His heart rate is 170/min, and RR is 40/min. The infant\'s anterior fontanelle is full, but there is no nuchal rigidity. The rest of examination is unremarkable. What is the APPROPRIATE management?',
  options:['Oral fluid and follow up in 24 hr','Amoxicillin and follow up in 1 week','Admission to hospital for investigations and treatment','IM ceftriaxone for 5 days','IV Fluid for 6 hr and follow up in 24 hr'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Neonatal fever in a 2-week-old is a medical emergency; full septic workup and inpatient monitoring with empiric antibiotics are required.\n\n---\n\n**Why admission for full workup and treatment is correct.** `18) febrile child and life threatening infections.txt` sets the neonatal age band (≤28 days) apart from older infants: "All febrile children < 1 mo = admission," requiring "a WBC count with a manual differential, blood cultures, urinalysis and urine culture" and "CSF evaluation with culture and appropriate PCR testing," plus a chest X-ray if there are respiratory signs, together with empiric IV antibiotics for the common neonatal pathogens. This 2-week-old is exactly that age band, and a full anterior fontanelle is one of the lecture\'s own listed features of meningitis (`11) Neonatal sepsis.txt` lists "tense or bulging fontanelle" under meningitis signs) — even without nuchal rigidity, which is frequently absent in a neonate, the combination of fever, tachycardia, tachypnoea, irritability and a full fontanelle is enough to mandate the complete septic and CSF work-up that only an admission can provide.\n\n**Why each distractor is wrong.** *Oral fluid with follow-up in 24 hours* and *IV fluid for 6 hours with follow-up* both treat this as an outpatient problem and provide no antimicrobial cover or CSF evaluation, which the guideline explicitly forbids for this age. *Amoxicillin with a 1-week follow-up* gives unfocused oral antibiotic cover without the blood, urine and CSF cultures needed to identify the organism, and without inpatient monitoring for a neonate who can deteriorate rapidly. *IM ceftriaxone for 5 days* supplies an antibiotic but as an outpatient course, again skipping the cultures, CSF evaluation and observation that "admission" specifically buys — the lecture\'s message is that investigation and treatment happen together, in hospital, at this age.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Fever in an infant under 1 month old always mandates hospital admission for a full septic work-up — including CSF evaluation — and empiric antibiotics, never outpatient management.',
  source:'Pediatrics endpoint part1.pdf p.491'
},

{
  id:'pedep-gi-40', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 6-week-old male is brought to clinic with concern for frequent regurgitation of feeds. His mother reports that he vomits large volumes of curdled milk after feeding. He is interested in feeding and breast feeds without difficulty. His weight gain has averaged 32 grams per day since his last visit. On physical examination, he appears comfortable and well hydrated. A small amount of curdled milk is present in his mouth. The remainder of his examination is unremarkable. Which of the following should be used to confirm suspicion of gastroesophageal reflux in this infant?',
  options:['Endoscopy','Esophageal pH monitoring','History and physical alone','Upper gastrointestinal series'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Physiological reflux in infants is diagnosed clinically; invasive tests are not needed if the baby is thriving and asymptomatic otherwise.\n\n---\n\n**Why history and physical alone are sufficient.** `22)Vomiting.txt` states plainly that "gastro-oesophageal reflux is usually diagnosed clinically, and no investigations are required," with tests reserved for when "the history is atypical, complications are present, or there is failure to respond to treatment." This baby has none of those triggers: he feeds eagerly, is comfortable and well hydrated on examination, and is gaining weight briskly (32 g/day is a healthy rate for this age) — a picture of uncomplicated, physiological regurgitation, the lecture\'s own description of most infants with reflux as thriving normally.\n\n**Why each distractor is wrong.** *Endoscopy* is used to look for oesophagitis or to exclude other causes of vomiting when reflux disease (not simple reflux) is suspected — not indicated in a thriving, comfortable infant. *Oesophageal pH monitoring* quantifies acid reflux and is reserved for atypical or complicated presentations, again not this straightforward case. *Upper gastrointestinal (contrast) series* is explicitly named by the lecture as "not recommended to diagnose or assess the severity of gastro-oesophageal reflux disease in infants, children and young people" — it looks for anatomical problems, not physiological reflux, and carries unnecessary radiation for a baby who needs no test at all.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A thriving, comfortable infant with regurgitation needs no investigation at all — gastro-oesophageal reflux is a clinical diagnosis unless the history is atypical or complicated.',
  source:'Pediatrics endpoint part1.pdf p.493'
},

{
  id:'pedep-gi-41', bank:'endpoint', module:'pediatrics', chapter:'haem-bleeding',
  stem:'Which of the following statements is the most factually correct with regard to the administration of vitamin K to babies in the neonatal period?',
  options:['If an oral regimen is undertaken, a single dose of oral vitamin K is recommended in all formula-fed babies','Significant bleeding in the neonatal period normally occurs in children with significant risk factors for vitamin K deficiency bleeding','The vast majority of vitamin K deficiency-associated bleeding occurs within the first week of life','There is good evidence to support an increased risk of childhood leukemia in babies given vitamin K in the neonatal period','Vitamin K deficiency bleeding is a potentially fatal disorder that is virtually preventable with one dose of vitamin K given intramuscularly at birth'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> IM vitamin K at birth effectively prevents vitamin K deficiency bleeding, which can be severe. The risk of childhood leukemia is not supported by evidence, and most bleeding occurs after the first week in exclusively breastfed infants without prophylaxis.\n\n---\n\n**Why a single IM dose is the correct statement.** `47)Hemorrhagic disorders .txt`\'s comparison table separates vitamin K deficiency from DIC by a prolonged PT with an otherwise normal platelet count, TT and fibrinogen — a coagulation-factor problem, not a consumptive or platelet one, which is exactly why replacing the missing factor (vitamin K) at birth is enough to prevent it. The policy detail that one intramuscular dose at birth is "virtually preventable" and highly effective, that most vitamin K deficiency bleeding is actually **late-onset** (beyond the first week, in exclusively breastfed infants who received no prophylaxis) rather than concentrated in the first week, and that the childhood-leukaemia scare has not been supported by good evidence, are public-health and neonatal-care facts the lecture\'s lab table does not itself spell out *(not taken from the course material)*.\n\n**Why each distractor is wrong.** *A single oral dose "in all formula-fed babies"* misstates policy: oral vitamin K regimens require **multiple** doses over the following weeks, not one, because oral absorption and coverage are less reliable than an IM injection *(not taken from the course material)*. *"Significant bleeding normally occurs only with risk factors"* is false — vitamin K deficiency bleeding classically strikes previously well, low-risk exclusively breastfed infants who simply never received prophylaxis, which is precisely why universal, not risk-based, prophylaxis is given. *"The vast majority occurs in the first week"* reverses the epidemiology: **late-onset** disease (week 2 to 6 months) is the more dangerous, less recognised pattern, often presenting with intracranial haemorrhage. *"Good evidence for a leukaemia link"* was a hypothesis raised in the 1990s that large subsequent studies have not confirmed *(not taken from the course material)*.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'One intramuscular dose of vitamin K at birth is highly effective, near-universal prophylaxis against vitamin K deficiency bleeding, which is not confined to the first week of life and carries no confirmed leukaemia risk.',
  source:'Pediatrics endpoint part1.pdf p.495, explanation box p.496'
},

{
  id:'pedep-gi-42', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'In gastroesophageal reflux, which statement is TRUE?',
  options:['it is a rare phenomenon in infants','The parents can be reassured, it is a process the child will outgrow as they get older','Thickening the feedings does not work','Most infants have slow weight gain','Always deserves further evaluation'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> GER is common and physiological in infants, usually resolving spontaneously by 12–18 months. Most infants grow normally and do not require intervention unless complications arise.\n\n---\n\n**Why reassurance is the true statement.** `22)Vomiting.txt` states that "most cases resolve spontaneously by 12 months of age due to a combination of maturation of the lower oesophageal sphincter, an upright posture and more solids in the diet," and calls gastro-oesophageal reflux "a benign, self-limited condition" unless complications turn it into reflux disease. Parental reassurance is listed first among the lecture\'s own management steps, precisely because most infants simply outgrow it.\n\n**Why each distractor is false.** *"Rare in infants"* is the opposite of the lecture\'s framing — reflux is described as "very common in infancy," caused by the normal functional immaturity of the lower oesophageal sphincter, a fluid diet, horizontal posture and a short intra-abdominal oesophagus. *"Thickening the feedings does not work"* contradicts the lecture\'s management list, which offers "smaller, more frequent feeds or adding inert thickening agents to feeds" as a recognised first-line measure. *"Most infants have slow weight gain"* is also reversed: the lecture specifically notes "most infants with gastro-oesophageal reflux are putting on weight normally," with faltering growth listed only as a complication of the more severe reflux disease, not the typical course. *"Always deserves further evaluation"* contradicts the same lecture\'s investigations section, which states reflux is "usually diagnosed clinically, and no investigations are required," with tests reserved for atypical or complicated cases.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Gastro-oesophageal reflux is common, usually resolves spontaneously by 12 months, and needs no routine investigation — reassurance is the correct management for the typical, thriving infant.',
  source:'Pediatrics endpoint part1.pdf p.498'
},

{
  id:'pedep-gi-43', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'Which of the following sets of signs and symptoms are most consistent with 5% dehydration?',
  options:['Alert and responsive, warm extremities, tears with crying, normal skin turgor, moist oral mucosa','Less active than usual, sticky oral mucosa, normal or slightly diminished skin turgor, normal capillary refill time','Oliguria, sunken eyes, pale mottled skin with reduced skin turgor, prolonged capillary refill time','Oliguria, sunken eyes, tachycardia, hypotension'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Mild dehydration (5%) causes subtle signs like slight lethargy and sticky mucous membranes; severe signs like hypotension or tachycardia indicate greater dehydration.\n\n---\n\n**Why option B matches 5% dehydration.** `23).1) Acute diarrhea.txt` grades dehydration in three bands: "no dehydration" (usually <5% loss), "some dehydration" ("clinical dehydration," usually 5% to 10% loss) and "severe dehydration" (usually >10% loss), with shock as a fourth, most severe category. The bedside assessment it teaches (GEMS: general condition, eyes, mouth, skin pinch) grades each sign as normal, or "slowly"/"very slowly" returning on skin pinch, and "lethargic, irritable" versus normal general condition. A child who is "less active than usual" with sticky mucous membranes and only mildly reduced turgor sits at the mild end of "some dehydration" — the lecture\'s own definition of roughly 5% loss — with capillary refill still normal because circulating volume is not yet critically reduced.\n\n**Why each distractor is wrong.** *Option A* (alert, warm extremities, moist mucosa, normal turgor) describes a child with **no dehydration**, not 5%. *Option C* (sunken eyes, pale mottled skin, reduced turgor, prolonged capillary refill) describes the lecture\'s "severe dehydration" band, over 10% loss — capillary refill only prolongs once perfusion is significantly compromised. *Option D* (oliguria, sunken eyes, tachycardia, hypotension) is frank **shock**, the lecture\'s most severe category, requiring an immediate 20 mL/kg bolus of 0.9% saline — far beyond a 5% deficit.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'5% ("some") dehydration presents as mild lethargy, sticky mucous membranes and only slightly reduced skin turgor, with capillary refill still normal — hypotension and prolonged refill mark shock, not this grade.',
  source:'Pediatrics endpoint part1.pdf p.500'
},

{
  id:'pedep-gi-44', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'Most common abdominal pain in childhood is:',
  options:['Functional','Appendicitis','Peptic ulcer disease','Intussusception'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Functional abdominal pain (not due to organic disease) is the most common type in children and typically resolves without surgical or medical intervention.\n\n---\n\n**Why functional pain is the commonest.** `24)Abdominal pain.txt` states that chronic or recurrent abdominal pain "occurs in 10-15% of children," and frames functional pain as "a Diagnosis of Exclusion" reached only once organic disease has been screened out by history, examination and initial tests — the sheer scale of that 10-15% figure, set against how uncommon any single organic cause is, is what makes functional pain the numerically dominant category. The lecture\'s own comparison table also distinguishes functional pain by a vague, midline site, a pattern that is never nocturnal, and the absence of the "alarm signals" (weight loss, growth deceleration, nocturnal waking, blood in stool) that flag an organic cause.\n\n**Why each distractor is wrong.** *Appendicitis* is an important acute surgical diagnosis but is a single, comparatively uncommon cause of abdominal pain overall, not the dominant one across all presentations. *Peptic ulcer disease* is uncommon in children and is one of the organic causes functional pain is diagnosed by excluding, not a frequent diagnosis in its own right. *Intussusception* is likewise a specific, less common surgical cause, concentrated in the 3-month to 2-year age band, and does not approach the prevalence of functional pain across the whole paediatric population.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Functional abdominal pain, a diagnosis of exclusion once organic disease is screened out, is the most common cause of abdominal pain in children overall.',
  source:'Pediatrics endpoint part1.pdf p.502'
},

{
  id:'pedep-gi-45', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'A 6-year-old boy presents to an urgent care clinic with a history of low-grade fevers, diffuse abdominal pain, and multiple episodes of non-bloody diarrhea for the last two days. He also had one to two episodes of non-bloody, non-bilious emesis each day, but this is slowing down. He is not eating as well as usual, but he is taking small bites and drinking plenty of fluids. On evaluation, he appears tired and is not playful, but his vital signs are normal and he appears to be well-hydrated. Which of the following is the most appropriate therapeutic approach for this patient?',
  options:['Antiemetic medication','Antimotility medication','Probiotic treatment','Zinc supplementation'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Acute gastroenteritis is a common infectious disease in children which manifests as frequent loose stools exceeding normal frequency with or without fever and vomiting, lasting from one day to two weeks.\n\n---\n\n**Why probiotic treatment is the printed key.** `23).1) Acute diarrhea.txt` lists probiotics as adjuvant therapy for acute gastroenteritis, and states that "two large systematic reviews have found probiotics (especially Lactobacillus GG) to be effective in reducing the duration of diarrhea in children presenting with acute gastroenteritis" — directly relevant to this well-hydrated, resolving, mildly ill boy who needs supportive, not aggressive, treatment. ⚠️ The same lecture also lists zinc supplementation as a routine recommendation "in all types of diarrhea, in all degree of dehydration," so a case can also be made for zinc from this material; the bank\'s printed key selects probiotic treatment, and that key is kept here rather than moved, with this note flagging the overlap for the record.\n\n**Why each other option is wrong regardless.** *Antiemetic medication* is explicitly discouraged: the lecture states "it is recommended that antiemetics not be routinely used in the management of children with AGE," reserving ondansetron for more severe vomiting with dehydration. *Antimotility medication* is stated to be "Not used for children," with drugs like loperamide contraindicated in acute gastroenteritis in children "because of their lack of benefit and increased risk of adverse effects, including ileus, drowsiness, and nausea" — actively dangerous, not merely unhelpful, in a young child.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Antiemetics and antimotility drugs are not used in paediatric acute gastroenteritis; supportive adjuvant measures such as probiotics or zinc are the recommended approach.',
  source:'Pediatrics endpoint part1.pdf p.504'
},

{
  id:'pedep-gi-46', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'You are counselling a 3-day-old term infant who has not passed meconium since birth. On examination his abdomen is distended but the remainder of the examination is normal. An x-ray of the abdomen shows distended loops throughout the bowel, including the rectum. What is the most likely diagnosis?',
  options:['Congenital hypothyroidism','Cystic fibrosis','Duodenal atresia','Hirschsprung disease','Malrotation'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Hirschsprung disease results from the absence of ganglion cells in the distal colon, causing functional obstruction. This leads to failure to pass meconium, abdominal distension, and on X-ray, dilated bowel loops including the rectum, distinguishing it from other causes like cystic fibrosis or duodenal atresia.\n\n---\n\n**Why Hirschsprung disease fits the picture.** *Hirschsprung disease is caused by failure of neural-crest-derived ganglion cells to migrate into the distal bowel wall during fetal development, leaving the affected segment permanently aganglionic and unable to relax — a functional, not mechanical, obstruction that classically presents as delayed passage of meconium beyond 24-48 hours in a term newborn, with abdominal distension and dilated proximal bowel visible on plain film (not taken from the course material; the cached constipation and vomiting decks do not cover Hirschsprung disease directly, though `6) Genetically determined disease_.txt` lists it once, as a recognised anomaly in Down syndrome).* A 3-day-old who has never passed meconium, with a distended abdomen and diffusely dilated loops on X-ray, is the textbook neonatal Hirschsprung presentation.\n\n**Why each distractor fails.** *Congenital hypothyroidism* can cause constipation and a distended, doughy abdomen, but it is a chronic, gradually declining picture, not a same-week failure to pass meconium at all with diffuse obstructive dilation. *Cystic fibrosis* causes meconium ileus, which also delays meconium passage, but its classic X-ray finding is a "soap-bubble" pattern of mixed gas and inspissated meconium localised to the right lower quadrant with a narrow, unused microcolon distally — not the uniformly dilated bowel including the rectum described here. *Duodenal atresia* obstructs very proximally and presents with early bilious vomiting and a "double bubble" of a distended stomach and duodenal cap on X-ray, with a gasless distal abdomen, the opposite pattern to diffusely dilated loops throughout the bowel. *Malrotation* (with or without volvulus) likewise presents with bilious vomiting from a proximal obstruction, not primarily with failure to pass meconium and diffuse distal dilation.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Delayed passage of meconium beyond 24-48 hours with abdominal distension and diffusely dilated bowel loops including the rectum is the classic neonatal presentation of Hirschsprung disease.',
  source:'Pediatrics endpoint part1.pdf p.506'
},

{
  id:'pedep-gi-47', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'Features of gastro-esophageal reflux disease in infants do NOT include the following:',
  options:['Excessive crying','Poor weight gain','Vomiting','Anemia, malnutrition and apnea may occur','Hemoptysis'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> GERD in infants can cause vomiting, poor weight gain, apnea, or anemia, but coughing up blood is not a typical feature.\n\n---\n\n**Why hemoptysis is the odd one out.** `22)Vomiting.txt` lists the complications of gastro-oesophageal reflux disease as faltering growth from severe vomiting, oesophagitis (which can cause haematemesis — vomited blood — discomfort on feeding, heartburn and iron-deficiency anaemia), recurrent pulmonary aspiration (recurrent pneumonia, cough or wheeze, and apnoea in preterm infants), Sandifer syndrome and brief resolved unexplained events. Every one of the four other options in this question maps directly onto that list: crying (discomfort/heartburn), poor weight gain (faltering growth), vomiting (the core symptom) and anaemia/apnoea (named complications). *Hemoptysis — coughing up blood from the lower respiratory tract — is a distinct sign from the haematemesis the lecture actually names, and is not a recognised feature of reflux even when aspiration causes recurrent chest infection (not taken from the course material for this specific distinction).*\n\n**Why the confusion is easy to make, and why it still fails.** Recurrent aspiration from reflux can cause pneumonia and cough, and severe respiratory infection can occasionally produce blood-streaked sputum from airway inflammation, but this is not the same clinical entity as true hemoptysis, and it is not listed among the lecture\'s reflux complications the way hematemesis explicitly is. The question is testing the distinction between a genuine, lecture-sourced reflux feature and a plausible-sounding but unlisted one.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'GERD complications include faltering growth, haematemesis, anaemia, apnoea and recurrent aspiration pneumonia — hemoptysis is not among the recognised features.',
  source:'Pediatrics endpoint part1.pdf p.508'
},

{
  id:'pedep-gi-48', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 5-month-old girl presented with complaints of vomiting after feed, recurrent attacks of pneumonia, wheezy chest, and failure to thrive. The MOST likely diagnosis is:',
  options:['Congenital hypertrophic pyloric stenosis','Faulty feeding techniques','Hirschsprung\'s disease','Gastro-esophageal reflux disease','Physiological regurgitation'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Recurrent aspiration due to reflux can cause respiratory symptoms and failure to thrive. Pyloric stenosis usually presents earlier with projectile vomiting.\n\n---\n\n**Why GERD fits this 5-month-old.** `22)Vomiting.txt` names "recurrent pulmonary aspiration — recurrent pneumonia, cough or wheeze, apnea in preterm infants" and "faltering growth from severe vomiting" as the two complications that together define gastro-oesophageal reflux **disease** rather than simple, benign reflux. This girl has all three: vomiting after feeds, recurrent pneumonia with a wheezy chest (aspiration), and failure to thrive — the complete triad the lecture describes.\n\n**Why each distractor is wrong.** *Congenital hypertrophic pyloric stenosis* "presents at 2-8 weeks of age," with non-bilious vomiting that becomes projectile — this infant is 5 months old, well outside that window, and pyloric stenosis does not cause recurrent pneumonia or wheeze. *Faulty feeding technique* could cause simple overfeeding-related regurgitation but does not explain recurrent chest infections or growth failure. *Hirschsprung\'s disease* is a lower-bowel motility disorder presenting with constipation and abdominal distension, not vomiting with respiratory disease. *Physiological regurgitation* is by definition benign, with normal growth and no respiratory complications — the presence of failure to thrive and recurrent pneumonia here is exactly what separates disease from physiological reflux.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Vomiting with recurrent pneumonia, wheeze and failure to thrive in an infant beyond the pyloric-stenosis age window is gastro-oesophageal reflux disease from recurrent aspiration.',
  source:'Pediatrics endpoint part1.pdf p.510'
},

{
  id:'pedep-gi-49', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'Which of the following is not consistent with Hirschsprung\'s disease?',
  options:['No passage of meconium after 24 hours of birth','Abdominal distension','Bile-stained vomiting','Refractory constipation','Resolves spontaneously'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Hirschsprung disease is a congenital absence of ganglion cells and does not resolve spontaneously; it requires surgical intervention.\n\n---\n\n**Why spontaneous resolution is the false statement.** *Hirschsprung disease is a fixed, structural absence of ganglion cells in the distal bowel wall — the aganglionic segment does not regain ganglion cells over time, so the functional obstruction it causes cannot resolve on its own (not taken from the course material; the cached constipation deck does not cover Hirschsprung disease directly). Definitive treatment is surgical, removing the aganglionic segment and pulling through healthy, innervated bowel — without that, the obstruction, and the risk of life-threatening Hirschsprung-associated enterocolitis, persists.*\n\n**Why each of the other four IS consistent with the disease.** *No meconium passed after 24 hours of birth* is the classic, most sensitive early sign, since the affected distal segment cannot relax to allow normal transit. *Abdominal distension* follows directly from proximal bowel dilating against the obstructed, aganglionic segment. *Bile-stained vomiting* can occur once the functional obstruction is severe enough to back up proximally to the point of causing vomiting. *Refractory constipation* — poorly responsive to the usual laxative and behavioural measures used for functional constipation — is exactly what should raise suspicion of an organic cause such as Hirschsprung disease rather than the far more common functional constipation.\n\n**This same near-identical stem and option set — a 5-way "not consistent with Hirschsprung\'s disease" list — is printed again elsewhere in this bank with a different final option**, offering "treatment is by repeated finger dilatation" in place of "resolves spontaneously"; each is keyed to its own distinct final option rather than being one repeated question.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Hirschsprung disease is a fixed anatomical absence of ganglion cells that never resolves spontaneously and always requires surgical correction.',
  source:'Pediatrics endpoint part1.pdf p.512'
},

{
  id:'pedep-gi-50', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A one-year-old boy presented to the emergency room with severe colicky abdominal pains associated with vomiting and bleeding per rectum. PR examination revealed a mass and blood on the finger on withdrawal. What is the MOST likely diagnosis?',
  options:['Intestinal polyp','Volvulus','Intussusception','Dysentery','Hirschsprung\'s disease'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Classic currant jelly stools, colicky pain, and palpable mass are pathognomonic for intussusception.\n\n---\n\n**Why intussusception is the diagnosis.** `24)Abdominal pain.txt` describes intussusception as the invagination of proximal bowel into a distal segment, most often ileum through the ileocaecal valve into the caecum, and states it is "the most common cause of intestinal obstruction in infants after the neonatal period," peaking between 3 months and 2 years — exactly this boy\'s age. The combination of severe colicky pain, vomiting, a palpable abdominal or rectal mass and blood found on withdrawal of the examining finger is *the classic bedside triad the lecture\'s intussusception content is built around (the specific detail that the blood is "redcurrant-jelly" in character — altered blood mixed with mucus from the intussuscepted, ischaemic bowel — is standard teaching but not spelled out in this lecture; not taken from the course material for that specific description).*\n\n**Why each distractor fails.** *Intestinal polyp* typically causes painless, intermittent rectal bleeding rather than acute colicky pain with a palpable mass. *Volvulus* causes sudden bilious vomiting and abdominal distension from a twisted loop of bowel, but a palpable mass with blood on PR examination is not its hallmark finding. *Dysentery* causes bloody, mucoid diarrhoea from mucosal inflammation, not a palpable mass or colicky, crampy pain pattern. *Hirschsprung\'s disease* is a chronic constipating condition from birth, not an acute presentation with colicky pain, vomiting and a mass.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Colicky abdominal pain, vomiting, and blood found on rectal examination with a palpable mass in a 3-month to 2-year-old is intussusception until proved otherwise.',
  source:'Pediatrics endpoint part1.pdf p.514'
},

{
  id:'pedep-gi-51', bank:'endpoint', module:'pediatrics', chapter:'perinatal',
  stem:'A 2-week-old baby presents with irritability and difficult feeding. On examination, a white adherent coating of the tongue and buccal mucosa is observed. There is some associated erythema and the lesion bleeds when you try to remove the white coating. Which of the following is the MOST appropriate in caring for this baby?',
  options:['Admit to hospital and order a sepsis work-up','Admit to hospital and order a coagulation study as the lesion bleeds','Send the baby home and prescribe an oral antibiotic','Send the baby home and prescribe oral nystatin','Send the baby home and prescribe a parenteral antibiotic'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Oral thrush (candidiasis) presents with white patches that bleed when scraped. It is treated with topical antifungal; hospitalization is not usually needed in otherwise healthy neonates.\n\n---\n\n**Why outpatient oral nystatin is correct.** *A white, adherent coating on the tongue and buccal mucosa that bleeds when scraped off — rather than wiping away cleanly, which would suggest simple retained milk curds — is the classic description of oral candidiasis (thrush), a common, benign fungal overgrowth in young infants (not taken from the course material; no cached lecture in this set covers neonatal oral candidiasis specifically). The associated irritability and reluctance to feed reflect local discomfort rather than systemic illness. First-line treatment for uncomplicated oral thrush in an otherwise well neonate is a topical or oral antifungal such as nystatin suspension, applied to the affected mucosa, managed entirely as an outpatient.*\n\n**Why each distractor is wrong.** *Admission for a sepsis work-up* is not warranted, since nothing in the vignette — an isolated oral lesion with local irritability — suggests systemic infection, fever or a septic-looking baby. *Admission for a coagulation study* over-interprets the bleeding: the bleeding described is superficial, mechanical bleeding from disrupting an inflamed candidal plaque, not evidence of an underlying bleeding disorder, so a full coagulation admission is unnecessary. *Oral or parenteral antibiotics* both target bacteria, and thrush is a fungal infection — an antibacterial agent will not treat it and, by disrupting normal flora, can even worsen candidal overgrowth.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A white, adherent oral coating that bleeds on scraping in a well neonate is oral candidiasis, treated as an outpatient with topical/oral antifungal, not antibiotics or admission.',
  source:'Pediatrics endpoint part1.pdf p.516'
},

{
  id:'pedep-gi-52', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A 6-year-old boy presents with joint pain, rash and severe abdominal pain. From mother\'s description, the rash has appeared in crops on his legs over the past week. What is the MOST likely diagnosis?',
  options:['Gastric bleed','Gastric ulcer','Henoch Schonlein purpura','Systemic lupus erythematosus','Varicella zoster (chicken pox)'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> HSP is a small-vessel vasculitis presenting with palpable purpura, abdominal pain, and arthralgia, often following upper respiratory infections.\n\n---\n\n**Why HSP fits exactly.** `47)Hemorrhagic disorders .txt` gives "the four main characteristics of Henoch-Schonlein purpura" as a purplish rash (reddish-purple spots resembling bruises, on the buttocks, legs and feet, "may be worse in areas of pressure"), swollen sore joints (mainly knees and ankles, sometimes preceding the rash), digestive-tract symptoms ("belly pain, nausea, vomiting and bloody stools," which can also precede the rash), and kidney involvement. This boy\'s rash appearing "in crops" over a week, together with joint pain and severe abdominal pain, is this exact triad — the rash presenting in successive crops reflects the episodic, small-vessel vasculitic process the lecture describes.\n\n**Why each distractor fails.** *Gastric bleed* and *gastric ulcer* could each cause abdominal pain but neither explains a purpuric rash appearing in crops or joint pain — they are single-system findings being asked to cover a multisystem picture. *Systemic lupus erythematosus* can cause joint pain and abdominal symptoms, but its classic rash is a malar (facial) or photosensitive rash, not a crops-of-purpura pattern on the legs, and SLE is also considerably less common than HSP in this age group. *Varicella zoster* produces a vesicular, itchy rash in crops of blisters, not palpable purpura, and does not typically cause severe abdominal pain and arthralgia as a triad.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Purpuric rash in crops on the legs with joint pain and abdominal pain in a school-age child is Henoch-Schonlein purpura, an IgA-mediated small-vessel vasculitis.',
  source:'Pediatrics endpoint part1.pdf p.518'
},

{
  id:'pedep-gi-53', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A 3-month-old male infant presents with episodes of drawing up his legs, crying and redcurrant jelly-like stools. What investigation would confirm the most likely diagnosis?',
  options:['Abdominal computerized tomography (CT)','Abdominal magnetic resonance imaging (MRI)','Abdominal ultrasound','Abdominal X-ray','C-reactive protein (CRP) test'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Ultrasound is the diagnostic test of choice for intussusception, showing the characteristic "target" or "donut" sign.\n\n---\n\n**Why ultrasound is the confirmatory test.** `24)Abdominal pain.txt` names intussusception as the leading cause of intestinal obstruction in infants after the neonatal period, peaking at 3 months to 2 years — this boy is right at the start of that peak — and drawing up the legs with crying, plus redcurrant-jelly stool, is its classic bedside description. *Abdominal ultrasound is the first-line imaging test used to confirm the diagnosis, because the invaginated bowel loop produces a recognisable "target" or "donut" sign on a transverse scan — a radiation-free, rapid, highly sensitive test (not taken from the course material, which names the clinical picture but not the specific confirmatory imaging modality).*\n\n**Why each distractor is wrong.** *CT* can also show intussusception but carries ionising radiation and is not needed as a first-line test in an infant when ultrasound is available and equally diagnostic. *MRI* is not a practical first-line emergency investigation in an acutely unwell infant — it is slow and usually requires sedation. *Abdominal X-ray* may show nonspecific signs of obstruction or a soft-tissue mass but cannot reliably confirm intussusception the way a targeted ultrasound can. *CRP* is a nonspecific inflammatory marker that cannot make an anatomical diagnosis at all.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Abdominal ultrasound, showing the target/donut sign, is the first-line confirmatory investigation for suspected intussusception.',
  source:'Pediatrics endpoint part1.pdf p.520'
},

{
  id:'pedep-gi-54', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A common clinical condition that mimics appendicitis in children is:',
  options:['Mesenteric lymphadenitis','Pyloric stenosis','Intussusception','Peptic ulcer disease'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Mesenteric lymphadenitis can cause right lower quadrant pain and tenderness, mimicking appendicitis, especially after viral infections.\n\n---\n\n**Why mesenteric lymphadenitis is the classic mimic.** `24)Abdominal pain.txt` describes "non-specific abdominal pain and mesenteric adenitis" as abdominal pain that "resolves in 24-48 hours," is "less severe than in appendicitis," with variable tenderness in the right iliac fossa, and is "often accompanied by an upper respiratory tract infection with cervical lymphadenopathy." That right-iliac-fossa location is exactly why it is confused with appendicitis at the bedside — inflamed mesenteric nodes, usually reactive to a preceding viral illness, sit near enough to the appendix to produce a similar pain distribution, but the pain is milder and self-limiting rather than progressive and surgical.\n\n**Why each distractor is wrong.** *Pyloric stenosis* presents in early infancy (2-8 weeks) with projectile, non-bilious vomiting and a palpable "olive" mass in the upper abdomen — a completely different age group and clinical picture from appendicitis. *Intussusception* has its own distinct triad of colicky pain, a mass and redcurrant-jelly stool, and occurs in a younger age band (peak 3 months-2 years); while it is a genuine differential for acute abdominal pain, it is not the condition specifically known for closely mimicking the right-iliac-fossa presentation of appendicitis the way mesenteric lymphadenitis is. *Peptic ulcer disease* is uncommon in children and typically produces epigastric pain related to meals, not localised right lower quadrant tenderness.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Mesenteric lymphadenitis, often following a viral upper respiratory infection, is the classic self-limiting mimic of appendicitis in children.',
  source:'Pediatrics endpoint part1.pdf p.522'
},

{
  id:'pedep-gi-55', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'Surgical management of gastroesophageal reflux in infants is indicated:',
  options:['In all cases after 6 months of age','Only in severe cases not responding to medical therapy','As soon as reflux is diagnosed','In every child with vomiting'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Surgery is reserved for complications or failure of conservative management, not all infants with reflux.\n\n---\n\n**Why surgery is reserved for severe, refractory cases.** `22)Vomiting.txt` states surgical management (Nissen fundoplication) is "reserved for children with complications unresponsive to intensive medical treatment or oesophageal stricture." The lecture\'s own management ladder runs from parental reassurance and feeding changes, through thickening agents and alginate therapy, to acid-suppressing drugs (H2 antagonists or proton-pump inhibitors) for reflux disease — surgery sits only at the very end of that ladder, for the minority who fail every medical step or develop a stricture.\n\n**Why each distractor is wrong.** *"In all cases after 6 months of age"* has no basis in the lecture — most infants with simple reflux have already resolved or are resolving by then, since "most cases resolve spontaneously by 12 months of age," and age alone is never the trigger for surgery. *"As soon as reflux is diagnosed"* contradicts the entire stepped-management approach the lecture teaches, where reassurance and conservative measures come first for the large majority of infants who need nothing more. *"In every child with vomiting"* massively over-treats: most vomiting in infancy is simple reflux or feeding-related and needs no intervention at all, let alone surgery, which is reserved for the rare complicated or resistant case.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Surgical treatment of infant GORD (Nissen fundoplication) is reserved for complications or failure of maximal medical therapy, never a routine or early step.',
  source:'Pediatrics endpoint part1.pdf p.524'
},

{
  id:'pedep-gi-56', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'In management of gastroenteritis, breastfeeding and milk feeds should be:',
  options:['Stopped immediately','Replaced with fruit juices','Continued as usual','Delayed until recovery'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Breastfeeding should continue during gastroenteritis as it provides fluids and nutrients, unless contraindicated.\n\n---\n\n**Why feeding continues as usual.** `23).1) Acute diarrhea.txt` is explicit under "Feeding during and after diarrhea": for breastfed infants, "continue breast feeding as usual during and after rehydration therapy," and for formula-fed infants, "continue same “normal” formula and same “normal” concentration AFTER rehydration," reserving lactose-free formula only for confirmed secondary lactose intolerance. For children on a mixed diet the lecture likewise advises continuing normal feeding with small, frequent meals, avoiding only over-sweetened, high-fibre, laxative or fatty foods — nowhere does it support stopping or delaying feeds.\n\n**Why each distractor is wrong.** *Stopping feeding immediately* deprives the child of fluid and calories during an illness that is already causing losses, worsening both dehydration and nutritional status — the opposite of the lecture\'s advice. *Replacing milk with fruit juice* removes protective, nutrient-dense breast milk or formula in favour of a high-sugar fluid that can itself worsen osmotic diarrhoea; the lecture\'s own recommended home-based fluids list plain, weak or unsweetened options, not fruit juice as a milk substitute. *Delaying feeding until recovery* is the same error as stopping feeds — the lecture\'s whole feeding-during-diarrhoea section exists specifically to counter this outdated practice, since prolonged starvation is even listed elsewhere in the lecture as a factor that worsens the course of diarrhoeal illness.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Breastfeeding and normal milk feeds should continue throughout an episode of gastroenteritis, not be stopped, delayed, or replaced with juice.',
  source:'Pediatrics endpoint part1.pdf p.526'
},

{
  id:'pedep-gi-57', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'In acute appendicitis, the initial pain is typically:',
  options:['Right iliac fossa, constant','Central, colicky','Left hypochondrium','Epigastric burning'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Appendicitis often starts as periumbilical, colicky pain before localizing to the right lower quadrant as inflammation progresses.\n\n---\n\n**Why central, colicky pain is the initial pattern.** `24)Abdominal pain.txt` gives the "classic picture" in older children as "fever, nausea, vomiting, right lower quadrant pain, tenderness and rigidity," but this represents the *established* stage. *The migration from an initial vague, central (periumbilical) colicky pain — from early visceral distension of the appendix, referred to the midline via the embryological midgut innervation — to a later, sharper, localised right iliac fossa pain once the inflamed appendix irritates the adjacent parietal peritoneum, is standard surgical teaching (not spelled out step-by-step in this lecture; not taken from the course material for the visceral-to-parietal mechanism specifically).* This staged progression is exactly why appendicitis is notoriously easy to miss early: the pain does not start where it will eventually localise.\n\n**Why each distractor is wrong.** *Right iliac fossa, constant* describes the later, established stage of appendicitis, once localisation and peritoneal irritation have occurred — not the initial presentation the question asks about. *Left hypochondrium* pain is not a recognised feature of appendicitis at any stage; that region overlies the spleen and left upper abdominal organs, not the appendix or its referred pain pattern. *Epigastric burning* is a dyspeptic pattern typical of peptic or gastritis-type pain, not the periumbilical colic of early appendicitis.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Acute appendicitis classically begins as vague, central, colicky pain that migrates to constant right iliac fossa pain only as inflammation progresses to the parietal peritoneum.',
  source:'Pediatrics endpoint part1.pdf p.528'
},

{
  id:'pedep-gi-58', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'Maternal polyhydramnios is frequently observed in all the following conditions except:',
  options:['Esophageal atresia','Duodenal atresia','Hirschsprung disease','Pyloric atresia'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Polyhydramnios is seen in conditions where swallowing is impaired (esophageal or duodenal atresia). Hirschsprung usually causes postnatal obstruction, not polyhydramnios.\n\n---\n\n**Why Hirschsprung disease is the exception.** *Polyhydramnios develops antenatally when the fetus cannot adequately swallow and absorb amniotic fluid through its gut — so it is a marker of a HIGH, proximal obstruction that blocks swallowing itself, not of a low, distal one (not taken from the course material; the cached genetics and constipation decks do not connect Hirschsprung disease to amniotic fluid volume). Hirschsprung disease is a distal, colonic aganglionosis: swallowing and upper gut transit are entirely normal in utero, amniotic fluid is swallowed and absorbed as usual, and the functional obstruction it causes only becomes clinically apparent after birth, as delayed passage of meconium and abdominal distension — it does not raise amniotic fluid volume antenatally.*\n\n**Why each of the other three DOES cause polyhydramnios.** *Oesophageal atresia* blocks the fetal swallowing pathway at its very start, so essentially no swallowed fluid reaches the gut to be absorbed, producing a marked, classic polyhydramnios. *Duodenal atresia* obstructs just distal to the stomach — swallowed fluid reaches the stomach and duodenum but cannot pass further to be absorbed by the small bowel — also producing polyhydramnios, with the characteristic postnatal "double bubble" sign this bank tests separately in `pedep-gi-46`. *Pyloric atresia* likewise obstructs proximally, at the gastric outlet, before any meaningful fluid absorption downstream, again producing polyhydramnios.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Polyhydramnios marks a HIGH fetal gut obstruction that blocks swallowing (oesophageal, duodenal or pyloric atresia); Hirschsprung disease is a distal, postnatal obstruction and does not raise amniotic fluid volume.',
  source:'Pediatrics endpoint part1.pdf p.530'
},

{
  id:'pedep-gi-59', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 2-month-old baby is seen in the pediatric outpatient department. She was born at term, weighing 3.5 kg, and is breastfed. Her mother is concerned as she has vomited some of the milk after most feeds since birth. She cries when she vomits. She is continuing to grow along the 50th centile. What is the most likely diagnosis?',
  options:['Gastroesophageal reflux','Gastroenteritis','Infant colic','Overfeeding','Pyloric stenosis'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Reflux is common, especially if baby is thriving and growing normally. Red flags (projectile vomiting, poor growth) are absent.\n\n---\n\n**Why reflux fits.** `22)Vomiting.txt` describes gastro-oesophageal reflux as "very common in infancy," caused by functional immaturity of the lower oesophageal sphincter, a predominantly fluid diet and a horizontal posture — exactly the physiology of a 2-month-old who has vomited after most feeds "since birth." Her steady growth along the 50th centile matches the lecture\'s statement that "most infants with gastro-oesophageal reflux are putting on weight normally," and there is no red flag such as projectile vomiting, bile staining or faltering growth to suggest anything more serious.\n\n**Why each distractor is wrong.** *Gastroenteritis* is an acute, usually self-limited illness with diarrhoea as its defining feature, not a symptom present "since birth" with steady growth. *Infant colic* causes excessive crying, typically in bouts, but is not primarily a vomiting disorder. *Overfeeding* is a plausible mimic, but the lecture treats reflux, not overfeeding, as the default diagnosis once thriving and normal growth are established, and nothing in the vignette (such as very large feed volumes) specifically points to overfeeding instead. *Pyloric stenosis* is excluded by the pattern here: it is not present "since birth" in a mild, non-progressive form, and this baby is not projectile-vomiting or failing to thrive — the lecture places pyloric stenosis at 2-8 weeks with vomiting that "increases in frequency and forcefulness over time," not this stable, well-tolerated pattern.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A thriving infant who vomits after most feeds since birth, with normal growth and no red flags, has physiological gastro-oesophageal reflux, not pyloric stenosis or overfeeding.',
  source:'Pediatrics endpoint part1.pdf p.532'
},

{
  id:'pedep-gi-60', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'An 8-year-old girl presents with a 6-month history of pain most days around the umbilicus which lasts for an hour and responds to paracetamol syrup. It does not occur at weekends usually. She opens her bowels daily and passes a soft stool. She is thriving with her weight and height on the 75th centile. Which of the following options is the appropriate next step?',
  options:['Abdominal radiograph','Referral to a pediatric gastroenterologist','Liver function tests','Reassurance and no further investigation','Prescription for laxatives'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> The girl\'s pain is functional abdominal pain since growth and examination are normal, and symptoms stop on weekends. No further tests are needed.\n\n---\n\n**Why reassurance alone is correct.** `24)Abdominal pain.txt` defines chronic/recurrent abdominal pain as at least monthly pain over two consecutive months interfering with function — this six-month history fits — and lists the features that separate organic from functional pain: functional pain is typically "vague, midline" in site, "never nocturnal," and, critically, alarm signals such as weight loss, growth deceleration, nocturnal waking and blood in stool are absent. Every one of those distinguishing points is satisfied here: periumbilical (vague, midline) pain, growth tracking a healthy 75th centile, daily soft stools (no constipation or diarrhoea), and — the most telling clue — a symptom-free pattern on weekends, which strongly suggests a psychosocial or school-related trigger rather than an organic disease process. The lecture\'s own stepwise algorithm states that once alarm signals are screened out and absent, the working diagnosis is a pain-related functional gastrointestinal disorder, managed with reassurance rather than escalating investigation.\n\n**Why each distractor is wrong.** *Abdominal radiograph* and *liver function tests* are organic-disease screens that the absence of alarm signals argues against ordering. *Referral to a paediatric gastroenterologist* is reserved for children with alarm features or who fail an initial period of reassurance and simple management, neither of which applies here. *Laxatives* would only be appropriate if constipation were present, but this girl already opens her bowels daily and passes soft stool, so there is no constipation to treat.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A school-age child with weekday-only, periumbilical pain, normal growth and no alarm signals has functional abdominal pain, managed with reassurance alone, not investigation or referral.',
  source:'Pediatrics endpoint part1.pdf p.534'
},

{
  id:'pedep-gi-61', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'An 18-month-old girl is seen in the outpatient department. She presents with loose stools two to three times each day, with no blood in them. She is generally difficult, and it has become a battle to get her to feed. Examination of her abdomen, although difficult due to distress at being examined, is unremarkable apart from being distended. She is not on any medication. Her weight was at the 9th centile and is now below the 0.4th centile. What is the most likely cause for weight loss?',
  options:['Chronic non-specific diarrhea','Celiac disease','Hirschsprung disease','Lactose intolerance','Ulcerative colitis'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Failure to thrive, distended abdomen, and persistent diarrhea with weight dropping below centiles strongly suggest malabsorption due to celiac disease.\n\n---\n\n**Why celiac disease fits.** `23).1) Acute diarrhea.txt` lists "sensitivity to milk, gluten" among the non-infectious causes of chronic diarrhoea. *Coeliac disease produces gluten-driven villous atrophy and malabsorption, classically presenting around weaning onto gluten-containing cereals with loose stools, a distended abdomen from bloating and gas, irritability/feeding difficulty, and a crossing-down of weight centiles from malabsorbed nutrients (not spelled out in this level of clinical detail in the cached lecture, which names coeliac only as a category of chronic diarrhoea; not taken from the course material for the specific presentation described).* This girl\'s dramatic centile crossing (9th down to below 0.4th), distended abdomen and feeding difficulty is the classic malabsorptive weight-loss picture, distinct from a simple, well-child chronic diarrhoea.\n\n**Why each distractor fits the stool pattern less well.** *Chronic non-specific (toddler\'s) diarrhoea* is explicitly a benign diagnosis with normal growth — this bank\'s own `pedep-gi-63` shows the same label paired with a child still "growing along the 50th centile," the opposite of this girl\'s severe faltering growth. *Hirschsprung disease* causes constipation and obstruction, not loose stools with malabsorptive weight loss. *Lactose intolerance* causes loose, watery, often frothy stools after dairy but is not typically associated with such severe faltering growth if the rest of the diet is adequate. *Ulcerative colitis* classically causes bloody diarrhoea, which is explicitly absent here.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Loose non-bloody stools with a distended abdomen and severe centile-crossing weight loss around toddler age is the malabsorptive picture of coeliac disease, not benign toddler\'s diarrhoea.',
  source:'Pediatrics endpoint part1.pdf p.536'
},

{
  id:'pedep-gi-62', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'A 2-year-old boy is seen in the pediatric emergency department. He has been vomiting and has had diarrhea for 3 days. His stool is watery and foul-smelling but has no blood in it. Examination reveals mild dehydration but is otherwise normal. What is the most likely organism that has caused his symptoms?',
  options:['Campylobacter','Escherichia coli','Giardia lamblia','Rotavirus','Shigella'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Rotavirus is the most common cause of acute viral gastroenteritis in young children, presenting with watery diarrhea and vomiting.\n\n---\n\n**This question shares its five-organism option list with `pedep-gi-1`** — the reasoning for why rotavirus outranks each of the other four organisms on that ladder is written there in full. This entry\'s own discriminating token is the age and setting: a 2-year-old with a 3-day history of vomiting plus watery, foul-smelling, non-bloody diarrhoea and only mild dehydration is squarely the classic acute rotavirus picture — `23).1) Acute diarrhea.txt` names rotavirus as the leading single cause of acute watery diarrhoea, within the roughly 70% of cases caused by viruses overall, and describes the illness as beginning acutely and lasting under two weeks, matching this short, self-limited, non-bloody course exactly.\n\n**Why the same four distractors fail here as on the shared ladder.** *Campylobacter*, *E. coli* and *Shigella* are bacterial causes, together accounting for only 10-20% of cases, and the lecture ties bacterial and dysenteric causes to blood in the stool and more severe systemic illness — absent here. *Giardia lamblia* is a protozoal cause (under 10% of cases) that more typically produces a persistent or malabsorptive picture rather than this acute, short, watery illness.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A short, acute, non-bloody watery diarrhoeal illness with vomiting and mild dehydration in a toddler is classic rotavirus gastroenteritis, the leading viral cause of acute diarrhoea.',
  source:'Pediatrics endpoint part1.pdf p.538'
},

{
  id:'pedep-gi-63', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'A 2-year-old boy has had diarrhea for the last 3 months. He produces up to four stools a day, which are loose, brown in color, and usually contain undigested food. The rest of the family is well. Examination is normal, and his personal child health record shows that he is growing along the 50th centile. What is the most likely diagnosis?',
  options:['Chronic non-specific diarrhea','Post-gastroenteritis syndrome','Cow\'s milk protein allergy','Inflammatory bowel disease','Lactose intolerance'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> This benign toddler\'s diarrhea shows loose stools with normal growth and no systemic illness.\n\n---\n\n**Why chronic non-specific (toddler\'s) diarrhoea fits.** `23).1) Acute diarrhea.txt` classifies "chronic diarrhea" among its main diarrhoea types and, separately, describes "persistent diarrhea" as usually post-infectious and associated with nutritional deterioration — the key distinguishing feature the lecture gives for that more worrying category is a link to malnutrition and weight loss. This boy has neither: he is "growing along the 50th centile" with an entirely normal examination, and his stool — loose, containing undigested food, several times a day, over months, in an otherwise thriving toddler — is the textbook description of chronic non-specific diarrhoea (toddler\'s diarrhoea), a benign motility variant rather than a disease process *(the specific label and stool description are standard toddler-diarrhoea teaching; not spelled out under that name in the cached lecture, so this detail is not taken from the course material)*.\n\n**Why each distractor is wrong.** *Post-gastroenteritis syndrome* follows a specific acute infective episode with ongoing malabsorption, not this insidious three-month history without a preceding acute illness described. *Cow\'s milk protein allergy* typically also produces other allergic features (eczema, blood/mucus in stool, or feeding-related distress) and is not this well-tolerated, growth-preserved picture. *Inflammatory bowel disease* would be expected to impair growth and often cause blood in the stool — both explicitly absent here, and the normal growth trajectory argues strongly against it. *Lactose intolerance* causes diarrhoea tied to dairy intake, not this constant three-month pattern independent of any noted dietary trigger.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Loose stools containing undigested food for months in a thriving, normally growing toddler with a normal examination is chronic non-specific (toddler\'s) diarrhoea, a benign diagnosis of normal growth.',
  source:'Pediatrics endpoint part1.pdf p.540'
},

{
  id:'pedep-gi-64', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'What is the most common cause of recurrent abdominal pain in children?',
  options:['Appendicitis','Ascariasis','Functional','Hepatitis'],
  answer:2,
  explanation:'**Functional abdominal pain is the most common cause of recurrent abdominal pain in children.** `24)Abdominal pain.txt` defines recurrent (chronic) abdominal pain as at least one episode of pain a month for two consecutive months, severe enough to interfere with routine functioning, and states this "occurs in 10-15% of children" — a scale far larger than any single organic diagnosis. The lecture frames functional pain explicitly as "a Diagnosis of Exclusion," reached by history, examination and initial screening tests once the much rarer organic causes have been ruled out, and separates functional from organic pain by site (vague, midline rather than localised), timing (never nocturnal, unlike organic pain which may wake the child) and the absence of the alarm signals — weight loss, growth deceleration, blood in stool, family history of organic GI disease — that would point toward disease instead.\n\n**Why each distractor is wrong.** *Appendicitis* is an important acute surgical emergency, but it is a single episode of acute, not recurrent, pain, and it is far less common overall than the broad functional-pain group. *Ascariasis*, an intestinal worm infestation, can cause abdominal pain and even mechanical obstruction of the pancreatic duct in heavy infestations, but it is one specific, geographically variable organic cause, not the dominant one across the general paediatric population that this lecture\'s 10-15% figure describes. *Hepatitis* causes right-upper-quadrant pain as part of a broader illness with jaundice and malaise, not the isolated, recurring pain pattern the question is asking about, and is again a single organic cause rather than the leading overall category.\n\nWritten for this bank — Pediatrics endpoint part1.pdf prints no explanation here.',
  objective:'Functional abdominal pain — a diagnosis of exclusion once organic causes and alarm signals are screened out — is the most common cause of recurrent abdominal pain in children, affecting 10-15% overall.',
  source:'Pediatrics endpoint part1.pdf p.542'
},

{
  id:'pedep-gi-65', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'What is the most common cause of gastroenteritis in children?',
  options:['Shigella','Giardia','Cryptosporidium','Viruses','Campylobacter jejuni'],
  answer:3,
  explanation:'**Viruses are the leading cause of acute gastroenteritis in children.** `23).1) Acute diarrhea.txt` states that acute watery diarrhoea (acute gastroenteritis) makes up about 80% of all diarrhoea in children, and that within that group, viruses cause roughly 70% of cases — well ahead of bacteria (10-20%) and protozoa (under 10%). The lecture names rotavirus, norovirus, enteric adenoviruses, caliciviruses, astroviruses and enteroviruses as the leading viral agents, and separately identifies rotavirus specifically as one of the most important causes of acute infective diarrhoea in developing countries. This is also why rotavirus immunisation is highlighted in the lecture\'s prevention section — targeting the single largest contributor to the disease burden.\n\n**Why each named organism is wrong on its own.** *Shigella* and *Campylobacter jejuni* are both bacterial causes, together making up only part of the 10-20% bacterial share, and are specifically linked in the lecture to dysentery (bloody, tenesmus-associated diarrhoea) rather than the ordinary watery gastroenteritis that dominates overall numbers. *Giardia* and *Cryptosporidium* are both protozoal causes, the smallest of the three groups at under 10% of cases, and tend to produce more persistent or malabsorptive illness rather than accounting for most acute gastroenteritis presentations.\n\nWritten for this bank — Pediatrics endpoint part1.pdf prints no explanation here.',
  objective:'Viruses cause roughly 70% of acute paediatric gastroenteritis, making them the leading cause overall, ahead of bacteria and protozoa combined.',
  source:'Pediatrics endpoint part1.pdf p.544'
},

{
  id:'pedep-gi-66', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'What is true about the management of gastroesophageal reflux in children?',
  options:['Parents can be reassured; it is a process the child will outgrow as they get older','Thickening the feedings does not work','Most infants have slow weight gain','It always deserves further evaluation','Surgery is indicated in preterm infants'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Most infants with GER are “happy spitters,” and reassurance is sufficient. It usually resolves by 12–18 months.\n\n---\n\n**Why parental reassurance is the true statement.** `22)Vomiting.txt` states that reflux "most cases resolve spontaneously by 12 months of age due to a combination of maturation of the lower oesophageal sphincter, an upright posture and more solids in the diet," and lists "parental reassurance" first among its management measures — this bank\'s own box adds the memorable clinical term "happy spitters" for these thriving, otherwise well infants, extending slightly beyond the lecture\'s wording but consistent with its message *(the specific phrase "happy spitters" itself is not printed in the cached lecture; not taken from the course material)*.\n\n**Why each distractor is wrong.** *"Thickening the feedings does not work"* contradicts the lecture\'s management list, which specifically offers "adding inert thickening agents to feeds" as a recognised measure. *"Most infants have slow weight gain"* reverses the lecture\'s own statement that "most infants with gastro-oesophageal reflux are putting on weight normally." *"It always deserves further evaluation"* contradicts the lecture\'s statement that reflux "is usually diagnosed clinically, and no investigations are required" unless the history is atypical or complicated. *"Surgery is indicated in preterm infants"* misstates the surgical criterion: the lecture reserves surgery for "complications unresponsive to intensive medical treatment or oesophageal stricture," a functional threshold, not prematurity itself, though preterm infants are separately listed as a group in whom reflux disease is more common overall.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Most infants with gastro-oesophageal reflux are thriving "happy spitters" who need only parental reassurance, since the condition usually resolves spontaneously by 12-18 months.',
  source:'Pediatrics endpoint part1.pdf p.546'
},

{
  id:'pedep-gi-67', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'Which is a medical cause of acute abdominal pain?',
  options:['Diabetic ketoacidosis','Thalassemia major','Hyperglycemia','Hemosiderosis','Acute hemolytic anemia'],
  answer:0,
  explanation:'**Diabetic ketoacidosis is a recognised medical (non-surgical) cause of acute abdominal pain in children.** `24)Abdominal pain.txt` lists diabetic ketoacidosis explicitly among the "Important Extra-Abdominal Causes" of abdominal pain, alongside pharyngitis, abdominal migraine, familial Mediterranean fever, Henoch-Schonlein purpura, sickle cell disease, pneumonia, HUS, drugs and lead poisoning, and again under "Other causes" of acute abdominal pain alongside acute pancreatitis, lower-lobe pneumonia and HSP. DKA produces genuine, sometimes severe, abdominal pain through a combination of the metabolic acidosis itself, dehydration and ileus — a classic trap where the abdominal pain can mimic a surgical abdomen and delay recognition of the underlying metabolic emergency (the precise mechanism of DKA-related abdominal pain is standard endocrine teaching beyond what this lecture\'s single list-entry states; *not taken from the course material* for that mechanistic detail).\n\n**Why each distractor is wrong.** *Thalassaemia major*, *hyperglycaemia* alone (without ketoacidosis), *haemosiderosis* and *acute haemolytic anaemia* are haematological or metabolic states that are not named anywhere in this lecture\'s lists of causes of acute abdominal pain — hyperglycaemia without acidosis is typically asymptomatic abdominally, and the others are chronic or systemic haematological conditions without a recognised acute-abdomen presentation in this material.\n\nWritten for this bank — Pediatrics endpoint part1.pdf prints no explanation here.',
  objective:'Diabetic ketoacidosis is a medical (extra-abdominal) cause of acute abdominal pain and a recognised mimic of a surgical abdomen in children.',
  source:'Pediatrics endpoint part1.pdf p.548'
},
