/* Peds ENDPOINT PART 2 -- Section 1 "Normal Development", DRAFT half A (n:1..14, ids pedep2-nd-1..14).
   Source of truth: endpoint-p2-s01-normal-dev.array.js (PEDEP2_S01_STAGED).
   Grounding: content/peds/lectures/1) Normal development.txt (pptx, 60 slides) and
   content/peds/lectures/Lec 1 Normal development_.txt (pdf, milestone table + median/limit-age
   teaching). Bare fragment -- validated with node tools/bank-harness/val-pd-ep2.js 1 A. */

{ id: 'pedep2-nd-1',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: "Steven has just had his first birthday party. During his party, he commando crawled with great speed, although he cannot walk. He managed to pick off all the Smarties (round chocolate sweets) from his birthday cake. He can say two words with meaning. After his birthday party, he impressed his guests by waving goodbye. Which area of Steven's development is delayed?",
  options: ['Fine motor and vision', 'Gross motor', 'Social, emotional, and behavioral development', 'Speech and hearing', 'None – his development is within normal limits'],
  answer: 4,
  explanation: "Every domain Steven shows is on time for 12 months, which is why the correct answer is that his development is within normal limits.\n\nGross motor: commando (belly) crawling with speed but not yet walking at his first birthday is not a red flag. Independent walking has a median age of 12 months, but the limit age — the age by which about 90–95% of children have achieved a milestone, beyond which assessment is warranted — is 18 months. A child who is already mobile by fast crawling and simply has not walked yet at exactly one year sits comfortably inside that normal range.\n\nFine motor and vision: picking individual Smarties off the cake one at a time is a mature pincer grasp (thumb-to-index-finger opposition), the fine motor skill expected to be established by 12 months; the immature version of this grasp is already emerging from around 9–10 months.\n\nSpeech and hearing: using two words with meaning is exactly the 12-month language milestone (typically 1–2 meaningful words, classically \"mama\"/\"papa\"), so this domain is on schedule rather than delayed.\n\nSocial, emotional, and behavioral development: waving goodbye to the party guests is the classic \"bye-bye\" social milestone, itself usually already present from around 10–12 months.\n\nSo options A–D each name a domain Steven is actually meeting on time; none of them is the delayed one, which is why the printed key is E.\n\nWritten for this bank — Pediatrics endpoint part2.pdf prints no explanation here.",
  objective: 'Recognize that a single gross-motor milestone not yet reached, while still inside its normal range, does not make that domain delayed.',
  source: 'Pediatrics endpoint part2.pdf p.19' },

{ id: 'pedep2-nd-2',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Sophie is a well-born 8-week-old baby who was born at term. She has come for a routine developmental check. Which of the following would you NOT expect her to be able to do?',
  options: ['Auditory brainstem response audiometry', 'Fix and follow a toy', 'Quiet to a loud noise', 'Raise her head when lying prone', 'Reach out and grasp an object'],
  answer: 4,
  explanation: "**The endpoint file prints this explanation:**\n\n> At 8 weeks, babies can fix and follow, respond to noise, and lift their head briefly when prone. Reaching and grasping is expected later, around 3–4 months.\n\n---\n\nAt around 6 weeks a term infant already lifts the head briefly when prone, fixes and follows a face or toy, and shows a social smile; by 8 weeks these skills are consolidating, which is why options B (fixing and following), C (quieting to a loud noise, an auditory orienting response present from the newborn period), and D (raising the head briefly when prone) are all things you would expect Sophie to do. Option A, auditory brainstem response audiometry, is not a skill an infant performs at all — it is a hearing-screening test, and in the UK it is normally carried out as part of the newborn hearing screen before or shortly after discharge, so it is not something still pending at 8 weeks; this specific screening timeline is not covered in the cached lecture material for this chapter — not taken from the course material. The key, option E, is the one genuine \"not yet\" on this list: reaching out and deliberately grasping an object needs voluntary hand-eye coordination and release of the strong newborn palmar grasp reflex, and this only becomes reliable from about 3–4 months, well after 8 weeks.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Identify which 8-week milestones are already present and which fine motor skill is still to come.',
  source: 'Pediatrics endpoint part2.pdf p.22' },

{ id: 'pedep2-nd-3',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Joanna is an active toddler. She is just being potty trained and has had several days where she has remained dry. She enjoys pulling her clothes off to use the potty but cannot dress herself again. She enjoys playing by pretending to make her mother a cup of tea but does not play well with her older siblings, as she has not yet learned how to take turns. She is very bossy and demands things by saying "give me" or "me drink". She can build a tower of six blocks and enjoys running and climbing on furniture. What developmental age is Joanna?',
  options: ['12 months', '18 months', '24 months', '2.5 years', '3 years'],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> Pretend play, potty training, and building a six-block tower are typical for a 2-year-old. Difficulty taking turns is normal at this age.\n\n---\n\nEvery clue in the stem lines up with the 2-year (19–24 month) row of the course's milestone table. Building a tower of six cubes is the fine-motor marker listed for 2 years; pretend play — Joanna \"making her mother a cup of tea\" — is the cognitive milestone described for the 18–24 month band; her telegraphic two-word demands (\"give me\", \"me drink\") match the language stage of simple two-word phrases and the 2-year tally of joining 2–3 words in a sentence. Running and climbing fits the 2-year gross-motor picture of running well and negotiating stairs two feet per step. Her difficulty taking turns with her siblings is not itself abnormal: parallel play, not the cooperative, turn-taking play of a 3-year-old, is what is expected at 2 years — cooperative play is not expected to begin until around 3 years. Early potty-training success with several dry days, and being able to pull clothing off but not yet dress herself again, are both consistent with an emerging-but-incomplete self-care picture around 2 years; the exact ages for potty training and dressing are not itemized in the cached milestone table, so this part is general pediatric knowledge — not taken from the course material. The younger options (12 and 18 months) are too early for a six-cube tower, pretend play, or two-word phrases — an 18-month-old is still mostly scribbling and typically has around six single words — while the older options (2.5 and 3 years) would already show cooperative play and more independent dressing, neither of which Joanna has reached yet.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Map a toddler's mixed clues across play, self-care, language, and motor skill onto a single developmental age.",
  source: 'Pediatrics endpoint part2.pdf p.24' },

{ id: 'pedep2-nd-4',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Rosette can build a three-cube tower and can point to her nose. At what age would one expect that child to achieve the milestones described in this scenario (median age)?',
  options: ['6 weeks', '6 months', '8 months', '18 months', '12 months'],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Pointing to body parts and building a 3-block tower are milestones commonly reached at 18 months.\n\n---\n\nThis five-rung ladder — 6 weeks, 6 months, 8 months, 18 months, 12 months — reappears unchanged in `pedep2-nd-5`, so the rungs are worked through in full here and that sibling entry adds only its own discriminating clue.\n\n| Age | What this rung marks |\n|---|---|\n| 6 weeks | lifting the head briefly when prone, fixing and following, an early social smile |\n| 6 months | sitting with support, a palmar grasp with hand-to-hand transfer, babbling |\n| 8 months | sitting unsupported, with crawling just beginning to emerge |\n| 12 months | first independent steps for many children, a mature pincer grasp, and 1–2 meaningful words |\n| 18 months | walking independently and running stiffly, scribbling, building a tower of about three cubes, pointing to indicate interest and naming body parts, and a vocabulary of six or more words |\n\nRosette's combination — a three-cube tower plus pointing to her own nose (naming a body part) — sits squarely on the 18-month rung, which is why D is keyed here. `pedep2-nd-5`'s clue, taking first independent steps, belongs to the 12-month rung instead.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Place a fine-motor-plus-language clue on the correct rung of a shared age ladder.',
  source: 'Pediatrics endpoint part2.pdf p.26' },

{ id: 'pedep2-nd-5',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Peace has just taken her first steps! At what age would one expect that child to achieve the milestones described in this scenario (median age)?',
  options: ['6 weeks', '6 months', '8 months', '18 months', '12 months'],
  answer: 4,
  explanation: "**The endpoint file prints this explanation:**\n\n> Most children take their first independent steps around 12 months, though the range can vary slightly.\n\n---\n\nThis is the same five-rung age ladder as `pedep2-nd-4`, worked through there in full. Peace's clue is different: taking her very first independent steps is exactly the 12-month rung on that ladder — the median age at which most children first walk unsupported — rather than the 18-month rung, which already implies walking independently and running stiffly. That is why the key here is E (12 months) rather than D.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Distinguish a first-steps milestone from a later, more advanced walking milestone on a shared age ladder.',
  source: 'Pediatrics endpoint part2.pdf p.28' },

{ id: 'pedep2-nd-6',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Anthony has a friend at nursery, and they enjoy playing with toy cars together. At what age would one expect that child to achieve the milestones described in this scenario (median age)?',
  options: ['6 months', '12 months', '18 months', '24 months', '36 months'],
  answer: 4,
  explanation: "**The endpoint file prints this explanation:**\n\n> Playing interactively with peers (parallel or cooperative play) typically emerges by 3 years of age.\n\n---\n\nThis ladder (6, 12, 18, 24, and 36 months) is a different set of rungs from the 6-week-to-18-month ladder used in `pedep2-nd-4`/`pedep2-nd-5`, built around social play rather than motor and language. At 6 months a baby is mostly engaging one-to-one with a familiar caregiver and beginning to show stranger anxiety; at 12 months play is still largely solitary, centered on simple games such as peekaboo; by 18 months play is symbolic and self-directed (feeding self, simple pretend acts) rather than shared; at 24 months children characteristically show parallel play — playing alongside another child with the same toys but not yet together. What Anthony is doing — genuinely sharing the activity of playing with toy cars with a nursery friend — is cooperative play, the marker for around 3 years (36 months), which is why E is keyed rather than D.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Distinguish parallel play from genuinely cooperative play with a peer.',
  source: 'Pediatrics endpoint part2.pdf p.30' },

{ id: 'pedep2-nd-7',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Herbert can transfer objects from one hand to the other while sitting without support and with a straight back. At what age would one expect that child to achieve the milestones described in this scenario (median age)?',
  options: ['6 months', '8 months', '12 months', '18 months', '24 months'],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> Children transfer objects around 7 months of age. A rounded back requires control of T1 to T12, but a straight back requires T12 and L1 so develops later. A child will often 'sit' at 6 months but sit and be stable and with a straight back at 8 months\n\n---\n\nThe course's own milestone table lists sitting with support and transferring objects hand to hand together at 6 months, which looks at first like it could support the 6-month option here — but that table entry describes a supported, C-shaped sit, not the unsupported, straight-backed sit the stem specifically describes. The printed box's more detailed account resolves that: a rounded-back sit needs control down to only about T12, which most babies manage around 6 months, while a genuinely straight-backed, unsupported sit needs control extending to T12–L1, achieved only from about 8 months — and this is also the age by which object transfer becomes a reliably coordinated skill rather than an early, wobbly one. The older options (12, 18, and 24 months) describe a child who is already cruising, standing, or walking, well past the stage of learning to sit independently, so they are too late for what Herbert is doing.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Link a specific postural clue (straight-backed, unsupported sitting) to the correct rung of a spinal-maturation-based motor milestone.',
  source: 'Pediatrics endpoint part2.pdf p.32' },

{ id: 'pedep2-nd-8',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Grace enjoys drawing. She has just learned to copy drawing a square and can build steps using blocks after being shown. At what age would one expect that child to achieve the milestones described in this scenario (median age)?',
  options: ['1 year', '2 years', '3 years', '4 years', '5 years'],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Copying a square and building steps are fine motor skills expected around 4 years of age.\n\n---\n\nThis ladder — 1, 2, 3, 4, and 5 years — reappears in `pedep2-nd-12`, so the fine-motor progression across it is set out fully here.\n\n| Age | Fine motor marker |\n|---|---|\n| 1 year (12 months) | mature pincer grasp; drinks from a cup held with both hands |\n| 2 years | builds a tower of six cubes; scribbles circular shapes |\n| 3 years | copies a circle |\n| 4 years | copies a cross |\n| 5 years | copies a square |\n\nOne divergence is worth flagging here without disturbing the printed key: the printed box times copying a square at 4 years, but the cached course milestone table instead places copying a square at 5 years and copying a cross at 4 years. The composite scenario — copying a square together with building \"steps\" out of blocks after demonstration, a constructional task not itemized in the course table at all and usually described around 4 years in general pediatric teaching (not taken from the course material) — is what the printed box keys to option D, and that key is left exactly as printed. `pedep2-nd-12`'s clue, tying shoelaces unaided, sits at the far (5-year) end of this same ladder.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Place a fine-motor drawing-and-construction clue on the correct rung of a shared age ladder, and flag where the source disagrees with the course table.',
  source: 'Pediatrics endpoint part2.pdf p.34' },

{ id: 'pedep2-nd-9',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Rita’s father is thrilled that she has just said her first word—says "dada" to her father only. At what age would one expect that child to achieve the milestones described in this scenario (median age)?',
  options: ['6 months', '8 months', '10 months', '12 months', '24 months'],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> Many children will make double-syllable sounds which are not specific to an object or person. In this case, the word ‘dada’ is specific for her father and so indicates 10 months of age\n\n---\n\nThis ladder — 6, 8, 10, 12, and 24 months — reappears in `pedep2-nd-13`, so the language progression across it is worked through here.\n\n| Age | Language marker |\n|---|---|\n| 6 months | mono-syllabic babbling ('ba-ba') |\n| 8–10 months | polysyllabic babbling, understanding 'no' |\n| 10 months | a double-syllable sound used specifically for one person (per the printed box) |\n| 12 months | 1–2 meaningful words, classically 'mama'/'papa' |\n| 24 months | two-word sentences |\n\nThere is a small divergence worth recording without moving the key: the cached course milestone table lists meaningful words such as 'papa'/'mama' as the 12-month marker, while the printed box times the same kind of person-specific sound one rung earlier, at 10 months. Both are within the normal range described by the course's own median-versus-limit-age teaching — a median age is only where half of children have reached a skill, so some ordinary variation between two teaching sources is expected — and the printed key, C (10 months), is left exactly as printed. `pedep2-nd-13`'s clue, starting to crawl, sits at the 8-month rung of this same ladder.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Place a person-specific first word on the correct rung of a shared language age ladder.',
  source: 'Pediatrics endpoint part2.pdf p.36' },

{ id: 'pedep2-nd-10',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: "Rinah can follow her mother's two-step commands, such as \"Go to the cupboard and fetch your red shoes\". At what age would one expect that child to achieve the milestones described in this scenario (median age)?",
  options: ['6 months', '12 months', '2 years', '3 years', '4 years'],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Following two-step commands typically develops by 3 years of age, showing increased language comprehension.\n\n---\n\nThere is a real divergence worth recording here without moving the key: the course's own cognitive-milestones slide lists following two-step commands under the 18–24 month band, a year to a year and a half earlier than the age this printed box gives. The printed key, D (3 years), is left exactly as it is keyed; the box's own reasoning — that following a compound instruction like this one shows more mature receptive language than a single instruction — is the reasoning followed here. The younger options (6 months, 12 months) describe a stage where even single-word comprehension (understanding \"no\") is only just developing, so a two-part instruction naming a location, an object, and a colour would be well beyond what is expected; the closest distractor, 2 years, is exactly where the course's other source (the slide) would in fact place this skill, which is the divergence flagged above.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Recognize the receptive-language marker of following a two-step instruction, and flag where the source disagrees with the course slide.',
  source: 'Pediatrics endpoint part2.pdf p.38' },

{ id: 'pedep2-nd-11',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: "Blessing's mother is so pleased; her baby has just learned to smile when she smiles at her! At what age would one expect that child to achieve the milestones described in this scenario (median age)?",
  options: ['6 weeks', '12 weeks', '6 months', '12 months', '18 months'],
  answer: 0,
  explanation: "**The endpoint file prints this explanation:**\n\n> Social smiling in response to a caregiver’s smile usually appears around 6 weeks of age.\n\n---\n\nThe course's milestone table lists a social smile as the marker for the 6-week row directly, matching the printed key exactly. The lecture slide deck describes the same skill slightly differently across two adjacent slides — \"regards face\" at 1 month and an explicit \"SOCIAL SMILE\" label at 2 months — but this is ordinary teaching variation around a genuinely gradual skill (a reflex-like early smile in the first few weeks becoming a reliable, reciprocal social smile by 6–8 weeks) rather than a contradiction, so nothing here moves the key. The older options — 12 weeks, 6, 12, and 18 months — all describe stages where social smiling is already long-established and other, more advanced social skills are the ones actually being newly acquired instead: recognizing familiar people and showing stranger anxiety by 6 months, waving bye-bye by 12 months, and increasingly symbolic play by 18 months — which is why none of them fit a milestone that has \"just\" appeared.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Recognize the age at which a genuinely reciprocal social smile is expected.',
  source: 'Pediatrics endpoint part2.pdf p.40' },

{ id: 'pedep2-nd-12',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Ivan can tie his shoelaces all by himself. At what age would one expect that child to achieve the milestones described in this scenario (median age)?',
  options: ['1 year', '2 years', '3 years', '4 years', '5 years'],
  answer: 4,
  explanation: "**The endpoint file prints this explanation:**\n\n> Tying shoelaces requires advanced fine motor coordination and typically develops around 5 years old.\n\n---\n\nThis is the same 1-to-5-year fine motor ladder used in `pedep2-nd-8`, where the progression through the earlier rungs (and a divergence between the printed box and the course table over copying a square) is set out in full. Tying shoelaces unaided needs bilateral hand coordination and a multi-step sequence well beyond copying a shape, so it sits at the oldest, 5-year rung of the ladder — not itemized as a specific age in the cached milestone table itself, so this exact skill is general pediatric knowledge, not taken from the course material, though it is consistent with the table's overall picture of increasingly complex fine-motor sequencing by school age.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Place an advanced fine-motor self-care skill at the top rung of a shared age ladder.',
  source: 'Pediatrics endpoint part2.pdf p.42' },

{ id: 'pedep2-nd-13',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'Lizzie has just started crawling. At what age would one expect that child to achieve the milestones described in this scenario (median age)?',
  options: ['6 months', '8 months', '10 months', '12 months', '24 months'],
  answer: 1,
  explanation: "This is the same 6-to-24-month language-ladder question style as `pedep2-nd-9`, but Lizzie's clue is motor rather than language: she has just started crawling. The course's slide-deck milestones place crawling explicitly at 8 months (\"8 months: Crawl\"), and the same deck's gross-motor summary lists crawling across 8–9 months; the milestone table instead groups it into a broader 9–10 month band alongside pulling to stand. The printed key here, B (8 months), matches the earlier, more specific slide figure rather than the table's grouped range — a minor variation between two parts of the same course material rather than a contradiction, and nothing here moves the key. For comparison, `pedep2-nd-9`'s clue on this same ladder, saying a word specific to one person (\"dada\" to her father), is timed two rungs later at 10 months.\n\nWritten for this bank — Pediatrics endpoint part2.pdf prints no explanation here.",
  objective: 'Distinguish a gross-motor milestone (crawling) from language milestones on a shared age ladder.',
  source: 'Pediatrics endpoint part2.pdf p.44' },

{ id: 'pedep2-nd-14',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: 'At which of these ages is the following action (first measles/mumps/rubella (MMR) immunization) usually first taken in the child health surveillance and promotion program in the United Kingdom?',
  options: ['3 months', '4 months', '8 months', '12 months', '18 months'],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> In the UK, the first dose of MMR vaccine is given at 12 months as part of routine immunization.\n\n---\n\nThe exact UK child health surveillance and immunisation schedule is not covered in the cached lecture material for this chapter, so the timing discussion here is general knowledge rather than course-sourced — not taken from the course material. In the UK's routine schedule, the primary course of injected vaccines (6-in-1, PCV, rotavirus, MenB) runs through early infancy from about 8 weeks, well before any of the options offered here; the first MMR dose is then given once maternally-transferred measles antibody has waned, at 12 months, alongside the Hib/MenC and PCV boosters, with a second MMR dose later in the preschool years. The younger options (3, 4, and 8 months) all fall inside that earlier, non-MMR run of injections, and 18 months is past the point at which the first dose is actually due, which is why D (12 months) is the printed key.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Recognize the UK schedule age for the first MMR dose.',
  source: 'Pediatrics endpoint part2.pdf p.46' }
