/* Section 12 "Model Final Exam 3" half B -- rows n25, n27..n38, n40, n41, n42 (16 entries).
   Drafted from content/peds/qb-pages/endpoint-s12-mfe3.array.js (PEDEP_S12_STAGED).
   Comma-joined fragments; the splicer strips this header. Id prefix pedep-mf3-.
   n24 and n39 are reprints and are not drafted here.
   n26 WAS DRAFTED HERE AND HAS BEEN REMOVED, because the escalation it raised was answered: it is
   the same question the endpoint file already prints at p.356 and p.387, live as `pedep-nut-59`,
   whose own `source` records the p.387 respelling word for word ("How does human milk
   oligosaccharides work?", "Function as prebiotics") plus a further reprint in Model Final Exam 2
   at p.1352. p.1535 is a fifth printing, so the live source was extended by the reprint pass and
   the eighteenth reprint is not drafted. Neither reprint probe could see it: both match on `stem`,
   and this one reprints a wording that lives in prose inside `source`.
   RECORDED, NOT FOLDED: n41 (p.1565) reprints the n6 vignette (p.1495) with a DIFFERENT ladder --
   five options including Listeria monocytogenes against four -- so it is a pairing, not a fold. */

{
  id: 'pedep-mf3-25',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'emergencies',
  stem: 'Which of the following is true about "capillary refill time"?',
  options: ["Apply blanching pressure for 2 seconds", "Prolonged capillary refill if > 3 seconds", "It is affected by body exposure to a cold environment", "It is reproducible only in children over the age of 2 years"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> CRT is prolonged (>3 sec) in poor perfusion and can be affected by cold environments. It is measured by blanching pressure for 5 seconds.\n\n---\n\nCapillary refill measures peripheral perfusion, and peripheral perfusion is precisely what ambient cold changes: cutaneous vasoconstriction in a cold room slows refill in a child whose central circulation is intact. `4) Shock in pediatrics_.txt` makes the same point structurally, listing delayed capillary refill alongside a core-peripheral temperature gap of more than 4°C among the early (compensated) features of shock -- the peripheral bed is temperature-sensitive, so a cold environment confounds the sign and the child must be exposed and assessed warm before the number means anything.\n\n**Why the other three fail.**\n\n**Blanching pressure for 2 seconds.** The endpoint file's own box on this page says the manoeuvre uses blanching pressure for **5 seconds**, so the book contradicts this option itself; 5 seconds of pressure, then timing the refill, is the conventional technique. The 2-second figure belongs to the refill time, not to the duration of the pressure -- confusing the two is what the distractor is built on.\n\n**Prolonged if > 3 seconds.** A threshold statement, and the material's own cut-off is lower: `4) Shock in pediatrics_.txt` prints delayed capillary refill as greater than **2 seconds**, not 3. The book keys the cold-environment option rather than this one, so the discrepancy does not change the answer, but the two numbers do disagree and the printed key stands as the book set it.\n\n**Reproducible only over the age of 2 years.** False, and the reverse of how the sign is used: capillary refill is assessed from the newborn period onwards and is at its most useful in infants, in whom blood pressure falls only late. Nothing in the material restricts it by age.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Recognise capillary refill time as a temperature-sensitive measure of peripheral perfusion, applicable at any paediatric age, and place the printed 3-second threshold against the 2-second cut-off the shock lecture teaches.",
  source: 'Pediatrics endpoint part1.pdf p.1533'
},

{
  id: 'pedep-mf3-27',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'infection-vaccine',
  stem: "A 5-year-old girl is receiving induction chemotherapy for acute lymphoblastic leukemia. Which of the following vaccines is contraindicated to be given to her 4-month-old sibling?",
  options: ["Oral Polio Vaccine", "Hemophilus influenzae Vaccine", "Hepatitis B Vaccine", "Pneumococcal Vaccine", "Diphtheria, Pertussis, Tetanus (DPT) Vaccine"],
  answer: 0,
  explanation: "**The endpoint file prints this explanation:**\n\n> Live oral polio vaccine is contraindicated in siblings of immunocompromised children due to risk of transmission.\n\n---\n\nThe question is answered entirely by sorting the five options into live and non-live, and `25)Immunodeficiency_.txt` prints that sort explicitly: \"Live attenuated vaccines, e.g. MMR, varicella, OPV, rotavirus, BCG - modified organisms\"; \"Inactivated vaccines, e.g. inactivated polio (IPV), whole organisms obtained by chemical or heat treatment (pertussis)\"; \"Subunit vaccines, e.g. diphtheria, tetanus toxoid, pneumococcus, Hib vaccine, Hepatitis B (HBV) - contain antigens of the organism\". **OPV is the only live organism on this ladder.**\n\nNote that the risk being avoided is not to the infant who receives the vaccine -- he is immunocompetent -- but to his sister on induction chemotherapy, which is the deepest phase of immunosuppression in leukaemia treatment. Vaccine poliovirus replicates in the gut and is shed in stool for weeks after an oral dose, so a household contact can acquire it, and in a profoundly immunosuppressed child that vaccine-derived virus can cause paralytic disease *(the household-contact rule is not taken from the course material: the immunodeficiency deck classifies the vaccines and lists which are available in Egypt, but prints no contact rule -- grepping the cached lectures for \"contraindicat\", \"immunocompromis\", \"immunosuppress\" and \"live vaccine\" returns the classification slide and unrelated hits in the diarrhoea, DKA and haematology decks, and nothing on vaccinating the household of an immunosuppressed child)*.\n\n**Why the other four are safe here.** By the lecture's own classification, **Hib**, **hepatitis B** and **pneumococcal** vaccines are subunit preparations containing antigen only, and **DPT** is a toxoid and killed-organism preparation. None contains a replicating organism, so none can be shed, transmitted or cause disease in the immunosuppressed sibling -- and all four remain indicated for the 4-month-old on his normal schedule.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Sort a routine infant schedule into live and non-live preparations, and recognise that only the live oral polio vaccine is withheld from the household contact of a child on induction chemotherapy, because vaccine virus is shed in stool and can be transmitted.",
  source: 'Pediatrics endpoint part1.pdf p.1537'
},

{
  id: 'pedep-mf3-28',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'perinatal-rd',
  stem: "A term infant born by elective C-section had developed acute respiratory distress few hours later. What is the most likely diagnosis?",
  options: ["Respiratory distress syndrome", "Transient tachypnea of the newborn", "Pneumothorax", "Meconium aspiration syndrome"],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> Transient tachypnea of the newborn occurs due to delayed clearance of fetal lung fluid, especially after elective C-section.\n\n---\n\nThree details settle this: **term**, **elective caesarean**, and onset **a few hours** after delivery. `9) Respiratory distress in newborn.txt` gives all three to transient tachypnoea of the newborn, which it also calls RDS type 2 or wet lung -- \"the most common cause of neonatal RD constituting more than 40% of cases\", \"occurs in term and late preterm neonates\", a \"mild and transient form of RD resulting from delayed clearance of fetal lung fluid by lymphatics\", with onset \"within 2 hours after delivery with mild to moderate RD\" and symptoms lasting \"few hours to 3 days\". Elective caesarean heads its printed risk-factor list, ahead of male gender and maternal diabetes.\n\nThe mechanism the same deck prints explains why the elective route matters: \"During labor and delivery, the concentration of adrenaline increases and, as a consequence, lung liquid secretion ceases and resorption begins.\" A caesarean performed before labour removes that adrenaline surge, so the roughly 20 ml/kg of fetal lung liquid present near term is still being secreted rather than reabsorbed when the baby takes its first breaths.\n\n**Why the other three fail.** **Respiratory distress syndrome** is surfactant deficiency, and the deck states its incidence is \"inversely proportional to gestational age\" -- 60-80% below 28 weeks against 15-30% at 32-36 weeks -- so a term infant is the wrong patient for it. **Pneumothorax** is an air leak, which the deck ties to the ventilated or meconium-aspirating infant and which presents as sudden deterioration with mediastinal shift rather than gradual tachypnoea (that presentation is `pedep-mf3-33`). **Meconium aspiration syndrome** requires aspiration of meconium in utero or at delivery, so it needs meconium-stained liquor and typically a post-term or distressed baby -- neither is offered here, and an elective section before labour is the least likely setting for it.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Attribute early respiratory distress in a term infant delivered by elective caesarean to transient tachypnoea of the newborn, explained by the absent labour adrenaline surge and delayed clearance of fetal lung fluid, against RDS, pneumothorax and meconium aspiration.",
  source: 'Pediatrics endpoint part1.pdf p.1539'
},

{
  id: 'pedep-mf3-29',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: "A healthy infant can sit without support, roll over and crawl but cannot stand alone. What is her most likely developmental age?",
  options: ["4 months", "6 months", "9 months", "13 months", "16 months"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> Sitting, rolling, and crawling without standing corresponds to around 9 months of age.\n\n---\n\nThe vignette sets a floor and a ceiling, and only one option sits between them. `1) Normal development.txt` prints the gross motor sequence as: complete rolling at 4-5 months, C-shaped sitting at 6 months, L-shaped sitting (sitting without support) at 7 months, crawling at 8-9 months, standing with support at 10 months, standing unsupported at 12 months and walking unsupported before 18 months. **Crawling sets the floor at 8-9 months**; **inability to stand alone sets the ceiling below 12 months**. Nine months is the only age that satisfies both, and the deck's own 9-month slide lists exactly this child -- \"Creeps or crawls or pulls to stand\".\n\n**Why the other four fail.** At **4 months** the infant is only just completing rolling and cannot yet sit at all, let alone crawl. At **6 months** sitting is still the unsteady C-shaped posture rather than unsupported sitting, and crawling has not started. At **13 months** she is past the deck's 12-month milestone of standing unsupported, so a child still unable to stand alone at that age is behind the sequence rather than matching it. At **16 months** she should be walking, and standing alone would be long established -- the deck sets walking unsupported before 18 months, so this option is further from the picture still.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Place an infant in the gross motor sequence by using an achieved milestone as a floor and an unachieved one as a ceiling: crawling puts her at 8-9 months and inability to stand alone keeps her under 12, leaving 9 months.",
  source: 'Pediatrics endpoint part1.pdf p.1541'
},

{
  id: 'pedep-mf3-30',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'growth-puberty',
  stem: "What is the main drive for growth during the childhood phase?",
  options: ["Nutrition", "Genetics", "Growth hormone", "Thyroid hormones", "Testosterone and estrogen"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> Growth hormone is the primary driver of linear growth during childhood, rather than sex hormones or nutrition alone.\n\n---\n\n**Linear growth is driven by different agents in each of the three phases of childhood, and the middle phase -- roughly the second year to the onset of puberty -- is the growth-hormone-dependent one, acting through IGF-1 on the growth plate** *(the phase-by-phase attribution is not taken from the course material; `13) Short stature.txt` prints the determinants of growth as an undifferentiated list -- genetics, systemic health, nutrition, sleep and exercise, and the hormones GH/IGF-1, thyroid hormone, insulin, sex steroids and glucocorticoids -- without ranking any of them by phase, and no cached deck names the infancy-childhood-puberty model)*. The clinical consequence is the one the same lecture is built around: growth hormone deficiency declares itself as a falling height velocity in the childhood years, and growth hormone treatment, which that lecture goes on to cover, is the response.\n\n**Why the other four fail.** **Nutrition** is the dominant drive of the *first* phase, infancy, when growth is fastest and least hormone-dependent -- it remains permissive later, and severe undernutrition will still stunt a child, but it is not what sets the pace once infancy is over. **Genetics** sets the target rather than the drive: it determines the height a child is growing towards, which is why the same lecture takes a family history of growth and puberty, but it does not distinguish one phase from another. **Thyroid hormones** are permissive and essential -- untreated hypothyroidism arrests linear growth, which is why the lecture examines for thyroid signs and lists hypothyroidism among the causes of short stature -- but they act alongside growth hormone rather than as the principal drive. **Testosterone and estrogen** drive the *third* phase, the pubertal growth spurt, and also close the epiphyses; the lecture ties height velocity to puberty for exactly that reason.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Separate the drivers of the three growth phases -- nutrition in infancy, growth hormone through childhood, sex steroids at puberty -- and distinguish a principal drive from the permissive (thyroid) and target-setting (genetic) determinants.",
  source: 'Pediatrics endpoint part1.pdf p.1543'
},

{
  id: 'pedep-mf3-31',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'emergencies',
  stem: "What is the optimal emergency management of a child presenting to the ER with severe croup?",
  options: ["Suction of the pharynx", "IV epinephrine", "Oral ampicillin", "Nebulized Epinephrine", "Immediate intubation"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Nebulized epinephrine reduces airway swelling rapidly and is first-line emergency treatment for severe croup.\n\n---\n\n**Severe croup is treated with nebulised epinephrine, which is delivered straight onto the oedematous subglottic mucosa, where its alpha-adrenergic vasoconstriction shrinks the swelling and widens the narrowest part of the airway within minutes; it is given alongside a corticosteroid (dexamethasone or nebulised budesonide), and because its effect wanes after a few hours the child must be kept under observation for rebound** *(not taken from the course material: croup is absent from the cached pediatrics lectures. Grepping every file in the lecture cache for \"croup\" and \"laryngotracheobronchitis\" returns a single unrelated hit -- the rickets deck describing the crouping or whooping sound of laryngeal spasm in tetany -- and \"nebulized epinephrine\", \"nebulised adrenaline\" and \"racemic\" return nothing at all. The one deck whose title suggests airway obstruction, `34)Students Obstructive diseases.txt`, turns out to be a cardiology deck on obstructive heart lesions, opening on aortic stenosis)*.\n\n**Why the other four fail.**\n\n**Suction of the pharynx** treats secretions, and the obstruction in croup is fixed mucosal oedema below the cords; worse, instrumenting the pharynx distresses the child, and distress increases turbulent flow and worsens the obstruction.\n\n**IV epinephrine** is the same drug by the wrong route. Given systemically it produces tachycardia, hypertension and arrhythmia while delivering almost nothing to the airway mucosa; the whole point of the nebulised route is topical vasoconstriction at the site of the swelling. Route is the only difference between this option and the key, and it is the discriminating token.\n\n**Oral ampicillin** treats nothing here -- croup is viral, so an antibiotic has no target, and an oral drug does not act quickly enough for an emergency in any case.\n\n**Immediate intubation** is the rescue, not the first move. It is reserved for a child who fails medical therapy or is progressing to complete obstruction; in most severe croup, nebulised epinephrine plus steroid avoids it, and passing a tube through an already narrowed, inflamed subglottis carries its own risk.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Choose nebulised epinephrine for severe croup, understanding that the topical route is what reduces subglottic oedema, and that suction, systemic epinephrine, antibiotics and immediate intubation each fail on route, target or timing.",
  source: 'Pediatrics endpoint part1.pdf p.1545'
},

{
  id: 'pedep-mf3-32',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'infection-vaccine',
  stem: "Increased risk for intussusception was observed as a rare complication following immunization with which vaccine?",
  options: ["Inactivated polio vaccine", "Oral polio vaccine", "Rotavirus vaccine", "Hepatitis A vaccine", "Hepatitis B vaccine"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> Rotavirus vaccine has a very rare risk of causing intussusception in infants.\n\n---\n\n**The oral rotavirus vaccine carries a small excess risk of intussusception, concentrated in the week after the first dose: the live vaccine virus replicates in the gut and the lymphoid hyperplasia it provokes in the Peyer's patches of the terminal ileum can act as a lead point for the bowel to telescope into itself** *(not taken from the course material: `25)Immunodeficiency_.txt` names the rotavirus vaccine twice -- once classifying it as live attenuated alongside MMR, varicella, OPV and BCG, and once listing it among the vaccines available in Egypt -- but prints no adverse effect for it. Grepping the whole lecture cache for \"intussuscept\" returns it only as a surgical cause of bile-stained vomiting in the vomiting deck, as a differential and complication in the acute diarrhoea and abdominal pain decks, as an option in a hematuria MCQ, and as a complication of Henoch-Schonlein purpura in the haemorrhagic disorders deck -- never once linked to a vaccine)*.\n\nThe association is the reason the first-generation rhesus-reassortant vaccine was withdrawn in 1999; the current vaccines were licensed only after very large trials, and the residual excess is of the order of a few cases per hundred thousand infants vaccinated -- small enough that the vaccine remains recommended, because rotavirus gastroenteritis itself causes far more harm.\n\n**Why the other four fail.** **Inactivated polio vaccine** is injected and killed, so nothing replicates in the gut at all. **Oral polio vaccine** does replicate in the gut and is the other live enteric vaccine on this ladder, which is what makes it the strongest distractor -- but its recognised rare complication is vaccine-associated paralytic poliomyelitis, not intussusception. **Hepatitis A vaccine** is an injected inactivated preparation and **hepatitis B vaccine** is a subunit preparation containing antigen only, as `25)Immunodeficiency_.txt` classifies it; neither replicates anywhere, let alone in the ileum.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Attribute the rare post-immunisation intussusception risk to the live oral rotavirus vaccine through ileal lymphoid hyperplasia acting as a lead point, and separate it from oral polio vaccine, whose rare complication is vaccine-associated paralysis.",
  source: 'Pediatrics endpoint part1.pdf p.1547'
},

{
  id: 'pedep-mf3-33',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'perinatal-rd',
  stem: "A preterm infant, intubated at birth, develops worsening of existing respiratory distress and shifting of mediastinum to one side. What is the most likely diagnosis?",
  options: ["Congenital heart disease", "Apnea of prematurity", "Herpes simplex infection", "Pneumothorax"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Mediastinal shift in a ventilated preterm infant indicates pneumothorax.\n\n---\n\nTwo elements of the stem point at one diagnosis. The first is the setting: `9) Respiratory distress in newborn.txt` lists, among the complications of respiratory distress syndrome, that \"Air leak syndromes (pneumothorax...) are usually the complications of mechanical ventilation\" -- a preterm infant intubated at birth is exactly the patient it describes, because positive pressure delivered to stiff, surfactant-deficient lungs over-distends the most compliant alveoli until one ruptures. The second is the sign: air trapped under pressure in one pleural space pushes the mediastinum away from it, so a **shift to one side** is a mechanical, unilateral event, and sudden worsening of distress in an already ventilated baby is how a tension pneumothorax announces itself.\n\n**Why the other three fail.** **Congenital heart disease** produces cyanosis, a murmur or heart failure; it does not displace the mediastinum acutely, and nothing about intubation at birth precipitates it. **Apnoea of prematurity** is cessation of breathing, not worsening work of breathing -- and an infant already intubated and ventilated is being breathed for, so apnoea is not the mechanism that would deteriorate here. **Herpes simplex infection** in the newborn presents as a sepsis-like illness, as vesicles of the skin, eye and mouth, or as encephalitis, evolving over days rather than as an abrupt mechanical shift of the mediastinum *(the neonatal HSV presentation is not taken from the course material: the cached decks mention aciclovir only as empirical cover in the febrile child and life-threatening infections deck and do not describe neonatal herpes)*.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Read acute deterioration with mediastinal shift in a ventilated preterm infant as a pneumothorax, understanding air leak as a recognised complication of mechanical ventilation rather than a cardiac, apnoeic or infective event.",
  source: 'Pediatrics endpoint part1.pdf p.1549'
},

{
  id: 'pedep-mf3-34',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'normal-dev',
  stem: "If the age of 18 months is the \"red-flag age\" of walking unsupported, what is the percentage of normal children who achieve that skill by age of 18 months?",
  options: ["27%", "57%", "77%", "97.5%"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> About 97.5% of normal children can walk unsupported by 18 months; delayed walking beyond this is a red flag.\n\n---\n\nThe question is really about what a limit age *is*. `Lec 1 Normal development_.txt` sets it against the median: the **median age** is \"the age at which 50% of children have achieved a particular milestone\", while the **limit age (upper limit of normal)** is the age by which nearly all have, and \"failure to achieve the milestone beyond this age is considered delayed\". It gives this very example -- \"Walking median age 12 months, but walking limit age is 18 months both are normal. If the child could not walk at age of 19 month, he will need assessment\" -- and `Lec 2 Child development_.txt` uses the same term, calling it the \"Red flag age (limit ages)\", the age by which a milestone should have been achieved. A limit age is therefore set high in the distribution by construction: 97.5% is the two-standard-deviation convention, leaving the slowest 2.5% of normal children as the group flagged for assessment.\n\n**A divergence worth recording, with the printed key left alone.** `Lec 1 Normal development_.txt` defines the limit age as \"the age by which ~90-95% of children have achieved the milestone\", not 97.5%. The book keys 97.5% and that is the answer as printed; the lecture's own figure is lower, and a student who learned the range from the deck should know both numbers describe the same idea -- a high cut-off near the top of the normal distribution -- while the exact percentage differs between the two sources.\n\n**Why the other three fail.** **27%**, **57%** and **77%** all sit too low in the distribution to serve as a limit age: at 77% nearly a quarter of entirely normal children would be labelled delayed, and at 27% the majority would. None of the three corresponds to any threshold the material uses -- and note that the one value with a defined meaning, the median at 50%, is absent from the ladder, because the median for walking is 12 months, not 18.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Define a limit or red-flag age as the high percentile by which a milestone should be achieved -- keyed here at 97.5% for walking by 18 months -- and distinguish it from the median age of 12 months.",
  source: 'Pediatrics endpoint part1.pdf p.1551'
},

{
  id: 'pedep-mf3-35',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'emergencies',
  stem: "Which of the following is a diagnostic sign of uncompensated shock?",
  options: ["Capillary refilling time equals 2 seconds", "Heart rate greater than 120 beats/min", "Cold extremities", "Respiratory rate greater than 40 breaths/min", "Low blood pressure"],
  answer: 4,
  explanation: "**The endpoint file prints this explanation:**\n\n> Low blood pressure is a late and definitive sign of uncompensated (decompensated) shock, showing that the body’s compensatory mechanisms have failed and organs are under-perfused. Other signs like rapid heart rate, fast breathing, or cold extremities indicate early or compensated shock, but only hypotension confirms the uncompensated stage.\n\n---\n\n`4) Shock in pediatrics_.txt` splits the clinical features into two explicit columns and repeats the discriminator twice, on its summary slide and again on its closing slide: \"Early sign of shock is tachycardia, late sign of shock is low blood pressure. It is important to recognize early compensated shock, as it is reversible, in contrast to decompensated shock, which may be irreversible.\" Hypotension appears only in the late (decompensated) column, alongside acidotic Kussmaul breathing, bradycardia, a depressed cerebral state, blue peripheries and absent urine output. The physiology behind the split is why blood pressure alone is diagnostic: a child maintains cardiac output by raising heart rate and systemic vascular resistance, so blood pressure is the last variable to fall, and it falls only once that compensation is exhausted.\n\n**Why every distractor is an early sign, or no sign at all.** **Heart rate above 120/min** is tachycardia, which the deck names as *the* early sign. **Respiratory rate above 40/min** is tachypnoea, also in the early column. **Cold extremities** correspond to the deck's mottled, pale, cold skin and to its core-peripheral temperature gap, again early -- these are the visible face of the vasoconstriction that is holding the blood pressure up, so their presence argues that compensation is still working. **Capillary refill of 2 seconds** is the weakest of the four: the deck's threshold for delayed refill is greater than 2 seconds, so a value of exactly 2 is not even abnormal, let alone diagnostic of the late stage (`pedep-mf3-25` covers what does and does not affect that measurement).\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Separate compensated from uncompensated shock by recognising hypotension as the single late, diagnostic sign, while tachycardia, tachypnoea, cold peripheries and a borderline capillary refill all belong to the reversible compensated stage.",
  source: 'Pediatrics endpoint part1.pdf p.1553'
},

{
  id: 'pedep-mf3-36',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'cardiac-acq',
  stem: "A Multi-system inflammatory response is a rare complication in children following which infection?",
  options: ["Influenza", "Cytomegalovirus infection", "Epstein-Barr infection", "COVID-19", "Meningitis"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> COVID-19 can trigger a rare pediatric multi-system inflammatory syndrome post-infection.\n\n---\n\n`36)Myocardial diseases.txt` teaches this entity by name and defines it in one line: MIS-C is \"Immune mediated multiorgan dysfunction after COVID infection\". The same deck gives its diagnostic formula -- \"Fever + acute phase reactants + multi-organ affection + evidence of COVID infection + exclusion of other DD\" -- which makes the answer structural rather than a matter of recall: **evidence of COVID infection is itself one of the criteria**, and exclusion of other differentials is another, so no other organism can satisfy the definition.\n\nThe reason the cardiology deck is where this is taught is the organ it hits: MIS-C \"has high tendency for cardiac affection\", the deck listing impaired left ventricular systolic function, mitral regurgitation, pericardial effusion and coronary involvement, treated with steroids, other immunomodulators and IVIG to interrupt the inflammatory cascade. Note also that the syndrome is post-infectious -- it follows the infection by weeks rather than accompanying it -- which is why a child can present well after the acute illness has passed.\n\n**Why the other four fail.** **Influenza** can cause myocarditis and pneumonia during the acute illness, but not this delayed immune-mediated multiorgan syndrome. **Cytomegalovirus** matters in paediatrics mainly as a congenital infection and, in the immunocompromised, as end-organ disease; it is not a MIS-C trigger. **Epstein-Barr infection** is the closest mimic on the ladder, because infectious mononucleosis is genuinely a febrile multisystem illness with lymphadenopathy and hepatosplenomegaly -- but it is direct infection, not a post-infectious hyperinflammatory state, and it is one of the differentials the deck's own criteria require to be excluded. **Meningitis** is not an infection by a named organism at all but a syndrome, and a direct infection of the meninges rather than an immune sequel.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Identify COVID-19 as the antecedent infection of MIS-C, using the taught diagnostic formula in which evidence of COVID infection and exclusion of other differentials are themselves criteria, and recall the cardiac involvement that makes it a cardiology problem.",
  source: 'Pediatrics endpoint part1.pdf p.1555'
},

{
  id: 'pedep-mf3-37',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'resp-bronch',
  stem: "A 3-month-old baby is admitted with a diagnosis of bronchiolitis. Her condition has further worsened, and she developed audible grunting sounds. What is the best pathophysiologic explanation for grunting in this baby?",
  options: ["Oxygen consumption is decreased with grunting which helps resolve hypoxemia", "During grunting lung volume increases as more air moves through the conducting airways", "Grunting increases end expiratory pressure and promotes gas exchange", "During grunting the diameter of the bronchi and bronchioles is increased"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> Grunting increases end-expiratory pressure, helping keep alveoli open and improving gas exchange.\n\n---\n\n**Grunting is expiration against a partially closed glottis. Holding the glottis shut through early expiration traps gas in the lungs at a pressure above atmospheric, which is self-generated positive end-expiratory pressure: it raises the functional residual capacity, splints open alveoli and small airways that would otherwise collapse at end-expiration, and so improves ventilation-perfusion matching and oxygenation** *(the mechanism is not taken from the course material. The cached decks list expiratory grunting only as a sign -- `7) Intro to neonatology.txt` and `9) Respiratory distress in newborn.txt` put it in their lists of signs of respiratory distress, and `30) Pneumonia.txt` names it among the features of severe pneumonia -- but none explains how it works, and grepping the whole lecture cache for \"end-expiratory\", \"PEEP\" and \"functional residual\" returns nothing at all)*. In a 3-month-old with bronchiolitis, small-airway obstruction and air trapping are already present, so the appearance of grunting marks the point at which the infant has begun recruiting this last mechanical reserve -- which is exactly why it is read at the bedside as a sign of deterioration rather than of coping.\n\n**Why the other three fail.**\n\n**Oxygen consumption is decreased with grunting.** The opposite: grunting is extra respiratory work and raises oxygen consumption. It relieves hypoxaemia by recruiting alveoli, not by lowering demand -- and a tiring infant whose consumption keeps rising is the one who goes on to need support.\n\n**Lung volume increases as more air moves through the conducting airways.** This misplaces the phase. Grunting acts in *expiration* and works by retarding outflow; the volume it preserves is end-expiratory volume already in the lungs, not additional air drawn in through the airways.\n\n**The diameter of the bronchi and bronchioles is increased.** The calibre that changes during a grunt is the glottis, and it narrows. Bronchial dilatation is what a bronchodilator attempts, and it is not the mechanism of this sound.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Explain grunting as expiration against a partially closed glottis generating auto-PEEP, which maintains functional residual capacity and gas exchange, and reject explanations based on reduced oxygen consumption, increased inspiratory flow or bronchial dilatation.",
  source: 'Pediatrics endpoint part1.pdf p.1557'
},

{
  id: 'pedep-mf3-38',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'infection-vesic',
  stem: '"Acyclovir" is an effective treatment of which virus infection?',
  options: ["Human Herpes virus type 6", "Measles virus", "Rubella", "Herpes simplex virus infection", "Coxsackie virus"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Acyclovir is effective against herpes simplex virus, not measles, rubella, or other viral infections listed.\n\n---\n\n`infectious diseases causing vesicular rash.txt` prescribes acyclovir for herpes simplex directly. Teaching herpetic gingivostomatitis as \"the most common clinical manifestation of a primary Herpes Simplex Virus (HSV) virus\" in children between 6 months and 5 years, caused by HSV-1, it gives the treatment as \"Oral Acyclovir (15 mg/kg for children, 800 mg for adults)... effective if started within 72 hours of symptom onset to shorten the duration of fever and lesions\". The reason it works only on this family is its mechanism: acyclovir is a nucleoside analogue that must first be phosphorylated by a **viral** thymidine kinase, which herpesviruses encode and the other viruses on this ladder do not, so the drug is activated only inside herpesvirus-infected cells.\n\n**Why the other four fail, each with the material's own treatment line.** **Human herpesvirus type 6** is the trap, because it is a herpesvirus by name -- but the roseola section of `infectious diseases causing maculopapular rash.txt` states that \"Management is entirely supportive\" and, where an antiviral is used at all in severe disease in the immunocompromised, names **ganciclovir**, not acyclovir; HHV-6 is not acyclovir-sensitive in practice. **Measles**: the same deck is explicit that \"There is no specific antiviral therapy. Management is supportive\", with vitamin A supplementation recommended for all. **Rubella** is likewise managed supportively, with rest, fluids and acetaminophen for fever. **Coxsackievirus**, which the vesicular deck covers as hand-foot-and-mouth disease and herpangina, has \"no specific antiviral medication; management is supportive\" -- pain and fever relief and hydration only. It is worth noting that acyclovir is also active against varicella-zoster, which the same deck treats with acyclovir, valacyclovir or famciclovir started within 72 hours of rash onset -- but varicella-zoster is not on this ladder, so herpes simplex is the only correct answer here.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Match acyclovir to herpes simplex virus by way of its dependence on viral thymidine kinase, and recall that roseola, measles, rubella and coxsackievirus illness are all managed supportively in the material.",
  source: 'Pediatrics endpoint part1.pdf p.1559'
},

{
  id: 'pedep-mf3-40',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'infection-rash',
  stem: "A 6-year-old girl missed a few days of school as she had a fever and was generally lethargic. Now she has a temperature of 38.3°C and has a marked erythematous rash on her cheeks. Which organism is most likely to be the causative agent?",
  options: ["Chickenpox virus (varicella-zoster virus)", "Herpes simplex virus", "Measles virus", "Parvovirus infection (fifth disease)", "Roseola infantum (sixth disease)"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> “Slapped cheek” appearance is classic for erythema infectiosum (Parvovirus B19).\n\n---\n\nThe vignette follows the two-phase course `infectious diseases causing maculopapular rash.txt` prints for erythema infectiosum. First a prodrome, \"a mild, non-specific illness... about a week after exposure\" with \"low-grade fever, headache, malaise, and mild upper respiratory symptoms\" -- the few days off school. Then the rash phase, \"2-5 days after the prodrome\", opening with \"Stage 1 ('Slapped-Cheek'): Bright red, erythematous flushing on the cheeks with circumoral pallor\" -- the marked erythematous rash on her cheeks now. The deck names the agent as **Human Parvovirus B19**, a non-enveloped single-stranded DNA virus that replicates in erythroid progenitor cells in the marrow.\n\nTwo consequences of that tropism are worth carrying away. Because the rash phase is immune-mediated rather than viraemic, the deck notes that \"once the characteristic rash develops, the child is considered no longer infectious and may return to school\" -- so the cheeks that make the diagnosis also mark the end of the infectious period. And because the virus attacks red cell precursors, it causes **aplastic crisis** in a child with high red cell turnover such as sickle cell disease or thalassaemia, and **fetal hydrops** if a pregnant contact is infected.\n\n**Why the other four fail.** **Varicella-zoster** produces a vesicular rash in successive crops over the whole body, not facial erythema. **Herpes simplex** in this age group presents as gingivostomatitis with oral vesicles and ulcers, or as cold sores -- again vesicular and not a facial flush. **Measles** would give a far more ill child with high fever, cough, coryza, conjunctivitis and Koplik spots, and its maculopapular rash begins behind the ears and at the hairline before spreading downwards; it does not begin as isolated red cheeks. **Roseola infantum**, caused by HHV-6, is an illness of infants and toddlers, not six-year-olds, and its defining feature is that rash and fever \"rarely overlap\" -- the truncal rash appears as the high fever breaks, whereas this girl is still febrile at 38.3°C with the rash present.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Diagnose erythema infectiosum from a prodrome followed by slapped-cheek erythema, name parvovirus B19 as the agent, and recall that the rash marks the end of infectivity while the erythroid tropism causes aplastic crisis and fetal hydrops.",
  source: 'Pediatrics endpoint part1.pdf p.1563'
},

{
  id: 'pedep-mf3-41',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'neonatal-sepsis',
  stem: "A girl was born at term weighing 4 kg. At 6 hours of age, she was noted to be breathing fast and have a low temperature. She was born by normal vaginal delivery and the membranes had ruptured 24 hours previously. She has not breastfed since birth and has had one vomit. On examination, she is lethargic and her core temperature is 35.5°C. She has a respiratory rate of 90 breaths/min, her central capillary refill time is 4 seconds, pulse 180/min, and oxygen saturation is 89% in air. Her chest X-ray shows consolidation at the right base. What is the most likely causative organism for her infection?",
  options: ["Escherichia coli (E. coli)", "Group B streptococcus", "Listeria monocytogenes", "Staphylococcus aureus", "Streptococcus pneumoniae"],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> GBS is the most common cause of early-onset neonatal sepsis/pneumonia.\n\n---\n\nThe endpoint file prints this vignette twice, and `pedep-mf3-6` carries the full working -- why onset at 6 hours places the illness inside the early-onset window that `11) Neonatal sepsis.txt` defines as the first 72 hours of life, why rupture of membranes 24 hours before delivery is the prolonged-rupture risk factor that deck attaches to vertical transmission, and why the same deck's table assigns GBS and E. coli to early-onset disease and staphylococci to late-onset disease after 72 hours.\n\n**What is different in this printing is a fifth option, Listeria monocytogenes**, and it deserves its own answer. Listeria is a genuine neonatal pathogen: `18) febrile child and life threatening infections.txt` lists it third, after group B streptococcus and E. coli, among the organisms causing bacterial meningitis from the neonatal period to 3 months. But it is the rarest of the three, it is acquired from contaminated food in the mother rather than from vaginal colonisation, and the risk factor this vignette actually gives -- prolonged rupture of membranes -- is the one tied to ascending genital-tract organisms. The neonatal sepsis deck names only GBS and E. coli for early-onset disease, so within this material Listeria is not even in the frame; **Group B streptococcus remains the most likely organism**, and the added option does not move the key.\n\n**Of the other three**, **E. coli** is early-onset disease's other classic organism but not the leading one here, **Staphylococcus aureus** sits in the late-onset column of the deck's own table, and **Streptococcus pneumoniae** is a respiratory pathogen of later childhood that the material does not assign to neonatal sepsis at all.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Confirm Group B streptococcus as the leading cause of early-onset neonatal sepsis on this vignette even when Listeria monocytogenes is added to the ladder, by distinguishing a food-borne maternal pathogen from the ascending genital-tract organism that prolonged rupture of membranes implicates.",
  source: 'Pediatrics endpoint part1.pdf p.1565'
},

{
  id: 'pedep-mf3-42',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: "A 5-year-old boy, at a birthday party, presented with sudden onset of edema that started in his lips and eyelids, then spread to the dorsum of the hands and the genitalia. What is the first possibility?",
  options: ["Nutritional anemia", "Nephrotic syndrome", "Hepatic insufficiency", "Angioedema", "Heart failure"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Rapid onset swelling without renal, hepatic, or cardiac features → allergic angioedema.\n\n---\n\nTwo features decide this: the **speed** and the **distribution**. `26)allergy_.txt` describes IgE-mediated food allergy as \"a history of allergic symptoms varying from urticaria to facial swelling to anaphylaxis, usually 10-15 minutes (up to 2 hours) after ingestion of a food\", and lists among its cutaneous features \"urticaria, angioedema, pruritus, flushing\" and, under the gastrointestinal heading, \"Swelling of lips/tongue/uvula\". `27)Anaphylaxsis.txt` lists the same skin picture -- flushing, urticaria, angioedema, itching. A birthday party is a food exposure, and lips and eyelids are where angioedema starts because the connective tissue there is loosest; the dorsum of the hands and the genitalia are the next such sites. The other four diagnoses all produce oedema by lowering oncotic pressure or raising venous pressure, and none of those mechanisms works in minutes.\n\n**Why the other four fail.** **Nephrotic syndrome** is the real trap, because periorbital swelling worst on waking is its classic presentation -- but it develops over days with heavy proteinuria behind it, does not begin in the lips, and does not appear abruptly at a party. **Hepatic insufficiency** causes hypoalbuminaemic oedema that is gradual and dependent, dominated by ascites, and accompanied by jaundice and other chronic liver stigmata. **Heart failure** gives dependent oedema with hepatomegaly, tachypnoea and poor feeding or exercise tolerance, again over days to weeks, and would not spare the legs to swell the lips. **Nutritional anaemia** causes pallor and fatigue, not oedema at all, unless it is severe enough to precipitate high-output failure -- a slow process, not this one.\n\n**The clinical point behind the answer:** angioedema of the lips is a warning that the same reaction can involve the airway. `26)allergy_.txt` lists hoarseness and stridor among the upper-airway features and tachycardia, hypotension and shock among the cardiovascular ones, so this child needs to be watched for progression to anaphylaxis rather than simply labelled and sent home.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Recognise sudden oedema of the lips and eyelids after a food exposure as allergic angioedema on the grounds of speed and distribution, exclude the oncotic and venous causes of oedema, and anticipate progression to airway involvement.",
  source: 'Pediatrics endpoint part1.pdf p.1567'
}
