/* ===========================================================================
   ENDPOINT - Pediatrics endpoint part1.pdf - SECTION 9: "Infection and Immunity"
   Verbatim staging record. PDF pages 929-1156; PDF page = printed page, offset zero.
   Merged from endpoint-s09-infection.part-A.js + endpoint-s09-infection.part-B.js + endpoint-s09-infection.part-C.js + endpoint-s09-infection.part-D.js by merge-parts-ep.js.
   
   Every question is printed TWICE: an unanswered page, then the ANSWERED page with the key
   highlighted in yellow and (usually) a bordered explanation box. Only answered pages are
   staged. `n` is the true sequential index, `pr` what the page prints, `p` the PDF page,
   `key` a ZERO-BASED INDEX into `opts` (never a letter), matching the app field `answer`,
   `expl` the printed box verbatim or "".
   =========================================================================== */
var PEDEP_S09_STAGED = [

/* ENDPOINT part1 — SECTION 9 "Infection and Immunity" — staging half A (n1..n24).
   p.938 resolved as branch (b): a highlighted PROSE/notes page (Encephalitis), not a question.
   pp.936-939 form a prose block (Viral Meningitis / Encephalitis / Specific Bacterial Infections
   study notes) with no lettered options anywhere. Section holds 95 answered question pages, and
   n1 starts the regular +2 run at p.967. */

{ n: 1, pr: 1, p: 967,
  key: 0,
  stem: 'An infant missed his four-month vaccination and is now six months old. What should be the advice to his mother?',
  opts: ['Give the delayed dose now and resume the schedule in order', 'Start the schedule from the beginning', 'Skip the four-month dose and resume the rest of the schedule', 'Give the four-month dose followed a week later by the next dose'],
  expl: 'Vaccination schedules should never be restarted. Missed doses are given as soon as possible, and the child continues with the rest of the schedule normally.' },

{ n: 2, pr: 2, p: 969,
  key: 1,
  stem: 'A four-year-old girl presented with high-grade fever and sore throat one day ago, followed by a pinpoint red rash, circumoral pallor, and a white-coated tongue. What is the most likely diagnosis?',
  opts: ['Measles', 'Scarlet fever', 'Rubella', 'Chickenpox', 'Mumps'],
  expl: 'Scarlet fever presents with fever, sore throat, circumoral pallor, strawberry tongue, and a fine, sandpaper-like rash.' },

{ n: 3, pr: 3, p: 971,
  key: 0,
  stem: 'A febrile child presents with a purpuric rash. What is the most likely diagnosis?',
  opts: ['Meningococcal septicemia', 'Viral exanthem', 'Immune thrombocytopenic purpura', 'Scarlet fever'],
  expl: 'A purpuric rash in a febrile child is a red flag for meningococcal septicemia, a medical emergency.',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

{ n: 4, pr: 4, p: 973,
  key: 0,
  stem: 'At what age is the first dose of MMR vaccine recommended?',
  opts: ['12 months', '6 months', 'At birth', '2 months'],
  expl: 'MMR is given at 12 months because maternal antibodies interfere with earlier doses. A booster follows in early childhood.',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

{ n: 5, pr: 5, p: 975,
  key: 1,
  stem: 'The 10-year-old sister of a 2-month-old baby develops pertussis. The mother reports being vaccinated in childhood. What is the correct action?',
  opts: ['The baby should be fully protected by maternal antibodies in the first 3 months', 'The baby should receive a macrolide prophylaxis', 'The mother has no risk of acquiring the disease because she was immunized', 'Vaccinating the infant with DPT will prevent infection', 'The 10-year-old sister should be immediately immunized with an additional dose of pertussis vaccine'],
  expl: 'Infants under 6 months are at high risk from pertussis and should receive macrolide prophylaxis after exposure.' },

{ n: 6, pr: 6, p: 977,
  key: 4,
  stem: 'A 7-year-old unimmunized child presents with fever and itchy vesicular rash, some crusted. What is a true statement about this illness?',
  opts: ['It has an incubation period of 5–7 days', 'The rash is confluent, centrifugal, and pustular', 'It is associated with Koplik spots', 'There is generalized lymphadenopathy', 'It can cause visceral dissemination in immunocompromised hosts'],
  expl: 'Chickenpox (varicella) can cause severe complications like pneumonitis and encephalitis in immunocompromised patients.' },

{ n: 7, pr: 7, p: 979,
  key: 0,
  stem: 'Which of the following statements about vaccines is correct?',
  opts: ["OPV shouldn't be given to immunocompromised individuals", 'MMR is contraindicated in all children under 1 year of age', 'Hepatitis B vaccine is contraindicated in newborns of HBsAg-positive mothers', 'BCG is never given after the neonatal period'],
  expl: 'Live attenuated OPV can cause vaccine-associated poliomyelitis in immunocompromised children, so it is contraindicated.',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

{ n: 8, pr: 8, p: 981,
  key: 4,
  stem: 'A 2-year-old girl with fever, decreased appetite, oral ulcers, and vesicles with erythema on hands and feet. Most likely organism?',
  opts: ['Candida albicans', 'Herpes simplex virus', 'Parvovirus B19', 'Varicella', 'Enterovirus'],
  expl: 'Classic presentation of hand-foot-and-mouth disease caused by Coxsackievirus (an enterovirus).' },

{ n: 9, pr: 9, p: 983,
  key: 0,
  stem: 'A 1-year-old with 3-day fever and headache. CSF shows: 1200 neutrophils/mm³, low glucose, high protein. Most likely diagnosis?',
  opts: ['Bacterial meningitis', 'Blood-stained tap', 'Normal lumbar puncture result', 'Tuberculous meningitis', 'Viral meningitis'],
  expl: 'Neutrophilic predominance, low glucose, and high protein are suggestive of bacterial meningitis.' },

{ n: 10, pr: 10, p: 985,
  key: 0,
  stem: 'What is the most common early presentation of neonatal sepsis?',
  opts: ['Pneumonia', 'Meningitis', 'Jaundice', 'Rash', 'Apnea'],
  expl: 'Early-onset sepsis often presents with respiratory distress/pneumonia due to pathogens like GBS and E. coli.' },

{ n: 11, pr: 11, p: 987,
  key: 0,
  stem: 'A 9-year-old girl had 4 days of fever, then a rash appeared starting from the forehead and spread downward. Fever subsided as rash reached feet. Most probable diagnosis?',
  opts: ['Measles', 'Rubella', 'Varicella', 'Scarlet fever', 'Roseola infantum'],
  expl: 'Measles has the described pattern: high fever followed by descending rash and fever resolution.' },

{ n: 12, pr: 12, p: 989,
  key: 3,
  stem: 'A 7-month-old has 3 days of fever, then a rash appears after defervescence. Most likely diagnosis?',
  opts: ['Measles', 'Rubella', 'Drug reaction', 'HHV-6 infection', 'Enteroviral infection'],
  expl: 'Early-onset sepsis often presents with respiratory distress/pneumonia due to pathogens like GBS and E. coli.',
  note: 'The printed explanation box does not match this question — it is the identical box text printed under Q10/p.985 (neonatal sepsis). Book defect; transcribed verbatim as printed, not corrected.' },

{ n: 13, pr: 13, p: 991,
  key: 0,
  stem: 'An 18-month-old child presents with 4 days of fever and coryza. The fever has now subsided, and a maculopapular rash has appeared. What is the most likely cause?',
  opts: ['HHV-6', 'Measles', 'Rubella', 'Parvovirus B19'],
  expl: 'The most likely cause is HHV-6, which causes roseola infantum (also known as exanthema subitum or sixth disease). This condition is characterized by high fever for several days, followed by a rash that appears suddenly as the fever breaks. The rash is typically maculopapular and appears on the trunk, face, and limbs',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

{ n: 14, pr: 14, p: 993,
  key: 1,
  stem: 'A 12-year-old girl received amoxicillin for sore throat, developed a maculopapular rash. Most likely cause?',
  opts: ['Cytomegalovirus', 'Epstein-Barr virus', 'Parvovirus B19', 'Roseola infantum', 'Group A streptococcus'],
  expl: 'Rash after amoxicillin in EBV infection (infectious mononucleosis) is characteristic.' },

{ n: 15, pr: 15, p: 995,
  key: 1,
  stem: 'An 8-year-old girl has low-grade fever, diffuse maculopapular rash, cervical and occipital lymphadenopathy. Rash fades after 3 days. Most likely diagnosis?',
  opts: ['Measles', 'German measles (Rubella)', 'Scarlet fever', 'Infectious mononucleosis', 'Chickenpox'],
  expl: 'Classic rubella presentation: mild illness, short-lasting rash, lymphadenopathy.' },

{ n: 16, pr: 16, p: 997,
  key: 0,
  stem: 'Which of the following does not cause acute wheezing?',
  opts: ['Pertussis', 'Asthma', 'RSV bronchiolitis', 'Foreign body aspiration', 'Viral URTI'],
  expl: 'Pertussis causes paroxysmal coughing with inspiratory whoop, but not wheezing. Asthma, bronchiolitis, viral URTI, and foreign body aspiration all cause wheezing.' },

{ n: 17, pr: 17, p: 999,
  key: 0,
  stem: 'A child diagnosed with Epstein-Barr virus (EBV) tonsillitis is treated with ampicillin. What is the expected outcome?',
  opts: ['Development of a maculopapular rash', 'Rapid resolution of symptoms', 'No adverse effects from ampicillin', 'Increased risk of bacterial superinfection'],
  expl: 'Ampicillin or amoxicillin in EBV causes a characteristic rash.',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

{ n: 18, pr: 18, p: 1001,
  key: 2,
  stem: 'A 5-year-old has 3 days of fever followed by a maculopapular rash and severe cough. Likely diagnosis?',
  opts: ['Roseola infantum', 'Rubella', 'Measles', 'Chickenpox', 'Glandular fever'],
  expl: 'Fever, cough, and descending rash are consistent with measles.' },

{ n: 19, pr: 19, p: 1003,
  key: 0,
  stem: 'An 8-year-old girl develops a ring-like rash after a camping trip in the New Forest. What is the next best step?',
  opts: ['Prescribe amoxicillin (if not allergic)', 'Prescribe an antihistamine', 'Prescribe doxycycline', 'Take acute and convalescent Borrelia serology and arrange outpatient follow-up', 'Take blood for Borrelia serology'],
  expl: 'Erythema migrans is diagnostic of Lyme disease. Empiric amoxicillin is indicated without waiting for serology.' },

{ n: 20, pr: 20, p: 1005,
  key: 3,
  stem: "A 7-year-old boy presents with fever, severe headache, and multiple episodes of vomiting. He is drowsy, febrile (38°C), with HR 135/min and BP 90/60 mmHg. On examination, extension of the knee is limited with hip flexion (positive Kernig's sign). What is the next most important step?",
  opts: ['Complete blood picture', 'Blood culture for aerobic and anaerobic organisms', 'Brain CT', 'CSF examination and culture', 'ESR and C-reactive protein'],
  expl: 'The child presents with signs of meningeal irritation and possible meningitis. Lumbar puncture for CSF analysis is the most urgent diagnostic step, unless there are signs of raised intracranial pressure or focal neurological deficits.' },

{ n: 21, pr: 21, p: 1007,
  key: 3,
  stem: 'A 3-year-old boy presents with 24 hours of irritability, vomiting, and fever. He has a purpuric rash on his upper limbs and abdomen. Vitals: Temp 38.5°C, HR 140/min, BP 90/60 mmHg. What is the most likely diagnosis?',
  opts: ['Henoch-Schönlein purpura', 'Immune thrombocytopenic purpura', 'Measles', 'Meningococcal sepsis', 'Leukemia'],
  expl: "This presentation is classic for meningococcal sepsis, especially with the purpuric rash, fever, and hypotension. It's a medical emergency requiring immediate antibiotic therapy." },

{ n: 22, pr: 22, p: 1009,
  key: 1,
  stem: 'Farida, a term newborn weighing 4 kg, presents at 6 hours old with fast breathing, low temperature, and poor feeding. She was born via normal vaginal delivery with prolonged rupture of membranes (24 hours). On exam: lethargic, RR 90/min, T 35.5°C, capillary refill 4 sec, SpO2 89%, CXR shows right lower lobe consolidation. What is the most likely causative organism?',
  opts: ['Escherichia coli', 'Group B Streptococcus', 'Listeria monocytogenes', 'Staphylococcus aureus', 'Streptococcus pneumoniae'],
  expl: 'Group B Streptococcus is the most common cause of early-onset neonatal sepsis and pneumonia, especially with prolonged rupture of membranes.' },

{ n: 23, pr: 23, p: 1011,
  key: 2,
  stem: 'Which of the following is a pathognomonic sign of measles?',
  opts: ['Vesicular rash at the hairline', 'Cervical lymphadenopathy', 'White spots on the buccal mucosa', 'Red strawberry tongue', 'Desquamation of the rash'],
  expl: 'Koplik spots white lesions on the buccal mucosa  are pathognomonic for measles and usually precede the characteristic rash.' },

{ n: 24, pr: 24, p: 1013,
  key: 0,
  stem: 'Which vaccine is contraindicated in a 10-year-old girl who has missed her earlier immunizations?',
  opts: ['Whole-cell pertussis vaccine', 'Tetanus toxoid', 'Hepatitis B vaccine', 'Inactivated polio vaccine'],
  expl: 'The whole-cell pertussis vaccine is not recommended after 7 years of age due to higher risk of adverse reactions; acellular forms are used instead.',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

/* ENDPOINT part1 — SECTION 9 "Infection and Immunity" — staging half B (n25..n48). */

{ n: 25, pr: 25, p: 1015,
  key: 0,
  stem: 'Which of the following is the most common causative organism of acute otitis media in children?',
  opts: ['Streptococcus pneumoniae', 'Staphylococcus aureus', 'Adenovirus', 'Herpes simplex virus', 'Influenza virus'],
  expl: 'Streptococcus pneumoniae is the most frequent bacterial cause of otitis media in young children, followed by Haemophilus influenzae and Moraxella catarrhalis.' },

{ n: 26, pr: 26, p: 1017,
  key: 4,
  stem: 'Which vaccine is contraindicated in a 4-year-old boy on immunosuppressive therapy for autoimmune hepatitis?',
  opts: ['Tetanus toxoid', 'Hepatitis B vaccine', 'Acellular pertussis vaccine', 'Inactivated polio vaccine', 'BCG'],
  expl: 'Live vaccines like BCG are contraindicated in immunosuppressed children due to the risk of disseminated infection.' },

{ n: 27, pr: 27, p: 1019,
  key: 3,
  stem: 'A 14-year-old boy presents with fever, sore throat, and fatigue. Examination reveals exudative pharyngitis. Which test is most helpful for confirming the diagnosis?',
  opts: ['Throat swab for Influenza A', 'HIV antibody test', 'Throat swab for Neisseria gonorrhoeae', 'Serology for Epstein-Barr virus (EBV)'],
  expl: 'These symptoms suggest infectious mononucleosis. EBV serology or a Monospot test confirms the diagnosis.',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

{ n: 28, pr: 28, p: 1021,
  key: 0,
  stem: 'Which of the following organisms is NOT a known cause of bacterial meningitis in children?',
  opts: ['Group A Streptococcus', 'Streptococcus pneumoniae', 'Haemophilus influenzae type b', 'Neisseria meningitidis', 'Listeria monocytogenes'],
  expl: 'Group A Streptococcus rarely causes meningitis in children, while the others are common causative pathogens.' },

{ n: 29, pr: 29, p: 1023,
  key: 2,
  stem: 'Which of the following is NOT a live attenuated vaccine?',
  opts: ['Varicella', 'Rubella', 'Inactivated influenza', 'MMR'],
  expl: 'Inactivated influenza vaccine is a killed-virus vaccine, unlike varicella, rubella, and MMR which are live attenuated.',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

{ n: 30, pr: 30, p: 1025,
  key: 3,
  stem: 'A 7-month-old child presents with 3 days of fever, mildly injected pharynx, and mild diarrhea. On the fourth day, the fever subsides and a maculopapular rash appears. What is the most likely diagnosis?',
  opts: ['Measles', 'Rubella', 'Drug reaction to antipyretics', 'HHV-6 infection', 'Enteroviral infection'],
  expl: 'This is classic for roseola infantum (exanthem subitum), caused by HHV-6, where rash appears as fever resolves.' },

{ n: 31, pr: 31, p: 1027,
  key: 0,
  stem: 'Which of the following is true regarding pneumococcal infection in children?',
  opts: ['It is commonly found in the nasopharynx of healthy children', 'It is a viral infection with seasonal outbreaks', 'It is primarily transmitted via the fecal-oral route', 'It does not cause invasive disease in immunocompromised hosts'],
  expl: 'Streptococcus pneumoniae is often carried asymptomatically in the nasopharynx, especially in young children, but can cause invasive disease when immunity is low.',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

{ n: 32, pr: 32, p: 1029,
  key: 2,
  stem: 'A toddler presents with a 3-day history of high fever. He develops a truncal rash that appears after the fever subsides. He also experienced a simple febrile convulsion. What is the most likely diagnosis?',
  opts: ['Adenovirus', 'Enterovirus', 'Human herpesvirus 6 (HHV-6)', 'Meningococcal septicemia', 'Parvovirus B19'],
  expl: 'This is consistent with roseola infantum (HHV-6), which can also cause febrile seizures in infants and toddlers.' },

{ n: 33, pr: 33, p: 1031,
  key: 4,
  stem: 'Parents are concerned that their daughter may have been exposed to hepatitis A after spending time with a grandparent recently diagnosed with the infection. What is the typical incubation period of hepatitis A?',
  opts: ['1–7 days', '7–14 days', '7–21 days', '14–21 days', '14–28 days'],
  expl: 'Hepatitis A has an incubation period ranging from 14 to 28 days. It is transmitted via the fecal-oral route and often presents with nonspecific symptoms before jaundice appears.' },

{ n: 34, pr: 34, p: 1033,
  key: 4,
  stem: 'Which of the following findings is not consistent with Hirschsprung\'s disease?',
  opts: ['No passage of meconium after 24 hours of birth', 'Abdominal distension', 'Bile-stained vomiting', 'Refractory constipation', 'Spontaneous resolution'],
  expl: 'Hirschsprung\'s disease is a congenital condition caused by absence of ganglion cells in the distal colon, leading to functional intestinal obstruction. Common features include failure to pass meconium within 24 hours, abdominal distension, bile-stained vomiting, and chronic constipation. However, spontaneous resolution does not occur, and surgical intervention is typically required.' },

{ n: 35, pr: 35, p: 1035,
  key: 4,
  stem: 'An 8-month-old child presents with episodes of vomiting and screaming for 12 hours. On examination, a sausage-shaped mass is palpable in the right upper quadrant. Which of the following would be most useful for diagnosis and treatment?',
  opts: ['Passage of a nasogastric tube', 'Stool examination for ova and parasites', 'Blood culture', 'Complete blood count', 'Rectal air insufflation or barium enema'],
  expl: 'These findings suggest intussusception. A contrast enema (air or barium) confirms the diagnosis and can be therapeutic by reducing the intussusception' },

{ n: 36, pr: 36, p: 1037,
  key: 2,
  stem: 'What is a pathognomonic sign of measles?',
  opts: ['A vesicular rash at the hairline', 'Cervical lymphadenopathy', 'White spots on the buccal mucosa', 'Red strawberry tongue', 'Desquamation of the rash'],
  expl: 'Koplik spots (tiny white lesions on the buccal mucosa)are pathognomonic for measles and typically appear before the skin rash.' },

{ n: 37, pr: 37, p: 1039,
  key: 0,
  stem: 'Which of the following is a known complication of the pertussis vaccine?',
  opts: ['Convulsions', 'Metabolic acidosis', 'Hemolytic anemia'],
  expl: 'One known complication of the whole-cell pertussis vaccine is febrile convulsions. Though rare, these are transient and not a contraindication to future vaccination.',
  note: 'Only 3 options printed (a-c) — book prints fewer than 5 here.' },

{ n: 38, pr: 38, p: 1041,
  key: 0,
  stem: 'Severe viral and fungal infections are most commonly associated with deficiency of which immune component?',
  opts: ['T cells', 'B cells', 'Complement', 'Leukocytes'],
  expl: 'T-cell deficiencies impair cell-mediated immunity, making individuals particularly vulnerable to severe viral and fungal infections such as CMV or candidiasis.',
  note: 'Only 4 options printed (a-d) — book prints fewer than 5 here.' },

{ n: 39, pr: 39, p: 1043,
  key: 2,
  stem: 'Which of the following is considered a form of passive immunity?',
  opts: ['Influenza vaccine', 'MMR vaccine', 'Monoclonal antibody (palivizumab)'],
  expl: 'Palivizumab provides passive immunity by delivering ready-made antibodies against RSV. Unlike vaccines, it does not induce active immune memory.',
  note: 'Only 3 options printed (a-c) — book prints fewer than 5 here.' },

{ n: 40, pr: 40, p: 1045,
  key: 1,
  stem: 'A 4-year-old girl presented with high-grade fever and sore throat one day ago. A pinpoint red papular rash has now developed all over her body, with circumoral pallor and a whitish-coated tongue. What is the most likely diagnosis?',
  opts: ['Measles', 'Scarlet fever', 'Rubella', 'Chickenpox', 'Mumps'],
  expl: 'Scarlet fever presents with fever, sore throat, "sandpaper" rash, circumoral pallor, and "white strawberry tongue." It is caused by toxin-producing Streptococcus pyogenes.',
  note: 'Near-duplicate of n2 (also Scarlet fever, similar stem) — printed as a separate question in the book; both staged verbatim.' },

{ n: 41, pr: 41, p: 1047,
  key: 4,
  stem: 'A 7-year-old unimmunized child presents with fever and an itchy vesicular rash, some of which are crusted. You diagnose chickenpox. Which of the following statements is TRUE about this illness?',
  opts: ['It has an incubation period of 5–7 days.', 'The rash is confluent, centrifugal, and pustular.', 'It is associated with Koplik spots.', 'There is generalized lymphadenopathy.', 'It can cause visceral dissemination in immunocompromised hosts.'],
  expl: 'In immunocompromised individuals, varicella (chickenpox) can lead to severe complications including pneumonia, hepatitis, and encephalitis due to visceral',
  note: 'Duplicate of n6 (identical stem/key, part A) — staged verbatim as printed. Explanation box text ends abruptly mid-sentence ("...due to visceral") as printed; no continuation appears on the page.' },

{ n: 42, pr: 42, p: 1049,
  key: 1,
  stem: 'A 12-year-old girl developed a severe sore throat and lethargy. Amoxicillin was prescribed. The next day, she developed a florid maculopapular rash. Which organism is most likely the causative agent?',
  opts: ['Cytomegalovirus', 'Epstein-Barr virus', 'Parvovirus', 'Roseola infantum', 'Group A Streptococcus'],
  expl: 'Epstein-Barr virus (EBV), the cause of infectious mononucleosis, commonly leads to a generalized maculopapular rash if treated with amoxicillin. The rash is not allergic but a drug-virus interaction.' },

{ n: 43, pr: 43, p: 1051,
  key: 1,
  stem: 'Naser, a newborn baby, is noted to have hepatosplenomegaly and a petechial rash. His red reflex is abnormal, and he fails his newborn hearing screen. There is no heart murmur. His mother\'s antenatal screening bloods were normal. What is the most likely diagnosis?',
  opts: ['Dysmorphic syndrome', 'Congenital infection', 'Infant of diabetic mother', 'Cranial abnormality', 'Neonatal infection'],
  expl: 'This presentation is classic for congenital CMV infection, which causes sensorineural hearing loss, chorioretinitis, and petechiae due to thrombocytopenia. Normal antenatal screening does not always detect CMV.' },

{ n: 44, pr: 44, p: 1053,
  key: 2,
  stem: 'Which of the following infections is typically associated with orchitis?',
  opts: ['Chickenpox', 'Measles', 'Mumps', 'Rubella', 'Scarlet fever'],
  expl: 'Mumps virus can lead to orchitis, particularly in post-pubertal males, and may cause testicular pain and swelling. It can rarely lead to infertility if bilateral.' },

{ n: 45, pr: 45, p: 1055,
  key: 0,
  stem: 'A 14-year-old boy develops a morbilliform rash after being prescribed amoxicillin for an upper respiratory tract infection. What is the most likely cause of the initial infection?',
  opts: ['Glandular fever', 'Measles', 'Parvovirus', 'Rhinovirus', 'Streptococcus A'],
  expl: 'Amoxicillin in the setting of infectious mononucleosis (EBV) often leads to a characteristic non-allergic, morbilliform rash. This is a diagnostic clue for glandular fever.',
  note: 'Same clinical pattern as n42 (amoxicillin rash unmasking EBV) — worded and keyed differently ("Glandular fever" here vs "Epstein-Barr virus" there); both printed as separate questions, staged verbatim.' },

{ n: 46, pr: 46, p: 1057,
  key: 0,
  stem: 'You are asked to see a 1-week-old baby with irritability, high-pitched cry, and a bulging fontanelle. Meningitis is suspected. Which microorganism is the most likely cause in this age group?',
  opts: ['Group B Streptococcus', 'Haemophilus influenzae type B', 'Mycobacterium tuberculosis', 'Neisseria meningitidis', 'Staphylococcus aureus'],
  expl: 'Group B Streptococcus is the leading cause of early neonatal meningitis. It\'s acquired during birth and presents within the first week of life.' },

{ n: 47, pr: 47, p: 1059,
  key: 4,
  stem: 'Which of the following are possible complications of impetigo?',
  opts: ['Cellulitis', 'Guttate psoriasis', 'Sepsis', 'Staphylococcal scalded skin syndrome', 'All of the above'],
  expl: 'Impetigo, a superficial skin infection, can lead to complications like cellulitis, sepsis, and post-infectious issues like guttate psoriasis or staphylococcal scalded skin syndrome.' },

{ n: 48, pr: 48, p: 1061,
  key: 3,
  stem: 'A 7-year-old boy presents with fever and severe headache. He has vomited six times in the last few hours. On examination, he is drowsy with a temperature of 38°C, heart rate of 135/min, and blood pressure of 90/60 mmHg. Knee extension is markedly limited when the hip is flexed. What is the next most important step?',
  opts: ['Complete blood count', 'Blood culture for aerobic and anaerobic organisms', 'Brain CT', 'CSF examination and culture', 'ESR and C-reactive protein'],
  expl: 'This presentation is strongly suggestive of meningitis, and the next essential step is lumbar puncture for CSF analysis and culture, unless contraindications exist.' },

/* ENDPOINT part1 — SECTION 9 "Infection and Immunity" — staging half C (n49..n72). */

{ n: 49, pr: 49, p: 1063,
  key: 4,
  stem: 'The following are contraindications to further pertussis immunization EXCEPT:',
  opts: ['Encephalopathy within 7 days', 'Persistent screaming', 'Convulsions within 48–72 hours', 'Shock', 'Fever of 39.5°C'],
  expl: 'Mild to moderate fever is not a contraindication to vaccination. Serious neurologic events such as encephalopathy or prolonged convulsions may be contraindications.',
  note: 'Key highlighted: yellow box on "e. Fever of 39.5°C".' },

{ n: 50, pr: 50, p: 1065,
  key: 3,
  stem: 'A 50-month-old child presents with a 1-day history of intermittent fever and runny nose. She is eating less but continues to drink fluids. On examination, her temperature is 37.9°C and she has a fine macular rash mainly over the trunk. What is the most likely causative agent?',
  opts: ['Measles', 'Parvovirus B19', 'Roseola infantum', 'Rhinovirus'],
  expl: 'This child has a short history of mild fever, coryza, and a fine trunk rash, consistent with a viral exanthem from a common cold virus. Measles causes high fever and facial rash, parvovirus B19 causes a "slapped cheek" rash, and roseola usually affects children under 3 years with several days of high fever before rash.',
  note: '4 options only (a-d). Key highlighted: yellow box on "d. Rhinovirus".' },

{ n: 51, pr: 51, p: 1067,
  key: 4,
  stem: 'Which of the following vaccines does not help prevent pneumonia?',
  opts: ['Pneumococcal vaccine', 'Varicella vaccine', 'Haemophilus influenzae type B vaccine', 'Measles vaccine', 'Rotavirus vaccine'],
  expl: 'Rotavirus vaccine prevents viral gastroenteritis, not pneumonia. The other listed vaccines (e.g., pneumococcal, Hib, measles, varicella) can prevent pneumonia.',
  note: 'Key highlighted: yellow box on "e. Rotavirus vaccine".' },

{ n: 52, pr: 52, p: 1069,
  key: 2,
  stem: 'What typically happens when a patient with infectious mononucleosis is incorrectly treated with ampicillin?',
  opts: ['Severe anaphylactic reaction', 'Rapid defervescence', 'Diffuse erythematous rash', 'Excessive nausea and vomiting', 'Severe diarrhea'],
  expl: 'Ampicillin or amoxicillin given during EBV infection commonly leads to a widespread erythematous rash, which is not due to allergy but a drug-virus interaction.',
  note: 'Key highlighted: yellow box on "c. Diffuse erythematous rash".' },

{ n: 53, pr: 53, p: 1071,
  key: 3,
  stem: "Joseph, aged 3 years, has been unwell for 24 hours with irritability, vomiting, and fever. He was seen by his general practitioner earlier in the day and started on amoxicillin. On examination, his temperature is 38.5°C, pulse is 140 beats/min, and blood pressure is 90/60 mmHg. He has a rash on his upper limbs and abdomen as shown in the figure. What is the most likely diagnosis?",
  opts: ['Henoch-Schönlein purpura', 'Immune thrombocytopenic purpura', 'Measles', 'Meningococcal sepsis', 'Pertussis'],
  expl: 'The rapid onset of fever, vomiting, irritability, hypotension, and a purpuric rash is highly suggestive of meningococcal sepsis, a medical emergency caused by Neisseria meningitidis. Immediate treatment is critical to prevent fatal outcomes.',
  fig: true,
  figAlt: 'Close-up clinical photo of the skin of the upper limb and abdomen of a child.',
  note: 'Key highlighted: yellow box on "D. Meningococcal sepsis".' },

{ n: 54, pr: 54, p: 1073,
  key: 2,
  stem: "What investigation is most likely to give a definitive diagnosis in Joseph's case? Select one answer only.",
  opts: ['Blood culture', 'Lumbar puncture', 'Polymerase chain reaction (PCR)', 'Pernasal swab', 'Throat swab'],
  expl: 'PCR testing for meningococcal DNA in blood or CSF is rapid and highly sensitive, often giving a quicker diagnosis than cultures, especially if antibiotics have already been started.',
  note: 'Continuation of the Joseph vignette from n53. Key highlighted: yellow box on "C. Polymerase chain reaction (PCR)".' },

{ n: 55, pr: 55, p: 1075,
  key: 0,
  stem: 'Henry is 4 years old and has a 3-day history of fever. He presents to the Emergency Department with a headache. A lumbar puncture is performed with the following CSF result: 250 RBCs/mm³, 1200 neutrophils/mm³, 250 lymphocytes/mm³, Protein: 0.6 g/L, CSF glucose: 2.1 mmol/L, Blood glucose: 7.2 mmol/L. What is the most likely diagnosis?',
  opts: ['Bacterial meningitis', 'Blood-stained tap', 'Normal lumbar puncture result', 'Tuberculosis meningitis', 'Viral meningitis'],
  expl: 'The high neutrophil count and low CSF glucose relative to blood glucose indicate bacterial meningitis, which typically presents with a neutrophilic CSF response and hypoglycorrhachia.',
  note: 'Key highlighted: yellow box on "A. Bacterial meningitis".' },

{ n: 56, pr: 56, p: 1077,
  key: 3,
  stem: 'Graham, 5 years old, presents with a 4-week history of intermittent fever, headache, and neck stiffness. CT scan is normal. CSF results: 95 lymphocytes/mm³, 10 neutrophils/mm³, 0 RBCs/mm³, Protein: 2.2 g/L, CSF glucose: 1.3 mmol/L, Blood glucose: 6.3 mmol/L. What is the most likely diagnosis?',
  opts: ['Ascending polyneuritis (Guillain-Barré syndrome)', 'Bacterial meningitis', 'Blood-stained tap', 'Tuberculosis meningitis', 'Viral meningitis'],
  expl: 'TB meningitis typically causes a lymphocytic CSF response, high protein, and very low CSF glucose. Chronic symptoms also support this diagnosis.',
  note: 'Key highlighted: yellow box on "D. Tuberculosis meningitis".' },

{ n: 57, pr: 57, p: 1079,
  key: 0,
  stem: 'John, a 2-year-old boy, has a rash on both feet and tender lesions on his hands. He is otherwise well. What is the most likely cause?',
  opts: ['Coxsackie A', 'Flea bites', 'Herpes zoster', 'Scabies', 'Varicella zoster'],
  expl: 'Coxsackie A virus causes hand, foot, and mouth disease, characterized by vesicular lesions on the hands, feet, and sometimes the mouth, often in otherwise well children.',
  fig: true,
  figAlt: 'Close-up clinical photo of the sole and toes of a child\'s foot.',
  note: 'Key highlighted: yellow box on "A. Coxsackie A".' },

{ n: 58, pr: 58, p: 1081,
  key: 4,
  stem: 'Imran, a 3-year-old boy who recently moved from Bangladesh, has not gained weight and presents with a cough. A chest X-ray is requested. What is the most likely diagnosis?',
  opts: ['Asthma', 'Neuroblastoma', 'Pertussis infection', 'Pneumonia', 'Tuberculosis'],
  expl: 'A history of recent immigration, failure to thrive, and chronic cough are red flags for tuberculosis, especially in high-prevalence countries like Bangladesh.',
  fig: true,
  figAlt: 'Frontal chest X-ray of a child.',
  note: 'Key highlighted: yellow box on "E. Tuberculosis".' },

{ n: 59, pr: 59, p: 1083,
  key: 2,
  stem: 'Harry, 21 months old, has a 3-day history of cough, fever, conjunctivitis, and a widespread rash. What is the most likely causative organism?',
  opts: ['Influenza virus', 'Rhinovirus', 'Measles virus', 'Roseola infantum', 'Cytomegalovirus'],
  expl: 'The classic triad of cough, coryza, and conjunctivitis followed by a maculopapular rash points to measles, caused by the measles virus.',
  fig: true,
  figAlt: 'Clinical photo of an infant\'s face and upper torso.',
  note: 'Key highlighted: yellow box on "C. Measles virus".' },

{ n: 60, pr: 60, p: 1085,
  key: 0,
  stem: 'Maryam, 10 months old, has an intermittent fever for one day, a runny nose, and a fine macular rash on her trunk. What is the most likely causative organism?',
  opts: ['Rhinovirus', 'HIV', 'RSV', 'EBV', 'Varicella zoster'],
  expl: 'A mild upper respiratory illness with a macular rash is often due to rhinovirus, a common cause of viral URTIs in infants.',
  note: 'Key highlighted: yellow box on "A. Rhinovirus". Looks like a possible repeat of n50 (p.1065) — check it. n50 stem: "A 50-month-old child presents with a 1-day history of intermittent fever and runny nose. She is eating less but continues to drink fluids. On examination, her temperature is 37.9°C and she has a fine macular rash mainly over the trunk. What is the most likely causative agent?" (opts Measles/Parvovirus B19/Roseola infantum/Rhinovirus, key Rhinovirus). n60 stem: "Maryam, 10 months old, has an intermittent fever for one day, a runny nose, and a fine macular rash on her trunk. What is the most likely causative organism?" (opts Rhinovirus/HIV/RSV/EBV/Varicella zoster, key Rhinovirus). Different age (50mo vs 10mo), different option sets — staged as separate entries, not folded.' },

{ n: 61, pr: 61, p: 1087,
  key: 3,
  stem: 'Jennifer, 12 years old, developed a severe sore throat and lethargy. She was prescribed amoxicillin and developed a florid maculopapular rash the next day. What is the most likely causative organism?',
  opts: ['Mumps virus', 'Measles virus', 'RSV', 'Epstein-Barr virus (EBV)', 'Rhinovirus'],
  expl: 'In EBV (infectious mononucleosis), administration of amoxicillin often causes a widespread rash, which is a hallmark clue for the diagnosis.',
  fig: true,
  figAlt: 'Clinical photo of a child\'s torso.',
  note: 'Key highlighted: yellow box on "D. Epstein-Barr virus (EBV)".' },

{ n: 62, pr: 62, p: 1089,
  key: 0,
  stem: 'Philip is 4 years old and presents with a widespread, intensely itchy vesicular rash after starting school. What is the most likely causative organism?',
  opts: ['Chickenpox (varicella zoster virus)', 'Measles virus', 'Mumps virus', 'Lyme disease (Borrelia burgdorferi)', 'Chickenpox virus (varicella zoster virus)'],
  expl: 'Chickenpox, caused by varicella zoster virus, typically presents with an itchy vesicular rash in children. It is highly contagious and common after starting school.',
  fig: true,
  figAlt: 'Clinical photo of a child\'s back.',
  note: 'Key highlighted: yellow box on "A. Chickenpox (varicella zoster virus)". Options A and E are printed as near-duplicate text ("Chickenpox (varicella zoster virus)" vs "Chickenpox virus (varicella zoster virus)") — transcribed verbatim as printed, not corrected.' },

{ n: 63, pr: 63, p: 1091,
  key: 0,
  stem: 'Katie, age 6, has a fever and a bright red "slapped cheek" rash on both cheeks. What is the most likely causative organism?',
  opts: ['Parvovirus B19 (fifth disease)', 'Roseola infantum (sixth disease)', 'Measles virus', 'Mumps virus', 'Cytomegalovirus'],
  expl: 'Parvovirus B19 causes erythema infectiosum (fifth disease), which presents with a "slapped cheek" rash and mild systemic symptoms. It\'s common in school-aged children.',
  note: 'Key highlighted: yellow box on "A. Parvovirus B19 (fifth disease)".' },

{ n: 64, pr: 64, p: 1093,
  key: 1,
  stem: 'Mohammed, age 2, has fever, cough, and crackles at the left lung base. He is stable but not eating. What is the next best step in management?',
  opts: ['Oral rehydration solution', 'Oral antibiotic', 'Intravenous immunoglobulin', 'Combined anti-tuberculosis medication', 'Antipyretic/analgesia'],
  expl: 'Crackles suggest pneumonia. Since he is stable with normal oxygen saturation and hydration, oral antibiotics are appropriate.',
  note: 'Key highlighted: yellow box on "B. Oral antibiotic".' },

{ n: 65, pr: 65, p: 1095,
  key: 2,
  stem: 'Imran, age 2, has fever and cough. Vitals are stable, and examination shows only pharyngitis. What is the best next step in management?',
  opts: ['Nasogastric rehydration therapy', 'Intravenous antibiotics', 'Antipyretic/analgesia', 'Oxygen', 'Oral antibiotic'],
  expl: 'A viral upper respiratory tract infection is likely. Supportive care with antipyretics is sufficient unless bacterial features emerge.',
  note: 'Key highlighted: yellow box on "C. Antipyretic/analgesia".' },

{ n: 66, pr: 66, p: 1097,
  key: 0,
  stem: 'Mustafa, 18 months old, has vomiting and diarrhea with signs of mild dehydration but no shock. What is the best next step?',
  opts: ['Oral rehydration solution', 'Nasogastric rehydration therapy', 'IV bolus 20 ml/kg NS', 'IV antibiotics', 'Oral antibiotic'],
  expl: 'The child is mildly to moderately dehydrated without shock, so oral rehydration is the appropriate first step.',
  note: 'Key highlighted: yellow box on "A. Oral rehydration solution". Not purely infectious topic (gastroenteritis/dehydration) — staged as printed, per section 9\'s mixed content.' },

{ n: 67, pr: 67, p: 1099,
  key: 0,
  stem: 'Josie, age 3, has fever, tachypnea, and signs of consolidation with hypoxia. What is the most appropriate management?',
  opts: ['Intravenous antibiotics', 'Oral antibiotics', 'IV immunoglobulin', 'Antiretroviral therapy', 'Antipyretic/analgesia'],
  expl: 'The clinical picture suggests pneumonia with respiratory distress and hypoxia, requiring inpatient care and IV antibiotics.',
  note: 'Key highlighted: yellow box on "A. Intravenous antibiotics".' },

{ n: 68, pr: 68, p: 1101,
  key: 2,
  stem: "A 2-year-old boy has barking cough, stridor, and intercostal recession. What's the most likely causative organism?",
  opts: ['Adenovirus', 'RSV', 'Parainfluenza virus', 'Rhinovirus', 'Influenza virus'],
  expl: 'Croup (laryngotracheobronchitis) is most commonly caused by parainfluenza virus and presents with a barking cough and stridor.',
  note: 'Key highlighted: yellow box on "C. Parainfluenza virus".' },

{ n: 69, pr: 69, p: 1103,
  key: 2,
  stem: 'A 6-month-old develops a blanching rash after fever resolves. Cultures are negative. What is the likely diagnosis?',
  opts: ['Measles', 'Rubella', 'Roseola infantum', 'Scarlet fever', 'Chickenpox'],
  expl: 'Roseola (HHV-6) causes high fever for a few days followed by a sudden rash after the fever subsides—classic in infants.',
  note: 'Key highlighted: yellow box on "C. Roseola infantum".' },

{ n: 70, pr: 70, p: 1105,
  key: 3,
  stem: 'A 3-year-old girl has fever, conjunctivitis, rash, lymphadenopathy, and extremity redness. IVIG and aspirin are started. What test is essential?',
  opts: ['Full blood count', 'Throat swab', 'ASO titer', 'Echocardiogram', 'CXR'],
  expl: 'This is Kawasaki disease, which may cause coronary artery aneurysms. An echocardiogram is crucial to monitor cardiac involvement.',
  note: 'Key highlighted: yellow box on "D. Echocardiogram".' },

{ n: 71, pr: 71, p: 1107,
  key: 2,
  stem: 'A 6-year-old has fever, neck stiffness, and CSF showing 8000 polymorphs, high protein, and low glucose. Diagnosis?',
  opts: ['TB meningitis', 'Viral meningitis', 'Bacterial meningitis', 'Encephalitis', 'Non-meningitis'],
  expl: 'High neutrophils, low glucose, and high protein in CSF are classic for bacterial meningitis.',
  note: 'Key highlighted: yellow box on "C. Bacterial meningitis". Same topic (CSF-pattern meningitis diagnosis) as n55/n56 but a distinct, shorter vignette with different numbers and no patient name — not a repeat, staged separately.' },

{ n: 72, pr: 72, p: 1109,
  key: 3,
  stem: "A 2-year-old girl has fever but is well-appearing with no localizing signs. What's the most appropriate next step?",
  opts: ['CXR', 'Inflammatory markers', 'Blood culture', 'Urine dipstick', 'Discharge'],
  expl: 'In children with fever and no focus, urinary tract infection must be excluded with a urine dipstick test.',
  note: 'Key highlighted: yellow box on "D. Urine dipstick".' },

/* ENDPOINT part1 — SECTION 9 "Infection and Immunity" — staging half D (n73..n95). */

{ n: 73, pr: 73, p: 1111,
  key: 2,
  stem: "A two-month-old male infant presents with history of fever for 6 days. No respiratory or GI symptoms and no improvement with symptomatic treatment. On examination, the child is sick looking and lethargic. What is the best next step in his management?",
  opts: ['Admit the child for more close examination and investigations in a controlled setting', 'Send the preliminary investigations and continue symptomatic treatment', 'Full septic work up and start broad spectrum IV antibiotics', 'Hydrate the infant and observe for fever'],
  expl: 'Any febrile infant under 3 months requires a full septic screen and empirical IV antibiotics regardless of appearance.',
  note: 'Only FOUR options printed (A-D) — no option E on this page. Key highlighted: yellow box on "C. Full septic work up and start broad spectrum IV antibiotics". Whole question (stem, options, key, explanation) prints on a single page, 1111.' },

{ n: 74, pr: 74, p: 1113,
  key: 3,
  stem: "A 10-year-old with fever, pharyngitis, lymphadenopathy, and atypical lymphocytes. Most likely diagnosis?",
  opts: ['Coxsackievirus', 'HSV', 'VZV', 'Epstein-Barr virus', 'CMV'],
  expl: 'Epstein-Barr virus (EBV) causes infectious mononucleosis with fever, sore throat, lymphadenopathy, hepatosplenomegaly, and atypical lymphocytes.',
  note: 'Key highlighted: yellow box on "D. Epstein-Barr virus". This question is printed twice — plain (no key) on 1112, then repeated with key + explanation on 1113; p records the keyed page.' },

{ n: 75, pr: 75, p: 1115,
  key: 3,
  stem: "A 9-year-old has coronary artery dilatation years after an undiagnosed febrile illness. What could have prevented this?",
  opts: ['Antibiotics', 'Antivirals', 'Antifungals', 'Immunoglobulin', 'Immunization'],
  expl: 'IV immunoglobulin given during acute Kawasaki disease significantly reduces the risk of coronary aneurysms.',
  note: 'Key highlighted: yellow box on "D. Immunoglobulin". Printed twice — plain on 1114, keyed on 1115; p records the keyed page.' },

{ n: 76, pr: 76, p: 1117,
  key: 2,
  stem: "A 6-week-old infant has gram-positive cocci in chains on CSF gram stain. Most likely organism?",
  opts: ['N. meningitidis', 'H. influenzae', 'Group B Streptococcus', 'S. aureus', 'L. monocytogenes'],
  expl: 'Group B Streptococcus is the most common cause of neonatal meningitis, often seen as gram-positive cocci in chains.',
  note: 'Key highlighted: yellow box on "C. Group B Streptococcus". Printed twice — plain on 1116, keyed on 1117; p records the keyed page.' },

{ n: 77, pr: 77, p: 1119,
  key: 4,
  stem: "Which pathogen is not typically associated with vesicular skin lesions?",
  opts: ['Herpes zoster', 'Varicella zoster', 'Staph. aureus', 'Herpes simplex', 'Human herpesvirus (e.g. HHV-6)'],
  expl: 'HHV-6 causes roseola, which results in a maculopapular rash—not vesicular. Others are known to cause vesicles.',
  note: 'Key highlighted: yellow box on "E. Human herpesvirus (e.g. HHV-6)". Printed twice — plain on 1118, keyed on 1119; p records the keyed page.' },

{ n: 78, pr: 78, p: 1121,
  key: 3,
  stem: "A toddler with severe egg allergy needs MMR vaccine. What is the best advice?",
  opts: ['He can safely receive all vaccines', 'Do not give MMR', 'Avoid all live vaccines', 'MMR can be given in hospital; avoid influenza/yellow fever', 'Give MMR with antihistamine'],
  expl: 'MMR is safe even in children with egg allergy, though hospital administration is preferred in severe cases. Influenza and yellow fever vaccines pose more risk.',
  note: 'Key highlighted: yellow box on "D. MMR can be given in hospital; avoid influenza/yellow fever". Printed twice — plain on 1120, keyed on 1121; p records the keyed page.' },

{ n: 79, pr: 79, p: 1123,
  key: 1,
  stem: "A 4-year-old boy presents to the emergency room with fever, irritability, headache, and neck stiffness. Meningitis is suspected and a lumbar puncture is performed. His blood glucose level is 4.3 mmol/L. Which of the following cerebrospinal fluid (CSF) findings is most suggestive of bacterial meningitis?",
  opts: ['WCC 18 × 10⁶/L (20% neutrophils), RBC 6 × 10⁶/L, protein 0.8 g/L, glucose 3.0 mmol/L', 'WCC 20 × 10⁶/L (80% neutrophils), RBC 5 × 10⁶/L, protein 1.6 g/L, glucose 1.0 mmol/L', 'WCC 22 × 10⁶/L (25% neutrophils), RBC 4 × 10⁶/L, protein 2.4 g/L, glucose 1.2 mmol/L', 'WCC 5 × 10⁶/L, RBC 4000 × 10⁶/L, protein 0.4 g/L, glucose 3.0 mmol/L'],
  expl: '',
  note: 'Only FOUR options printed (A-D) — no option E on this page, either plain (1122) or keyed (1123) printing. Key highlighted: yellow box on "B. WCC 20 x 10^6/L (80% neutrophils)...". NO explanation box is printed for this question on 1123. Superscript "6" in "10^6" read directly off the rendered page image, not from OCR. CORRECTED 2026-09-03: this row previously carried an AUTHORED sentence in `expl` ("A CSF profile of high WCC with a predominance of neutrophils, elevated protein, and low CSF:blood glucose ratio (here 1.0/4.3, markedly reduced) is classic for bacterial meningitis; this matches option B."), contradicting this same note. `expl` is the verbatim-printed-box field and the whole pipeline reads non-empty as "the book printed a box here": val-pd-ep.js therefore demanded the boxed explanation shape, and the drafted entry duly told the reader "The endpoint file prints this explanation:" above text the book never printed. Set to \'\' so the unboxed shape is required instead. No instrument could see this — the validator derives boxed-vs-unboxed from this field alone.' },

{ n: 80, pr: 80, p: 1125,
  key: 0,
  stem: "A mother with no prior chickenpox exposure is breastfeeding a neonate and her toddler has chickenpox. Best step?",
  opts: ['Check maternal antibodies; if negative, give VZIG', 'Observe neonate', 'Discharge and isolate', 'No precautions', 'Treat neonate with aciclovir'],
  expl: 'Neonates are at risk if the mother lacks immunity. If maternal antibodies are absent, VZIG is indicated.',
  note: 'Key highlighted: yellow box on "A. Check maternal antibodies; if negative, give VZIG". Printed twice — plain on 1124, keyed on 1125; p records the keyed page.' },

{ n: 81, pr: 81, p: 1127,
  key: 4,
  stem: "Which of the following is not a contraindication to live vaccination?",
  opts: ['Acute fever >38°C', 'High-dose steroids', 'Previous severe reaction', 'Immunodeficiency', 'Weight <2.5 kg'],
  expl: 'Low birth weight is not a contraindication. Live vaccines should be avoided in immunocompromised patients or those acutely unwell.',
  note: 'Key highlighted: yellow box on "E. Weight <2.5 kg". Printed twice — plain on 1126, keyed on 1127; p records the keyed page.' },

{ n: 82, pr: 82, p: 1129,
  key: 4,
  stem: "A 15-year-old boy presents to the hospital with malaise, fever, and mild jaundice over the last week. On examination, there is intense inflammation of the tonsils with discharge, splenomegaly, and cervical lymphadenopathy. What is the most likely cause of his illness?",
  opts: ['Acute lymphoblastic leukemia', 'Beta hemolytic Streptococcus', 'Hepatitis A infection', 'Non-Hodgkins lymphoma', 'Epstein-Barr infection (EBV)'],
  expl: 'EBV causes infectious mononucleosis with hepatosplenomegaly, fatigue, and pharyngitis. It often spreads in close contact, like among students.',
  note: 'Key highlighted: yellow box on "E. Epstein-Barr infection (EBV)". Printed twice — plain on 1128, keyed on 1129; p records the keyed page.' },

{ n: 83, pr: 83, p: 1131,
  key: 2,
  stem: "An 18-month-old boy is seen in the clinic for evaluation of 4 days of fever, “pink eye,” and irritability. Along with the conjunctivitis, he also has a generalized maculopapular rash. The mother reports that there are several sick contacts at his daycare. Which of the following examination findings would prompt you to order an echocardiogram?",
  opts: ['A tender 5-mm preauricular lymph node', 'Shallow ulcers on the gingiva', 'Red lips, palms, and soles', 'Hepatosplenomegaly', 'Bilateral crackles and wheezes'],
  expl: 'These are classic features of Kawasaki disease, which carries a risk of coronary artery aneurysm. Echocardiography is required to evaluate cardiac involvement.',
  note: 'Key highlighted: yellow box on "C. Red lips, palms, and soles". Printed twice — plain on 1130, keyed on 1131; p records the keyed page.' },

{ n: 84, pr: 84, p: 1133,
  key: 1,
  stem: "A 6-year-old girl presents with a history of 4 days of fever, headache, rash, and sore throat. The rash is maculopapular, blanching, with a sandpaper-like texture and located on the cheeks, axillae, and trunk, with streaks of linear confluent petechiae on the axillae and in the antecubital fossa. Tonsillar erythema and exudates are noted along with an erythematous oropharynx and strawberry tongue. The lips and conjunctiva are normal. What is the most appropriate management?",
  opts: ['Measles immunoglobulin', 'Rapid strep test', 'IVIG and high-dose aspirin', 'Supportive care with antipyretics', 'Serum autoantibodies and rheumatology consult'],
  expl: 'This is scarlet fever caused by Group A strep. Diagnosis is confirmed with a strep test, and treatment with penicillin/antibiotics is then given.',
  note: 'Key highlighted: yellow box on "B. Rapid strep test". Printed twice — plain on 1132, keyed on 1133; p records the keyed page.' },

{ n: 85, pr: 85, p: 1135,
  key: 3,
  stem: "A 5-month-old irritable infant has 7 days of high fever, an erythematous rash in the diaper region, and swollen, red lips. He has a mild normocytic anemia, a white blood cell count (WBC) of 15,000/mm³ with a predominance of neutrophils and immature forms, and an erythrocyte sedimentation rate (ESR) of 80 mm/h. Urinalysis is normal, but the cerebrospinal fluid shows pleocytosis with a negative Gram stain and negative culture. Blood culture is negative. After 48 hours of ceftriaxone, he continues to have high fever and has developed foot edema. Subsequent management of this child should include which of the following?",
  opts: ['Nystatin for the diaper rash', 'Repeat of the spinal tap', 'Addition of vancomycin to the antibiotic regimen', 'Pediatric cardiology consultation for echocardiogram', 'Continuing current management and following the culture results'],
  expl: 'This is atypical Kawasaki disease, not bacterial sepsis. Prolonged fever with mucocutaneous findings and no bacterial source warrants cardiac evaluation.',
  note: 'Key highlighted: yellow box on "D. Pediatric cardiology consultation for echocardiogram". Printed twice — plain on 1134, keyed on 1135; p records the keyed page.' },

{ n: 86, pr: 86, p: 1137,
  key: 4,
  stem: "A 7-year-old girl has had 5 days of fever, conjunctivitis, erythema of the oropharynx, and a generalized maculopapular rash. Her lips, lymph nodes, and extremities appear normal. Which of the following laboratory tests would NOT be used to establish a diagnosis?",
  opts: ['Complete blood cell count (CBC)', 'Urinalysis (UA)', 'C-reactive protein (CRP)', 'Erythrocyte sedimentation rate (ESR)', 'Antinuclear antibody (ANA)'],
  expl: 'Kawasaki disease is diagnosed with CBC, ESR, CRP, UA (sterile pyuria) but ANA is not useful. ANA is for autoimmune disease, not Kawasaki.',
  note: 'Key highlighted: yellow box on "E. Antinuclear antibody (ANA)". Printed twice — plain on 1136, keyed on 1137; p records the keyed page.' },

{ n: 87, pr: 87, p: 1139,
  key: 1,
  stem: "At a 2-month-old well-child checkup, a female infant is noted to have the following physical findings: widely open anterior and posterior fontanels, large protruding tongue, coarse facial features, low-set hair line, and an umbilical hernia. In her newborn period, she had a history of prolonged physiologic icterus. Which of the following diagnoses is consistent with this clinical presentation?",
  opts: ['Congenital adrenal hyperplasia', 'Congenital hypothyroidism', 'Crigler-Najjar syndrome', 'Galactosemia', 'Gilbert syndrome'],
  expl: 'Classic presentation of untreated congenital hypothyroidism, which can lead to developmental delay if not treated with levothyroxine.',
  note: 'OFF-TOPIC — this is an endocrine/neonatal-jaundice question (congenital hypothyroidism), not infection/immunity, but it is transcribed here because it appears inside Section 9 of the book (see brief §3). Key highlighted: yellow box on "B. Congenital hypothyroidism". Printed twice — plain on 1138, keyed on 1139; p records the keyed page.' },

{ n: 88, pr: 88, p: 1141,
  key: 3,
  stem: "It is postulated that antibody-antigen complexes are responsible for some viral exanthems because the rash does not appear until after the patient begins to recover. Which of the following viral illnesses follows this pattern of rash appearance concurrent with recovery?",
  opts: ['Hand, foot, and mouth disease', 'Kawasaki disease', 'Rocky Mountain spotted fever', 'Roseola'],
  expl: 'HHV-6 roseola presents with 3–5 days of high fever followed by a maculopapular rash after defervescence, unlike measles/rubella where rash and fever overlap.',
  note: 'Only FOUR options printed (A-D) — no option E on either printing. Key highlighted: yellow box on "D. Roseola". Printed twice — plain on 1140, keyed on 1141; p records the keyed page.' },

{ n: 89, pr: 89, p: 1143,
  key: 3,
  stem: "A 13-year-old boy presents with four days of sore throat, low grade fever, and generalized malaise. He denies significant nasal congestion or cough. On examination, he has 2+ erythematous tonsils covered in white exudate, bilateral posterior cervical adenopathy, as well as shotty axillary and inguinal lymphadenopathy. Which of the following is indicated?",
  opts: ['Course of oral prednisone', 'Drainage of peritonsillar abscess', 'Intramuscular penicillin G', 'Supportive care'],
  expl: 'This is infectious mononucleosis (EBV). No antibiotics are needed, and amoxicillin is contraindicated due to risk of rash.',
  note: 'Only FOUR options printed (A-D) — no option E on either printing. Key highlighted: yellow box on "D. Supportive care". Printed twice — plain on 1142, keyed on 1143; p records the keyed page.' },

{ n: 90, pr: 90, p: 1145,
  key: 2,
  stem: "A 5-year-old boy has a height which is 2.1 standard deviations below normal for his age. His height velocity is six centimeters per year. When calculated, the boy's projected height is 2.2 standard deviations below the mid-parental height. His parents state he has been in good health and no abnormalities are found on physical exam other than short stature. Which of the following is the most appropriate next step in evaluation of this boy's short stature?",
  opts: ['Complete blood count and erythrocyte sedimentation rate to screen for anemia or autoimmune disease', 'Karyotype testing to screen for Turner syndrome', 'Radiographs of left wrist and hand to determine bone age', 'Tissue transglutaminase IgA test to screen for celiac disease'],
  expl: 'Bone age distinguishes constitutional growth delay (delayed bone age, normal adult height) from pathologic causes of short stature.',
  note: 'OFF-TOPIC — this is an endocrine/growth question (short stature workup), not infection/immunity, but it is transcribed here because it appears inside Section 9 of the book (see brief §3). Only FOUR options printed (A-D). Key highlighted: yellow box on "C. Radiographs of left wrist and hand to determine bone age". Printed twice — plain on 1144, keyed on 1145; p records the keyed page.' },

{ n: 91, pr: 91, p: 1147,
  key: 1,
  stem: "A 4-month-old girl presents with two weeks of cough that includes severe coughing episodes with associated cyanosis, respiratory distress, and post-tussive emesis. Her mother and father both have upper respiratory infections. Which of the following is the treatment of choice?",
  opts: ['Amoxicillin', 'Azithromycin', 'Nebulized albuterol', 'Reassurance'],
  expl: 'This is pertussis (whooping cough). Macrolides (azithromycin/clarithromycin) are the treatment of choice and also used for prophylaxis.',
  note: 'OFF-TOPIC — this is a respiratory-infection question (pertussis), not infection/immunity per se, but transcribed in place per brief §3 since it prints inside Section 9. Only FOUR options printed (A-D) — no option E on either printing. Key highlighted: yellow box on "B. Azithromycin". Printed twice — plain on 1146, keyed on 1147; p records the keyed page.' },

{ n: 92, pr: 92, p: 1149,
  key: 2,
  stem: "A 10-year-old girl presents to clinic due to a generalized rash. History reveals that four days prior the onset of rash she was noted to have low-grade fever, runny nose, cough, and conjunctival congestion. The rash is characterized as red, maculopapular eruptions which were noted to first appear on the forehead before spreading downward to the extremities. The physical examination reveals a weak-looking girl with anicteric sclerae, pink conjunctivae, cervical and occipital lymphadenopathy, harsh breath sounds, adynamic precordium, no heart murmur, soft non-tender abdomen, full equal pulses, capillary return time of less than two seconds, and maculopapular rashes on the lower trunk and extremities with brawny desquamation on the upper trunk. Further history reveals that she is missing some of her immunizations. Which of the following is the most likely diagnosis?",
  opts: ['Exanthem subitum', 'Kawasaki disease', 'Measles', 'Rubella'],
  expl: 'The triad of cough, coryza, conjunctivitis, followed by a descending maculopapular rash starting from the forehead, is classic for measles.',
  note: 'Only FOUR options printed (A-D) — no option E on either printing. Key highlighted: yellow box on "C. Measles". Printed twice — plain on 1148, keyed on 1149; p records the keyed page.' },

{ n: 93, pr: 93, p: 1151,
  key: 2,
  stem: "A 10-year-old girl has had a rash for 4 days without other symptoms. She is taking no medications. Physical examination reveals erythematous cheeks and a lacy, reticulated erythema involving the extremities. Of the following, the MOST likely causative organism is:",
  opts: ['Epstein-Barr virus', 'Human Herpes viruses 6,7', 'Parvovirus B19', 'Rubella virus'],
  expl: 'The classic "slapped cheek" appearance and lacy rash on the extremities is typical of fifth disease (erythema infectiosum) caused by Parvovirus B19. Other viruses may cause rash but not this characteristic pattern.',
  note: 'Options printed lower-case (a-d) on this page, unlike the A-D style used elsewhere in this batch — transcribed as printed style is not preserved (opts array has no letter prefixes per schema), only the text. Only FOUR options printed — no option E on either printing. Key highlighted: yellow box on "c. Parvovirus B19". Printed twice — plain on 1150, keyed on 1151; p records the keyed page.' },

{ n: 94, pr: 94, p: 1153,
  key: 2,
  stem: "A 2-year-old girl presents with six days of fever. She has also had a mild cough, red eyes, and nasal congestion. Vital signs are notable for a temperature of 102.5°F and heart rate 135 beats per minute. Examination findings include bilateral conjunctival injection, rhinorrhea, red tongue, bilateral shotty anterior cervical adenopathy with a prominent right sided lymph node, and swollen hands with erythematous palms. Which of the following is most likely to resolve her symptoms?",
  opts: ['Amoxicillin', 'Honey, acetaminophen, and a cool mist humidifier', 'Intravenous immunoglobulin', 'Vancomycin'],
  expl: 'This is Kawasaki disease. Treatment with IVIG + high-dose aspirin reduces risk of coronary aneurysm.',
  note: 'Only FOUR options printed (A-D) — no option E on either printing. Key highlighted: yellow box on "C. Intravenous immunoglobulin". Printed twice — plain on 1152, keyed on 1153; p records the keyed page.' },

{ n: 95, pr: 95, p: 1155,
  key: 2,
  stem: "A 4-month-old male infant has a history of failure to thrive, chronic diarrhea and has been admitted twice to hospital with viral pneumonia since birth. There is evidence of oral thrush. What is the most likely diagnosis?",
  opts: ['Neutrophil defect (Chronic granulomatous disease)', 'B-cell defect (X-linked agammaglobulinemia)', 'T-cell defect (SCID)', 'Leukocyte function defect', 'Complement defects'],
  expl: 'This 4-month-old infant has failure to thrive, chronic diarrhea, recurrent viral pneumonia, and oral thrush, which are classic signs of severe combined immunodeficiency (SCID), a T-cell defect.',
  note: 'Full five options printed (A-E). Key highlighted: yellow box on "C. T-cell defect (SCID)". Printed twice — plain on 1154, keyed on 1155; p records the keyed page. Page 1156 (next page, rendered and checked) is a closing dua graphic in Arabic, not a question — confirms Section 9 / this staging batch ends at n95, page 1155.' }

];
