/* Section 11 "Model Final Exam 2" — half B, staged n30,n31,n32,n33,n34,n35,n36,n37,n41,n44,n45,n46.
   Drafted from content/peds/qb-pages/endpoint-s11-mfe2.array.js (PEDEP_S11_STAGED).
   Bare fragments; splicer strips this header. Id prefix is pedep-mf2- per val-pd-ep.js SEC[11]. */

{
  id: 'pedep-mf2-30',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'gi-abdopain',
  stem: "\"Dance sign\" is:",
  options: ["Sausage-shaped mass on the abdomen","Empty right iliac fossa","Redcurrant jelly","Intermittent colicky abdominal pain"],
  answer: 1,
  explanation: "**Dance's sign is a classic bedside finding in intussusception: on palpation the right iliac fossa feels empty**, because the caecum and terminal ileum have telescoped out of their normal position and migrated along the colon, most often toward the transverse or splenic region, leaving the fossa that should contain them palpably vacant *(the eponym and its definition are not named in the cached course material — searched \"Dance\", \"empty iliac fossa\" and \"intussusception\" in `24)Abdominal pain.txt`, which teaches the diagnosis and its epidemiology but not this specific bedside sign — not taken from the course material)*. `24)Abdominal pain.txt` does ground the disease this sign belongs to: intussusception is defined there as the invagination of proximal bowel into a distal segment, most commonly ileum passing into the caecum through the ileocaecal valve, and it is named the most common cause of intestinal obstruction in infants after the neonatal period, peaking between 3 months and 2 years of age. A palpable sausage-shaped mass (usually in the right upper quadrant, tracking the path the invaginated bowel has taken) and an empty right iliac fossa together are the two classic abdominal findings on examination, and it is the combination — mass present elsewhere, fossa found empty — that makes Dance's sign useful: it tells the examiner where the bowel has gone as much as that it has gone.\n\n**Why each distractor fails.** *Sausage-shaped mass on the abdomen* is a real finding in intussusception, but it is a separate sign describing where the invaginated bowel is felt, not what Dance's sign itself describes, which is the fossa it has left behind. *Redcurrant jelly* stool is the classical late finding from mucosal ischaemia and sloughing in the invaginated segment, a stool appearance rather than a palpation finding. *Intermittent colicky abdominal pain* is the symptom pattern of intussusception — episodic pain with pain-free intervals, often with drawing up of the legs — not a physical examination sign at all.\n\nWritten for this bank — Pediatrics endpoint part1.pdf prints no explanation here.",
  objective: "Dance's sign is a palpably empty right iliac fossa in intussusception, reflecting migration of the caecum and terminal ileum along the invaginated bowel's path — distinct from the sausage-shaped mass, the redcurrant-jelly stool, and the colicky pain pattern the same disease also produces.",
  source: 'Pediatrics endpoint part1.pdf p.1382'
},

{
  id: 'pedep-mf2-31',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'gi-abdopain',
  stem: "The pathognomonic sign in US abdomen in case of intussusception is:",
  options: ["Olive sign","Target sign","Double track sign","Shoulder sign"],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> The “target” or “donut” sign on ultrasound is diagnostic of intussusception.\n\n---\n\n`24)Abdominal pain.txt` grounds why intussusception is the disease being imaged here: it defines intussusception as ileum invaginating through the ileocaecal valve into the caecum, names it the leading cause of intestinal obstruction in infants after the neonatal period, and peaks it between 3 months and 2 years. *The naming of the ultrasound appearance itself as a \"target\" or \"donut\" sign is not spelled out in the lecture, which teaches the diagnosis without describing its imaging findings — not taken from the course material.* On a transverse scan through the invaginated segment, concentric alternating rings of bowel wall and mesenteric fat produce the target-like appearance the box names; on a longitudinal scan the same anatomy can look like a pseudokidney. Ultrasound is preferred for confirmation because it is rapid, radiation-free and highly sensitive for this specific concentric-ring pattern.\n\n**Why each distractor fails.** *Olive sign* is a palpable, not sonographic, finding — the firm, mobile, olive-shaped mass felt in the right upper quadrant in hypertrophic pyloric stenosis, an entirely different disease and a different examination modality (palpation, not ultrasound). *Double track sign* and *shoulder sign* are both classically described on a contrast (barium) study of hypertrophic pyloric stenosis — the double track describes two thin channels of contrast squeezed through the elongated, narrowed pyloric canal, and the shoulder sign describes the bulge of hypertrophied pyloric muscle indenting the antrum — neither belongs to intussusception, and neither is an ultrasound finding.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "The ultrasound-diagnostic sign for intussusception is the target (donut) sign — concentric bowel-wall rings on transverse scan — distinct from the olive sign (palpable pyloric stenosis mass) and the double track/shoulder signs (barium findings in pyloric stenosis).",
  source: 'Pediatrics endpoint part1.pdf p.1384'
},

{
  id: 'pedep-mf2-32',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'gastroenterology',
  stem: "Plain x-ray abdomen standing in case of jejunal atresia may show:",
  options: ["Cobra head sign","String sign","Air fluid levels","Shoulder sign"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> Jejunal atresia causes proximal bowel obstruction, so a plain X-ray in standing position shows multiple air–fluid levels. Signs like cobra head or string sign are associated with urinary tract/GI conditions (not jejunal atresia).\n\n---\n\n**Jejunal atresia itself is not covered in the cached course material** — searched \"atresia\", \"jejunal\" and \"apple peel\" across the peds lecture set with no relevant hits beyond a passing mention of esophageal atresia and diaphragmatic hernia as risk factors for reflux in `22)Vomiting.txt` — not taken from the course material; the reasoning below is standard neonatal surgical knowledge. Jejunal atresia is a complete or near-complete luminal discontinuity of the jejunum, thought to arise from a late intrauterine vascular accident (a mesenteric vessel occlusion) rather than a failure of recanalisation. Because it is a mechanical obstruction sitting distal to the stomach and duodenum, swallowed air and fluid accumulate proximal to the atretic point; on an erect (standing) film, gas rises and fluid settles by gravity within each dilated, obstructed loop, producing the classic multiple **air–fluid levels** — the more distal the atresia, the more loops (and levels) are seen proximal to it, in contrast with the two-bubble picture of a more proximal duodenal atresia.\n\n**Why each distractor fails.** The *cobra head sign* describes the smooth, tapered filling defect of a ureterocele on an intravenous urogram or cystogram — a urinary tract finding with no relationship to bowel gas at all. The *string sign* classically describes the thread-like column of barium passed through a markedly narrowed, elongated pyloric channel in hypertrophic pyloric stenosis (or, in a different context, a narrowed terminal ileal segment in Crohn's disease) — a contrast-study finding of luminal narrowing, not the obstructive dilation-plus-levels picture of an atresia. The *shoulder sign* likewise belongs to pyloric stenosis, describing the bulge of hypertrophied pyloric muscle indenting the gastric antrum on a contrast study — again a different disease and a different (contrast, not plain-film) study.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Jejunal atresia is a mechanical small-bowel obstruction that produces multiple air–fluid levels on an erect plain film, distinct from the cobra head sign (ureterocele) and the string/shoulder signs (both hypertrophic pyloric stenosis contrast-study findings).",
  source: 'Pediatrics endpoint part1.pdf p.1386'
},

{
  id: 'pedep-mf2-33',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'emergencies',
  stem: "Patients with congenital diaphragmatic hernia should have:",
  options: ["Immediate postnatal surgical repair","Immediate face mask ventilation","Immediate intubation","Immediate ECMO"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> Face mask ventilation should be avoided because it worsens gastric distension and lung compression. Intubation and gentle ventilation are the correct initial steps before surgical repair.\n\n---\n\n`9) Respiratory distress in newborn.txt` gives congenital diaphragmatic hernia (CDH) its classic triad — severe, immediate respiratory distress, a scaphoid (sunken) abdomen, and heart sounds shifted to the right — reflecting herniated bowel filling the affected (usually left) hemithorax and compressing the lung and mediastinum. *The specific reason bag-mask ventilation is avoided in CDH is not spelled out in this lecture, which gives the diagnostic triad but not the airway-management rationale — not taken from the course material; the mechanism is standard neonatal resuscitation teaching.* Positive-pressure delivered by face mask pushes air down the oesophagus into the stomach and bowel as well as into the lungs, and in CDH that herniated bowel is already occupying space in the chest — distending it further with swallowed air compresses the already hypoplastic lung(s) even more and can precipitate a tension-physiology deterioration. Endotracheal intubation delivers positive pressure directly to the trachea and lungs, bypassing the oesophagus, which is why it is the immediate airway step, followed by a nasogastric tube on free drainage to decompress the herniated bowel.\n\n**Why each distractor fails.** *Immediate postnatal surgical repair* reverses the accepted sequence: CDH is a physiological emergency (pulmonary hypoplasia, labile pulmonary hypertension) rather than a surgical one, and operating on an infant whose gas exchange and haemodynamics are still unstable can itself provoke a pulmonary hypertensive crisis — repair is delayed until the infant is stabilised on minimal ventilator support, not performed immediately. *Immediate face mask ventilation* is precisely the manoeuvre this question is testing as dangerous, for the reasons above. *Immediate ECMO* is a real rescue therapy for the most severe, refractory cases of pulmonary hypertension and hypoxaemia in CDH, but it is an escalation reserved for infants failing maximal conventional support, not the first airway step for every newborn with the diagnosis.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "In congenital diaphragmatic hernia, the airway is secured by immediate endotracheal intubation rather than face-mask ventilation, because mask breaths distend the herniated bowel and worsen lung compression; surgical repair and ECMO are later, not first, steps.",
  source: 'Pediatrics endpoint part1.pdf p.1388'
},

{
  id: 'pedep-mf2-34',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'gastroenterology',
  stem: "Which of the following describes type IIIb intestinal atresia?",
  options: ["Two blind-ending atretic ends connected by a fibrous cord","Intraluminal diaphragm","Apple peel appearance","Multiple atresia"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> Type IIIb jejunal atresia is characterized by a proximal jejunal atresia with the distal small bowel spiraling around a marginal artery called “apple peel” deformity.\n\n---\n\n**The intestinal atresia classification is not covered in the cached course material** — searched \"atresia\", \"apple peel\" and \"Type III\" with no relevant hits beyond a passing mention of esophageal atresia in `22)Vomiting.txt` — not taken from the course material; the grading system below is standard paediatric surgical knowledge. Small-bowel atresias are graded (Grosser/Louw–Barnard) by how the bowel ends and its mesentery are affected: type I is an intraluminal membrane or diaphragm with the bowel wall and mesentery otherwise intact and in continuity; type II is two blind-ending atretic segments joined by a solid fibrous cord, with the mesentery intact; type IIIa is two blind ends completely separated by a V-shaped mesenteric gap; type IIIb — this question — is the most severe subtype short of multiple atresia: the proximal jejunum ends blindly just past the ligament of Treitz, most of the superior mesenteric artery's distal distribution is absent, and the remaining distal small bowel receives its blood supply from a single retrograde marginal vessel around which it spirals, giving the “apple peel” (or “Christmas tree”) appearance the box names; and type IV is multiple atresias in series, described as a “string of sausages.”\n\n**Why each distractor fails.** *Two blind-ending atretic ends connected by a fibrous cord* describes type II, not type IIIb — the defining feature there is the solid cord joining the two ends, with the mesentery still intact, not a bowel spiralling around a single vessel. *Intraluminal diaphragm* describes type I, the mildest form, where the bowel remains grossly continuous and only a membrane obstructs the lumen. *Multiple atresia* describes type IV, a distinct and separate grade from IIIb, involving several atretic segments rather than one severe single-point atresia with the apple-peel mesenteric pattern.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Type IIIb intestinal atresia is the apple-peel deformity: a proximal jejunal atresia with loss of the distal superior mesenteric artery distribution and the remaining bowel spiralling around one retrograde marginal vessel — distinct from type I (intraluminal diaphragm), type II (fibrous cord between blind ends) and type IV (multiple atresias).",
  source: 'Pediatrics endpoint part1.pdf p.1390'
},

{
  id: 'pedep-mf2-35',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'neonatal',
  stem: "The optimal time for surgery in undescended testes is:",
  options: ["Before 1 month","Between 6–12 months","In adulthood","After 5 years"],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> Orchidopexy is recommended between 6–12 months to reduce risk of infertility and malignancy. Surgery before 6 months is not advised as spontaneous descent may still occur.\n\n---\n\n**Cryptorchidism and orchidopexy are not covered in the cached course material** — searched \"undescended\", \"cryptorchid\" and \"orchidopexy\" with zero hits across the peds lecture set — not taken from the course material; the timing rationale below is standard paediatric surgical knowledge. Most testes that are undescended at birth complete their descent spontaneously within the first months of life, which is exactly why surgery is not offered immediately — operating before 6 months would needlessly treat testes that were still going to descend on their own. Waiting past roughly the first year, on the other hand, allows the testis to remain in an abnormally warm, extra-scrotal environment for longer, and cryptorchidism left uncorrected carries a raised long-term risk of impaired spermatogenesis (infertility) and testicular malignancy, risks that correlate with how long the testis stays undescended. Orchidopexy performed in the 6–12-month window is the compromise that gives spontaneous descent its full chance to happen first while still correcting the defect early enough to protect fertility and reduce malignancy risk.\n\n**Why each distractor fails.** *Before 1 month* is too early — a meaningful proportion of testes still undescended at birth will descend on their own within the first months, so operating this soon subjects infants to unnecessary surgery. *In adulthood* and *after 5 years* both leave the testis undescended for years beyond the window associated with preserved fertility and lower malignancy risk, well past the point the recommended timing is designed to avoid.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Orchidopexy for an undescended testis is timed to 6–12 months of age — late enough to let spontaneous descent occur, early enough to limit the long-term risks of infertility and testicular malignancy from a prolonged undescended position.",
  source: 'Pediatrics endpoint part1.pdf p.1392'
},

{
  id: 'pedep-mf2-36',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'neonatal',
  stem: "A male infant born at 29 weeks is now 4 hours old. He has developed an increased oxygen requirement, there is tachypnoea and severe intercostal and subcostal recessions. CXR demonstrates a ground-glass appearance. The most likely diagnosis is which of the following?",
  options: ["Transient tachypnoea of the newborn","Respiratory distress syndrome","Congenital pneumonia","Pneumothorax","Congenital heart disease"],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> Preterm infants have surfactant deficiency, leading to atelectasis and a “ground-glass” CXR appearance with air bronchograms. TTN occurs in term infants and resolves quickly.\n\n---\n\n`9) Respiratory distress in newborn.txt` gives respiratory distress syndrome (RDS, hyaline membrane disease) as the result of pulmonary immaturity and surfactant deficiency, producing poor pulmonary compliance, atelectasis, decreased gas exchange and hypoxia, with manifestations appearing immediately or shortly after birth — this infant is 4 hours old. The same lecture gives the film exactly as the box describes it: small lung volume with a fine reticulogranular ground-glass mottling in both lung fields, through which an air bronchogram is seen. At 29 weeks this infant sits well within the preterm range where surfactant production is still immature, and severe intercostal and subcostal recession together with rising oxygen need over the first hours is the classic RDS course of rapidly aggravating distress.\n\n**Why each distractor fails.** *Transient tachypnoea of the newborn* is, by the same lecture, \"the most common cause of neonatal RD\" but is a term/late-preterm disease of delayed lung-fluid clearance rather than surfactant deficiency, with a mild, regressive course resolving within about 3 days — it does not fit a 29-week infant with a ground-glass film and worsening oxygen need. *Congenital pneumonia* (`7) Intro to neonatology.txt`) is described as \"often indistinguishable from HMD\" on clinical grounds, but arises from aspiration of infected amniotic fluid and would be expected to bring maternal risk factors or septicaemia signs, none of which are given here — the vignette instead points straight at prematurity as the driver. *Pneumothorax* causes sudden deterioration with asymmetric, unilateral signs (decreased breath sounds and chest movement on the affected side), not the bilateral, symmetric ground-glass pattern described. *Congenital heart disease* would be expected to declare itself with a murmur, cyanosis unresponsive to oxygen, or signs of heart failure rather than a surfactant-deficiency pattern on the chest film, and prematurity itself is not the driving risk factor for structural heart disease.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "A markedly preterm infant with respiratory distress in the first hours of life and a ground-glass, air-bronchogram chest film has respiratory distress syndrome from surfactant deficiency, distinguished from TTN (term/late-preterm, mild, self-resolving), congenital pneumonia (maternal/septic risk factors), pneumothorax (asymmetric, sudden) and congenital heart disease (murmur/cyanosis-driven).",
  source: 'Pediatrics endpoint part1.pdf p.1394'
},

{
  id: 'pedep-mf2-37',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'neonatal',
  stem: "A female infant born at 28 weeks is now 10 days old. She had been doing very well and breast milk was started 2 days ago via nasogastric tube. She has become increasingly unwell over the past 12 hours with abdominal distension, temperature instability and bile-stained aspirates from the NG tube. Some blood is noted in the stools. Abdominal XR shows air within the bowel walls. What is the most likely diagnosis?",
  options: ["Sepsis","Intestinal obstruction","Necrotizing enterocolitis","Malrotation","Duodenal atresia"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> NEC presents with abdominal distension, bile-stained aspirates, bloody stools, and X-ray showing air in the bowel wall (pneumatosis intestinalis). This is a neonatal emergency.\n\n---\n\n`7) Intro to neonatology.txt` names necrotising enterocolitis (NEC) the most common serious GI problem of the preterm infant, with an incidence that rises the more immature the infant is — at 28 weeks this baby sits well within the high-risk band — and gives its pathognomonic radiological finding as pneumatosis intestinalis, air tracking within the bowel wall itself, produced by gas-forming bacteria invading an ischaemic, mucosally damaged segment of gut. Enteral feeding started two days before the deterioration is the recognised trigger: introducing feed to a still-immature preterm gut is when the ischaemia/mucosal-insult/infection triad the lecture lists as NEC's uncertain aetiology comes together. The clinical picture given — abdominal distension, bile-stained NG aspirates (feed intolerance beyond the stomach), blood in the stools (mucosal breakdown) and temperature instability (systemic inflammatory response) — is, together with the film, the textbook presentation.\n\n**Why each distractor fails.** *Sepsis* shares many of the same non-specific signs (temperature instability, feed intolerance) and often coexists with NEC, but sepsis alone does not put air inside the bowel wall — the pneumatosis is what confirms NEC over a purely septic picture. *Intestinal obstruction* and *malrotation* can both cause distension and bilious aspirates from a mechanical block, but neither produces pneumatosis intestinalis or bloody stools as a primary feature, and malrotation with volvulus is typically a sudden, catastrophic event rather than a gradual 12-hour deterioration after feeds have already been tolerated for two days. *Duodenal atresia* is a congenital, proximal obstruction that declares itself with bilious vomiting from the first day or two of life — this infant had been doing well and only deteriorated after feeds were established on day 8, which does not fit a lesion that should have prevented feeding from succeeding at all.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "A preterm infant who deteriorates within days of starting enteral feeds, with abdominal distension, bile-stained aspirates, bloody stools, temperature instability and pneumatosis intestinalis on X-ray, has necrotising enterocolitis — the intramural air is what separates it from sepsis, mechanical obstruction/malrotation and duodenal atresia.",
  source: 'Pediatrics endpoint part1.pdf p.1396'
},

{
  id: 'pedep-mf2-41',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'emergencies',
  stem: "How would you manage a choking child with mild airway obstruction?",
  options: ["Start early CPR","Give 5 abdominal thrusts","Do 5 back blows","Give 5 chest thrusts","Encourage cough"],
  answer: 4,
  explanation: "**The endpoint file prints this explanation:**\n\n> If the child has mild obstruction and can cough effectively, the best management is to encourage coughing. Back blows or thrusts are for severe obstruction.\n\n---\n\n**The specific choking (foreign-body airway obstruction) algorithm is not covered in the cached course material** — searched \"choking\", \"back blow\", \"abdominal thrust\" and \"foreign body\" across the peds lecture set with no relevant hits; `3) Pediatric resuscitation.txt` teaches the general ABCDE approach (\"Look, listen, and feel for: airway obstruction or respiratory distress\") but not a dedicated choking protocol — not taken from the course material; the algorithm below is standard paediatric basic life support teaching. Airway obstruction from an inhaled foreign body is graded by whether the child's own cough is still effective: an effective cough means the child is conscious, able to vocalise or cry, and able to breathe between coughs — a **mild** obstruction — and in that state the airway is not yet critically compromised, so a forceful, physiological cough clears an object more effectively and more safely than any manual manoeuvre. The child is only encouraged to keep coughing and closely observed, ready to escalate immediately if the cough becomes ineffective or the child stops breathing.\n\n**Why each distractor fails.** *Starting early CPR* is reserved for a child who is unresponsive and not breathing — well beyond mild obstruction, where the child is still coughing and moving air. *5 abdominal thrusts* and *5 chest thrusts* (the latter used in infants, in whom abdominal thrusts risk intra-abdominal injury) are both interventions for **severe** obstruction — an ineffective, silent cough, cyanosis, or an inability to vocalise — not for a child whose cough is still doing its job. *5 back blows* is likewise the first-line manoeuvre for severe, not mild, obstruction, alternated with thrusts if the back blows fail to dislodge the object.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "In mild airway obstruction (child conscious, coughing effectively), encourage continued coughing and observe closely — back blows and chest/abdominal thrusts, and eventually CPR, are escalation steps for severe obstruction or arrest, not first-line management of an effective cough.",
  source: 'Pediatrics endpoint part1.pdf p.1404'
},

{
  id: 'pedep-mf2-44',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'infection-vaccine',
  stem: "At what age is the first Measles/Mumps/Rubella (MMR) vaccine given in Egypt?",
  options: ["6 months","9 months","12 months","18 months","24 months"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> The first MMR dose is given at 12 months, followed by a booster at school age.\n\n---\n\n**The Egyptian national vaccination schedule is not covered in the cached course material** — no cached lecture is dedicated to it, and a search for \"vaccine\", \"vaccination\" and \"schedule\" across the peds lecture set returns no dedicated schedule document — not taken from the course material; the timing and its rationale below are standard national-programme and immunology knowledge. In Egypt's compulsory immunisation schedule, MMR is first given at 12 months and boosted again in early childhood (commonly cited as 18 months, and again at school entry). MMR is a live attenuated vaccine, and the 12-month timing is deliberate rather than arbitrary: most infants still carry circulating maternally transferred antibody against measles through much of the first year, and that antibody would neutralise the live measles component of the vaccine before the infant's own immune system had a chance to respond and generate its own protective memory, effectively wasting an earlier dose.\n\n**Why each distractor fails.** *6 months* and *9 months* both fall inside the window where residual maternal antibody is still expected to blunt the vaccine's effect, which is why neither age carries an MMR dose on the schedule. *18 months* is a real timepoint on the Egyptian schedule, but it is the **booster**, not the first dose — the primary dose has already been given by then. *24 months* is later still than either the first dose or its usual booster and does not correspond to a scheduled MMR timepoint.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "The first MMR dose in Egypt's schedule is given at 12 months, timed to let maternally transferred antibody wane so the live measles component can generate the infant's own immune response; earlier ages risk antibody interference, and 18/24 months are booster or later timepoints, not the first dose.",
  source: 'Pediatrics endpoint part1.pdf p.1410'
},

{
  id: 'pedep-mf2-45',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'infection-immunity',
  stem: "Which of the following is an example of passive immunity?",
  options: ["Palivizumab (monoclonal antibody to RSV)","Diphtheria-Tetanus toxoid","MMR","Influenza vaccine","Hepatitis B vaccine given at birth"],
  answer: 0,
  explanation: "**The endpoint file prints this explanation:**\n\n> Passive immunity is provided by pre-formed antibodies, such as palivizumab. Vaccines like MMR or DTaP induce active immunity.\n\n---\n\n`32)Acute bronchiloitis_.txt` names palivizumab as a humanised monoclonal anti-RSV antibody licensed for preventing severe disease from RSV infection, given as prophylaxis to high-risk infants. **The lecture does not itself use the term \"passive immunity,\"** but the mechanism it describes is exactly that: palivizumab supplies a ready-made, pre-formed antibody directly to the infant rather than presenting an antigen the infant's own immune system must respond to and remember — *the \"passive immunity\" label and its contrast with active vaccination is not taken from the course material beyond the drug's described mechanism.* Because no antigen exposure or immune memory is generated, protection lasts only as long as the administered antibody persists, which is why palivizumab is given as repeated monthly doses through the RSV season rather than as a one-off, memory-building immunisation.\n\n**Why each distractor fails.** *Diphtheria–Tetanus toxoid*, *MMR*, and *Hepatitis B vaccine given at birth* are all active immunisations: each presents an antigen (an inactivated toxoid, a live attenuated virus, or a viral surface antigen respectively) to the recipient's own immune system, which then mounts its own antibody response and lays down immunological memory capable of a faster, stronger reaction on future exposure. *Influenza vaccine* works the same way, using inactivated or subunit viral antigen to prompt the recipient's own immune response. That active generation of memory — present in all four of these — is precisely what distinguishes a vaccine from passive immunity, and it is why none of them provides the ready-made, memory-free protection palivizumab does.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Palivizumab is passive immunity — a pre-formed monoclonal antibody against RSV giving temporary, memory-free protection — contrasted with DTaP, MMR, influenza vaccine and hepatitis B vaccine, which are all active immunisations that provoke the recipient's own antibody response and immunological memory.",
  source: 'Pediatrics endpoint part1.pdf p.1412'
},

{
  id: 'pedep-mf2-46',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'nutrition-feed',
  stem: "What is the most effective intervention tested to prevent allergic diseases in infants and children?",
  options: ["Adding probiotics and prebiotics to infants' feeds","Adding omega-3 fatty acids to infants' diet","The use of skin moisturizers as early as possible","Feeding common food allergens to young infants","Avoidance of allergenic foods during the first year of life"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Early introduction of allergenic foods (like peanuts/eggs) has been shown to reduce the risk of allergy. Avoidance actually increases allergy risk.\n\n---\n\n`26)allergy_.txt` names this intervention directly as **oral tolerance induction**: \"the induction of 'immune tolerance' by feeding common food allergens such as eggs, cow's milk and peanut to young infants to reduce the risk of allergy,\" now \"often suggested in infant feeding guidelines for countries where food allergy is common.\" The same slide gives the mechanism behind why this specific intervention works: immunological tolerance to a food depends on early exposure through the gastrointestinal tract, while allergic sensitisation instead develops through exposure to allergens via an **impaired skin barrier** — so keeping a food out of the diet does not remove exposure to it, it simply shifts exposure to the route (skin) that provokes allergy rather than tolerance. This is why deliberately feeding, rather than avoiding, common allergenic foods in infancy is the intervention the material names as reducing allergic risk.\n\n**Why each distractor fails.** *Adding probiotics and prebiotics* and *adding omega-3 fatty acids* have both been studied as possible allergy-prevention strategies, but the trial evidence for either is inconsistent and neither is established as an effective, guideline-level intervention *(not taken from the course material, which does not cover either as an allergy-prevention measure)*. *Skin moisturizers used as early as possible* targets the skin-barrier route the lecture names as the sensitisation pathway, and it was a genuinely tested hypothesis, but large randomised trials of early, routine emollient use have not shown it reduces the risk of food allergy or eczema, and it is not the intervention this material credits *(not taken from the course material)*. *Avoidance of allergenic foods during the first year of life* is the reverse of the printed key: the lecture's own point is that this older advice raises rather than lowers allergy risk, because avoidance removes the gut-tolerance route while leaving skin exposure unaddressed.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Feeding common allergenic foods (egg, cow's milk, peanut) to young infants — oral tolerance induction — is the intervention shown to reduce allergic disease risk, because tolerance depends on early gut exposure while sensitisation develops through the skin; avoidance, probiotics/prebiotics, omega-3 and early moisturizer use are not established as effective in the same way.",
  source: 'Pediatrics endpoint part1.pdf p.1414'
},
