{
  id:'pedep-gi-1', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'Benjamin is a 6-year-old boy who is seen in the Paediatric Emergency Department. He has been vomiting and has had diarrhea for 3 days. His stool is watery and foul-smelling but contains no blood. He has never left the UK. Examination reveals mild dehydration but is otherwise normal. What is the most likely organism that has caused his symptoms?',
  options:['Campylobacter','Escherichia coli','Giardia lamblia','Rotavirus','Shigella'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Rotavirus is a common cause of acute viral gastroenteritis in young children, especially under 5. It presents with vomiting, foul-smelling watery diarrhea, and often occurs without blood or recent travel.\n\n---\n\n**Sorting the five organisms on this list.** `23).1) Acute diarrhea.txt` splits the causes of acute gastroenteritis by relative frequency: viruses (~70%) — Rotavirus, Norovirus, adenovirus and others — bacteria (10–20%) — Campylobacter jejuni, non-typhoid Salmonella, enteropathogenic E. coli, Shigella, Yersinia, Shiga-toxin-producing E. coli, Salmonella typhi/paratyphi, Vibrio cholerae — and protozoa (<10%) — Cryptosporidium, Giardia lamblia, Entamoeba histolytica. Of these, the deck names Rotavirus, enterotoxigenic E. coli, Shigella, Campylobacter jejuni and Cryptosporidium as the most important causes of acute infective diarrhoea.\n\n**Why the pattern here points to a virus, and specifically Rotavirus.** The deck describes two mechanisms behind acute watery diarrhoea — secretory (toxin-driven) and osmotic (villous damage) — both of which produce loose, watery stool rather than the bloody, mucoid stool of invasive bacterial or amoebic dysentery. Benjamin\'s stool is watery and foul-smelling with **no blood**, he has **no travel history**, and he is under 5 — exactly the age band and stool character the deck attaches to viral gastroenteritis, of which Rotavirus is the single largest contributor.\n\n**Why each distractor fails.** *Campylobacter* and *Shigella* are bacterial causes that classically produce dysentery — blood and mucus in the stool, sometimes with tenesmus — not this watery, non-bloody picture. *Escherichia coli*, in its more invasive or Shiga-toxin-producing forms, is likewise associated with bloody stool and carries a risk of haemolytic uraemic syndrome, again not matching this presentation. *Giardia lamblia* is a protozoal cause typically linked to contaminated water exposure and produces a more prolonged, often greasy, malabsorptive-type diarrhoea rather than a 3-day acute illness with no travel history.\n\n**This vignette is printed twice in this bank.** The identical scenario, option list and key reappear later as `pedep-gi-62`, with the child\'s age changed from 6 to 2 years; the reasoning above applies unchanged to that printing.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Watery, foul-smelling, non-bloody diarrhoea with vomiting and no travel history in a young child is most likely viral gastroenteritis — Rotavirus is the single most common cause.',
  source:'Pediatrics endpoint part1.pdf p.414'
},

{
  id:'pedep-gi-2', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'Rodney, a boisterous 2-year-old, has had diarrhea for the last 3 months. He produces up to four stools a day, which are loose, brown in color, and usually contain undigested food. The rest of the family is well. He has never been abroad. Examination is normal, and his personal child health record shows that he is growing along the 50th centile.\nWhat is the most likely diagnosis?',
  options:['Chronic non-specific diarrhea','Coeliac disease',"Cow's milk protein allergy",'Inflammatory bowel disease','Lactose intolerance'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> This condition, also called toddler\'s diarrhea, presents with chronic loose stools containing undigested food but normal growth and development. It is common in well children aged 1-5 years.\n\n---\n\n**The name, and the one fact that carries the whole question.** *(Toddler\'s diarrhoea is not named in the cached lectures — not taken from the course material.)* The single finding that does the diagnostic work here is on the growth chart, not the stool chart: Rodney is **growing steadily along the 50th centile** despite three months of loose stools. `23).1) Acute diarrhea.txt` defines diarrhoea itself simply as an increase in the fluidity, volume or number of stools relative to a child\'s usual habit, and lists loose stools containing undigested food as a benign, self-limited pattern once a malabsorptive or inflammatory cause is excluded — which normal growth does here.\n\n**Why each distractor fails.** *Coeliac disease* causes malabsorption severe enough to blunt growth, and typically comes with additional features such as anaemia or abdominal distension — contrast `pedep-gi-21`, where the same-shaped stem is paired with 4 kg of weight loss and microcytic anaemia and the key becomes coeliac disease instead. *Cow\'s milk protein allergy* usually presents with additional features such as eczema, blood-streaked stool, or faltering growth, and is most often triggered by a change in feed. *Inflammatory bowel disease* is a chronic autoimmune process that would be expected to impair growth and often brings blood in the stool, abdominal pain or systemic symptoms — none of which are present. *Lactose intolerance* would be expected to track with dairy intake and often causes bloating and flatulence from fermentation, which is not described here.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Chronic loose stools with undigested food in a well toddler who is growing normally is chronic non-specific (toddler\'s) diarrhoea — a diagnosis that rests on normal growth, not on the stool itself.',
  source:'Pediatrics endpoint part1.pdf p.416'
},

{
  id:'pedep-gi-3', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'Ellie is a 4-year-old girl who has been complaining of tummy pain for a month. It is worse when she goes to the toilet; her stools are firm, and she opens her bowels only every 2-3 days. She has not had any vomiting. For the last 2 weeks, her stools have become loose. On examination, she has a mass in the left iliac fossa. What is the most likely diagnosis?',
  options:['Appendix mass','Constipation','Gastroenteritis','Intussusception',"Hirschsprung's disease"],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Chronic constipation can lead to overflow diarrhea and a palpable fecal mass in the left iliac fossa. Pain with defecation and hard stools suggest functional constipation.\n\n---\n\n**Why constipation is right.** `23).2)Constipation.txt` defines constipation as delay or difficulty in defecation present for **2 or more weeks** and sufficient to cause distress — Ellie\'s month-long history of pain, firm stools and infrequent defecation every 2–3 days fits directly. The deck also names a palpable **fecal mass on the left lower quadrant (loaded sigmoid colon)** as an examination finding, matching Ellie\'s left iliac fossa mass exactly. Her recent switch to loose stool is the classic overflow pattern the box describes: liquid stool leaking around an impacted, hard faecal mass.\n\n**Why each distractor fails.** *Appendix mass* would be expected to sit in the right, not left, iliac fossa, and typically follows an acute febrile illness rather than a month of painful, infrequent defecation. *Gastroenteritis* is an acute illness lasting days, not the chronic month-long course described here. *Intussusception* presents acutely with episodic colicky pain, vomiting and a right-sided mass, often with red-currant-jelly stool, not a gradually evolving month-long constipation history. *Hirschsprung\'s disease* causes constipation from birth with delayed passage of meconium; Ellie\'s history began only a month ago in what reads as a previously normal child, which argues against a congenital aganglionic cause.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A left iliac fossa fecal mass with a history of painful, infrequent hard stools and new overflow-type looseness is constipation, not an acute surgical abdomen.',
  source:'Pediatrics endpoint part1.pdf p.418'
},

{
  id:'pedep-gi-4', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'Alysha is a 2-month-old baby who is seen in the paediatric outpatient department. She was born at term, weighing 3.5 kg, and is breastfed. Her mother is concerned as she has vomited some of the milk after most feeds since birth. She cries when she vomits. She is continuing to grow along the 50th centile. What is the most likely diagnosis?',
  options:['Gastro-oesophageal reflux','Helicobacter pylori infection','Infant colic','Overfeeding','Pyloric stenosis'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Physiological reflux is common in infants due to immature lower esophageal sphincter tone. Vomiting without weight loss or systemic signs supports this diagnosis.\n\n---\n\n**Why reflux is right.** `22)Vomiting.txt` names gastro-oesophageal reflux as the **common cause of vomiting in infants**, driven by functional immaturity of the lower oesophageal sphincter, the predominantly fluid diet, a horizontal posture and a short intra-abdominal length of oesophagus. It adds that most infants with reflux are **putting on weight normally**, exactly as Alysha is doing along the 50th centile, and that reflux resolves spontaneously by around 12 months as the sphincter matures and the diet becomes more solid.\n\n**Why each distractor fails.** *Helicobacter pylori infection* is an uncommon cause of vomiting in this age group and would be expected to bring features of peptic disease rather than a simple, feed-related posset since birth. *Infant colic* is defined by excessive, otherwise-unexplained crying rather than vomiting as the primary complaint. *Overfeeding* is a genuine differential for regurgitation, but nothing in the stem quantifies excess feed volumes, and the lecture flags reflux — not overfeeding — as the default first diagnosis for this presentation. *Pyloric stenosis* presents at 2–8 weeks with **non-bilious vomiting that increases in frequency and forcefulness over time**, eventually becoming projectile, and typically brings weight loss if presentation is delayed; Alysha\'s vomiting has been stable "since birth" rather than progressively worsening, and her growth is normal, arguing against it.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Vomiting after most feeds since birth in a thriving, normally growing infant is physiological gastro-oesophageal reflux, not pyloric stenosis or overfeeding.',
  source:'Pediatrics endpoint part1.pdf p.420'
},

{
  id:'pedep-gi-5', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'Claire, a 7-year-old girl, has had abdominal pain for the last 6 months. On several occasions, it has been sufficiently severe for her to be sent home early from school. The pain happens once or twice a week in the afternoon or early evening. It is periumbilical in nature. It does not wake her at night. She has not had vomiting or diarrhoea. She is growing well. Her examination is normal. Her urine is clear on dipstick testing. What is the most likely cause for her pain?',
  options:['Functional abdominal pain','Gastritis','Hepatitis A','Irritable bowel syndrome','Meckel diverticulum'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Functional abdominal pain is common in school-aged children and is not associated with red flag features like weight loss or night waking. It often affects otherwise healthy, growing children.\n\n---\n\n**Why functional abdominal pain is right.** `24)Abdominal pain.txt` sets out an organic-versus-functional table: organic pain is **localised** and **may be nocturnal**, while functional pain is **vague and midline** and **never nocturnal**. Claire\'s pain is periumbilical (vague midline) and specifically does not wake her at night. The deck\'s alarm-signal list includes nocturnal symptoms, weight loss or growth retardation, and an abnormal urinalysis — Claire has none of these: she is growing well, her exam is normal and her urine dipstick is clear. Functional pain is formally a "diagnosis of exclusion", and here the exclusion is achieved by a careful history rather than by investigation.\n\n**Why each distractor fails.** *Gastritis* would be expected to bring epigastric rather than periumbilical pain, often with a relation to meals, and sometimes haematemesis — none described. *Hepatitis A* would be expected to bring jaundice, malaise or hepatomegaly, which a normal examination excludes. *Irritable bowel syndrome* is a functional disorder too, but by the deck\'s own definition it is characterised by crampy pain **linked to altered bowel habit** (diarrhoea or constipation around the pain) — Claire has had no diarrhoea, whereas the sibling vignette at `pedep-gi-26` describes exactly that bowel-habit link and keys IBS instead. *Meckel diverticulum* classically presents with painless rectal bleeding from ectopic gastric mucosa, not recurrent afternoon abdominal pain.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Chronic periumbilical pain, never nocturnal, in a well, normally growing child with a normal exam and urinalysis is functional abdominal pain — a diagnosis made by excluding alarm features on history, not by testing.',
  source:'Pediatrics endpoint part1.pdf p.422'
},

{
  id:'pedep-gi-6', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:"Ben, aged 9 months, has had a 3-day history of diarrhoea and vomiting. On examination, he is found to be quiet but alert, is tachypnoeic, has a tachycardia but normal pulses, a dry mouth, no mottling of the skin but reduced skin turgor and a sunken fontanelle. The capillary refill time is 2 seconds. His blood pressure is normal for his age. He continues to vomit even with an oral rehydration solution given via a nasogastric tube. Ben's plasma sodium is found to be 156 mmol/L (normal range: 135-145 mmol/L). He needs fluid as he has clinical dehydration. How would this fluid best be replaced?",
  options:['Immediate bolus of 20 ml/kg of 0.9% sodium chloride followed by reassessment and replacement of the remaining deficit over 24 hours with 0.9% sodium chloride solution','Rehydration over 6 hours followed by repeat urea and electrolyte measurement and maintenance fluid only for a further 18 hours','Rehydration over 24 hours with 0.18% sodium chloride/5% glucose solution','Rehydration over 24 hours with 0.9% sodium chloride/5% glucose solution','Rehydration over 48 hours with 0.9% or 0.45% saline'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Ben has hypernatremic dehydration, which requires slow and cautious rehydration over 48 hours to avoid the risk of cerebral oedema. Rapid correction with hypotonic fluids or quick boluses is dangerous due to the osmotic shifts involved in hypernatremia.\n\n---\n\n**Classifying Ben\'s dehydration.** `23).1) Acute diarrhea.txt` names hypertonic (hypernatraemic) dehydration as one of the three types alongside isotonic and hypotonic, and notes it is the **least common** pattern (10–15% of cases) but carries the most dangerous fluid physiology. Ben\'s plasma sodium of 156 mmol/L against a normal range of 135–145 confirms this is the hypernatraemic type, and clinically his signs are consistent with the deck\'s general assessment findings for dehydration — a dry mouth, sunken fontanelle and reduced skin turgor — on top of a 3-day diarrhoeal illness he cannot rehydrate orally.\n\n**Why slow, 48-hour correction is the safe answer.** *(The specific 48-hour timeframe and the cerebral-oedema mechanism are general paediatric fluid-therapy knowledge — not taken from the course material, which covers dehydration typing and standard rehydration volumes but not the hypernatraemic-specific protocol.)* In hypernatraemic dehydration, water has been lost disproportionately to sodium, so brain cells have adapted by generating intracellular osmoles to protect their volume against the high extracellular osmolality. If serum sodium is corrected too quickly, water shifts rapidly into these osmotically primed brain cells, causing cerebral oedema, seizures and can be fatal. Rehydrating slowly, over roughly 48 hours, with a fluid that does not itself lower serum osmolality too fast (isotonic 0.9% saline, or half-strength 0.45% saline used cautiously) avoids that swing.\n\n**Why each distractor fails.** *Immediate 20 ml/kg bolus then 24-hour replacement* — Ben is not in shock (normal blood pressure, capillary refill 2 seconds, normal pulses), so a resuscitation bolus is not indicated by the deck\'s own severity-based fluid plan, and the follow-on 24-hour correction is still too fast for hypernatraemia. *Rehydration over 6 hours* is drastically too rapid and would risk a dangerous, rapid fall in osmolality. *Rehydration over 24 hours with 0.18% saline/5% glucose* pairs too fast a timeframe with a markedly hypotonic fluid relative to Ben\'s hypernatraemic state — the combination most likely to precipitate cerebral oedema. *Rehydration over 24 hours with 0.9% saline/5% glucose* uses an appropriately isotonic fluid but still corrects twice as fast as the recommended 48 hours.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Hypernatraemic (hypertonic) dehydration must be corrected slowly, over about 48 hours, with an isotonic or near-isotonic fluid — rapid correction risks a fatal osmotic shift into brain cells (cerebral oedema).',
  source:'Pediatrics endpoint part1.pdf p.424, explanation box p.425'
},

{
  id:'pedep-gi-7', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'Matthew is a 3-day-old term infant who has not passed meconium since birth. On examination, his abdomen is distended, but the remainder of the examination is normal. An x-ray of the abdomen shows distended loops throughout the bowel, including the rectum. What is the most likely diagnosis?',
  options:['Congenital hypothyroidism','Cystic fibrosis','Duodenal atresia',"Hirschsprung's disease",'Rectal atresia'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Failure to pass meconium in the first 48 hours with abdominal distension suggests Hirschsprung\'s disease. The rectum may still appear full on imaging due to functional obstruction.\n\n---\n\n**Why Hirschsprung\'s disease fits.** *(Hirschsprung\'s disease itself is not covered in the cached lecture set beyond a passing mention as a feature of Down syndrome — the pathophysiology and diagnostic reasoning below are general paediatric surgical knowledge, not taken from the course material.)* Hirschsprung\'s disease is caused by the congenital absence of ganglion cells in a segment of distal bowel, usually beginning at the rectum and extending proximally for a variable distance. The aganglionic segment cannot relax, so it acts as a functional obstruction: stool backs up proximal to it, meconium is passed late or not at all, and the abdomen distends. Failure to pass meconium within the first 24–48 hours of life is the classic trigger for suspecting it, and Matthew is 3 days old with no meconium and a distended abdomen. The x-ray finding of distension **throughout the bowel, including the rectum**, matches the box\'s point that the rectum can still look "full" on imaging even though it is functionally obstructed, because the bowel above the narrowed segment dilates with retained stool and gas.\n\n**Why each distractor fails.** *Congenital hypothyroidism* can cause constipation as one feature among many (macroglossia, hypotonia, prolonged jaundice, lethargy), but it does not produce an acute picture of distended bowel loops on imaging in the first days of life, and Matthew\'s exam is otherwise normal. *Cystic fibrosis* can present as meconium ileus, but that classically obstructs more proximally in the small bowel and often shows a "soap-bubble" appearance on x-ray rather than distension extending all the way through to the rectum. *Duodenal atresia* obstructs high in the gut and classically produces bilious vomiting from day one with a "double bubble" on x-ray — gas in the stomach and duodenum only, not distension of the whole bowel including the rectum. *Rectal atresia* would be suspected on finding an abnormal or absent anal opening on examination, which is not described here.\n\n**A near-identical vignette reprints later in this section**, at `pedep-gi-19` (a 2-month-old with the same delayed-meconium/distension picture) and `pedep-gi-23` (the same story, now asked as which test confirms the diagnosis) — the reasoning above carries across all three.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Delayed passage of meconium beyond 24–48 hours with a distended abdomen and distended bowel loops (including the rectum) on x-ray is Hirschsprung\'s disease until proved otherwise.',
  source:'Pediatrics endpoint part1.pdf p.427'
},

{
  id:'pedep-gi-8', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'James, an 8-month-old infant, is brought to the Emergency Department by his parents. He is having episodes of abdominal pain and is just recovering from an upper respiratory tract infection. He seems well in between, but then suddenly seems to be in pain and looks pale. He has vomited several times. On questioning, he has had no blood in his stool but has not opened his bowels for 24 hours. Which of the following is the most likely cause of vomiting in this patient?',
  options:['Intussusception','Diabetic ketoacidosis','Appendicitis',"Coeliac disease",'Pyloric stenosis'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Sudden episodic abdominal pain with pallor and vomiting in infants suggests intussusception, often post-viral. Early features may occur before the passage of red currant jelly stool.\n\n---\n\n**This option list cycles through three vignettes in this bank** (`pedep-gi-8`, `pedep-gi-9`, `pedep-gi-10`), each picking a different one of the five causes of vomiting. Written once here, so the siblings only need to argue their own case:\n\n| Diagnosis | Signature | Grounded in |\n|---|---|---|\n| **Intussusception** (this entry) | Well infant with **sudden episodic pain, pallor, vomiting**, often post-viral, peak 3 months–2 years | `24)Abdominal pain.txt` |\n| **Diabetic ketoacidosis** (`pedep-gi-9`) | Vomiting + **deep/rapid (Kussmaul) breathing** + dehydration + weight loss, no diarrhoea | `51) DKA.txt` |\n| **Appendicitis** | Fever + progressive, localising pain + tenderness/rigidity (older child); irritability and feed refusal (infant) | `24)Abdominal pain.txt` |\n| **Coeliac disease** | Chronic, not acute — diarrhoea, weight loss/growth faltering over months *(general medical knowledge; not the acute-vomiting pattern this ladder is testing)* | — |\n| **Pyloric stenosis** (`pedep-gi-10`) | **2–8 weeks old**, forceful/projectile **non-bilious** vomiting, hungry straight after | `22)Vomiting.txt` |\n\n**Why James is intussusception specifically.** `24)Abdominal pain.txt` describes intussusception as the invagination of proximal bowel into a distal segment — most commonly ileum into caecum through the ileocaecal valve — and names it the **most common cause of intestinal obstruction in infants after the neonatal period**, with a peak age of **3 months to 2 years**. James is 8 months old, just recovering from a viral URTI (a recognised trigger, as enlarged Peyer\'s patches from the infection can act as a lead point), and has the classic pattern of being **well in between episodes** and then suddenly painful and pale — the box\'s "episodic" pattern. Not opening his bowels for 24 hours fits early bowel obstruction, appearing here before any red-currant-jelly stool, which the box notes may not yet have appeared.\n\n**Why the other four fail in James\'s case.** No Kussmaul breathing, dehydration or weight loss is described (against DKA). There is no fever and no localising right iliac fossa tenderness or rigidity described (against appendicitis, and James is also younger than the typical age). Coeliac disease is a chronic malabsorptive process, not an acute episodic pain-and-vomiting illness. Pyloric stenosis presents at 2–8 weeks with forceful, non-bilious vomiting worsening over time, not episodic pain in an 8-month-old.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A previously well infant aged 3 months to 2 years with sudden episodic abdominal pain, pallor and vomiting, often after a viral illness, has intussusception until proved otherwise.',
  source:'Pediatrics endpoint part1.pdf p.429'
},

{
  id:'pedep-gi-9', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'Bridgitta, an 8-year-old girl, presents to her family doctor with vomiting and abdominal pain. Her vomiting only started today and she has no diarrhoea or fever. She looks unwell and has clinical dehydration on examination and has deep, rapid breathing. She is thirsty and pale. She has lost weight over the last few weeks. Which of the following is the most likely cause of the vomiting in this patient?',
  options:['Intussusception','Diabetic ketoacidosis','Appendicitis','Coeliac disease','Pyloric stenosis'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Vomiting with Kussmaul respiration, dehydration, and weight loss in a child points to new-onset type 1 diabetes with DKA. The absence of diarrhea supports a metabolic cause.\n\n---\n\nThis question shares its five-option list with `pedep-gi-8` and `pedep-gi-10` — the full comparison table is written there. Bridgitta\'s own discriminating token is the combination `51) DKA.txt` calls the **clinical signs of DKA**: nausea and vomiting, abdominal pain, and **tachypnoea** — here specifically "deep, rapid breathing", the Kussmaul pattern that compensates for metabolic acidosis. Add to that clinical dehydration, thirst and pallor (osmotic diuresis from hyperglycaemia), and weeks of weight loss (the classic build-up to a first presentation of type 1 diabetes), and the picture fits the deck\'s classical triad of DKA — hyperglycaemia, metabolic acidosis and ketonaemia/ketonuria — even though the actual blood results are not given in the stem. The **absence of diarrhoea or fever** is what the box leans on to exclude the infective, surgical and post-viral causes on the same list, since a metabolic cause does not need either.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Vomiting with Kussmaul (deep, rapid) breathing, dehydration and weeks of preceding weight loss in a child is new-onset diabetic ketoacidosis, even before any blood result is known.',
  source:'Pediatrics endpoint part1.pdf p.431'
},

{
  id:'pedep-gi-10', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'Noah is 5 weeks old and has been breastfeeding well and putting on weight. However, over the last 36 hours, he has been vomiting after almost every feed. The vomit goes everywhere, and he then wants to feed again. All the vomits are milky. He was born at term (birth weight 3.8 kg). Which of the following is the most likely cause of the vomiting in this patient?',
  options:['Intussusception','Diabetic ketoacidosis','Appendicitis','Coeliac disease','Pyloric stenosis'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Pyloric stenosis presents in young infants with non-bilious, forceful vomiting and hunger after vomiting. It typically appears between 2-8 weeks of age.\n\n---\n\nThis question shares its five-option list with `pedep-gi-8` and `pedep-gi-9` — the full comparison table is written there. Noah\'s own discriminating token is his age and the character of the vomit: `22)Vomiting.txt` places pyloric stenosis at **2–8 weeks of age** — Noah is 5 weeks — with **non-bilious vomiting that increases in frequency and forcefulness**, becoming forceful enough to "go everywhere" (the lay description of projectile vomiting), and with the infant **feeding normally, even hungrily, straight after vomiting**, exactly as Noah "wants to feed again". The vomit being "all milky" confirms it is non-bilious, ruling out the bile-stained emergencies (malrotation, obstruction) on the wider vomiting differential. Nothing here suggests episodic pain and pallor (against intussusception), Kussmaul breathing or weight loss (against DKA), fever or localising tenderness (against appendicitis), or a chronic malabsorptive course (against coeliac disease).\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Non-bilious, increasingly forceful vomiting in a 2–8-week-old who remains hungry and feeds eagerly straight after vomiting is pyloric stenosis.',
  source:'Pediatrics endpoint part1.pdf p.433'
},

{
  id:'pedep-gi-11', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'Amir was born by elective caesarean section for maternal pre-eclampsia. His birthweight was 3.3 kg. He is 36 hours old. He has started to establish breastfeeding but has been vomiting after every feed. The vomit is noted by the midwife to be green. On examination, his temperature is 37.2°C. His abdomen is slightly distended. The rest of his examination is normal. Which of the following is the most likely cause of the vomiting in this patient?',
  options:['Intussusception','Malrotation','Meningitis','Inflammatory bowel disease','Migraine'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Bilious vomiting in a neonate is a surgical emergency and strongly suggests malrotation with volvulus. The green vomit reflects obstruction distal to the ampulla of Vater.\n\n---\n\n**This option list is also shared, with `pedep-gi-12`** — the discriminator there is an older girl with a classic migraine, not a neonate. The table across both:\n\n| Diagnosis | Signature |\n|---|---|\n| **Malrotation** (this entry) | Neonate, **green (bile-stained) vomiting**, mild abdominal distension — surgical emergency |\n| Intussusception | Peak age 3 months–2 years, not a 36-hour-old neonate |\n| Meningitis | Fever, neck stiffness, lethargy — none described in either vignette |\n| Inflammatory bowel disease | Chronic course, not an acute neonatal or single-episode presentation |\n| **Migraine** (`pedep-gi-12`) | Older child/adolescent, unilateral headache with photophobia, normal exam |\n\n**Why malrotation is right for Amir.** `22)Vomiting.txt` is explicit that **"green bile in vomit is an emergency, as it suggests obstructed bowel"**, and that the more proximal the obstruction, the sooner it becomes bile-stained, **unless the obstruction is proximal to the ampulla of Vater** — the green colour tells you the block sits distal to where bile enters the gut. The same summary slide names malrotation, alongside intussusception and strangulated inguinal hernia, as the emergency causes of bile-stained vomiting to consider. Amir is a term neonate, only 36 hours old, vomiting bile after every feed with a distended abdomen — the classic early presentation of malrotation with volvulus, where the midgut has twisted around an abnormally narrow mesenteric attachment and needs urgent surgical correction to prevent bowel ischaemia.\n\n**Why each other option fails.** *Intussusception* has a peak age of 3 months to 2 years and would be very unusual in a 36-hour-old. *Meningitis* would be expected to bring fever, lethargy or neck stiffness — Amir\'s temperature is essentially normal and the rest of his exam is unremarkable. *Inflammatory bowel disease* is a chronic condition and does not present acutely in the first days of life. *Migraine* is not a neonatal diagnosis at all; it is the answer to the paired sibling question instead, in an adolescent with a headache.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Bile-stained (green) vomiting in a neonate is a surgical emergency until proved otherwise, and malrotation with volvulus is the diagnosis to exclude first.',
  source:'Pediatrics endpoint part1.pdf p.435'
},

{
  id:'pedep-gi-12', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'Jennifer, a 14-year-old girl, presents to the Emergency Department with a severe headache for the last 6 hours, mainly affecting the left side of her head. She just wants to lie still in the dark and dislikes being disturbed, but her mother is concerned as she has never had such an episode before and is normally a very lively girl who is doing well at school. She has been vomiting for the last 2 hours and cannot keep anything down and is also complaining of tummy pain. On examination, she is distressed by her headache and dislikes having the examination light shone on her. Her temperature is 37.2°C. She does not have neck stiffness or papilloedema. The rest of her examination is normal. Which of the following is the most likely cause of the vomiting in this patient?',
  options:['Intussusception','Malrotation','Meningitis','Inflammatory bowel disease','Migraine'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> This is a classic migraine presentation in an adolescent: unilateral headache, photophobia, and vomiting, with normal neurological exam and no meningeal signs. First episodes often present in adolescence.\n\n---\n\nThis question shares its five-option list with `pedep-gi-11`, where the full comparison table is written. Jennifer\'s own discriminating token is that the vomiting is **secondary to a headache**, not a primary gut problem: unilateral (left-sided) headache, photophobia (dislikes the exam light), a desire to lie still in the dark, and abdominal pain accompanying it are a recognisable migraine constellation, particularly as migraine can present with prominent nausea, vomiting and abdominal pain in children and adolescents. Her **normal temperature, absent neck stiffness and absent papilloedema** argue against meningitis or raised intracranial pressure, and a normal neurological exam with no prior episodes in an otherwise well, high-functioning teenager fits a first migraine attack rather than a chronic or structural cause. None of the other four options on the shared list — intussusception, malrotation, meningitis, inflammatory bowel disease — involve a headache at all, which is the feature driving this presentation.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Vomiting that is secondary to a unilateral, photophobic headache in an adolescent, with a normal neurological exam and no meningeal signs, is migraine.',
  source:'Pediatrics endpoint part1.pdf p.437'
},

{
  id:'pedep-gi-13', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'Max, aged 9 years, has been brought to the Emergency Department because he is crying and saying his tummy hurts. He has had a 2-day history of fever and coryza. He has been drinking orange juice but has only eaten some jelly and yogurt. He has not opened his bowels. His temperature is 38.2°C. His throat is red and he has tender cervical lymph nodes. He is not dehydrated. He has mild generalized tenderness of the abdomen, with no guarding. Which of the following is the most likely diagnosis in this patient?',
  options:['Constipation','Pneumonia','Appendicitis','Mesenteric adenitis','Functional abdominal pain'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Mesenteric adenitis commonly follows a viral illness and mimics appendicitis. The presence of fever, coryza, red throat, and cervical lymphadenopathy suggests a viral etiology causing inflamed mesenteric lymph nodes.\n\n---\n\n**This option list cycles through four vignettes in this bank** (`pedep-gi-13`, `pedep-gi-14`, `pedep-gi-15`, `pedep-gi-16`), each picking a different one of five causes of childhood abdominal pain. Written once here:\n\n| Diagnosis | Signature | Grounded in |\n|---|---|---|\n| **Mesenteric adenitis** (this entry) | Recent/current URTI + cervical lymphadenopathy, **mild, generalised** tenderness, **no guarding**, pain resolves in 24–48h | `24)Abdominal pain.txt` |\n| **Pneumonia** (`pedep-gi-14`) | Cough, tachypnoea, fever + **referred** RUQ/abdominal pain | `24)Abdominal pain.txt` |\n| **Appendicitis** (`pedep-gi-15`) | Progressive, **localising** RIF pain, fever, unable to stand straight, worsening course | `24)Abdominal pain.txt` |\n| **Constipation** (`pedep-gi-16`) | No bowel movement for days, palpable indentable fecal mass, minimal tenderness | `23).2)Constipation.txt` |\n| **Functional abdominal pain** | Chronic, vague, never nocturnal, no alarm signs *(not the acute-febrile pattern this ladder tests)* | `24)Abdominal pain.txt` |\n\n**Why Max is mesenteric adenitis specifically.** `24)Abdominal pain.txt` describes non-specific abdominal pain and mesenteric adenitis as pain that **resolves in 24–48 hours**, is **less severe than appendicitis**, with **variable** right iliac fossa tenderness, and **often accompanied by an upper respiratory tract infection with cervical lymphadenopathy**. Max has a 2-day history of fever and coryza, a red throat, tender cervical nodes, and only **mild, generalised** abdominal tenderness **with no guarding** — the deck\'s own contrast against appendicitis, where tenderness is expected to be more localised and accompanied by guarding as the disease progresses.\n\n**Why each other option fails for Max.** *Pneumonia* is not supported — there is no cough, tachypnoea or respiratory sign described. *Appendicitis* is undercut precisely by the mild, generalised (not localising) tenderness and complete absence of guarding — the deck\'s discriminator against mesenteric adenitis. *Constipation* does not fit a 2-day febrile coryzal illness with a red throat and lymphadenopathy, and no fecal mass is described. *Functional abdominal pain* is a chronic diagnosis of exclusion, not an acute febrile presentation with a clear preceding viral illness.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Mild, generalised, non-guarding abdominal pain in a child with a current or recent viral URTI and cervical lymphadenopathy is mesenteric adenitis, which mimics but is milder than appendicitis.',
  source:'Pediatrics endpoint part1.pdf p.439'
},

{
  id:'pedep-gi-14', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:"Pete, aged 4 years, is brought by his mother to the Emergency Department because he is crying and saying his tummy hurts. He has had a 2-day history of fever, coryza, and cough. He is sitting quietly on his mother's lap and is reluctant to play. He has a temperature of 38.2°C and a respiratory rate of 50 breaths/min. On examination, his throat is red and he has tender cervical lymph nodes. He complains of tenderness on palpation of the right upper quadrant of the abdomen. Which of the following is the most likely diagnosis in this patient?",
  options:['Constipation','Pneumonia','Appendicitis','Mesenteric adenitis','Functional abdominal pain'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Abdominal pain in children can be a presenting feature of lower lobe pneumonia due to diaphragmatic irritation. The cough, coryza, fever, tachypnea, and RUQ tenderness point toward pneumonia rather than a primary abdominal pathology.\n\n---\n\nThis question shares its five-option list with `pedep-gi-13`, `pedep-gi-15` and `pedep-gi-16` — the full comparison table is written there. Pete\'s own discriminating token is his **respiratory rate of 50 breaths/min and a cough**, which the other three siblings do not have: `24)Abdominal pain.txt` lists **lower lobe pneumonia** as a cause of abdominal pain through **referred pain**, since the diaphragm shares its nerve supply with the lower chest and upper abdomen. Right upper quadrant tenderness with tachypnoea, fever and cough in a young child is the classic way pneumonia masquerades as an abdominal complaint — a diagnostic trap the same deck flags explicitly (pneumonia is listed among the acute infections that present with the fever–vomiting–abdominal-pain triad, and again among the "other causes" of referred abdominal pain). Nothing here is a surgical abdominal sign (no guarding, no progressive localisation), which is why the diagnosis lies in the chest rather than the gut.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A raised respiratory rate and cough alongside upper-quadrant abdominal tenderness in a febrile child should raise lower lobe pneumonia as a cause of referred abdominal pain.',
  source:'Pediatrics endpoint part1.pdf p.441'
},

{
  id:'pedep-gi-15', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'Molly, aged 10 years, is brought to the Paediatric Assessment Unit as she has been vomiting and had central abdominal pain for 2 days. She has also had some diarrhoea. She has only had apple juice and no food for the last day. Her pain is getting worse. On examination, she has a temperature of 38.2°C and a heart rate of 110 beats/min. She has mild dehydration. There is tenderness in the lower right abdomen, but no guarding. When asked to walk, she is unable to stand up straight because of pain. Which of the following is the most likely diagnosis in this patient?',
  options:['Constipation','Pneumonia','Appendicitis','Mesenteric adenitis','Functional abdominal pain'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Appendicitis presents with worsening abdominal pain, usually starting centrally and localizing to the RIF. Inability to stand upright and focal tenderness despite mild dehydration is highly suggestive of appendicitis.\n\n---\n\nThis question shares its five-option list with `pedep-gi-13`, `pedep-gi-14` and `pedep-gi-16` — the full comparison table is written there. Molly\'s own discriminating token is the **trajectory and the gait sign**: `24)Abdominal pain.txt` describes appendicitis in older children as fever, nausea, vomiting and **right lower quadrant pain that localises and worsens**, and Molly\'s pain began centrally (periumbilical, the classic first phase as the appendix inflames) and is now **getting worse** and localising to the lower right abdomen. Being **unable to stand up straight** because of pain is a recognised sign of peritoneal irritation, and her tachycardia and mild dehydration reflect an evolving acute surgical illness rather than the milder, self-limiting course of mesenteric adenitis (Max, `pedep-gi-13`), whose pain is explicitly **less severe** and resolves within 24–48 hours. The absence of guarding here does not exclude appendicitis — guarding is a later sign, and the deck\'s own point is that the trajectory (worsening, localising) is what separates it from adenitis, not tenderness alone.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Central abdominal pain that worsens and localises to the right iliac fossa, with an inability to stand up straight, is appendicitis even before guarding appears.',
  source:'Pediatrics endpoint part1.pdf p.443'
},

{
  id:'pedep-gi-16', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'Ted, aged 2 years, has had a 2-day history of low-grade fever and coryza. His mother has brought him to the Emergency Department because he is crying inconsolably. She thinks his tummy is hurting him. He has not opened his bowels for 2 days. He appears reasonably well, has minimal abdominal tenderness, but has an indentable mass on the left side of the abdomen. Which of the following is the most likely diagnosis?',
  options:['Constipation','Pneumonia','Appendicitis','Mesenteric adenitis','Functional abdominal pain'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Chronic constipation can present with a palpable fecal mass and abdominal discomfort. The minimal tenderness and history of not opening bowels support this diagnosis over acute surgical causes\n\n---\n\nThis question shares its five-option list with `pedep-gi-13`, `pedep-gi-14` and `pedep-gi-15` — the full comparison table is written there. Ted\'s own discriminating token is the **left-sided, indentable mass** together with **minimal tenderness** and the child looking **"reasonably well"**: `23).2)Constipation.txt` names a fecal mass on the **left lower quadrant (loaded sigmoid colon)** as an examination finding of constipation, and an indentable quality is what a soft faecal mass, rather than an inflamed appendix or lymph node mass, feels like on palpation. Ted has not opened his bowels for 2 days, and his mild coryzal illness is incidental rather than the driver of his pain — unlike Max (`pedep-gi-13`), whose fever and lymphadenopathy are the point, or Molly (`pedep-gi-15`), whose pain is worsening and localising with systemic upset. The combination of minimal tenderness, no guarding, and a well-looking child argues against appendicitis or pneumonia, and there is no sign this is chronic enough to be labelled functional pain — this is a discrete, explicable episode.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A left-sided, indentable abdominal mass with minimal tenderness in a well-looking child who has not opened his bowels for days is constipation, not a surgical or infective abdomen.',
  source:'Pediatrics endpoint part1.pdf p.445'
},

{
  id:'pedep-gi-17', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 5-week-old baby boy is brought to the Emergency Department with a 48-hour history of projectile vomiting. The infant is hungry after vomiting and has not opened his bowels in 3 days. Clinical examination reveals a mass in the left upper quadrant. A blood gas is performed: pH 7.50, pCO2 5.5 kPa, and bicarbonate 30 mmol/L. What does this blood gas represent?',
  options:['Normal findings','Metabolic acidosis','Metabolic alkalosis','Respiratory acidosis','Respiratory alkalosis'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Projectile vomiting leads to loss of gastric hydrochloric acid, resulting in metabolic alkalosis. The high pH, elevated bicarbonate, and clinical signs support this acid-base imbalance.\n\n---\n\nThe vignette is pyloric stenosis: onset around 5 weeks of age (typically 2–8 weeks), non-bilious **projectile** vomiting, a baby who remains **hungry after vomiting**, and infrequent stooling from reduced gut throughput. Repeated vomiting of gastric contents strips out hydrochloric acid and, with it, hydrogen and chloride ions; the kidney responds by conserving hydrogen and chloride at the expense of retaining bicarbonate, producing the classic **hypochloraemic, hypokalaemic metabolic alkalosis** of pyloric stenosis (`22)Vomiting.txt`). The gas here — **raised pH, raised bicarbonate, pCO2 not low** — is exactly that picture: a primary metabolic process (bicarbonate up) with the pH moving in the same direction, not a respiratory one.\n\nEach distractor is a different pattern the same gas does not fit. *Normal findings* — a pH of 7.50 and bicarbonate of 30 mmol/L are both clearly outside the normal range. *Metabolic acidosis* would show a **low** pH and **low** bicarbonate, the opposite of what is printed. *Respiratory acidosis* needs a **low** pH with a **raised** pCO2 driving it; here pCO2 is unremarkable and pH is high, not low. *Respiratory alkalosis* needs a **low** pCO2 (hyperventilation blowing off CO2) with a compensatory fall in bicarbonate — here pCO2 is normal-to-mildly-raised (a degree of respiratory compensation for the metabolic alkalosis) and bicarbonate is high, not low — the reverse pattern.\n\nOne point in the stem is worth naming plainly rather than passing over: the mass of hypertrophic pyloric stenosis is classically described as an **olive-shaped mass in the right upper quadrant or epigastrium**, palpable during or after a test feed — not the left upper quadrant this stem prints. The rest of the vignette (age, projectile vomiting, hunger after vomiting, constipation, and the acid-base picture) is unambiguously pyloric stenosis regardless of that detail, and the side printed here is carried exactly as the page prints it.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Pyloric stenosis produces a hypochloraemic, hypokalaemic metabolic alkalosis from repeated loss of gastric hydrochloric acid — raised pH and raised bicarbonate with pCO2 not driving the change.',
  source:'Pediatrics endpoint part1.pdf p.447'
},

{
  id:'pedep-gi-18', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A 12-year-old boy presents to the Emergency Room with a 4-hour history of groin pain. He is complaining of nausea and has vomited twice. On examination, there is tenderness and swelling of the scrotum and right testicle, with absence of the cremasteric reflex on that side. There is no fever or erythema. Routine blood tests are normal. He describes several previous episodes of short-lived pain. What is the most likely diagnosis?',
  options:['Testicular torsion','Torsion of the hydatid of Morgagni','Inguinal hernia','Renal stone','Epididymo-orchitis'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Testicular torsion presents with sudden onset of unilateral testicular pain, absent cremasteric reflex, and sometimes nausea or vomiting. This is a surgical emergency and must be recognized promptly.\n\n---\n\n*(This vignette is not covered in the peds GI lectures — the acute scrotum is a surgical topic, so the reasoning below is drawn from general medical knowledge, not taken from the course material.)*\n\nTesticular torsion is a time-critical surgical emergency: the testis twists on its spermatic cord, cutting off its own blood supply. It classically presents with **sudden, severe unilateral testicular or groin pain**, often with nausea and vomiting from the visceral pain response, and examination finds a **swollen, tender testis with an absent cremasteric reflex** on the affected side — exactly this boy\'s picture. The history of **several previous short episodes of pain** fits intermittent torsion-detorsion, a recognised pattern before a full torsion that does not spontaneously resolve. **No fever, no erythema, and normal blood tests** argue against an infective process, which is the key discriminator against the two infective distractors.\n\nEach distractor fails a specific feature. *Torsion of the hydatid of Morgagni* (a vestigial embryological remnant on the testis) causes testicular pain but the cremasteric reflex is typically **preserved**, and a tender nodule ("blue dot sign") rather than diffuse scrotal swelling is more typical — the absent reflex here points away from it. *Inguinal hernia* would usually present with a reducible or irreducible groin swelling tracking toward the inguinal canal rather than isolated testicular/scrotal tenderness, and normal bloods and the acute onset with an absent reflex do not fit an incarcerated hernia\'s more gradual, bowel-obstruction-type picture. *Renal stone* causes colicky loin-to-groin pain that may radiate to the testis, but it does not cause scrotal swelling or an absent cremasteric reflex, and urinalysis (not given here as abnormal) would typically show haematuria. *Epididymo-orchitis* is excluded by the **absence of fever and erythema** and **normal inflammatory markers on routine bloods**, plus it does not typically abolish the cremasteric reflex — the reflex loss is a torsion-specific sign.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Sudden unilateral testicular pain with an absent cremasteric reflex, especially with a history of prior short-lived episodes, is testicular torsion until surgically excluded — it does not wait for confirmatory tests.',
  source:'Pediatrics endpoint part1.pdf p.449'
},

{
  id:'pedep-gi-19', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 2-month-old infant is brought to the GP by his mother. She is concerned that he vomits after every feeding. She has noticed that his abdomen has become distended. On further questioning, he opens his bowels infrequently every 3-4 days and did not pass meconium until 72 hours of age. Abdominal X-ray shows distended loops of bowel with no air in the rectum. What is the most likely diagnosis?',
  options:['Hirschsprung\'s disease','Constipation due to dehydration','Pyloric stenosis','Cow\'s milk protein allergy','Intussusception'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Delayed passage of meconium, chronic constipation, abdominal distension, and absence of rectal air on X-ray are classic features of Hirschsprung\'s disease. This is due to aganglionic segments of bowel leading to functional obstruction.\n\n---\n\nHirschsprung\'s disease is discussed earlier in this section at `pedep-gi-7`, where it presented as neonatal delayed meconium and constipation; this vignette adds the two other classic pillars. *(The following mechanism detail is general medical knowledge rather than something the peds lectures cover directly — not taken from the course material.)* The bowel wall\'s ganglion cells, which normally allow peristaltic relaxation, fail to develop in a segment starting at the anus and extending proximally for a variable distance; that segment stays permanently contracted and cannot relax to pass stool, so bowel proximal to it dilates and obstructs. **Delayed passage of meconium beyond 48 hours (here 72 hours), chronic infrequent stooling, progressive abdominal distension, and vomiting from functional obstruction** are the clinical picture, and an X-ray showing **distended bowel loops with no air reaching the rectum** is the classic radiological correlate of a distal aganglionic segment obstructing outflow. Confirmation is by rectal suction biopsy showing absent ganglion cells — the investigation tested separately at `pedep-gi-23`.\n\nEach distractor is excluded by a specific feature. *Constipation due to dehydration* is a functional, usually older-infant problem from inadequate fluid/feed volume; it does not explain a **72-hour delay in passing meconium at birth** or an X-ray with **no air in the rectum**, both of which point to a structural/functional obstruction present from birth. *Pyloric stenosis* causes non-bilious projectile vomiting from a hypertrophied pylorus, but it does not cause delayed meconium passage or infrequent stooling from birth, and it obstructs at the stomach outlet, not the distal bowel — the X-ray would not show distal bowel gas absence in this pattern. *Cow\'s milk protein allergy* causes vomiting, blood/mucus in stool, or eczema/atopy in a milk-fed infant, but does not explain a birth history of delayed meconium passage. *Intussusception* is an acute, usually older-infant (peak 6 months to 2 years) telescoping event with colicky pain and a palpable mass, not a chronic pattern present since the newborn period.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Delayed passage of meconium beyond 48 hours, chronic infrequent stooling, abdominal distension, and no rectal gas on X-ray together point to Hirschsprung\'s disease.',
  source:'Pediatrics endpoint part1.pdf p.451'
},

{
  id:'pedep-gi-20', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A 7-month-old infant presents with a 12-hour history of intermittent inconsolable crying. He is mottled, has cold peripheries, and has vomited several times. Examination reveals a mass in the right upper quadrant of the abdomen. What is the most likely cause of his symptoms?',
  options:['Colic','Incarcerated hernia','Gastroenteritis','Intussusception','Gastro-oesophageal reflux'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Intussusception typically presents with intermittent pain, vomiting, a palpable abdominal mass, and systemic signs like mottling and lethargy. It is a surgical emergency often seen in infants around this age.\n\n---\n\n`24)Abdominal pain.txt` describes intussusception as telescoping of one segment of bowel into an adjacent one, classically peaking around 6 months to 2 years of age, presenting with **intermittent, colicky, inconsolable crying** (the infant draws the legs up between episodes of apparent well-being), **vomiting**, and a **palpable sausage-shaped mass**, often in the right upper quadrant as the ileocaecal segment telescopes. **Mottling and cold peripheries** signal the child is becoming shocked — a surgical emergency requiring urgent reduction (air/contrast enema or surgery) rather than watchful waiting. Every element of this 7-month-old\'s presentation — the age, the intermittent pattern, the RUQ mass, and the systemic compromise — fits this diagnosis precisely.\n\nEach distractor lacks the mass or the systemic severity. *Colic* causes episodic infant crying but is a diagnosis of exclusion in a well, thriving infant with **no palpable mass and no systemic signs** — mottling and cold peripheries are never part of colic. *Incarcerated hernia* causes a tender, irreducible groin (not right-upper-quadrant abdominal) swelling; the mass location here does not fit. *Gastroenteritis* causes vomiting and often diarrhoea, but not an intermittent colicky crying pattern with a discrete abdominal mass — the mass is the finding that rules it out. *Gastro-oesophageal reflux* causes recurrent regurgitation/vomiting but does not cause intermittent severe colicky pain, a palpable mass, or shock signs; it is a far milder, chronic picture (`22)Vomiting.txt`).\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Intermittent inconsolable crying with vomiting, a palpable right-sided abdominal mass, and signs of shock (mottling, cold peripheries) in an infant is intussusception until reduced.',
  source:'Pediatrics endpoint part1.pdf p.453'
},

{
  id:'pedep-gi-21', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'A 9-year-old presents with a 6-month history of non-bloody diarrhea associated with 4 kg of weight loss. His mother says he is less energetic than before and looks paler than normal. There is no history of foreign travel. Blood tests show microcytic anemia (Hb 8.9 g/dL, MCV 72) but normal inflammatory markers. What is the most likely diagnosis?',
  options:['Crohn\'s disease','Salmonella infection','Coeliac disease','Cow\'s milk protein allergy','Ulcerative colitis'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Chronic diarrhea, weight loss, pallor, and microcytic anemia with normal inflammatory markers are classic for coeliac disease. This autoimmune condition is triggered by gluten intake and affects nutrient absorption.\n\n---\n\nThis question contrasts with `pedep-gi-2`, where a toddler\'s **normal-looking, thriving** chronic diarrhoea argued against coeliac disease; here the pattern is the opposite. *(Coeliac disease itself is not covered in detail in the peds GI lectures beyond being listed as a screening step in an unrelated context — the reasoning below draws on general medical knowledge, not taken from the course material.)* Coeliac disease is an autoimmune enteropathy triggered by dietary gluten, causing villous atrophy in the small bowel and consequent malabsorption. A **6-month history of chronic non-bloody diarrhoea with significant weight loss (4 kg), fatigue, pallor, and iron-deficiency-pattern microcytic anaemia (low Hb, low MCV)** is the classic malabsorption picture, and **normal inflammatory markers** are an important discriminator — coeliac disease is not primarily an inflammatory bowel process, so CRP/ESR are typically normal or only mildly raised, unlike true inflammatory bowel disease.\n\nEach distractor is excluded chiefly by that inflammatory-marker point or the exposure history. *Crohn\'s disease* can cause chronic diarrhoea, weight loss and anaemia, but it is a transmural inflammatory disease and would be expected to raise inflammatory markers (CRP/ESR), and often features abdominal pain, mouth ulcers or perianal disease not described here. *Salmonella infection* causes acute, often bloody diarrhoea with a preceding exposure (contaminated food or travel) and would raise inflammatory markers acutely — the 6-month chronicity and explicit absence of foreign travel argue against it. *Cow\'s milk protein allergy* presents in younger infants around the time of milk introduction, not a previously well 9-year-old with a half-year history. *Ulcerative colitis* is another inflammatory bowel disease that classically causes **bloody** diarrhoea and, like Crohn\'s, would be expected to raise inflammatory markers — both features this child lacks.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Chronic non-bloody diarrhoea with weight loss, fatigue and iron-deficiency microcytic anaemia but normal inflammatory markers should suggest coeliac disease over inflammatory bowel disease.',
  source:'Pediatrics endpoint part1.pdf p.455'
},

{
  id:'pedep-gi-22', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'An 8-year-old girl presents with a 6-month history of pain most days around the umbilicus, lasting for an hour and responding to paracetamol syrup. It does not usually occur at weekends. She opens her bowels daily and passes a soft stool. She is thriving, with her weight and height on the 75th centile. Which of the following is the appropriate next step?',
  options:['Abdominal radiograph','Referral to a paediatric gastroenterologist','Inflammatory markers and liver function tests','Reassurance and no further investigation','Prescription for laxatives'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Chronic periumbilical pain in a thriving child with normal bowel habits and no red flags suggests functional abdominal pain. It is common and does not require further investigation if there are no alarm features.\n\n---\n\nThis vignette prints more than once across this bank; the printings are recorded separately here, not reconciled against one another. Taking the page as it stands: `24)Abdominal pain.txt` sets out the alarm ("red flag") signals that separate organic from functional abdominal pain — nocturnal waking, weight loss or growth faltering, blood in stool, fever, and pain that is progressive or localised rather than vague and recurrent. This girl has **none of them**: her pain is **periumbilical** (the textbook site for functional pain), **does not occur at weekends** (a recognised pattern linking it to school-day stress), she has **daily soft stools** (no constipation or diarrhoea), and she is **thriving on the 75th centile** for both weight and height, which excludes any organic process causing malabsorption or systemic illness. With a clear history and a normal examination, the correct next step for classic, alarm-free functional abdominal pain is **reassurance** of the child and family, explaining the benign nature of the pain, rather than pursuing investigations that a low-probability history does not justify.\n\nEach distractor represents over-investigation or a mismatched intervention. *Abdominal radiograph* would be reasonable if constipation with faecal loading were suspected, but her daily soft stool argues against that. *Referral to a paediatric gastroenterologist* is appropriate when alarm features are present or first-line reassurance fails — neither applies at this first presentation with a clean history. *Inflammatory markers and liver function tests* are the kind of screen ordered when an organic or inflammatory cause is suspected; nothing here (growth, stool pattern, systemic wellbeing) points that way. *Prescription for laxatives* treats constipation, which this child does not have — she is already passing a soft stool daily.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Chronic periumbilical pain in a thriving child with a normal stool pattern and no alarm features is functional abdominal pain, managed with reassurance rather than investigation.',
  source:'Pediatrics endpoint part1.pdf p.457'
},

{
  id:'pedep-gi-23', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'A 6-month-old baby presents with a history of constipation since birth. Her mother has been using glycerine suppositories every 3 days to help her defecate. When she inserts the suppository, a gush of liquid stool is passed. Her mother remembers she did not open her bowels until she was 3 days old. Which of the following investigations would confirm the diagnosis?',
  options:['Thyroid function tests','Barium enema','Bone profile','Abdominal film','Suction biopsy of the rectum'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> A suction rectal biopsy is the gold standard for diagnosing Hirschsprung\'s disease. The history of chronic constipation since birth and explosive stools after rectal stimulation are key clues.\n\n---\n\nThis case follows on from `pedep-gi-7` and `pedep-gi-19`, where Hirschsprung\'s disease was diagnosed clinically; here the question asks for the **confirmatory investigation**. The history is textbook: **constipation since birth**, **delayed passage of meconium (day 3)**, and — a specific clue — a **gush of liquid stool on rectal stimulation** (the "squirt sign"), which happens because stool has pooled proximal to the permanently contracted aganglionic segment and is released under pressure once the rectal exam or suppository disturbs it. *(The specifics of the confirmatory test are general medical knowledge, not detailed in the peds GI lectures — not taken from the course material.)* **Suction biopsy of the rectum**, examined histologically for the **absence of ganglion cells** (with hypertrophied nerve trunks and increased acetylcholinesterase activity), is the definitive diagnostic test, because Hirschsprung\'s disease is fundamentally a histological diagnosis — the bowel\'s nerve supply, not its shape, is the abnormality.\n\nEach distractor investigates the wrong system or only supports rather than confirms the diagnosis. *Thyroid function tests* would be relevant if congenital hypothyroidism were suspected as a cause of constipation, but the birth history (delayed meconium, gush sign) already points specifically to Hirschsprung\'s disease, not a metabolic cause. *Barium enema* can show a transition zone between the narrow aganglionic segment and the dilated normal bowel proximal to it, which is highly suggestive, but it is a **supportive** imaging test, not the confirmatory (histological) one. *Bone profile* investigates calcium/phosphate/vitamin D disorders, unrelated to bowel innervation. *Abdominal film* may show dilated bowel loops as a non-specific sign of obstruction, again supportive rather than diagnostic.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Suction rectal biopsy showing absent ganglion cells is the confirmatory (not merely supportive) investigation for Hirschsprung\'s disease.',
  source:'Pediatrics endpoint part1.pdf p.459'
},

{
  id:'pedep-gi-24', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A 9-year-old boy presents with a 24-hour history of abdominal pain, initially around the umbilicus and now localized to the right iliac fossa. His mother says he has not eaten today and has been listless. He finds it difficult to stand up straight. On examination, he is tender and guarding on palpation. What is the next step in management?',
  options:['Referral to surgical team','Abdominal radiograph','Intravenous antibiotics','Full septic screen','Admit to the ward for review on the ward round'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> The clinical picture is highly suggestive of appendicitis, with localized tenderness, guarding, and inability to stand upright. Urgent surgical evaluation is the appropriate next step.\n\n---\n\nThis vignette shares its clinical picture with `pedep-gi-15` (Molly), which asked for the **diagnosis** off the same pattern of pain migrating from periumbilical to the right iliac fossa, anorexia, an inability to stand up straight, and tenderness with guarding — this question asks for the **next step** once appendicitis is the working diagnosis. `24)Abdominal pain.txt` frames appendicitis as a surgical emergency: once the clinical picture is this convincing (guarding is a peritoneal sign, not a soft finding), the priority is **urgent surgical referral** for assessment and likely appendicectomy, not further delay for tests that a strong clinical diagnosis does not need.\n\nEach distractor either delays definitive care or targets the wrong problem. *Abdominal radiograph* rarely adds useful information in classic appendicitis and would only delay surgical review. *Intravenous antibiotics* may eventually form part of peri-operative management, but starting them is not the **next step** ahead of getting the surgical team involved, and antibiotics alone do not treat an inflamed, potentially perforating appendix. *Full septic screen* (blood cultures, urine, sometimes lumbar puncture) is the correct next step for a source-unclear sepsis picture, not a child with a clear localising surgical abdomen. *Admit to the ward for review on the ward round* dangerously delays a time-critical surgical assessment — appendicitis can progress to perforation while a child waits for a scheduled round.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Once a clinical picture is convincingly appendicitis (migrating pain, guarding, inability to stand straight), the next step is urgent surgical referral, not further delay for investigations.',
  source:'Pediatrics endpoint part1.pdf p.461'
},

{
  id:'pedep-gi-25', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 6-week-old male infant presents with a one-week history of worsening non-bilious vomiting. His mother reports that the vomiting is projectile and seems to be gradually worsening. He is eager to feed after vomiting but is having fewer wet nappies than usual. On examination, he is afebrile, appears hungry, and looks mildly dehydrated. What is the most likely diagnosis?',
  options:['Cow\'s milk protein intolerance','Gastroenteritis','Meningitis','Pyloric stenosis','Malrotation and volvulus'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Progressive non-bilious projectile vomiting with persistent hunger and dehydration is typical of pyloric stenosis. Diagnosis is clinical and confirmed by imaging.\n\n---\n\nThis is the same diagnosis as `pedep-gi-10` and `pedep-gi-17`, this time asked as a straightforward recall from the vignette rather than against a differential list. `22)Vomiting.txt` describes pyloric stenosis presenting at **2–8 weeks of age** (this baby is 6 weeks) with **non-bilious, projectile, progressively worsening vomiting**, a baby who remains **hungry and eager to feed** immediately afterwards because the obstruction is at the gastric outlet and not further down the gut, and signs of **dehydration** (here, reduced wet nappies) from ongoing fluid loss. Being **afebrile** fits — this is a mechanical obstruction, not an infective illness.\n\nEach distractor is excluded by a specific mismatch. *Cow\'s milk protein intolerance* typically causes vomiting alongside diarrhoea, blood/mucus in stool, or eczema, not isolated progressively worsening projectile vomiting with hunger. *Gastroenteritis* usually comes with diarrhoea and fever, and does not typically produce true projectile vomiting with a hungry, otherwise well-looking infant between episodes. *Meningitis* would be expected to cause fever, lethargy or irritability, and possibly a bulging fontanelle — not an afebrile, hungry, alert infant with isolated progressive vomiting. *Malrotation and volvulus* classically causes **bilious (green)** vomiting, a surgical red flag distinct from this baby\'s **non-bilious** picture, and tends to present more acutely and unwell than a gradually worsening week-long course.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Progressive non-bilious projectile vomiting in a hungry 2–8-week-old infant with signs of dehydration is pyloric stenosis.',
  source:'Pediatrics endpoint part1.pdf p.463'
},

{
  id:'pedep-gi-26', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A 15-year-old girl attends a clinic concerned about episodic abdominal pain and loose stool over the past year. She dates the symptoms back to when she changed schools and says they occur more often on school days. She describes crampy abdominal pain followed by the need to pass a stool, occurring about twice a month. Her bowel habit is normal on other days. There has never been any blood, and she has not lost any weight. What is the most likely underlying cause of her symptoms?',
  options:['Cow\'s milk protein intolerance','Coeliac disease','Ulcerative colitis','Irritable bowel syndrome','Overflow diarrhea secondary to constipation'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Crampy abdominal pain associated with bowel habit changes, occurring during stress (school days), and without red flags suggests irritable bowel syndrome. This is a functional GI disorder common in adolescents.\n\n---\n\nThis question contrasts directly with `pedep-gi-5`, where the same "functional" family of diagnoses was tested via **functional abdominal pain** (pain without a bowel-habit trigger). Here, `24)Abdominal pain.txt`\'s functional GI disorders extend to **irritable bowel syndrome**: crampy pain **linked to defecation** (pain followed by the urge to pass stool, a core IBS feature), a clear **stress trigger** (worse on school days, since she changed schools a year ago), **episodic** rather than constant symptoms, and **normal bowel habit between episodes**. The **absence of blood and weight loss** over a full year is the reassuring negative that keeps this functional rather than organic.\n\nEach distractor is excluded by a mismatched feature. *Cow\'s milk protein intolerance* is a food-reactive process typically presenting in infancy, not a 15-year-old with a stress-linked, episodic pattern. *Coeliac disease* would be expected to cause weight loss or growth/nutritional impact over a year of active disease (as seen in `pedep-gi-21`), which this girl explicitly does not have. *Ulcerative colitis* causes **bloody** diarrhoea and is a chronic inflammatory process — both excluded here by "there has never been any blood" and the episodic, otherwise-normal bowel pattern. *Overflow diarrhoea secondary to constipation* would show a background of infrequent, hard stool with soiling episodes, not a normal bowel habit between discrete episodes of crampy pain and loose stool.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Episodic, stress-linked crampy abdominal pain relieved by defecation with a normal bowel habit between episodes and no red flags is irritable bowel syndrome.',
  source:'Pediatrics endpoint part1.pdf p.465'
},

{
  id:'pedep-gi-27', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'A mother brings in her 3-month-old girl because of repeated diarrhea and vomiting that started the day before and is currently unable to retain anything in her stomach. You find that the infant is severely dehydrated and feverish with cold extremities. What is first thing you should do?',
  options:['cold foments and antipyretic','anti-emetic and trial of breast feeding','IV line and administer normal saline','continue breast feeding with and give ORS','IM antibiotics and oral rehydration solution'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> The infant is severely dehydrated and hemodynamically unstable; the priority is rapid fluid resuscitation with IV isotonic saline to restore perfusion. Symptomatic treatments or oral rehydration are insufficient at this stage.\n\n---\n\n`23).1) Acute diarrhea.txt` sets out dehydration severity and its management: mild-to-moderate dehydration can be managed with **oral rehydration solution (ORS)**, but **severe dehydration with shock features — cold extremities, being unable to retain any oral intake, and fever suggesting systemic compromise — needs immediate IV fluid resuscitation**, because the gut cannot be relied on to absorb fluid fast enough to correct a shocked circulation, and a vomiting infant cannot keep oral fluid down regardless. The **first** action in this severely unwell infant is therefore to secure **IV access and give a bolus of isotonic (0.9%) saline** to restore circulating volume, before any oral strategy is considered.\n\nEach distractor either treats the wrong problem or uses the wrong route. *Cold foments and antipyretic* only addresses the fever and does nothing for the underlying dehydration and shock. *Anti-emetic and trial of breastfeeding* still relies on the oral route, which this vomiting, severely dehydrated infant cannot tolerate. *Continue breastfeeding with ORS* is correct management for **mild-to-moderate** dehydration, not this severe, shocked presentation. *IM antibiotics and oral rehydration solution* both treats a presumed infection empirically (not established) and again relies on oral rehydration, which is inadequate once a child is in shock — fluid resuscitation always comes before antibiotics in an unstable child.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A severely dehydrated, vomiting infant with shock signs (cold extremities, unable to retain intake) needs immediate IV isotonic fluid resuscitation before any oral rehydration strategy.',
  source:'Pediatrics endpoint part1.pdf p.467'
},

{
  id:'pedep-gi-28', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A previously healthy 6 months old child develops paroxysmal colicky abdominal pain. The infant has occasional vomiting. Over the next 12 hours the infant passes blood and mucous and becomes progressively lethargic. Following fluid resuscitation, the most appropriate next step in management is:',
  options:['IV antibiotics','stool culture','barium meal','abdominal US','empiric anti-dysentery therapy'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> The presentation is classic for intussusception. Ultrasound is the diagnostic modality of choice as it is non-invasive, sensitive, and can sometimes guide reduction.\n\n---\n\nThis is the same diagnosis as `pedep-gi-8` and `pedep-gi-20` — paroxysmal colicky pain, vomiting, and here the added classic sign of **redcurrant-jelly stool (blood and mucous)**, with progressive lethargy signalling the child is becoming unwell. Once initial fluid resuscitation has stabilised the child, `24)Abdominal pain.txt`\'s point about intussusception is that **abdominal ultrasound** is the investigation of choice: it is non-invasive, quick, highly sensitive for the "target" or "doughnut" sign of telescoped bowel, and — unlike some of the alternatives — carries no radiation and can be followed directly by an image-guided (air or contrast) reduction attempt in the same setting.\n\nEach distractor either targets the wrong diagnosis or is the wrong modality. *IV antibiotics* would be relevant if a bacterial dysenteric infection were confirmed, but the clinical picture (paroxysmal colic, a palpable course, redcurrant stool) points to a mechanical surgical problem, not an infection to be treated empirically before imaging. *Stool culture* looks for an infective cause of bloody stool, which is a reasonable differential but does not address the more urgent, more likely surgical diagnosis suggested by the colicky pattern and lethargy — and does not by itself guide immediate management. *Barium meal* images the upper GI tract and is not the tool used to diagnose or manage intussusception, which is typically distal small-bowel/ileocaecal. *Empiric anti-dysentery therapy* again assumes an infective cause without confirmation, and delays the imaging that would identify (and potentially treat) intussusception.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Once an infant with suspected intussusception is fluid-resuscitated, abdominal ultrasound is the next investigation of choice — non-invasive, sensitive, and able to guide reduction.',
  source:'Pediatrics endpoint part1.pdf p.469'
},

{
  id:'pedep-gi-29', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'Which is not a consequence of watery diarrhea?',
  options:['dehydration','Hyponatremia','Hypokalemia','Hypernatremia','Metabolic alkalosis'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Watery diarrhea usually causes dehydration, hyponatremia, and hypokalemia; it typically leads to metabolic acidosis due to bicarbonate loss, not alkalosis.\n\n---\n\nThis is a straight recall question off `23).1) Acute diarrhea.txt`\'s list of the metabolic consequences of watery diarrhoea. Stool is rich in water, sodium, potassium and **bicarbonate**; losing large volumes of it produces **dehydration**, and depending on the balance of water versus electrolyte loss and on oral intake, either **hyponatraemia** (if replacement fluid is relatively electrolyte-poor, e.g. plain water) or **hypernatraemia** (if free water loss outpaces sodium loss, e.g. from fever and insensible losses) can result — both are recognised patterns of dehydration in diarrhoeal illness, which is why both appear as options that ARE consequences. **Hypokalaemia** follows directly from stool potassium loss. Because bicarbonate is lost in the stool, the acid-base consequence of watery diarrhoea is **metabolic acidosis**, not alkalosis — the option the question asks you to identify as the one that does **not** occur.\n\nThis question does not carry a shared option menu or a clinical vignette to work through per-distractor; each of the other four options (dehydration, hyponatraemia, hypokalaemia, hypernatraemia) is a genuine, recognised consequence of diarrhoeal fluid and electrolyte loss, which is exactly why *metabolic alkalosis* stands out as the one that is not — it is instead the acid-base pattern seen in **projectile vomiting/pyloric stenosis** (`pedep-gi-17`), where acid rather than bicarbonate is lost, the mirror image of this question.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Watery diarrhoea loses bicarbonate in stool and causes metabolic acidosis, not alkalosis — the mirror image of the metabolic alkalosis caused by vomiting in pyloric stenosis.',
  source:'Pediatrics endpoint part1.pdf p.471'
},

{
  id:'pedep-gi-30', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'Which of the following is not consistent with Hirschsprung\'s disease?',
  options:['No passage of meconium after 24 hours of birth','Abdominal distension','Bile-stained vomiting','Refractory constipation','Treatment is by repeated finger dilatation'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Hirschsprung\'s disease is managed surgically (pull-through procedure), not by repeated digital dilatation. Other options reflect common clinical features.\n\n---\n\nThis vignette-free recall question appears to reprint elsewhere in this bank; the two printings are recorded separately here, not reconciled against each other. Taking this page as it stands: the first four options are all genuine features of Hirschsprung\'s disease already established across `pedep-gi-7`, `pedep-gi-19` and `pedep-gi-23` — **failure to pass meconium within 24–48 hours of birth**, **abdominal distension** from proximal bowel dilatation, **bile-stained vomiting** as the obstruction becomes more complete, and **refractory (treatment-resistant) constipation** from the permanently contracted aganglionic segment. Definitive treatment is **surgical**: a "pull-through" procedure that resects the aganglionic segment and anastomoses healthy, ganglion-containing bowel down to the anus, restoring normal peristalsis and relaxation. **Repeated finger (digital) dilatation** is not curative for an anatomically and histologically abnormal segment of bowel that lacks ganglion cells — dilating the anal canal does not restore nerve supply — which is why it is the option that is **not** consistent with the disease or its management.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Hirschsprung\'s disease is treated surgically (pull-through resection of the aganglionic segment), not by repeated digital dilatation, which cannot restore missing ganglion cells.',
  source:'Pediatrics endpoint part1.pdf p.473'
},

{
  id:'pedep-gi-31', bank:'endpoint', module:'pediatrics', chapter:'gi-abdopain',
  stem:'A 1-year-old presenting to the ER with abdominal colic and vomiting. X ray of the abdomen shows distended small bowel and absence of air in the distal colon and rectum, what is the diagnosis?',
  options:['intussusception','Hirschsprung disease','Incarcerated hernia','Peptic ulcer disease','Fecal impaction'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> The X-ray findings of distended small bowel with absence of air in the distal colon and rectum in a 1-year-old with acute abdominal colic and vomiting strongly suggest a mechanical small bowel obstruction, which is classic for intussusception in this age group\n\n---\n\nThis is the same diagnosis as `pedep-gi-8`, `pedep-gi-20` and `pedep-gi-28`, now identified purely from an **X-ray pattern** rather than the clinical vignette. A 1-year-old is squarely within the peak age range for intussusception (`24)Abdominal pain.txt`). **Colicky abdominal pain, vomiting, and an X-ray showing distended small bowel with no distal (colonic/rectal) gas** together describe a **mechanical small bowel obstruction with a distal cut-off**, which is exactly the picture produced when a segment of bowel telescopes into an adjacent segment and physically blocks the lumen — gas cannot pass the obstruction to reach the rectum, while bowel proximal to it dilates from trapped gas and fluid.\n\nEach distractor does not fit this specific radiological pattern at this age. *Hirschsprung disease* is a **chronic, since-birth** presentation, not an **acute** presentation at 1 year of age with colic; its X-ray pattern is a distal transition zone rather than a picture that develops acutely. *Incarcerated hernia* would show a visible groin swelling on examination alongside the obstructive picture — not mentioned here — and is a less common cause of this X-ray pattern at this age than intussusception. *Peptic ulcer disease* is rare in a 1-year-old and does not cause a small bowel obstruction pattern. *Fecal impaction* causes a colonic loading pattern with stool visible on X-ray, not distended small bowel with absent distal gas, and does not typically present with acute colic and vomiting in a previously well 1-year-old.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Distended small bowel with absent gas in the distal colon and rectum on X-ray, in a colicky, vomiting infant, is intussusception until proved otherwise.',
  source:'Pediatrics endpoint part1.pdf p.475'
},

{
  id:'pedep-gi-32', bank:'endpoint', module:'pediatrics', chapter:'gi-diarrhoea',
  stem:'A 6-year-old boy presents with polydipsia, polyuria and unexplained weight loss. On examination, he is lethargic and thin. His blood sugar is 34mmol/mol. His urine dipstick shows the presence of glucose and ketones, and his blood ketones are 4.0. You are about to take bloods, including a blood gas. Which ONE of these conditions should be screened for at presentation?',
  options:['Coeliac disease','Diabetic retinopathy','Diabetic neuropathy','Diabetic nephropathy','Multiple endocrine neoplasia type 1'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Children with type 1 diabetes have a higher risk of autoimmune conditions, especially coeliac disease, which should be screened at diagnosis.\n\n---\n\nThe vignette is new-onset diabetic ketoacidosis: polydipsia, polyuria, weight loss, lethargy, hyperglycaemia, and glucose plus ketones on dipstick with a markedly raised blood ketone level (`51) DKA.txt`). Type 1 diabetes is an autoimmune condition, and children with one autoimmune disease carry an increased risk of others — **coeliac disease is the classic co-screened autoimmune association at diagnosis of type 1 diabetes**, tested for the same reason it is raised as part of the short-stature/screening workup elsewhere in this course. Screening at presentation (rather than waiting for symptoms) matters because coeliac disease can be asymptomatic or subtle in children and, left undetected, adds a second cause of poor growth and malabsorption on top of the new diabetes diagnosis.\n\nEach distractor is a **complication of established, longstanding** diabetes, not something screened for **at presentation**. *Diabetic retinopathy*, *diabetic neuropathy* and *diabetic nephropathy* are all microvascular complications that develop after years of hyperglycaemic exposure and are screened for periodically once diabetes is established, not at the point of first diagnosis in a previously well child. *Multiple endocrine neoplasia type 1* is a rare inherited tumour syndrome unrelated to type 1 diabetes\'s autoimmune associations and is not part of the standard diagnosis-time screen.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Coeliac disease should be screened for at the time of a new type 1 diabetes diagnosis, because both are autoimmune conditions that cluster together — unlike the microvascular complications, which are screened for only once diabetes is established.',
  source:'Pediatrics endpoint part1.pdf p.477'
},

{
  id:'pedep-gi-33', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 3-week-old breastfed baby has been referred by Emergency. His parents are very concerned because he has not opened his bowels for 3d. He has episodic screaming episodes which occur mostly in the evenings. He is the first baby of non-consanguineous parents. He was born at full term by emergency C-section dt prolonged 2nd stage of labor. There was meconium stained liquor. His APGARS were 9,10 and 10, and he was discharged home the next day. He is otherwise well and feeding well. What is the MOST likely diagnosis?',
  options:['Hirschsprung\'s disease','Infantile colic','Intussusception','Meckel\'s diverticulum','Pyloric stenosis'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Episodic evening crying in a well-fed, healthy infant with normal growth and no systemic symptoms is typical of colic; Hirschsprung\'s would show persistent constipation and abdominal distension.\n\n---\n\n*(Infantile colic itself is a clinical diagnosis of exclusion not covered in detail across the peds GI lectures — the reasoning below is drawn from general medical knowledge, not taken from the course material.)* This vignette is built to look concerning — not opening bowels for 3 days, and screaming episodes — but every detail that would normally raise alarm is deliberately reassuring: the baby is **otherwise well and feeding well**, had **excellent Apgars (9, 10, 10)** and an uncomplicated discharge, and the crying is specifically **episodic and evening-predominant**, the classic pattern of infantile colic (often described by the "rule of three": crying for more than 3 hours a day, more than 3 days a week, for more than 3 weeks, typically peaking in the evening, in an otherwise thriving infant). Three days without a stool in an exclusively breastfed infant is also not unusual — breastfed babies can have infrequent stools without this representing pathological constipation, since breast milk is very efficiently absorbed.\n\nEach distractor is undercut by a specific missing feature. *Hirschsprung\'s disease* would be expected to show **persistent, refractory constipation with abdominal distension** and typically a history from birth (delayed meconium), not a well, thriving baby with isolated evening crying — and here there is no mention of distension or a birth history of delayed meconium (the meconium-stained liquor mentioned is an intrapartum finding, unrelated to the baby\'s own bowel pattern). *Intussusception* causes acute paroxysmal colic with vomiting, lethargy, and eventually redcurrant-jelly stool — none of which is present in this well, feeding baby. *Meckel\'s diverticulum* classically presents with painless rectal bleeding, not with crying episodes and no stool. *Pyloric stenosis* causes progressive projectile vomiting, not isolated crying with normal feeding.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Episodic, evening-predominant crying in an otherwise well, thriving, well-feeding infant with no distension, vomiting or bleeding is infantile colic, a diagnosis of exclusion.',
  source:'Pediatrics endpoint part1.pdf p.479'
},

{
  id:'pedep-gi-34', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'A 5-week infant was brought by intractable vomiting and weight loss over the last 2 weeks. He was dehydrated, and his weight was 3 kg on feeding, visible gastric peristalsis was seen, and projectile non-bilious vomiting occurred. Abdominal examination reveals a palpable mass. The MOST suitable study for diagnosis is:',
  options:['Plain x ray','abdomen US','Barium enema','Serum electrolytes levels','Esophageal monitoring'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Classic presentation of pyloric stenosis; ultrasound is the diagnostic test of choice for measuring pyloric muscle thickness.\n\n---\n\nThis is the same diagnosis as `pedep-gi-10`, `pedep-gi-17` and `pedep-gi-25`, this time asked as the confirmatory investigation. `22)Vomiting.txt` describes the diagnostic triad the physical exam adds here: **visible gastric peristalsis** (waves moving left to right across the upper abdomen as the stomach tries to force contents past the obstructed pylorus), a **palpable "olive" mass** (the hypertrophied pyloric muscle), and **projectile non-bilious vomiting** with dehydration and weight loss over 2 weeks. **Abdominal ultrasound** is the diagnostic test of choice because it directly measures **pyloric muscle thickness and canal length**, is non-invasive, avoids radiation, and can be performed at the bedside without sedation — ideal in a young, dehydrated infant.\n\nEach distractor is either non-specific or the wrong tool. *Plain X-ray* may show a distended, gas-filled stomach as a non-specific sign but cannot measure the pyloric muscle itself or confirm the diagnosis. *Barium enema* images the colon and is used for lower GI pathology such as Hirschsprung\'s disease, not an upper GI outlet obstruction. *Serum electrolyte levels* are essential for assessing the metabolic consequence (hypochloraemic, hypokalaemic metabolic alkalosis, `pedep-gi-17`) and guiding rehydration before surgery, but they do not establish the anatomical diagnosis. *Oesophageal monitoring* (pH studies) investigates gastro-oesophageal reflux, a different and much milder condition than this vignette\'s palpable mass and visible peristalsis.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Abdominal ultrasound, measuring pyloric muscle thickness directly, is the diagnostic investigation of choice for pyloric stenosis.',
  source:'Pediatrics endpoint part1.pdf p.481'
},
