/* Peds endpoint PART 2, section 14 "Model Final Exam 3", half B: n53,55,60,63,64,66,67,68,73,
   74,75,78,79. Drafted from PEDEP2_S14_STAGED against endpoint-p2-s14-drafting-notes.md and
   endpoint-p2-s14-chapter-rulings.md. */
var PEDEP2_S14_MFE3_DRAFT_B = [

{
  id:'pedep2-mf3-53', bank:'endpoint', module:'pediatrics', chapter:'neuro-cp',
  stem:'Cerebral diplegia is a common consequence of which cerebral damage?',
  options:['Perinatal hypoxic-ischemic encephalopathy','Genetic brain disorders','Structural brain anomalies','Kernicterus','Periventricular area damage in preterm babies'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Spastic diplegia is commonly caused by injury to the periventricular white matter in premature infants.\n\n---\n\nneuro-28\'s clinical-types table names the exact pattern the key describes: bilateral spastic diplegia is common in prematurity, the legs are more affected than the arms, and the table closes by calling diplegia "the premature baby\'s pattern." per-10 supplies the lesion itself — periventricular leukomalacia, ischaemic white matter injury seen on cranial ultrasound in about 3% of very-low-birth-weight infants, alongside intraventricular haemorrhage from the fragile germinal-layer vessels. Prematurity and low birth weight are neuro-27\'s two most important CP risk factors, which is why this pattern is so strongly tied to the preterm brain rather than to a term insult.\n\nThe stem\'s own vocabulary is worth flagging: neuro-28 states in the same breath that "topographic categorization into hemiplegia, quadriplegia and diplegia is NO LONGER USED" in favour of the SCPE classification, even though its own clinical-types table keeps using diplegia to describe this exact pattern. The current name for what this question calls cerebral diplegia is bilateral spastic cerebral palsy; the key is answered in the bank\'s own (retired) vocabulary and is not disputed.\n\nEach distractor points at a different clinical type on the same table. Perinatal hypoxic-ischemic encephalopathy and kernicterus both sit under the dyskinetic pattern — perinatal asphyxia or kernicterus causing basal-ganglia injury and involuntary movements — not the periventricular, legs-worse-than-arms pattern the stem describes. Genetic brain disorders and structural brain anomalies are both real contributors to cerebral palsy in general (neuro-27\'s cause is identified in only 50% of cases, and cortical migration disorders and congenital CNS malformations are named prenatal risk factors), but neither is the specific, well-recognised mechanism linking prematurity to this particular clinical pattern the way periventricular damage is.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Bilateral spastic diplegia — legs more affected than arms — is the premature baby\'s pattern, caused by periventricular white-matter injury; the current classification calls it bilateral spastic cerebral palsy rather than "diplegia", but the bank keys the question in its own retired vocabulary.',
  source:'Pediatrics endpoint part2.pdf p.1701'
},

{
  id:'pedep2-mf3-55', bank:'endpoint', module:'pediatrics', chapter:'haematology',
  stem:'Which of the following viruses commonly causes aplastic crisis in a patient with sickle cell disease?',
  options:['Roseola','Parvovirus B19','Coxsackie A16','Echovirus 11','Cytomegalovirus'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Parvovirus B19 infects erythroid precursors, causing temporary aplastic crisis in patients with chronic hemolysis like sickle cell disease.\n\n---\n\ninf-30 gives the mechanism the box compresses: parvovirus B19 replicates in erythroid progenitor cells in the marrow, and it is flagged there as the explanation for both of the virus\'s dangerous complications — aplastic crisis in sickle cell disease and thalassaemia, and fetal hydrops in pregnancy. haem-8\'s table of anaemia causes places parvovirus B19 under "impaired production, red cell aplasia," and haem-22 lists it again among aplastic anaemia\'s acquired viral causes alongside hepatitis and CMV, so the same virus is anchored from two directions in the corpus.\n\nThis question shares its disease and its underlying fact with `pedep2-hem-65`, but not its option menu, and the two must not be folded into one. `pedep2-hem-65` asks for the most common cause of aplastic crisis and offers a menu of causes — dehydration, RSV, parvovirus B19, repeated transfusion, Haemophilus septicaemia — only one of which is a virus. This question restricts the menu to five viruses and asks which one does it, with the key moving to index 1 rather than 2. The discriminating step here is virus-versus-virus, not cause-versus-cause.\n\nOf the four wrong viruses, none is described anywhere in the corpus as marrow-suppressive. Roseola (human herpesvirus 6) and coxsackie A16 and echovirus 11 are exanthem/enterovirus infections without a described erythroid-progenitor tropism; cytomegalovirus is named in haem-22\'s aplastic-anaemia list as one cause among several viruses, but it is not the one the deck ties specifically to sickle cell disease\'s chronic haemolytic state — parvovirus B19 is the named partner for that pairing throughout the corpus.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Parvovirus B19 replicates in bone-marrow erythroid progenitor cells, shutting down red cell production; in a child already destroying red cells fast (sickle cell disease, thalassaemia) that halt in production produces a life-threatening aplastic crisis.',
  source:'Pediatrics endpoint part2.pdf p.1705'
},

{
  id:'pedep2-mf3-60', bank:'endpoint', module:'pediatrics', chapter:'renal',
  stem:'On receiving the result of a urine analysis of a child, which finding will support the diagnosis of glomerulonephritis?',
  options:['Leukocyte esterase','White blood cells','Normal protein/creatinine ratio','Casts','Bacteria'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Casts in urine indicate glomerular origin, supporting a diagnosis of glomerulonephritis.\n\n---\n\nren-7\'s glomerular-versus-extra-glomerular table names this outright: RBC casts are pathognomonic of glomerular origin, set directly against extra-glomerular bleeding, where casts are absent. ren-9 and ren-10 give the disease this points to — acute post-streptococcal glomerulonephritis, the commonest cause of acute nephritic syndrome in children, whose urinalysis shows rusty or tea-coloured urine with dysmorphic RBCs, RBC casts and sterile pyuria alongside proteinuria.\n\nThe other four options all describe the extra-glomerular, lower-urinary-tract picture ren-7\'s table sets against the glomerular one. Leukocyte esterase, white blood cells and bacteria are the standard urinalysis triad for a urinary tract infection, which ren-7 lists as a history and examination pointer toward the tract rather than the kidney. A normal protein/creatinine ratio would argue against glomerulonephritis rather than for it: ren-7 states that protein above 100 mg/dL indicates glomerular origin, and ren-9 records that proteinuria is part of the APSGN picture, so a normal ratio is the wrong direction for this diagnosis.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'RBC casts on urinalysis are pathognomonic of glomerular bleeding; leukocyte esterase, white cells, bacteria and a normal protein/creatinine ratio all point toward the lower urinary tract or away from glomerular disease instead.',
  source:'Pediatrics endpoint part2.pdf p.1715'
},

{
  id:'pedep2-mf3-63', bank:'endpoint', module:'pediatrics', chapter:'haematology',
  stem:'What will be the next step in a child presenting with anemia and microcytosis?',
  options:['Reticulocyte count','Hb electrophoresis','Serum ferritin test','Sickling test','Serum folic acid'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Microcytic anemia is most commonly due to iron deficiency; serum ferritin is the most specific test to confirm low iron stores.\n\n---\n\nhaem-10\'s classification-by-MCV table lists iron deficiency, thalassaemia, lead poisoning and chronic disease under the microcytic column, and warns that chronic disease sits in two columns at once — which is exactly why MCV alone never settles the diagnosis and a further test is needed. haem-18 supplies the iron-study picture that confirms iron deficiency once ferritin is checked: decreased ferritin, decreased serum iron, raised TIBC and decreased transferrin saturation, alongside the CBC picture of low Hb, low MCV, low MCH and raised RDW.\n\n**A tension worth naming, not hiding:** haem-18 does not rank ferritin as the next investigative step. It states that diagnosis rests on three things — clinical findings, laboratory findings, and a therapeutic trial of oral iron, which it calls "the BEST diagnostic study," judged by improvement in neurological function within 24-48 hours and reticulocytosis by 48-72 hours. Ranking serum ferritin ahead of a therapeutic trial as the single next step is *not taken from the course material* — the material sources the iron-deficiency work-up in full but does not order its components against each other, and the key stands as printed regardless.\n\nThe distractors sit elsewhere on haem-10\'s own map. Reticulocyte count characterises production versus destruction rather than iron status specifically. Hb electrophoresis and the sickling test investigate haemoglobinopathies (thalassaemia, sickle cell disease) rather than iron deficiency, and would only be reached for if the iron studies came back normal. Serum folic acid investigates a macrocytic, not microcytic, process on the same table.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Serum ferritin confirms iron deficiency as the cause of a microcytic anaemia; the material does not itself rank ferritin ahead of a therapeutic iron trial as the specific next step, but both belong to the same iron-deficiency work-up the key targets.',
  source:'Pediatrics endpoint part2.pdf p.1721'
},

{
  id:'pedep2-mf3-64', bank:'endpoint', module:'pediatrics', chapter:'renal-cakut',
  stem:'Bilateral hydroureters and hydronephrosis may result from which type of urinary tract obstruction?',
  options:['Pelviureteric junction obstruction','Left vesicoureteric junction obstruction','Posterior urethral valve','Bilateral renal pelvis stones'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Bilateral hydronephrosis and hydroureters in a male infant often indicate a lower urinary tract obstruction, most commonly posterior urethral valves.\n\n---\n\nren-15 states posterior urethral valve occurs in males only and causes bladder outlet obstruction, presenting antenatally as bilateral hydronephrosis with a distended bladder in a male fetus, and postnatally with failure to pass urine, a poor stream, or urinary tract infections; up to 30% go on to end-stage or chronic renal insufficiency. Because the obstruction sits at the bladder outlet — downstream of both ureters — the backpressure is transmitted up both collecting systems at once, which is what makes the finding bilateral. ren-16 adds that MCUG is mandatory in males with bilateral hydronephrosis to confirm it, though ultrasound comes first.\n\nEach wrong option obstructs only one side of the tract. Pelviureteric junction obstruction is ren-15\'s single commonest obstructive lesion in childhood, but it sits at the renal pelvis of one kidney (about 60% left-sided, only 10% bilateral) and produces unilateral hydronephrosis without hydroureter, because the block is above the ureter, not below it. Left vesicoureteric junction obstruction is explicitly one-sided by name. Bilateral renal pelvis stones would need to be bilateral by chance rather than by the anatomy of a single obstructing lesion, and urolithiasis is not among the CAKUT obstructive lesions ren-15 or ren-14 names.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Posterior urethral valve sits at the bladder outlet, downstream of both ureters, so it is the obstruction that produces bilateral hydroureter and hydronephrosis; PUJ obstruction and unilateral VUJ obstruction each affect only one kidney\'s drainage.',
  source:'Pediatrics endpoint part2.pdf p.1723'
},

{
  id:'pedep2-mf3-66', bank:'endpoint', module:'pediatrics', chapter:'cardiac',
  stem:'A one-week-old infant is in shock because of a congenital heart disease. Which of the following is the most likely cause?',
  options:['ASD','VSD','Coarctation','Fallot Tetralogy','PDA'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Critical coarctation of the aorta often causes shock in newborns when the ductus arteriosus closes, reducing blood flow to the body.\n\n---\n\ncard-9 describes exactly this course: examination on the first day of life is usually normal because the duct is still feeding the descending aorta, then acute circulatory collapse follows a few days later when the duct closes, presenting as a sick baby with severe heart failure, absent femoral pulses and severe metabolic acidosis. This is duct-dependent systemic circulation — the descending aorta depends on right-to-left flow across the duct — and card-9\'s own table sets critical coarctation alongside interrupted aortic arch and hypoplastic left heart as the three duct-dependent, left-heart-obstruction lesions that collapse the same way once the duct closes, distinguished from one another only by which pulses remain.\n\ncard-1\'s six-group classification places the other four options in categories that do not present as first-week shock. ASD, VSD and PDA are left-to-right shunt lesions, presenting as breathlessness or being asymptomatic rather than shock — and card-1 notes VSD is in fact the commonest CHD overall, which is why it is a tempting distractor here, but a large VSD declares itself with heart failure over weeks, not collapse in the first week. Tetralogy of Fallot is card-1\'s right-to-left shunt group, presenting as cyanosis (it is the commonest cyanotic lesion after age 1), not the acidotic, pulseless collapse this stem describes.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Critical coarctation is duct-dependent for the systemic circulation; the baby looks well until the duct closes, then collapses with absent femoral pulses and acidosis — a pattern the left-to-right shunts and Fallot tetralogy do not produce in the first week.',
  source:'Pediatrics endpoint part2.pdf p.1727'
},

{
  id:'pedep2-mf3-67', bank:'endpoint', module:'pediatrics', chapter:'liver-hep',
  stem:'Which nutritional problem do children with chronic liver disease suffer from?',
  options:['Defective absorption of medium-chain fatty acids','Defective absorption of long-chain fatty acids','Increased absorption of cholesterol','Improper digestion of proteins','Defective absorption of folic acid and vitamin B'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Chronic liver disease affects bile production and fat absorption, leading to deficiency of fat-soluble vitamins and long-chain fatty acids.\n\n---\n\nliv-15 names the nutritional complication of chronic liver disease as malnutrition, fat-soluble vitamin deficiency and pruritus. **The specific mechanism the key names — that it is long-chain fatty acids that fail to absorb — is not itself taught: "long-chain" returns zero hits anywhere in the corpus** (*not taken from the course material*). What is sourced is the reason it happens: liver disease reduces bile salt delivery to the gut, and long-chain fatty acids need bile salts to form micelles before they can be absorbed, so they are malabsorbed together with the fat-soluble vitamins A, D, E and K that travel the same route — the deficiency liv-15 does teach. liv-9\'s management section for a related cholestatic liver problem confirms the fix from the other end: a medium-chain triglyceride formula is used precisely because medium-chain fats are absorbed without needing bile salts, which is the one corpus hit for "medium-chain" and the mirror image of why long-chain fats are the ones that fail.\n\n**Distractor overlap to flag:** liv-15 itself prints "fat-soluble vitamin deficiency" as the complication, so if a menu offered that as an option instead of long-chain fatty acids it would be the sourced answer — here it is not offered, and the key targets the fat malabsorption mechanism, not its vitamin consequence. Increased cholesterol absorption is the opposite direction of the true defect. Improper protein digestion is not a complication liv-15 names for CLD. Folic acid and vitamin B are water-soluble and are not linked to bile-salt-dependent absorption at all — the deficient vitamins in CLD are specifically the fat-soluble ones.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Chronic liver disease reduces bile salt delivery, so long-chain fatty acids (needing micelles) and the fat-soluble vitamins A, D, E and K malabsorb together; medium-chain triglycerides, absorbed without bile salts, are what a therapeutic formula substitutes.',
  source:'Pediatrics endpoint part2.pdf p.1729'
},

{
  id:'pedep2-mf3-68', bank:'endpoint', module:'pediatrics', chapter:'neuro-nm',
  stem:'What is the emergency (acute) investigation in a case of Guillain-Barré syndrome?',
  options:['MRI of the spinal cord/brain','Acute phase reactant measurement','CPK blood level','EMG (electromyogram)','Nerve biopsy'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> In acute Guillain-Barré syndrome, EMG can detect demyelination or conduction block, aiding in early diagnosis.\n\n---\n\n**This key is not supported by the material, and the disagreement is recorded here without disputing it.** neuro-21 names three investigations for Guillain-Barré syndrome — CSF showing protein-cell dissociation (raised protein, normal cell count), nerve conduction studies showing reduced velocities, and MRI of the spinal cord to show nerve root enhancement and exclude other spinal lesions — and does not print "EMG" anywhere. A corpus-wide check for "EMG" returns three hits (`neuro-19`, `neuro-25`, `nns-13`), none of them about Guillain-Barré. Nor does neuro-21 rank any of its three investigations as specifically the acute one.\n\nWhat can be said honestly, and is the closest the material comes to the key: electromyography and nerve conduction studies are the two halves of one electrophysiological examination of peripheral nerve and muscle — EMG records the muscle\'s electrical activity, nerve conduction studies measure how fast a signal travels along the nerve — so a clinician ordering "nerve conduction studies" is very often performing an EMG/NCS study as a single test. That the ranking of it as the *acute* investigation is asserted rather than taught is *not taken from the course material*.\n\nOf the remaining distractors: MRI of the spinal cord is one of neuro-21\'s three genuine investigations, just not (per this key) the acute one. Acute phase reactants and CPK are non-specific — CPK points toward a muscle disease (myopathy) rather than a demyelinating neuropathy, and neither is named for GBS anywhere in the corpus. Nerve biopsy is not a GBS investigation at all in the material; GBS is diagnosed clinically and electrophysiologically, not histologically.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'The course teaches CSF protein-cell dissociation, nerve conduction studies and spinal MRI as the three investigations for Guillain-Barré syndrome, and does not name EMG or rank any of the three as the acute one; the printed key is recorded as printed, not disputed.',
  source:'Pediatrics endpoint part2.pdf p.1731'
},

{
  id:'pedep2-mf3-73', bank:'endpoint', module:'pediatrics', chapter:'renal-cakut',
  stem:'What would be the initial management of a newborn with an antenatal diagnosis of a urinary tract anomaly?',
  options:['Collect urine for culture immediately after birth','Cord blood sample for serum electrolytes','Start prophylactic antibiotics','Give an appointment after one month for ultrasonographic assessment'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Newborns with antenatally detected urinary tract anomalies may need prophylactic antibiotics to prevent infection until further evaluation.\n\n---\n\nren-16 does teach prophylactic antibiotics as part of postnatal management of CAKUT, naming trimethoprim or nitrofurantoin, and ren-15 confirms MCUG is mandatory in a male with bilateral hydronephrosis once imaging has stratified the risk. **What is not sourced as printed is starting prophylaxis as the very first step, before any imaging** (*not taken from the course material*): ren-16\'s own indication for prophylactic antibiotics is narrower and later — "high-grade VUR or obstructive uropathy with recurrent infections" — a state that is only known once ultrasound (and, where indicated, MCUG) has characterised the anomaly, not the day-one management of a newborn whose anomaly is still only an antenatal finding. ren-16 is explicit that renal ultrasound is first-line for exactly this situation: it gives kidney size, corticomedullary differentiation and system dilatation non-invasively, whereas ultrasound findings alone give anatomy, not function.\n\nStill, of the four printed options, prophylactic antibiotics is the one that matches the corpus\'s general theme for antenatally detected anomalies — covering the infant against infection while the anomaly is worked up — better than any alternative. Collecting urine for culture immediately after birth has no basis without a suspected infection already present. A cord blood electrolyte sample measures placental, not the neonate\'s own, renal function at that moment, and ren-16\'s functional test is plasma creatinine and electrolytes taken from the baby, not the cord. Waiting a full month for the first ultrasound contradicts ren-16\'s own ranking of renal ultrasound as the first-line, prompt investigation for CAKUT.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'CAKUT management starts with a renal ultrasound and reserves prophylactic antibiotics for high-grade VUR or obstructive uropathy with recurrent infection; the material does not itself teach prophylaxis as the very first newborn step, but of the options offered it is the sourced theme that fits best.',
  source:'Pediatrics endpoint part2.pdf p.1741'
},

{
  id:'pedep2-mf3-74', bank:'endpoint', module:'pediatrics', chapter:'infection-bact',
  stem:'Anti-Streptolysin O titer (ASOT) is a specific diagnostic test for which of the following?',
  options:['Rheumatic fever','Rheumatic heart disease','Acute glomerulonephritis','Recent group A streptococcal infection'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> ASOT measures antibodies against streptolysin O, indicating recent infection with group A streptococcus.\n\n---\n\nren-9 states the mechanism directly: nephritogenic group A beta-haemolytic streptococci provoke antibodies to streptococcus (anti-streptolysin O) in the circulation, which is what ASOT detects. card-18 adds the same fact from the rheumatic-fever side — the ASO test is a high anti-streptolysin O antibody titre against streptolysin O, the streptococcal antigen — and notes the titre behaves as a curve, rising from infection and peaking near 800-900 units before falling back over roughly a year, so a single reading dates a recent infection only loosely.\n\n**The word doing the work in this stem is "specific," and it is worth naming why the other three options are wrong rather than merely different.** ASOT rises after any recent group A streptococcal infection — it cannot by itself tell which downstream disease, if any, will follow. Rheumatic fever, rheumatic heart disease and acute glomerulonephritis are three of that infection\'s possible sequelae, not the thing ASOT actually measures: ren-9 and ren-10 teach ASOT as evidence of the preceding streptococcal trigger for APSGN, and card-18 teaches it the same way for rheumatic fever, in both cases as one supporting piece of a larger diagnosis built from the clinical picture (the Jones criteria, or the nephritic syndrome and latent period), never as a test that is itself diagnostic of the sequela. A raised titre is compatible with all three, or with none of them if the infection resolved without complication — which is exactly why the key excludes all three and lands on the infection itself.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A raised ASOT is evidence only of a recent group A streptococcal infection; it cannot distinguish rheumatic fever, rheumatic heart disease and acute glomerulonephritis from each other or from an infection that caused none of them, which is why none of the three sequelae is the "specific" answer.',
  source:'Pediatrics endpoint part2.pdf p.1743'
},

{
  id:'pedep2-mf3-75', bank:'endpoint', module:'pediatrics', chapter:'neurological',
  stem:'Which of the following principles is true regarding the use of antiepileptic drugs (AEDs) in children?',
  options:['Monotherapy to prevent seizures is the goal','Initial combined drug therapy to prevent seizures is preferred','AEDs are continued indefinitely','AED therapy may be tapered and stopped after 6 months free of seizures','AEDs are contraindicated in infants'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> In children, single-drug therapy is preferred to minimize side effects and simplify management.\n\n---\n\nneuro-13 lists six principles of AED use in one place, and this question, `pedep2-neu-28` and `pedep2-neu-32` each key a different one of them — three separate questions built from the same short list, none of them a fold of the others. This entry\'s own key, monotherapy before polytherapy, is neuro-13\'s third principle. `pedep2-neu-28` keys the fourth principle instead — that all AEDs have potential unwanted effects — and `pedep2-neu-32` keys a stopping-rule principle, that not all cases need treatment (echoed in neuro-13\'s own note that therapy may be discontinued after seizure freedom, but should usually continue indefinitely in juvenile absence or juvenile myoclonic epilepsy). The three share a subject and a source section but turn on three different sentences of it, which is why each earns its own entry.\n\nThe remaining distractors here invert or overstate neuro-13\'s own principles. Initial combined drug therapy is the opposite of "monotherapy before polytherapy." Continuing AEDs indefinitely overstates neuro-13\'s stopping rule, which allows discontinuation after two years free of seizures in most epilepsies (this stem prints six months, a shorter and unsupported figure, but the option is wrong on the "indefinitely" claim regardless). AEDs being contraindicated in infants is not a principle neuro-13 states; vigabatrin, for instance, is named there as the mainstay for infantile spasms specifically.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Monotherapy before polytherapy is one of six AED principles the material teaches; `pedep2-neu-28` and `pedep2-neu-32` key two of the other five from the same list, which is why three questions exist rather than one.',
  source:'Pediatrics endpoint part2.pdf p.1745'
},

{
  id:'pedep2-mf3-78', bank:'endpoint', module:'pediatrics', chapter:'endocrine',
  stem:'What is the etiology of type 1 DM?',
  options:['Obesity','Viral destruction of pancreatic beta cells','Gestational diabetes','Autoimmune process affecting the beta cells of the pancreas','Drug-induced'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Type 1 diabetes results from autoimmune destruction of insulin-producing beta cells.\n\n---\n\nendo-2 gives the mechanism in full: autoimmune destruction of pancreatic beta cells in genetically susceptible individuals, especially those carrying particular HLA genes, with environmental triggers such as viral infections (enterovirus is named) able to start the autoimmune process rather than destroy the cells directly. That progressive destruction leads to absolute insulin deficiency, which endo-2 traces step by step into the DKA cascade — reduced glucose utilisation, rising counter-regulatory hormones, lipolysis and ketogenesis, protein breakdown and osmotic diuresis. endo-1\'s classification grid confirms the mechanism column for type 1 diabetes reads exactly this way and notes it accounts for over 90% of paediatric diabetes.\n\nEach distractor names a mechanism endo-1\'s grid assigns to a different category. Obesity is the named example under type 2 diabetes\'s insulin-resistance mechanism, not type 1\'s beta-cell destruction. "Viral destruction" mischaracterises the role of a viral trigger — endo-2 is explicit that viruses may start the autoimmune process, not act as a direct cytolytic cause, so this option gets the mechanism itself wrong even though a virus is genuinely involved. Gestational diabetes is not listed anywhere on endo-1\'s grid as a paediatric type 1 mechanism. Drug-induced diabetes is endo-1\'s own separate category, driven by insulin resistance or reduced secretion from agents such as steroids or antipsychotics — a distinct entity from the autoimmune process this question asks about.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Type 1 diabetes is autoimmune destruction of pancreatic beta cells in a genetically susceptible child, with viral infection able to trigger rather than directly cause the process; obesity, gestational diabetes and drug-induced diabetes each belong to a different mechanism on the same classification grid.',
  source:'Pediatrics endpoint part2.pdf p.1751'
},

{
  id:'pedep2-mf3-79', bank:'endpoint', module:'pediatrics', chapter:'neurological',
  stem:'What does the term "seizure" mean?',
  options:['A paroxysmal abnormality of motor, sensory or autonomic function due to transient brain dysfunction','An abnormal electric activity of the brain','A transient brain dysfunction with more components','A brain disorder that predisposes to epilepsy','An acute brain injury'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> A seizure is a sudden, temporary disturbance in brain function causing abnormal movements, sensations, or behavior.\n\n---\n\nneuro-6 defines an epileptic seizure as abnormal excessive neuronal electrical activity in the brain, producing sudden onset and offset, transient recurrent neurological symptoms and/or signs, and states the localising principle behind that: the site of origin of the abnormal firing determines the symptoms produced — a motor cortex focus gives a motor seizure. The key\'s wording, "a paroxysmal abnormality of motor, sensory or autonomic function due to transient brain dysfunction," is the same substance in different language: "paroxysmal" restates "sudden onset and offset," "due to transient brain dysfunction" restates the abnormal electrical activity, and the motor/sensory/autonomic triad is exactly what the localising principle predicts — the abnormal firing can show up as movement, sensation, or an autonomic sign depending on where it starts. The word "autonomic" is not left to inference: neuro-6\'s own older-ILAE list names simple partial seizures as producing "motor, sensory, autonomic or psychic signs" with consciousness preserved, so all three terms in the key are directly attested.\n\nEach distractor drops or distorts one clause of that definition. "An abnormal electric activity of the brain" names the mechanism but drops the clinical consequence — a seizure is defined by producing symptoms or signs, not by the electrical activity alone (which can be subclinical). "A transient brain dysfunction with more components" is vague to the point of not specifying what those components are, unlike the key\'s named triad. "A brain disorder that predisposes to epilepsy" describes something else entirely — that is closer to neuro-5\'s aetiological causes of seizures (structural or metabolic brain disorders) than to the definition of a single seizure event, and epilepsy itself is neuro-6\'s separate definition of two or more unprovoked seizures. "An acute brain injury" is one of neuro-5\'s structural insults that can *cause* an acute symptomatic seizure, not a definition of what a seizure is. neuro-5 also supplies what is not a seizure at all — convulsive syncope from an arrhythmia, breath-holding spells, vasovagal syncope — the differential this definition question sits beside.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A seizure is a sudden, transient episode of motor, sensory or autonomic dysfunction caused by abnormal brain electrical activity, localised by where that activity starts; the mechanism alone, a vague "dysfunction," a predisposing disorder and a causal brain injury are each a different, related concept rather than the definition itself.',
  source:'Pediatrics endpoint part2.pdf p.1753'
}

];
