/* Section 3 "Genetics" (Pediatrics endpoint part2.pdf), HALF B of the draft pass.
   Drafted from content/peds/qb-pages/endpoint-p2-s03-genetics.array.js (PEDEP2_S03_STAGED),
   entries n:16 through n:27 only (staging n:16 sits in HALF A of the staging record; n:17-27
   sit in HALF B of the staging record -- the staging split does not line up with this draft
   split, and that is expected). Id prefix pedep2-gen- per val-pd-ep2.js SEC[3]. */
var PEDEP2_GEN_DRAFT_B = [

{
  id: 'pedep2-gen-16',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'Mr. and Mrs. David are seen by the geneticist as their baby, Sarah, has Down syndrome. Her chromosomes are examined, and three copies of chromosome 21 are seen, one of which is attached to chromosome 14. How would you describe this abnormality?',
  options: ['Balanced Robertsonian translocation','Mosaicism','Nondisjunction','Triplet repeat expansion','Unbalanced Robertsonian translocation'],
  answer: 4,
  explanation: "**The endpoint file prints this explanation:**\n\n> This chromosomal rearrangement causes an extra copy of chromosome 21 material, leading to Down syndrome.\n\n---\n\nSarah already has a live extra dose of chromosome-21 material -- three effective copies, one of them fused onto chromosome 14 -- and any baby with three copies of 21 has trisomy 21 regardless of how the extra copy is packaged, which is why this is an **unbalanced** Robertsonian translocation. `6) Genetically determined disease_.txt` draws exactly this line: a **balanced** translocation carries no net loss or gain of genetic material -- the carrier has the normal total dose of every gene, just repackaged onto fewer, larger chromosomes -- and such a carrier is phenotypically normal; an **unbalanced** translocation carries an incorrect amount of chromosomal material and produces the dysmorphic, developmentally-delayed phenotype described here. A parent who carries a balanced 21;14 translocation is themselves unaffected and typically comes to attention only after a child like Sarah is born with the unbalanced form -- which is why **balanced Robertsonian translocation** is wrong: Sarah is the clinically affected individual, not the silent carrier.\n\nThe other two mechanisms fail for a different reason -- neither one fuses chromosome 21 onto anything. **Nondisjunction** is the commonest cause of trisomy 21 (about 94% of cases, per the same lecture) but it produces three *free-standing* copies of chromosome 21 from a meiotic segregation error; there is no attachment to chromosome 14 at all. **Mosaicism** means two genetically distinct cell lines coexist in the same person -- some cells with the normal 46 chromosomes and some with 47 -- arising from a mitotic error after fertilisation; again, nothing here describes two cell lines, and mosaicism does not involve a fusion to chromosome 14 either. **Triplet repeat expansion** is an unrelated mechanism altogether: it lengthens a repeated DNA sequence inside a single gene (as in fragile X syndrome or myotonic dystrophy) and causes disease through an abnormal transcript or protein, not through gaining a whole extra chromosome.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'A baby born with Down syndrome from a chromosome-21/14 fusion has an unbalanced Robertsonian translocation, because the affected child necessarily carries a net gain of chromosome-21 material; only a phenotypically normal parent can be the balanced carrier.',
  source: 'Pediatrics endpoint part2.pdf p.199'
},

{
  id: 'pedep2-gen-17',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'Olive is a 10-day-old baby with Down syndrome. On examination, you hear a loud heart murmur. What is the most likely cause?',
  options: ['Aortic stenosis','Atrioventricular septal defect','Coarctation of the aorta','Innocent murmur','Patent ductus arteriosus'],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> This is the most common cardiac defect in Down syndrome, resulting from endocardial cushion defects.\n\n---\n\n`6) Genetically determined disease_.txt` lists congenital heart defects in roughly 40% of babies with Down syndrome, and the cardiac lecture names the specific lesion: `33)Congenital acyanotic heart disease_.txt` states plainly that atrioventricular septal defect (AVSD, also called AVCD or endocardial cushion defect) is \"common in Down syndrome\", describing it as a single five-leaflet common valve stretching across the whole atrioventricular junction that tends to leak, with a large shunt and high pulmonary artery pressure -- which is exactly the loud murmur Olive presents with in the first days of life, before the heart-failure picture (typically appearing between 2 weeks and 3 months, per the same slide) has had time to develop.\n\n**Why the other four fail.** Aortic stenosis and coarctation of the aorta are recognised congenital heart lesions but are not the defect specifically associated with Down syndrome's endocardial-cushion abnormality; coarctation is the lesion classically linked to Turner syndrome instead. An innocent murmur is, by definition, a murmur with no underlying structural defect -- it does not explain a *loud* murmur in a baby already known to carry the chromosomal abnormality with the highest rate of structural heart disease. Patent ductus arteriosus is common in preterm infants and can occur in Down syndrome too, but it is not the lesion the material singles out as characteristic of trisomy 21 the way AVSD is -- AVSD is the one condition the cardiac lecture explicitly ties back to Down syndrome by name.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Atrioventricular septal defect is the cardiac lesion characteristically linked to Down syndrome, arising from a failure of endocardial cushion fusion, and it should top the differential for a murmur in a newborn with trisomy 21.',
  source: 'Pediatrics endpoint part2.pdf p.201'
},

{
  id: 'pedep2-gen-18',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'Fiona is a well 4-year-old girl with Down syndrome. She attends her yearly follow-up appointment with her mother. There are no real problems other than constipation, for which her general practitioner has started treatment. When you plot Fiona on the Down syndrome growth chart, you notice that her height has dropped from the 75th centile to the 25th centile. Her weight, however, has increased from the 50th to the 75th centile. Which of the following investigations would you perform?',
  options: ['Coeliac screen','Abdominal ultrasound','Full blood count','Thyroid function tests'],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Children with Down syndrome are at increased risk for hypothyroidism, which can cause growth deceleration and weight gain.\n\n---\n\nFiona's pattern -- falling height centiles with *rising* weight centiles, plus new constipation -- is the classic combination for acquired hypothyroidism, not simple faltering growth (where weight and height usually fall together). `6) Genetically determined disease_.txt` lists an increased risk of hypothyroidism (about 15%) among the later clinical problems of Down syndrome, on top of the baseline hypotonia and developmental issues present from birth, which is why annual thyroid function testing is part of the routine follow-up of every child with trisomy 21, symptomatic or not.\n\n**Why each distractor fails.** Coeliac disease is also increased in Down syndrome and can cause growth deceleration, but coeliac disease drives weight *down* with the height, through malabsorption -- it does not explain Fiona's weight *gain*, which points to a metabolic slowdown rather than a malabsorptive process. Abdominal ultrasound has no defined role in an otherwise well child with isolated constipation and a growth-chart change; it would be reached for only if there were a mass, organomegaly or an acute abdomen, none of which is described. A full blood count would be reasonable if leukaemia or anaemia were suspected, but nothing here suggests a haematological process -- Fiona is well, and her growth pattern fits an endocrine, not a marrow, problem.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'A Down syndrome child who is falling in height centiles while rising in weight centiles, especially with new constipation, should be screened with thyroid function tests for acquired hypothyroidism, which is screened for routinely in this group.',
  source: 'Pediatrics endpoint part2.pdf p.203'
},

{
  id: 'pedep2-gen-19',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'Mary is an infant with Down syndrome. Her antenatal scans were normal, and an echocardiogram in the neonatal unit shortly after birth was also normal. She attends the community clinic at 4 weeks of age, thriving and feeding well. Her parents have many questions about future risks. Which condition is Mary at increased risk of developing compared to the general population?',
  options: ['Congenital heart disease','Duodenal atresia','Ischaemic heart disease','Leukaemia','Pyloric stenosis'],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Children with Down syndrome have a significantly increased risk of developing acute lymphoblastic and myeloid leukemia.\n\n---\n\n`6) Genetically determined disease_.txt` lists \"increased risk of leukemia and solid tumors\" among the later problems that follow a child with Down syndrome through life, distinct from the anomalies (heart disease, duodenal atresia) that are usually already present or excluded at, or soon after, birth. Mary's own echocardiogram is already normal, which is exactly why congenital heart disease is not the answer here: it is a risk that has already been assessed and cleared for her specifically, whereas leukaemia is a risk that persists and only becomes relevant with time -- the vignette is built so that the two heart-related distractors are ruled out by Mary's own normal work-up, not just by general reasoning.\n\n**Why the remaining distractors fail.** Duodenal atresia is a congenital structural anomaly that, if present, causes bilious vomiting in the first days of life; a well, thriving 4-week-old with normal antenatal scans has already passed the window where it would present. Ischaemic heart disease is not a recognised association of Down syndrome at all -- the cardiac risk in this group is structural (congenital) disease, not atherosclerotic disease. Pyloric stenosis is unrelated to the chromosomal abnormality; it is not a feature the material links to trisomy 21.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Beyond the congenital anomalies present from birth, children with Down syndrome carry a persisting, lifelong increased risk of leukaemia and solid tumours that a normal early echocardiogram and normal antenatal scans do not reduce.',
  source: 'Pediatrics endpoint part2.pdf p.205'
},

{
  id: 'pedep2-gen-20',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: "Mr. and Mrs. Walsh attend the clinic with their new baby, Ophelia, who has Down syndrome. They are keen to have further children and want to know more about their future risk of having children with Down syndrome. What chromosomal abnormality is most likely to have caused Ophelia's condition?",
  options: ['Mosaicism','Nondisjunction','Point mutation','Translocation','Triplet repeat expansion'],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> Most cases of Down syndrome are due to nondisjunction, a random error during meiosis. Risk increases with maternal age.\n\n---\n\n`6) Genetically determined disease_.txt` breaks Down syndrome down by cytogenetic mechanism: meiotic nondisjunction accounts for about 94% of cases, translocation for about 4-5%, and mosaicism for about 1%. Nondisjunction happens when a chromosome-21 pair fails to separate during meiosis, so one gamete ends up with two copies of 21 and the other with none; fertilisation of the two-copy gamete produces a trisomy-21 zygote. Because nondisjunction accounts for the overwhelming majority of cases, it is also the statistically most likely mechanism for any newly diagnosed baby with Down syndrome whose parents have not yet had karyotyping -- and, per the same source, its recurrence risk for future pregnancies is low (about 1 in 200 for mothers under 35, tracking the mother's age-related risk above that), unlike a translocation, where a parental carrier can raise recurrence to 10-15% or more.\n\n**Why the other options fail.** Translocation and mosaicism are both real mechanisms of Down syndrome but each accounts for only a small minority of cases, so neither is the *most likely* single cause without further testing pointing that way. Point mutation is not a recognised cause of Down syndrome at all -- trisomy 21 is a chromosome-number abnormality, not a single-base change in one gene. Triplet repeat expansion is likewise an unrelated mechanism, associated with conditions such as fragile X syndrome and myotonic dystrophy, not with aneuploidy.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'About 94% of Down syndrome arises from meiotic nondisjunction, making it the statistically most likely cause pending karyotype confirmation, and it carries a much lower recurrence risk than a translocation.',
  source: 'Pediatrics endpoint part2.pdf p.207'
},

{
  id: 'pedep2-gen-21',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'A Bangladeshi couple are referred for genetic counselling. Both parents are carriers of a faulty PEX1 gene; possession of two abnormal copies leads to death in infancy. They have lost two children who both died in the first 2 years of life and have one healthy daughter aged 3 years. What is the risk that their daughter is a carrier?',
  options: ['None','1 in 4','1 in 2','2 in 3','100%'],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Unaffected siblings of affected children have a 2/3 chance of being carriers in autosomal recessive inheritance.\n\n---\n\nBoth of this couple's dead children died from inheriting two copies of the faulty PEX1 gene, so each pregnancy from two heterozygous (carrier) parents was working from the standard autosomal-recessive cross that `6) Genetically determined disease_.txt` describes -- \"the parents are normal while sibs are affected\" -- which, worked through as a Punnett square, gives every child a 1-in-4 chance of being homozygous unaffected, a 2-in-4 chance of being a heterozygous carrier, and a 1-in-4 chance of being homozygous affected *(the specific 2/3 figure asked for here is the standard downstream calculation from that cross rather than a number stated in the cached lecture itself -- not taken from the course material)*. Their daughter is known to be unaffected, which removes the \"1-in-4 affected\" branch from consideration entirely; among the three genotypes left standing -- two carrier outcomes and one homozygous-normal outcome -- two of the three surviving possibilities are carriers, which is where the 2-in-3 risk comes from.\n\n**Why each distractor fails.** \"None\" and \"100%\" both wrongly treat the daughter's carrier status as already resolved; without a specific carrier test, it is a probability, not a certainty in either direction. \"1 in 4\" is the pre-test probability of being *affected*, not the *conditional* probability of being a carrier once affected status has already been excluded by her being alive and well at 3 years old. \"1 in 2\" would be the carrier risk quoted for a random, untested child of two carrier parents *before* excluding the affected outcome -- it ignores the extra information that this particular daughter is known to be unaffected, which is precisely the information that raises her carrier risk from 1-in-2 (unconditional) to 2-in-3 (conditional on being unaffected).\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'For an unaffected sibling of a child with an autosomal recessive condition, excluding the homozygous-affected branch of the parental cross raises the carrier probability from the naive 1-in-2 to a conditional 2-in-3.',
  source: 'Pediatrics endpoint part2.pdf p.209'
},

{
  id: 'pedep2-gen-22',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'George has Klinefelter syndrome. What is his karyotype?',
  options: ['46, XO','46, XY','45, XO','45, XY','47, XXY'],
  answer: 4,
  explanation: "**The endpoint file prints this explanation:**\n\n> Unaffected siblings of affected children have a 2/3 chance of being carriers in autosomal recessive inheritance.\n\n---\n\n**This printed box belongs to the previous question, not this one.** The endpoint file repeats, word for word, the explanation from the PEX1 carrier-risk question on the page before -- a statement about autosomal-recessive carrier probability that has no connection to Klinefelter syndrome or to karyotyping at all. It is quoted above exactly as printed, per this bank's rule of recording a source defect rather than silently fixing it, but it should be disregarded for George's question; nothing about the correct answer below depends on it.\n\nGeorge's actual answer is **47, XXY**. Klinefelter syndrome is caused by an extra X chromosome in a male, most often from nondisjunction during meiosis in either parent, giving a total of 47 chromosomes: the normal 44 autosomes plus an XXY sex-chromosome complement instead of the normal XY *(the karyotype itself is not printed in the cached genetics lecture, which mentions Klinefelter only as a cause of hypergonadotropic hypogonadism without stating its chromosome count -- not taken from the course material; the karyotype 47,XXY is standard clinical genetics knowledge for this diagnosis)*.\n\n**Why each distractor fails.** 46,XY is a normal male karyotype and cannot be Klinefelter's, which by definition carries an extra chromosome. 46,XO and 45,XO are not valid options for Klinefelter at all -- 45,X0 (Turner syndrome) is the *monosomy* pattern in a phenotypic female with a single X and no Y, the numerical opposite of Klinefelter's extra X; \"46,XO\" is not a biologically coherent karyotype, since a cell with only one sex chromosome and 46 total chromosomes does not occur. 45,XY is likewise not a recognised karyotype -- a cell missing a chromosome entirely (monosomy of an autosome) is generally lethal, and this combination does not correspond to any named syndrome the material covers.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Klinefelter syndrome is 47,XXY, an extra X in a male usually from meiotic nondisjunction; the printed explanation on this page is a misprint of the previous question and should be disregarded for this one, while the printed key (47,XXY) is correct and unaffected by that error.',
  source: 'Pediatrics endpoint part2.pdf p.211'
},

{
  id: 'pedep2-gen-23',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'Rachael is a 3-month-old girl who attends the Emergency Department because of rapid breathing. She is the seventh infant born to a 39-year-old mother. On developmental history, she smiled at 7 weeks but cannot yet hold her head unsupported. On examination, she is tachypnoeic, sweaty, and hypotonic. Her weight is below the 0.4th centile. What is the most likely diagnosis?',
  options: ['Achondroplasia','Down syndrome','Turner syndrome','Klinefelter syndrome','Prader-Willi syndrome'],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> Features including hypotonia, feeding issues, and developmental delay in a baby of advanced maternal age suggest Down syndrome.\n\n---\n\nThree separate findings in this vignette point the same way. First, Rachael's mother is 39 -- advanced maternal age is the single biggest driver of the nondisjunction that causes most Down syndrome, and `6) Genetically determined disease_.txt` gives the scale directly: incidence rises from about 1 in 500 at 30 years to about 1 in 350 at 35 and 1 in 110 at 40. Second, her development is delayed in exactly the pattern the same lecture predicts for Down syndrome -- \"delayed motor mile stones\" alongside hypotonia -- since normal infants achieve steady head control by 3 months (per `1) Normal development.txt`), and Rachael, who can smile roughly on schedule (6-8 weeks is the normal window for social smile) but still cannot hold her head unsupported at 3 months, shows a selective motor lag layered on top of preserved social development, the classic hypotonic-infant picture. Third, her tachypnoea and sweating with feeding are the presentation of early heart failure, and `33)Congenital acyanotic heart disease_.txt` notes that the atrioventricular septal defect strongly associated with Down syndrome typically produces heart failure between 2 weeks and 3 months of age -- precisely Rachael's age here -- explaining both the respiratory distress that brought her to the emergency department and the faltering weight (below the 0.4th centile) that a large left-to-right shunt produces through increased work of breathing and feeding difficulty.\n\n**Why each distractor fails.** Achondroplasia causes short-limbed short stature from birth but does not cause hypotonia, developmental motor delay or heart failure, and it is not linked to maternal age. Turner syndrome affects only phenotypic females with a 45,X karyotype and classically presents with lymphoedema of the hands and feet, neck webbing and short stature -- not with hypotonia, developmental delay or a heart-failure picture in early infancy, and it is not associated with advanced maternal age the way Down syndrome is. Klinefelter syndrome is a male-only condition and can be excluded immediately since Rachael is female. Prader-Willi syndrome does cause infantile hypotonia and feeding difficulty, but it typically presents with *poor* feeding and weight gain difficulty from birth without the maternal-age association or the cardiac decompensation described here, and none of the material links it to a heart-failure presentation the way it does for Down syndrome.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'A hypotonic infant of an older mother with selective motor developmental delay and a heart-failure picture between 2 weeks and 3 months of age fits Down syndrome with an associated AVSD, and working up a sick young infant along a structured cardiac-and-developmental pathway is the same approach used for any unwell neonate or young infant.',
  source: 'Pediatrics endpoint part2.pdf p.213'
},

{
  id: 'pedep2-gen-24',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'A paediatrician is asked to review a heart murmur in a 2-day-old baby born by vaginal delivery following an uneventful pregnancy to a 38-year-old primiparous mother. The baby has been feeding well. On examination, he is hypotonic and has single palmar creases and epicanthic folds. What is the most likely heart lesion?',
  options: ['Atrioventricular septal defect','Atrial septal defect','Aortic stenosis','Coarctation of the aorta','Patent ductus arteriosus'],
  answer: 0,
  explanation: "**The endpoint file prints this explanation:**\n\n> This is the hallmark cardiac anomaly in infants with Down syndrome and presents early with a murmur.\n\n---\n\nThe dysmorphic features here -- hypotonia, single (simian) palmar crease and epicanthic folds, in a baby of an older (38-year-old) mother -- are the classic bedside picture of Down syndrome that `6) Genetically determined disease_.txt` lists among its craniofacial and other features, and the cardiac lecture identifies AVSD as the lesion \"common in Down syndrome\", a single five-leaflet valve spanning the atrioventricular junction that leaks under high pulmonary pressure -- which is why a murmur heard this early, at 2 days old, in an infant with these features points to AVSD ahead of the other listed lesions.\n\n**Why each distractor fails.** Atrial septal defect is a real, generally milder shunt lesion, but it is not the lesion the material specifically associates with Down syndrome, and an isolated ASD is usually a soft murmur that often escapes detection this early rather than presenting as the abnormality being reviewed on day 2. Aortic stenosis and coarctation of the aorta are structural left-heart lesions that are not the ones linked to trisomy 21 in the source material -- coarctation, in particular, is the lesion classically tied to Turner syndrome, not Down syndrome. Patent ductus arteriosus is common, especially in preterm infants, but this baby is not described as preterm, and PDA is not the defect the lecture names as the hallmark Down syndrome lesion.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Dysmorphic features of Down syndrome (hypotonia, single palmar crease, epicanthic folds) plus an early murmur should point first to atrioventricular septal defect, the lesion the material names as characteristic of trisomy 21.',
  source: 'Pediatrics endpoint part2.pdf p.215'
},

{
  id: 'pedep2-gen-25',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'Common forms of inheritance include autosomal dominant and autosomal recessive patterns. Which of the following conditions is autosomal dominant?',
  options: ['Neurofibromatosis type 1','Cystic fibrosis','Sickle cell disease','Haemophilia A','Duchenne muscular dystrophy'],
  answer: 0,
  explanation: "**The endpoint file prints this explanation:**\n\n> Neurofibromatosis type 1 is inherited in an autosomal dominant pattern, meaning only one copy of the defective gene is sufficient to cause the condition. In contrast, cystic fibrosis and sickle cell disease are autosomal recessive, and hemophilia A and Duchenne muscular dystrophy are X-linked.\n\n---\n\n`6) Genetically determined disease_.txt` gives the general rule the box applies: in autosomal dominant inheritance, \"one abnormal allele is enough to cause disease,\" and both sexes are equally affected *(neurofibromatosis type 1 is not itself named among the lecture's worked AD examples -- Achondroplasia, adult polycystic kidney disease, myotonic dystrophy, Noonan syndrome and familial hypercholesterolaemia are the ones listed -- but it is a well-established autosomal dominant condition in standard clinical genetics; not taken from the course material)*.\n\n**Why each distractor fails, matched against the lecture's own examples.** Cystic fibrosis is named directly in the lecture's autosomal recessive example list, alongside Hurler syndrome, phenylketonuria, galactosaemia, thalassaemia and Gaucher disease -- both parents must be carriers, and \"the parents are normal while sibs are affected\" is the pattern the lecture describes for this group. Sickle cell disease is likewise an autosomal recessive haemoglobinopathy, requiring two copies of the abnormal beta-globin gene. Haemophilia A and Duchenne muscular dystrophy are both named in the lecture's X-linked recessive example list -- they are carried on the X chromosome, so they overwhelmingly affect males, while female carriers are usually unaffected or only mildly so, which is a different transmission pattern from the autosomal dominant one the question asks about.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Cystic fibrosis and sickle cell disease are autosomal recessive, haemophilia A and Duchenne muscular dystrophy are X-linked recessive, leaving neurofibromatosis type 1 as the autosomal dominant condition among these five.',
  source: 'Pediatrics endpoint part2.pdf p.217'
},

{
  id: 'pedep2-gen-26',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'A 6-year-old boy attends the outpatient clinic with a diagnosis of Down syndrome. He has been pale and lethargic for the last 4 weeks and has some bruises on his shins. Which of the following conditions is important to rule out given his underlying diagnosis?',
  options: ['Parvovirus infection','ITP','Haemophilia A','Acute leukaemia','Henoch-Schönlein purpura'],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> Children with Down syndrome are at increased risk of developing acute leukemia, especially acute lymphoblastic or myeloid leukemia. Unexplained pallor, lethargy, and bruising warrant prompt evaluation.\n\n---\n\n`6) Genetically determined disease_.txt` flags an \"increased risk of leukemia and solid tumors\" as one of the later clinical problems of Down syndrome, which is exactly the context this stem hangs the presentation on. `48)Leukemias.txt` then supplies the mechanism behind this boy's specific symptoms: acute lymphoblastic leukaemia causes pallor and lassitude from marrow-driven anaemia (general systemic effects listed at 40% and 50% respectively), and thrombocytopenia from marrow infiltration causes petechiae, purpura and easy bruisability -- pale, lethargic and bruised over four weeks in a child already known to carry a chromosomal condition that raises leukaemia risk is the pattern that must be actively excluded, not assumed benign.\n\n**Why each distractor fails.** Parvovirus B19 classically causes a transient aplastic crisis in children with an underlying haemolytic condition (such as sickle cell disease), producing pallor from anaemia but not bruising, and this boy has no haemolytic disease predisposing him to that crisis. Immune thrombocytopenic purpura (ITP) could explain isolated bruising from a low platelet count, but it does not explain pallor and lethargy, and it carries no specific link to Down syndrome the way leukaemia does -- which is why it is not the diagnosis this particular child's underlying condition should make you rule out first. Haemophilia A is an X-linked bleeding disorder of clotting factor VIII; it causes bleeding into joints and soft tissue but has no association with Down syndrome and does not explain pallor or lethargy at all. Henoch-Schönlein purpura causes a palpable purpuric rash, typically over the buttocks and lower limbs, often with joint and abdominal symptoms, but it is a vasculitis unrelated to Down syndrome, and it does not produce the marrow-failure picture of pallor plus lethargy plus bruising together.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'In a child with Down syndrome presenting with pallor, lethargy and bruising, acute leukaemia -- to which trisomy 21 confers a specifically increased risk -- must be actively excluded ahead of the other, unrelated causes of anaemia or bruising.',
  source: 'Pediatrics endpoint part2.pdf p.219'
},

{
  id: 'pedep2-gen-27',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'genetics',
  stem: 'Down syndrome is the most common form of trisomy encountered in children and occurs on chromosome 21. Which of the following statements is true?',
  options: ['Most babies with Down syndrome are born to older mothers','Males are frequently infertile','The incidence is 1 in 1,400','Epicanthic folds are pathognomonic','The majority have severe intellectual impairment'],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> Most males with Down syndrome are infertile due to abnormal spermatogenesis. While incidence increases with maternal age, most cases still occur in younger mothers due to higher birth rates in that group.\n\n---\n\n**Male infertility in Down syndrome is standard clinical genetics teaching rather than a stated fact in the cached lecture**, which does not discuss reproductive outcomes for trisomy 21 at all -- *not taken from the course material*. The box's reasoning for the maternal-age half of the statement, though, is confirmed directly by `6) Genetically determined disease_.txt`: incidence rises steeply with maternal age (about 1 in 1530 at 20 years, up to 1 in 37 at 45), but because far more pregnancies overall occur in younger women, the lecture states outright that \"most of the affected babies [are] born to younger mothers\" -- making \"most babies are born to older mothers\" false, and confirming \"males are frequently infertile\" as the one true statement offered here.\n\n**Why each remaining distractor fails.** \"The incidence is 1 in 1,400\" contradicts the figure the same lecture gives directly -- Down syndrome incidence is about 1 in 650 live births, not 1 in 1,400, and increases further with maternal age from there. \"Epicanthic folds are pathognomonic\" overstates a real but non-specific sign: the lecture lists epicanthic folds as one feature among many (alongside a flat nasal bridge, upslanting palpebral fissures, Brushfield spots and a protruding tongue), but epicanthic folds also occur as a normal variant in many healthy infants and in several other conditions, so no single feature by itself is diagnostic -- the diagnosis is confirmed by karyotype, not by one physical sign. \"The majority have severe intellectual impairment\" also overstates the lecture's own wording, which describes \"learning difficulties with variable degree of severity\" rather than a majority with severe impairment -- cognitive outcomes in Down syndrome range widely, most commonly in the mild-to-moderate range.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: 'Down syndrome incidence is about 1 in 650 and rises with maternal age, yet most affected babies are still born to younger mothers because they have far more pregnancies overall; no single dysmorphic feature is pathognomonic, and intellectual impairment is typically variable rather than uniformly severe.',
  source: 'Pediatrics endpoint part2.pdf p.221'
}

];
