var PEDEP2_S12_MFE1_DRAFT_A = [
{
  id:'pedep2-mf1-3', bank:'endpoint', module:'pediatrics', chapter:'dev-problems',
  stem:'A 2-year-old child is brought to the outpatient clinic for developmental delay. He is just able to stand with support and can pronounce 2 or 3 words. He cannot grasp a pencil. What is the most important initial diagnostic step?',
  options:['MRI brain','CT brain','Fundus examination','EEG','Detailed birth history'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> The first step in evaluating developmental delay is a thorough history, especially perinatal and birth events. Imaging or EEG may follow based on history and examination findings.\n\n---\n\nThis child is delayed across more than one field at once: gross motor (standing only with support, short of unsupported standing expected around 12 months), fine motor (cannot yet grasp a pencil, a skill that follows the mature pincer grasp), and language (2-3 single words, short of the 2-word sentences expected by 2 years). A picture this broad raises global developmental delay, and dp-1 organises the causes of any developmental problem under three headings - neurodevelopmental disorders, chronic ill health, and the child\'s physical or psychological needs not being met - arising prenatally, perinatally, or postnatally. None of those headings can be narrowed without first asking about the pregnancy, the delivery and the neonatal course, which is exactly what a detailed birth history supplies.\n\ndp-5 lists the eight investigations sent once global delay is confirmed: brain MRI, a gene study, a chromosomal study, hearing assessment (ABR), fundus or VEP examination, thyroid function plus a PKU metabolic screen, autism screening, and EEG. Every one of those tests is chosen and prioritised on the strength of clues the history turns up - a difficult birth points toward MRI, a family history toward the gene or chromosomal study - so sending any of them before the history is taken means guessing which of the eight to run first.\n\nMRI brain, fundus examination and EEG are all genuine items on that same panel, but each is premature here, since none is more informative than the history that should choose between them. CT brain is not on the panel at all - MRI is the panel\'s imaging test, chosen for detail without ionising radiation - so it is both premature and the wrong imaging choice even once imaging becomes appropriate.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Global developmental delay is worked up with a directed birth and perinatal history first; the history decides which of the panel of investigations (MRI, gene/chromosomal study, ABR, fundus/VEP, thyroid/PKU, autism screen, EEG) to send, not the other way round.',
  source:'Pediatrics endpoint part2.pdf p.1276'
},

{
  id:'pedep2-mf1-4', bank:'endpoint', module:'pediatrics', chapter:'resp-pneumonia',
  stem:'A 3-year-old boy presents with fever and difficulty breathing, getting worse for the last 3 days. Examination shows the following clinical signs: respiratory rate 40 breaths/min, heart rate 120 beats/min, heart sounds normal, no murmurs, dullness on percussion, bronchial breathing, and inspiratory crepitations over the right lower chest front. Select the most likely diagnosis.',
  options:['Acute exacerbation of asthma','Inhaled foreign body (right side)','Pleural effusion (right-sided)','Pneumonia (right-sided)','Pneumothorax (right-sided)'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Fever, crepitations, bronchial breathing, and dullness on percussion suggest lobar pneumonia. Other options like asthma or pneumothorax usually have different clinical signs.\n\n---\n\nresp-4 sets the WHO tachypnoea threshold for a child of 12 months to 5 years at more than 40 breaths/min, so this boy\'s rate of 40/min sits right at that cutoff - a reminder that the surrounding signs, not the respiratory rate alone, are what confirm the diagnosis here. Those signs track resp-5\'s description of lobar pneumonia: dullness to percussion and bronchial breathing mark the consolidated (hepatization) stage, while crepitations are the finding of the congestion and resolution stages either side of it - together they describe a lobar process that is consolidating, exactly the composite picture a real bedside examination gives rather than one textbook-pure stage.\n\nAcute exacerbation of asthma produces a hyperinflated, wheezy chest with resonant, not dull, percussion, and no bronchial breathing - resp-14\'s asthma-versus-mimic table lists widespread wheeze, not focal consolidation, as what makes asthma likely. Inhaled foreign body causes reduced air entry over the obstructed side from air trapping, not the increased vocal resonance and bronchial breathing of consolidated lung. Pleural effusion is stony dull like this, but the fluid between lung and chest wall abolishes breath sounds and vocal resonance rather than increasing them, so there would be decreased, not bronchial, breathing. Pneumothorax gives a hyper-resonant, not dull, percussion note with reduced or absent breath sounds and no crepitations. Only the consolidated, still partly air-containing lung of lobar pneumonia produces dullness, bronchial breathing and crepitations together.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Dullness to percussion plus bronchial breathing plus crepitations together mark a consolidating lobar pneumonia; each of the four distractors instead has its own distinct percussion note and breath-sound pattern.',
  source:'Pediatrics endpoint part2.pdf p.1278'
},

{
  id:'pedep2-mf1-7', bank:'endpoint', module:'pediatrics', chapter:'cardiac',
  stem:'A 5-year-old girl is accidentally discovered to have a murmur during routine school health check-up. She is otherwise well with no previous hospital admissions or illnesses. The S1 is normal and the S2 shows wide and fixed splitting. There is a grade I/VI ejection systolic murmur best heard at the left upper sternal edge. Which of the following is the most likely diagnosis?',
  options:['Aortic stenosis','Aorto-pulmonary window','Atrial septal defect','Pulmonary stenosis','Ventricular septal defect'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> A fixed, wide splitting of S2 with an ejection systolic murmur at the left upper sternal edge is classic for ASD. The child is otherwise asymptomatic, which fits this diagnosis.\n\n---\n\ncard-4\'s murmur grid places an ejection systolic murmur at the upper left sternal edge with a wide, fixed split of S2 as the ASD signature, and card-7 explains why: the murmur itself comes from increased flow across the pulmonary valve, produced by the left-to-right shunt, not from flow across the defect itself, and the fixed split reflects right heart volume overload that no longer varies with respiration. card-3\'s innocent-murmur checklist requires normal heart sounds with no added sounds; a wide, fixed split of S2 is itself an abnormal heart sound, so this murmur fails that criterion even though it is soft (grade I/VI), asymptomatic and at the left sternal edge. A well, asymptomatic school-age girl with an incidental murmur is exactly the classic ASD presentation, since ASD produces little in the way of symptoms in childhood.\n\nAortic stenosis instead gives an ejection systolic murmur at the upper RIGHT sternal edge radiating to the carotids, with a soft, delayed A2, not a wide fixed split. Pulmonary stenosis shares the upper left sternal edge but its second sound is a soft, delayed P2 with an ejection click, not a fixed split. Ventricular septal defect gives a pansystolic, not ejection systolic, murmur at the lower left sternal edge with a normal P2. Aorto-pulmonary window, a direct communication between the two great arteries, is a rare lesion producing a continuous murmur similar to a patent ductus arteriosus rather than the fixed-split pattern described here (this comparison is not taken from the course material, which does not teach aorto-pulmonary window as a separate lesion).\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A wide, fixed split of S2 with an ejection systolic murmur at the upper left sternal edge is the ASD signature; the fixed split itself is what disqualifies the murmur from being called innocent.',
  source:'Pediatrics endpoint part2.pdf p.1284'
},

{
  id:'pedep2-mf1-9', bank:'endpoint', module:'pediatrics', chapter:'neuro-nm',
  stem:'Which clinical sign is characteristic of a disorder of the corticospinal (pyramidal) tract?',
  options:['Brisk hyperreflexia and extensor plantar reflex','Difficulty initiating movements','Dystonia or dyskinesia','Jerky movements','Wide-based gait'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Lesions of the corticospinal tract cause upper motor neuron signs such as spasticity, hyperreflexia, and Babinski sign.\n\n---\n\nneuro-15 names the three central motor control centres and gives each its own signature disorder. A corticospinal (pyramidal) tract lesion produces spasticity, brisk reflexes and an extensor plantar response, together with loss of fine finger movements and weakness in characteristic patterns (shoulder adduction, elbow flexion and forearm pronation in the arm; hip and knee extension with ankle plantar flexion in the leg) - cerebral palsy is named as the commonest cause. Brisk hyperreflexia with an extensor plantar reflex is exactly this upper motor neuron signature.\n\nThe other four options belong to the other two centres. Difficulty initiating movements and dystonia or dyskinesia are both basal ganglia signs, alongside chorea (jerky, involuntary movements) and athetosis (writhing movements) - so "jerky movements" is also a basal ganglia sign, not a corticospinal one. A wide-based gait is a cerebellar sign, part of the ataxic picture that also includes dysmetria, dysdiadochokinesis, nystagmus, dysarthria and a Romberg sign when a sensory pathway is also involved. neuro-16 lists the causes behind each of the three syndromes - cerebral dysgenesis, acquired brain injury and hypoxia-ischaemia for the corticospinal tract; hypoxia-ischaemia, mitochondrial and Wilson or Huntington disease for the basal ganglia; and genetic ataxias, toxins and posterior fossa tumours for the cerebellum - confirming that each clinical picture maps to a different anatomical level.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Corticospinal (pyramidal) tract disease gives spasticity, brisk reflexes and an extensor plantar response; difficulty initiating movement, dystonia and chorea are basal ganglia signs, and a wide-based ataxic gait is a cerebellar sign.',
  source:'Pediatrics endpoint part2.pdf p.1288'
},

{
  id:'pedep2-mf1-10', bank:'endpoint', module:'pediatrics', chapter:'normal-dev',
  stem:'At what age can a child draw a triangle without seeing how it is done?',
  options:['One year','Two years','Three years','Four years','Five years'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Children typically develop the motor and cognitive skills to draw shapes like a triangle around 5 years old. Earlier attempts usually result in scribbles or simpler shapes.\n\n---\n\nnd-8\'s fine-motor table places drawing a triangle at 5 years, matching the printed key directly. The younger ages on the same table build up to it in stages: scribbling and stacking two blocks by 12-15 months, stacking 6-7 blocks and turning pages at 2 years, and drawing a circle or a person and using scissors at 3-4 years - a triangle, with its three straight sides and angles, is a later, more demanding shape than any of those.\n\nOne genuine tension is worth recording rather than smoothing over: nd-6\'s own milestone spine gives a different drawing ladder at these same ages - copies a circle at 3 years, a cross at 4 years, and a square (not a triangle) at 5 years - and nd-8 itself flags that its handout source likewise says "copies a square" at 5, not a triangle. The course material therefore contains two different fifth-year drawing targets depending on which table is read. This does not change the answer here, since the question asks specifically about a triangle and nd-8\'s own fine-motor table (the source that actually names a triangle) places it at 5 years, matching the printed key; the square-at-5 alternative is simply the material\'s other, uncorrected version of the same age.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'The fine-motor table places freehand triangle drawing at 5 years; the course material separately gives a square, not a triangle, as the 5-year copying target elsewhere, an internal disagreement recorded here without changing the answer.',
  source:'Pediatrics endpoint part2.pdf p.1290'
},

{
  id:'pedep2-mf1-11', bank:'endpoint', module:'pediatrics', chapter:'genetics',
  stem:'Which type of genetically determined diseases is responsible for the production of Turner syndrome?',
  options:['Single gene mutation','Imprinting','Chromosomal abnormality','Multifactorial disorder'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Turner syndrome is caused by monosomy X or structural abnormalities of the X chromosome. It is not caused by single-gene mutations or multifactorial disorders.\n\n---\n\ngen-1 lists the four mechanisms behind any genetically determined disease: chromosomal abnormality (numerical or structural), single gene (Mendelian) disorder, unusual mechanisms such as imprinting, and multifactorial genetic-environmental interaction. gen-8 places Turner syndrome squarely in the first group - about half of cases are the full numerical monosomy 45,X0, and the other half are structural or mosaic variants (an X with a short-arm deletion, an isochromosome, or mosaicism such as 46XX/45X0). Either way, the defect is a chromosomal one, not a mutation in a single gene.\n\nSingle gene mutation and multifactorial disorder are directly excluded by the printed explanation itself. Imprinting is gen-1\'s third mechanism, responsible for conditions where the same genetic change behaves differently depending on the parent of origin - it plays no part in Turner syndrome, which is a pure chromosomal-number or chromosomal-structure problem rather than a parent-of-origin effect.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Turner syndrome is a chromosomal abnormality - either full monosomy 45,X0 or a structural/mosaic variant - not a single-gene, imprinting or multifactorial disease.',
  source:'Pediatrics endpoint part2.pdf p.1292'
},

{
  id:'pedep2-mf1-12', bank:'endpoint', module:'pediatrics', chapter:'liver',
  stem:'A 2-day-old baby is admitted to the neonatal unit with respiratory distress and jaundice. A full septic screen is performed, which yields positive E. coli blood cultures. Ophthalmological assessment confirms the presence of cataracts. What is the most likely diagnosis?',
  options:['Galactosemia','Neonatal hepatitis','Biliary atresia','Hypothyroidism','Breast milk jaundice'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> E. coli sepsis in a neonate with cataracts suggests galactosemia. Accumulated galactose causes liver dysfunction, sepsis susceptibility, and eye lens changes.\n\n---\n\nliv-8 names galactosaemia as the metabolic-hepatitis cause the course material singles out, and describes exactly this triad: an unmetabolised sugar build-up that damages the liver (jaundice, hepatomegaly), the eyes (cataracts) and the kidneys and brain, alongside an increased susceptibility to sepsis, classically with E. coli. Cataracts are the detail that separates galactosaemia from the other causes of neonatal jaundice on this list, none of which affects the lens.\n\nNeonatal hepatitis and biliary atresia are both cholestatic causes of prolonged jaundice (liv-4), but neither one produces cataracts or a specific link to E. coli sepsis - biliary atresia\'s own hallmark is pale, acholic stool, not mentioned here. Hypothyroidism causes prolonged jaundice with feeding difficulty and constipation, again without cataracts or sepsis. Breast milk jaundice is a benign, unconjugated hyperbilirubinaemia in an otherwise well infant, and this baby is neither well nor unconjugated-jaundiced alone - he has respiratory distress and a positive blood culture.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Cataracts plus E. coli sepsis in a jaundiced neonate points to galactosaemia; it is the one cause on this list that damages the eye and predisposes to sepsis.',
  source:'Pediatrics endpoint part2.pdf p.1294'
},

{
  id:'pedep2-mf1-13', bank:'endpoint', module:'pediatrics', chapter:'normal-dev',
  stem:'An infant can sit without support, roll over, and crawl but cannot stand alone. What is her most likely developmental age?',
  options:['4 months','6 months','9 months','13 months','16 months'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Crawling and sitting without support typically occur around 8–9 months. Standing without support usually develops closer to 12 months.\n\n---\n\nnd-6\'s milestone spine places sitting unsupported at 8 months and pulling to stand with crawling at 9-10 months, while nd-7\'s ladder gives sitting without support at 7 months and crawling or creeping at 8-9 months. Both put this combination of skills - rolling already achieved, sitting stable, crawling under way, but not yet standing alone - at around 9 months, well before the 12-month median for standing unsupported that nd-7 gives.\n\n4 and 6 months are too young for crawling, which needs the trunk and limb control that only develops after independent sitting. 13 and 16 months are both past the point where a child who can already crawl would typically still be unable to stand alone at all - by 12 months most children stand unsupported, and by 13-16 months many are walking, per nd-7\'s ladder.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Sitting unsupported, rolling and crawling without yet standing alone is the developmental picture of an approximately 9-month-old, ahead of the 12-month median for unsupported standing.',
  source:'Pediatrics endpoint part2.pdf p.1296'
},

{
  id:'pedep2-mf1-14', bank:'endpoint', module:'pediatrics', chapter:'normal-dev',
  stem:'What is the predominant evidence of developmental progression during school age?',
  options:['Cognitive development and abstract thinking','Gross motor, vision, and fine motor skills','Hearing and language milestones','Social interaction and self-care skills'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> School-age children develop advanced cognitive skills, problem solving, and abstract thinking, while gross and fine motor skills are mostly established.\n\n---\n\nnd-1 states this directly: gains across all developmental domains are particularly rapid in the first 5 years, but in the school years progression is predominantly cognitive, with the emergence of abstract thinking. By school age the basic gross motor, fine motor, hearing and language milestones described in nd-6 and nd-7 have already been achieved in the preschool years, so they are no longer what marks ongoing progress.\n\nGross motor, vision and fine motor skills, and hearing and language milestones, are each the dominant story of infancy and the toddler years rather than of school age, once the milestone spine has essentially been completed. Social interaction and self-care skills likewise develop earliest, through the toddler and preschool years (nd-6\'s social column), and continue to mature, but the course material specifically names cognition and abstract thought, not socialisation, as what marks school-age development.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'By school age the motor, hearing and language milestones are largely complete; ongoing developmental progress is predominantly cognitive, with the emergence of abstract thinking.',
  source:'Pediatrics endpoint part2.pdf p.1298'
},

{
  id:'pedep2-mf1-15', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:'A 3-year-old boy was eating peanuts 2 days ago when his younger brother pushed him over. He coughed up the peanuts and was all right. Today, he has been coughing and becomes breathless as soon as he runs about. He is afebrile. Examination findings are: Respiratory rate 36 breaths/min, heart apex beat displaced to the right, reduced air entry on the left chest. Percussion normal. What is the most likely diagnosis?',
  options:['Inhaled foreign body (left side)','Inhaled foreign body (right side)','Pleural effusion','Pneumonia','Pneumothorax'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Sudden onset respiratory symptoms with reduced air entry on one side suggest foreign body aspiration. The history of choking confirms this.\n\n---\n\nThe choking history while eating peanuts, followed by a cough-then-apparent-recovery interval and now exertional breathlessness, is the classic course of an inhaled foreign body - resp-12 lists foreign body aspiration among the recognised causes of a wheezy, breathless child, and this history of an eyewitnessed choking episode is what separates it from the viral or allergic wheeze patterns on the same list. The physical findings narrow it further: reduced air entry on the left with a normal, not dull or hyper-resonant, percussion note fits a partially obstructing foreign body causing air trapping in the affected lung rather than fluid (which would be dull) or a pneumothorax (which would be hyper-resonant).\n\nThe side the mediastinum shifts toward is the key discriminator between the two foreign-body options, and the mechanism behind it is not covered in the course material: a foreign body that partially obstructs a bronchus acts as a one-way valve, letting air in on inspiration but trapping it on expiration, so the affected lung becomes hyperinflated and pushes the heart and mediastinum away from itself, toward the opposite, normal side. Here the apex beat is displaced to the RIGHT, meaning the hyperinflated, obstructed lung is on the LEFT - so the foreign body is inhaled foreign body (left side), even though the reduced air entry is also described on the left. (This air-trapping, mediastinal-shift mechanism is general medical knowledge, not taken from the course material.)\n\nInhaled foreign body (right side) would instead push the mediastinum to the left, the opposite of what is described. Pleural effusion and pneumonia would each be expected to cause dullness on percussion, which is explicitly normal here, and pneumonia would usually run with fever, which this afebrile child does not have. Pneumothorax would give a hyper-resonant, not normal, percussion note.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A witnessed choking episode with unilateral reduced air entry, normal percussion, and the mediastinum shifted AWAY from the affected side points to an inhaled foreign body causing air trapping on that (here, left) side.',
  source:'Pediatrics endpoint part2.pdf p.1300'
},

{
  id:'pedep2-mf1-16', bank:'endpoint', module:'pediatrics', chapter:'genetics',
  stem:'A 2-month-old male infant was born to a 37-year-old mother. The baby was noticed by the primary health care physician to have dysmorphic features, including a flat nasal bridge, short neck, upslanted palpebral fissures, epicanthic folds, and left single palmar crease. Detailed examination revealed a pansystolic murmur heard on the left sternal border, generalized hypotonia, and a 2.5-kg current weight, while his birth weight was 3 kg. What is the most probable cause of all his findings?',
  options:['Congenital heart disease','Severe malnutrition','Chromosomal abnormality','Congenital infection'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Features like flat nasal bridge, epicanthic folds, and single palmar crease suggest Down syndrome, a chromosomal disorder (trisomy 21).\n\n---\n\ngen-4\'s Down syndrome examination table lists exactly this cluster: flat nasal bridge, upslanting palpebral fissures, epicanthic folds and a short neck among the craniofacial features, plus a single palmar crease and hypotonia among the other anomalies, and a congenital heart defect (present in about 40% of cases) - here, a pansystolic murmur consistent with an atrioventricular canal or similar defect. A maternal age of 37 also fits: gen-7\'s maternal-age table shows incidence rising sharply through the 30s, from about 1 in 500 at 30 years toward 1 in 350 at 35 and beyond. Down syndrome is a chromosomal abnormality (trisomy 21), which is the mechanism gen-1 places this dysmorphic-plus-cardiac-plus-hypotonia picture under.\n\nCongenital heart disease and congenital infection can each produce isolated pieces of this picture (a murmur, or dysmorphic features and hypotonia respectively), but neither explains the full, specific combination of facial dysmorphism, palmar crease and cardiac defect together the way a single chromosomal cause does. Severe malnutrition could explain poor weight gain but not the dysmorphic facial features, the palmar crease or the murmur.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Flat nasal bridge, upslanting palpebral fissures, epicanthic folds, a single palmar crease, hypotonia and a cardiac murmur together are the Down syndrome (trisomy 21) cluster, a chromosomal abnormality.',
  source:'Pediatrics endpoint part2.pdf p.1302'
},

{
  id:'pedep2-mf1-17', bank:'endpoint', module:'pediatrics', chapter:'endo-dka',
  stem:'What is the initial management of diabetic ketoacidosis?',
  options:['Insulin','Fluids','Potassium','Bicarbonate','Antibiotics'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Fluid resuscitation is the first priority in DKA to correct dehydration. Insulin, potassium, and other measures are started after stabilizing circulation.\n\n---\n\nendo-13\'s immediate assessment for DKA follows the general PALS sequence - vital signs, weight, severity of dehydration, level of consciousness, and a blood sample - before any specific drug therapy, and endo-15 sets out fluids as the first concrete step: an initial resuscitation bolus of 10 mL/kg over 30-60 minutes with 0.9% saline, restoring circulating volume, before moving on to deficit replacement and maintenance fluids over 36-48 hours.\n\nInsulin is started once resuscitation is under way, and is deliberately not front-loaded, since correcting glucose and ketosis too quickly, before the circulation and osmolality are stabilised, risks cerebral oedema - endo-15\'s own fluid rules add glucose to the drip only once plasma glucose falls to 250-300 mg/dL, which happens well after insulin and fluids are both running. Potassium is added to replacement fluids once levels and renal function are known, not as a first step. Bicarbonate is not part of standard initial DKA management at all in this material. Antibiotics are reserved for febrile patients, and only after appropriate cultures are taken, per endo-13\'s own list of additional measures - they are not a routine first step in every case.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'DKA management starts with fluid resuscitation (0.9% saline bolus) to restore circulation; insulin, potassium and other measures follow once the patient is being actively resuscitated.',
  source:'Pediatrics endpoint part2.pdf p.1304'
},

{
  id:'pedep2-mf1-20', bank:'endpoint', module:'pediatrics', chapter:'renal-uti',
  stem:'A 3-month-old baby girl presents with a urinary tract infection. Which of the following organisms is most likely to be isolated from her urine?',
  options:['Enterococcus spp.','Pseudomonas','Proteus','Escherichia coli','Klebsiella'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> E. coli is the most frequent cause of UTI in infants due to its prevalence in the gut flora and proximity to the urinary tract.\n\n---\n\nren-1 states that UTI in children is overwhelmingly caused by Gram-negative bacilli reaching the bladder by the ascending route - bowel flora to perineum to urethra to bladder - and gives E. coli as the organism in 75-90% of cases, far ahead of any other single organism on the list.\n\nThe other four organisms are all real but minority causes tied to specific circumstances that are not described here: Proteus is associated with the flora under the prepuce of an uncircumcised boy, which does not apply to this baby girl; Pseudomonas is linked to urinary stasis from an obstructive uropathy, vesicoureteric reflux, constipation or a neuropathic bladder, none of which is mentioned; Klebsiella and Enterococcus faecalis are both named on ren-1\'s organism list but as less common causes than E. coli, with no particular risk factor for either flagged in this history.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'E. coli, reaching the urinary tract by the ascending route from bowel flora, causes 75-90% of childhood UTI and is the default organism in the absence of a specific risk factor for another one.',
  source:'Pediatrics endpoint part2.pdf p.1310'
},

{
  id:'pedep2-mf1-24', bank:'endpoint', module:'pediatrics', chapter:'genetics',
  stem:'When a girl with Down syndrome was investigated, three copies of chromosome 21 were seen in karyotyping, one of which is attached to chromosome 14. How would you describe this abnormality?',
  options:['Balanced Robertsonian translocation','Mosaicism','Nondisjunction','Triplet repeat expansion','Unbalanced Robertsonian translocation'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> The extra chromosome 21 attached to 14 causes trisomy 21. This is unbalanced, unlike a balanced translocation where no extra material is present.\n\n---\n\ngen-6 describes this exact mechanism: in translocation Down syndrome, an extra chromosome 21 is joined onto another chromosome, usually 14, as a Robertsonian translocation - accounting for around 4% of Down syndrome cases. gen-10 supplies the balanced-versus-unbalanced distinction that decides the answer: a balanced translocation carries no loss or gain of genetic material and is usually phenotypically normal, while an unbalanced translocation carries an incorrect amount of material and produces the physical and cognitive effects of the extra chromosome. Because this girl has three full copies of chromosome 21 material (two free copies plus the one attached to 14) rather than the normal two, she has an unbalanced translocation - it is the extra copy of chromosome 21 that produces her Down syndrome phenotype.\n\nA balanced Robertsonian translocation carries no extra genetic material and would not, by itself, cause Down syndrome in the person carrying it - it is the finding looked for in an asymptomatic PARENT after a translocation trisomy 21 is diagnosed in a child, per gen-6\'s own rule to karyotype the parents. Mosaicism means some cells are normal and some trisomic, which is a different mechanism from a translocation and is not what is described here. Nondisjunction is the mechanism behind the free (non-translocation) form of trisomy 21, in which chromosome 21 fails to separate at meiosis - it does not produce an extra chromosome attached to another one. Triplet repeat expansion is an unrelated mechanism (seen in conditions such as fragile X) with no chromosomal translocation involved at all.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'An extra copy of chromosome 21 attached to another chromosome is an unbalanced Robertsonian translocation - unbalanced because extra genetic material is present, unlike a balanced translocation.',
  source:'Pediatrics endpoint part2.pdf p.1318'
},

{
  id:'pedep2-mf1-25', bank:'endpoint', module:'pediatrics', chapter:'infection-rash',
  stem:'A 15-year-old boy presents to the hospital with malaise, fever, and mild jaundice over the last week. On examination, there is intense inflammation of the tonsils with purulent discharge, splenomegaly, and cervical lymphadenopathy. What is the most likely cause of his illness?',
  options:['Acute lymphoblastic leukemia','Beta-hemolytic Streptococcus','Hepatitis A infection','Non-Hodgkin’s lymphoma','Epstein-Barr virus (EBV) infection'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Fever, sore throat with exudate, and splenomegaly point to infectious mononucleosis caused by EBV.\n\n---\n\ninf-31 describes exactly this combination as infectious mononucleosis: the core triad of fever, pharyngitis and lymphadenopathy, with pharyngitis often severe and the tonsils showing a white or grey exudate, lymphadenopathy classically posterior cervical, and hepatosplenomegaly with raised transaminases and sometimes mild jaundice. A 15-year-old is a typical age for this presentation, and EBV accounts for around 90% of cases of this picture.\n\nBeta-haemolytic Streptococcus causes exudative tonsillitis and fever but not splenomegaly or jaundice, and inf-31 specifically notes that hepatitis with lymphadenopathy in an adolescent points to EBV rather than a primary hepatitis virus. Hepatitis A can cause fever and jaundice but does not produce exudative tonsillitis or the marked lymphadenopathy and splenomegaly described here. Acute lymphoblastic leukaemia and non-Hodgkin lymphoma can each cause lymphadenopathy and sometimes splenomegaly, but neither typically produces an acute exudative tonsillitis, and the week-long feverish illness with jaundice fits an infectious rather than a malignant process.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Fever, exudative tonsillitis, splenomegaly and cervical lymphadenopathy in a teenager, sometimes with mild jaundice, is the infectious mononucleosis picture caused by EBV in about 90% of cases.',
  source:'Pediatrics endpoint part2.pdf p.1320'
},

{
  id:'pedep2-mf1-27', bank:'endpoint', module:'pediatrics', chapter:'cardiac',
  stem:'Which of the following is not a feature of an innocent heart murmur and requires further investigation?',
  options:['No radiation','Varies with posture','Systolic','Third heart sound','No symptoms'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Innocent murmurs are usually systolic, vary with posture, have no radiation, and occur in asymptomatic children. A third heart sound is abnormal in children and may indicate heart disease, so it requires further investigation.\n\n---\n\ncard-3\'s "S" checklist for an innocent murmur requires it to be aSymptomatic, Soft, Systolic only, and heard at the left Sternal edge, varying with posture and getting louder with fever, anaemia or exercise since it is a flow murmur. Just as important, three findings must be ABSENT for a murmur to be called innocent: normal heart sounds with no added sounds, no parasternal thrill, and no radiation.\n\nNo radiation, varying with posture, being systolic, and having no symptoms are all features that positively support an innocent murmur, matching card-3\'s checklist item for item. A third heart sound is an added sound, and the checklist explicitly requires normal heart sounds with NO added sounds - a third heart sound therefore breaks the innocent-murmur pattern and, per card-3\'s table of disqualifying findings, is one of the features that should prompt further investigation (such as echocardiography) rather than reassurance.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'An innocent murmur must have normal heart sounds with NO added sounds; a third heart sound is an added sound and disqualifies the murmur from being called innocent, requiring further investigation.',
  source:'Pediatrics endpoint part2.pdf p.1324'
},

{
  id:'pedep2-mf1-28', bank:'endpoint', module:'pediatrics', chapter:'normal-dev',
  stem:'At a routine health visitor consultation, a 13-month-old boy is noticed to be crossing arms in his left hand and dragging his left hand and synkinesis and spastic gait. He is holding a toy in his left hand and his father informs the health visitor that he only uses his right side. What is the most likely finding here?',
  options:['Normal developmental milestones','Fine motor delay','Speech and language delay','Play and social delay','Global delay'],
  answer:1,
  explanation:'This baby shows an established hand preference at 13 months, only using his right side while dragging and holding a toy in the left hand, together with synkinesis and a spastic gait. nd-15\'s red-flag list names early hand preference under 18 months as one of the general warning signs of an asymmetric motor problem, and its cerebral-palsy-specific red flags add a scissoring or spastic pattern and persistent primitive reflexes to the same picture - findings consistent with an evolving hemiplegic pattern affecting the left side.\n\nThe five options on offer are categories of developmental delay by field, not diagnoses, and the description here is built almost entirely around what the left hand is failing to do: it is not being used to hold, reach for or manipulate objects the way the right hand is, which is a fine motor (vision and manipulation) skill in nd-3\'s four-field division of development. The synkinesis and spastic gait describe the same underlying asymmetric motor problem showing itself in the leg and in mirrored movements, but the option list does not offer a separate motor or gait category - fine motor delay is the field this picture maps onto among the choices given.\n\nNormal developmental milestones is excluded outright by the asymmetry itself: nd-15 is explicit that early hand preference under 18 months is never a normal finding, unlike a same-aged child who reaches, crawls and babbles symmetrically. Speech and language delay and play and social delay are not supported here - nothing in the description touches language, play or social behaviour, only the use of one side of the body. Global delay would require delay spread across multiple fields (motor, language, social), and this vignette describes a one-sided motor problem rather than an across-the-board delay.\n\nWritten for this bank — Pediatrics endpoint part2.pdf prints no explanation here.',
  objective:'Consistent hand preference before 18 months, with an asymmetric spastic pattern, is an abnormal finding (a possible early hemiplegic pattern); among the categories offered, it is classed as a fine motor delay.',
  source:'Pediatrics endpoint part2.pdf p.1326'
},

{
  id:'pedep2-mf1-29', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:'A 10-year-old boy has a 1-year history of cough that is worse at night and with exercise. Which one of the following tests is most likely to assist you in making a diagnosis?',
  options:['Barium swallow','Bronchoscopy','Chest radiograph','Spirometry','CT chest'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Chronic cough worse at night or with exercise suggests asthma. Spirometry measures lung function and helps confirm obstructive airway disease.\n\n---\n\nA year-long cough that is worse at night and with exercise is the pattern resp-15 lists as making asthma more likely. This boy is over 6 years old, the age at which resp-15 says the diagnosis should be confirmed by demonstrating variable expiratory airflow limitation: spirometry measures FEV1 and FVC, and an obstructive pattern shows a low FEV1 with a normal FVC, giving a reduced FEV1/FVC ratio, with reversibility of 12% or more after a bronchodilator being diagnostic.\n\nBarium swallow investigates swallowing and reflux-related causes of cough, not an asthma pattern. Bronchoscopy is reserved for suspected structural or foreign-body problems, not a year-long exertional and nocturnal cough. Chest radiograph is usually normal in asthma, per resp-15, and is used only to exclude an alternative diagnosis rather than to confirm this one. CT chest is not part of the standard work-up for a straightforward asthma-pattern cough and is reserved for more complex or atypical presentations.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'In a child over 6 with an asthma-pattern cough (worse at night and with exercise), spirometry demonstrating an obstructive, reversible pattern is the test that confirms the diagnosis.',
  source:'Pediatrics endpoint part2.pdf p.1328'
},

{
  id:'pedep2-mf1-33', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:'Which of the following is the best reliever therapy in asthma?',
  options:['Antihistamines','Inhaled corticosteroids','Inhaled short-acting beta agonists','Short-acting theophylline','Inhaled anticholinergic bronchodilators.'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Short-acting beta agonists quickly relieve bronchospasm in asthma attacks, making them the first-choice reliever therapy.\n\n---\n\nresp-16 divides asthma drugs into relievers, taken only during an acute exacerbation, and controllers, taken daily for long-term control. Among relievers, rapid-acting inhaled beta2-agonists (SABAs such as salbutamol) are named as the most potent bronchodilators, acting within 5-15 minutes and usable alone in intermittent asthma - the first-line reliever for an acute attack.\n\nAntihistamines are of no established value in asthma according to resp-16, being useful only where allergic rhinitis coexists. Inhaled corticosteroids are the gold-standard controller, taken daily to reduce inflammation, not a rescue drug for an acute attack. Short-acting theophylline is a methylxanthine, listed among the slower-acting controller options, not the first-choice reliever. Inhaled anticholinergics such as ipratropium bromide are explicitly described as add-on therapy, used together with a SABA in severe acute asthma rather than as the drug of first choice on their own.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Rapid-acting inhaled short-acting beta2-agonists are the most potent bronchodilators and the first-choice reliever for an acute asthma exacerbation; anticholinergics are add-on, not first-line, relievers.',
  source:'Pediatrics endpoint part2.pdf p.1336'
},

{
  id:'pedep2-mf1-35', bank:'endpoint', module:'pediatrics', chapter:'neurological',
  stem:'Which of the following is a feature of a typical febrile seizure?',
  options:['Age usually before 6 months','Focal or generalized','Lasts more than 15 minutes','No post-ictal manifestations','Recurs within 24 hours'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Typical febrile seizures usually occur in children 6 months–5 years, are brief (<15 min), and can be generalized or focal, often with post-ictal recovery.\n\n---\n\nneuro-4 defines a febrile seizure as occurring between 5 months and 6 years of age, and separates the simple (typical) form from the complex form on a short list of features: simple febrile seizures are generalised tonic-clonic (not focal), brief, not repeated within the same illness, and without post-ictal events, while complex ones are focal, prolonged, and repeated. "No post-ictal manifestations" is neuro-4\'s own listed feature of the simple, typical seizure.\n\nAge usually before 6 months falls outside neuro-4\'s stated age range of 5 months to 6 years, and even within that range the peak is later in infancy, not before 6 months. Focal seizures, lasting more than 15 minutes, and recurrence within 24 hours (within the same illness) are all listed by neuro-4 as features of the complex, not the typical, febrile seizure.\n\nWorth recording for the record, though it does not change the printed key: the same explanation box also describes typical febrile seizures as "often with post-ictal recovery", language that reads in tension with its own highlighted answer of "no post-ictal manifestations" - the box is transcribed here exactly as printed, and the key is left exactly as the bank prints it.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A typical (simple) febrile seizure is generalised, brief, not repeated in the same illness, and has no post-ictal period; focal, prolonged or recurrent seizures within the illness mark the complex form instead.',
  source:'Pediatrics endpoint part2.pdf p.1340'
},

{
  id:'pedep2-mf1-36', bank:'endpoint', module:'pediatrics', chapter:'endo-thyroid',
  stem:'Neonatal blood spot screening program for congenital hypothyroidism in Egypt aims at detecting which abnormality?',
  options:['Low TSH','Low T4','Low T3','High TSH','High T3'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> The test detects elevated TSH, which indicates primary hypothyroidism, allowing early treatment to prevent developmental delay.\n\n---\n\nendo-27 describes the Egyptian programme directly: a heel-stick blood sample is taken from every newborn on days 3-7, adsorbed onto filter paper, and analysed in a central laboratory for TSH - the screen is a TSH assay, not a T4 or T3 assay. endo-26 explains why the programme exists at all: congenital hypothyroidism is the commonest preventable cause of intellectual disability, affected infants usually look normal at birth, and only 5-10% would be diagnosed clinically in the first month without screening, so a raised TSH is the trigger that identifies most cases before irreversible neurological damage sets in beyond the first 1-3 months of life.\n\nLow TSH would suggest the opposite problem (hyperthyroidism or a central, pituitary cause), not the primary hypothyroidism the programme is built to catch. Low T4 is the underlying biochemical abnormality in congenital hypothyroidism, but endo-27 is explicit that the Egyptian programme\'s actual assay is TSH, not T4 - some other countries do use a T4-based screen, but that is not this programme. Low T3 and high T3 are not the analyte used by this or most other national newborn screening programmes for this condition.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Egypt\'s newborn screening programme for congenital hypothyroidism assays TSH (a raised value on days 3-7), not T4 or T3, to catch a condition that is otherwise clinically silent at birth.',
  source:'Pediatrics endpoint part2.pdf p.1342'
},

{
  id:'pedep2-mf1-37', bank:'endpoint', module:'pediatrics', chapter:'endocrine',
  stem:'Which is the pathophysiologic cause of type I diabetes in children?',
  options:['Insulin resistance','B-cell failure','Obesity','Carbohydrate overfeeding','Autoimmune destruction of B cells'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Type I diabetes occurs due to autoimmune destruction of pancreatic beta cells, leading to insulin deficiency.\n\n---\n\nendo-2 gives the pathophysiology directly: type 1 diabetes arises from autoimmune destruction of pancreatic beta cells in genetically susceptible individuals, often triggered by an environmental factor such as a viral infection, and the progressive beta-cell loss leads to absolute insulin deficiency, which then drives the downstream metabolic cascade (increased gluconeogenesis, lipolysis and ketone formation, protein breakdown, and osmotic diuresis). endo-1\'s classification table confirms type 1 as more than 90% of paediatric diabetes and specifically names autoimmune beta-cell destruction as its mechanism, distinct from type 2\'s insulin resistance. (Options B and E as printed both read "B cells", which the explanation box\'s own wording makes clear is meant as pancreatic beta cells; this is transcribed here exactly as printed.)\n\nInsulin resistance is endo-1\'s mechanism for type 2, not type 1, diabetes. "B-cell failure" states only that the cells fail, without specifying why, which is a vaguer and less complete answer than the specific autoimmune-destruction mechanism the course material actually teaches - the more precise option is the better answer among the two that mention the same cells. Obesity is a risk factor for type 2 diabetes, not the cause of type 1. Carbohydrate overfeeding is not a recognised cause of either type of paediatric diabetes in this material.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Type 1 diabetes is caused by autoimmune destruction of pancreatic beta cells leading to absolute insulin deficiency; insulin resistance and obesity instead describe type 2 diabetes.',
  source:'Pediatrics endpoint part2.pdf p.1344'
},

{
  id:'pedep2-mf1-38', bank:'endpoint', module:'pediatrics', chapter:'haematology',
  stem:'What is the diagnostic clue for anemia due to acute blood loss?',
  options:['Normal retic count and high bilirubin','High retic count and high bilirubin','High retic count and normal bilirubin','High retic count and marked red cell hypochromia','Marked red cell hypochromia and microcytosis'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Acute blood loss stimulates the bone marrow to produce reticulocytes, while bilirubin remains normal because hemolysis is not the cause.\n\n---\n\nhaem-13\'s two-branch approach to anaemia sends the reticulocyte count first, then the bilirubin, to sort a child into one of three boxes. haem-12 explains what each marker measures: the reticulocyte count reflects red cell PRODUCTION (a young marrow responding to a falling haemoglobin raises it), while bilirubin, in the absence of liver disease, is an excellent marker of red cell DESTRUCTION. In acute blood loss, whole red cells are lost from the circulation rather than broken down, so the marrow ramps up production (raising the reticulocyte count) while there is no extra hemoglobin breakdown to raise bilirubin - haem-13\'s own flowchart places this pattern, raised reticulocytes with normal bilirubin, under blood loss rather than haemolysis.\n\nNormal reticulocyte count with high bilirubin does not fit any of haem-13\'s three boxes as blood loss, since blood loss should raise, not leave normal, the reticulocyte count. High reticulocyte count with high bilirubin is haem-13\'s own haemolysis pattern (red cells being destroyed, not merely lost), covering conditions like hereditary spherocytosis or sickle cell disease from haem-8\'s causes table - not acute blood loss. Marked red cell hypochromia and microcytosis, with or without a high reticulocyte count, describes an iron-deficient film rather than the acute picture described here, and haem-13\'s iron-deficiency limb is reached by a NORMAL, not high, reticulocyte count.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Acute blood loss raises the reticulocyte count (marrow responding to falling haemoglobin) with a normal bilirubin (no increased red cell destruction), distinguishing it from haemolysis, where both are raised.',
  source:'Pediatrics endpoint part2.pdf p.1346'
},

{
  id:'pedep2-mf1-39', bank:'endpoint', module:'pediatrics', chapter:'haematology',
  stem:'What is the pathophysiologic defect in sickle cell anemia?',
  options:['Enzyme deficiency','Absent red cell precursors','Red cell membrane abnormality','Amino acid replacement','mRNA abnormality'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Sickle cell anemia is caused by a mutation replacing glutamic acid with valine in the beta-globin chain, altering hemoglobin structure.\n\n---\n\nThe course material teaches sickle cell disease repeatedly as a disease with consequences - haem-8 lists it as a haemoglobinopathy causing haemolysis, and haem-11 describes its sickle-shaped cells on the blood film alongside erythroblasts - but it never states the underlying molecular lesion. The exact defect, a single point mutation that substitutes valine for glutamic acid at position 6 of the beta-globin chain, altering hemoglobin\'s structure and allowing it to polymerise when deoxygenated, is not in the course material and is answered here from general medical knowledge, tagged as not taken from the course material. In molecular terms this is a missense substitution at the level of the protein\'s amino acid sequence - which is what "amino acid replacement" describes - rather than a defect in an enzyme, a cell structure, or RNA processing.\n\nThe other four options each correspond to a real mechanism taught elsewhere in the material, which is what makes them plausible distractors: enzyme deficiency describes G6PD deficiency (haem-8); absent red cell precursors describes red cell aplasia, where the marrow shows no RBC precursors on examination (haem-23); red cell membrane abnormality describes hereditary spherocytosis, the commonest membrane defect (haem-11); and mRNA abnormality does not match any of the mechanisms this material teaches for the anaemias it covers - sickle cell disease\'s defect is a change to the DNA sequence and its protein product, not to RNA processing.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Sickle cell disease is caused by a single amino acid substitution (valine for glutamic acid) in the beta-globin chain - a point mutation at the protein level, not an enzyme, membrane or RNA defect (not taken from the course material).',
  source:'Pediatrics endpoint part2.pdf p.1348'
},

{
  id:'pedep2-mf1-40', bank:'endpoint', module:'pediatrics', chapter:'genetics',
  stem:'Which ONE of the following disorders is inherited as a sex-linked recessive disorder?',
  options:['Thalassemia','Idiopathic thrombocytopenia','Glucose-6-phosphate dehydrogenase deficiency','Von Willebrand\'s disease','Hereditary spherocytosis'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> G6PD deficiency is X-linked recessive, mostly affecting males, with females being carriers.\n\n---\n\ngen-16\'s rules of transmission match this exactly: an affected father passes his X to every daughter, so all daughters of an affected male are obligate carriers, and there is no male-to-male transmission of an X-linked trait, ever - the reason glucose-6-phosphate dehydrogenase deficiency sits on gen-16\'s own list of X-linked recessive examples, alongside haemophilia A and B, colour blindness, ocular albinism, Hunter\'s disease and Duchenne muscular dystrophy. gen-13\'s pattern chart gives the same giveaway from the other direction: an X-linked recessive disease shows up in males only, skipping generations by passing silently through carrier mothers.\n\nThe other four options fail that test on the pattern the corpus gives each one. Thalassemia is one of gen-15\'s six named autosomal recessive disorders, transmitted horizontally within a single sibship born to two normal, often consanguineous, parents - not skipping generations through carrier mothers. Von Willebrand\'s disease, in its commonest type 1 form (60-80% of all vWD, per haem-41), is autosomal dominant, and haem-42\'s comparison table states outright that it affects males and females equally, the opposite of an X-linked pattern. Idiopathic thrombocytopenia is haem-33\'s immune thrombocytopenic purpura, an autoimmune destruction of platelets by IgG autoantibodies, most often triggered by a preceding viral infection - an acquired disease, so no inherited pattern applies to it at all. Hereditary spherocytosis is named in nnj-6 only as the commonest red-cell membrane defect causing haemolysis; the corpus never states its inheritance pattern anywhere, which is a gap rather than a claim that it is X-linked, but it is also absent from gen-16\'s own list of named X-linked examples, which is reason enough to exclude it here.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'G6PD deficiency is inherited as an X-linked recessive trait, matching gen-16\'s rules of transmission and its list of named examples; thalassemia and von Willebrand disease are autosomal (recessive and dominant respectively), ITP is acquired rather than inherited, and hereditary spherocytosis\'s inheritance pattern is never stated in the corpus.',
  source:'Pediatrics endpoint part2.pdf p.1350'
},

{
  id:'pedep2-mf1-41', bank:'endpoint', module:'pediatrics', chapter:'normal-dev',
  stem:'What is the median age of mature pincer grasp?',
  options:['8 months','10 months','12 months','14 months','16 months'],
  answer:1,
  explanation:'The printed key here is 10 months, but the corpus does not agree with itself on this exact figure. nd-6\'s milestone spine punctuates fine motor development at 9-10 months with "Immature pincer grasp developing" and moves to "Mature pincer grasp" only at the 12-month row - on that table, 10 months falls inside the immature phase, and mature pincer grasp is itself a 12-month milestone. nd-8\'s fine-motor table instead gives a single 6-9 month band for "Transfers objects; pincer grasp" with no immature/mature split at all, and its own month-by-month slide entries split it differently again, putting a plain "PINCER GRASP" at 9 months and a "mature pincer" only alongside the 12-month "releases an object when commanded". nd-15\'s reassurance row for the same milestone lists only a plain "Pincer grasp (thumb and index)" as normal, with no age split given at all. So the corpus gives the mature pincer grasp at least two different ages depending on which table is read - 10 months on one reading of nd-6, 12 months on nd-6\'s own mature-pincer row and on nd-8\'s month-by-month slides - and this entry follows the bank\'s printed key of 10 months without adjudicating between them. The distractors read off nd-6\'s ladder for the surrounding ages: 8 months precedes even the immature pincer grasp; 12 months is where nd-6 itself places the mature grasp; 14 and 16 months fall past every age the corpus gives for pincer grasp of either kind, sitting instead among the walking-and-first-words months of the same table.\n\nWritten for this bank — Pediatrics endpoint part2.pdf prints no explanation here.',
  objective:'The corpus gives at least two different ages for the mature pincer grasp - 10 months on one reading of nd-6, 12 months on nd-6\'s own mature-pincer row and on nd-8\'s month-by-month slides - and this entry records that contradiction rather than resolving it, since the bank\'s printed key (10 months) is never moved.',
  source:'Pediatrics endpoint part2.pdf p.1352'
},
];
