{ n:39, pr:39, p:314, key:2,
  stem:'Delaying the introduction of allergenic foods (e.g., peanuts, eggs) will:',
  opts:['Prevent food allergy','Delay food allergy','Increase risk of allergy','Have no effect'],
  expl:'Early introduction of allergenic foods like peanuts and eggs reduces the risk of developing allergies, delaying them can increase risk.',
  note:'' },

{ n:40, pr:40, p:316, key:1,
  stem:'Developmental delay occurs in weight faltering if:',
  opts:['Any degree of faltering is present','Only prolonged and severe faltering is present','Only mild faltering is present','Never occurs'],
  expl:'Mild or short-term weight faltering usually does not affect development, whereas prolonged severe malnutrition can impair growth and cognition.',
  note:'' },

{ n:41, pr:41, p:318, key:1,
  stem:'Weight faltering is usually identified when:',
  opts:['Weight fluctuates within one centile space','Weight crosses down two or more centile spaces','Height falters','BMI increases'],
  expl:'Crossing downward by ≥2 centile spaces on a growth chart is considered clinically significant weight faltering.',
  note:'' },

{ n:42, pr:42, p:320, key:0,
  stem:'Severe prolonged weight faltering usually affects:',
  opts:['Height','Only weight','Only head circumference','Only mid-arm circumference'],
  expl:'Chronic malnutrition eventually affects linear growth, leading to stunting, while acute malnutrition initially affects weight.',
  note:'' },

{ n:43, pr:43, p:322, key:2,
  stem:'Weight faltering in children was formerly called:',
  opts:['Protein energy malnutrition','Wasting','Failure to thrive','Growth failure'],
  expl:'"Failure to thrive" was the old term for weight faltering or poor growth, reflecting inadequate nutrition or chronic illness.',
  note:'' },

{ n:44, pr:44, p:324, key:2,
  stem:'Nutritional status of a child can be reliably assessed by:',
  opts:['A single weight measurement','A single height measurement','Multiple anthropometric indices','Only head circumference'],
  expl:'A single measurement is insufficient; weight, height, BMI, and mid-arm circumference together provide a comprehensive assessment.',
  note:'' },

{ n:45, pr:45, p:326, key:1,
  stem:'Mid-arm circumference is independent of age in children between:',
  opts:['Birth–6 months','6 months–5 years','5–10 years','Adolescence'],
  expl:'In this age range, mid-arm circumference can be used without age adjustment to screen for malnutrition.',
  note:'' },

{ n:46, pr:46, p:328, key:0,
  stem:'Which of the following is a poor tool for nutritional assessment?',
  opts:['Skin fold thickness','Weight for height','Mid-arm circumference','BMI'],
  expl:'Skin fold measurements are operator-dependent and less reliable than weight-for-height or mid-arm circumference for clinical assessment.',
  note:'' },

{ n:47, pr:47, p:330, key:1,
  stem:'Immunodeficiency in malnutrition is mainly indicated by:',
  opts:['Low serum immunoglobulins','Impaired cell-mediated immunity','Reduced neutrophil count','Low complement levels'],
  expl:'Protein-energy malnutrition primarily causes T-cell defects, while immunoglobulin levels are often preserved.',
  note:'' },

{ n:48, pr:48, p:332, key:1,
  stem:'Unmodified cow’s milk in infancy is:',
  opts:['Suitable from birth','Unsuitable','Safe at 3 months','Recommended after 6 months'],
  expl:'Cow’s milk is not recommended in the first year due to risk of iron deficiency, high renal solute load, and protein excess.',
  note:'' },

{ n:49, pr:49, p:334, key:1,
  stem:'Compared to human milk, cow’s milk contains:',
  opts:['Less protein and minerals','More protein and minerals','Equal protein and minerals','No protein'],
  expl:'Cow’s milk contains higher protein and mineral content, which can stress an infant’s kidneys compared to breast milk.',
  note:'' },

{ n:50, pr:50, p:336, key:2,
  stem:'A modified cow’s milk–based formula should be continued until at least:',
  opts:['6 months','9 months','12 months','18 months'],
  expl:'Formula is usually continued until 12 months, after which toddlers can transition to cow’s milk or varied diet.',
  note:'' },

{ n:51, pr:51, p:338, key:1,
  stem:'Wasting is best defined as:',
  opts:['Low height for age','Low weight for height','Low BMI','Low mid-arm circumference'],
  expl:'Wasting reflects acute malnutrition, distinguishing it from stunting (chronic malnutrition) or underweight (mixed).',
  note:'Page flagged for OCR undercounting option letters; the image itself is fully legible with four clear options a-d, no ambiguity.' },

{ n:52, pr:52, p:340, key:1,
  stem:'A child with marasmus typically has:',
  opts:['Severe edema','No edema','Puffy face','Ascites'],
  expl:'Marasmus is severe wasting without edema, unlike kwashiorkor which features edema and fatty liver.',
  note:'' },

{ n:53, pr:53, p:342, key:1,
  stem:'Criteria for underfeeding in breast-fed babies do NOT include:',
  opts:['Slow irregular weight gain','Sleeping much after nursing','Decreased amount of urine and ↓ frequency of urination','Sucking fists between feeds','Stay on breast for a long period'],
  expl:'Long feeding sessions alone do not indicate underfeeding; the focus is on growth, urine output, and feeding efficiency.',
  note:'' },

{ n:54, pr:54, p:344, box:345, key:0,
  stem:'Which of the following statements about preterm and term formulae and breast milk is most factually correct?',
  opts:['Babies fed on fortified breast milk have a decreased incidence of late-onset sepsis and necrotizing enterocolitis when compared with babies fed on preterm formulae','Preterm babies fed with fortified breast milk show similar weight gain profiles to preterm babies fed on preterm formula milks','Preterm formula contains more fat, protein, and electrolytes but the same amount of carbohydrate as term formula or unfortified breast milk','Preterm formula has a lower sodium content than term formula','Preterm formula has the same protein content as term formula'],
  expl:'Fortified breast milk combines the nutritional adequacy needed for preterm growth with the immunologic and protective benefits of breast milk. Preterm formula supports growth but does not provide the same protective immune factors, so infants fed formula are at higher risk for serious complications like NEC and late-onset sepsis.',
  note:'Box did not fit on the answered page and is printed alone on p.345 (italic text, "Fortified breast milk" lead-in in red).' },

{ n:55, pr:55, p:347, box:348, key:2,
  stem:'An 18-month-old infant is seen in the pediatrician’s office as a new patient for a well-child visit having moved from Minnesota to Texas. A comparison of new to previous growth parameters suggest he has dropped to less than fifth percentile for height, weight, and head circumference. Physical examination findings are significant for lower-extremity bowing, wrist enlargement, frontal bossing, and some hypotonia. The mother is concerned because he does not pull to stand nor walking. She reports that he was exclusively breast-fed until he was 9 to 10 months old, currently drinks about 24 oz of whole milk daily, and has never taken medications or dietary supplements. The mother also has a question about whether he needs allergy testing given his history of frequent upper respiratory infections. Which of the following laboratory findings would be expected?',
  opts:['Low calcium, normal phosphorus, elevated alkaline phosphatase, elevated parathyroid hormone(PTH)','Low calcium, low phosphorus, low alkaline phosphatase, elevated PTH','Low calcium, low phosphorus, elevated alkaline phosphatase, elevated PTH','Low calcium, high phosphorus, elevated alkaline phosphatase, elevated PTH','Low calcium, low phosphorus, low alkaline phosphatase, low PTH'],
  expl:'Nutritional rickets from vitamin D deficiency commonly presents with hypocalcemia and hypophosphatemia, which leads to secondary hyperparathyroidism and elevated alkaline phosphatase. Clinical signs include bowing of legs, wrist enlargement, frontal bossing, and hypotonia.',
  note:'Long vignette; the allergy-testing question in the stem is a distractor, not part of what is being asked. Box did not fit on the answered page and is printed alone on p.348. Read at native 800x450 without needing a hi-res render — fully legible.' },

{ n:56, pr:56, p:350, key:3,
  stem:'Which of the following would be the most likely radiographic finding in a child who has been diagnosed with calcium-deficient rickets?',
  opts:['Widening of the ribs','Shortening of the radius and ulna','Vertebral fissures and fractures','Prominence of the costochondral junctions','Increased densities in the long bone shafts'],
  expl:'Calcium-deficient rickets causes expansion of the growth plates and metaphyseal changes, often seen as prominent costochondral junctions (“rachitic rosary”). Other classic radiographic features may include cupping and fraying of metaphyses.',
  note:'' },

{ n:57, pr:57, p:352, key:1,
  stem:'Which of the following types of food is contraindicated and has to be avoided in a child under one year of age?',
  opts:['Eggs','Honey','Peanut','All of the above'],
  expl:'● Foods high in salt and sugar should be avoided and honey must not be given until 1 year of age because of risk of infantile botulism.\n● Early introduction of common allergens such as egg and peanut at, or around 4 months of age in infants at high risk of developing IgE-mediated allergy may reduce the risk of developing allergy to these foods.',
  note:'' },

{ n:58, pr:58, p:354, key:0,
  stem:'What is appropriate regarding the role of vitamins in children’s nutrition?',
  opts:['Vitamin C deficiency can lead to petechiae and mucosal bleeding','Vitamin K’s main function is in the synthesis of RBCs','Vitamin E deficiency leads to decreased clot generation','Vitamin B12 deficiency is common in infants','Folic acid has no role in blood production'],
  expl:'Vitamin C deficiency (scurvy) leads to defective collagen synthesis, bruising, bleeding gums, and petechiae. Vitamin K is for coagulation, not RBC synthesis.',
  note:'Duplicate pair with n=70 (p.378): identical five option statements, REORDERED — key here is position A (Vitamin C statement first); at n=70 the same five statements are reordered and the same Vitamin C statement is last, moving the key to E.' },

{ n:59, pr:59, p:356, key:1,
  stem:'What is the main benefit of human milk oligosaccharides?',
  opts:['Kill microorganisms','Work as prebiotics','Help protein absorption','Help lactose digestion','Prevent infant colic'],
  expl:'HMOs promote growth of beneficial gut microbiota, supporting immunity and gut health.',
  note:'Near-repeat of n=74 (p.387): stem reworded to "How does human milk oligosaccharides work?" and option B reworded to "Function as prebiotics"; same options otherwise, same key position B.' },

{ n:60, pr:60, p:358, key:3,
  stem:'An 18-month-old exclusively breastfed infant has not started standing or walking yet. On examination, she has swelling of her wrists, an open fontanelle, and has not yet erupted any teeth. Which of the following is the most likely cause?',
  opts:['Vitamin A deficiency','Vitamin B deficiency','Vitamin C deficiency','Vitamin D deficiency','Vitamin E deficiency'],
  expl:'These are classic features of rickets due to vitamin D deficiency, common in exclusively breastfed infants without supplementation.',
  note:'' },

{ n:61, pr:61, p:360, key:1,
  stem:'A three-day term infant born at home, exclusively breastfed, presents with lethargy and hematemesis. On examination, he is markedly pale but not jaundiced and has bulging anterior fontanel. His hemoglobin is 7.2 g/dL in venous blood gas (VBG) report. What is the most likely etiology of his illness?',
  opts:['Vitamin D deficiency','Vitamin K deficiency','Folate deficiency','Iron deficiency','Hypocalcemia'],
  expl:'Newborns who are exclusively breastfed and did not receive vitamin K prophylaxis can develop hemorrhagic disease of the newborn.',
  note:'' },

{ n:62, pr:62, p:362, key:4,
  stem:'An eleven-month-old boy presented to the emergency room with convulsions. He had a history of diarrhea for 3 days and was afebrile. His mother described that he was not thirsty and had no history of convulsions. Examination revealed a large head with wide anterior fontanelle, prominent costochondral junctions, and broad wrists. His eyes and skin pinch were normal, and rectal temperature was 37.8 °C. What is the emergency room initial treatment?',
  opts:['ORS','Antipyretic drug and cold fomentations','Low sodium IV fluids','IV Ceftriaxone','IV calcium gluconate'],
  expl:'The child has hypocalcemic seizures from vitamin D deficiency rickets. Emergency management is IV calcium gluconate.',
  note:'Paired vignette with n=71 (p.380): same clinical picture (infant with convulsions, diarrhea, large head/fontanelle, broad wrists, normal temp) but a different question — this one asks for initial treatment, n=71 asks for expected investigations. Not a duplicate.' },

{ n:63, pr:63, p:364, key:0,
  stem:'A 5-month-old infant is exclusively breastfed until yesterday when her mother started her on formula as she is planning to go back to work. The mother noticed that her baby developed an urticarial rash all over her body very soon after the formula feed. What is the most likely mechanism of this baby’s urticaria?',
  opts:['IgE-mediated cow milk allergy','Non-IgE mediated cow milk allergy','Non-allergic hypersensitivity','Lactose intolerance','Immune complex-mediated hypersensitivity reaction'],
  expl:'Immediate urticaria after exposure is due to IgE-mediated allergy. Non-IgE allergy causes delayed GI symptoms.',
  note:'' },

{ n:64, pr:64, p:366, key:3,
  stem:'What is the main cause of edema in kwashiorkor?',
  opts:['Proteinuria','Hepatomegaly','Elevated serum sodium','Low Protein intake','Protein loss in stools'],
  expl:'Hypoalbuminemia from protein deficiency leads to decreased oncotic pressure and edema.',
  note:'Option D prints "Low Protein intake" with a capital P mid-sentence, transcribed as printed.' },

{ n:65, pr:65, p:368, key:1,
  stem:'Which of the following is a feature of marasmus?',
  opts:['Dermatosis','Gross muscle wasting','Edema','Hair changes'],
  expl:'Marasmus = severe wasting without edema. Kwashiorkor shows edema and dermatosis.',
  note:'Printed number "65" repeats on p.370 (a different question); my n=65 here is correct for this page (pr matches n).' },

{ n:66, pr:65, p:370, key:0,
  stem:'Which of the following laboratory findings is diagnostic of infantile rickets?',
  opts:['Normal calcium level and low phosphorus level','Low calcium level and normal phosphorus level','High calcium level and low phosphorus level','High calcium level and normal phosphorus level','High calcium level and high phosphorus level'],
  expl:'Rickets typically shows low phosphate, normal/low calcium, and high alkaline phosphatase.',
  note:'Page prints "65", duplicating p.368’s printed number as flagged in the brief. My n=66 is used per instruction; pr:65 records what is actually printed. From this page onward the printed number trails n by one.' },

{ n:67, pr:66, p:372, key:0,
  stem:'Which of the following is a key sign of protein-energy malnutrition in infants?',
  opts:['Edema','Hyperactivity','Hypoactivity','Diarrhea','Polyuria'],
  expl:'Edema is a hallmark of protein-energy malnutrition, especially kwashiorkor. It results from low albumin and protein deficiency.',
  note:'' },

{ n:68, pr:67, p:374, key:3,
  stem:'Which vitamin is often deficient in breastfed infants?',
  opts:['Vitamin A','Vitamin B12','Vitamin C','Vitamin D','Vitamin E'],
  expl:'Exclusively breastfed infants often develop vitamin D deficiency, since breast milk is low in vitamin D. This can lead to rickets if not supplemented.',
  note:'' },

{ n:69, pr:68, p:376, key:0,
  stem:'A 6-month-old exclusively breastfed infant presents with wide anterior fontanelle and craniotabes. The mother follows a vegan diet and does not take any supplements. What is the most appropriate next step?',
  opts:['Begin Vitamin D supplementation','Start calcium supplementation','Introduce solid foods','Reassure and monitor','Perform skull X-rays'],
  expl:'The findings suggest rickets due to vitamin D deficiency, especially in a vegan mother not supplementing. Calcium deficiency is less likely.',
  note:'' },

{ n:70, pr:69, p:378, key:4,
  stem:'What is appropriate about the role of vitamins in children’s nutrition?',
  opts:['Folic acid has no role in blood production','Vitamin K main function is in the synthesis of RBCs','Vitamin E deficiency leads to decreased clot generation','Vitamin B12 deficiency is common in infants','Vitamin C deficiency can lead to petechiae and mucosal bleeding'],
  expl:'Vitamin C is required for collagen synthesis; deficiency causes scurvy with bleeding signs.',
  note:'Duplicate pair with n=58 (p.354): same five option statements REORDERED — n=58 keys the Vitamin C statement at position A, this page keys the identical statement at position E. Option B here prints "Vitamin K main function" (no possessive s); n=58 prints "Vitamin K’s main function" — transcribed as printed on each page.' },

{ n:71, pr:70, p:380, box:381, key:1,
  stem:'A 9-month-old boy presented to the emergency room with convulsions. He had a history of mild diarrhea for 3 days and was afebrile. His mother described that he was not thirsty and had no past history of convulsions. The examination revealed a large head, prominent fontanelles, and broad wrists. His eyes and skin were normal, and rectal temperature was 37.8°C. Which of the following is expected in his investigations?',
  opts:['Normal calcium level, low phosphate level, high alkaline phosphatase level','Low calcium level, low phosphate level, high alkaline phosphatase level','Low calcium level, normal phosphate level, normal alkaline phosphatase level','Normal calcium level, normal phosphate level, high alkaline phosphatase level','Low calcium level, normal phosphate level, high alkaline phosphatase level'],
  expl:'This 9-month-old with convulsions, large head, open fontanelles, and broad wrists has vitamin D deficiency rickets.\n• Vitamin D deficiency → ↓ calcium absorption → hypocalcemia.\n• Secondary hyperparathyroidism → ↑ phosphate excretion → hypophosphatemia.\n• Alkaline phosphatase ↑ due to active osteoblasts trying to mineralize bone.\nClassic labs in nutritional rickets = low calcium + low phosphate + high ALP.',
  note:'Box did not fit on the answered page and is printed alone on p.381 (italic bullet list, red/bold lead sentence). Paired vignette with n=62 (p.362) — same clinical picture, different question (investigations vs. treatment); not a duplicate.' },

{ n:72, pr:71, p:383, key:1,
  stem:'A 4-month-old baby girl is assessed by her general practitioner because of constant crying and poor feeding. She is fed by bottle on infant formula. Her mother tearfully complains that she is finding it very difficult to cope. Her development, growth, and physical examination are normal, but her stools frequently contain streaks of blood. What is the likely cause of the girl’s problem?',
  opts:['An inherited genetic condition','Cow’s milk protein allergy','Down syndrome','Gastroesophageal reflux','Cystic fibrosis'],
  expl:'Blood-streaked stools in an otherwise healthy infant suggest cow’s milk protein allergy. Reflux does not cause blood.',
  note:'' },

{ n:73, pr:72, p:385, key:3,
  stem:'Which of the following is considered a drawback of breastfeeding?',
  opts:['Reduces the risk of diabetes mellitus','Promotes maternal-child bonding','Provides passive immunity to the infant','May be harmful in some genetic disorders'],
  expl:'Generally breastfeeding is beneficial, but in rare metabolic disorders like galactosemia, it can be harmful.',
  note:'' },

{ n:74, pr:73, p:387, key:1,
  stem:'How does human milk oligosaccharides work?',
  opts:['Kill microorganisms','Function as prebiotics','Help protein absorption','Help lactose digestion','Prevent infant colic'],
  expl:'',
  note:'No explanation box printed on this page. Near-repeat of n=59 (p.356) — reworded stem ("What is the main benefit of...") and option B reworded ("Work as prebiotics"); otherwise identical options, same key position B.' },

{ n:75, pr:74, p:389, key:1,
  stem:'A 10-day-old infant is brought in by her parents, who are concerned that she is not breastfeeding well. The infant was born at term and has been exclusively breastfed. On examination, the baby is alert but has lost 10% of her birth weight. Which of the following is the next best step in management?',
  opts:['Advise immediate weaning and start formula','Encourage more frequent breastfeeding sessions','Introduce solid foods','Supplement with water between feeds'],
  expl:'A 10% weight loss is common in the first days but should improve. The best management is encouraging effective, frequent breastfeeding, not formula or water.',
  note:'' },

{ n:76, pr:75, p:391, key:1,
  stem:'Which specialized milk formula best suits infants with cow’s milk protein allergy?',
  opts:['Lactose free formula','Amino acid-based formula','Soy protein formula','Formula high in omega 3 fatty acids','Medium-chain fatty acids formula'],
  expl:'In cow’s milk protein allergy (CMPA), the immune system reacts to the proteins in cow’s milk (casein and whey). Therefore, formulas that still contain these proteins (even in modified form) can trigger allergic reactions.',
  note:'' },
