/* Section 11 "Model Final Exam 2" — half D, n63,n64,n65,n66,n67,n68,n69,n71,n75,n77,n78.
   Drafted from content/peds/qb-pages/endpoint-s11-mfe2.array.js (PEDEP_S11_STAGED).
   Bare fragments; splicer strips this header. Id prefix is pedep-mf2- per val-pd-ep.js SEC[11]. */

{
  id: 'pedep-mf2-63',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'perinatal',
  stem: 'A full-term boy was presented with imperforate anus shortly after birth. After a few hours of resuscitation, he was noted to pass meconium per urethra. What is the next step?',
  options: ["Colostomy","Perineal anoplasty","Posterior sagittal anorectoplasty","Urethral dilatation","Watchful expectancy"],
  answer: 0,
  explanation: "**The endpoint file prints this explanation:**\n\n> Meconium passing via urethra indicates a high anorectal malformation with fistula. Initial management is colostomy, followed later by definitive repair.\n\n---\n\nMeconium appearing at the urethral meatus can only mean the rectum is communicating with the urinary tract, and a rectourethral fistula places the blind rectal pouch above the levator sling -- that is a high (supralevator) anorectal malformation, not a low one *(anorectal malformations are not taught in any cached paediatrics deck -- \"imperforate\", \"anorectal malformation\", \"anoplasty\" and \"colostomy\" all return nothing across the lecture set, and the only surgical bowel disease mentioned at all is Hirschsprung, as a one-line Down syndrome association in the genetics deck -- not taken from the course material)*. A high lesion cannot be brought down through the perineum in a newborn, so the neonate is diverted with a colostomy, allowed to grow, and imaged by distal colostogram before the definitive pull-through.\n\n**Why each distractor fails.** *Perineal anoplasty* is the operation for a LOW malformation, where the pouch already lies below the levator and the fistula opens on the perineum -- meconium per urethra rules that out. *Posterior sagittal anorectoplasty* is the right definitive operation for this baby but the wrong step now: it follows the colostomy after growth and colostogram, it does not replace it. *Urethral dilatation* treats no part of this problem -- the urethra is normal calibre and is merely receiving meconium through an abnormal communication. *Watchful expectancy* is unsafe: an imperforate anus is a complete distal obstruction, and waiting invites abdominal distension, perforation and urinary sepsis from ongoing faecal contamination of the urinary tract.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Meconium passed per urethra in a newborn with an imperforate anus means a rectourethral fistula and therefore a high anorectal malformation; the immediate step is a diverting colostomy, with posterior sagittal anorectoplasty deferred until after growth and a distal colostogram.",
  source: 'Pediatrics endpoint part1.pdf p.1448'
},

{
  id: 'pedep-mf2-64',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'perinatal',
  stem: 'During a screening examination of a 3200 g boy, an absence of anal opening was noted. How can you reliably determine whether this imperforate anus case is high or low?',
  options: ["Administration of water-soluble contrast by nasogastric tube with delayed images","Ultrasound of the perineum","Magnetic resonance imaging scan of the pelvis","Wait 24 hours and observe the perineum for meconium","Plain abdominal films with a radiopaque marker on the perineum immediately after birth"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> After 24 hours, a plain abdominal X-ray with perineal marker helps define the level of gas. This determines if the malformation is high or low.\n\n---\n\n**The printed key and the printed box do not agree here, and the key is left exactly as the bank printed it.** The highlighted answer is *Wait 24 hours and observe the perineum for meconium*. The box, quoted above word for word, describes instead the technique named in the last option -- a plain abdominal film with a radiopaque marker on the perineum -- while attaching a timing clause of its own, \"After 24 hours\". Both statements are reproduced as printed; neither is corrected.\n\n**The clinical picture on its own terms.** Level assignment in an imperforate anus turns on where the blind rectal pouch ends relative to the levator sling, and neither the pouch nor a fistula can be read at birth. Two things change over the first 24 hours: swallowed air travels distally and finally distends the terminal rectum, and a low lesion with a perineal or vestibular fistula declares itself by meconium appearing on the perineum, at the fourchette or in the urine. Inspecting the perineum after that interval is therefore a genuine bedside discriminator, and it is also the interval that makes any distal radiograph -- prone cross-table lateral or invertogram, with a metal marker taped at the anal dimple -- interpretable, because the gas column must first reach the pouch for the marker-to-gas distance to mean anything *(the timing and technique of level assignment in anorectal malformation are not covered in any cached paediatrics deck; \"imperforate\", \"anorectal malformation\" and \"invertogram\" return nothing across the lecture set -- not taken from the course material)*.\n\n**Why the other three fail.** *Water-soluble contrast by nasogastric tube with delayed images* opacifies the whole gut over many hours to reach a blind pouch that swallowed gas outlines by itself, and it adds an aspiration risk in a newborn for no extra information. *Ultrasound of the perineum* can estimate the pouch-to-skin distance and is used in some centres, but it is operator-dependent and does not reliably establish the relationship to the levator, which is the thing being asked. *Magnetic resonance imaging of the pelvis* shows the sphincter complex and sacral anatomy beautifully and is the best anatomical study of the three, but it needs a stable, often sedated infant and is a planning tool before definitive repair, not the way the level is settled in the first day of life.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "In a newborn with an imperforate anus the high-versus-low level cannot be assigned at birth: about 24 hours must pass for swallowed gas to reach the blind rectal pouch and for a low fistula to declare itself as meconium on the perineum. Note that this question's printed key and its printed explanation box name different options, and the key has been left as printed.",
  source: 'Pediatrics endpoint part1.pdf p.1450'
},

{
  id: 'pedep-mf2-65',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'renal-cakut',
  stem: 'Which of the following is not a feature of hypospadias?',
  options: ["Dorsal chordee","Hooded foreskin","Ventrally placed meatus","Proximal meatus"],
  answer: 0,
  explanation: "**The endpoint file prints this explanation:**\n\n> Hypospadias involves ventrally placed meatus, hooded foreskin, and sometimes proximal meatus. Chordee, if present, is ventral, not dorsal\n\n---\n\nHypospadias is a single developmental failure -- incomplete fusion of the urethral folds along the ventral surface of the penis -- and every one of its features points the same way, ventrally *(hypospadias is not taught in any cached paediatrics deck; \"hypospadias\" and \"chordee\" both return nothing across the lecture set, including the congenital anomalies of the kidney and urinary tract deck -- not taken from the course material)*. That is what makes the question answerable without recall of a list: any feature described as dorsal is describing the opposite anomaly. A dorsally placed meatus with dorsal curvature is epispadias, which belongs to the bladder-exstrophy spectrum, not to hypospadias.\n\n**Why the other three are genuine features.** *Hooded foreskin* follows directly from the same fusion failure: the prepuce is deficient ventrally and heaps up dorsally, and it is often the finding that brings the baby to attention on newborn examination. *Ventrally placed meatus* is the definition of the condition. *Proximal meatus* describes the severe end of the same spectrum -- the meatus may sit anywhere from just below the glans to the penoscrotal junction or perineum, and the more proximal it lies the more likely significant chordee and the more complex the repair. Because the foreskin is used in reconstruction, a boy with hypospadias should not be circumcised before a surgical opinion.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Hypospadias is a ventral anomaly throughout -- ventrally placed meatus which may be proximal, dorsally hooded foreskin from ventral preputial deficiency, and chordee that curves ventrally; dorsal chordee belongs to epispadias, not hypospadias.",
  source: 'Pediatrics endpoint part1.pdf p.1452'
},

{
  id: 'pedep-mf2-66',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'perinatal-rd',
  stem: 'In retrosternal diaphragmatic hernia of Morgagni, the defect is situated:',
  options: ["Posteriorly in the diaphragm at the area of the embryonic pleuroperitoneal canal.","Anteriorly through the opening for the superior epigastric artery","Through the esophageal hiatus at the gastroesophageal junction.","In the central tendon"],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> Morgagni hernia is a retrosternal diaphragmatic defect located anteriorly, usually through the foramina of Morgagni.\n\n---\n\nThe word retrosternal in the stem already fixes the anatomy: the foramen of Morgagni is the anterior parasternal gap between the sternal and costal origins of the diaphragm, transmitted by the superior epigastric vessels, so a hernia through it sits behind the sternum, usually on the right, and typically contains transverse colon or omentum. It is the uncommon variety, often silent and found on a chest film taken for another reason, which is why it presents so differently from the classic neonatal emergency *(the anatomical distinction between Morgagni and Bochdalek defects is not taught in any cached paediatrics deck -- \"Morgagni\" and \"Bochdalek\" both return nothing across the lecture set -- not taken from the course material)*.\n\n**Why each distractor fails.** *Posteriorly at the embryonic pleuroperitoneal canal* is the Bochdalek hernia, the posterolateral and much commoner defect; that is the one `9) Respiratory distress in newborn.txt` describes under congenital diaphragmatic hernia as \"Severe, immediate respiratory distress,\" with a \"Scaphoid (sunken) abdomen\" and \"Heart sounds shifted to the right,\" often picked up on prenatal ultrasound at 18-20 weeks. *Through the esophageal hiatus at the gastroesophageal junction* is a hiatus hernia, a different lesion in a different opening, and the same deck set treats reflux rather than herniation as its consequence. *In the central tendon* describes the rare central (septum transversum) defect, which is neither retrosternal nor parasternal and is not what the eponym names.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "The Morgagni hernia is the anterior, retrosternal parasternal defect through the foramen transmitting the superior epigastric artery; the posterolateral defect at the pleuroperitoneal canal is Bochdalek, the hiatal opening gives a hiatus hernia, and a central tendon defect is a separate rare entity.",
  source: 'Pediatrics endpoint part1.pdf p.1454'
},

{
  id: 'pedep-mf2-67',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'perinatal',
  stem: 'In babies born with umbilical hernia:',
  options: ["The majority need surgical correction","Spontaneous closure is the rule rather than the exception","A mesh is usually needed in surgical repair","None of the above"],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> Most infantile umbilical hernias close spontaneously by 2–3 years of age. Surgery is rarely required.\n\n---\n\nAn infantile umbilical hernia is a fascial ring that has not yet contracted, not a structural defect: the umbilical ring narrows steadily through infancy and most rings close on their own, so the correct advice to a parent is reassurance and observation rather than referral *(the natural history of the infantile umbilical hernia is not taught in any cached paediatrics deck -- the only appearances of \"umbilical hernia\" in the lecture set are in `52) hypothyrodism.txt`, where it is listed among the neonatal features of congenital hypothyroidism and again among the physical stigmata that treatment reverses -- not taken from the course material)*. That single cached mention is itself worth carrying: an umbilical hernia in a baby who is also feeding poorly, constipated, hoarse, cold and mottled with a large tongue and a posterior fontanel over 0.5 cm is a pointer to hypothyroidism, not an isolated surgical problem. Incarceration and strangulation, the events that drive repair in adults, are distinctly rare in infants.\n\n**Why each distractor fails.** *The majority need surgical correction* inverts the natural history and is the error the question is built to catch. *A mesh is usually needed in surgical repair* imports adult hernia practice into a child: the small number of paediatric repairs that do go ahead -- for a persistent defect in an older child, a very large or proboscoid hernia, or the rare complication -- are simple suture closures of the ring, and mesh is not routine. *None of the above* cannot stand once a true statement is present in the ladder.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Infantile umbilical hernias close spontaneously in the great majority, generally by 2–3 years, so observation and reassurance are the rule; repair is uncommon, is a suture closure rather than a mesh repair, and an umbilical hernia with other neonatal stigmata should prompt thought of congenital hypothyroidism.",
  source: 'Pediatrics endpoint part1.pdf p.1456'
},

{
  id: 'pedep-mf2-68',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'gastroenterology',
  stem: '"Corkscrew sign" on upper GI study indicates the presence of:',
  options: ["Intussusception","Infantile hypertrophic pyloric stenosis","Meconium ileus","Midgut volvulus"],
  answer: 3,
  explanation: "**The endpoint file prints this explanation:**\n\n> On upper GI contrast study, a \"corkscrew appearance\" indicates twisted bowel loops due to malrotation with volvulus.\n\n---\n\nThe sign is literal: in malrotation the mesenteric root is narrow, so the midgut can rotate about the superior mesenteric artery, and contrast passing through the twisted duodenojejunal segment spirals downwards instead of crossing the midline to a normally sited duodenojejunal flexure. The upper GI contrast study is the study that shows it, which is why the stem specifies that modality *(the corkscrew sign is not described in any cached paediatrics deck -- \"corkscrew\" returns nothing across the lecture set, and malrotation appears only in `22)Vomiting.txt`, in the list of emergencies to consider when vomiting is bile-stained -- not taken from the course material)*. That cached line is the clinical half of the same fact: bile-stained vomiting in an infant is midgut volvulus until proven otherwise, and the twist strangulates the entire midgut, so the study is arranged urgently and the child goes to theatre.\n\n**Why each distractor fails.** *Intussusception* is telescoping of bowel, which `24)Abdominal pain.txt` defines as \"the invagination of proximal bowel into a distal segment,\" most often ileum into caecum, peaking at \"3 months – 2 years\"; it is imaged by ultrasound and reduced by air or contrast enema, and gives a target or claw appearance, not a spiral. *Infantile hypertrophic pyloric stenosis* obstructs at the gastric outlet, presenting per `22)Vomiting.txt` with projectile vomiting \"at 2–8 weeks of age\" and an olive-shaped mass, and it is now diagnosed by ultrasound; its contrast appearance is an elongated narrow pyloric channel, not a corkscrew. *Meconium ileus* is a neonatal distal small bowel obstruction by inspissated meconium, strongly associated with cystic fibrosis, and is a contrast enema finding of microcolon with filling defects rather than an upper GI spiral.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "A corkscrew or spiral course of the duodenojejunal segment on upper GI contrast study is malrotation with midgut volvulus -- the surgical emergency behind bile-stained vomiting in an infant -- as distinct from the target sign of intussusception, the narrow channel of pyloric stenosis and the microcolon of meconium ileus.",
  source: 'Pediatrics endpoint part1.pdf p.1458'
},

{
  id: 'pedep-mf2-69',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'gi-diarrhoea',
  stem: 'A diagnosis of Hirschsprung disease is made on a newborn baby. What is the definitive diagnostic test for Hirschsprung disease?',
  options: ["Barium enema","Rectal biopsy","Diagnostic laparoscopy","Anorectal manometry"],
  answer: 1,
  explanation: "**The endpoint file prints this explanation:**\n\n> The gold standard is biopsy showing absence of ganglion cells in the submucosa. Barium enema or manometry are supportive, not definitive.\n\n---\n\nHirschsprung disease is defined histologically, not radiologically: neural crest cells fail to complete their craniocaudal migration, so the distal bowel has no submucosal or myenteric ganglion cells and cannot relax, which is why only tissue can confirm it. A suction rectal biopsy taken above the dentate line shows aganglionosis with hypertrophied nerve trunks, and the diagnosis is made on that specimen *(the diagnostic pathway for Hirschsprung disease is not taught in any cached paediatrics deck -- \"ganglion\" and \"rectal biopsy\" both return nothing across the lecture set, and the single appearance of the disease anywhere in it is one line in `6) Genetically determined disease_.txt` listing it among the associations of Down syndrome -- not taken from the course material)*. That association is worth holding on to, because a newborn with Down syndrome who fails to pass meconium in the first 48 hours is exactly the child in whom this diagnosis is chased.\n\n**Why each distractor fails.** *Barium enema* may show a narrow distal segment with a funnel-shaped transition zone to dilated proximal bowel and delayed contrast evacuation, which supports the diagnosis and helps plan surgery, but the transition zone is unreliable in the neonate and normal films do not exclude the disease. *Diagnostic laparoscopy* inspects serosal surfaces and cannot see an absence of submucosal ganglion cells; it has no diagnostic role here. *Anorectal manometry* demonstrates failure of the rectoanal inhibitory reflex on balloon distension and is a useful screening study in older children, but it is technically unreliable in small infants and, like the enema, never replaces tissue.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Hirschsprung disease is confirmed by rectal biopsy showing absent submucosal ganglion cells; barium enema (transition zone) and anorectal manometry (absent rectoanal inhibitory reflex) are supportive only, and laparoscopy has no diagnostic role.",
  source: 'Pediatrics endpoint part1.pdf p.1460'
},

{
  id: 'pedep-mf2-71',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'infection-rash',
  stem: 'A 9-year-old girl presented with fever that increased gradually to 40°C over 4 days. Then a maculopapular rash appeared on the forehead and spread to the trunk and extremities over 3 days. When the rash had appeared on the feet, the temperature dropped abruptly. What is the most probable diagnosis?',
  options: ["Measles","Rubella","Varicella","Scarlet fever","Roseola infantum"],
  answer: 0,
  explanation: "**The endpoint file prints this explanation:**\n\n> Measles presents with fever followed by a maculopapular rash starting at the forehead, spreading downward. Rash coincides with fever peak.\n\n---\n\nThe stem is a description of the measles exanthem stage as `infectious diseases causing maculopapular rash.txt` teaches it. The prodrome is \"a stepwise increase in fever (often peaking at 103°F–105°F)\" with the \"three Cs\": Cough, Coryza and Conjunctivitis -- the gradual four-day climb to 40°C here. The rash then \"Begins at the hairline and face, then spreads cephalocaudally (downward) to the neck, trunk, and eventually the extremities (including palms and soles in severe cases),\" which is the forehead-to-feet march over three days, and the fever settles as that spread completes. Koplik spots, \"tiny white-to-bluish specks on a red base... on the buccal mucosa (opposite the molars) 1–2 days before the rash,\" are the pathognomonic sign to ask about, and as the rash fades after 5–6 days it leaves \"a coppery-brown discoloration and fine skin peeling (desquamation).\"\n\n**Why each distractor fails.** *Rubella* runs a much milder course: the deck gives \"Low-grade fever (<39°C/102.2°F)\" with a rash \"finer and less bright than the measles (rubeola) rash,\" and in children \"the rash is often the first sign of illness\" rather than the end of a four-day fever. *Varicella* does not belong in a maculopapular question at all -- it is absent from this deck's own list of maculopapular exanthems and is covered separately as a vesicular rash, appearing in successive crops rather than as a single downward-spreading eruption. *Scarlet fever* begins abruptly with high fever, beefy red exudative tonsils and strawberry tongue, and its rash appears \"12–48 hours after the fever begins,\" is \"sandpaper\" in texture, starts on the trunk and neck, and adds Pastia lines and circumoral pallor -- none of which is described here. *Roseola infantum* is the deliberate trap, and the deck states the discriminator outright: \"Roseola is unique because the rash and the fever rarely overlap.\" Its very high fever, \"often >40°C or 104°F,\" lasts \"3 to 5 days\" in a child who looks surprisingly well, and the rash appears only once the fever has broken; here the rash and the fever overlapped for three days, and the temperature fell only after the rash had reached the feet.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "A stepwise fever to 40°C for several days followed by a maculopapular rash that starts on the forehead and spreads cephalocaudally, with defervescence as the rash reaches the feet, is measles; roseola is excluded because its rash appears only after the fever breaks, and rubella, scarlet fever and varicella each have a different fever-rash relationship and rash morphology.",
  source: 'Pediatrics endpoint part1.pdf p.1464'
},

{
  id: 'pedep-mf2-75',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'infection',
  stem: 'A two-year-old male child is admitted with a history of fever for the last ten days. History and clinical examination are unremarkable. What is the next most appropriate step in managing this child?',
  options: ["Verification of the severity and duration of fever.","To do investigations to rule out tuberculosis.","Immediate hospital admission.","To do preliminary blood investigations.","Start broad-spectrum antibiotics after blood culture."],
  answer: 0,
  explanation: "**The endpoint file prints this explanation:**\n\n> This is fever of unknown origin (FUO). First step is careful history and confirmation before investigations.\n\n---\n\nBefore a prolonged fever is investigated it has to be established that it is real, that it is as high as reported, and that it has genuinely been continuous for ten days -- a substantial proportion of referred \"prolonged fever\" turns out on verification to be a series of short viral illnesses, or a normal temperature measured badly *(the term fever of unknown origin and its work-up are not defined in any cached paediatrics deck -- \"fever of unknown origin\", \"FUO\" and \"prolonged fever\" as a diagnostic category all return nothing across the lecture set, whose febrile-child teaching is built around acute fever -- not taken from the course material)*. What the cached teaching does supply is exactly why verification comes first: `18) febrile child and life threatening infections.txt` specifies how a temperature must be taken in this age group -- \"by an electronic or chemical dot thermometer in the axilla or infrared tympanic thermometer\" for a child over 4 weeks -- and warns that \"axillary temperatures underestimate body temperature by 0.5°C.\" The same deck ends on \"Follow-up of the clinical course remains the most sensitive indicator in serious conditions,\" which is the same principle applied over time. Documenting the pattern on a chart also converts a vague history into the single most useful piece of data for what follows.\n\n**Why each distractor fails.** *Investigations to rule out tuberculosis* jumps to one diagnosis before the problem has been defined; tuberculosis is a legitimate cause of prolonged fever in this setting and is taught in its own cached deck, but it is pursued when the history, contact tracing or first-line results point that way, not as the opening move. *Immediate hospital admission* is driven by risk, and this child carries none of the deck's red flags -- \"Age < 1 mo, Lethargy, excess irritabilty, or toxic appearance, Respiratory distress, Petechiae or purpura, Inconsolability,\" a seizure, altered consciousness, unremitting headache, persistent vomiting or complex medical problems -- being a well two-year-old with an unremarkable examination. *Preliminary blood investigations* is the correct second step, not the first: tests ordered before the fever is verified and characterised are unfocused, and a normal set in an unverified fever answers nothing. *Broad-spectrum antibiotics after blood culture* is empirical treatment for a septic-looking or high-risk child; the deck's closing instruction is blunt -- \"Do not abuse antibiotics: FEVER does not mean ANTIBIOTIC\" -- and blind treatment here would also sterilise cultures and obscure the diagnosis.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "In a well child with a ten-day fever and an unremarkable history and examination, the first step is to verify the fever itself -- how it was measured, how high it truly is and whether it has really been continuous -- before ordering blood tests, chasing a specific diagnosis such as tuberculosis, admitting, or starting empirical antibiotics.",
  source: 'Pediatrics endpoint part1.pdf p.1473'
},

{
  id: 'pedep-mf2-77',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'neonatal',
  stem: 'A 4-week-old boy came to your clinic with persistent jaundice. He was born by SVD at term with a weight of 3.3 kg. He had an Apgar score of 9 and 9 at 1 and 5 minutes respectively and was discharged home with no concerns. On investigation, his conjugated bilirubin was 0.8 mg/dL and his unconjugated bilirubin was 14 mg/dL. The mother reports that she has always breastfed her baby and that her baby has always been well. On examination, he is jaundiced, alert, afebrile, and has a normal liver span. His current weight is 4.1 kg. Which of the following is the most appropriate management?',
  options: ["Cessation of breastfeeding.","Commence phototherapy.","Reassure the mother and continue breastfeeding.","Perform liver function tests and ultrasound abdomen."],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> This is breast milk jaundice, benign and self-limiting. No treatment needed if conjugated bilirubin is normal.\n\n---\n\nThis vignette is `8) COMMON PROBLEMS IN THE TERM NEWBORN.txt`'s definition of breast-milk jaundice, item for item: \"Unconjugated hyperbilirubinemia lasting until 2–3 months of age is common in breastfed infants,\" and \"Moderate unconjugated hyperbilirubinemia for 6– 12 weeks in a thriving breastfed infant without evidence of hemolysis, hypothyroidism, or other disease strongly suggests this diagnosis.\" Every clause is satisfied here -- the jaundice is unconjugated (14 mg/dL against a conjugated fraction of 0.8 mg/dL), the infant is thriving (3.3 kg at birth, 4.1 kg at 4 weeks), and he is alert, afebrile and has a normal liver span. The deck also separates this from \"BREAST-FEEDING–ASSOCIATED JAUNDICE,\" the \"lack of breastmilk\" jaundice of the first days caused by \"poor enteral intake and increased enterohepatic circulation,\" for which the answer is more feeding, not less; a baby who has gained 800 g is not in that group.\n\n**Why each distractor fails.** *Cessation of breastfeeding* treats a benign, self-limiting condition by removing the feed that is best for the infant; the deck's management of jaundice in a breastfed baby is to support and increase feeding, never to stop it, and the only true absolute contraindication to breastfeeding in this material's context is galactosaemia *(the specific list of absolute contraindications to breastfeeding is not set out in the cached newborn deck -- not taken from the course material)*. *Commence phototherapy* misapplies a threshold: the deck starts phototherapy \"when the TSB is approximately 6 mg/dL (102 mmol/L) lower than the predicted exchange level for that infant,\" using AAP nomograms for infants of 35 or more weeks' gestation, and those nomograms address the first days of life in a baby at risk of bilirubin neurotoxicity, not a well, thriving four-week-old. *Perform liver function tests and ultrasound abdomen* is the cholestasis work-up, and the deck sets out when it is triggered: \"Fractionated bilirubin level in infants who appear ill, those with prolonged jaundice, acholic stool, hepatosplenomegaly, or dark urine to evaluate for cholestasis.\" That fractionation has already been done here and the conjugated fraction of 0.8 mg/dL is not raised *(the numerical cut-off separating a normal from a raised conjugated fraction is not printed in the cached decks -- not taken from the course material)*, so there is no cholestasis to image. The safety net that remains is the one thing the deck insists on -- if the stools ever become pale or the urine dark, biliary atresia must be excluded urgently.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Persistent unconjugated jaundice at 4 weeks in a thriving, well breastfed infant with a normal conjugated fraction is breast-milk jaundice: reassure and continue breastfeeding, with no phototherapy, no interruption of feeding and no cholestasis work-up unless the conjugated fraction rises or stools become pale.",
  source: 'Pediatrics endpoint part1.pdf p.1477'
},

{
  id: 'pedep-mf2-78',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'perinatal-rd',
  stem: "A female infant is delivered by cesarean section at 32 weeks' gestation. Her birth weight is 1.9 kg. No resuscitation is required. At 2 hours of age, she develops respiratory distress, with a respiratory rate of 70 breaths/min, grunting respirations, and indrawing of her rib cage. Respiratory support with CPAP (continuous positive airway pressure) and 45% oxygen is required. What is the most likely reason that this baby needs respiratory support?",
  options: ["Aspiration of meconium","Patent ductus arteriosus","Surfactant deficiency","Transient tachypnea of the newborn","Early neonatal sepsis"],
  answer: 2,
  explanation: "**The endpoint file prints this explanation:**\n\n> A 32-week infant with early respiratory distress most likely has respiratory distress syndrome due to surfactant deficiency.\n\n---\n\n`9) Respiratory distress in newborn.txt` supplies both the mechanism and the risk. Surfactant is \"secreted by type ll alveolar cells,\" acts \"to decrease the surface tension inside the alveoli, thus preventing their collapse during expiration,\" and its \"synthesis begins at 24-28 weeks and is mature by 35 weeks of gestation\" -- a baby born at 32 weeks is inside that window, still short of mature production. The deck states the incidence directly: \"The incidence of RDS is inversely proportional to gestational age: 60-80% of <28wk GA, 15-30% of 32-36wk GA.\" Deficiency gives \"poor pulmonary compliance, atelectasis, decreased gas exchange and severe hypoxia and acidosis,\" which is precisely what grunting (self-generated end-expiratory pressure against collapsing alveoli), tachypnoea at 70 breaths/min and rib-cage indrawing represent, and it is why CPAP with 45% oxygen -- pressure to hold alveoli open -- is the support that is required.\n\n**Why each distractor fails.** *Aspiration of meconium* is defined in the same deck as \"respiratory distress that resulted from the aspiration of the meconium, in utero or at delivery,\" a problem of the term and post-term infant under intrapartum stress; nothing here describes meconium-stained liquor, and this baby needed no resuscitation. *Patent ductus arteriosus* is out on timing: `33)Congenital acyanotic heart disease_.txt` counts a duct as patent only when there is \"Persistence of duct more than 72h,\" and the respiratory-distress deck lists PDA as a complication that follows RDS rather than a cause of distress at 2 hours of age. *Transient tachypnea of the newborn* is the strongest distractor because caesarean delivery is its risk factor, but the deck describes it as a \"Mild and transient form of RD resulting from delayed clearance of fetal lung fluid by lymphatics\" that \"occurs in term and late preterm neonates\"; a 32-week infant needing CPAP and 45% oxygen has outgrown both the gestational range and the word mild. *Early neonatal sepsis* remains a differential that is usually covered empirically, but `11) Neonatal sepsis.txt` frames early-onset infection around risk factors -- chorioamnionitis, a previous child with GBS infection, GBS bacteriuria in pregnancy -- and none is offered here, while prematurity itself supplies a complete explanation.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective: "Respiratory distress beginning within hours of birth in a 32-week infant is respiratory distress syndrome from surfactant deficiency -- surfactant synthesis begins at 24-28 weeks and matures only by 35 weeks, and RDS affects 15-30% of infants born at 32-36 weeks -- distinguishing it from the mild, term/late-preterm course of transient tachypnoea, from meconium aspiration, from a duct that is only called patent after 72 hours, and from sepsis without risk factors.",
  source: 'Pediatrics endpoint part1.pdf p.1479'
},
