/* ===========================================================================
   ENDPOINT - Pediatrics endpoint part1.pdf - SECTION 3: "Gastroenterology"
   Verbatim staging record. PDF pages 393-549; PDF page = printed page, offset zero.
   Merged from endpoint-s03-gastro.part-A.js + endpoint-s03-gastro.part-B.js by merge-parts-ep.js.
   
   Every question is printed TWICE: an unanswered page, then the ANSWERED page with the key
   highlighted in yellow and (usually) a bordered explanation box. Only answered pages are
   staged. `n` is the true sequential index, `pr` what the page prints, `p` the PDF page,
   `key` a ZERO-BASED INDEX into `opts` (never a letter), matching the app field `answer`,
   `expl` the printed box verbatim or "".
   =========================================================================== */
var PEDEP_S03_STAGED = [

{ n:1, pr:1, p:414, key:3,
  stem:'Benjamin is a 6-year-old boy who is seen in the Paediatric Emergency Department. He has been vomiting and has had diarrhea for 3 days. His stool is watery and foul-smelling but contains no blood. He has never left the UK. Examination reveals mild dehydration but is otherwise normal. What is the most likely organism that has caused his symptoms?',
  opts:['Campylobacter','Escherichia coli','Giardia lamblia','Rotavirus','Shigella'],
  expl:'Rotavirus is a common cause of acute viral gastroenteritis in young children, especially under 5. It presents with vomiting, foul-smelling watery diarrhea, and often occurs without blood or recent travel.',
  note:'' },

{ n:2, pr:2, p:416, key:0,
  stem:'Rodney, a boisterous 2-year-old, has had diarrhea for the last 3 months. He produces up to four stools a day, which are loose, brown in color, and usually contain undigested food. The rest of the family is well. He has never been abroad. Examination is normal, and his personal child health record shows that he is growing along the 50th centile.\nWhat is the most likely diagnosis?',
  opts:['Chronic non-specific diarrhea','Coeliac disease',"Cow's milk protein allergy",'Inflammatory bowel disease','Lactose intolerance'],
  expl:"This condition, also called toddler's diarrhea, presents with chronic loose stools containing undigested food but normal growth and development. It is common in well children aged 1-5 years.",
  note:'flagged options-differ vs unanswered page — answered page options transcribed as printed' },

{ n:3, pr:3, p:418, key:1,
  stem:'Ellie is a 4-year-old girl who has been complaining of tummy pain for a month. It is worse when she goes to the toilet; her stools are firm, and she opens her bowels only every 2-3 days. She has not had any vomiting. For the last 2 weeks, her stools have become loose. On examination, she has a mass in the left iliac fossa. What is the most likely diagnosis?',
  opts:['Appendix mass','Constipation','Gastroenteritis','Intussusception',"Hirschsprung's disease"],
  expl:'Chronic constipation can lead to overflow diarrhea and a palpable fecal mass in the left iliac fossa. Pain with defecation and hard stools suggest functional constipation.',
  note:'' },

{ n:4, pr:4, p:420, key:0,
  stem:'Alysha is a 2-month-old baby who is seen in the paediatric outpatient department. She was born at term, weighing 3.5 kg, and is breastfed. Her mother is concerned as she has vomited some of the milk after most feeds since birth. She cries when she vomits. She is continuing to grow along the 50th centile. What is the most likely diagnosis?',
  opts:['Gastro-oesophageal reflux','Helicobacter pylori infection','Infant colic','Overfeeding','Pyloric stenosis'],
  expl:'Physiological reflux is common in infants due to immature lower esophageal sphincter tone. Vomiting without weight loss or systemic signs supports this diagnosis.',
  note:'' },

{ n:5, pr:5, p:422, key:0,
  stem:'Claire, a 7-year-old girl, has had abdominal pain for the last 6 months. On several occasions, it has been sufficiently severe for her to be sent home early from school. The pain happens once or twice a week in the afternoon or early evening. It is periumbilical in nature. It does not wake her at night. She has not had vomiting or diarrhoea. She is growing well. Her examination is normal. Her urine is clear on dipstick testing. What is the most likely cause for her pain?',
  opts:['Functional abdominal pain','Gastritis','Hepatitis A','Irritable bowel syndrome','Meckel diverticulum'],
  expl:'Functional abdominal pain is common in school-aged children and is not associated with red flag features like weight loss or night waking. It often affects otherwise healthy, growing children.',
  note:'flagged options-differ vs unanswered page — answered page options transcribed as printed' },

{ n:6, pr:6, p:424, key:4, box:425,
  stem:"Ben, aged 9 months, has had a 3-day history of diarrhoea and vomiting. On examination, he is found to be quiet but alert, is tachypnoeic, has a tachycardia but normal pulses, a dry mouth, no mottling of the skin but reduced skin turgor and a sunken fontanelle. The capillary refill time is 2 seconds. His blood pressure is normal for his age. He continues to vomit even with an oral rehydration solution given via a nasogastric tube. Ben's plasma sodium is found to be 156 mmol/L (normal range: 135-145 mmol/L). He needs fluid as he has clinical dehydration. How would this fluid best be replaced?",
  opts:['Immediate bolus of 20 ml/kg of 0.9% sodium chloride followed by reassessment and replacement of the remaining deficit over 24 hours with 0.9% sodium chloride solution','Rehydration over 6 hours followed by repeat urea and electrolyte measurement and maintenance fluid only for a further 18 hours','Rehydration over 24 hours with 0.18% sodium chloride/5% glucose solution','Rehydration over 24 hours with 0.9% sodium chloride/5% glucose solution','Rehydration over 48 hours with 0.9% or 0.45% saline'],
  expl:'Ben has hypernatremic dehydration, which requires slow and cautious rehydration over 48 hours to avoid the risk of cerebral oedema. Rapid correction with hypotonic fluids or quick boluses is dangerous due to the osmotic shifts involved in hypernatremia.',
  note:'flagged options-differ vs unanswered page — answered page options transcribed as printed; box printed alone on p.425, confirmed belongs to this question' },

{ n:7, pr:7, p:427, key:3,
  stem:'Matthew is a 3-day-old term infant who has not passed meconium since birth. On examination, his abdomen is distended, but the remainder of the examination is normal. An x-ray of the abdomen shows distended loops throughout the bowel, including the rectum. What is the most likely diagnosis?',
  opts:['Congenital hypothyroidism','Cystic fibrosis','Duodenal atresia',"Hirschsprung's disease",'Rectal atresia'],
  expl:"Failure to pass meconium in the first 48 hours with abdominal distension suggests Hirschsprung's disease. The rectum may still appear full on imaging due to functional obstruction.",
  note:'' },

{ n:8, pr:8, p:429, key:0,
  stem:'James, an 8-month-old infant, is brought to the Emergency Department by his parents. He is having episodes of abdominal pain and is just recovering from an upper respiratory tract infection. He seems well in between, but then suddenly seems to be in pain and looks pale. He has vomited several times. On questioning, he has had no blood in his stool but has not opened his bowels for 24 hours. Which of the following is the most likely cause of vomiting in this patient?',
  opts:['Intussusception','Diabetic ketoacidosis','Appendicitis',"Coeliac disease",'Pyloric stenosis'],
  expl:'Sudden episodic abdominal pain with pallor and vomiting in infants suggests intussusception, often post-viral. Early features may occur before the passage of red currant jelly stool.',
  note:'' },

{ n:9, pr:9, p:431, key:1,
  stem:'Bridgitta, an 8-year-old girl, presents to her family doctor with vomiting and abdominal pain. Her vomiting only started today and she has no diarrhoea or fever. She looks unwell and has clinical dehydration on examination and has deep, rapid breathing. She is thirsty and pale. She has lost weight over the last few weeks. Which of the following is the most likely cause of the vomiting in this patient?',
  opts:['Intussusception','Diabetic ketoacidosis','Appendicitis','Coeliac disease','Pyloric stenosis'],
  expl:'Vomiting with Kussmaul respiration, dehydration, and weight loss in a child points to new-onset type 1 diabetes with DKA. The absence of diarrhea supports a metabolic cause.',
  note:'' },

{ n:10, pr:10, p:433, key:4,
  stem:'Noah is 5 weeks old and has been breastfeeding well and putting on weight. However, over the last 36 hours, he has been vomiting after almost every feed. The vomit goes everywhere, and he then wants to feed again. All the vomits are milky. He was born at term (birth weight 3.8 kg). Which of the following is the most likely cause of the vomiting in this patient?',
  opts:['Intussusception','Diabetic ketoacidosis','Appendicitis','Coeliac disease','Pyloric stenosis'],
  expl:'Pyloric stenosis presents in young infants with non-bilious, forceful vomiting and hunger after vomiting. It typically appears between 2-8 weeks of age.',
  note:'' },

{ n:11, pr:11, p:435, key:1,
  stem:'Amir was born by elective caesarean section for maternal pre-eclampsia. His birthweight was 3.3 kg. He is 36 hours old. He has started to establish breastfeeding but has been vomiting after every feed. The vomit is noted by the midwife to be green. On examination, his temperature is 37.2°C. His abdomen is slightly distended. The rest of his examination is normal. Which of the following is the most likely cause of the vomiting in this patient?',
  opts:['Intussusception','Malrotation','Meningitis','Inflammatory bowel disease','Migraine'],
  expl:'Bilious vomiting in a neonate is a surgical emergency and strongly suggests malrotation with volvulus. The green vomit reflects obstruction distal to the ampulla of Vater.',
  note:'' },

{ n:12, pr:12, p:437, key:4,
  stem:'Jennifer, a 14-year-old girl, presents to the Emergency Department with a severe headache for the last 6 hours, mainly affecting the left side of her head. She just wants to lie still in the dark and dislikes being disturbed, but her mother is concerned as she has never had such an episode before and is normally a very lively girl who is doing well at school. She has been vomiting for the last 2 hours and cannot keep anything down and is also complaining of tummy pain. On examination, she is distressed by her headache and dislikes having the examination light shone on her. Her temperature is 37.2°C. She does not have neck stiffness or papilloedema. The rest of her examination is normal. Which of the following is the most likely cause of the vomiting in this patient?',
  opts:['Intussusception','Malrotation','Meningitis','Inflammatory bowel disease','Migraine'],
  expl:'This is a classic migraine presentation in an adolescent: unilateral headache, photophobia, and vomiting, with normal neurological exam and no meningeal signs. First episodes often present in adolescence.',
  note:'' },

{ n:13, pr:13, p:439, key:3,
  stem:'Max, aged 9 years, has been brought to the Emergency Department because he is crying and saying his tummy hurts. He has had a 2-day history of fever and coryza. He has been drinking orange juice but has only eaten some jelly and yogurt. He has not opened his bowels. His temperature is 38.2°C. His throat is red and he has tender cervical lymph nodes. He is not dehydrated. He has mild generalized tenderness of the abdomen, with no guarding. Which of the following is the most likely diagnosis in this patient?',
  opts:['Constipation','Pneumonia','Appendicitis','Mesenteric adenitis','Functional abdominal pain'],
  expl:'Mesenteric adenitis commonly follows a viral illness and mimics appendicitis. The presence of fever, coryza, red throat, and cervical lymphadenopathy suggests a viral etiology causing inflamed mesenteric lymph nodes.',
  note:'' },

{ n:14, pr:14, p:441, key:1,
  stem:"Pete, aged 4 years, is brought by his mother to the Emergency Department because he is crying and saying his tummy hurts. He has had a 2-day history of fever, coryza, and cough. He is sitting quietly on his mother's lap and is reluctant to play. He has a temperature of 38.2°C and a respiratory rate of 50 breaths/min. On examination, his throat is red and he has tender cervical lymph nodes. He complains of tenderness on palpation of the right upper quadrant of the abdomen. Which of the following is the most likely diagnosis in this patient?",
  opts:['Constipation','Pneumonia','Appendicitis','Mesenteric adenitis','Functional abdominal pain'],
  expl:'Abdominal pain in children can be a presenting feature of lower lobe pneumonia due to diaphragmatic irritation. The cough, coryza, fever, tachypnea, and RUQ tenderness point toward pneumonia rather than a primary abdominal pathology.',
  note:'' },

{ n:15, pr:15, p:443, key:2,
  stem:'Molly, aged 10 years, is brought to the Paediatric Assessment Unit as she has been vomiting and had central abdominal pain for 2 days. She has also had some diarrhoea. She has only had apple juice and no food for the last day. Her pain is getting worse. On examination, she has a temperature of 38.2°C and a heart rate of 110 beats/min. She has mild dehydration. There is tenderness in the lower right abdomen, but no guarding. When asked to walk, she is unable to stand up straight because of pain. Which of the following is the most likely diagnosis in this patient?',
  opts:['Constipation','Pneumonia','Appendicitis','Mesenteric adenitis','Functional abdominal pain'],
  expl:'Appendicitis presents with worsening abdominal pain, usually starting centrally and localizing to the RIF. Inability to stand upright and focal tenderness despite mild dehydration is highly suggestive of appendicitis.',
  note:'' },

{ n:16, pr:16, p:445, key:0,
  stem:'Ted, aged 2 years, has had a 2-day history of low-grade fever and coryza. His mother has brought him to the Emergency Department because he is crying inconsolably. She thinks his tummy is hurting him. He has not opened his bowels for 2 days. He appears reasonably well, has minimal abdominal tenderness, but has an indentable mass on the left side of the abdomen. Which of the following is the most likely diagnosis?',
  opts:['Constipation','Pneumonia','Appendicitis','Mesenteric adenitis','Functional abdominal pain'],
  expl:'Chronic constipation can present with a palpable fecal mass and abdominal discomfort. The minimal tenderness and history of not opening bowels support this diagnosis over acute surgical causes',
  note:'' },

{ n:17, pr:17, p:447, key:2,
  stem:'A 5-week-old baby boy is brought to the Emergency Department with a 48-hour history of projectile vomiting. The infant is hungry after vomiting and has not opened his bowels in 3 days. Clinical examination reveals a mass in the left upper quadrant. A blood gas is performed: pH 7.50, pCO2 5.5 kPa, and bicarbonate 30 mmol/L. What does this blood gas represent?',
  opts:['Normal findings','Metabolic acidosis','Metabolic alkalosis','Respiratory acidosis','Respiratory alkalosis'],
  expl:'Projectile vomiting leads to loss of gastric hydrochloric acid, resulting in metabolic alkalosis. The high pH, elevated bicarbonate, and clinical signs support this acid-base imbalance.',
  note:'stem prints "mass in the left upper quadrant" — classically pyloric stenosis presents with a mass in the right upper quadrant/epigastrium; transcribed exactly as printed' },

{ n:18, pr:18, p:449, key:0,
  stem:'A 12-year-old boy presents to the Emergency Room with a 4-hour history of groin pain. He is complaining of nausea and has vomited twice. On examination, there is tenderness and swelling of the scrotum and right testicle, with absence of the cremasteric reflex on that side. There is no fever or erythema. Routine blood tests are normal. He describes several previous episodes of short-lived pain. What is the most likely diagnosis?',
  opts:['Testicular torsion','Torsion of the hydatid of Morgagni','Inguinal hernia','Renal stone','Epididymo-orchitis'],
  expl:'Testicular torsion presents with sudden onset of unilateral testicular pain, absent cremasteric reflex, and sometimes nausea or vomiting. This is a surgical emergency and must be recognized promptly.',
  note:'' },

{ n:19, pr:19, p:451, key:0,
  stem:"A 2-month-old infant is brought to the GP by his mother. She is concerned that he vomits after every feeding. She has noticed that his abdomen has become distended. On further questioning, he opens his bowels infrequently every 3-4 days and did not pass meconium until 72 hours of age. Abdominal X-ray shows distended loops of bowel with no air in the rectum. What is the most likely diagnosis?",
  opts:["Hirschsprung's disease","Constipation due to dehydration",'Pyloric stenosis',"Cow's milk protein allergy",'Intussusception'],
  expl:"Delayed passage of meconium, chronic constipation, abdominal distension, and absence of rectal air on X-ray are classic features of Hirschsprung's disease. This is due to aganglionic segments of bowel leading to functional obstruction.",
  note:'' },

{ n:20, pr:20, p:453, key:3,
  stem:'A 7-month-old infant presents with a 12-hour history of intermittent inconsolable crying. He is mottled, has cold peripheries, and has vomited several times. Examination reveals a mass in the right upper quadrant of the abdomen. What is the most likely cause of his symptoms?',
  opts:['Colic','Incarcerated hernia','Gastroenteritis','Intussusception','Gastro-oesophageal reflux'],
  expl:'Intussusception typically presents with intermittent pain, vomiting, a palpable abdominal mass, and systemic signs like mottling and lethargy. It is a surgical emergency often seen in infants around this age.',
  note:'' },

{ n:21, pr:21, p:455, key:2,
  stem:'A 9-year-old presents with a 6-month history of non-bloody diarrhea associated with 4 kg of weight loss. His mother says he is less energetic than before and looks paler than normal. There is no history of foreign travel. Blood tests show microcytic anemia (Hb 8.9 g/dL, MCV 72) but normal inflammatory markers. What is the most likely diagnosis?',
  opts:["Crohn's disease",'Salmonella infection','Coeliac disease',"Cow's milk protein allergy",'Ulcerative colitis'],
  expl:'Chronic diarrhea, weight loss, pallor, and microcytic anemia with normal inflammatory markers are classic for coeliac disease. This autoimmune condition is triggered by gluten intake and affects nutrient absorption.',
  note:'' },

{ n:22, pr:22, p:457, key:3,
  stem:'An 8-year-old girl presents with a 6-month history of pain most days around the umbilicus, lasting for an hour and responding to paracetamol syrup. It does not usually occur at weekends. She opens her bowels daily and passes a soft stool. She is thriving, with her weight and height on the 75th centile. Which of the following is the appropriate next step?',
  opts:['Abdominal radiograph','Referral to a paediatric gastroenterologist','Inflammatory markers and liver function tests','Reassurance and no further investigation','Prescription for laxatives'],
  expl:'Chronic periumbilical pain in a thriving child with normal bowel habits and no red flags suggests functional abdominal pain. It is common and does not require further investigation if there are no alarm features.',
  note:'suspected reprint — page prints a periumbilical/functional-abdominal-pain vignette (pain around umbilicus, worse weekdays, thriving child, key: reassurance and no further investigation), not a GORD/reflux stem. Flagged by the parent as possibly reprinting the House bank\'s pedhd-gastro-22 (GORD) — parent to compare, the printed content here does not read as reflux' },

{ n:23, pr:23, p:459, key:4,
  stem:'A 6-month-old baby presents with a history of constipation since birth. Her mother has been using glycerine suppositories every 3 days to help her defecate. When she inserts the suppository, a gush of liquid stool is passed. Her mother remembers she did not open her bowels until she was 3 days old. Which of the following investigations would confirm the diagnosis?',
  opts:['Thyroid function tests','Barium enema','Bone profile','Abdominal film','Suction biopsy of the rectum'],
  expl:"A suction rectal biopsy is the gold standard for diagnosing Hirschsprung's disease. The history of chronic constipation since birth and explosive stools after rectal stimulation are key clues.",
  note:'' },

{ n:24, pr:24, p:461, key:0,
  stem:'A 9-year-old boy presents with a 24-hour history of abdominal pain, initially around the umbilicus and now localized to the right iliac fossa. His mother says he has not eaten today and has been listless. He finds it difficult to stand up straight. On examination, he is tender and guarding on palpation. What is the next step in management?',
  opts:['Referral to surgical team','Abdominal radiograph','Intravenous antibiotics','Full septic screen','Admit to the ward for review on the ward round'],
  expl:'The clinical picture is highly suggestive of appendicitis, with localized tenderness, guarding, and inability to stand upright. Urgent surgical evaluation is the appropriate next step.',
  note:'flagged options-differ vs unanswered page — answered page options transcribed as printed' },

{ n:25, pr:25, p:463, key:3,
  stem:'A 6-week-old male infant presents with a one-week history of worsening non-bilious vomiting. His mother reports that the vomiting is projectile and seems to be gradually worsening. He is eager to feed after vomiting but is having fewer wet nappies than usual. On examination, he is afebrile, appears hungry, and looks mildly dehydrated. What is the most likely diagnosis?',
  opts:["Cow's milk protein intolerance",'Gastroenteritis','Meningitis','Pyloric stenosis','Malrotation and volvulus'],
  expl:'Progressive non-bilious projectile vomiting with persistent hunger and dehydration is typical of pyloric stenosis. Diagnosis is clinical and confirmed by imaging.',
  note:'' },

{ n:26, pr:26, p:465, key:3,
  stem:'A 15-year-old girl attends a clinic concerned about episodic abdominal pain and loose stool over the past year. She dates the symptoms back to when she changed schools and says they occur more often on school days. She describes crampy abdominal pain followed by the need to pass a stool, occurring about twice a month. Her bowel habit is normal on other days. There has never been any blood, and she has not lost any weight. What is the most likely underlying cause of her symptoms?',
  opts:["Cow's milk protein intolerance",'Coeliac disease','Ulcerative colitis','Irritable bowel syndrome','Overflow diarrhea secondary to constipation'],
  expl:'Crampy abdominal pain associated with bowel habit changes, occurring during stress (school days), and without red flags suggests irritable bowel syndrome. This is a functional GI disorder common in adolescents.',
  note:'flagged options-differ vs unanswered page — answered page options transcribed as printed' },

{ n:27, pr:27, p:467, key:2,
  stem:'A mother brings in her 3-month-old girl because of repeated diarrhea and vomiting that started the day before and is currently unable to retain anything in her stomach. You find that the infant is severely dehydrated and feverish with cold extremities. What is first thing you should do?',
  opts:['cold foments and antipyretic','anti-emetic and trial of breast feeding','IV line and administer normal saline','continue breast feeding with and give ORS','IM antibiotics and oral rehydration solution'],
  expl:'The infant is severely dehydrated and hemodynamically unstable; the priority is rapid fluid resuscitation with IV isotonic saline to restore perfusion. Symptomatic treatments or oral rehydration are insufficient at this stage.',
  note:'' },

{ n:28, pr:28, p:469, key:3,
  stem:'A previously healthy 6 months old child develops paroxysmal colicky abdominal pain. The infant has occasional vomiting. Over the next 12 hours the infant passes blood and mucous and becomes progressively lethargic. Following fluid resuscitation, the most appropriate next step in management is:',
  opts:['IV antibiotics','stool culture','barium meal','abdominal US','empiric anti-dysentery therapy'],
  expl:'The presentation is classic for intussusception. Ultrasound is the diagnostic modality of choice as it is non-invasive, sensitive, and can sometimes guide reduction.',
  note:'' },

{ n:29, pr:29, p:471, key:4,
  stem:'Which is not a consequence of watery diarrhea?',
  opts:['dehydration','Hyponatremia','Hypokalemia','Hypernatremia','Metabolic alkalosis'],
  expl:'Watery diarrhea usually causes dehydration, hyponatremia, and hypokalemia; it typically leads to metabolic acidosis due to bicarbonate loss, not alkalosis.',
  note:'' },

{ n:30, pr:30, p:473, key:4,
  stem:"Which of the following is not consistent with Hirschsprung's disease?",
  opts:['No passage of meconium after 24 hours of birth','Abdominal distension','Bile-stained vomiting','Refractory constipation','Treatment is by repeated finger dilatation'],
  expl:"Hirschsprung's disease is managed surgically (pull-through procedure), not by repeated digital dilatation. Other options reflect common clinical features.",
  note:'suspected reprint of p.512 (half B) — same stem? page prints stem "Which of the following is not consistent with Hirschsprung\'s disease?" opts [No passage of meconium after 24 hours of birth / Abdominal distension / Bile-stained vomiting / Refractory constipation / Treatment is by repeated finger dilatation], key E (Treatment is by repeated finger dilatation), expl as above — parent to compare against p.512' },

{ n:31, pr:31, p:475, key:0,
  stem:'A 1-year-old presenting to the ER with abdominal colic and vomiting. X ray of the abdomen shows distended small bowel and absence of air in the distal colon and rectum, what is the diagnosis?',
  opts:['intussusception','Hirschsprung disease','Incarcerated hernia','Peptic ulcer disease','Fecal impaction'],
  expl:'The X-ray findings of distended small bowel with absence of air in the distal colon and rectum in a 1-year-old with acute abdominal colic and vomiting strongly suggest a mechanical small bowel obstruction, which is classic for intussusception in this age group',
  note:'' },

{ n:32, pr:32, p:477, key:0,
  stem:'A 6-year-old boy presents with polydipsia, polyuria and unexplained weight loss. On examination, he is lethargic and thin. His blood sugar is 34mmol/mol. His urine dipstick shows the presence of glucose and ketones, and his blood ketones are 4.0. You are about to take bloods, including a blood gas. Which ONE of these conditions should be screened for at presentation?',
  opts:['Coeliac disease','Diabetic retinopathy','Diabetic neuropathy','Diabetic nephropathy','Multiple endocrine neoplasia type 1'],
  expl:'Children with type 1 diabetes have a higher risk of autoimmune conditions, especially coeliac disease, which should be screened at diagnosis.',
  note:'' },

{ n:33, pr:33, p:479, key:1,
  stem:'A 3-week-old breastfed baby has been referred by Emergency. His parents are very concerned because he has not opened his bowels for 3d. He has episodic screaming episodes which occur mostly in the evenings. He is the first baby of non-consanguineous parents. He was born at full term by emergency C-section dt prolonged 2nd stage of labor. There was meconium stained liquor. His APGARS were 9,10 and 10, and he was discharged home the next day. He is otherwise well and feeding well. What is the MOST likely diagnosis?',
  opts:["Hirschsprung's disease",'Infantile colic','Intussusception',"Meckel's diverticulum",'Pyloric stenosis'],
  expl:"Episodic evening crying in a well-fed, healthy infant with normal growth and no systemic symptoms is typical of colic; Hirschsprung's would show persistent constipation and abdominal distension.",
  note:'' },

{ n:34, pr:34, p:481, key:1,
  stem:'A 5-week infant was brought by intractable vomiting and weight loss over the last 2 weeks. He was dehydrated, and his weight was 3 kg on feeding, visible gastric peristalsis was seen, and projectile non-bilious vomiting occurred. Abdominal examination reveals a palpable mass. The MOST suitable study for diagnosis is:',
  opts:['Plain x ray','abdomen US','Barium enema','Serum electrolytes levels','Esophageal monitoring'],
  expl:'Classic presentation of pyloric stenosis; ultrasound is the diagnostic test of choice for measuring pyloric muscle thickness.',
  note:'' },

{ n:35, pr:35, p:483, key:1,
  stem:'A 6-week-old baby boy presents to the emergency department with a history of vomiting, the vomiting has been present since the third week of life but has suddenly increased in violence and frequency over the preceding 3 days. The baby is well but hungry and failing to thrive. The most useful next step is?',
  opts:['Take an accurate feeding history and decrease feed volumes','Take a blood gas','Perform a septic screen','Start intensive gastro-oesophageal reflux therapy','Refer surgically immediately'],
  expl:'The baby’s presentation is classic for infantile hypertrophic pyloric stenosis. The immediate priority is to check a blood gas to detect the typical hypochloremic, hypokalemic metabolic alkalosis and correct it before surgery. Definitive treatment is pyloromyotomy once the infant is stabilized.',
  note:'' },

{ n:36, pr:36, p:485, key:1,
  stem:'A 9-month-old infant presents with vomiting and crying. On examination she is afebrile and has a diffusely tender abdomen. No masses are palpable. Which one of the following diagnoses is the most important to exclude?',
  opts:['Gastroenteritis','Intussusception','Mesenteric adenitis','Hirschsprung’s disease','Colic'],
  expl:'Intermittent abdominal pain with crying in an infant is a red flag for intussusception, which requires urgent diagnosis and management.',
  note:'' },

{ n:37, pr:37, p:487, key:2,
  stem:'A 5-year-old girl has had a persistent nocturnal cough for over 2 years that has not responded to Rx including inhaled steroids & bronchodilators. The cough tends to be paroxysmal & is associated with vomiting, disturbing her sleep virtually every night. She is happy & normally active during the day & did not have any exercise intolerance. In other respects, she has been well with no significant past history. There is no family Hx of asthma/eczema/allergy. Clinically, her weight was on the 75th centile & her height on the 50th centile. Examinations were normal. CXR & CBC – normal range. CRP, PEF 99%, Mantoux negative. The next most useful test that will aid the diagnosis is?',
  opts:['Bronchoscopy','CT scan of thorax','Ambulatory esophageal pH study','Barium meal','Spirometry'],
  expl:'Chronic nocturnal cough with vomiting and normal respiratory evaluation suggests gastroesophageal reflux; pH monitoring is diagnostic.',
  note:'' },

{ n:38, pr:38, p:489, key:0,
  stem:'An 8-month-old infant has had watery diarrhoea for 4 days. There has been no recent travel. Her 2-year-old sibling has recently had a similar illness, though less severe. She is drinking her normal formula milk well and is not dehydrated. What is the diagnosis?',
  opts:['Viral gastro-enteritis','Bacterial dysentery','Lactose intolerance','Giardiasis'],
  expl:'Self-limited watery diarrhea in a well-hydrated infant with a household contact points to a viral cause; supportive care is sufficient.',
  note:'page prints only 4 options (a-d)' },

{ n:39, pr:39, p:491, key:2,
  stem:'A 2-week-old infant develops fever 38.9 °C, vomiting, and irritability. His heart rate is 170/min, and RR is 40/min. The infant\'s anterior fontanelle is full, but there is no nuchal rigidity. The rest of examination is unremarkable. What is the APPROPRIATE management?',
  opts:['Oral fluid and follow up in 24 hr','Amoxicillin and follow up in 1 week','Admission to hospital for investigations and treatment','IM ceftriaxone for 5 days','IV Fluid for 6 hr and follow up in 24 hr'],
  expl:'Neonatal fever in a 2-week-old is a medical emergency; full septic workup and inpatient monitoring with empiric antibiotics are required.',
  note:'' },

{ n:40, pr:40, p:493, key:2,
  stem:'A 6-week-old male is brought to clinic with concern for frequent regurgitation of feeds. His mother reports that he vomits large volumes of curdled milk after feeding. He is interested in feeding and breast feeds without difficulty. His weight gain has averaged 32 grams per day since his last visit. On physical examination, he appears comfortable and well hydrated. A small amount of curdled milk is present in his mouth. The remainder of his examination is unremarkable. Which of the following should be used to confirm suspicion of gastroesophageal reflux in this infant?',
  opts:['Endoscopy','Esophageal pH monitoring','History and physical alone','Upper gastrointestinal series'],
  expl:'Physiological reflux in infants is diagnosed clinically; invasive tests are not needed if the baby is thriving and asymptomatic otherwise.',
  note:'page prints only 4 options (A-D)' },

{ n:41, pr:41, p:495, key:4, box:496,
  stem:'Which of the following statements is the most factually correct with regard to the administration of vitamin K to babies in the neonatal period?',
  opts:['If an oral regimen is undertaken, a single dose of oral vitamin K is recommended in all formula-fed babies','Significant bleeding in the neonatal period normally occurs in children with significant risk factors for vitamin K deficiency bleeding','The vast majority of vitamin K deficiency-associated bleeding occurs within the first week of life','There is good evidence to support an increased risk of childhood leukemia in babies given vitamin K in the neonatal period','Vitamin K deficiency bleeding is a potentially fatal disorder that is virtually preventable with one dose of vitamin K given intramuscularly at birth'],
  expl:'IM vitamin K at birth effectively prevents vitamin K deficiency bleeding, which can be severe. The risk of childhood leukemia is not supported by evidence, and most bleeding occurs after the first week in exclusively breastfed infants without prophylaxis.',
  note:'' },

{ n:42, pr:42, p:498, key:1,
  stem:'In gastroesophageal reflux, which statement is TRUE?',
  opts:['it is a rare phenomenon in infants','The parents can be reassured, it is a process the child will outgrow as they get older','Thickening the feedings does not work','Most infants have slow weight gain','Always deserves further evaluation'],
  expl:'GER is common and physiological in infants, usually resolving spontaneously by 12–18 months. Most infants grow normally and do not require intervention unless complications arise.',
  note:'flagged options-differ vs unanswered printing; not compared, only answered page transcribed' },

{ n:43, pr:43, p:500, key:1,
  stem:'Which of the following sets of signs and symptoms are most consistent with 5% dehydration?',
  opts:['Alert and responsive, warm extremities, tears with crying, normal skin turgor, moist oral mucosa','Less active than usual, sticky oral mucosa, normal or slightly diminished skin turgor, normal capillary refill time','Oliguria, sunken eyes, pale mottled skin with reduced skin turgor, prolonged capillary refill time','Oliguria, sunken eyes, tachycardia, hypotension'],
  expl:'Mild dehydration (5%) causes subtle signs like slight lethargy and sticky mucous membranes; severe signs like hypotension or tachycardia indicate greater dehydration.',
  note:'page prints only 4 options (a-d); flagged few-options and options-differ — answered page transcribed as printed' },

{ n:44, pr:44, p:502, key:0,
  stem:'Most common abdominal pain in childhood is:',
  opts:['Functional','Appendicitis','Peptic ulcer disease','Intussusception'],
  expl:'Functional abdominal pain (not due to organic disease) is the most common type in children and typically resolves without surgical or medical intervention.',
  note:'page prints only 4 options (a-d)' },

{ n:45, pr:45, p:504, key:2,
  stem:'A 6-year-old boy presents to an urgent care clinic with a history of low-grade fevers, diffuse abdominal pain, and multiple episodes of non-bloody diarrhea for the last two days. He also had one to two episodes of non-bloody, non-bilious emesis each day, but this is slowing down. He is not eating as well as usual, but he is taking small bites and drinking plenty of fluids. On evaluation, he appears tired and is not playful, but his vital signs are normal and he appears to be well-hydrated. Which of the following is the most appropriate therapeutic approach for this patient?',
  opts:['Antiemetic medication','Antimotility medication','Probiotic treatment','Zinc supplementation'],
  expl:'Acute gastroenteritis is a common infectious disease in children which manifests as frequent loose stools exceeding normal frequency with or without fever and vomiting, lasting from one day to two weeks.',
  note:'page prints only 4 options (a-d); flagged both few-options and options-differ — answered page transcribed as printed' },

{ n:46, pr:46, p:506, key:3,
  stem:'You are counselling a 3-day-old term infant who has not passed meconium since birth. On examination his abdomen is distended but the remainder of the examination is normal. An x-ray of the abdomen shows distended loops throughout the bowel, including the rectum. What is the most likely diagnosis?',
  opts:['Congenital hypothyroidism','Cystic fibrosis','Duodenal atresia','Hirschsprung disease','Malrotation'],
  expl:'Hirschsprung disease results from the absence of ganglion cells in the distal colon, causing functional obstruction. This leads to failure to pass meconium, abdominal distension, and on X-ray, dilated bowel loops including the rectum, distinguishing it from other causes like cystic fibrosis or duodenal atresia.',
  note:'' },

{ n:47, pr:47, p:508, key:4,
  stem:'Features of gastro-esophageal reflux disease in infants do NOT include the following:',
  opts:['Excessive crying','Poor weight gain','Vomiting','Anemia, malnutrition and apnea may occur','Hemoptysis'],
  expl:'GERD in infants can cause vomiting, poor weight gain, apnea, or anemia, but coughing up blood is not a typical feature.',
  note:'' },

{ n:48, pr:48, p:510, key:3,
  stem:'A 5-month-old girl presented with complaints of vomiting after feed, recurrent attacks of pneumonia, wheezy chest, and failure to thrive. The MOST likely diagnosis is:',
  opts:['Congenital hypertrophic pyloric stenosis','Faulty feeding techniques','Hirschsprung\'s disease','Gastro-esophageal reflux disease','Physiological regurgitation'],
  expl:'Recurrent aspiration due to reflux can cause respiratory symptoms and failure to thrive. Pyloric stenosis usually presents earlier with projectile vomiting.',
  note:'' },

{ n:49, pr:49, p:512, key:4,
  stem:'Which of the following is not consistent with Hirschsprung\'s disease?',
  opts:['No passage of meconium after 24 hours of birth','Abdominal distension','Bile-stained vomiting','Refractory constipation','Resolves spontaneously'],
  expl:'Hirschsprung disease is a congenital absence of ganglion cells and does not resolve spontaneously; it requires surgical intervention.',
  note:'SUSPECTED REPRINT of p.473 (half A) — page prints: "Which of the following is not consistent with Hirschsprung\'s disease? a. No passage of meconium after 24 hours of birth b. Abdominal distension c. Bile-stained vomiting d. Refractory constipation e. Resolves spontaneously" key=e "Resolves spontaneously", box: "Hirschsprung disease is a congenital absence of ganglion cells and does not resolve spontaneously; it requires surgical intervention." — parent to compare against p.473.' },

{ n:50, pr:50, p:514, key:2,
  stem:'A one-year-old boy presented to the emergency room with severe colicky abdominal pains associated with vomiting and bleeding per rectum. PR examination revealed a mass and blood on the finger on withdrawal. What is the MOST likely diagnosis?',
  opts:['Intestinal polyp','Volvulus','Intussusception','Dysentery','Hirschsprung\'s disease'],
  expl:'Classic currant jelly stools, colicky pain, and palpable mass are pathognomonic for intussusception.',
  note:'' },

{ n:51, pr:51, p:516, key:3,
  stem:'A 2-week-old baby presents with irritability and difficult feeding. On examination, a white adherent coating of the tongue and buccal mucosa is observed. There is some associated erythema and the lesion bleeds when you try to remove the white coating. Which of the following is the MOST appropriate in caring for this baby?',
  opts:['Admit to hospital and order a sepsis work-up','Admit to hospital and order a coagulation study as the lesion bleeds','Send the baby home and prescribe an oral antibiotic','Send the baby home and prescribe oral nystatin','Send the baby home and prescribe a parenteral antibiotic'],
  expl:'Oral thrush (candidiasis) presents with white patches that bleed when scraped. It is treated with topical antifungal; hospitalization is not usually needed in otherwise healthy neonates.',
  note:'' },

{ n:52, pr:52, p:518, key:2,
  stem:'A 6-year-old boy presents with joint pain, rash and severe abdominal pain. From mother\'s description, the rash has appeared in crops on his legs over the past week. What is the MOST likely diagnosis?',
  opts:['Gastric bleed','Gastric ulcer','Henoch Schonlein purpura','Systemic lupus erythematosus','Varicella zoster (chicken pox)'],
  expl:'HSP is a small-vessel vasculitis presenting with palpable purpura, abdominal pain, and arthralgia, often following upper respiratory infections.',
  note:'' },

{ n:53, pr:53, p:520, key:2,
  stem:'A 3-month-old male infant presents with episodes of drawing up his legs, crying and redcurrant jelly-like stools. What investigation would confirm the most likely diagnosis?',
  opts:['Abdominal computerized tomography (CT)','Abdominal magnetic resonance imaging (MRI)','Abdominal ultrasound','Abdominal X-ray','C-reactive protein (CRP) test'],
  expl:'Ultrasound is the diagnostic test of choice for intussusception, showing the characteristic "target" or "donut" sign.',
  note:'flagged options-differ vs unanswered printing; not compared, only answered page transcribed' },

{ n:54, pr:54, p:522, key:0,
  stem:'A common clinical condition that mimics appendicitis in children is:',
  opts:['Mesenteric lymphadenitis','Pyloric stenosis','Intussusception','Peptic ulcer disease'],
  expl:'Mesenteric lymphadenitis can cause right lower quadrant pain and tenderness, mimicking appendicitis, especially after viral infections.',
  note:'page prints only 4 options (a-d)' },

{ n:55, pr:55, p:524, key:1,
  stem:'Surgical management of gastroesophageal reflux in infants is indicated:',
  opts:['In all cases after 6 months of age','Only in severe cases not responding to medical therapy','As soon as reflux is diagnosed','In every child with vomiting'],
  expl:'Surgery is reserved for complications or failure of conservative management, not all infants with reflux.',
  note:'page prints only 4 options (a-d)' },

{ n:56, pr:56, p:526, key:2,
  stem:'In management of gastroenteritis, breastfeeding and milk feeds should be:',
  opts:['Stopped immediately','Replaced with fruit juices','Continued as usual','Delayed until recovery'],
  expl:'Breastfeeding should continue during gastroenteritis as it provides fluids and nutrients, unless contraindicated.',
  note:'page prints only 4 options (a-d)' },

{ n:57, pr:57, p:528, key:1,
  stem:'In acute appendicitis, the initial pain is typically:',
  opts:['Right iliac fossa, constant','Central, colicky','Left hypochondrium','Epigastric burning'],
  expl:'Appendicitis often starts as periumbilical, colicky pain before localizing to the right lower quadrant as inflammation progresses.',
  note:'page prints only 4 options (a-d)' },

{ n:58, pr:58, p:530, key:2,
  stem:'Maternal polyhydramnios is frequently observed in all the following conditions except:',
  opts:['Esophageal atresia','Duodenal atresia','Hirschsprung disease','Pyloric atresia'],
  expl:'Polyhydramnios is seen in conditions where swallowing is impaired (esophageal or duodenal atresia). Hirschsprung usually causes postnatal obstruction, not polyhydramnios.',
  note:'page prints only 4 options (a-d); flagged options-differ — answered page transcribed as printed' },

{ n:59, pr:59, p:532, key:0,
  stem:'A 2-month-old baby is seen in the pediatric outpatient department. She was born at term, weighing 3.5 kg, and is breastfed. Her mother is concerned as she has vomited some of the milk after most feeds since birth. She cries when she vomits. She is continuing to grow along the 50th centile. What is the most likely diagnosis?',
  opts:['Gastroesophageal reflux','Gastroenteritis','Infant colic','Overfeeding','Pyloric stenosis'],
  expl:'Reflux is common, especially if baby is thriving and growing normally. Red flags (projectile vomiting, poor growth) are absent.',
  note:'' },

{ n:60, pr:60, p:534, key:3,
  stem:'An 8-year-old girl presents with a 6-month history of pain most days around the umbilicus which lasts for an hour and responds to paracetamol syrup. It does not occur at weekends usually. She opens her bowels daily and passes a soft stool. She is thriving with her weight and height on the 75th centile. Which of the following options is the appropriate next step?',
  opts:['Abdominal radiograph','Referral to a pediatric gastroenterologist','Liver function tests','Reassurance and no further investigation','Prescription for laxatives'],
  expl:'The girl\'s pain is functional abdominal pain since growth and examination are normal, and symptoms stop on weekends. No further tests are needed.',
  note:'SUSPECTED REPRINT flagged by brief as a GORD question also in House bank, but the page as printed is NOT about GORD — it is periumbilical functional/periodic abdominal pain in an 8-year-old girl with weekday-only pattern, normal growth, responds to paracetamol. Page prints: stem as above, options A-E as above, key=D "Reassurance and no further investigation", box: "The girl\'s pain is functional abdominal pain since growth and examination are normal, and symptoms stop on weekends. No further tests are needed." Flagging the mismatch with the brief\'s description for the parent to check.' },

{ n:61, pr:61, p:536, key:1,
  stem:'An 18-month-old girl is seen in the outpatient department. She presents with loose stools two to three times each day, with no blood in them. She is generally difficult, and it has become a battle to get her to feed. Examination of her abdomen, although difficult due to distress at being examined, is unremarkable apart from being distended. She is not on any medication. Her weight was at the 9th centile and is now below the 0.4th centile. What is the most likely cause for weight loss?',
  opts:['Chronic non-specific diarrhea','Celiac disease','Hirschsprung disease','Lactose intolerance','Ulcerative colitis'],
  expl:'Failure to thrive, distended abdomen, and persistent diarrhea with weight dropping below centiles strongly suggest malabsorption due to celiac disease.',
  note:'' },

{ n:62, pr:62, p:538, key:3,
  stem:'A 2-year-old boy is seen in the pediatric emergency department. He has been vomiting and has had diarrhea for 3 days. His stool is watery and foul-smelling but has no blood in it. Examination reveals mild dehydration but is otherwise normal. What is the most likely organism that has caused his symptoms?',
  opts:['Campylobacter','Escherichia coli','Giardia lamblia','Rotavirus','Shigella'],
  expl:'Rotavirus is the most common cause of acute viral gastroenteritis in young children, presenting with watery diarrhea and vomiting.',
  note:'' },

{ n:63, pr:63, p:540, key:0,
  stem:'A 2-year-old boy has had diarrhea for the last 3 months. He produces up to four stools a day, which are loose, brown in color, and usually contain undigested food. The rest of the family is well. Examination is normal, and his personal child health record shows that he is growing along the 50th centile. What is the most likely diagnosis?',
  opts:['Chronic non-specific diarrhea','Post-gastroenteritis syndrome','Cow\'s milk protein allergy','Inflammatory bowel disease','Lactose intolerance'],
  expl:'This benign toddler\'s diarrhea shows loose stools with normal growth and no systemic illness.',
  note:'flagged options-differ in index — answered page prints 5 complete options (a-e), none truncated' },

{ n:64, pr:64, p:542, key:2,
  stem:'What is the most common cause of recurrent abdominal pain in children?',
  opts:['Appendicitis','Ascariasis','Functional','Hepatitis'],
  expl:'',
  note:'page prints only 4 options (a-d); no explanation box printed' },

{ n:65, pr:65, p:544, key:3,
  stem:'What is the most common cause of gastroenteritis in children?',
  opts:['Shigella','Giardia','Cryptosporidium','Viruses','Campylobacter jejuni'],
  expl:'',
  note:'no explanation box printed' },

{ n:66, pr:66, p:546, key:0,
  stem:'What is true about the management of gastroesophageal reflux in children?',
  opts:['Parents can be reassured; it is a process the child will outgrow as they get older','Thickening the feedings does not work','Most infants have slow weight gain','It always deserves further evaluation','Surgery is indicated in preterm infants'],
  expl:'Most infants with GER are “happy spitters,” and reassurance is sufficient. It usually resolves by 12–18 months.',
  note:'' },

{ n:67, pr:67, p:548, key:0,
  stem:'Which is a medical cause of acute abdominal pain?',
  opts:['Diabetic ketoacidosis','Thalassemia major','Hyperglycemia','Hemosiderosis','Acute hemolytic anemia'],
  expl:'',
  note:'no explanation box printed' }

];
