/* Section 8 (Allergy), part A -- pedep-alg-1 .. pedep-alg-9.
   Source: Pediatrics endpoint part1.pdf pp.911-927. Drafted from
   endpoint-s08-allergy.array.js, which is the verbatim staging record. */
{
  id: 'pedep-alg-1',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: 'Jonathan, aged 6 years, is brought to the Emergency Department after becoming unwell at a family party. He is only able to say one word at a time and indicates that he is struggling to breathe. He appears very anxious and has a raised itchy rash spreading from his face down to his chest. This has never happened before. His mother says he has asthma and uses a salbutamol inhaler for wheezy episodes.What is the most likely diagnosis?',
  options: ['Acute asthma', 'Allergic reaction', 'Anaphylaxis', 'Idiopathic urticaria', 'Inhaled foreign body'],
  answer: 2,
  explanation: '**The endpoint file prints this explanation:**\n\n> Jonathan has multi-system involvement—respiratory distress, anxiety, and an urticarial rash—following likely allergen exposure, consistent with anaphylaxis. His underlying asthma also increases the risk of severe respiratory compromise in anaphylactic reactions.\n\n---\n\nAnaphylaxis is diagnosed clinically, not by waiting to identify the trigger. The WAO 2020 criteria call it likely once there is acute onset of illness (minutes to hours) with skin/mucous-membrane involvement (Jonathan\'s spreading urticarial rash) plus at least one more system affected — here, respiratory compromise severe enough that he can only manage one word at a time. That satisfies the "unknown allergen" pathway even though nobody at the party has yet named what he reacted to. His anxiety and sense of being unwell are also typical neurological features of an evolving reaction. `27)Anaphylaxsis.txt` lists asthma and atopy among the factors that increase the risk of a reaction being severe or hard to treat, which is exactly why his existing asthma is flagged in the box rather than treated as incidental.\n\n**Why each wrong option is wrong.** *Acute asthma* could explain the breathlessness on its own, but it does not produce a spreading urticarial rash, and "this has never happened before" argues against a routine exacerbation of known asthma. *Allergic reaction* undersells the picture — once two organ systems (skin and respiratory) are involved together and acutely, the specific and more urgent diagnosis is anaphylaxis, not the vaguer umbrella term. *Idiopathic urticaria* accounts for the rash alone and has no mechanism for his breathing difficulty or anxiety. *Inhaled foreign body* can cause sudden respiratory distress in a child, but there is no choking history and it does not explain a rash spreading from face to chest.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective: 'Recognise multi-system anaphylaxis (skin plus respiratory involvement) in a child with acute-onset breathlessness and urticaria, and identify asthma/atopy as risk factors for a more severe reaction.',
  source: 'Pediatrics endpoint part1.pdf p.911'
},
{
  id: 'pedep-alg-2',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: 'What is the first step in Jonathan\'s management?',
  options: ['Administer a budesonide nebulizer', 'Assess his airway and give high-flow oxygen', 'Give intramuscular benzylpenicillin', 'Insert an intravenous cannula', 'Lie him flat'],
  answer: 1,
  explanation: '**The endpoint file prints this explanation:**\n\n> In anaphylaxis, prompt assessment of airway and oxygen delivery is essential to prevent respiratory failure. Oxygen is a priority before medications or IV access.\n\n---\n\nThe patient here is a 6-year-old boy who has just developed acute anaphylaxis — struggling to breathe, unable to speak more than one word at a time, anxious, with a spreading urticarial rash — after unwitnessed exposure to an unknown trigger at a family party. Whatever the eventual drug treatment, `27)Anaphylaxsis.txt` sets out hospital management as a sequence: rapidly assess airway, breathing, circulation, skin and body mass first, start resuscitation if indicated, and only then move to positioning and definitive drug therapy (intramuscular epinephrine remains the main therapy, but it is not one of the options offered here). Assessing his airway and giving high-flow oxygen is the correct first action because a child this breathless may be minutes from respiratory failure, and oxygenation buys time for everything that follows.\n\n**Why each wrong option is wrong.** *Budesonide nebulizer* is an inhaled steroid — it has no role as an acute rescue drug in this situation and does not address airway compromise quickly. *Intramuscular benzylpenicillin* is an antibiotic used for suspected bacterial sepsis (e.g. meningococcaemia), which is not this presentation. *Insert an intravenous cannula* will be needed for fluids and drugs, but obtaining access should never come before securing the airway and giving oxygen — the ABC sequence puts breathing ahead of circulation access. *Lie him flat* is actively unhelpful for a child in respiratory distress; supine positioning (with legs raised) is the posture used once hypotension/shock dominates the picture, not while a patient is struggling to breathe and needs to be allowed a position that eases ventilation.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective: 'Sequence the first action in suspected anaphylaxis as airway assessment and oxygen delivery, ahead of drug administration or IV access.',
  source: 'Pediatrics endpoint part1.pdf p.913'
},
{
  id: 'pedep-alg-3',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: 'Cordelia, a 5-month-old infant, was exclusively breastfed until yesterday when her mother introduced formula feeding. Soon after the feed, the baby developed a rash covering her body. She has no past medical history and is not on medications.What term best describes the rash?',
  options: ['Annular', 'Maculopapular', 'Purpuric', 'Urticarial', 'Vesicular'],
  answer: 3,
  explanation: '**The endpoint file prints this explanation:**\n\n> Urticarial rashes are raised, itchy, and often appear suddenly, especially in allergic reactions such as cow\'s milk protein allergy following formula introduction.\n\n---\n\n`26)allergy_.txt` lists urticaria as the leading cutaneous feature of an IgE-mediated food reaction, alongside angioedema, pruritus, flushing and a morbilliform rash, typically appearing 10-15 minutes and up to 2 hours after ingestion. Cordelia\'s timeline — a previously exclusively breastfed infant who develops a rash "soon after" her very first formula (cow\'s milk) feed — is exactly this pattern, so the descriptive term the question is testing is the morphology itself: raised, itchy wheals, which is what "urticarial" means.\n\n**Why each wrong option is wrong.** *Annular* describes ring-shaped lesions with central clearing, typical of conditions like tinea or erythema migrans, not an acute allergic eruption. *Maculopapular* describes flat macules mixed with raised papules, the pattern seen in viral exanthems or many drug rashes that build up over days, not a rash appearing within minutes of a feed. *Purpuric* describes non-blanching lesions from bleeding into the skin, seen in vasculitis, thrombocytopenia or meningococcal disease — a different and more serious differential entirely, with no allergic trigger implied. *Vesicular* describes fluid-filled blisters, as in chickenpox, herpes or eczema herpeticum, not the raised, itchy wheals of an acute allergic reaction.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective: 'Recognise and name the urticarial morphology of an acute IgE-mediated cutaneous food reaction, and distinguish it from other rash descriptors.',
  source: 'Pediatrics endpoint part1.pdf p.915'
},
{
  id: 'pedep-alg-4',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: 'Eddy, an 8-month-old infant, had diarrhea and vomiting with fever for three days, managed at home with oral rehydration. Vomiting resolved, but diarrhea has persisted for three weeks. Stool microscopy and culture are negative. He appears well, with a soft, mildly distended abdomen.\nWhat is the most likely cause of his prolonged diarrhea?',
  options: ['Coeliac disease', 'Giardiasis', 'IgE-mediated cow\'s milk protein allergy', 'Non-allergic food hypersensitivity', 'Non-IgE-mediated cow\'s milk protein allergy'],
  answer: 3,
  explanation: '**The endpoint file prints this explanation:**\n\n> Post-infectious or non-allergic food hypersensitivity can cause prolonged diarrhea after gastroenteritis in infants, even in the absence of a specific pathogen or allergy.\n\n---\n\n`23).1) Acute diarrhea.txt` names exactly this picture "persistent diarrhea": watery diarrhea or dysentery that begins acutely and lasts 14 days or more, also called postgastroenteritis syndrome, accounting for about 10% of acute diarrhoeal episodes with a peak age around 18 months — Eddy at 8 months, three weeks out from an acute infective illness, fits both the age band and the duration cut-off. The same source gives the mechanism: infection-related mucosal injury flattens the villi and reduces digestive enzyme output, so digestion and absorption stay impaired — producing an osmotic, food-triggered diarrhea — even after the original organism has been cleared and stool studies have gone negative. That impaired, transient reaction to feeds during mucosal recovery is what "non-allergic food hypersensitivity" refers to here, distinct from a true immune-mediated food allergy.\n\n**Why each wrong option is wrong.** *Coeliac disease* is a chronic, gluten-driven enteropathy that does not typically launch from a single resolved gastroenteritis episode, and it is diagnosed on ongoing gluten exposure and serology rather than a three-week post-infective course. *Giardiasis* would be expected to show cysts or trophozoites on stool microscopy, which is explicitly negative here. *IgE-mediated cow\'s milk protein allergy* causes rapid-onset reactions (minutes, up to about two hours after a feed) with cutaneous or systemic features such as urticaria or angioedema — not an isolated, several-week watery diarrhea with a preceding infective illness and no rash. *Non-IgE-mediated cow\'s milk protein allergy* does cause gastrointestinal symptoms including diarrhea, but its classic story is a reaction to milk protein itself (sometimes with blood in the stool from proctitis), not a diarrhoeal illness whose onset and timeline track a preceding infective gastroenteritis the way postgastroenteritis syndrome does.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective: 'Recognise postgastroenteritis (persistent diarrhea) syndrome as a cause of prolonged, culture-negative diarrhea following resolved acute gastroenteritis, and separate it from true food allergy and coeliac disease.',
  source: 'Pediatrics endpoint part1.pdf p.917'
},
{
  id: 'pedep-alg-5',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: 'A 4-year-old girl with a family history of atopy visits her GP. Her brother has a nut allergy and hay fever. Her mother wants skin-prick testing before introducing nuts.Which of the following statements about skin-prick testing is true?',
  options: ['The severity of a reaction can be predicted by the size of the skin-prick reaction', 'It detects both IgE- and non-IgE-mediated allergies', 'It is more accurate than blinded food challenge', 'Positive (histamine) and negative (saline) controls should be used to ensure test validity', 'It tests for specific serum IgE levels'],
  answer: 3,
  explanation: '**The endpoint file prints this explanation:**\n\n> Skin-prick testing requires control samples to confirm that the test was performed and interpreted correctly. It only detects IgE-mediated allergy and cannot predict severity.\n\n---\n\n`26)allergy_.txt` places skin-prick testing on the laboratory row of the IgE-mediated, immediate (Type 1) column only — it is not listed for the delayed, T-cell-mediated (Type 4) pathway, and the lecture is clear that a positive test means "sensitization," which "does not equate to allergy unless a clinical reaction is initiated on exposure." **Running a histamine (positive) and saline (negative) control alongside the allergen wheal is not itself named in the cached lecture** — *not taken from the course material* — but it is the standard methodology point being tested: the histamine control confirms the child\'s skin can mount a wheal at all, and the saline control excludes a false positive from simple skin reactivity (dermatographism), so without both, a result cannot be trusted as valid.\n\n**Why each wrong option is wrong.** *Wheal size predicting severity* is false — the lecture\'s own diagnosis pathway treats a positive test only as evidence of sensitisation, never as a severity gauge; larger wheals correlate loosely with the probability of true allergy, not with how bad a reaction would be. *Detecting both IgE- and non-IgE-mediated allergies* is false — skin-prick testing sits specifically under the IgE-mediated column, and non-IgE-mediated reactions (delayed, T-cell/GI-predominant) are not picked up by it at all. *More accurate than blinded food challenge* has it backwards — the lecture\'s own diagnostic flow places the (placebo-controlled) oral food challenge as the step used when history and allergen-specific IgE evidence are not clear, making it the more definitive test, not skin-prick testing. *Tests for specific serum IgE levels* describes a blood test (specific IgE / RAST), not skin-prick testing, which demonstrates an in-vivo cutaneous mast-cell response to the allergen rather than measuring a serum antibody level.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective: 'State the correct scope and validity requirements of skin-prick testing: IgE-mediated allergy only, sensitisation rather than severity or confirmed allergy, and the need for positive/negative controls.',
  source: 'Pediatrics endpoint part1.pdf p.919'
},
{
  id: 'pedep-alg-6',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: 'A 6-month-old boy presents with bloody diarrhea and failure to thrive. Examination is normal, and there is no vomiting. Cow\'s milk allergy is suspected.\nWhich of the following statements is true regarding food allergy?',
  options: ['It is commonly non-IgE mediated', 'RAST testing will identify all food allergies accurately', 'A positive skin-prick test to soya confirms allergy', 'Elimination/reintroduction is unhelpful', 'Most children do not outgrow their allergies'],
  answer: 0,
  explanation: '**The endpoint file prints this explanation:**\n\n> In infants, cow\'s milk protein allergy often presents as a non-IgE-mediated condition with gastrointestinal symptoms. Skin tests and RAST may be negative, and elimination/reintroduction is the diagnostic gold standard.\n\n---\n\n`26)allergy_.txt` describes non-IgE-mediated food allergy as occurring hours after ingestion, usually confined to the gastrointestinal tract, with diarrhea, vomiting, abdominal pain and sometimes faltering growth — and specifically notes it can present in an infant with blood in the stools in the first few weeks of life from proctitis. This boy\'s bloody diarrhea, failure to thrive, no vomiting and a normal examination is exactly that pattern of infant cow\'s milk protein allergy, which is why non-IgE-mediated presentations are described as common in this age group.\n\n**Why each wrong option is wrong.** *RAST testing will identify all food allergies accurately* is false on two counts: RAST measures specific IgE and so only picks up IgE-mediated reactions, missing non-IgE-mediated allergy like this case, and even for IgE-mediated allergy a positive result only shows sensitisation, not a guaranteed clinical reaction. *A positive skin-prick test to soya confirms allergy* is false for the same reason — the lecture is explicit that sensitisation "does not equate to allergy unless a clinical reaction is initiated on exposure." *Elimination/reintroduction is unhelpful* is the opposite of the lecture\'s own diagnostic approach, where an elimination diet followed by reintroduction (or a formal oral food challenge) is used precisely when history and allergen-specific IgE are unclear. *Most children do not outgrow their allergies* contradicts the lecture\'s natural history section, which states that most children outgrow milk, egg, wheat and/or soy allergies, unlike peanut, tree nut, fish and shellfish allergies, which tend to be lifelong.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective: 'Identify infant cow\'s milk protein allergy presenting with bloody stools and faltering growth as typically non-IgE-mediated, and state why RAST/skin-prick tests and elimination/reintroduction behave differently across IgE- versus non-IgE-mediated food allergy.',
  source: 'Pediatrics endpoint part1.pdf p.921'
},
{
  id: 'pedep-alg-7',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: 'A 5-month-old infant is exclusively breastfed until yesterday when her mother started her on formula as she is planning to go back to work. The mother noticed that her baby developed an urticarial rash all over her body very soon after the formula feed. What is the most likely mechanism of this baby\'s urticaria?',
  options: ['IgE-mediated cow milk allergy', 'Non-IgE mediated cow milk allergy', 'Non-allergic hypersensitivity', 'Lactose intolerance', 'Immune complex-mediated hypersensitivity reaction'],
  answer: 0,
  explanation: '**The endpoint file prints this explanation:**\n\n> Immediate urticaria after exposure is due to IgE-mediated allergy. Non-IgE allergy causes delayed GI symptoms.\n\n---\n\n`26)allergy_.txt` splits food reactions on timing and mechanism: IgE-mediated reactions appear rapidly, usually 10-15 minutes and up to about 2 hours after ingestion, with cutaneous features such as urticaria and angioedema, while non-IgE-mediated reactions typically emerge hours later and are largely gastrointestinal. This baby\'s rash appeared "very soon" after her first-ever formula (cow\'s milk protein) feed and is described as urticarial and generalised — the timing and the morphology together point specifically to an IgE-mediated mechanism, matching the lecture\'s own Type 1/immediate row of its hypersensitivity table (histamine-driven, minutes to onset).\n\n**Why each wrong option is wrong.** *Non-IgE mediated cow milk allergy* is excluded by timing — its classic pattern is delayed gastrointestinal symptoms (diarrhea, vomiting, abdominal pain) hours after a feed, not an immediate, widespread skin eruption. *Non-allergic hypersensitivity* (food intolerance) is by definition not immune-mediated, and urticaria is a mast-cell/immunoglobulin-driven skin finding that intolerance does not typically produce. *Lactose intolerance* is an enzymatic (lactase deficiency) problem causing bloating and diarrhea after lactose-containing feeds, with no mechanism for a cutaneous rash. *Immune complex-mediated hypersensitivity reaction* (Type 3) classically produces a serum-sickness-like picture — fever, joint pain, rash — typically days after exposure to the triggering protein, not urticaria appearing within minutes to a couple of hours of a single feed.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective: 'Use reaction timing and morphology to identify IgE-mediated cow\'s milk allergy as the mechanism of immediate post-feed urticaria, and separate it from non-IgE-mediated allergy, intolerance and immune-complex reactions.',
  source: 'Pediatrics endpoint part1.pdf p.923'
},
{
  id: 'pedep-alg-8',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: 'A 4-year-old child presents with vomiting and diarrhea after eating shellfish for the first time. Which of the following findings would most likely indicate a food allergy rather than food intolerance?',
  options: ['Elevated blood glucose', 'Presence of eosinophils in stool', 'Positive skin prick test', 'Elevated serum amylase', 'Negative IgE levels'],
  answer: 2,
  explanation: '**The endpoint file prints this explanation:**\n\n> Food allergy is IgE-mediated and confirmed with positive allergy testing, unlike intolerance which does not involve the immune system.\n\n---\n\n`26)allergy_.txt` draws its central distinction here: adverse food reactions split into food intolerances, which are not immune-mediated, and food allergies, which are either IgE- or non-IgE-mediated. Shellfish is named directly in the lecture as one of the most common food allergens. A positive skin-prick test demonstrates an IgE-mediated, mast-cell-driven response to the allergen — direct evidence the immune system is involved — which is what separates true allergy from intolerance, where no immune mechanism is present at all.\n\n**Why each wrong option is wrong.** *Elevated blood glucose* has no relationship to either allergy or intolerance — it is not a marker either process produces. *Eosinophils in stool* can appear in some non-IgE-mediated, GI-predominant allergic conditions, but they are nonspecific and not the standard test used to separate allergy from intolerance the way a positive allergy test does. *Elevated serum amylase* is a marker of pancreatitis and unrelated to either food allergy or food intolerance. *Negative IgE levels* would argue against, not for, an IgE-mediated allergy — a negative result is more consistent with intolerance (or a non-IgE-mediated process) than with allergy.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective: 'Distinguish food allergy from food intolerance by identifying a positive immune-mediated test (skin-prick) as evidence of allergy, versus findings unrelated to either process.',
  source: 'Pediatrics endpoint part1.pdf p.925'
},
{
  id: 'pedep-alg-9',
  bank: 'endpoint',
  module: 'pediatrics',
  chapter: 'allergy',
  stem: 'A 7-year-old girl has a history of severe allergic reactions to multiple foods. Which of the following is the most critical component of her management plan?',
  options: ['Avoidance of relevant foods', 'Carrying an epinephrine auto-injector', 'Regular skin testing', 'Routine blood tests for IgE levels', 'Consultation with a dietitian'],
  answer: 1,
  explanation: '**The endpoint file prints this explanation:**\n\n> Avoidance is important, but accidental exposure can still occur. The most critical life-saving measure is prompt administration of epinephrine in anaphylaxis, so the child must always carry an auto-injector.\n\n---\n\n`27)Anaphylaxsis.txt` sets out community emergency preparedness for a child at risk of severe reactions as, first, a self-injectable epinephrine auto-injector (EAI), then an anaphylaxis emergency action plan, then medical identification — and repeats that "the main therapy is" intramuscular epinephrine once a reaction is under way. For a girl with a documented history of severe reactions to multiple foods, the single element that converts a future accidental exposure from potentially fatal to survivable is having epinephrine on hand and ready to give immediately, since a severe reaction can progress to airway compromise or shock within minutes.\n\n**Why each wrong option is wrong.** *Avoidance of relevant foods* is genuinely foundational — `26)allergy_.txt` names it as the core of managing a food-allergic child — but it can never be guaranteed complete (cross-contamination, mislabelled ingredients, unfamiliar meals), so it cannot by itself be the "most critical" safeguard; the auto-injector is what covers the gap when avoidance fails. *Regular skin testing* is a monitoring tool used to track sensitisation over time, not an emergency intervention. *Routine blood tests for IgE levels* are likewise a diagnostic/monitoring measure, not something that treats an acute reaction. *Consultation with a dietitian* supports safe, practical avoidance and nutritional adequacy, which is valuable, but it is a supportive rather than a life-saving component of the plan.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective: 'Identify carrying an epinephrine auto-injector as the single most critical, life-saving element of a management plan for a child with a history of severe food allergy.',
  source: 'Pediatrics endpoint part1.pdf p.927'
}