/* Peds ENDPOINT PART 2, section 5 "Respiratory disorders" -- DRAFT HALF B, n:14-26 (pp.503-527).
   Drafted against content/peds/qb-pages/endpoint-p2-s05-respiratory.array.js and
   tools/bank-harness/pd-ep2-draft-brief.md. Comma-joined fragments; the splicer strips a
   trailing comma. */

{
  id:'pedep2-res-14', bank:'endpoint', module:'pediatrics', chapter:'resp-bronch',
  stem:"Jack, a 4-month-old infant, has rapid, labored breathing that has been getting worse over the last 2 days. His mother is concerned as she is struggling to get him to feed. He was born at 27 weeks' gestation, birth weight 979 g, and was discharged home at 3 months of age. On examination, he has a temperature of 37.4°C and a respiratory rate of 60 breaths/min. He is coughing. His chest is hyperinflated with marked intercostal recession. On auscultation, there are generalized fine crackles and wheezes. What is the most likely diagnosis?",
  options:['Bronchiolitis','Pneumonia','Pertussis (whooping cough)','Bronchiolitis','Laryngotracheobronchitis (croup)'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Bronchiolitis presents in infants with cough, tachypnea, wheeze, and crackles, often caused by RSV. Preterm infants are at higher risk for severe disease, and hyperinflated lungs with respiratory distress are characteristic.\n\n---\n\n**⚠️ A printed defect, reproduced exactly as it stands: option A and option D are both "Bronchiolitis," word for word.** The key is option A; the letter is positional, so choosing D scores wrong even though it names the same disease. This is a fact about the printed book, not corrected here. This five-option menu is shared with `pedep2-res-13` and `pedep2-res-15`, and the table comparing all three is anchored at `pedep2-res-13`.\n\nJack sits inside the bronchiolitis definitions on both sides of their usual disagreement: a **generalized** picture of fine crackles AND wheeze, in an infant under 12 months, with hyperinflation and marked recession — matching the European definition\'s bilateral crackles and the American Academy of Pediatrics\' wheeze-led one at once. His ex-27-week prematurity, low birth weight and recent discharge place him directly on the recognised high-risk list for severe disease, alongside chronic lung disease and cardiovascular disease. None of the shared menu\'s other three diagnoses fits this generalized, bilateral small-airway picture: pneumonia is the focal, often unilateral consolidation of `pedep2-res-15`; pertussis needs a cough running over two weeks with paroxysmal bouts and vomiting, which Jack\'s 2-day history does not have; croup is an upper-airway disease causing a barking cough and inspiratory stridor, not lower-airway crackles and wheeze.\n\nJack\'s clinical course also fits the disease\'s own timeline: a coryzal prodrome giving way to lower respiratory signs that peak several days after onset, so an infant seen this early in the illness has not yet reached his worst day. Chest radiographs and blood tests are reserved for atypical or severe cases, because the diagnosis here is made on clinical grounds alone.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Diagnose bronchiolitis in an ex-preterm infant from generalized bilateral crackles and wheeze with hyperinflation and recession, against the pneumonia/pertussis/croup options on the shared menu, and record the printed duplicate "Bronchiolitis" option without disputing the key.',
  source:'Pediatrics endpoint part2.pdf p.503'
},

{
  id:'pedep2-res-15', bank:'endpoint', module:'pediatrics', chapter:'resp-pneumonia',
  stem:'Fred is a normally well 4-year-old boy. He has had a runny nose and fever for 3 days. He has now developed a cough and difficulty breathing. On examination, his temperature is 39°C. He watches you but sits quietly on his mother’s lap. He has a respiratory rate of 55 breaths/min. His breaths are rapid but shallow with some mild substernal recession. There is no wheeze on auscultation but some coarse crackles at the right base. His oxygen saturation is 91% in air. What is the most likely diagnosis?',
  options:['Bronchiolitis','Pneumonia','Pertussis (whooping cough)','Bronchiolitis','Laryngotracheobronchitis (croup)'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Fever, localized crackles, tachypnea, and oxygen desaturation point toward pneumonia. The lack of wheeze and presence of coarse crackles at the base further support bacterial pneumonia.\n\n---\n\n**⚠️ The same printed defect as `pedep2-res-14`: option A and option D both read "Bronchiolitis," reproduced exactly as printed.** It does not bite here, because Fred\'s key is option B, not either duplicate. This is the same shared menu anchored at `pedep2-res-13` (with `pedep2-res-14`).\n\nFred is 4 years old, above the age band either bronchiolitis definition covers, and his findings are focal rather than generalized: coarse crackles localised to the **right base only**, explicitly **no wheeze**. His respiratory rate of 55/min clears the WHO tachypnoea threshold for 12 months to 5 years (>40/min) by a wide margin, and fever plus more than one sign of respiratory distress — tachypnoea, recession, an oxygen saturation of 91% — are the strongest predictors of pneumonia. Coarse crackles at one base with decreased air entry match the congestion-stage local sign of a lobar process, rather than bronchiolitis\'s bilateral picture, croup\'s stridor, or pertussis\'s paroxysmal cough with vomiting (`pedep2-res-16`), none of which Fred has.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Diagnose pneumonia from a focal right-basal crackle, absent wheeze, high fever and low saturation in a 4-year-old, using the WHO tachypnoea threshold and the strongest pneumonia predictors against the bronchiolitis/pertussis/croup options on the shared menu, and record the same printed duplicate option as `pedep2-res-14`.',
  source:'Pediatrics endpoint part2.pdf p.505'
},

{
  id:'pedep2-res-16', bank:'endpoint', module:'pediatrics', chapter:'resp-pneumonia',
  stem:'Hannah is a 3-month-old infant who has had a cough for over 2 weeks. She has now developed prolonged bouts of coughing. She has started to vomit at the end of the bout of coughing. Her temperature is 38°C. Her respiratory rate is 25 breaths/min. On auscultation of her chest, there are some scattered crackles. What is the most likely diagnosis?',
  options:['Bronchiolitis','Pneumonia','Pertussis (whooping cough)','Bronchiolitis'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Pertussis typically presents with paroxysms of coughing followed by post-tussive vomiting, especially in young infants. The prolonged cough history and classic vomiting pattern are key diagnostic clues.\n\n---\n\n**⚠️ Only FOUR options are printed on this page, the same menu as `pedep2-res-14`/`pedep2-res-15` with the croup option simply missing** — confirmed against the unanswered twin. This is the page as printed, not a transcription drop, and the printed duplicate "Bronchiolitis" at option A and option D is reproduced exactly.\n\nHannah\'s cough has run for **over 2 weeks**, well past the acute timelines of bronchiolitis, pneumonia or croup, and she now has **prolonged, paroxysmal coughing bouts followed by vomiting** — the discriminating token that sets her apart from the rest of this shared menu (`pedep2-res-14`, `pedep2-res-15`). This clinical picture is not itself printed in the cached material; the age-pathogen table names *B. pertussis* only inside its "2 weeks – 3 months" band — the band Hannah, at 3 months, sits at the very edge of — without describing the paroxysmal-cough-with-vomiting picture *(not taken from the course material)*. Her mild fever, only mild tachypnoea and scattered (rather than focal or generalized bilateral) crackles fit a catarrhal/paroxysmal course rather than bronchiolitis\'s bilateral crackles and wheeze or pneumonia\'s focal consolidation.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Diagnose pertussis from a cough of over 2 weeks with paroxysmal bouts and post-tussive vomiting, against the bronchiolitis/pneumonia options on the shared menu, and record the four-option printing (croup option absent) and the repeated "Bronchiolitis" option without disputing the key.',
  source:'Pediatrics endpoint part2.pdf p.507'
},

{
  id:'pedep2-res-17', bank:'endpoint', module:'pediatrics', chapter:'infection',
  stem:'Sara, an 8-month-old Asian girl, presents with a 3-day history of being unsettled. She has had coryzal symptoms and a mild fever. On examination of the right ear canal, you note a bulging red tympanic membrane. Her respiratory rate is 25 breaths/min, and there is no chest recession.\n\nWhich of the following is the most appropriate next step in the management of this patient?',
  options:['Oral corticosteroid','Inhaled salbutamol via metered-dose inhaler and spacer','Oral antipyretic/analgesic','Continuous positive airway pressure (CPAP)','Endotracheal intubation and ventilation'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> The presentation suggests acute otitis media. Initial management in mild cases includes oral antipyretics and analgesics for symptom relief, especially if the child is otherwise stable.\n\n---\n\nSara\'s fever-focus map points straight at her ear: the deck\'s own instruction is to **always examine the tympanic membranes in a febrile child**, because otitis media is one of the commonest sources of unexplained fever. Her bulging red tympanic membrane confirms acute otitis media, and her normal respiratory rate with no chest recession shows she is systemically well, not in respiratory distress. A well child with uncomplicated acute otitis media is managed with an oral antipyretic/analgesic for symptom relief, with antibiotics reserved for those who fail to settle or who have red-flag features not present here.\n\nThe other four options all belong to a different disease\'s management ladder, one this menu also uses for the asthma and croup questions on this page (`pedep2-res-18`, `pedep2-res-19`): an oral corticosteroid treats croup, inhaled salbutamol via spacer treats an asthma exacerbation, and CPAP or intubation are escalating respiratory-support steps for a child in respiratory failure — none of which applies to a child with a normal respiratory rate and no recession whose problem is a painful ear, not an airway.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Manage uncomplicated acute otitis media in a systemically well, non-distressed infant with an oral antipyretic/analgesic, using the fever-focus instruction to always examine the tympanic membranes, against a menu of respiratory-support and asthma/croup steps that do not apply.',
  source:'Pediatrics endpoint part2.pdf p.509'
},

{
  id:'pedep2-res-18', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:'Chardonnay is a 6-year-old Caucasian girl who has asthma. Her mother smokes cigarettes, and there is poor compliance with her preventative steroid therapy. She presents with a 2-day history of cough, runny nose, mild fever, and breathlessness. Her mother cannot recall her previous peak-flow result. On examination, she has a respiratory rate of 30 breaths/min, mild intercostal recession, and oxygen saturation of 96% in room air.\nWhich of the following is the most appropriate next step in the management of this patient?',
  options:['Oral corticosteroid','Inhaled salbutamol via metered-dose inhaler and spacer','Oral antipyretic/analgesic','Continuous positive airway pressure (CPAP)'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Inhaled salbutamol via spacer is the first-line treatment for mild asthma exacerbation. The child is stable with good oxygenation, so oral steroids or intensive measures are not immediately needed.\n\n---\n\n**Only four options are printed here** — the CPAP/intubation escalation pairing seen on this menu elsewhere in this section stops at CPAP on this page, confirmed against the twin.\n\nChardonnay\'s respiratory rate of 30/min and mild intercostal recession, with a saturation of 96% and preserved speech, place her at the **moderate** end of the acute asthma severity grading: able to talk, saturation above 92%, and a rate under the ≤40/min threshold for a 6-year-old at the mild/moderate cut. Treatment for a moderate attack starts with a SABA (salbutamol) delivered by MDI and spacer, escalating the number of puffs and reassessing response — exactly the first step this option offers. Her risk factors for a poorly controlled attack — a smoking parent and poor steroid compliance — explain why she is here, but they do not change the first step of acute management, which is graded on her current signs, not her history.\n\nAn oral corticosteroid course is added for a short course once bronchodilator treatment is under way, not chosen ahead of the bronchodilator itself. An oral antipyretic/analgesic treats fever alone and does nothing for her bronchospasm — it is the correct next step for the otitis-media picture on `pedep2-res-17`, not for an asthma exacerbation. CPAP is reserved for severe respiratory distress with a high oxygen requirement, well beyond Chardonnay\'s current picture of mild recession and a normal saturation.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Treat a moderate asthma exacerbation with inhaled salbutamol via spacer as the first step, using the severity grading by speech, saturation and respiratory rate, against oral steroid, antipyretic and CPAP options that belong to a later step or a different diagnosis.',
  source:'Pediatrics endpoint part2.pdf p.511'
},

{
  id:'pedep2-res-19', bank:'endpoint', module:'pediatrics', chapter:'resp-bronch',
  stem:'Jake, a 7-month-old infant, presents with a 2-day history of fever and runny nose. During the night, he developed a harsh cough and noisy breathing on inspiration. On examination, he has moderate inspiratory stridor and mild intercostal and subcostal recession. His respiratory rate is 30 breaths/min, temperature is 37.8°C, capillary refill time is normal, and oxygen saturation is 96% in air. Which of the following is the most appropriate next step in the management of this patient?',
  options:['Oral corticosteroid','Inhaled salbutamol via metered-dose inhaler and spacer','Oral antipyretic/analgesic','Continuous positive airway pressure (CPAP)','Endotracheal intubation and ventilation'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> This is moderate croup, indicated by stridor at rest with mild recession. Oral corticosteroids (e.g., dexamethasone) are the treatment of choice to reduce airway inflammation.\n\n---\n\nJake shares this page\'s five-option management menu with the asthma vignette `pedep2-res-18` and the otitis-media vignette `pedep2-res-17`; his own discriminating token is **inspiratory stridor at rest, following a coryzal prodrome and a harsh (barking) cough** — the classic croup picture, distinct from Chardonnay\'s wheeze-and-recession asthma picture and Sara\'s ear finding. Croup is a viral upper-airway illness, typically over 1–2 days after coryza, with a barking cough, hoarse voice and low-grade or absent fever — all present here, alongside his normal capillary refill time and a saturation of 96%, showing he is not yet in extremis.\n\nStridor present **at rest**, rather than only on crying or agitation, together with mild intercostal and subcostal recession, places Jake at the moderate end of croup severity. Oral corticosteroids (classically dexamethasone) are the standard treatment at this severity, reducing laryngeal mucosal oedema.\n\nInhaled salbutamol treats bronchospasm from asthma, not the fixed upper-airway narrowing of croup, and would not be expected to help. An oral antipyretic/analgesic does not address the airway obstruction itself. CPAP and intubation are reserved for severe or life-threatening upper-airway obstruction — increasing stridor at rest with marked recession, cyanosis, lethargy or exhaustion — none of which this moderately unwell infant shows.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Treat moderate croup (stridor at rest, mild recession, low-grade fever after coryza) with an oral corticosteroid, distinguishing it by discriminating features from the asthma and otitis-media steps sharing this menu.',
  source:'Pediatrics endpoint part2.pdf p.513'
},

{
  id:'pedep2-res-20', bank:'endpoint', module:'pediatrics', chapter:'resp-pneumonia',
  stem:'A 5-year-old boy is under outpatient review for asthma. His chest X-ray shows hyperinflation, but his symptoms remain unresponsive despite a stepwise increase in asthma therapy. Further questioning reveals delayed passage of meconium at birth, and finger clubbing is noted on examination.\nWhat is the most appropriate next step in the management of this child?',
  options:['Arrange a CT chest scan','Organize a sweat test','Test lung function using spirometry','Take a per-nasal swab','Send sputum cultures'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Atypical asthma symptoms, clubbing, and delayed meconium suggest cystic fibrosis. A sweat test is the diagnostic gold standard to confirm CF.\n\n---\n\n**This boy\'s "asthma" is the label he arrived with, not the diagnosis the history supports — the point of the question is to look past a treatment-resistant label toward the disease behind it, which is why this is filed as a pneumonia-differential question rather than an asthma one.** An asthma diagnosis that fails to respond to a stepwise increase in therapy is itself a red flag, and the recognised list of causes of recurrent or persistent pneumonia names cystic fibrosis directly as one of eight mimics of a diffuse airway disease that does not behave as expected. This boy adds two further, classic clues: **delayed passage of meconium at birth** and **finger clubbing**. *(Not taken from the course material: delayed passage of meconium beyond 48 hours raises meconium ileus, a bowel obstruction from abnormally thick, viscid meconium and the single most CF-specific of all its neonatal presentations, since CF accounts for the large majority of meconium ileus cases; finger clubbing reflects chronic hypoxaemia and suppurative lung disease, another CF hallmark. The sweat test, measuring chloride concentration in sweat and elevated because the defective CFTR channel fails to reabsorb chloride in the sweat duct, is the standard confirmatory investigation for cystic fibrosis, and neither "meconium ileus" nor "sweat test" is taught directly in the cached lecture material.)*\n\nA CT chest scan might eventually show bronchiectasis in established CF but does not establish the diagnosis itself. Spirometry monitors severity in an already-diagnosed airway disease but cannot distinguish asthma from CF, and it does not address the meconium history or clubbing. A per-nasal swab tests for pertussis (`pedep2-res-16`), not a chronic, treatment-unresponsive picture with clubbing. Sputum cultures may eventually identify organisms colonising CF airways later in the disease course, but they do not establish the diagnosis now.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Recognise cystic fibrosis behind a treatment-unresponsive "asthma" label from delayed meconium passage and finger clubbing, and select the sweat test as the confirmatory next step, using the recurrent/persistent pneumonia cause list to place cystic fibrosis on the differential.',
  source:'Pediatrics endpoint part2.pdf p.515'
},

{
  id:'pedep2-res-21', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:'A 4-year-old girl is under outpatient review for asthma. Her regular treatment includes a preventative steroid inhaler at 200 micrograms twice daily and a reliever inhaler used approximately once every two weeks. However, over the last 3 months, she has used her reliever every other day, and her nocturnal coughing has increased, disturbing her sleep.\nWhat is the appropriate next step in care for this child?',
  options:['Continue on the same dose of steroid inhaler','Increase the steroid inhaler dose to 400 micrograms BD','Start a course of oral steroids','Start oral theophylline','Add a long-acting beta agonist'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Step-up therapy in asthma with poorly controlled symptoms despite low-dose ICS includes adding a long-acting beta agonist (LABA). Increased reliever use and night-time symptoms indicate poor control.\n\n---\n\nThis girl has moved from reliever use roughly fortnightly to every other day over 3 months, with new nocturnal cough disturbing her sleep — by the standard control goals (no reliever use beyond twice weekly, no night symptoms), she has clearly slipped from controlled to poorly controlled on her current low-dose inhaled steroid. The stepwise treatment ladder moves from step 2 (low-dose ICS) to step 3 (low-dose ICS plus a long-acting beta agonist) when control is not achieved, adding therapy in sequence rather than simply repeating the same step.\n\nContinuing unchanged ignores the escalating reliever use and new night symptoms that define loss of control. Doubling the steroid dose to 400 micrograms BD is a reasonable-sounding option, but the ladder\'s next rung after an inadequately controlled low-dose ICS is an add-on agent rather than a bare dose increase. A course of oral steroids is reserved for an acute exacerbation needing systemic treatment, not for stepping up stable but poorly controlled maintenance therapy (the situation instead facing `pedep2-res-25`). Oral theophylline is a recognised option, but later on the ladder than a LABA, not the first agent added.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Step up chronic asthma maintenance by adding a long-acting beta agonist when reliever use and nocturnal symptoms escalate on an existing low-dose inhaled steroid, using the stepwise long-term management ladder.',
  source:'Pediatrics endpoint part2.pdf p.517'
},

{
  id:'pedep2-res-22', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:'A 3-year-old girl is admitted with a 3-day history of coryzal symptoms followed by acute onset of breathing difficulty. She is otherwise fit and well, apart from mild eczema, and her parents are non-smokers. She is thriving. On examination, she has widespread wheeze without crepitations.\nWhat is the most likely diagnosis?',
  options:['Viral wheeze','Asthma','Heart failure','Bronchiolitis','Recurrent aspiration'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> In children under 5, wheeze triggered by viral infections without interval symptoms is termed viral wheeze. It is common and self-limited in otherwise healthy children.\n\n---\n\nThis girl\'s picture sits inside the definition of viral episodic wheeze, and every feature that would instead point to asthma is explicitly absent. She has a coryzal prodrome (3 days) followed by acute widespread wheeze, is previously fit and well, thriving, with mild eczema noted but no other atopic or environmental risk (non-smoking parents). The recognised three-pattern wheeze table distinguishes viral episodic wheeze from multiple trigger wheeze and asthma on exactly one question — are there symptoms **between** the colds? — and her single, cold-triggered episode with no stated interval symptoms answers that question. At 3 years she is also below the age at which a formal asthma diagnosis and confirmatory tools such as a peak-flow diary become reliably usable.\n\nAsthma would need either recurrent episodes or interval symptoms between colds, neither of which this single-episode vignette describes. Heart failure would be expected to show additional signs such as hepatomegaly or poor perfusion, and a coryzal illness is not its typical trigger. Bronchiolitis centres on crackles (European definition) or wheeze with retractions typically under 12 months, usually with bilateral crackles present — this girl explicitly has **no crepitations**, and at 3 years she is above the age band either definition specifies. Recurrent aspiration would need a history of feeding difficulty, vomiting or a neurological/anatomical risk factor, none of which is given.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Diagnose viral episodic wheeze from a single cold-triggered episode of widespread wheeze with no crepitations and no interval symptoms in a thriving 3-year-old, using the three-pattern wheeze table to exclude asthma, bronchiolitis, heart failure and recurrent aspiration.',
  source:'Pediatrics endpoint part2.pdf p.519'
},

{
  id:'pedep2-res-23', bank:'endpoint', module:'pediatrics', chapter:'resp-pneumonia',
  stem:'A 4-year-old girl is admitted with fever, difficulty breathing, and cough. A diagnosis of left lower lobe pneumonia is made and intravenous antibiotics are commenced. What is the most likely pathogen?',
  options:['Streptococcus pneumoniae','Haemophilus influenzae','Mycoplasma pneumoniae','Chlamydia trachomatis','E. coli'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Strep pneumoniae is the most common cause of community-acquired pneumonia in this age group. Fever, cough, and lobar consolidation are typical features.\n\n---\n\n**Option E prints as "E. coli" — the bacterium\'s standard abbreviation, not a stray option-letter artefact** — confirmed against the unanswered twin, reproduced exactly and not stripped to "coli."\n\nA 4-year-old falls in the age-pathogen table\'s 3 months to 5 years band, which names *Haemophilus influenzae* and *Streptococcus pneumoniae* as the leading bacterial causes, but the same source states directly that **Strep. pneumoniae is the commonest bacterial cause of community-acquired pneumonia after the neonatal period** — reinforced by its own aetiology figures, where *Streptococcus pneumoniae* is the single largest slice at 34%. A lobar (left lower lobe) pattern is also the classic radiological picture of pneumococcal disease, matching both the age band and the general rule.\n\n*Haemophilus influenzae* is named in the same age band, but the material explicitly ranks pneumococcus as the commoner cause after the neonatal period. *Mycoplasma pneumoniae* is assigned to the older, over-5-years band, not this 4-year-old\'s. *Chlamydia trachomatis* and *E. coli* are both assigned to the birth-to-4-weeks neonatal band, from perinatal transmission — far younger than this previously well 4-year-old.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Identify Streptococcus pneumoniae as the commonest bacterial cause of community-acquired pneumonia in a 4-year-old, using the age-pathogen table and its explicit ranking of pneumococcus above the other age-appropriate organisms, and record the "E. coli" printing verbatim.',
  source:'Pediatrics endpoint part2.pdf p.521'
},

{
  id:'pedep2-res-24', bank:'endpoint', module:'pediatrics', chapter:'infection',
  stem:'A 24-month-old girl with trisomy 21 attends for her developmental review. Her mother is concerned about her hearing and explains that she has had two recent right ear infections within the last 5 months. An audiogram is carried out, which confirms a conductive hearing loss of the right ear. What is the most likely explanation for this finding?',
  options:['Congenital infection','Otitis media with effusion','Acquired meningitis','Antibiotic toxicity','Foreign body'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Children with Down syndrome are prone to OME due to eustachian tube dysfunction. This leads to conductive hearing loss, especially following recurrent ear infections.\n\n---\n\n**Filed here rather than under genetics: the discriminating fact is the ear disease and its mechanism, not the trisomy 21 itself, which only raises how commonly this happens** — the same craniofacial examination material for Down syndrome names small ears among its features without linking that to otitis media or hearing loss, so the genetics chapter does not carry the answer.\n\nThis girl\'s history of two recent right-sided ear infections culminating in a confirmed **conductive** hearing loss on the same side follows directly from the standing instruction to always examine the tympanic membranes in a febrile child (`pedep2-res-17`), extended here to its downstream consequence. *(Not taken from the course material: repeated middle-ear infection commonly leaves behind persistent middle-ear effusion — "glue ear" — which mechanically dampens sound conduction through the ossicular chain and produces a conductive rather than sensorineural loss; children with trisomy 21 are additionally known to be at higher risk of middle-ear disease from relatively narrow Eustachian tubes and hypotonia.)* Conductive hearing loss following recurrent acute otitis media is a recognised, common outcome, matching this audiogram exactly.\n\nCongenital infection would be present from birth, not developing after two recent, separately timed infections at 24 months. Acquired meningitis classically causes **sensorineural** loss from cochlear damage, not conductive loss, and no meningitis history is given. Antibiotic (aminoglycoside) toxicity is also classically sensorineural and needs a specific exposure history not given here. A foreign body would be an incidental canal finding, not an explanation for a confirmed conductive loss following two documented infections.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Diagnose otitis media with effusion as the cause of conductive hearing loss following recurrent acute ear infections, using the standing instruction to examine the tympanic membranes, and tag the trisomy-21-specific susceptibility as outside the course material.',
  source:'Pediatrics endpoint part2.pdf p.523'
},

{
  id:'pedep2-res-25', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:"A 6-year-old boy with known asthma has been brought in by ambulance to the local emergency department with an acute severe exacerbation. He has already received salbutamol and ipratropium nebulizers together with an intravenous steroid. Upon reassessment, he appears exhausted with varying responsiveness. Fifteen liters of oxygen are needed to maintain his saturations, and auscultation of his chest reveals minimal breath sounds. What is the next most important step in this child's care?",
  options:['Reassess 30 minutes later','Give intravenous antibiotics','Request a chest X-ray','Give intravenous salbutamol','Admit to ward'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> This is a life-threatening asthma exacerbation with poor air entry and fatigue. IV salbutamol is the next escalation step after nebulizers and steroids.\n\n---\n\nThis boy has already had the standard severe-attack treatment — nebulized salbutamol and ipratropium plus IV steroid — yet on reassessment he is exhausted with varying responsiveness, needs a very high oxygen flow to maintain saturation, and has minimal breath sounds. **A silent chest is not improvement — wheeze needs airflow to exist**, and minimal breath sounds signal near-complete airway obstruction rather than resolution. Exhaustion, altered responsiveness and a high oxygen requirement are named life-threatening features in their own right. When first-line nebulized and IV steroid therapy has already been given without turning the picture around, treatment escalates to the IV therapies not yet used, including IV salbutamol, alongside urgent senior and PICU involvement.\n\nWaiting 30 minutes to reassess delays escalation a child already showing life-threatening markers cannot safely wait for. Nothing in the vignette suggests a bacterial process driving this exacerbation, so IV antibiotics do not fit. A chest X-ray is used in a child not responding to exclude pneumothorax or infection, but it does not treat the immediate, escalating obstruction. Admission to a ward is a step down in the level of care for a child whose signs mark him for escalation, not routine admission.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Escalate to intravenous salbutamol in a child with life-threatening asthma showing exhaustion, varying responsiveness and a silent chest despite nebulized and IV steroid treatment already given, using the severity grading and treatment ladder for a failing acute attack.',
  source:'Pediatrics endpoint part2.pdf p.525'
},

{
  id:'pedep2-res-26', bank:'endpoint', module:'pediatrics', chapter:'resp-bronch',
  stem:'Bronchiolitis is one of the most common respiratory conditions affecting infants. Which of the following is not a clinical feature of bronchiolitis?',
  options:['Tachypnoea','Apnoea','Wheeze','Fine crackles','Paroxysmal cough'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Bronchiolitis causes tachypnea, wheeze, and fine crackles but does not present with paroxysmal cough, which is more characteristic of pertussis.\n\n---\n\n**A note on the printed text: the stem and options spell "Tachypnoea/Apnoea," while the box spells "tachypnea" — both transcribed exactly as printed on their respective source, without harmonising the spelling.**\n\nThis is a direct recognition question against the bronchiolitis definitions used across this shared menu (`pedep2-res-14`/`pedep2-res-15`/`pedep2-res-16`): tachypnoea, retractions and bilateral crackles or wheeze are the named core clinical features, and apnoea is separately named as an indication for hospital admission in bronchiolitis in its own right. That leaves **paroxysmal cough** as the one option that is not part of the bronchiolitis picture — it is instead the signature feature of pertussis, the prolonged, paroxysmal coughing bout followed by vomiting already established as the discriminator between bronchiolitis and pertussis on the shared menu at `pedep2-res-14` through `pedep2-res-16`.\n\nTachypnoea, apnoea, wheeze and fine crackles are each directly named bronchiolitis features or admission indications, so none of them is the odd one out; only paroxysmal cough belongs to a different disease.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Recognise paroxysmal cough as the pertussis feature that is the odd one out against tachypnoea, apnoea, wheeze and fine crackles, all directly named as bronchiolitis features or admission indications.',
  source:'Pediatrics endpoint part2.pdf p.527'
}
