/* Draft half A of section 5 "Respiratory disorders" -- entries pedep2-res-1 through pedep2-res-13.
   Source of truth: endpoint-p2-s05-respiratory.array.js (PEDEP2_S05_STAGED n:1-13).
   Grounding: content/peds/lectures/specific bacterial infection.txt (GABHS pharyngitis, Hib
   epiglottitis, otitis media), Asthma_.txt (diagnosis, severity table, delivery devices,
   wheeze differential list including foreign body aspiration), 32)Acute bronchiloitis_.txt
   (bronchiolitis definition and RSV spectrum), infectious diseases causing maculopapular
   rash.txt (measles, infectious mononucleosis) and vesicular rash.txt (HSV gingivostomatitis).
   Croup is not covered by any cached lecture. The chapter here follows the ruling written into
   app/data/theory.peds.js, which states it twice in the 'infection' chapter -- "Pneumonia and
   croup as diseases are `resp-pneumonia`/`resp-bronch`" and "No cached deck teaches croup as a
   disease -- it belongs to `resp-bronch`" -- so n:10 and n:13 are filed 'resp-bronch'. Part 1's
   pedep-inf-68 files a croup question under 'respiratory' and therefore disagrees with that
   ruling; it is another chat's live file and is recorded here, not changed.
   Stripped by the splicer; not part of the app data shape. */

{ id:'pedep2-res-1', bank:'endpoint', module:'pediatrics', chapter:'infection-bact',
  image:'q-pd-ep2-477',
  imgAlt:'A clinical photograph of the oropharynx.',
  stem:'Liam, a 7-year-old boy, complains to his family doctor of a sore throat and has a mild fever. The appearance of his throat is as shown in the opposite figure. What is the most likely diagnosis?',
  options:['Diphtheria','Glandular fever (Epstein–Barr virus)','Group A Streptococcal tonsillitis','Measles','Herpes simplex stomatitis'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Streptococcal tonsillitis presents with sore throat, fever, and tonsillar exudates, especially in school-aged children. The absence of systemic features like rash or gray pseudomembrane helps exclude other options like measles or diphtheria.\n\n---\n\nThe cached bacterial-infection lecture describes Group A Streptococcal (GABHS) pharyngitis as a sudden sore throat with fever and beefy red tonsils, often with white exudate, and states it "crucially...usually lacks a cough or runny nose" (specific bacterial infection.pdf) -- exactly Liam\'s picture: an acute sore throat with mild fever and no coryzal symptoms mentioned, and a photograph showing erythematous, enlarged tonsils carrying yellowish surface exudate.\n\nDiphtheria classically produces a thick grey-white pseudomembrane across the tonsils and posterior pharynx that bleeds if scraped, together with marked systemic toxicity from exotoxin; this disease is not covered in the cached lecture material -- not taken from the course material. Liam\'s throat shows exudate confined to the tonsillar surface, not a spreading membrane, and he is only mildly unwell.\n\nGlandular fever (infectious mononucleosis, EBV) is described in the cached exanthem lecture as a triad of fever, pharyngitis and lymphadenopathy, with fever often high (up to 40°C) and prominent posterior cervical lymphadenopathy, sometimes with a faint rash or a florid rash if amoxicillin is mistakenly given (infectious diseases causing maculopapular rash.pdf). Liam has none of the lymphadenopathy or high, sustained fever this illness typically produces, favouring the simpler bacterial picture.\n\nMeasles is taught in the same lecture as a prodrome of cough, coryza and conjunctivitis (the "three Cs") with pathognomonic Koplik spots before a cephalocaudal rash -- a respiratory and mucocutaneous illness, not an exudative tonsillitis, so it does not fit a photograph confined to the throat with no rash or cough described.\n\nHerpes simplex (herpetic gingivostomatitis) is described in the cached vesicular-rash lecture as a painful ulcerative process of the anterior mouth and gums in a child aged 6 months to 5 years, not a tonsillar exudate -- the site and appearance in the figure do not match.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Recognise beefy red, exudative tonsils with fever and no coryza as GABHS pharyngitis, and separate it from the exanthems and mucosal infections it is confused with.',
  source:'Pediatrics endpoint part2.pdf p.477' },

{ id:'pedep2-res-2', bank:'endpoint', module:'pediatrics', chapter:'infection',
  image:'q-pd-ep2-479',
  imgAlt:'An endoscopic image of the airway taken during intubation.',
  stem:'Mohammed, a 5-year-old refugee from Somalia, presents acutely unwell to the Emergency Department. He has a 1-day history of sore throat and a high temperature (40.1°C). Over the last 8 hours, he has been having increasing difficulty breathing with quiet stridor. He has never been immunized. He is noted to be unable to swallow his saliva. The opposite figure was taken when he was intubated. What is the most likely diagnosis?',
  options:['Bacterial tracheitis','Croup','Epiglottitis','Foreign body','Laryngomalacia'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Epiglottitis presents acutely with high fever, drooling, muffled voice, stridor, and inability to swallow. In an unimmunized child, Haemophilus influenzae type b is a likely cause and requires urgent airway management.\n\n---\n\nThe cached bacterial-infection lecture ties this picture together directly: Hib epiglottitis presents with rapid-onset high fever, severe sore throat and drooling from inability to swallow, with stridor and a "hot potato" voice, and it specifically names the unimmunized child as at risk since the vaccine targets this organism (specific bacterial infection.pdf). Mohammed\'s 40.1°C fever, one-day sore throat, drooling and lack of any vaccination all match this teaching precisely, and the endoscopic photograph -- a swollen, cherry-red, rounded mass filling the airway around the endotracheal tube -- is the classic intubation appearance of an inflamed epiglottis.\n\nBacterial tracheitis can mimic epiglottitis but classically follows a preceding viral croup-like illness with a more gradual, biphasic course and copious purulent tracheal secretions rather than the abrupt drooling-and-stridor onset described here -- not taken from the course material beyond the Hib teaching already cited.\n\nCroup (viral laryngotracheobronchitis) typically causes a barking cough with a more gradual coryzal prodrome and is not usually associated with drooling or inability to swallow saliva, which reflects epiglottic, not subglottic, swelling.\n\nForeign body aspiration causes sudden-onset choking and localized wheeze rather than a febrile illness with progressive sore throat and drooling over hours.\n\nLaryngomalacia is a congenital cause of chronic inspiratory stridor presenting in early infancy, not an acute febrile illness in a 5-year-old.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Recognise Hib epiglottitis in an unimmunized child from high fever, drooling and stridor, and distinguish it from croup, tracheitis, foreign body and laryngomalacia.',
  source:'Pediatrics endpoint part2.pdf p.479' },

{ id:'pedep2-res-3', bank:'endpoint', module:'pediatrics', chapter:'resp-pneumonia',
  stem:'Amber, a 9-month-old girl, presents with a 4-day history of coughing spasms which are followed by vomiting. A whooping cough (Bordetella pertussis infection) is suspected. Which of the following tests would be most useful in confirming the diagnosis?',
  options:['Blood culture','Chest X-ray','Full blood count and film','Nasopharyngeal aspirate','Pernasal swab'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Whooping cough (pertussis) is best confirmed with a pernasal swab for PCR or culture of Bordetella pertussis. Symptoms include paroxysmal cough followed by vomiting and inspiratory "whoop."\n\n---\n\nThe cached pneumonia lecture lists Bordetella pertussis among the recognised bacterial respiratory pathogens of childhood (30) Pneumonia.pdf, and Amber\'s paroxysmal coughing spasms ending in vomiting is the classic pertussis presentation. The specific choice of a pernasal swab -- taken from deep in the nasopharynx, where B. pertussis colonises the ciliated respiratory epithelium, for culture or PCR -- as the confirmatory test of choice is not detailed beyond that pathogen mention in the cached material -- not taken from the course material.\n\nBlood culture samples the bloodstream and is not useful because pertussis is a localized mucosal respiratory infection rather than a bacteraemic illness.\n\nChest X-ray may show a "shaggy" right heart border or perihilar changes in complicated pertussis but does not confirm the causative organism; it supports, rather than establishes, the diagnosis.\n\nA full blood count and film may show a striking lymphocytosis in pertussis, which is a supportive clue but not a specific confirmatory test, since lymphocytosis has many other causes.\n\nA nasopharyngeal aspirate, while similarly sited to a pernasal swab and used to diagnose viral bronchiolitis pathogens such as RSV, is not the sample of choice for B. pertussis, which is better recovered by a dedicated pernasal (calcium-alginate or Dacron) swab plated directly onto selective culture medium or sent for PCR -- not taken from the course material.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Identify a pernasal swab, not a nasopharyngeal aspirate or nonspecific test, as the confirmatory investigation for suspected pertussis.',
  source:'Pediatrics endpoint part2.pdf p.481' },

{ id:'pedep2-res-4', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:"Tak, a 3-year-old Asian boy, presents to his family doctor. He has a 'hacking' cough that started several weeks ago and has failed to respond to two courses of antibiotics. He is otherwise well and has had no previous chest problems. On examination, there is decreased air entry in the right lower zone with normal percussion noted. His growth is normal. What is the most appropriate next step?",
  options:['Admit for intravenous antibiotic therapy','Assess bronchodilator response','Organize ultrasound-guided drainage of his pleural effusion','Request a chest X-ray','Request a sweat test and evaluation of immunoglobulins and functional antibodies'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> In a child with chronic cough and localized findings (decreased air entry), a chest X-ray is the first investigation to rule out pneumonia, foreign body, or structural abnormalities.\n\n---\n\nThe cached asthma lecture\'s "red flag" list warns that a persistent, focal chest finding in an otherwise normal, thriving child is not typical asthma and should prompt investigation rather than empirical treatment (Asthma_.pdf); Tak\'s normal growth and isolated, localized sign (decreased air entry, right lower zone, but normal percussion, so no established consolidation or effusion yet) is exactly the kind of unexplained localized finding that calls for imaging before anything more invasive.\n\nAdmission for intravenous antibiotics is premature: two oral courses have already failed, so simply repeating antibiotic therapy without first imaging the chest to look for an alternative explanation (partial obstruction, foreign body, structural anomaly) does not address why treatment has not worked.\n\nAssessing bronchodilator response presumes an asthma diagnosis, but Tak has no previous chest problems and a focal, not diffuse, sign -- not the generalized wheeze pattern asthma produces.\n\nOrganizing pleural drainage is premature and unsupported: percussion is normal, so there is no evidence of pleural fluid to drain.\n\nA sweat test and immunoglobulin/antibody work-up is the right direction for a child with recurrent or unexplained chest disease but is a second-line investigation once a chest X-ray has first localized and characterized the problem -- ordering it before imaging skips a simpler, faster, and cheaper first step.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Choose chest X-ray as the first investigation for a focal chest sign with a chronic, antibiotic-unresponsive cough, ahead of more invasive or more specialised tests.',
  source:'Pediatrics endpoint part2.pdf p.483' },

{ id:'pedep2-res-5', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:'Amir, a 4-year-old boy, presents to his family doctor with a history of eczema, rhinitis, chronic nocturnal cough, and intermittent wheeze. Asthma is suspected, and a bronchodilator is prescribed. How should his bronchodilator be delivered?',
  options:['Dry powder inhaler','Metered-dose inhaler (MDI)','Metered-dose inhaler with large-volume spacer','Nebulizer','Syrup'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> In preschool children, bronchodilators should be delivered via an MDI with a spacer for optimal lung deposition. Dry powder inhalers are not suitable for young children due to insufficient inspiratory flow.\n\n---\n\nThe cached asthma lecture\'s device table states an MDI with a spacer "is suitable for all ages as it doesn\'t need cooperation or effort," delivered by face mask under 3 years and by mouthpiece from 3 years -- exactly Amir\'s age -- while a dry powder inhaler needs a forceful inspiratory effort and is only suitable from age 6 upward (Asthma_.pdf).\n\nA plain metered-dose inhaler (no spacer) needs the coordinated "press and slow deep breath, then hold" technique the lecture reserves for adolescents who can cooperate; a 4-year-old cannot reliably coordinate actuation with inspiration.\n\nA dry powder inhaler is explicitly excluded at this age by the same table for needing high inspiratory flow that a 4-year-old cannot generate.\n\nA nebulizer is reserved in the same lecture\'s treatment tables for acute, moderate-to-severe exacerbations requiring high drug delivery under supervision, not for routine home maintenance dosing in a stable outpatient like Amir.\n\nBronchodilators are not formulated or recommended as an oral syrup in the cached teaching; oral beta-agonists have slower onset and more systemic side effects than an inhaled route, and are not part of the delivery options the lecture describes -- not taken from the course material beyond the device table already cited.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Match MDI-with-spacer as the age-appropriate bronchodilator delivery device for a preschool child, ahead of a plain MDI, dry powder inhaler, nebulizer or syrup.',
  source:'Pediatrics endpoint part2.pdf p.485' },

{ id:'pedep2-res-6', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:'Sarah, a 10-year-old girl, has frequent attacks of asthma. She attends the Emergency Department with increasing difficulty breathing over the last 12 hours. Initial observation shows that she is anxious, sitting upright, has a marked tracheal tug, and is unable to complete a sentence. Which of the following statements is most likely to be correct?',
  options:['Sarah’s asthma attack is of moderate severity','Sarah’s condition is likely to improve if she is encouraged to lie flat','Sarah’s oxygen saturation should be measured','Sarah should be taken promptly to the X-ray department for a chest X-ray','The lack of wheeze should make you consider a panic attack'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> In a child with severe asthma signs, oxygen saturation is essential to assess respiratory compromise. Lying flat would worsen symptoms, and the lack of wheeze does not exclude asthma—it may indicate silent chest.\n\n---\n\nThe cached asthma lecture\'s exacerbation-severity table, for a child aged 6 years and older, defines "words/unable to speak" (rather than sentences) as a severe/life-threatening feature, alongside agitation, tachycardia and tachypnoea (Asthma_.pdf); Sarah is 10 years old and cannot complete a sentence, so she already meets a severe criterion, and the same table mandates giving oxygen "to keep SO2 = 94-98%" -- which first requires measuring her saturation to know how much she needs and to track her response to treatment.\n\nHer attack is not moderate: inability to complete a sentence and marked tracheal tug (accessory-muscle recruitment) are severe features by the lecture\'s own table, not the milder "sentences, normal cry" category.\n\nLying flat is dangerous, not helpful, in an acute severe asthma attack: children in extremis instinctively sit upright to maximise diaphragmatic excursion and accessory muscle use, and forcing recumbency would worsen her work of breathing -- not taken from the course material beyond the sitting-upright sign already described.\n\nSending her to the X-ray department is inappropriate: a severe exacerbation needs her kept in a monitored resuscitation area for immediate nebulized treatment and oxygen, not transport away from care for imaging that will not change immediate management.\n\nThe absence of a wheeze mentioned in this vignette is not reassuring: the same severity table specifically flags a "silent chest" -- when airflow is so reduced that even wheeze cannot be generated -- as indicating severe or life-threatening disease, the opposite of a panic attack.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Use the ≥6-year severity table (speech, tracheal tug, silent chest) to grade Sarah\'s attack as severe and prioritise oxygen saturation monitoring, not repositioning or imaging.',
  source:'Pediatrics endpoint part2.pdf p.487' },

{ id:'pedep2-res-7', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  stem:'Zak, a 3-year-old boy, is seen by his general practitioner because of recurrent wheezing associated with upper respiratory tract infections. Which of the following features most supports the diagnosis of asthma?',
  options:['Daytime cough','Finger clubbing','Peak-flow variability diary','Persistent moist cough','The presence of symptoms between coughs and colds'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Asthma is more likely if symptoms such as wheeze or cough occur between infections. Persistent moist cough and finger clubbing suggest alternative diagnoses.\n\n---\n\nThe cached asthma lecture distinguishes asthma from simple viral-triggered ("episodic viral") wheeze precisely on this point: true asthma symptoms are "variable over time," often "worse at night or on waking" and provoked by triggers such as exercise, laughter, cold air and allergens, meaning they are not confined to the days around a cold (Asthma_.pdf). A child who wheezes or coughs only when he has an upper respiratory infection, and is entirely well between infections, fits interval-free viral wheeze; a child with symptoms between infections as well is showing the persistent airway hyperresponsiveness that defines asthma.\n\nDaytime cough alone is nonspecific and common to many respiratory conditions, and is not, by itself, a discriminating feature for asthma over viral wheeze.\n\nFinger clubbing is explicitly listed among the lecture\'s asthma "red flags" -- signs that point away from asthma toward suppurative lung disease such as cystic fibrosis -- not a supporting feature.\n\nA peak-flow variability diary can demonstrate the variable airflow limitation of asthma, but this tool needs the child to be old enough to perform reliable spirometry/peak flow, which a 3-year-old cannot yet do, so it is not a usable feature at Zak\'s age -- not taken from the course material beyond the age-based device and technique teaching already cited.\n\nA persistent moist (wet) productive cough is the other red flag the lecture names, since asthma\'s classic cough is dry and non-productive; a chronic wet cough instead suggests a suppurative process such as protracted bacterial bronchitis or bronchiectasis.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Use interval symptoms (wheeze/cough between colds), not clubbing or a wet cough, to separate true asthma from viral-triggered wheeze in a preschool child.',
  source:'Pediatrics endpoint part2.pdf p.489' },

{ id:'pedep2-res-8', bank:'endpoint', module:'pediatrics', chapter:'infection',
  stem:'Norah, an 18-month-old girl, presents to her family doctor with coryza, cough, and a mild fever for 3 days. She feeds poorly and is unsettled at night. Her respiratory rate is normal, and there is no chest recession. What is the most likely diagnosis?',
  options:['Bronchiolitis','Frontal sinusitis','Pneumonia (lower respiratory tract infection)','Tonsillitis','Upper respiratory tract infection'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Coryza, mild fever, and no chest recession or tachypnea suggest a simple URTI, the most common cause of such symptoms in toddlers.\n\n---\n\nThe cached bronchiolitis lecture defines bronchiolitis by a seasonal illness with "nasal discharge, cough, tachypnoea, retractions and bilateral crackles" (32)Acute bronchiloitis_.pdf, and separately notes that RSV, the leading cause of bronchiolitis, can also cause a milder upper respiratory tract infection rather than progressing to lower-tract disease. Norah has the nasal discharge and cough but a normal respiratory rate and no recession, so she fails the tachypnoea-and-retraction criteria that would make this bronchiolitis; what remains is a straightforward upper respiratory tract infection, the everyday illness this age group has repeatedly.\n\nBronchiolitis is excluded specifically because the defining lower-airway signs -- tachypnoea and chest recession -- are both absent here.\n\nFrontal sinusitis is anatomically unlikely in an 18-month-old, since the frontal sinuses are not yet pneumatised at this age, and nothing in the vignette (no periorbital swelling, no facial pain) points to sinus disease -- not taken from the course material beyond general paediatric sinus development.\n\nPneumonia (lower respiratory tract infection) is excluded by the same normal respiratory rate and absence of recession that rules out bronchiolitis; there are no signs of lower-airway or alveolar involvement.\n\nTonsillitis is not supported: there is no mention of sore throat, dysphagia or an exudative pharyngeal exam, only coryza and cough, which point to the nose and upper airway rather than the tonsils.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Use a normal respiratory rate and absent recession to rule out bronchiolitis and settle on simple URTI as the diagnosis.',
  source:'Pediatrics endpoint part2.pdf p.491' },

{ id:'pedep2-res-9', bank:'endpoint', module:'pediatrics', chapter:'infection',
  image:'q-pd-ep2-493',
  imgAlt:'An otoscopic photograph of the tympanic membrane.',
  stem:'Fiona, a 10-month-old infant, has been unsettled and febrile with a runny nose for 2 days. Her family doctor examines her ear canal, and the tympanic membrane appears as in the opposite figure. What is the most likely diagnosis?',
  options:['Acute otitis externa','Cholesteatoma','Chronic otitis externa','Foreign body in the external ear canal','Otitis media with effusion'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Otitis media often presents after a viral URTI with fever and bulging, erythematous tympanic membrane. It\'s common in infants and toddlers.\n\n---\n\nThe cached bacterial-infection lecture lists otitis media among the common "other infections" seen with respiratory pathogens, presenting with ear pain, fever and sometimes discharge, and very common in children (specific bacterial infection.pdf); Fiona\'s two-day coryzal, febrile illness followed by an unsettled infant is the typical antecedent, and the otoscopic photograph -- a bulging, erythematous membrane that has lost its normal landmarks and light reflex -- is the classic appearance the lecture describes.\n\nAcute otitis externa is an infection of the ear canal skin itself, usually from water exposure or trauma, and would show canal swelling/discharge rather than a bulging, reddened tympanic membrane behind an otherwise normal canal -- not taken from the course material beyond the general anatomical distinction between canal and middle-ear disease.\n\nCholesteatoma is a chronic, destructive keratin-filled lesion that develops over months to years, typically with a retraction pocket and foul discharge, not an acute two-day febrile illness.\n\nChronic otitis externa implies a long-standing canal problem, which does not fit an acute two-day presentation in a previously well infant.\n\nA foreign body in the canal would show a visible object or canal-level abnormality on otoscopy, not a bulging, erythematous middle-ear membrane, and there is no history of object insertion.\n\n*Printed-key note, not disputed:* the option worded as the key, "otitis media with effusion," names a condition usually described as a dull, retracted membrane with a visible fluid level and without acute erythema, rather than the acutely bulging, red membrane the box and figure both describe -- a picture that better matches acute suppurative otitis media. The book\'s printed key is left exactly as printed.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Recognise a bulging, erythematous tympanic membrane after a viral URTI as acute otitis media, and separate middle-ear from ear-canal and chronic pathology.',
  source:'Pediatrics endpoint part2.pdf p.493' },

{ id:'pedep2-res-10', bank:'endpoint', module:'pediatrics', chapter:'resp-bronch',
  stem:'Jamel 10-month-old boy is brought at 1 am to the emergency because he has woken up with noisy breathing. He had coryzal symptoms for 2 days and now has a barking cough. On examination he has a fever of 37.8. He is alert and watches you but clings to his mother. On crying, he has marked inspiratory stridor. Select the most likely diagnosis.',
  options:['Bronchiolitis','HF','Inhaled F.B','CROUP','Pneumonia'],
  answer:3,
  explanation:'A two-day coryzal prodrome followed by a barking cough, low-grade fever and inspiratory stridor that worsens on crying is the classic triad of croup (viral laryngotracheobronchitis): the barking, "seal-like" cough and stridor come from subglottic airway oedema, and the fact that Jamel is alert, watches his examiner and simply clings to his mother -- rather than being drowsy, exhausted or too breathless to interact -- argues for a mild-to-moderate rather than a severe attack. This nocturnal, sudden-waking pattern is a well-recognised feature of croup, which classically worsens at night.\n\nBronchiolitis is a lower-airway disease of infants under a year presenting with tachypnoea, chest recession and wheeze or crackles rather than a barking cough and inspiratory stridor; nothing in Jamel\'s examination describes recession, wheeze or crackles, so the clinical picture points to the upper, not the lower, airway (bronchiolitis definition, 32)Acute bronchiloitis_.pdf).\n\n"HF" (heart failure) does not fit an otherwise well infant with a two-day coryzal illness and no mention of feeding difficulty, sweating, hepatomegaly or a cardiac murmur -- there is nothing in the vignette to suggest a cardiac cause for noisy breathing.\n\nAn inhaled foreign body classically causes a sudden-onset choking episode during feeding or play, with persistent localized wheeze rather than a preceding two-day coryzal prodrome and a barking cough -- the gradual viral build-up described here does not match a foreign-body history.\n\nPneumonia would be expected to show tachypnoea, focal crackles or dullness to percussion rather than a barking cough and stridor, which are upper-airway, not alveolar, findings.\n\nThis vignette is a near-identical companion to `pedep2-res-13` -- both describe a similarly-named, similarly-aged infant woken at night with a barking cough and stridor -- but the two pages print entirely different, non-overlapping option lists and only one of the two prints an explanation box; each is answered on its own terms here rather than folded together.\n\nWritten for this bank — Pediatrics endpoint part2.pdf prints no explanation here.',
  objective:'Recognise the barking cough, stridor and nocturnal onset of croup in an alert, interactive infant, and separate it from bronchiolitis, cardiac and foreign-body causes of noisy breathing.',
  source:'Pediatrics endpoint part2.pdf p.495' },

{ id:'pedep2-res-11', bank:'endpoint', module:'pediatrics', chapter:'respiratory',
  image:'q-pd-ep2-497',
  imgAlt:'A frontal chest X-ray.',
  stem:'A 10-year-old African boy woke up four nights ago with a sudden onset of coughing and choking. Since then, he has been noted to be intermittently wheezy. He has wheeze on auscultation of his right chest only. His chest X-ray is shown in the opposite figure. What is the most likely diagnosis?',
  options:['Pneumonia','Inhaled foreign body','Laryngotracheobronchitis (croup)','Bronchopulmonary dysplasia (BPD)','Chronic asthma'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Unilateral wheeze and sudden onset of symptoms during sleep suggest an inhaled foreign body. X-ray may show air trapping or hyperinflation on the affected side.\n\n---\n\nThis page shares its exact five-option menu (Pneumonia / Inhaled foreign body / Laryngotracheobronchitis (croup) / Bronchopulmonary dysplasia (BPD) / Chronic asthma) with `pedep2-res-12`; the shared ladder is worked through once here, and its sibling gives only its own discriminating fact.\n\nAcross this menu, the five conditions are told apart by tempo and distribution: pneumonia is a febrile illness with focal crepitations and consolidation; inhaled foreign body is a sudden choking event followed by a persistent, one-sided wheeze; croup is an acute barking cough and stridor from upper-airway oedema; BPD is a chronic disease that only occurs in infants who were born prematurely and ventilated; and chronic asthma is a long-standing, trigger-related, bilateral wheeze.\n\nThis boy\'s discriminating fact is the abrupt onset of coughing and choking four nights ago followed by wheeze confined to one side of the chest -- rather than the generalized, bilateral polyphonic wheeze the cached asthma lecture describes for true asthma (Asthma_.pdf), which also lists foreign body aspiration among the causes of childhood wheeze that must be told apart from asthma. The chest X-ray, a single frontal film with no annotation over both hemithoraces, is read by the box as showing air trapping or hyperinflation on the affected side, the classic radiographic sign of a check-valve partial bronchial obstruction that lets air in on inspiration but traps it on expiration.\n\nPneumonia is excluded here by the absence of fever, focal crepitations or a history of a preceding febrile illness -- this is a purely wheezy picture beginning with a choking episode.\n\nCroup is excluded because there is no barking cough or stridor, and the four-night duration is far longer than an acute laryngeal oedema episode.\n\nBronchopulmonary dysplasia is excluded because this is a previously well 10-year-old with no history of prematurity or neonatal ventilation.\n\nChronic asthma is excluded because the wheeze is strictly one-sided and began abruptly with choking, not the bilateral, trigger-related pattern asthma produces.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Use a sudden choking episode plus unilateral wheeze and unilateral air trapping on chest X-ray to diagnose an inhaled foreign body over asthma, pneumonia or croup, anchoring the shared menu this page shares with `pedep2-res-12`.',
  source:'Pediatrics endpoint part2.pdf p.497' },

{ id:'pedep2-res-12', bank:'endpoint', module:'pediatrics', chapter:'resp-pneumonia',
  image:'q-pd-ep2-499',
  imgAlt:'A frontal chest X-ray.',
  stem:'A 3-year-old Asian girl has been coughing for 10 days, with fever and lethargy for 2 days. On examination, she has a respiratory rate of 45 breaths/min and crepitations with decreased air entry at her left lung base. Her chest X-ray is shown in the opposite figure. What is the most likely diagnosis?',
  options:['Pneumonia','Inhaled foreign body','Laryngotracheobronchitis (croup)','Bronchopulmonary dysplasia (BPD)','Chronic asthma'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Fever, tachypnea, localized crepitations, and focal decreased air entry are classic signs of pneumonia. X-ray typically shows consolidation or infiltrates in the affected area.\n\n---\n\nThis page prints the same five-option menu (Pneumonia / Inhaled foreign body / Laryngotracheobronchitis (croup) / Bronchopulmonary dysplasia (BPD) / Chronic asthma) as `pedep2-res-11`, which works through how the five are told apart; only this girl\'s own discriminating fact is given here.\n\nThe cached pneumonia lecture names tachypnoea and chest indrawing as "the most important signs for diagnosis," alongside crepitations and dullness to percussion over a consolidated area (30) Pneumonia.pdf. Her discriminating picture is a 10-day febrile illness with a raised respiratory rate of 45/min, lethargy and focal crepitations with decreased air entry at the left base -- unlike the sudden choking-then-wheeze pattern of a foreign body, the acute barking cough and stridor of croup, the prematurity history BPD requires, or the bilateral trigger-related wheeze of asthma. The chest X-ray -- a single frontal film showing an area of increased opacity at the left lung base -- shows the consolidation the lecture describes as the radiographic counterpart of these signs.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Recognise fever, tachypnoea, focal crepitations and lobar consolidation on X-ray as pneumonia, using the differential worked through at `pedep2-res-11`.',
  source:'Pediatrics endpoint part2.pdf p.499' },

{ id:'pedep2-res-13', bank:'endpoint', module:'pediatrics', chapter:'resp-bronch',
  stem:'Jamal, a 10-month-old Asian boy, is brought at 1 a.m. to the Emergency Department because he has woken up with noisy breathing. He has had coryzal symptoms for 2 days and now has a barking cough. On examination, he has a fever of 37.8°C. He is alert and watches you but clings to his mother. On crying, he is noted to have inspiratory stridor. What is the most likely diagnosis?',
  options:['Bronchiolitis','Pneumonia','Pertussis (whooping cough)','Bronchiolitis','Laryngotracheobronchitis (croup)'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Croup typically follows a viral prodrome and presents with barking cough and inspiratory stridor, especially in the evening or at night. The child appears alert and interactive, which supports a mild-to-moderate croup diagnosis.\n\n---\n\nThis vignette is essentially identical to `pedep2-res-10` -- the same age, the same 1 a.m. presentation, the same two-day coryzal prodrome, barking cough, low fever and inspiratory stridor in an alert, interactive infant clinging to his mother -- and the printed key again lands on croup (laryngotracheobronchitis) for the same reasons: subglottic viral inflammation producing the barking cough and stridor, and preserved alertness arguing against a severe or exhausted presentation.\n\nThis page also prints the same five-option menu (Bronchiolitis / Pneumonia / Pertussis (whooping cough) / Bronchiolitis / Laryngotracheobronchitis (croup)) as later pages in this book section; the four distinct conditions on that ladder are worked through in full below, so a sibling sharing this menu need only give its own discriminating fact and point back here.\n\n*Defective option list, reproduced verbatim and not disputed:* option D repeats option A word for word as "Bronchiolitis," so the printed list effectively offers only four distinct diagnoses across five letters; this was confirmed on both the answered page and its unanswered twin, so it is a genuine printing defect in the source rather than a transcription slip. Reproducing this duplicate does not change which option is highlighted as the key.\n\nBronchiolitis (options A and D) is excluded on the same grounds as its sibling vignette: bronchiolitis needs tachypnoea, recession and wheeze/crackles, none of which are described here, only an upper-airway barking cough and stridor.\n\nPneumonia would be expected to show tachypnoea and focal crepitations rather than a barking cough and stridor, which localize disease to the larynx and trachea, not the alveoli.\n\nPertussis (whooping cough) causes paroxysmal coughing spasms often ending in vomiting or a post-tussive "whoop," built up over days to weeks, not a two-day coryzal illness culminating in a barking cough and stridor.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Recognise croup from a barking cough, stridor and alert affect, and record a duplicated option (Bronchiolitis printed twice) without disputing the printed key.',
  source:'Pediatrics endpoint part2.pdf p.501' },


