/* Peds endpoint PART 2, section 13 "Model Final Exam 2", half A: n1,2,3,6,9,10,11,12,16,20,21,26,
   29,30,31,32,33,34,35,36,39,40,43,44,45,46. Drafted from PEDEP2_S13_STAGED against
   endpoint-p2-s13-drafting-notes.md and endpoint-p2-s13-chapter-rulings.md. */
var PEDEP2_S13_MFE2_DRAFT_A = [

{
  id:'pedep2-mf2-1', bank:'endpoint', module:'pediatrics', chapter:'normal-dev',
  stem:'Developmental milestones vary between children; however, there are normal ranges for each domain. Which of the following denotes developmental delay?',
  options:['Not following moving objects by turning head at 4 weeks','Not sitting without support at 5 months','Not walking at 12 months','Can’t crawl on hands and knees at 6 months','Poor head control at 6 months'],
  answer:4,
  explanation:'**The endpoint file prints this explanation:**\n\n> Red flag age for head control is 4 months.\n\n---\n\nnd-5\'s limit-age table sets head control at 4 months, sitting unsupported at 9 months, standing with support at 12 months and walking independently at 18 months. Poor head control at 6 months has already passed the 4-month limit by two months, so it is a true red flag rather than a variant within the normal range.\n\nEach distractor sits comfortably inside the normal spread nd-5 and nd-7 describe. Turning to follow a moving object develops well before 4 weeks in most infants but the limit age for fixing and following is 3 months, so a report at exactly 4 weeks describes typical early behaviour, not delay. Not sitting without support at 5 months is unremarkable against a 9-month limit — nd-7\'s own ladder places unsupported sitting nearer 7-8 months as typical, well past 5 months. Not walking at 12 months is normal against an 18-month limit; nd-7 notes the lecture\'s own median for independent walking is 15 months, later still than 12. Crawling has no fixed limit age on nd-5\'s table, and nd-7 places it at 8-9 months as typical, so its absence at 6 months describes a child who simply has not reached that stage yet, not one who has missed a deadline.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A milestone counts as delayed only once the child has passed its limit age on the red-flag table; poor head control persisting to 6 months has passed the 4-month limit, while the other options each sit within their own normal range at the stated age.',
  source:'Pediatrics endpoint part2.pdf p.1434'
},

{
  id:'pedep2-mf2-2', bank:'endpoint', module:'pediatrics', chapter:'renal',
  stem:'Which of the following is the most common cause of haematuria in children?',
  options:['Trauma','IgA nephropathy','Urinary tract infection','Postinfectious glomerulonephritis','Tumours'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> UTI is the most common cause of haematuria in children.\n\n---\n\nren-8 states this as one of the two anchors the examiner returns to: the most common cause of gross haematuria in children is bacterial or viral urinary tract infection. UTI also appears in ren-8\'s own extra-glomerular, lower-tract branch, alongside dysuria and frequency as the accompanying symptoms that point toward it rather than toward the kidney itself.\n\nThe other four options are all real, named causes on ren-8\'s tree, just less common ones. IgA nephropathy is the commonest chronic glomerular disease in children (ren-11) but is not the commonest cause of haematuria overall — it typically declares itself with synpharyngitic gross haematuria within 1-2 days of a respiratory or gut infection, a more specific and less frequent picture than UTI. Postinfectious glomerulonephritis is ren-8\'s other anchor fact: most acute glomerulonephritis is post-infectious, usually after group A streptococcal throat or skin infection, but "most acute GN" is a narrower category than "all haematuria". Trauma and tumours (Wilms) both sit in ren-8\'s upper-tract branch as recognised but distinctly less frequent causes than an ascending bladder infection.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Urinary tract infection is the commonest cause of gross haematuria in children; IgA nephropathy, postinfectious glomerulonephritis, trauma and tumours are all real but less frequent causes on the same differential.',
  source:'Pediatrics endpoint part2.pdf p.1436'
},

{
  id:'pedep2-mf2-3', bank:'endpoint', module:'pediatrics', chapter:'neuro-nm',
  stem:'In which neurological disorders does “muscle fasciculation” occur?',
  options:['Spinal muscle atrophy','Peripheral neuropathies','Myopathies','Neuromuscular junction','Cerebral palsy'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> In spinal muscle atrophy (anterior horn cell disease), there are signs of denervation: weakness, loss of reflexes, fasciculation and wasting as the nerve supply to the muscle fails\n\n---\n\nneuro-18\'s table of the four neuromuscular sites places tongue fasciculations, alongside absent reflexes and more prominent wasting, specifically at the anterior horn cell. neuro-20 names spinal muscular atrophy as one of the two worked anterior horn cell examples (with poliomyelitis) and repeats the same signature: degeneration of the anterior horn cells produces weakness, wasting, diminished or absent reflexes and fasciculation as denervation spreads. Fasciculation is a fibre-bundle twitch that only appears once a motor neuron cell body itself, not just its axon, is failing.\n\nThe other three sites on neuro-18\'s table each have a different signature that does not include fasciculation. Peripheral neuropathies give distal wasting and weakness, pes cavus, sensory loss and absent reflexes, but the pathology sits along the nerve, not at the cell body. Myopathies produce a waddling gait, hyperlordosis and a positive Gowers\' sign from proximal weakness, with the muscle itself diseased rather than denervated. Neuromuscular junction disease gives fatiguability that worsens through the day, bulbar involvement and ptosis, a transmission failure rather than a structural nerve or muscle lesion. Cerebral palsy is an upper motor neuron disorder (neuro-27, neuro-28), giving spasticity and hyperreflexia — the opposite pattern to the flaccid, denervated picture fasciculation belongs to.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Muscle fasciculation is an anterior horn cell sign of denervation, seen in spinal muscular atrophy and poliomyelitis; peripheral neuropathy, myopathy, neuromuscular junction disease and cerebral palsy each have their own distinct clinical signature instead.',
  source:'Pediatrics endpoint part2.pdf p.1438'
},

{
  id:'pedep2-mf2-6', bank:'endpoint', module:'pediatrics', chapter:'neuro-cp',
  stem:'Where is the site of the brain lesion in dyskinetic-type cerebral palsy?',
  options:['Pyramidal tract','Cerebellum','Basal ganglia and extrapyramidal tract','Brainstem','Dorsal ganglia'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Dyskinetic-type CP occurs due to damage or dysfunction in the basal ganglia or their associated pathways (extrapyramidal).\n\n---\n\nneuro-28\'s anatomical classification maps each clinical type of cerebral palsy to a single site: the pyramidal (motor and paramotor) areas give spastic CP, the extrapyramidal basal ganglia give dyskinetic CP, and the cerebellum and its connections give ataxic CP. Dyskinetic CP\'s own row in the SCPE table lists dystonia, chorea, athetosis and fluctuating tone — movement disorders that are the basal ganglia\'s own repertoire — and neuro-27 adds that dyskinetic CP is often caused by perinatal asphyxia or kernicterus, both of which selectively injure the basal ganglia.\n\nThe pyramidal tract is instead the site behind spastic CP, giving increased tone, hyperreflexia and Babinski sign rather than dyskinesia. The cerebellum and its connections produce the ataxic type — loss of coordination and abnormal force, rhythm and accuracy — not involuntary movements. The brainstem is not one of neuro-28\'s three named sites for any clinical type of CP. Dorsal (posterior root) ganglia carry sensory, not motor, fibres and play no part in cerebral palsy\'s motor classification at all.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Dyskinetic cerebral palsy localises to the basal ganglia and extrapyramidal pathways, distinct from the pyramidal-tract lesion of spastic CP and the cerebellar lesion of ataxic CP.',
  source:'Pediatrics endpoint part2.pdf p.1444'
},

{
  id:'pedep2-mf2-9', bank:'endpoint', module:'pediatrics', chapter:'haematology',
  stem:'What is the underlying pathophysiologic mechanism of anemia in patients with G6PD enzyme deficiency?',
  options:['Bone marrow aplasia','Consumption coagulopathy','Food poisoning','Intravascular hemolysis','Extravascular hemolysis'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Hemolysis due to G6PD deficiency is mainly intravascular, associated with fever, malaise, abdominal pain, and dark urine containing hemoglobin and urobilinogen.\n\n---\n\nhaem-8\'s three-mechanism table of anaemia places G6PD deficiency under increased destruction (haemolysis), in the red cell enzyme branch alongside hereditary spherocytosis\'s membrane branch. nnj-6 names G6PD deficiency as the commonest red cell enzyme defect causing haemolysis, with two mechanisms acting together — increased bilirubin production from red cell breakdown, exaggerated by a decreased rate of conjugation. Free haemoglobin released directly into the plasma, rather than being handled inside the spleen, is what the box\'s dark urine containing haemoglobin and urobilinogen is describing — the hallmark of an intravascular process.\n\nBone marrow aplasia is a production failure, the opposite mechanism to a destructive haemolytic anaemia, and belongs instead to conditions such as Diamond-Blackfan anaemia or parvovirus B19-triggered aplasia (haem-8). Consumption coagulopathy describes disseminated intravascular coagulation, a clotting-factor and platelet disorder rather than a cause of anaemia by red cell destruction. Food poisoning is not a recognised cause of haemolysis in G6PD deficiency; the relevant trigger is oxidant stress, not gastrointestinal infection. Extravascular haemolysis is the mechanism behind hereditary spherocytosis instead, where the spleen removes rigid, non-deformable red cells — the opposite compartment to the intravascular breakdown that defines a G6PD crisis.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'G6PD deficiency causes anaemia through intravascular haemolysis, releasing free haemoglobin into the plasma, distinct from bone marrow aplasia (a production failure), consumption coagulopathy (a clotting disorder) and the extravascular haemolysis of hereditary spherocytosis.',
  source:'Pediatrics endpoint part2.pdf p.1450'
},

{
  id:'pedep2-mf2-10', bank:'endpoint', module:'pediatrics', chapter:'haematology',
  stem:'Which of the following tests is diagnostic for hereditary spherocytosis?',
  options:['Hemoglobin electrophoresis','CBC','Osmotic fragility test','Hormonal assay'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> The osmotic fragility test measures red blood cell resistance to hemolysis in hypotonic saline solutions. It is diagnostic for hereditary spherocytosis.\n\n---\n\nThe disease itself is well sourced: haem-8 files hereditary spherocytosis as the red cell membrane cause of haemolytic anaemia, haem-11 shows the spherocyte on the blood film — a loss of central pallor — and nnj-6 ranks it the commonest red cell membrane defect, adding that it may cause splenomegaly and that the diagnosis is *suspected on the peripheral blood smear and the family history*. **The osmotic fragility test as the named diagnostic tool is not taught at all — searching "osmotic fragility" across the cached material returns zero results; the material\'s only other "osmotic" hits are osmotic diarrhoea and osmotic diuresis, unrelated conditions.** That the fragility test exists and works the way the box describes — measuring how easily the abnormally shaped, less deformable spherocyte lyses in hypotonic saline compared with a normal biconcave red cell — is supplied here rather than sourced.\n\nnnj-6\'s "suspected on the peripheral blood smear" is close to distractor B, CBC, but a film that suggests spherocytosis is not the same as a dedicated test that confirms it: a CBC and film review are the screening step that prompts the osmotic fragility test, not a substitute for it. Haemoglobin electrophoresis instead diagnoses hameoglobinopathies such as thalassaemia or sickle cell disease (haem-8\'s haemoglobinopathy branch), a different membrane-versus-haemoglobin mechanism entirely. A hormonal assay has no role in a red cell membrane disorder.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Hereditary spherocytosis is the commonest red cell membrane defect, suspected on the blood film and family history and confirmed by the osmotic fragility test; the test itself, and the diagnostic role that fact implies, is not taught in the cached material and is answered from general knowledge.',
  source:'Pediatrics endpoint part2.pdf p.1452'
},

{
  id:'pedep2-mf2-11', bank:'endpoint', module:'pediatrics', chapter:'renal',
  stem:'Which of the following is a feature of pediatric nephrotic syndrome?',
  options:['Low C3 level','It is usually associated with hematuria','It rarely causes chronic renal failure','It is usually associated with hypertension'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Pediatric nephrotic syndrome (steroid-sensitive) typically presents with normal blood pressure, normal complement levels, and no hematuria. It rarely leads to chronic renal failure.\n\n---\n\nren-13\'s nephrotic-versus-nephritic table lines up exactly with the printed key: nephrotic syndrome carries little or no blood, a normal blood pressure and normal C3/C4 complement, in contrast to the raised blood pressure, low C3 and gross or microscopic haematuria of a nephritic picture. Minimal change disease, the idiopathic cause behind 85-90% of childhood nephrotic syndrome, is described as having a good prognosis, and ren-13 states plainly that it rarely progresses to chronic renal failure — unlike the steroid-resistant patterns (focal segmental glomerulosclerosis, membranoproliferative or membranous disease) which carry a worse long-term renal outlook.\n\nLow C3 is instead the nephritic finding, seen for example in acute post-streptococcal glomerulonephritis, not in nephrotic syndrome, where ren-13 states complement stays normal. Haematuria is likewise the nephritic feature; ren-13\'s own table records minimal change nephrotic syndrome as having no macroscopic haematuria. Hypertension is again the nephritic column\'s feature, since ren-13 specifically lists normal blood pressure as one of minimal change disease\'s defining findings.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Childhood nephrotic syndrome (minimal change disease) presents with normal blood pressure, normal complement and no haematuria, and rarely progresses to chronic renal failure — the opposite profile to nephritic syndrome, which has low C3, hypertension and haematuria.',
  source:'Pediatrics endpoint part2.pdf p.1454'
},

{
  id:'pedep2-mf2-12', bank:'endpoint', module:'pediatrics', chapter:'neurological',
  stem:'What is the preferred (most common) method of treatment for hydrocephalus?',
  options:['Oral diuretics to relieve raised intracranial pressure','Oral carbonic anhydrase inhibitors','Insertion of ventriculoperitoneal shunt','Ventriculo-cardiac (right atrium) shunt'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Ventriculoperitoneal shunt insertion is the mainstay treatment for hydrocephalus. Occasionally, endoscopic third ventriculostomy is performed.\n\n---\n\nper-10 names the ventriculo-peritoneal shunt as the standard course once post-haemorrhagic hydrocephalus follows an intraventricular bleed and the ventricles dilate. inf-11 repeats the same instrument for hydrocephalus complicating bacterial meningitis, and inf-22 names it again for hydrocephalus complicating tuberculous meningitis — three different causes of paediatric hydrocephalus in the material, all converging on the same treatment. The consistency across three separate diseases is what makes VP shunting the preferred, most common answer rather than a cause-specific one.\n\nOral diuretics and oral carbonic anhydrase inhibitors (such as acetazolamide) are sometimes used as temporising medical measures in selected cases, but none of the three anchors names either as the mainstay treatment — the material\'s own repeated answer is surgical, not pharmacological. A ventriculo-cardiac (atrial) shunt, draining CSF into the right atrium rather than the peritoneal cavity, is an older alternative route that has been superseded by the ventriculo-peritoneal route because of complications specific to placing a catheter in the bloodstream, such as shunt-related bacteraemia and thromboembolism; none of the material\'s three hydrocephalus discussions names it as the modern choice.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Ventriculoperitoneal shunt insertion is the standard treatment for hydrocephalus across its different causes in the material — post-haemorrhagic, post-meningitic and tuberculous — ahead of medical measures or the older ventriculo-atrial route.',
  source:'Pediatrics endpoint part2.pdf p.1456'
},

{
  id:'pedep2-mf2-16', bank:'endpoint', module:'pediatrics', chapter:'haematology',
  stem:'Nazma, aged 4 years, presents with a 1-week history of episodic central abdominal pain. She is of Indian ethnicity, but the family live in Kenya and are visiting relatives in the UK. She is otherwise well. Her relative’s general practitioner thinks she may be slightly pale and that her spleen is enlarged, as it is 3 cm below the costal margin. There are no other abnormalities on examination. Which of the following is the most likely cause for her enlarged spleen?',
  options:['Acute lymphoblastic leukaemia','Malaria','Hookworm infestation','Wilms tumour','Sickle cell disease'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> High prevalence in Kenya and may cause chronic anaemia and splenomegaly.\n\n---\n\ninf-3\'s risk-factor list makes exactly the link this vignette turns on: recent travel abroad, with malaria given as the worked example, sits under the history questions asked of any febrile or unwell child. Nazma\'s family lives in Kenya, a malaria-endemic country, and she now presents with pallor and splenomegaly — the anaemia and organomegaly that come from ongoing red cell destruction by the parasite. **The mechanism itself — Plasmodium infecting and rupturing red cells, with the spleen enlarging as it clears parasitised cells — is not taught in the cached material, which mentions malaria only as a travel risk factor and nowhere as a disease in its own right; this detail is supplied from general medical knowledge.** The vignette\'s well-otherwise, afebrile-at-presentation picture with a mildly enlarged spleen fits chronic or repeated malarial infection rather than an acute severe attack.\n\nThe distractors are all real causes of splenomegaly the material does teach, just not the best fit here. Acute lymphoblastic leukaemia causes splenomegaly through marrow and organ infiltration (mal-5, mal-6), but it typically comes with systemic upset — fever in 60%, bleeding, bone pain — which this well child lacks. Sickle cell disease is a haemoglobinopathy cause of haemolytic anaemia and splenomegaly on haem-8\'s tree, but recurrent splenic infarction in sickle disease usually leaves the spleen small (autosplenectomy) by mid-childhood rather than palpably enlarged, and there is no mention of a sickling-prone ethnic background here. **Wilms tumour presents as a smooth abdominal mass in a usually well child, arising from the kidney rather than the spleen, and does not cross the midline — this comparison against neuroblastoma is itself supplied and tagged rather than taught in any cached deck, not taken from the course material.** Hookworm infestation causes anaemia through chronic intestinal blood loss but is not associated with splenomegaly in the way malaria is.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Travel to a malaria-endemic country with pallor and splenomegaly points to malaria; the disease itself and its splenomegaly mechanism are outside the cached material, while leukaemia, sickle cell disease, Wilms tumour and hookworm are each real but less fitting causes of splenomegaly on the same differential.',
  source:'Pediatrics endpoint part2.pdf p.1464'
},

{
  id:'pedep2-mf2-20', bank:'endpoint', module:'pediatrics', chapter:'renal-cakut',
  stem:'Which clinical problem may present with secondary (onset) enuresis?',
  options:['Acute kidney injury','Emotional upset','Ectopic ureter','Orthostatic proteinuria','Glomerulonephritis'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Emotional upset usually presents with secondary enuresis.\n\n---\n\nren-17 defines secondary enuresis as wetting returning after at least six months of previously established dryness, and states this always needs a cause sought. Among its named causes is a new psychosocial stress such as starting school — the same category as the printed key\'s emotional upset. A child who was previously dry losing that continence in response to a stressor such as family disruption, a new sibling or a change in school is the textbook pattern of secondary, not primary, enuresis.\n\nAn ectopic ureter is instead a cause of continuous dribbling incontinence present from birth, which is a primary rather than a secondary pattern — the child was never fully dry, since the ureter bypasses the bladder neck entirely. Orthostatic proteinuria (ren-13) is a benign finding of protein appearing in the urine only after upright activity; it is not a cause of enuresis at all. Acute kidney injury and glomerulonephritis both cause oliguria or reduced urine output as filtration falls, the opposite direction to enuresis, which is an excess of voided urine or loss of bladder control rather than a shortage of urine produced.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Secondary enuresis — wetting returning after 6 months of dryness — always needs a cause sought, and a new psychosocial stress such as emotional upset is one of the material\'s named causes; an ectopic ureter instead causes lifelong dribbling, and orthostatic proteinuria, acute kidney injury and glomerulonephritis are unrelated to enuresis.',
  source:'Pediatrics endpoint part2.pdf p.1472'
},

{
  id:'pedep2-mf2-21', bank:'endpoint', module:'pediatrics', chapter:'genetics',
  stem:'Jack is a 3-year-old boy whose father has a genetic disorder associated with short stature. Jack is also very short, has bowed legs and a very prominent forehead. His head is disproportionately large compared with his body size. Which of the following is the most likely mode of genetic inheritance of this disorder?',
  options:['Autosomal dominant disorder','Autosomal recessive disorder','X-linked dominant','X-linked recessive','Microdeletion'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Jack and his father have the same condition. Jack has achondroplasia.\n\n---\n\ngp-5\'s short stature tree names achondroplasia as the example of a congenital, disproportionate skeletal dysplasia — matching Jack\'s bowed legs, prominent forehead and disproportionately large head over a short body. gen-14\'s account of autosomal dominant inheritance lists achondroplasia by name as an example disease, and Jack\'s picture fits its rules precisely: an affected father transmitting to an affected son is exactly the male-to-male transmission gen-14 gives as a defining feature of AD inheritance, and gen-14\'s homozygote table separately notes that achondroplasia is one condition where a homozygous double dose (from two affected parents) produces more severe disease than either single copy — confirming this is a single-gene, dominantly acting condition rather than one needing two carrier parents.\n\nAn autosomal recessive disorder would need Jack\'s father to be a carrier or affected and his mother to also carry the gene, with typically unaffected parents in a purely carrier pairing — not the direct parent-to-child pattern described here. X-linked dominant and X-linked recessive disorders both trace through the X chromosome, so an affected father passes an X-linked gene to all his daughters and none of his sons, making father-to-son transmission impossible for either X-linked pattern — ruling both out for Jack. A microdeletion is a chromosomal, not single-gene, mechanism and is not how achondroplasia (caused by a point mutation in FGFR3) is inherited.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Achondroplasia is autosomal dominant, and father-to-son transmission (Jack and his father sharing the disorder) is the male-to-male pattern that confirms autosomal, not X-linked, inheritance; autosomal recessive and microdeletion mechanisms do not fit a directly transmitted, single-gene skeletal dysplasia.',
  source:'Pediatrics endpoint part2.pdf p.1474'
},

{
  id:'pedep2-mf2-26', bank:'endpoint', module:'pediatrics', chapter:'endocrine',
  stem:'Sophie, a 9-year-old girl with type 1 diabetes mellitus, develops a fever along with vomiting and diarrhoea. After 2 days, her mother takes her to the local paediatric assessment unit as she continues to vomit. On examination, her temperature is 37.5°C. She is able to talk to her mother. She has clinical dehydration. Her pulses, capillary refill time, and blood pressure are normal. Her blood glucose is 16 mmol/L. Which of the following is the best course of action to take immediately for this patient?',
  options:['Oral glucose drink','Intravenous infusion of normal saline (0.9% sodium chloride)','Subcutaneous insulin','Fluid resuscitation with normal saline (0.9% sodium chloride)','Intravenous infusion of 5% glucose'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> She is clinically dehydrated and vomiting, so she needs IV fluid. She is not shocked, so fluid resuscitation is not indicated.\n\n---\n\nemg-13\'s three degrees of dehydration by weight loss separate clinical dehydration (5-9%) from shock (10% or more, with the collapsed circulation that implies). Sophie\'s normal pulses, capillary refill and blood pressure place her squarely in the clinical-dehydration band, not shock — she needs replacement fluid, not resuscitation fluid. Because she is vomiting and cannot reliably keep fluids down by mouth, an intravenous infusion is the appropriate route, and normal saline (0.9% sodium chloride) is the standard maintenance and deficit-replacement fluid for a dehydrated, non-shocked child.\n\nAn oral glucose drink is wrong on two counts: she is already vomiting, so oral intake is unlikely to be retained, and her glucose at 16 mmol/L is already raised, not low — she needs volume, not more sugar. Subcutaneous insulin is premature: with a background of vomiting, diarrhoea and intercurrent illness in a type 1 diabetic, the priority the endpoint file identifies is correcting dehydration first; endo-4 notes insulin needs vary through illness and require individualised adjustment rather than a reflex extra dose the moment glucose is mildly elevated, and this vignette gives no ketone or blood gas result that would point toward diabetic ketoacidosis needing an insulin infusion. Fluid resuscitation with normal saline is the emg-13 label reserved for the shocked child (≥10% loss) needing rapid bolus therapy to restore the circulation — a different volume and speed of fluid delivery to the steady deficit-replacement infusion this normotensive, well-perfused child actually needs. Intravenous 5% glucose would add sugar to a child whose glucose is already 16 mmol/L, working against, not with, her current metabolic state.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A vomiting, clinically dehydrated (not shocked) child needs IV normal saline for deficit replacement rather than oral fluids, insulin, shock-level fluid resuscitation, or dextrose-containing fluid, since her pulses, capillary refill and blood pressure are all normal.',
  source:'Pediatrics endpoint part2.pdf p.1484'
},

{
  id:'pedep2-mf2-29', bank:'endpoint', module:'pediatrics', chapter:'neurological',
  stem:'Which of the following is among the red flag features of headache?',
  options:['Bilateral headache','Headache that gets worse on lying down','Headache following head trauma','Headache associated with vision impairment'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Headache worse when lying down or with coughing/straining suggests raised intracranial pressure and is a red flag.\n\n---\n\n**No cached deck carries a dedicated headache section or a printed red-flag headache list — searching directly for one returns nothing.** What the material does supply, spread across several chapters, is the underlying idea the printed key rests on: mal-20 describes medulloblastoma presenting with morning headache and vomiting from obstructive hydrocephalus (the detail itself flagged there as outside the course material), gp-7 sends a child with headache or neurological signs for an MRI specifically to exclude an intracranial tumour such as craniopharyngioma, and neuro-1 gives the sudden, severe "thunderclap" headache of subarachnoid haemorrhage. Together these establish that headache can signal raised intracranial pressure or a structural lesion — genuine course content — but **the specific mechanical claim that recumbency itself worsens the headache, which is what the printed key selects, is not spelled out anywhere in the cached material and is supplied from general knowledge: lying flat raises intracranial venous pressure and reduces CSF drainage, so a headache that is worse lying down and better upright is a recognised sign of raised intracranial pressure.**\n\nThe printed key is recorded here as the bank\'s own choice rather than adjudicated, because three of the four options are genuine red flags in ordinary clinical teaching too. Headache following head trauma raises concern for extradural or subdural haemorrhage (neuro-1) and would be treated as a red flag in most standard lists. Headache with visual impairment can signal raised intracranial pressure causing papilloedema, or a mass affecting the visual pathways, and is likewise a conventional red flag. Bilateral headache is the one true non-flag among the four — a bilateral, symmetrical pattern is typical of the common, benign tension-type headache rather than a focal or pressure-related cause, so it is the least concerning feature on this list, even though it is not the option this question keys.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'The material has no dedicated headache section, but scattered anchors (medulloblastoma\'s morning headache from raised ICP, the MRI referral for headache with neurological signs, and subarachnoid haemorrhage\'s thunderclap headache) support headache as a marker of intracranial pathology; the specific claim that recumbency worsens it is supplied knowledge, and the printed key is recorded as the bank\'s own choice among several plausible red flags.',
  source:'Pediatrics endpoint part2.pdf p.1490'
},

{
  id:'pedep2-mf2-30', bank:'endpoint', module:'pediatrics', chapter:'resp-pneumonia',
  stem:'Which of the following antibiotics is used for treating atypical pneumonia?',
  options:['Amoxicillin','Azithromycin','Cephalexin','Gentamicin'],
  answer:1,
  explanation:'resp-1 and resp-3 both teach that atypical organisms — Mycoplasma pneumoniae, Chlamydia pneumoniae and Legionella — are a recognised group of community-acquired pneumonia pathogens, with resp-3\'s age table naming Mycoplasma and Chlamydia pneumoniae as typical of children aged 10-21 years and resp-3\'s own recovered pie chart placing the atypicals together as the second commonest cause of CAP overall, ahead of every named bacterium except the pneumococcus. resp-7\'s empiric antibiotic table gives the actual treatment logic: for children aged 5-21 years, the age band where atypical organisms cluster, the recommended agents are macrolides, oral or intravenous depending on severity, and resp-7 specifically names erythromycin — a macrolide — for suspected chlamydia. This establishes that the macrolide drug class is the sourced answer to "what treats atypical pneumonia".\n\n**Azithromycin itself, as the specific named macrolide in the printed key, is not named anywhere in the cached material — resp-7 names erythromycin as its macrolide example, not azithromycin — so the specific agent is supplied from general medical knowledge: azithromycin is a macrolide, in the same drug class as the erythromycin resp-7 does teach, and is commonly preferred clinically for its once-daily dosing and shorter course.** The reasoning that makes it work — inhibiting bacterial protein synthesis in organisms that lack a cell wall, which is why beta-lactams cannot reach them — is the same class-level fact resp-7\'s empiric table already implies.\n\nAmoxicillin is resp-7\'s own first-line agent for mild, typical bacterial pneumonia in children aged 2 months to 5 years, but as a beta-lactam it targets bacterial cell wall synthesis, a target atypical organisms such as Mycoplasma lack entirely (Mycoplasma has no cell wall), so beta-lactams do not work against them. Cephalexin is likewise a beta-lactam (a cephalosporin), sharing the same mechanism and the same blind spot for atypical organisms. Gentamicin is an aminoglycoside effective against aerobic Gram-negative organisms and used in combination regimens for severe or resistant infections, not the empiric choice for an outpatient atypical pneumonia picture.\n\nWritten for this bank — Pediatrics endpoint part2.pdf prints no explanation here.',
  objective:'Atypical pneumonia (Mycoplasma, Chlamydia, Legionella) needs a macrolide, since these organisms lack the cell wall that beta-lactams such as amoxicillin, cephalexin or aminoglycosides such as gentamicin depend on; the material teaches erythromycin as its macrolide example, and azithromycin as the specific named agent is supplied from general knowledge.',
  source:'Pediatrics endpoint part2.pdf p.1492'
},

{
  id:'pedep2-mf2-31', bank:'endpoint', module:'pediatrics', chapter:'gastroenterology',
  stem:'Which of the following statements best describes the findings in a 2-week-old infant with pyloric stenosis?',
  options:['Severe bilious vomiting','Dehydration with a metabolic acidosis','Hypokalaemic hypochloraemic alkalosis','Massive abdominal distension','Bowel sounds are absent'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Pyloric stenosis leads to projectile non-bilious vomiting, dehydration, and hypokalaemic hypochloraemic metabolic alkalosis due to loss of gastric acid.\n\n---\n\ngast-3 gives the metabolic signature directly: repeated vomiting of hydrochloric-acid-rich gastric contents produces a hypochloraemic, hypokalaemic metabolic alkalosis, sometimes with accompanying hyponatraemia — matching the printed key precisely, and matching the 2-week age, which sits inside gast-3\'s stated presentation window of 2-8 weeks regardless of gestational age.\n\nBilious vomiting is specifically excluded by gast-3, which states the vomiting is non-bilious because the obstruction sits above the ampulla of Vater, where bile enters the gut — so bile cannot reflux back through a pylorus that lies proximal to it. Dehydration with a metabolic acidosis gets the acid-base direction backwards: vomiting stomach acid causes the body to lose acid, driving the pH up into alkalosis, not down into acidosis — acidosis would instead suggest a different process such as bowel obstruction with ischaemia or severe diarrhoeal losses. Massive abdominal distension and absent bowel sounds both describe a lower or more distal bowel obstruction or ileus; gast-3\'s own diagnostic sign is the opposite picture — visible gastric peristalsis moving left to right across the upper abdomen, with an over-distended, gas-filled stomach that is relieved rather than worsened by nasogastric emptying before the pyloric mass is examined for.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Pyloric stenosis causes a hypokalaemic, hypochloraemic metabolic alkalosis from vomiting gastric acid, with non-bilious (not bilious) vomiting and visible gastric peristalsis rather than distension or absent bowel sounds, and metabolic alkalosis rather than acidosis.',
  source:'Pediatrics endpoint part2.pdf p.1494'
},

{
  id:'pedep2-mf2-32', bank:'endpoint', module:'pediatrics', chapter:'infection',
  stem:'A child is brought to the Emergency Department with stridor, drooling of saliva, and respiratory distress. What is the most appropriate next step in management?',
  options:['Intravenous steroids','Oxygen and nebulized adrenaline','Intravenous antibiotics','Immediate intubation','Nebulized salbutamol'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> This child likely has epiglottitis. Airway protection is the immediate priority before any other interventions.\n\n---\n\ninf-15\'s epiglottitis-versus-croup table names drooling as one of the two discriminators that is present in epiglottitis and absent in croup, alongside the tripod posture and muffled "hot potato" voice — this vignette\'s stridor, drooling and respiratory distress together match the epiglottitis column, not the croup one. inf-15 is explicit and emphatic about what comes first: airway first, secured usually by intubation, before any other procedure, and separately warns against examining the throat, since instrumentation can precipitate complete airway obstruction in a swollen, inflamed epiglottis. Only once the airway is secured does inf-15 move on to IV antibiotics such as ceftriaxone or cefotaxime, and to IV dexamethasone as an adjunct.\n\nIV steroids and IV antibiotics are both genuine parts of epiglottitis management on inf-15\'s own account, but they are explicitly sequenced after the airway is secured, not before — treating the infection or the inflammation is irrelevant if the child obstructs completely first. Oxygen and nebulised adrenaline is instead the standard next step in the croup column of inf-15\'s table, not epiglottitis, since croup\'s subglottic swelling responds to nebulised adrenaline in a way an inflamed, obstructing epiglottis does not. Nebulised salbutamol is a bronchodilator for lower airway disease such as asthma or bronchiolitis; it does nothing for an upper airway obstruction at the epiglottis.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Epiglottitis (stridor, drooling, tripod posture, high fever, no cough) is an airway emergency where securing the airway by intubation comes before steroids, antibiotics, adrenaline or bronchodilators, and throat examination is avoided.',
  source:'Pediatrics endpoint part2.pdf p.1496'
},

{
  id:'pedep2-mf2-33', bank:'endpoint', module:'pediatrics', chapter:'neurological',
  stem:'Which of the following is the most common cause of febrile convulsions in children?',
  options:['Bacterial meningitis','Human herpesvirus 6 (HHV-6)','Influenza','Pneumococcal sepsis','Otitis media'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> HHV-6 is the most common cause of febrile convulsions, especially in children aged 6 months to 5 years.\n\n---\n\ninf-29\'s own roseola infantum section names this exact link: HHV-6 causes an abrupt very high fever, often above 40°C, for 3 to 5 days, and febrile seizures occur in 10-15% of cases because the fever rises so fast — inf-29 calls this the commonest complication of the infection. neuro-4 defines a febrile seizure as an epileptic seizure with fever in the ABSENCE of intracranial infection, in a child aged 5 months to 6 years, a window that matches the age group named in this stem, and lists a seizure occurring early in a viral infection, while temperature is climbing, as a predisposing feature — exactly the mechanism inf-29 describes for roseola\'s abrupt, rapidly rising fever.\n\nneuro-4\'s own definition already excludes bacterial meningitis and pneumococcal sepsis from being called febrile convulsions at all, since it specifically requires the ABSENCE of intracranial infection — a seizure occurring because of meningitis is a seizure caused by meningitis, a different diagnostic category with its own work-up (lumbar puncture) and management, not a benign febrile convulsion. Otitis media is a genuine, common trigger of the fever behind a febrile seizure, but it is not named as the single commonest cause the way inf-29 names HHV-6. Influenza can likewise provoke a febrile seizure through fever alone, but inf-29\'s specific point about HHV-6 — fever this abrupt and this high, in exactly the youngest age band most prone to febrile seizures — is what the material identifies as the leading cause.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A febrile seizure is fever plus seizure WITHOUT intracranial infection (excluding bacterial meningitis and pneumococcal sepsis by definition); HHV-6/roseola\'s abrupt, very high fever is named as the commonest cause of the febrile seizures it triggers (10-15% of cases), ahead of influenza and otitis media.',
  source:'Pediatrics endpoint part2.pdf p.1498'
},

{
  id:'pedep2-mf2-34', bank:'endpoint', module:'pediatrics', chapter:'endo-thyroid',
  stem:'A 2-week-old baby is brought with vomiting and poor feeding. Examination shows hypotonia and ambiguous genitalia. Blood tests reveal hyponatraemia, hyperkalaemia, and hypoglycaemia. What is the most likely diagnosis?',
  options:['Congenital hypothyroidism','Inborn error of metabolism','Galactosaemia','Congenital adrenal hyperplasia','Neonatal sepsis'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> The classic presentation of congenital adrenal hyperplasia (CAH) includes salt-wasting, ambiguous genitalia in females, and electrolyte abnormalities.\n\n---\n\nendo-33 marks itself plainly as a gap: CAH is named as a cause in three paediatric decks but taught in none, so what follows is supplied rather than sourced, apart from the ACTH stimulation test, which is printed elsewhere in the material. **With that flagged, the picture endo-33 lays out matches this vignette closely: salt-losing crisis at 1-3 weeks of age with vomiting, weight loss, dehydration and shock, alongside hyponatraemia, hyperkalaemia, metabolic acidosis and hypoglycaemia — the same electrolyte pattern printed here — caused by 21-hydroxylase deficiency in over 90% of cases blocking cortisol and aldosterone synthesis and shunting precursor hormones into androgens.** Ambiguous genitalia specifically points to a genetically female infant virilised in utero by that androgen excess, since endo-33 notes affected boys instead look entirely normal at birth and are only picked up when they later collapse.\n\nCongenital hypothyroidism causes prolonged jaundice, poor feeding, hypotonia and constipation, but not this specific salt-wasting electrolyte pattern or ambiguous genitalia. A generic inborn error of metabolism can cause vomiting, hypoglycaemia and hypotonia, but it does not typically cause ambiguous genitalia, which points to a specific disorder of sex-hormone synthesis rather than a broader metabolic defect. Galactosaemia causes jaundice, hepatomegaly, cataracts and E. coli sepsis susceptibility (liv-8), not the hyperkalaemia/hyponatraemia salt-wasting picture or ambiguous genitalia. Neonatal sepsis can cause vomiting, poor feeding and hypotonia from generalised illness, but does not specifically cause this electrolyte derangement or genital ambiguity.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A salt-losing crisis (hyponatraemia, hyperkalaemia, hypoglycaemia) with ambiguous genitalia in a 1-3-week-old is congenital adrenal hyperplasia from 21-hydroxylase deficiency; this disease account is supplied since no cached deck teaches CAH, unlike hypothyroidism, a generic metabolic error, galactosaemia or sepsis, none of which produces this specific combination.',
  source:'Pediatrics endpoint part2.pdf p.1500'
},

{
  id:'pedep2-mf2-35', bank:'endpoint', module:'pediatrics', chapter:'emergencies',
  stem:'Which of the following is the most likely cause of cyanosis in a newborn that improves with crying?',
  options:['Tricuspid atresia','Choanal atresia','Tetralogy of Fallot','Transposition of the great arteries','Pulmonary atresia'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> In choanal atresia, the nasal airway is blocked. Crying opens the mouth and improves oxygenation.\n\n---\n\ncard-10\'s list of the eight cyanosis types names cyclical cyanosis specifically as the pattern caused by bilateral choanal atresia — cyanosis that comes and goes rather than staying fixed. Newborns are obligate nasal breathers; when both nasal passages are physically blocked at birth, the infant becomes cyanosed at rest but turns pink again the moment it cries, because crying opens the mouth and bypasses the obstructed nose entirely — the improvement with crying is the direct mechanical consequence of switching from nasal to oral airflow. prd-3\'s airway causes of respiratory distress list choanal atresia or stenosis alongside laryngeal web and subglottic stenosis as structural upper-airway lesions, distinct from the parenchymal and cardiac causes of neonatal breathing difficulty.\n\nThe four remaining options are all cardiac causes of true central cyanosis from right-to-left or mixed shunting, and card-10\'s own classification places central cardiac cyanosis in a different category from the cyclical pattern this vignette describes: none of a fixed anatomical cardiac shunt gets mechanically better with crying the way an obstructed nasal airway does, since crying does not change the underlying cardiac shunt. Tricuspid atresia and pulmonary atresia are both duct-dependent cyanotic lesions with fixed right-to-left shunting. Tetralogy of Fallot is card-1\'s named example of the right-to-left shunt group and the commonest cause of cyanosis after 1 year of age — but its cyanosis, if anything, may worsen with the increased pulmonary vascular resistance and right ventricular outflow spasm that crying and agitation can provoke (a "tet spell"), not improve with it. Transposition of the great arteries produces card-10\'s reverse differential cyanosis when combined with a PDA, again a fixed structural shunt unaffected by crying.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Cyclical cyanosis that improves with crying is the signature of bilateral choanal atresia, a mechanical nasal obstruction bypassed by mouth breathing when crying; cardiac causes such as tricuspid atresia, tetralogy of Fallot, transposition and pulmonary atresia are fixed structural shunts unaffected by crying, and Fallot\'s cyanosis can worsen rather than improve with agitation.',
  source:'Pediatrics endpoint part2.pdf p.1502'
},

{
  id:'pedep2-mf2-36', bank:'endpoint', module:'pediatrics', chapter:'haem-bleeding',
  stem:'A 4-year-old boy presents with abdominal pain, joint swelling, and a purpuric rash over the lower limbs. What is the most likely diagnosis?',
  options:['Idiopathic thrombocytopenic purpura','Meningococcaemia','Henoch–Schönlein purpura','Acute leukaemia','Systemic lupus erythematosus'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Henoch–Schönlein purpura is a vasculitis that typically presents with palpable purpura, abdominal pain, and joint involvement.\n\n---\n\nhaem-36 names the four main characteristics of HSP exactly as this vignette lays them out: a purpuric rash typically over the buttocks, legs and feet; swollen, sore joints mainly at the knees and ankles, which may even precede the rash; and digestive tract involvement with belly pain, sometimes before the rash appears too. ren-11 adds that HSP is the most common vasculitis of childhood, peaking around age 6 — close to this 4-year-old — typically preceded by an upper respiratory infection, and affecting small vessels of skin, joints, gut and glomeruli together, which is why the triad of rash, joint pain and abdominal pain appears as one disease rather than three separate problems.\n\nIdiopathic thrombocytopenic purpura causes a purpuric rash from low platelets, but haem-36 is explicit that HSP\'s platelet count is normal — it is a vascular, not a platelet, purpura — and ITP does not typically cause joint swelling or abdominal pain, since it is a bleeding disorder rather than a vasculitis affecting the gut and joints. Meningococcaemia causes a purpuric rash in a septic, unwell, febrile child, a much more acute and dangerous presentation than this description, and it does not classically cause joint swelling as a presenting feature the way HSP does. Acute leukaemia can cause both purpura (from thrombocytopenia, mal-5) and bone or joint pain from marrow infiltration, but it typically comes with systemic features such as fever, pallor and hepatosplenomegaly (mal-6) rather than this localised, lower-limb rash-arthritis-abdominal-pain triad. Systemic lupus erythematosus can cause a vasculitic rash and joint involvement, but it is far less common in a 4-year-old than HSP and its rash is not typically the same lower-limb-predominant purpura pattern.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Henoch-Schönlein purpura\'s triad — lower-limb purpura, joint swelling (knees and ankles) and abdominal pain, with a normal platelet count — distinguishes it from ITP (thrombocytopenic, no joints or abdomen), meningococcaemia (septic, unwell), leukaemia (systemic marrow-failure features) and SLE (rarer at this age, different rash distribution).',
  source:'Pediatrics endpoint part2.pdf p.1504'
},

{
  id:'pedep2-mf2-39', bank:'endpoint', module:'pediatrics', chapter:'cardiac',
  stem:'Which of the following is the most common cause of heart failure in the first week of life?',
  options:['Coarctation of the aorta','Large ventricular septal defect','Tetralogy of Fallot','Hypoplastic left heart syndrome','Patent ductus arteriosus'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Hypoplastic left heart syndrome often presents with shock and heart failure in the first few days as the ductus arteriosus closes.\n\n---\n\ncard-9\'s pulse-pattern table lists hypoplastic left heart syndrome alongside coarctation and interrupted aortic arch as the three duct-dependent systemic lesions that collapse when the duct closes, but marks HLHS out as the most severe of the three: ALL peripheral pulses are absent, against absent femorals only in coarctation, because in HLHS the underdeveloped left heart cannot support the systemic circulation at all once the duct-fed right-to-left flow across the arterial duct is lost. card-1\'s six-group table places HLHS in the "sick neonate with obstruction" group, whose symptom column reads simply COLLAPSED WITH SHOCK — the first-week presentation this stem describes.\n\nA large VSD is card-1\'s own commonest CHD, at 30-40% of newborns with a defect, but card-2 explains why it is quiet at birth: pulmonary vascular resistance is still high in the first days, so the left-to-right shunt across the VSD stays small, and heart failure only declares once PVR falls over the following weeks — card-2 gives 2-8 weeks, not the first week, as the age this failure appears. Tetralogy of Fallot sits in card-1\'s right-to-left shunt group, whose symptom is "blue", not "breathless" — it is a cyanosis lesion and the commonest cause of cyanosis after age 1, not a first-week heart-failure presentation. Patent ductus arteriosus is about 10% of CHD (card-1) and behaves like the VSD it is mechanistically similar to: a large PDA\'s left-to-right shunt widens as PVR falls, producing failure on the same weeks-long timescale as a VSD rather than in the first days. Coarctation of the aorta is genuinely a close second on card-9\'s own table — it collapses on the same duct-closure timeline as HLHS — but the table\'s own pulse pattern marks it as the less complete lesion (femorals absent, not all pulses), which is the material\'s basis for treating HLHS as the more classically severe first-week presentation.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'HLHS, coarctation and interrupted aortic arch are all duct-dependent systemic lesions that collapse in the first days of life as the duct closes, but HLHS is the most complete (all peripheral pulses absent, not just femorals); VSD and PDA instead decompensate at 2-8 weeks as pulmonary vascular resistance falls, and Fallot is a cyanosis lesion, not a first-week failure presentation.',
  source:'Pediatrics endpoint part2.pdf p.1510'
},

{
  id:'pedep2-mf2-40', bank:'endpoint', module:'pediatrics', chapter:'resp-bronch',
  stem:'A 3-year-old child presents with a barking cough and inspiratory stridor. What is the most likely diagnosis?',
  options:['Bronchiolitis','Epiglottitis','Foreign body aspiration','Laryngotracheobronchitis (croup)','Asthma'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Croup is a common cause of barking cough and stridor in children aged 6 months to 6 years.\n\n---\n\ninf-15\'s epiglottitis-versus-croup table names the barking cough as croup\'s own column, against absent or slight cough for epiglottitis, and lists the causative organism as parainfluenza virus, the one row of that column the material sources directly. **The rest of the croup column — the barking-cough-and-stridor picture, the typical 6-month-to-6-year age band, and the low-grade or absent fever — is flagged in inf-15 itself as not taken from the course material, since no cached deck teaches croup as a disease in its own right; it is filed here in `resp-bronch` for that reason.** This 3-year-old\'s barking cough and stridor with no other detail given matches that supplied picture.\n\nBronchiolitis is instead defined in the material by age and by a different sound: a seasonal RSV illness in infants under 12-24 months (the two guideline definitions disagree on the exact cutoff) with wheeze or bilateral crackles, not stridor, and a 3-year-old is already older than either definition\'s upper limit. Epiglottitis is inf-15\'s own hallmark comparison: rapid onset, high fever, drooling, a muffled "hot potato" voice and a tripod posture, with cough absent or only slight — the opposite pattern to this barking, stridulous presentation. Foreign body aspiration typically has a sudden onset with a choking history and can cause stridor or unilateral wheeze, but it does not typically produce a barking cough, and no choking history is given here. Asthma\'s hallmark sound is expiratory wheeze from lower airway obstruction, not inspiratory stridor from the upper airway, so it does not fit this picture at all.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Barking cough plus inspiratory stridor is croup (laryngotracheobronchitis) — parainfluenza is the one sourced fact, the rest of the croup picture is supplied since no cached deck teaches it as a disease. Bronchiolitis is an infant wheeze/crackle illness, epiglottitis is the opposite drooling/no-cough/high-fever picture, foreign body needs a choking history, and asthma wheezes rather than stridors.',
  source:'Pediatrics endpoint part2.pdf p.1512'
},

{
  id:'pedep2-mf2-43', bank:'endpoint', module:'pediatrics', chapter:'dev-problems',
  stem:'A 4-year-old boy has delayed speech, prefers playing alone, gets upset with changes, and avoids eye contact.\nWhat is the most likely diagnosis?',
  options:['Deaf mutism','Normal development','Autism','Speech delay'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> The child shows delayed speech, social avoidance, repetitive behaviors, and distress with changes, which are classic features of autism. Deafness or simple speech delay would not explain all social and behavioral signs.\n\n---\n\ndp-9\'s classical triad for autism spectrum disorder is a defect in language/communication, a defect in socialisation, and imposition of routine and repetitive behaviour — all three of which this stem supplies: delayed speech (language), preferring to play alone and avoiding eye contact (socialisation), and getting upset with changes (routine/repetitive domain). dp-11\'s own social-interaction column separately names "prefers own company; no interest or ability in interacting with peers" and "gaze avoidance" as autism features, and its restricted-and-repetitive column names "excessive adherence to routine" — matching this child\'s distress at any change to it.\n\nDeaf mutism could explain the delayed speech alone, since a child who cannot hear language cannot easily produce it, but dp-9\'s and dp-11\'s socialisation and routine-related features — avoiding eye contact, preferring solitary play, distress with change — have no hearing-based explanation, which is why a single-domain diagnosis like deafness cannot account for this three-domain picture. Normal development is excluded by dp-11\'s own early-signs list, which flags poor eye contact and delayed language as departures from the typical pattern rather than normal variation. Speech delay alone, like deafness, would only explain the language domain; it does not touch the social avoidance or the routine-bound behaviour this child also shows, so a diagnosis confined to speech cannot cover the whole picture the way autism\'s three-domain triad does.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Autism\'s classical triad — language/communication defect, socialisation defect, and routine/repetitive behaviour — requires all three domains; deaf mutism and speech delay each explain only the language domain, so neither accounts for the social avoidance and distress-with-change this child also shows.',
  source:'Pediatrics endpoint part2.pdf p.1518'
},

{
  id:'pedep2-mf2-44', bank:'endpoint', module:'pediatrics', chapter:'haem-bleeding',
  stem:'A term infant delivered at home is brought on day 4 with oozing from the umbilical stump. The mother is unsure if the newborn received vitamin K.\nWhich of the following blood results is most likely to be abnormal?',
  options:['Platelets','Prothrombin time','APTT','Hemoglobin','Antiplatelet antibodies'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Vitamin K is needed for clotting factors II, VII, IX, and X. Deficiency prolongs prothrombin time (PT) while platelets and APTT may remain normal.\n\n---\n\nhaem-44 names this exact scenario, haemorrhagic disease of the newborn, as vitamin K\'s deficiency state, with a day 2-7 classic onset window that covers this day-4 presentation, and states plainly that vitamin K\'s function is carboxylation of clotting factors, deficiency giving haemorrhagic disease of the newborn with a prolonged prothrombin time. haem-29 places vitamin K deficiency at the common and extrinsic limbs of the cascade, which is why PT (the extrinsic-limb test) is the result this question keys as abnormal, and haem-44\'s own table marks platelets as staying normal in vitamin K deficiency, matching the printed explanation\'s claim about platelets specifically.\n\n**A genuine tension is worth recording rather than resolving: the printed explanation here says APTT "may remain normal", but haem-44\'s own table for the same condition marks PTT as "Prolonged", and haem-29 separately notes that factor IX, an intrinsic-limb factor, is also vitamin-K-dependent — which would argue for a prolonged APTT too. The two course sources do not agree with each other on this one point. Nothing here changes the printed key: PT is prolonged on every version of the material, so it remains the answer regardless of which account of APTT is followed.** Haemoglobin is not part of the coagulation screen and would only fall after a large enough bleed to cause anaemia, not as a direct marker of the clotting defect itself. Antiplatelet antibodies are the test for immune thrombocytopenia, a platelet-number disorder unrelated to a vitamin-K-dependent factor deficiency.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Vitamin K deficiency (haemorrhagic disease of the newborn, classic onset day 2-7) prolongs PT via factors II, VII and X; platelets stay normal. The material itself disagrees on whether APTT is also prolonged (haem-44\'s table says yes, the printed explanation says no) — recorded as a contradiction, since PT is the answer either way.',
  source:'Pediatrics endpoint part2.pdf p.1520'
},

{
  id:'pedep2-mf2-45', bank:'endpoint', module:'pediatrics', chapter:'renal',
  stem:'A 6-year-old boy presents with periorbital oedema and frothy urine. Urinalysis shows 4+ protein and no blood. What is the most likely diagnosis?',
  options:['Glomerulonephritis','Minimal change disease','IgA nephropathy','Post-streptococcal nephritis','Alport syndrome'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Minimal change disease is the most common cause of nephrotic syndrome in children and typically presents with heavy proteinuria and oedema.\n\n---\n\nren-13 defines nephrotic syndrome as heavy proteinuria plus oedema plus hypoalbuminaemia, and its nephrotic-versus-nephritic table marks protein as "heavy — 4+ on dipstick" and blood as "little or none" for the nephrotic pattern — exactly the 4+ protein, no blood urinalysis this stem gives. ren-13 then names minimal change disease as the idiopathic cause of nephrotic syndrome and states it accounts for 85-90% of children with nephrotic syndrome, with a typical age of 1-10 years (this 6-year-old fits), gross periorbital, ascitic and scrotal oedema, and normal blood pressure and complement.\n\nGlomerulonephritis and post-streptococcal nephritis are both filed under ren-13\'s nephritic column, not nephrotic: their protein is mild to moderate rather than heavy, and their blood is gross or microscopic haematuria with red cell casts — the opposite of the "no blood" finding here. IgA nephropathy, ren-11\'s commonest chronic glomerular disease in children, classically presents with synpharyngitic gross haematuria within 1-2 days of a respiratory or gut infection, again a haematuria-led picture rather than this bloodless, heavy-proteinuria one. Alport syndrome is ren-8\'s familial glomerular cause of haematuria, again defined by blood in the urine rather than by nephrotic-range proteinuria without blood.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Heavy proteinuria (4+) with oedema and NO blood is the nephrotic pattern on ren-13\'s own table; minimal change disease causes 85-90% of childhood nephrotic syndrome. Glomerulonephritis, post-streptococcal nephritis, IgA nephropathy and Alport syndrome are all haematuria-led (nephritic or glomerular-bleeding) pictures, not this bloodless nephrotic one.',
  source:'Pediatrics endpoint part2.pdf p.1522'
},

{
  id:'pedep2-mf2-46', bank:'endpoint', module:'pediatrics', chapter:'dev-problems',
  stem:'A 4-year-old boy is referred to his GP by his teacher at nursery. She has noticed that he has delayed speech and has only a handful of words. He struggles with imaginative play and usually plays alone. He becomes upset if there is a change to the daily routine. In the surgery, he does not make eye contact. There are no dysmorphic features. What is the most likely diagnosis?',
  options:['Selective mutism','Normal development','Autism','Speech delay','Fragile X'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Autism is a pervasive developmental disorder characterized by speech delay and poor social communication skills. It is part of a spectrum of disorders including Asperger’s syndrome. Autistic children struggle to interpret non-verbal communications and to form relationships with peers. Autistic behaviours are associated with a number of syndromes including fragile X, untreated phenylketonuria, and Williams syndrome.\n\n---\n\ndp-9\'s triad and dp-11\'s three-column table again match this vignette feature for feature: delayed speech with only a handful of words (language/communication), struggling with imaginative play and usually playing alone (dp-11\'s "prefers own company; no interest or ability in interacting with peers"), and becoming upset with a change to routine (dp-11\'s "excessive adherence to routine"); not making eye contact is dp-11\'s own "gaze avoidance" sign. dp-9 also notes females are more likely than males to have associated cognitive impairment despite the 4:1 male-to-female ratio, though sex is not what distinguishes the options here.\n\nSelective mutism is a diagnosis of a child who can speak normally in some settings (commonly home) but not others, driven by anxiety rather than a pervasive language and social deficit; it does not explain the imaginative-play difficulty, the routine-bound distress or the gaze avoidance this child also shows. Normal development is excluded by dp-11\'s own early-signs list, which flags poor eye contact and delayed language as departures from typical development rather than variation within it. Speech delay alone would only account for the handful-of-words finding, not the social and behavioural features. Fragile X is named in the printed explanation itself as one of the syndromes autism is *associated with*, not as a stand-alone diagnosis that better explains this picture than autism does — and the stem\'s own "no dysmorphic features" line points away from a syndromic diagnosis such as fragile X, whose recognised phenotype includes dysmorphic features not present here.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Delayed speech, solitary play with poor imaginative play, distress with routine change and gaze avoidance together match autism\'s three-domain picture; selective mutism, normal development and isolated speech delay each explain only part of it, and fragile X is an associated syndrome, not a better-fitting stand-alone diagnosis, especially with no dysmorphic features present.',
  source:'Pediatrics endpoint part2.pdf p.1524'
},

];
