// house-ch14-endocrine.array.js — STAGED transcription of House ch.14 "Diabetes & endocrinology", book pp.111–117.
// Staged by Codex via tools/chapter-loop.js (stage) from 300-dpi half-sheet renders; each run's raw answer sits in
// the scratchpad and is summarised in house-ch14-endocrine.loop.json. UNVERIFIED until the `check` step is acked —
// every key, dose, unit and exponent must be read against the page image before this file is drafted or spliced.
// Schema: { n, p:'<book page>', boiler, stem, opts:[...], key:<zero-based index | null>, fig?, straddle?, note }.
var PEDHD_ENDO_STAGED = [
  { n:1, p:"111", boiler:true,
    stem:"Ellie, a 7-year-old girl, is newly diagnosed with diabetes mellitus. She has been drinking lots of fluid and has had to pass urine frequently. She has a markedly raised blood glucose (20 mmol/L) and heavy glycosuria. Which of the following is most likely to be true about her diabetes?",
    opts:["Her diagnosis should be confirmed with an oral glucose tolerance test", "She can be managed with oral hypoglycaemic agents and dietary modification", "She will have gained weight in the last few weeks", "The incidence in the UK is falling", "There is autoimmune pancreatic β-cell damage"],
    key:4,
    note:"" },
  { n:2, p:"111", boiler:true,
    stem:"James, aged 11 years, has type 1 diabetes mellitus. While playing Football during the mid-morning break at a holiday camp, he suddenly feels faint. His classmates call the supervisor who finds him lying unresponsive in the playground. What should be his immediate management?",
    opts:["Call an ambulance", "Check blood glucose", "Give a glucose drink", "Give buccal glucose gel", "Give insulin"],
    key:3,
    note:"" },
  { n:3, p:"111", boiler:true,
    stem:"Catherine, aged 15 years, has had type 1 diabetes mellitus for 7 years. Her insulin regimen has remained unchanged for the last 7 months. Her HbA1C has increased from 58 mmol/mol (7.5%) to 90 mmol/mol (10.3%) (desired level <58 mmol/mol). The most recent blood glucose levels as recorded in her book are shown in the figure in the next page (overleaf):",
    opts:["During the summer holidays she took less exercise", "She has reduced her insulin dosage to try to lose weight", "She is taking more insulin than she needs", "She is regularly eating snacks and indulging in high carbohydrate food", "Some of the blood glucose measurements are fictitious"],
    key:4,
    fig:"Blood glucose record chart, frontal view; printed labels: Insulin injection; Blood; Time; Dosage; Date; Before breakfast; 2hr after breakfast; Before mid-day meal; 2hr after mid-day meal; Before evening meal; 2hr after evening meal; Before bed; During night; Comments; Please refer to your Doctor or Diabetes Nurse specialist as to when you should perform your tests.",
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.111 -> p.112" },
  { n:4, p:"113", boiler:true,
    stem:"Mohammed, a 12-year-old boy with type 1 diabetes mellitus, is reviewed in the outpatient clinic. In spite of maintaining good control of his diabetes, his height has remained static for 9 months. He says his appetite is alright, but he has lost interest in football, which is his passion, as he says he can't keep up with the other boys any more. He just stays at home and watches TV, but wants to be out playing football and getting back his energy. A full blood count and C-reactive protein are normal and his HbA1C is satisfactory. What is the most likely diagnosis?",
    opts:["Anorexia nervosa", "Depression", "Growth hormone deficiency", "Hypothyroidism", "Inflammatory bowel disease"],
    key:3,
    note:"" },
  { n:5, p:"113", boiler:true,
    stem:"Zeinab, aged 15 years, has had 3 months of diarrhoea, weight loss and palpitations. You suspect hyperthyroidism. Which combination of thyroid function test results would confirm the diagnosis?",
    opts:["High TSH and high T4 levels", "High TSH and low T4 levels", "Low TSH and high T4 levels", "Low TSH and low T4 levels", "Normal TSH and high T4 levels"],
    key:2,
    note:"" },
  { n:6, p:"113", boiler:true,
    stem:"George, a 2-week-old male infant, presents to the Emergency Department with vomiting, diarrhoea and poor feeding. Investigations show:\n• sodium 112 mmol/L (normal range 133–145 mmol/L)\n• potassium 6.8 mmol/L (normal range 3.5–6.0 mmol/L)\n• urea 7.8 mmol/L (normal range 2.5–8.0 mmol/L)\n• creatinine 30 mmol/L (normal range 20–65 mmol/L)\n• blood glucose 1.7 mmol/L (normal range >2.6 mmol/L)\n• infection screen—negative\nWhat is the most likely cause?",
    opts:["Acute kidney injury", "Congenital adrenal hyperplasia", "Congenital adrenal hypoplasia", "Cushing syndrome", "Gastroenteritis"],
    key:1,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.113 -> p.114" },
  { n:7, p:"114", boiler:true,
    stem:"A newborn baby has recently been delivered. The midwife requests an urgent paediatric review of the baby because she cannot tell if the baby is male or female (as shown in the opposite figure). The parents are asking what sex their baby is. What should you tell them?",
    opts:["You are unable to tell if the baby is male or female, and tell the parents it is likely to be a mixture of both sexes, i.e. ovotesticular disorder of sex development (DSD – or hermaphroditism)", "You are unable to tell right now and a detailed assessment of the baby including scans and blood tests will be needed before a specialist can tell them", "You are unable to tell right now but will be able to assign a sex as soon as you get the baby's chromosomes back", "You think it is likely to be a girl so tell them the baby should be named as a female on the birth certificate pending the results", "You think it is likely to be a boy so tell them the child should be named as a male on the birth certificate pending the results"],
    key:1,
    fig:"Photograph, frontal perineal view.",
    note:"" },
  { n:8, p:"114", boiler:true,
    stem:"A baby is born with a disorder of sexual differentiation. Congenital adrenal hyperplasia is suspected. What blood result would confirm the diagnosis?",
    opts:["A low testosterone", "A markedly lowered plasma 17α-hydroxyprogesterone", "A markedly raised cortisol level", "A markedly raised plasma 17α-hydroxyprogesterone", "A raised blood glucose"],
    key:3,
    note:"" },
  { n:9, p:"115", boiler:false,
    stem:"Julie, aged 7 years, has diabetes mellitus. She is admitted to hospital as she has vomited on three occasions. She has a 2-day history of being unwell with a mild fever, sore throat and decreased appetite. Her blood glucose measurement reads ‘high’. Although she was not eating, her parents maintained her usual insulin dose. On examination her temperature is 37.5°C. She is drowsy and confused. Her pulse is 150 beats/min, blood pressure 80/45 mmHg (low for age) and capillary refill time 3 seconds. Examination of her throat shows tonsillitis. Her blood glucose is 22 mmol/L. Which of the following is the best course of action to take immediately for that patient?",
    opts:["Oral glucose drink", "Intravenous infusion of normal saline (0.9% sodium chloride)", "Subcutaneous insulin", "Fluid resuscitation with normal saline (0.9% sodium chloride)", "Intravenous infusion of 5% glucose"],
    key:3,
    note:"" },
  { n:10, p:"115", boiler:false,
    stem:"Jon is 12 years old. His brother has diabetes. He has started to drink a lot of fluids and pass a lot of urine. He checked his blood glucose on his brother’s glucometer. It was 19 mmol/L. When he arrives in the Emergency Department he is well with no signs of dehydration. Diabetes mellitus type 1 is diagnosed as his blood glucose is 21 mmol/L. A venous blood sample shows a normal pH with 2 mmol/L of ketones (within the normal range) and a HbA1c blood test result is awaited. Which of the following is the best course of action to take immediately for that patient?",
    opts:["Oral glucose drink", "Intravenous infusion of normal saline (0.9% sodium chloride)", "Subcutaneous insulin", "Fluid resuscitation with normal saline (0.9% sodium chloride)", "Intravenous infusion of 5% glucose"],
    key:2,
    note:"" },
  { n:11, p:"115", boiler:false,
    stem:"Harriet, a 5-year-old girl, is known to have diabetes mellitus type 1. She was only diagnosed 2 months ago and is on a basal bolus regime of insulin. She is running around the garden at home when her mother notices she suddenly becomes aggressive towards her brother and looks pale and not her usual self. Her mother checks her blood glucose, which is 3 mmol/L. Which of the following is the best course of action to take immediately for that patient?",
    opts:["Oral glucose drink", "Intravenous infusion of normal saline (0.9% sodium chloride)", "Subcutaneous insulin", "Fluid resuscitation with normal saline (0.9% sodium chloride)", "Intravenous infusion of 5% glucose"],
    key:0,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.115 -> p.116" },
  { n:12, p:"116", boiler:false,
    stem:"Sophie, a 9-year-old girl with type 1 diabetes mellitus, develops a fever along with vomiting and diarrhoea. After 2 days her mother takes her to the local paediatric assessment unit as she continues to vomit. On examination her temperature is 37.5°C. She is able to talk to her mother. She has clinical dehydration. Her pulses, capillary refill time and blood pressure are normal. Her blood glucose is 16 mmol/L. Which of the following is the best course of action to take immediately for that patient?",
    opts:["Oral glucose drink", "Intravenous infusion of normal saline (0.9% sodium chloride)", "Subcutaneous insulin", "Fluid resuscitation with normal saline (0.9% sodium chloride)", "Intravenous infusion of 5% glucose"],
    key:1,
    note:"" },
  { n:13, p:"116", boiler:false,
    stem:"A newborn baby is noted to have coarse facies, a large fontanelle and hypotonia on routine examination. He also has jaundice. His blood sugar levels are normal. Which of the following investigations would be most likely to reveal the underlying diagnosis?",
    opts:["Growth hormone", "Karyotype", "Thyroid function tests", "Blood group", "CK"],
    key:2,
    note:"" },
  { n:14, p:"116", boiler:false,
    stem:"A 7-day-old male baby is brought into the emergency department with a 1-day history of poor feeding and vomiting. He was born at term by spontaneous vaginal delivery weighing 3200 g and his postnatal period was uneventful. On arrival, he appears lethargic and has moderate dehydration. His weight is 2750 g. His blood glucose is 2.0 and his blood gas reveals a sodium of 124 mmol/L and the potassium is 6.8 mmol/L. Following resuscitation and stabilization, what is most likely to confirm the diagnosis?",
    opts:["Abdominal ultrasound scan", "ACTH level", "Karyotype", "17 Hydroxyprogesterone level", "Chloride level"],
    key:3,
    note:"" },
  { n:15, p:"117", boiler:false,
    stem:"A 14-year-old boy is admitted with diabetic ketoacidosis. Intravenous insulin has been running at 0.1 units/kg/h for the last 12 hours alongside a 500 ml bag of 0.9% normal saline. His last blood sugar is 22 mmol/L and he has a good urine output. Which of the following are most likely to be decreased?",
    opts:["Serum sodium", "Serum potassium", "Serum lactate", "Serum chloride", "Serum calcium"],
    key:1,
    note:"" },
  { n:16, p:"117", boiler:false,
    stem:"On routine newborn examination a baby is noted to have bilaterally undescended testes. Genitalia appears to be male. Which is the most important initial investigation?",
    opts:["Karyotype with FISH for sex-determining region of the Y chromosome", "Abdominal ultrasound scan", "Abdominal CT scan", "17-Hydroxyprogesterone levels", "Urea and electrolytes (U&Es)"],
    key:4,
    note:"" },
];
