// house-ch19-liver.array.js — STAGED transcription of House ch.19 "Liver disorders", book pp.137–140.
// Staged by Codex via tools/chapter-loop.js (stage) from 300-dpi half-sheet renders; each run's raw answer sits in
// the scratchpad and is summarised in house-ch19-liver.loop.json. UNVERIFIED until the `check` step is acked —
// every key, dose, unit and exponent must be read against the page image before this file is drafted or spliced.
// Schema: { n, p:'<book page>', boiler, stem, opts:[...], key:<zero-based index | null>, fig?, straddle?, note }.
var PEDHD_LIV_STAGED = [
  { n:1, p:"137", boiler:true,
    stem:"Manuel, a 3-day-old infant is born to healthy parents. He presents with oozing from the umbilical stump and sleepiness. On examination he is pale and grunting. He responds only to painful stimuli. He has marked hepatomegaly. Oxygen is delivered and senior help summoned as he is very unwell. The nurse practitioner inserts an intravenous line and asks what blood tests you would like first. From the following list of blood tests pick the one you would undertake first.",
    opts:["Ammonia", "Blood culture", "Blood gas", "Blood glucose", "Coagulation studies"],
    key:3,
    note:"" },
  { n:2, p:"137", boiler:true,
    stem:"Reece, a 4-week-old male infant living in the UK, is taken to his family doctor because he is jaundiced. He was born at term and is breastfed. His mother reports that he has always looked yellow and has started to develop bruises. His stools are now pale in colour. On examination he has hepatomegaly. Which of the following investigations would you undertake first?",
    opts:["Faecal elastase", "Serum conjugated and unconjugated bilirubin", "Sweat test", "Ultrasound scan of the liver", "Urinalysis"],
    key:1,
    note:"" },
  { n:3, p:"137", boiler:true,
    stem:"Javid is a 5-month-old Asian baby born at term in rural Pakistan. He presents with jaundice. His mother’s blood group is AB rhesus positive. His stool and urine are a normal colour. He is breastfed, although he has not been feeding well. His mother is concerned that this could be due to his constipation. When you examine the infant (in the opposite figure) you note that he has dry skin and an umbilical hernia. Which of the following is the most likely diagnosis?",
    opts:["Biliary atresia", "Congenital infection", "Galactosaemia", "Rhesus haemolytic disease of the newborn", "Hypothyroidism"],
    key:4,
    fig:"clinical photograph, frontal facial view",
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.137 -> p.138" },
  { n:4, p:"138", boiler:true,
    stem:"Luna, a 32-year-old Cantonese woman has just given birth to her third child. She arrived in the UK 3 months ago to live with her extended family following the death of her husband. Antenatal screening shows that she is hepatitis B surface antigen (HBsAg) positive and hepatitis B e antigen (HBeAg) negative. The newborn infant looks well and has fed. The postnatal team are keen to send the mother and baby home. Which of the following is the best advice to give concerning immunization of the family?",
    opts:["Hepatitis B vaccination for the baby", "Hepatitis B vaccination for the baby and all other children", "Hepatitis B vaccination for the baby and mother", "Hepatitis B vaccination for the baby with hepatitis B immunoglobulin", "No treatment required"],
    key:1,
    note:"" },
  { n:5, p:"138", boiler:true,
    stem:"Summer, a 12-year-old girl, is seen in the Emergency Department. Her parents report that her school performance has been deteriorating and recently she has become confused and unsteady on her feet. Examination findings of her eyes are shown in the opposite figure. Select the most likely diagnosis.",
    opts:["Glaucoma", "Hyperthyroidism", "Illicit drug use", "Intracranial tumour", "Wilson disease"],
    key:4,
    fig:"clinical photograph, close-up eye view",
    note:"" },
  { n:6, p:"139", boiler:false,
    stem:"Jason, a 3-week-old boy, is still jaundiced. His mother is reassured that this is likely to be 'breast milk' jaundice as she is fully breastfeeding him. He presents 3 weeks later with poor feeding, vomiting and bruising on his forehead and limbs. He has pale stools. On examination the liver is palpable 4 cm below the costal margin. Which of the following is the most likely diagnosis of that patient?",
    opts:["Hepatitis A", "Hepatitis B", "Biliary atresia", "Galactosemia", "Primary sclerosing cholangitis"],
    key:2,
    note:"" },
  { n:7, p:"139", boiler:false,
    stem:"Raj, a previously well 14-year-old Asian boy, is noted to be jaundiced. He has recently returned to the UK from India where he was visiting relatives in a rural village. He had a 10-day diarrhoea and vomiting illness whilst in India. Which of the following is the most likely diagnosis of that patient?",
    opts:["Hepatitis A", "Hepatitis B", "Biliary atresia", "Galactosemia", "Primary sclerosing cholangitis"],
    key:0,
    note:"" },
  { n:8, p:"139", boiler:false,
    stem:"A 5-week-old southern Asian male infant born in the UK presents to the Paediatric Assessment Unit with vomiting. He has not gained weight since birth. On examination you find an infant who is jaundiced, lethargic and hypotonic. Cataracts are present. Which of the following is the most likely diagnosis of that patient?",
    opts:["Hepatitis A", "Hepatitis B", "Biliary atresia", "Galactosemia", "Primary sclerosing cholangitis"],
    key:3,
    note:"" },
  { n:9, p:"139", boiler:false,
    stem:"Lee is a 12-year-old Chinese boy who moved with his parents from China 2 years ago. He presents with episodes of vomiting which is blood-stained. On examination he is jaundiced, malnourished and has splenomegaly. Which of the following is the most likely diagnosis of that patient?",
    opts:["Hepatitis A", "Hepatitis B", "Biliary atresia", "Galactosemia", "Primary sclerosing cholangitis"],
    key:1,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.139 -> p.140" },
];
