// house-ch20-malignant.array.js — STAGED transcription of House ch.20 "Malignant disease", book pp.141–148.
// Staged by Codex via tools/chapter-loop.js (stage) from 300-dpi half-sheet renders; each run's raw answer sits in
// the scratchpad and is summarised in house-ch20-malignant.loop.json. UNVERIFIED until the `check` step is acked —
// every key, dose, unit and exponent must be read against the page image before this file is drafted or spliced.
// Schema: { n, p:'<book page>', boiler, stem, opts:[...], key:<zero-based index | null>, fig?, straddle?, note }.
var PEDHD_MAL_STAGED = [
  { n:1, p:"141", boiler:true,
    stem:"Concerning the epidemiology of childhood cancer, which of the following types is most common in the UK?",
    opts:["Bone tumour", "Brain tumour", "Leukaemia", "Neuroblastoma", "Wilms tumour (nephroblastoma)"],
    key:2,
    note:"" },
  { n:2, p:"141", boiler:true,
    stem:"Polly is a 2-year-old girl who is receiving chemotherapy for her acute lymphoblastic leukaemia. She is known to be neutropenic and has developed a fever of over 38.5°C. What is the most appropriate course of action?",
    opts:["Be admitted to hospital for observation", "Be started immediately on oral antibiotics", "Have her blood count and inflammatory markers (e.g. C-reactive protein) measured", "Have blood cultures taken and be started on intravenous antibiotics", "See her general practitioner for further assessment and decision regarding antibiotics"],
    key:3,
    note:"" },
  { n:3, p:"141", boiler:true,
    stem:"Mohammed is a 3-year-old boy who is reviewed in the Paediatric Assessment Unit. He has a history of weight loss and lethargy. His mother is also concerned as he keeps crying and complains of pain in his tummy. On examination of his abdomen he has an extensive mass. The doctor is worried he may have a childhood malignancy. Which of the following investigations would be the most useful in making the diagnosis?",
    opts:["Plasma ammonia", "Plasma LDG (lactate dehydrogenase)", "Serum α-fetoprotein", "Serum beta-HCG (human chorionic gonadotrophin)", "Urinary catecholamines"],
    key:4,
    note:"" },
  { n:4, p:"142", boiler:true,
    stem:"Josh is a 2-year-old boy who presents to the Emergency Department with weight loss and lethargy. On examination he has splenomegaly. You are worried that he has leukaemia. You perform an urgent full blood count. What are the most likely haematology results if he has leukaemia?",
    opts:["Low haemoglobin and low platelets", "High haemoglobin and low platelets", "Normal haemoglobin and normal platelets", "High haemoglobin and raised platelets", "Low haemoglobin and raised platelets"],
    key:0,
    note:"" },
  { n:5, p:"142", boiler:true,
    stem:"Amy is a 2-year-old girl who presents to the outpatient department with a history of developmental regression. She was able to walk but has ‘gone off her legs’ in the last few weeks. Her parents are very worried about her. On further questioning she had been well with no preceding coryzal illness. On examination, she is very unsteady on her feet and her power is reduced in her lower limbs. She has no obvious visual problems and seems able to follow the picture book her mother has brought to clinic. A CT scan is obtained and is shown in the opposite figure. What is the most likely underlying cause?",
    opts:["Cerebral abscess", "Cortical astrocytoma", "Craniopharyngioma", "Medulloblastoma", "Viral encephalitis"],
    key:3,
    fig:"CT scan, axial view",
    note:"" },
  { n:6, p:"143", boiler:true,
    stem:"Mark, a 3-year-old boy, is currently receiving chemotherapy. His sister has developed the rash shown in the opposite figure. Mark is well and does not have a fever. Mark’s parents are worried and phone the oncology ward for advice. What information should they be given?",
    opts:["Advise them to see their general practitioner to check that he is all right", "Mark needs urgent treatment to prevent him from becoming unwell", "Monitor Mark and if he becomes unwell with a fever, bring him to the ward", "Monitor Mark and if he has any signs of the rash, bring him to the ward", "Reassurance – this is a common illness that most children get"],
    key:1,
    fig:"Photograph",
    note:"" },
  { n:7, p:"143", boiler:true,
    stem:"Essa is a 2-year-old boy whose parents have noticed his two eyes look different. He has no other medical history and is not currently on any medication. On examination, the movement of the eyes is normal and the pupils are equal and reactive to light. On checking his pupillary reflex you observe his left pupil looks red but the right looks white. His systemic examination is normal. What is the likely cause of this?",
    opts:["Congenital cataract", "Glaucoma", "Retinoblastoma", "Allergic conjunctivitis", "VI nerve palsy"],
    key:2,
    note:"" },
  { n:8, p:"143", boiler:true,
    stem:"Brittney, aged 5 years, goes to her optician. She has needed glasses for 4 months but her mother thinks her prescription needs changing as she has been getting progressively worsening headaches. When the optician examines her eyes she finds the examination shown in the figure below (next page). Both her eyes have a red reflex. What is the most likely diagnosis?",
    opts:["Craniopharyngioma", "Concomitant squint", "Optic glioma", "Posterior fossa tumour", "Retinoblastoma"],
    key:3,
    fig:"Two-panel illustration, labelled “Looking left” and “Looking right”",
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.143 -> p.144" },
  { n:9, p:"144", boiler:false,
    stem:"Natalia, a 4-year-old girl, presents to her general practitioner. This is her second bad episode of tonsillitis in the same month. She is tired and looks pale and has a number of bruises on her lower legs. On examination she has pallor, scattered purpuric skin lesions and hepatosplenomegaly. Which of the following is the most likely diagnosis of that patient?",
    opts:["Neuroblastoma", "Brain tumour", "Wilms tumour (nephroblastoma)", "Acute lymphoblastic leukaemia", "Hodgkin disease"],
    key:3,
    note:"" },
  { n:10, p:"144", boiler:false,
    stem:"Angel, a 2-year-old boy, presents to his general practitioner with an abdominal mass noticed by his mother on dressing him. He has no other medical problems and is not on any medication. His stool pattern is regular. He is otherwise relatively well in himself. You examine his abdomen and feel a mass in his left abdomen, which does not cross the midline. There is no hepatosplenomegaly. Which of the following is the most likely diagnosis of that patient?",
    opts:["Neuroblastoma", "Brain tumour", "Wilms tumour (nephroblastoma)", "Acute lymphoblastic leukaemia", "Hodgkin disease"],
    key:2,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.144 -> p.145" },
  { n:11, p:"145", boiler:false,
    stem:"Kay, a 3-year-old girl, presents to the Paediatric Assessment Unit as her mother is worried she is pale, tired and ‘not quite right’. She has also lost 2 kg of weight in the last month. On examination the child looks unwell, has pallor and a large firm, irregular abdominal mass in the centre of her abdomen. Which of the following is the most likely diagnosis of that patient?",
    opts:["Neuroblastoma", "Brain tumour", "Wilms tumour (nephroblastoma)", "Acute lymphoblastic leukaemia", "Hodgkin disease"],
    key:0,
    note:"" },
  { n:12, p:"145", boiler:false,
    stem:"Douglas, a 7-year-old boy, visits his general practitioner with his mother. He has been getting headaches over the last 3–5 weeks which have increased in intensity. These have woken him from sleep. His mother reports that he has recently begun vomiting in the morning. His teachers have also commented his school work is getting worse. His mother thinks this may be because his sight has deteriorated as he keeps complaining of double vision. Which of the following is the most likely diagnosis of that patient?",
    opts:["Neuroblastoma", "Brain tumour", "Wilms tumour (nephroblastoma)", "Acute lymphoblastic leukaemia", "Hodgkin disease"],
    key:1,
    note:"" },
  { n:13, p:"145", boiler:false,
    stem:"Connor, a 4-year-old boy, presents to the Paediatric Assessment Unit with his parents. They are worried as he seems to be very tired and complains of his legs hurting. He also seems to have a fine rash that has developed on his arms. On examination he is pale, has a petechial rash on his arms and legs and has hepatosplenomegaly. A full blood count shows low haemoglobin and platelet count. Which of the following is the investigation most likely to confirm the diagnosis of that patient?",
    opts:["Bone marrow aspirate", "Blood film", "Chest X-ray", "Clotting screen", "CT scan"],
    key:0,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.145 -> p.146" },
  { n:14, p:"146", boiler:false,
    stem:"Niamh, a 4-year-old girl, is taken to her general practitioner as her mother has noticed she has red urine. On further questioning she has been more tired than normal and has been complaining of abdominal pain. On examination she is pale with a left-sided abdominal mass. Her urine is red and a dipstick confirms that this is blood. Which of the following is the investigation most likely to confirm the diagnosis of that patient?",
    opts:["Full blood count", "Magnetic resonance imaging (MRI) scan", "Positron emission tomography (PET) scan", "Ultrasound of abdomen", "Urine catecholamines"],
    key:3,
    note:"" },
  { n:15, p:"146", boiler:false,
    stem:"Oscar, a 3-year-old boy, attends the Emergency Department as his mother is worried he has lost weight and looks pale. On examination he has a large irregular mass extending across his abdomen. His blood pressure is high. Which of the following is the investigation most likely to confirm the diagnosis of that patient?",
    opts:["Full blood count", "Magnetic resonance imaging (MRI) scan", "Positron emission tomography (PET) scan", "Ultrasound of abdomen", "Urine catecholamines"],
    key:4,
    note:"" },
  { n:16, p:"146", boiler:false,
    stem:"Francis, a 2-year-old boy, is taken to his general practitioner by his father who is worried as he has become ‘cross-eyed’. Otherwise he is very well in himself and has no history of vomiting. On examination he appears to be well but has an absent red reflex in his left eye. Which of the following is the investigation most likely to confirm the diagnosis of that patient?",
    opts:["Full blood count", "Magnetic resonance imaging (MRI) scan", "Positron emission tomography (PET) scan", "Ultrasound of abdomen", "Urine catecholamines"],
    key:1,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.146 -> p.147" },
  { n:17, p:"147", boiler:false,
    stem:"Carla is a 4-year-old girl who is seen in the Paediatric Assessment Unit complaining of headaches. Her mother has noticed that her eye movements are not normal. The whole family has recently had a sickness bug but Carla seems to have continued vomiting. Which of the following is the investigation most likely to confirm the diagnosis of that patient?",
    opts:["Full blood count", "Magnetic resonance imaging (MRI) scan", "Positron emission tomography (PET) scan", "Ultrasound of abdomen", "Urine catecholamines"],
    key:1,
    note:"" },
  { n:18, p:"147", boiler:false,
    stem:"Solomon is a 12-year-old boy. He has recently lost weight and his ‘glands are up’. His mother reports that the ‘glands’ in his neck have been enlarged for several months now. He has no other medical problems. He has not been having any episodes of fever or night sweats. On examination he has several large, irregular, hard lymph nodes in his neck. They are all greater than 2 cm in size. You order a full blood count and blood film, which show normal results. Which of the following is the investigation most likely to confirm the diagnosis of that patient?",
    opts:["Blood film", "Chest X-ray", "Clotting screen", "CT scan", "Excision biopsy"],
    key:4,
    note:"" },
  { n:19, p:"147", boiler:false,
    stem:"ALL is the commonest form of childhood leukaemia and carries a 5-year survival rate of over 80%. However, prognosis depends on a number of factors. Which of the following is a good prognostic factor in acute lymphoblastic leukaemia?",
    opts:["White cell count (WCC) >50 x 10⁹/L at diagnosis", "Age >10 at diagnosis", "Age <1 year at diagnosis", "Non-B cell, non-T cell leukaemia", "Presence of translocations, e.g. Philadelphia chromosome"],
    key:3,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.147 -> p.148" },
  { n:20, p:"148", boiler:false,
    stem:"There are a number of syndromes that predispose to specific forms of malignancy and require vigilance and screening to make an early diagnosis. Which of the following conditions is not associated with an increased risk of malignancy?",
    opts:["Down syndrome", "Beckwith-Wiedemann syndrome", "Ataxia telangiectasia", "Li Fraumeni syndrome", "Turner syndrome"],
    key:4,
    note:"" },
  { n:21, p:"148", boiler:false,
    stem:"Brain tumours are the most common solid tumour of childhood and presentation may be insidious leading to late diagnosis. Which of the following statements regarding brain tumours in childhood is true?",
    opts:["They are usually supratentorial", "Signs of raised intracranial pressure are rare", "Astrocytomas carry poor prognosis", "Medulloblastomas are the most common type", "Metastasis is common"],
    key:2,
    note:"" },
  { n:22, p:"148", boiler:false,
    stem:"A 2-month-old baby is brought to the GP as a family photo shows a discrepancy in her eyes. On examination a red reflex is present in one eye only. She is otherwise healthy. Which of the following is the most likely diagnosis?",
    opts:["Retinoblastoma", "Retinopathy of prematurity", "Congenital cataracts", "CMV retinitis", "Glaucoma"],
    key:0,
    note:"" },
];
