// House pediatrics bank — Part I, chapter 12 "Neurological disorders", book pp.97-100.
// Half B of the chapter split: n:17 through n:26 (ten entries), drafted from the verbatim staging
// record `content\peds\qb-pages\house-ch12-neurological.array.js` (PEDHD_NEURO_STAGED). Nothing
// transcribed here is new — stem, options and key are copied byte-identical from staging; this file
// adds explanation, objective, source and chapter assignment only.
// id prefix: pedhd-neuro- + staged n. bank:'house', module:'pediatrics'. Grep confirmed the prefix
// free in app\data\questions.peds.js before drafting (0 matches).
var PEDHD_NEURO_DRAFT_B = [

{
  id:'pedhd-neuro-17', bank:'house', module:'pediatrics', chapter:'neuro-nm',
  stem:'Ahmed is a 5-year-old boy who presents to the outpatient clinic with weakness. His parents report that he finds it difficult to climb the stairs at home. This has been becoming progressively worse over the preceding 6–12 months. He is playing on the carpet with his brother when his mother calls him over. He has to roll from his back onto his front in order to stand up. Which of the following is the sign being described in this clinical scenario?',
  options:['Babinski’s sign','Romberg’s sign','Gower’s sign','Kernig’s sign','Chorea'],
  answer:2,
  explanation:'**Gower’s sign — Ahmed uses his own arms to climb up his body because his hip and thigh muscles cannot lift his trunk from the floor unaided.**\n\n`neuro-nm` §`neuro-18` defines it directly: **Gowers’ sign is the need to turn prone to rise to standing from a supine position, usually after 3 years of age, indicating proximal muscle weakness** — exactly Ahmed rolling onto his front to stand up. The same section places it under **myopathy**, alongside a **waddling gait and hyperlordosis**, as the presentation pattern of proximal weakness. His difficulty climbing stairs over 6–12 months is the other classic early clue the material gives for the same mechanism: stair-climbing needs hip and knee extensors to lift the whole body weight, the same muscle groups that fail first in a myopathy. `neuro-nm` §`neuro-24` names the disease Gower’s sign is taught against most often — **Duchenne muscular dystrophy**, diagnosed clinically **around 5 years** with **Gowers’ sign, calf pseudohypertrophy and a waddling gait** — which fits Ahmed’s age and course, though the question only asks for the sign, not the diagnosis.\n\nThis entry carries the comparative table for the shared five-sign option menu that also prints on `pedhd-neuro-18`, `pedhd-neuro-19` and `pedhd-neuro-20`, which point back here and each name only their own discriminating token.\n\n| Sign | The stem that keys it | Discriminating clinical token |\n|---|---|---|\n| **Gower’s sign** (this key) | Ahmed — progressive stair-climbing difficulty, rolls prone to stand | Rising from the floor by climbing up the legs with the hands — the deck’s own definition, `neuro-18` |\n| Babinski’s sign (`pedhd-neuro-18`’s key) | Christopher — birth asphyxia, right-sided increased tone and reflexes | Extension of the great toe with fanning of the other toes on plantar stimulation |\n| Romberg’s sign (`pedhd-neuro-19`’s key) | Sayeed — poor coordination, slurred speech, calf wasting | Steady with eyes open, unsteady and swaying once the eyes close, feet together |\n| Kernig’s sign (`pedhd-neuro-20`’s key) | Paolo — fever, photophobia | Pain and back-arching on extending the knee with the hip flexed to 90°, `infection` §`inf-8` |\n| Chorea | Not keyed in this group | Jerky, involuntary, irregular movements — a basal ganglia sign, `neuro-nm` §`neuro-15` |\n\n**Why the other four fail for Ahmed.** Babinski’s sign is an extensor plantar response, tested by stroking the sole, and is not what rolling-to-stand describes. Romberg’s sign specifically tests balance with the eyes closed and points to a sensory or dorsal-column problem, not a proximal-weakness pattern. Kernig’s sign is a meningeal stretch test unrelated to standing from the floor. Chorea is an involuntary movement disorder, not a manoeuvre a child performs to compensate for weakness.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Recognise Gower’s sign — rising from the floor by climbing up the legs — as the marker of proximal (myopathic) weakness, most classically Duchenne muscular dystrophy, and use the shared four-question sign menu to distinguish it from Babinski’s, Romberg’s and Kernig’s signs and from chorea.',
  source:'pediatric .pdf p.97 (Part I, ch.12 Q17)'
},

{
  id:'pedhd-neuro-18', bank:'house', module:'pediatrics', chapter:'neuro-cp',
  stem:'Christopher attends outpatient clinic for his routine follow-up. He is a 3-year-old boy who did not breathe at birth. Following resuscitation, he required intensive care for the first 5 days of life. He now has increased tone and reflexes in his right upper and lower limbs. On rubbing a blunt instrument up the lateral side of his right foot there is extension of the greater toe and fanning of his toes. Which of the following is the sign being described in this clinical scenario?',
  options:['Babinski’s sign','Romberg’s sign','Gower’s sign','Kernig’s sign','Chorea'],
  answer:0,
  explanation:'**Babinski’s sign — the comparative table for this shared menu (Babinski’s / Romberg’s / Gower’s / Kernig’s sign / Chorea) is written once, in `pedhd-neuro-17`; only this entry’s own discriminating token is added here.**\n\nChristopher’s discriminating token: stroking a blunt instrument up the lateral sole produces **extension of the great toe with fanning of the other toes** — the extensor plantar (Babinski) response, an upper motor neurone sign. `neuro-nm` §`neuro-15` lists **extensor plantar responses, spasticity and brisk reflexes** as the corticospinal (pyramidal) tract pattern, and Christopher already shows two of the other three — **increased tone and increased reflexes**, confined to the right side.\n\nThe stem is a classic unilateral spastic cerebral palsy vignette, and Christopher’s history supplies every risk marker `neuro-cp` names for it: he **did not breathe at birth and needed intensive care for 5 days** — perinatal **hypoxic-ischaemic encephalopathy / birth asphyxia**, the deck’s own top-listed perinatal risk period for CP (§`neuro-27`). §`neuro-28`’s clinical-type table describes exactly Christopher’s pattern: **unilateral (hemiplegia), often from a perinatal insult, one side affected, arm and leg together, with a positive Babinski sign among spastic CP’s defining features** (≈90% of CP is spastic). The question only asks for the sign’s name, not the underlying diagnosis, but the vignette is worth reading in full because the CP link is why the sign appears at all here.\n\nRomberg’s sign needs a positive-eyes-closed balance test, not a plantar stimulus. Gower’s sign is a manoeuvre for standing up, not a reflex test. Kernig’s sign is a meningeal stretch test of the hip and knee, not the foot. Chorea is a movement pattern seen at rest, not something elicited by stroking the sole.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Identify Babinski’s sign — extension of the great toe with fanning of the others on plantar stimulation — as an upper motor neurone (pyramidal) sign, and place it in a perinatal-asphyxia vignette consistent with unilateral spastic cerebral palsy.',
  source:'pediatric .pdf p.98 (Part I, ch.12 Q18)'
},

{
  id:'pedhd-neuro-19', bank:'house', module:'pediatrics', chapter:'neuro-nm',
  stem:'Sayeed is an 8-year-old Pakistani boy who has developed muscle weakness. His mother reports that he has poor coordination at home and at school. His speech has also recently become slurred. His problems have come on slowly over the last 12–18 months. He has no other medical history and is not taking any medications. On examination you notice that he has wasting of his calves. When standing upright with his legs together and closing his eyes he becomes unsteady and starts to sway. Which of the following is the sign being described in this clinical scenario?',
  options:['Babinski’s sign','Romberg’s sign','Gower’s sign','Kernig’s sign','Chorea'],
  answer:1,
  explanation:'**Romberg’s sign — the comparative table for this shared menu is written once, in `pedhd-neuro-17`; only this entry’s own discriminating token is added here.**\n\nSayeed’s discriminating token: standing with the **feet together and eyes closed** brings on unsteadiness and swaying that is not there with the eyes open. `neuro-nm` §`neuro-15` names exactly this test as **a Romberg sign if sensory involvement is present**, and adds the rule that makes it specific: **a positive Romberg points away from the cerebellum and towards the sensory pathway — a cerebellar patient is unsteady with the eyes open too**. Sayeed is steady with his eyes open, so vision is compensating for a loss of proprioceptive (joint-position) feedback — a sensory, not cerebellar, ataxia.\n\nThe rest of Sayeed’s picture matches a named cause the material gives for this pattern. §`neuro-17`’s Friedreich ataxia list reads almost point for point: **ataxia, dysarthria (his slurred speech), pes cavus, distal wasting** (his calf wasting), with **loss of joint position and vibration sense — the dorsal columns** as the sensory basis for a positive Romberg, and a **slow, progressive course** consistent with his 12–18 month history. Only the question’s own sign — Romberg’s — is what is being tested here; the Friedreich link is supplied because it is the material’s own worked example of a positive Romberg with distal wasting and dysarthria together, not because the stem asks for a diagnosis.\n\nBabinski’s sign is a plantar-stimulus reflex, not a standing-balance test. Gower’s sign is a manoeuvre for rising from the floor, which Sayeed is not shown performing. Kernig’s sign tests hip and knee extension, unrelated to standing balance. Chorea is an involuntary movement pattern, not a positional test.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Identify Romberg’s sign — steady with eyes open, unsteady with eyes closed — as a sensory (dorsal column) sign distinct from cerebellar ataxia, and recognise its classic association with Friedreich ataxia (ataxia, dysarthria, pes cavus, distal wasting).',
  source:'pediatric .pdf p.98 (Part I, ch.12 Q19)'
},

{
  id:'pedhd-neuro-20', bank:'house', module:'pediatrics', chapter:'infection',
  stem:'Paolo is a 7-year-old boy who presents to the Accident and Emergency department with fever. His mother reports that this has been present for the last 8 hours and that he is sleepy and wants to sleep in a dark room. He has no other medical history. On examination you note that he is photophobic. Whilst he is lying on the couch you flex his right knee and hip to 90°. On fully extending the knee, he complains of pain and arches on his back. Which of the following is the sign being described in this clinical scenario?',
  options:['Babinski’s sign','Romberg’s sign','Gower’s sign','Kernig’s sign','Chorea'],
  answer:3,
  explanation:'**Kernig’s sign — the comparative table for this shared menu is written once, in `pedhd-neuro-17`; only this entry’s own discriminating token is added here.**\n\nPaolo’s discriminating token: with the hip flexed to 90°, extending the knee produces **pain and back-arching**. `infection` §`inf-8` defines the sign in exactly those mechanical terms — **Kernig’s sign: pain on straightening the knee with the hip flexed** — and lists it alongside **Brudzinski’s sign, nuchal rigidity and a bulging fontanelle** in the neurologic group of meningitis features. The rest of Paolo’s vignette is drawn from the same grid: **fever, photophobia and lethargy/sleepiness** sit in the general and vital-signs groups the material gives for meningitis (§`inf-8`), fitting an evolving meningitic illness of 8 hours’ duration in a school-age child.\n\nThis entry is filed under `infection` rather than a general-signs chapter because the sign itself is meningitis-specific and its full context — the organism-by-age table, the CSF picture, when lumbar puncture is and is not done — lives there, not in the neurological/neuromuscular chapters the other three siblings in this menu are filed under.\n\nBabinski’s sign is a plantar-stimulus reflex unrelated to hip and knee flexion. Romberg’s sign is a standing balance test, and Paolo is examined lying down. Gower’s sign describes rising from the floor, not a passive limb manoeuvre performed by the examiner. Chorea is an involuntary movement pattern, not a provoked sign.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Elicit and interpret Kernig’s sign — pain and back-arching on knee extension with the hip flexed to 90° — as a meningeal irritation sign, in a vignette of fever, photophobia and lethargy consistent with meningitis.',
  source:'pediatric .pdf p.98 (Part I, ch.12 Q20)'
},

{
  id:'pedhd-neuro-21', bank:'house', module:'pediatrics', chapter:'neurological',
  stem:'A 14-month-old is seen in clinic as his mother is concerned that he may be having seizures. The episodes occur when he is angry or upset. He has colour change followed by collapse and occasional jerking movements. The most likely diagnosis is?',
  options:['Breath holding spells','‘Tet’ spells','Myoclonic epilepsy','Non-epileptic seizure','Vasovagal syncope'],
  answer:0,
  explanation:'**Breath holding spells — an anger-triggered, non-epileptic paroxysmal event, not a seizure.**\n\n`neurological` §`neuro-5` files this under **non-epileptic paroxysmal disorders — convulsive syncope**, warning explicitly that **“not all seizures are epileptic.”** It names **expiratory apnoea syncope, the “blue breath-holding spells”**, as one of the entities on that list. This child’s trigger — becoming **angry or upset** — followed by a **colour change**, then **collapse**, with **occasional jerking movements** as the brain is briefly starved of its normal perfusion, is the textbook breath-holding spell pattern: the child cries, holds the breath in expiration, turns blue or pale, and can have a brief anoxic seizure-like jerk before recovering spontaneously. The age fits too — breath-holding spells characteristically begin in the second year of life, as here at 14 months.\n\n**‘Tet’ spells** are hypercyanotic spells of tetralogy of Fallot, provoked by crying or exertion in a child with an *already known* cyanotic congenital heart lesion causing dynamic right ventricular outflow obstruction; nothing in this stem describes an underlying cardiac diagnosis or the murmur/cyanosis-at-baseline picture that would raise it *(the cardiac mechanism itself is not taken from the course material — supplied because the option needs excluding on more than name alone)*. **Myoclonic epilepsy** is an unprovoked epileptic seizure type with a stereotyped EEG signature, not an event reliably triggered by the child’s emotional state. **Non-epileptic seizure** (functional/psychogenic) is a diagnosis of exclusion typically made in older children who can report the internal experience, not a 14-month-old with an anger trigger and colour change. **Vasovagal syncope** is also listed in §`neuro-5`, but as a reflex response to pain, fear or prolonged standing rather than to anger and crying, and the deck separates it from the breath-holding pattern as its own entity.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Recognise breath-holding spells as a non-epileptic paroxysmal event triggered by anger or upset in a toddler, and distinguish it from Tet spells, myoclonic epilepsy, non-epileptic (functional) seizures and vasovagal syncope.',
  source:'pediatric .pdf p.99 (Part I, ch.12 Q21)'
},

{
  id:'pedhd-neuro-22', bank:'house', module:'pediatrics', chapter:'neurological',
  stem:'A 6-year-old boy is falling behind at school. His mother is concerned he is inattentive. She describes him daydreaming frequently, during which time it is difficult to attract his attention. Routine blood tests are normal. An EEG demonstrates spikes at 3 Hz. The likely diagnosis is which of the following?',
  options:['ADHD – inattentive form','Absence seizures','Juvenile myoclonic epilepsy','Daydreaming','Non-epileptic seizures'],
  answer:1,
  explanation:'**Absence seizures — the 3 Hz EEG spike is the deciding fact the stem hands over, on top of a classic clinical picture.**\n\n`neurological` §`neuro-8` describes absence seizures as **brief loss of consciousness** in which the child **“stares blankly into space,” with cessation of activity for seconds** and **no aura and no loss of posture** — matching this boy’s frequent “daydreaming” during which his mother cannot attract his attention. The same section notes absences **may be repeated 50-100 times a day** and that **the patient is fully alert immediately after, with no postictal state**, which is exactly why absence seizures are so easily mistaken for simple inattention or daydreaming rather than a seizure. §`neuro-8` also states the clinical consequence that fits his school difficulty: **“absence seizures impair learning → academic difficulty.”** The EEG finding named in the stem — **generalized 3 Hz spike-and-wave** — is the classic electrographic signature of childhood absence epilepsy, corresponding to §`neuro-8`’s own criterion of a **bilaterally synchronous discharge on EEG** for a generalized seizure *(the specific 3 Hz frequency value is not itemised in the cached theory, which describes the EEG only as bilaterally synchronous; supplied because it is the number the stem quotes and needs interpreting)*.\n\n**ADHD – inattentive form** would not produce an abnormal, epileptiform EEG; ADHD is a behavioural diagnosis, not an electrographic one. **Juvenile myoclonic epilepsy** presents with **brief, shock-like myoclonic jerks**, typically in adolescence, not staring spells in a 6-year-old (§`neuro-8`). **Daydreaming** is excluded by the abnormal EEG — ordinary inattention does not generate 3 Hz spikes. **Non-epileptic seizures** are functional events without an epileptiform EEG correlate; here the EEG is positive, arguing against that diagnosis.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Diagnose childhood absence epilepsy from staring spells mistaken for daydreaming/inattention plus a generalized spike-wave EEG, and exclude ADHD, juvenile myoclonic epilepsy, ordinary daydreaming and non-epileptic seizures.',
  source:'pediatric .pdf p.99 (Part I, ch.12 Q22)'
},

{
  id:'pedhd-neuro-23', bank:'house', module:'pediatrics', chapter:'neurological',
  stem:'A 5-month-old boy is brought in by his mother. She is concerned that he is frequently irritable. She is worried he may be in pain as he tenses and bends his head up, flailing his arms for a few seconds at a time. An EEG is performed which shows large-amplitude slow waves with spikes and sharp waves. The most likely diagnosis is which of the following?',
  options:['Absence seizures','Benign rolandic epilepsy','Gastro-oesophageal reflux','West syndrome (infantile spasms)','Breath holding attacks'],
  answer:3,
  explanation:'**West syndrome (infantile spasms) — the age, the movement and the EEG all point the same way.**\n\n`neurological` §`neuro-9` gives West syndrome’s triad as **epileptic spasms, interictal EEG hypsarrhythmia (spelled “hypsarhythmia” in the deck), and developmental regression — the diagnosis can still be made if one is missing.** The described movement — **tensing, bending the head/trunk up, and flailing the arms for a few seconds** — is the deck’s own description of the spasm itself: **“violent flexor spasms of head, trunk and limbs… lasting 1-2 seconds, in bursts of 20-30.”** The EEG here — **large-amplitude slow waves with spikes and sharp waves** — is a chaotic, high-amplitude pattern consistent with hypsarrhythmia, the classic interictal picture of West syndrome. The age (5 months) sits inside the material’s stated window: **onset 3-12 months, peak 3-7 months (50-77%).** §`neuro-9` also flags exactly the trap this stem is built around: infantile spasms **“may be misinterpreted as colic”** — precisely the mother’s worry that her son is “in pain,” which is the clinical mimicry the material itself warns against.\n\n**Absence seizures** need a **generalized 3 Hz spike-wave** EEG and staring spells with no motor flexion component, and are vanishingly rare at 5 months (§`neuro-8`). **Benign rolandic epilepsy** presents with **nocturnal facial/oral seizures — drooling, unusual sounds, unilateral facial jerking** in a school-age child, not flexor spasms in an infant. **Gastro-oesophageal reflux** can cause arching (Sandifer-like) posturing, but does not produce an abnormal spike-and-sharp-wave EEG — the abnormal EEG is what rules it out here, mirroring the “misinterpreted as colic” trap the material names. **Breath holding attacks** are anger/upset-triggered events with a normal interictal EEG, not linked to a spike-wave pattern.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Diagnose West syndrome (infantile spasms) from flexor spasms in a young infant plus an abnormal (hypsarrhythmia-consistent) EEG, recognise the colic-mimicry trap the material names, and exclude absence seizures, benign rolandic epilepsy, reflux and breath-holding attacks.',
  source:'pediatric .pdf p.99 (Part I, ch.12 Q23)'
},

{
  id:'pedhd-neuro-24', bank:'house', module:'pediatrics', chapter:'neurological',
  stem:'An 8-year-old girl presents with a second generalized tonic-clonic seizure. It required lorazepam to terminate the seizure and a decision is made to start anti-epileptic treatment. Which of the following is first line therapy?',
  options:['Phenobarbital','Sodium valproate','Vigabatrin','Ethosuximide','Phenytoin'],
  answer:1,
  explanation:'**Sodium valproate — the material’s own drug-of-choice table names it first line for exactly this seizure type.**\n\n`neurological` §`neuro-13`’s “Drug of choice by seizure type” table gives **tonic-clonic: first-line valproate, carbamazepine; second-line clobazam, levetiracetam, topiramate.** Of the two named first-line drugs, only sodium valproate is offered among this question’s five options, which resolves the choice. A **second** generalized tonic-clonic seizure is the point at which starting maintenance therapy is considered, since one afebrile seizure alone does not confirm epilepsy; **lorazepam** fits the material’s own note that rescue therapy is used for **“convulsive seizures with loss of consciousness lasting over 5 minutes”** to terminate the acute event, separate from the maintenance drug started afterwards.\n\n**Phenobarbital** and **Phenytoin** do not appear anywhere in §`neuro-13`’s seizure-type table at all — neither is listed as first- or second-line for any of the four seizure types the material covers, so both are excluded on that basis rather than by a positive reason to prefer valproate over them. **Vigabatrin** is named in the same section, but only as the treatment **“mainly”** used for **infantile spasms**, with its use elsewhere limited by a **visual field restriction** side effect — not a tonic-clonic first-line agent. **Ethosuximide** is first line specifically for **absence** seizures, paired there with valproate, not for tonic-clonic seizures.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Select sodium valproate as first-line maintenance therapy for generalized tonic-clonic seizures, distinguishing it from rescue therapy (lorazepam/buccal midazolam) and from drugs indicated for other seizure types or not listed at all in the material’s choice table.',
  source:'pediatric .pdf p.99 (Part I, ch.12 Q24; the stem and option A only are printed on p.99, with options B-E and the answer line printed as the first content on p.100)'
},

{
  id:'pedhd-neuro-25', bank:'house', module:'pediatrics', chapter:'malignant-solid',
  stem:'A 9-year-old girl is brought to her GP with a 2-month history of headaches. Which of the following features of her headaches is not a red-flag symptom?',
  options:['Associated with vomiting','Morning headache','Worse on lying down','Presence of focal neurology','Symmetrical, band-like in nature'],
  answer:4,
  explanation:'**A symmetrical, band-like headache is the description of a tension-type headache, not a red flag — the other four are all raised-intracranial-pressure warning signs the material names.**\n\n`malignant-solid` §`mal-19` lists the warning pattern for a brain tumour directly: **headache “frequent, and worse in the morning or with a change of position”** — grounding both **morning headache** and **worse on lying down** (lying flat is the position change that raises intracranial pressure by increasing venous congestion and reducing CSF drainage) as printed red flags. The same section names **“neurological deficits: problems with vision, speech or motor function from pressure on the brain”** as another warning category — grounding **presence of focal neurology**. §`mal-20`’s worked example, medulloblastoma, pairs **morning headache and vomiting** as the direct clinical consequence of **obstructive hydrocephalus**, which grounds **associated with vomiting** as a red flag rather than a coincidental symptom.\n\n**A symmetrical, band-like headache is not taken from the course material as a stated feature** — neither `malignant-solid` nor the rest of the neurological theory describes this descriptor at all. It is supplied because the option needs a positive reason to be the “not a red flag” answer: a bilateral, pressing or band-like quality without vomiting, morning predominance, positional worsening or focal signs is the classic description of a **tension-type headache**, the commonest primary (non-structural) headache in children, and its absence of any of the printed warning features is exactly why it sits apart from the other four options here.\n\nAll four of the excluded options describe features that, individually, would prompt further work-up for a structural cause under §`mal-19`/§`mal-20`’s framework; only the band-like, symmetrical quality lacks that basis.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Identify the red-flag features of a paediatric headache that raise concern for a structural (brain tumour) cause — morning timing, positional worsening, vomiting and focal neurology — and distinguish them from the reassuring, symmetrical band-like pattern of a tension-type headache.',
  source:'pediatric .pdf p.100 (Part I, ch.12 Q25)'
},

{
  id:'pedhd-neuro-26', bank:'house', module:'pediatrics', chapter:'neurological',
  stem:'An 18-month-old girl is seen on the post take ward round following her first febrile seizure. When counselling her parents about the diagnosis which of the following statements regarding simple febrile convulsions is true?',
  options:['They are often focal in nature','Children frequently go on to develop epilepsy','Occur between ages of 6 months and 5 years','Should always be investigated with lumbar puncture','May occur without fever'],
  answer:2,
  explanation:'**A typical age range of roughly 6 months to 5 years is the true statement; the other four each contradict the material directly.**\n\n`neurological` §`neuro-4`’s simple-versus-complex table gives simple febrile seizures as **generalized tonic-clonic** in pattern, not focal — a **focal** pattern is listed as a feature of the **complex** type instead, so option A describes the wrong type. The same section gives the recurrence risk of later epilepsy as **1-2%** after simple febrile seizures — **“the same as for all children”** — explicitly ruling out option B’s claim that children **frequently** go on to develop epilepsy. The material also states simple febrile seizures **“do not cause brain damage”** and describes lumbar puncture as being done **“to exclude the intracranial infection the definition excludes”** rather than as an automatic step for every case — so option D’s **“always”** overstates the material’s conditional wording. By the deck’s own definition, a febrile seizure is **“an epileptic seizure accompanied by a fever”** — fever is part of the definition itself, so option E’s **“may occur without fever”** is contradicted outright.\n\n⚠️ **A small divergence, noted and not disputed:** §`neuro-4` gives the age band for the febrile-seizure definition as **“between the ages of 5 months and 6 years,”** while this option prints **“ages of 6 months and 5 years”** — a narrower, shifted range that is nonetheless the commonly quoted teaching band for febrile convulsions. The two are close enough, and this is the only true statement among the five, that the discrepancy is recorded here rather than treated as reason to question the printed key; `answer` stays exactly as the bank prints it.\n\nWritten for this bank — pediatric .pdf prints no explanation here.',
  objective:'Counsel on simple febrile convulsions using the material’s own true/false anchors — generalized (not focal) pattern, ~1-2% epilepsy risk, no automatic lumbar puncture, and fever as part of the definition — while noting the source’s minor age-band discrepancy against the printed key.',
  source:'pediatric .pdf p.100 (Part I, ch.12 Q26)'
},

];
