// house-ch17-emergencies.array.js — STAGED transcription of House ch.17 "Paediatric emergencies", book pp.126–134.
// Staged by Codex via tools/chapter-loop.js (stage) from 300-dpi half-sheet renders; each run's raw answer sits in
// the scratchpad and is summarised in house-ch17-emergencies.loop.json. UNVERIFIED until the `check` step is acked —
// every key, dose, unit and exponent must be read against the page image before this file is drafted or spliced.
// Schema: { n, p:'<book page>', boiler, stem, opts:[...], key:<zero-based index | null>, fig?, straddle?, note }.
var PEDHD_EMG_STAGED = [
  { n:1, p:"126", boiler:true,
    stem:"The paediatric team is resuscitating a 3-monthold boy who is in pulseless electrical activity. He was discovered to be blue and lifeless when his parents went to wake him in the morning. The airway has been secured and despite bag valve mask ventilation the child remains blue. Cardiac compressions are given. Where is the most appropriate position on the chest (in the figure below) to do cardiac compressions?",
    opts:["A", "B", "C", "None of the above", "All of the above"],
    key:1,
    fig:"Three-panel illustration, labelled A, B and C; side view.",
    note:"" },
  { n:2, p:"126", boiler:true,
    stem:"You are in the Acute Assessment Unit and see David, a 15-month-old boy, who has a fever of 38.5°C. He has had a runny nose, cough and a fever for 3 days. Since this morning he has slept and has been difficult to wake. His heart rate is raised. He has a rash (Fig. 6.2) scattered over his legs which does not disappear with pressure. Which of the following is the most likely diagnosis?",
    opts:["Acute lymphoblastic leukaemia", "Henoch–Schönlein purpura", "Immune thrombocytopenia", "Non-accidental injury", "Septicaemia"],
    key:4,
    fig:"Clinical photograph, close-up view of legs.",
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.126 -> p.127" },
  { n:3, p:"127", boiler:true,
    stem:"A 3-year-old boy who is unconscious arrives in the Emergency Department. You manage his airway, breathing and circulation. His blood glucose is normal. On examination you note his pupils are as in the opposite figure (bilateral pinpoint pupils). His temperature and other vital signs are otherwise normal. What is the most likely cause?",
    opts:["Third nerve lesion", "Severe hypoxia", "Hypothermia", "Tentorial herniation", "Opiate poisoning"],
    key:4,
    fig:"Illustration, frontal view of eyes.",
    note:"" },
  { n:4, p:"127", boiler:true,
    stem:"You are called to see a 3-year-old boy with a high fever. The nurse is worried that he is very sleepy. As you walk into the resuscitation room he makes no spontaneous response. You try calling his name but he makes no response. On stimulation, his eyes open, he cries and he raises his hand and pushes your hand away. What is this child's Glasgow Coma Score (GCS)?",
    opts:["8", "9", "10", "11", "12"],
    key:1,
    note:"" },
  { n:5, p:"127", boiler:true,
    stem:"Ryan, aged 10 months, is rushed to the children's emergency department after being found submerged in the bath. His mother runs screaming into the department saying 'Help my baby, please'. Which is the next most appropriate step?",
    opts:["Commence chest compressions in a ratio of 15:2", "If the child is not breathing, commence bag and mask ventilation", "Place the child onto the examination couch and put his head into the neutral position", "Remove wet clothing/towels and dry the baby vigorously", "Stimulate the baby and shout for help"],
    key:4,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.127 -> p.128" },
  { n:6, p:"128", boiler:true,
    stem:"Mohammed, aged 8 months, has been vomiting and off his feeds for 2 days. Initially, he had episodes of crying uncontrollably, drawing his legs up into his abdomen as if in pain, and appeared fractious. His mother gave him some oral rehydration solution, but his vomiting continued and he has become lethargic. On admission to hospital he is in shock. What is the most likely diagnosis?",
    opts:["Gastroenteritis", "Intussusception", "Malrotation and volvulus", "Meckel diverticulum", "Strangulated hernia"],
    key:1,
    note:"" },
  { n:7, p:"128", boiler:true,
    stem:"Mohammed, aged 8 months, presented with the clinical scenario described above. He weighs 8 kg. He needs a bolus of normal saline 0.9% to treat his shock. What volume of fluid would you give initially?",
    opts:["40 ml", "160 ml", "320 ml", "680 ml", "800 ml"],
    key:1,
    note:"" },
  { n:8, p:"128", boiler:true,
    stem:"Mohammed, aged 8 months, has presented with the clinical scenario described in the previous 2 questions. He has received the fluid bolus of normal saline 0.9%, which has improved his condition. From his presentation you suspect he is 10% dehydrated. You receive his laboratory results, which reveal a plasma sodium of 138 mmol/L (within the normal range). His continuing fluid loss from vomiting is small and can be ignored. What is Mohammed’s total fluid requirement for the initial 24 hours? He weighs 8 kg.",
    opts:["160 ml", "320 ml", "800 ml", "880 ml", "1600 ml"],
    key:4,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.128 -> p.129" },
  { n:9, p:"129", boiler:true,
    stem:"You are called to the resuscitation room where there is a 6-year-old child who has arrived by ambulance. The child has been having a generalized seizure for 15 minutes. The ambulance crew gave a dose of buccal midazolam 5 minutes ago. The emergency doctor has maintained the airway and has applied oxygen. His capillary refill time is less than 2 seconds and his heart rate 120 beats/min. What is the next most appropriate management step?",
    opts:["Administer further anticonvulsant", "Check blood glucose level", "Gain intravenous access", "Request senior review", "Start bag and valve mask ventilation"],
    key:1,
    note:"" },
  { n:10, p:"129", boiler:true,
    stem:"Seb, a 2-year-old boy, was at his cousin's birthday party. His mother noticed that he has suddenly developed a widespread urticarial rash and has also become flushed in the face. His vital signs are normal and he has no respiratory compromise. Which medication would you give?",
    opts:["Intramuscular adrenaline", "Intramuscular antihistamine", "Intravenous hydrocortisone", "Oral antihistamine", "Oral corticosteroid"],
    key:3,
    note:"" },
  { n:11, p:"129", boiler:false,
    stem:"Jenny, a 3-year-old girl, was at a village fete. She suddenly developed swollen cheeks and lips and a widespread urticarial rash. She is rushed to the nearby general practice surgery, where it is noted that her breathing is very noisy. She is distressed and frightened. On auscultation she has widespread wheeze. Which medication would you give first?",
    opts:["Intramuscular adrenaline", "Intramuscular antihistamine", "Intravenous hydrocortisone", "Oral antihistamine", "Oral corticosteroid"],
    key:0,
    straddle:true,
    note:"STRADDLES THE PAGE BREAK p.129 -> p.130 Printed option letters after A are E, C, D, B." },
  { n:12, p:"130", boiler:false,
    stem:"There has been a dramatic decline in the incidence of sudden infant death syndrome in the UK. Which of the following is the single most important factor responsible for this decline?",
    opts:["Feet to foot of cot", "Keeping baby in parent's room until 6 months of age", "Keeping room cool to prevent overheating", "Parents not smoking in the same room as infant", "Supine sleeping"],
    key:4,
    note:"" },
  { n:13, p:"130", boiler:false,
    stem:"Nathaniel, a 4-year-old boy, is brought to hospital with shortness of breath. He is able to talk but has oxygen saturation of 90%. His capillary refill time is less than 2 seconds. Which of the following is the most appropriate next step in the management of that patient?",
    opts:["Check blood glucose", "Check pupils", "Airway opening manoeuvres", "High-flow oxygen therapy", "Commence cardiac compressions using the hands encircling method"],
    key:3,
    note:"" },
  { n:14, p:"130", boiler:false,
    stem:"Kelsey, a 2-year-old girl, is found unconscious in the garden. When she is bought into the resuscitation room she is gasping and moaning. Which of the following is the most appropriate next step in the management of that patient?",
    opts:["Check blood glucose", "Check pupils", "Airway opening manoeuvres", "High-flow oxygen therapy", "Commence cardiac compressions using the hands encircling method"],
    key:2,
    note:"" },
  { n:15, p:"131", boiler:false,
    stem:"Ahmed, aged 2 months, is found by his mother to be pale and floppy in his cot. The paramedics are giving bag and valve mask ventilation when he arrives in the resuscitation room and his chest is moving well. His heart rate is 40 beats/min. Which of the following is the most appropriate next step in the management of that patient?",
    opts:["Check blood glucose", "Check pupils", "Airway opening manoeuvres", "High-flow oxygen therapy", "Commence cardiac compressions using the hands encircling method"],
    key:4,
    note:"" },
  { n:16, p:"131", boiler:false,
    stem:"Daniel, age 10 years, has diabetes mellitus and has been playing football at his friend's house. He has been brought to the emergency department as he has become. Which of the following is the most appropriate next step in the management of that patient?",
    opts:["Check blood glucose", "Check pupils", "Airway opening manoeuvres", "High-flow oxygen therapy", "Commence cardiac compressions using the hands encircling method"],
    key:0,
    note:"Printed stem ends \"has become.\"" },
  { n:17, p:"131", boiler:false,
    stem:"Aisha, a 3-year-old girl, is bought to hospital by the paramedics as she has had a seizure. She is receiving high-flow oxygen, her breathing is regular, and the cardiac monitor shows a heart rate of 100 beats/min. She is unresponsive to painful stimuli, as she does not flinch when her blood glucose is checked. Which of the following is the most appropriate next step in the management of that patient?",
    opts:["Check blood glucose", "Check pupils", "Airway opening manoeuvres", "High-flow oxygen therapy", "Commence cardiac compressions using the hands encircling method"],
    key:1,
    note:"" },
  { n:18, p:"132", boiler:false,
    stem:"A 9-year-old boy is 'blue-lighted' into the emergency department by ambulance with an acute history of reduced consciousness. His mother described him complaining of headache and fever earlier in the day. On examination, he is pyrexial with a GCS of 14/15 and is cardiovascularly stable. A few petechiae are noted on his legs. What is the single most effective immediate management for this child?",
    opts:["Arrange an urgent CT brain scan", "Give a 20 mL/kg normal saline fluid bolus", "Give a 3 mL/kg 10% dextrose fluid bolus", "Gain intravenous access, take blood cultures and administer broad-spectrum antibiotics", "Administer vitamin K"],
    key:3,
    note:"" },
  { n:19, p:"132", boiler:false,
    stem:"A 3-year-old girl is 'blue-lighted' into the local emergency department with reduced consciousness. Her mother informs the paramedic that her daughter has been unwell for the last 8 days with vomiting and profuse diarrhoea. On arrival, she is apyrexial, has a heart rate of 170 beats per minute and respiratory rate of 20 per minute. Her systolic blood pressure is 75 mmHg and she has a capillary refill time of 5 seconds. She is barely responsive to pain. Resuscitation begins and a blood gas reveals a pH 6.9, base excess 18 mmol/L and blood sugar of 2.2 mmol/L. What is the most likely clinical syndrome?",
    opts:["Anaphylactic shock", "Septicaemic shock", "Cardiogenic shock", "Hypovolaemic shock", "Neurogenic shock"],
    key:3,
    note:"" },
  { n:20, p:"132", boiler:false,
    stem:"A known epileptic is brought into the local emergency department in status epilepticus. The paramedic crew have given rectal diazepam 10 minutes ago but the patient continues to have generalized tonic-clonic seizures. He now has intravenous access and his blood sugar is 5.5 mmol/L. What is the most appropriate next drug treatment to be given?",
    opts:["Intravenous lorazepam", "Intravenous phenytoin", "Intravenous thiopental", "Rectal paraldehyde", "Buccal midazolam"],
    key:0,
    note:"" },
  { n:21, p:"133", boiler:false,
    stem:"A previously well 5-year-old boy is brought in by ambulance to the emergency department with an acute onset of breathing difficulty. On arrival, he appears unwell, pale with audible stridor and is sitting upright unable to speak. His temperature is 40C. What is the first priority in this child's management?",
    opts:["Lie the child down", "Take a throat swab", "Obtain intravenous access", "Give oral dexamethasone", "Summon immediate anaesthetic help"],
    key:4,
    note:"" },
  { n:22, p:"133", boiler:false,
    stem:"A 9-year-old boy in asystole is brought in by ambulance to the emergency department. The various members of the cardiac arrest team arrive and resuscitation begins. Which is the most important drug of choice?",
    opts:["Adrenaline (epinephrine)", "Sodium bicarbonate", "Atropine", "Amiodarone", "Lidocaine"],
    key:0,
    note:"" },
  { n:23, p:"133", boiler:false,
    stem:"A 3-year-old girl is brought into the emergency department by ambulance with a 4-hour history of listlessness, high fever and reduced responsiveness. Her temperature is 40.0C, she has a heart rate of 170 beats per minute, a respiratory rate of 35 per minute and saturations of 100% in 15 litres of high-flow oxygen. On examination, she is responsive to voice and maintaining her airway. Systemic examination is unremarkable; her capillary refill time is 4 seconds. What is the first priority in the management of this child?",
    opts:["Intubation and ventilation", "10 mL/kg bolus of normal saline", "20 mL/kg bolus of normal saline", "15 mL/kg packed red cells", "3 mL/kg bolus of dextrose"],
    key:2,
    note:"" },
  { n:24, p:"134", boiler:false,
    stem:"An 8-year-old girl is brought to hospital following ingestion of a cereal bar containing peanuts. She is noted to have a widespread urticarial rash and swelling of the face and lips. She is finding it difficult to speak and there is widespread wheeze on auscultation. The single most important step in her management is which of the following?",
    opts:["Intramuscular 1 microgram/kg adrenaline (epinephrine) (1:1000)", "Intravenous adrenaline (epinephrine), 1 microgram/kg (1:10 000)", "Intravenous hydrocortisone", "Oxygen", "Chlorphenamine"],
    key:0,
    note:"DOSE READ OFF p.134 AND CONFIRMED AS PRINTED: option A reads \"Intramuscular 1 microgram/kg adrenaline (epinephrine) (1:1000)\", option B \"1 microgram/kg (1:10 000)\" with a space inside 10 000. The printed IM figure is a tenth of the standard 10 microgram/kg (0.01 mL/kg of 1:1000); RECORD the printed dose and the divergence in the explanation, do NOT move the key or edit the option - the route the key selects is right and the answer stands." },
  { n:25, p:"134", boiler:false,
    stem:"A 12-year-old girl with known epilepsy is brought in by ambulance. She has been fitting for 15 minutes. Her parents administered buccal midazolam after 5 minutes as part of her rescue regimen. On arrival, tonic-clonic movements are ongoing. The ambulance crew have inserted a cannula and are giving high flow oxygen via facemask. What is the next step in management?",
    opts:["Intravenous lorazepam", "Rectal diazepam", "Rapid sequence induction", "Loading dose of phenytoin", "Intravenous phenobarbital"],
    key:0,
    note:"" },
  { n:26, p:"134", boiler:false,
    stem:"A 3-month-old baby is found dead in a Moses basket sleeping on her back. She was born in July at 41 weeks to a mother who smoked during the pregnancy and afterwards. Which of the following factors is the most likely to have influenced her sudden infant death?",
    opts:["Maternal smoking", "Sleeping in a ‘Moses basket’", "Supine sleeping position", "Born in summer months", "Post-term delivery"],
    key:0,
    note:"" },
];
