  {
    id:'opqb-t20-791', bank:'gradegain', module:'ophtho', chapter:'op-conj',
    stem:'Vitamin A deficiency can cause any of the following EXCEPT',
    options:['Ophthalmoplegia.','Keratomalacia.','Bitot spots.','Night blindness'],
    answer:0,
    explanation:'Vitamin A deficiency is an ocular-surface and retinal disease, not a motility disease. Retinol is the precursor of rhodopsin, the rod visual pigment, and the book makes the link explicit: the rods are "necessary for seeing in dim light. SO, diseases affecting the rods result in night blindness" (ophthalmology.pdf p.11), and night blindness is listed among the visual complaints a patient may present with (ophthalmology.pdf p.4) — so D is a genuine feature. Bitot spots are the keratinised, foamy triangular patches of conjunctival xerosis; the conjunctiva lecture prints the entity by name, as "Bitôt Spot" with a circumflex and no possessive (L6) Conjunctiva, sl.62) — so C is a genuine feature. Keratomalacia is the colliquative corneal melting of advanced xerophthalmia, and it too is a genuine feature of the deficiency; note that keratomalacia is named in none of the 29 cached ophthalmology lecture decks, in none of the 12 cached book chapters, and not in book chapter 20 either — the only grep hit in the whole cache is inside L6\'s own not-covered list, which is a record of the absence rather than teaching, so this option is answered from general medical knowledge and is not taken from the course material. Ophthalmoplegia is the exception and therefore the key: external ophthalmoplegia with nystagmus and ataxia is the ocular signature of THIAMINE (vitamin B1) deficiency in Wernicke encephalopathy, not of vitamin A — also not taken from the course material, since no cached ophthalmology source assigns ophthalmoplegia to a vitamin. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Recognise the ocular triad of vitamin A deficiency — night blindness, conjunctival xerosis with Bitot spots and keratomalacia — and separate it from the ophthalmoplegia of thiamine deficiency.',
    source:'ophthalmology qb.pdf p.127, Q791 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.11, p.4; L6) Conjunctiva sl.62.'
  },
  {
    id:'opqb-t20-792', bank:'gradegain', module:'ophtho', chapter:'op-insid',
    stem:'Retinal toxicity is a feature of chronic therapy with',
    options:['Tetracyclines.','Corticosteroids','Acetazolamide.','Chloroquine.'],
    answer:3,
    explanation:'Chloroquine phosphate and hydroxychloroquine sulfate, used for malaria and then for rheumatoid arthritis, systemic lupus erythematosus and other autoimmune disorders, produce two ocular effects: asymptomatic corneal deposits, and — far more serious — a retinopathy that is "insidious, slowly progressive, and usually irreversible", whose "typical bull\'s-eye macular lesions do not become visible ophthalmoscopically until serious retinal damage has already occurred" (ophthalmology.pdf p.269). That irreversibility is why the book requires a baseline dilated examination with visual fields, colour vision and fundus photography before therapy begins (p.269). Acetazolamide is a carbonic anhydrase inhibitor and its chronic toxicity is systemic, not retinal — paraesthesia of the extremities, anorexia and gastrointestinal upset, headache, altered taste and smell, metabolic acidosis, hypokalaemia, renal calculi and rare bone marrow suppression (p.267). Corticosteroids damage the eye by other routes: posterior subcapsular cataract and raised intraocular pressure, with central serous retinopathy as a possible aggravation rather than a toxic maculopathy (p.270). Tetracyclines have no retinal toxicity; their neuro-ophthalmic association is raised intracranial pressure with papilloedema, which is not taken from the course material. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Attribute bull\'s-eye maculopathy to chronic chloroquine or hydroxychloroquine, and contrast it with the non-retinal toxicities of acetazolamide and the steroid complications.',
    source:'ophthalmology qb.pdf p.127, Q792 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.269, p.267, p.270.'
  },
  {
    id:'opqb-t20-793', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'Prolonged use of topical steroids:',
    options:['Retinoapthy','Glaucoma','Cataract','All of the Above'],
    answer:3,
    explanation:'The bank prints option A as "Retinoapthy"; read it as retinopathy. All three are documented steroid effects, so the key is D. The book\'s topical-steroid warning names two of them directly: topical ocular corticosteroids "should never be prescribed by a primary care provider" and their serious complications include "promotion of viral, bacterial, and fungal infections" and "possible development of glaucoma and cataract" (ophthalmology.pdf p.261). The systemic-medication chapter names the cataract precisely — "Corticosteroids can produce posterior subcapsular cataracts" — and adds "The use of systemic or inhaled corticosteroids is associated with elevated IOP (steroid-induced glaucoma) in susceptible individuals" (p.270). The retinal limb is the third bullet on the same page: "Oral and inhaled steroids may also precipitate or aggravate acute or chronic central serous retinopathy, a condition resulting in pooling of fluid under the macula with the resultant decrease in central vision" (p.270). Note the mismatch the reader should hold: the stem says TOPICAL steroids while the book attributes the raised pressure and the central serous retinopathy to systemic and inhaled preparations — the bank is treating the drug class as one. B and C alone are each true but incomplete, which is what makes D the printed key. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'List the three ocular hazards of prolonged corticosteroid use — cataract, raised intraocular pressure and central serous retinopathy — alongside the promotion of infection.',
    source:'ophthalmology qb.pdf p.127, Q793 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.261, p.270.'
  },
  {
    id:'opqb-t20-794', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'A mydriatic drug in a patient with shallow anterior chamber is dangerous because it can:',
    options:['Cause open angle glaucoma','Precipitate an attack of angle closure glaucoma','Cause glaucoma inversus','Cause all of the above'],
    answer:1,
    explanation:'A dilated pupil bunches the peripheral iris into the angle; in an eye whose anterior chamber is already shallow that is enough to close it. The book states the mechanism twice. Under the cautions for pupillary dilation: "In eyes with subluxated lens, dilatation can precipitate an attack of angle closure glaucoma", and patients "should be warned about the symptoms of angle closure, pain, headache, nausea and vomiting, halos around light and decreased vision" (ophthalmology.pdf p.260). Under decongestants: "In rare instances, acute angle-closure glaucoma may be precipitated in susceptible eyes by the use of sympathomimetic drugs because they can dilate the pupil" (p.261). The same paragraph disposes of option A: "these drugs may be used without harm by patients with chronic open-angle glaucoma because they do not produce a rise in intraocular pressure (IOP) if the filtration angle is open" (p.261) — an open angle is not closed by dilation, so mydriatics do not cause open-angle glaucoma. Option C, "glaucoma inversus", is not a recognised entity in any cached ophthalmology source and appears to be a fault in the printed option; it is not taken from the course material because it does not exist. D fails with A and C. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Explain why mydriasis endangers a shallow anterior chamber but is safe in an eye with an open filtration angle.',
    source:'ophthalmology qb.pdf p.127, Q794 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.260, p.261.'
  },
  {
    id:'opqb-t20-795', bank:'gradegain', module:'ophtho', chapter:'op-neuro-optic',
    stem:'Toxic amblyopia may be due to',
    options:['Vitamin A deficiency.','Vitamin B deficiency.','Vitamin C deficiency.','Vitamin D deficiency.'],
    answer:1,
    explanation:'Toxic (nutritional) amblyopia is a bilateral optic neuropathy of the papillomacular bundle, and the B vitamins are the deficiency that produces it. The book lists it under chronic retrobulbar neuritis, whose causes include "Drugs eg. ethambutol, chloramphenicol, etc." alongside B12 deficiency (ophthalmology.pdf p.190), and names the field defect it produces as "Centrocaecal scotoma (Tobacco-alcohol amblyopia)" (p.187) — the classical tobacco-alcohol picture being a combined thiamine and B12 depletion. Vitamin A deficiency damages the ocular surface and the rods, giving night blindness, conjunctival xerosis and keratomalacia, not an optic neuropathy — so A is wrong for the reason Q791 sets out. Vitamin C deficiency is scurvy, whose ocular expression is haemorrhagic (subconjunctival and orbital bleeding) rather than neural, and vitamin D deficiency is a bone disease with no classical optic neuropathy; neither association is taken from the course material, since no cached ophthalmology source assigns an optic neuropathy to vitamin C or D. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Attribute toxic and nutritional amblyopia to B-group vitamin deficiency and to its classical tobacco-alcohol setting.',
    source:'ophthalmology qb.pdf p.127, Q795 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.190, p.187.'
  },
  {
    id:'opqb-t20-796', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'All of the following drugs increase aqueous drainage EXCEPT:',
    options:['Prostaglandins.','Beta blockers.','Cholinergic drugs.','Alpha adrenergic agonists.'],
    answer:1,
    explanation:'Every glaucoma drug either suppresses aqueous production or improves its exit, and the beta-blockers are pure suppressants. The book: "Nonselective B-adrenergic antagonists (beta-blockers) reduce the formation of aqueous humour by the ciliary body and thereby reduce IOP" (ophthalmology.pdf p.265), and the class table repeats the mechanism as "the formation of aqueous humour" decreased (p.268). The three distractors all open an outflow route. Prostaglandin analogues act "through the uveoscleral pathway, a supplemental route through which a small portion of aqueous normally drains" (p.266). Cholinergic drugs act at the other route: "Pilocarpine, a cholinergic-stimulating drug available as eyedrops, lowers IOP by increasing aqueous outflow through the trabecular meshwork" (p.265). Alpha-2 adrenergic agonists are the option that could be argued, because brimonidine works "by a presumed dual mechanism of decreased aqueous production and increased uveoscleral (non-trabecular meshwork) aqueous outflow" (p.266) — it does both, so it still belongs with the drainage drugs and is not the exception. The glaucoma lecture sorts the classes the same way, putting beta-blockers, carbonic anhydrase inhibitors and alpha agonists under decreasing production and prostaglandin analogues, miotics and alpha agonists under increasing drainage (L11) Glaucoma Diag, POAG). Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Sort the antiglaucoma classes by mechanism and identify the beta-blockers as the aqueous suppressant among outflow drugs.',
    source:'ophthalmology qb.pdf p.127, Q796 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.265, p.266, p.268; L11) Glaucoma Diag, POAG.'
  },
  {
    id:'opqb-t20-797', bank:'gradegain', module:'ophtho', chapter:'op-neuro-optic',
    stem:'Field examination in a case of tobacco poisoning shows:',
    options:['Tubular field.','Arcuate field defect.','Centero-cecal scotoma.','Baring of blind spot.'],
    answer:2,
    explanation:'The bank prints option C as "Centero-cecal scotoma"; read it as centrocaecal. The book maps the defect to the disease in one line, inside the signs-of-optic-nerve-dysfunction box: the visual field defects of optic nerve disease are "Central scotoma", "Altitudinal visual field defect (AION)", "Centrocaecal scotoma (Tobacco-alcohol amblyopia)" and "Arcuate scotoma (bundle nerve defect in glaucoma)" (ophthalmology.pdf p.187) — tobacco-alcohol amblyopia is named against the centrocaecal scotoma and against nothing else. The shape follows the anatomy: the toxin attacks the papillomacular bundle, so the scotoma runs from fixation to the blind spot and takes central acuity and colour vision with it. The same page assigns option B elsewhere: the arcuate scotoma is the nerve-fibre-bundle defect of glaucoma, and the glaucoma lecture lists it with the paracentral scotomata of Bjerrum area, the nasal step and the ring scotoma (L11) Glaucoma Diag, POAG). Option A, tubular field, is the end stage of that same glaucomatous constriction — "Constriction of visual field (to tubular field)" and "Temporal island of vision" (L11) — not a toxic sign. Option D, baring of the blind spot, is described as an early glaucomatous field change; it is named in none of the cached ophthalmology sources and is not taken from the course material. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Match the centrocaecal scotoma to toxic and nutritional optic neuropathy, and the arcuate and tubular defects to glaucoma.',
    source:'ophthalmology qb.pdf p.127, Q797 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.187; L11) Glaucoma Diag, POAG.'
  },
  {
    id:'opqb-t20-798', bank:'gradegain', module:'ophtho', chapter:'op-intro',
    stem:'A 45-year-old woman is using multiple glaucoma eye drops. She complains of tearing and irritation after applying her medications. The most important instruction to give her when instilling multiple eye drops is:',
    options:['Apply all drops quickly one after another','Allow 5 minutes between different drops','Apply two drops each time','Tilt head down after instillation'],
    answer:1,
    explanation:'The conjunctival sac holds only a fraction of one drop, so a second drop instilled immediately simply washes the first one out before it has been absorbed — the patient loses the drug and gains the irritation of a double preservative load. The book gives the interval as a rule: "Allow a minimum of 5 minutes between drops if using more than one type of medication" (ophthalmology.pdf p.255). The same list disposes of option C — "Apply only one drop" — because the sac cannot hold two and the excess spills onto the lid and cheek or drains down the nose, which is exactly the tearing and irritation this patient describes. Option A is the error the rule exists to prevent. Option D is the wrong direction: the book\'s technique has the patient look up with the lower lid pulled down so the drop lands in the lower fornix (p.255), and the manoeuvre that actually matters after instillation is closing the eyes and pressing at the nasal corner to occlude the puncta, which reduces systemic absorption in a patient on glaucoma drops (p.263). The book also orders the formulations: "When using ointments or gels, make them the last to be used" (p.255). Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'State the five-minute rule for multiple topical medications and the one-drop rule that goes with it.',
    source:'ophthalmology qb.pdf p.127, Q798 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.255, p.263.'
  },
  {
    id:'opqb-t20-799', bank:'gradegain', module:'ophtho', chapter:'op-intro',
    stem:'Which of the following is TRUE regarding eye drop technique?',
    options:['Drops must be placed directly on the cornea','Pull the upper lid upward','Apply in the lower conjunctival fornix','Touch tip of the bottle to eyelids for accuracy'],
    answer:2,
    explanation:'The book gives the technique in a single sentence that answers three of the four options at once: "Instil the correct amount of medication into the lower conjunctival fornix. Avoid applying drops directly to the cornea, which is the most sensitive part of the eye, and avoid touching the tip of the applicator to the patient\'s lids or eye" (ophthalmology.pdf p.255). The fornix is the target because it is a reservoir that lets the drug spread over the surface with the next blink, and because it is insensitive — option A is wrong precisely because the cornea is the most densely innervated tissue in the body, so a drop landing on it stings, provokes reflex blinking and reflex tearing, and is promptly washed away. Option D is wrong for a different reason: contact between the applicator tip and the lids or lashes contaminates the bottle and turns a therapeutic drop into an inoculum for the next instillation. Option B misdirects the lid manoeuvre — the lower lid is drawn DOWN to open the inferior fornix; pulling the upper lid up exposes the cornea and defeats the purpose. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Instil a drop into the lower conjunctival fornix without touching the cornea or contaminating the bottle tip.',
    source:'ophthalmology qb.pdf p.127, Q799 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.255.'
  },
  {
    id:'opqb-t20-800', bank:'gradegain', module:'ophtho', chapter:'op-cornea',
    stem:'Fluorescein staining of the cornea primarily detects:',
    options:['Endothelial defects','Epithelium defects','Retinal edema','Lens opacities'],
    answer:1,
    explanation:'Fluorescein is a water-soluble dye that cannot cross an intact lipid-rich corneal epithelium; wherever the epithelium is missing the dye enters the exposed hydrophilic stroma and pools, so it maps epithelial loss and nothing else. The book introduces it as the first of the topical ocular drugs, and its clinical uses on the surface are the detection of epithelial defects, which appear green under the cobalt blue light, and the demonstration of a leaking corneal wound, where "the dark leaking aqueous (with cobalt blue light) is seen to wash out the green-stained tear film (Seidel test)" (ophthalmology.pdf p.256). Option A is wrong because the endothelium is a single posterior cell layer that the dye never reaches through an intact epithelium and stroma; endothelial function is assessed by corneal thickness and by specular microscopy, not by a surface stain. Option C is wrong because retinal oedema is not a surface phenomenon at all — fluorescein does image the retina, but only when given INTRAVENOUSLY for angiography, which the book treats as a separate use with its own adverse effects (p.258). Option D is wrong because lens opacities are seen by retroillumination and the slit lamp; a dye that stops at the epithelium cannot report on the lens. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Use topical fluorescein as a map of corneal epithelial loss, and separate that from its intravenous use in angiography.',
    source:'ophthalmology qb.pdf p.127, Q800 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.256, p.258.'
  },
  {
    id:'opqb-t20-801', bank:'gradegain', module:'ophtho', chapter:'op-cornea',
    stem:'A complication of fluorescein staining of the cornea is:',
    options:['Stains hard contact lenses','Stains soft contact lenses','Causes corneal ulcer','Permanent staining of cornea'],
    answer:1,
    explanation:'The bank prints this as a back-reference — "In the previous Q, a complication of this stain is" — and the stain in question is the topical corneal fluorescein of Q800. The book states the complication and its scope in one sentence: "Although no systemic complications accompany the use of topical fluorescein, a single local complication is the staining of soft contact lenses because of their porous structure" (ophthalmology.pdf p.256). The mechanism is the discriminating detail. Soft lenses are hydrogels — a water-filled polymer matrix that takes up the water-soluble dye and holds it, which is why soft lenses must be removed before staining and left out until the tear film has cleared. Rigid gas-permeable and PMMA lenses are non-porous, so option A fails on exactly the property that makes B true. Option C inverts the drug: fluorescein detects an ulcer, it does not cause one — the topical agent in this chapter that genuinely ulcerates the cornea is repeated tetracaine, which "inhibit[s] mitosis and cellular migration and can lead to corneal ulceration and scarring" (p.258). Option D is wrong because corneal staining is transient: the dye sits in the exposed stroma and in the tear film and is washed out by tearing within minutes to hours, leaving nothing behind. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Name the single local complication of topical fluorescein and explain why it is confined to soft lenses.',
    source:'ophthalmology qb.pdf p.128, Q801 (Grade Gain, "Drugs and The Eye"). Back-reference to Q800, repaired in place. Supporting: ophthalmology.pdf p.256, p.258.'
  },
  {
    id:'opqb-t20-802', bank:'gradegain', module:'ophtho', chapter:'op-cornea',
    stem:'A patient with a leaking corneal wound undergoes fluorescein testing. The test used to detect aqueous leak is:',
    options:['Jones test','Seidel test','Schirmer test','Applanation tonometry'],
    answer:1,
    explanation:'The book names the test at the moment it describes the sign: under the clinical uses of fluorescein, "Leaking corneal wounds: The dark leaking aqueous (with cobalt blue light) is seen to wash out the green-stained tear film (Seidel test)", illustrated as Figure (20-1) (ophthalmology.pdf p.256). What the examiner looks for is not staining but the reverse — a dark rivulet of clear aqueous diluting the concentrated green film and running down the cornea, positive Seidel. Option A belongs to the tear DRAINAGE pathway, not the wound: the Jones I and Jones II dye tests ask whether fluorescein instilled in the sac reaches the nose, and Jones II is performed only when Jones I is negative (p.257). Option C measures tear PRODUCTION by wetting of a filter paper strip and says nothing about wound integrity. Option D is actively contraindicated in this eye — applanation tonometry presses on a cornea that is already perforated and will express more aqueous, and the pressure it records in a leaking eye is meaningless. Note the scoping: Seidel is named in book chapter 20 and in none of the 29 cached lecture decks nor the 12 cached book chapters — the only other grep hit in the cache is inside chapter 1\'s own not-covered list. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Recognise a positive Seidel test as aqueous washing out the fluorescein film, and distinguish it from the Jones and Schirmer tests.',
    source:'ophthalmology qb.pdf p.128, Q802 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.256 (Figure 20-1), p.257.'
  },
  {
    id:'opqb-t20-803', bank:'gradegain', module:'ophtho', chapter:'op-lac',
    stem:'TBUT is the time between:',
    options:['Instillation of dye → appearance of red reflex','Last blink → first dark spot','Last blink → green staining','Drop → disappearance of dye'],
    answer:1,
    explanation:'The tear film break-up time is measured after fluorescein is instilled: the patient blinks, then holds the eyes open, and the examiner watches the green film under cobalt blue light until the first dry spot appears in it as a dark break. The interval from that last blink to that first dark spot is the TBUT, and the book sets the abnormal cut-off at under ten seconds (ophthalmology.pdf p.257) — a short break-up time points to a mucin- or lipid-layer problem, i.e. evaporative dry eye, as opposed to the aqueous-deficient dry eye that a Schirmer strip detects. Option C inverts the observation: the green staining is the starting condition, present from the moment the dye spreads, and it is the LOSS of green over a dry spot that is being timed, not its appearance. Option A confuses the test with retinoscopy and the red reflex, which has nothing to do with the tear film. Option D describes tear clearance or dye disappearance from the sac, which is a drainage measurement, not a stability one, and it belongs to the Jones dye tests on the same page. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Define TBUT as last blink to first dry spot and place it as a test of tear film stability.',
    source:'ophthalmology qb.pdf p.128, Q803 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.257.'
  },
  {
    id:'opqb-t20-804', bank:'gradegain', module:'ophtho', chapter:'op-lac',
    stem:'A patient has persistent tearing. Primary Jones test is negative. What is the next step?',
    options:['Stop testing','Perform Jones II','Repeat TBUT','Perform Schirmer test'],
    answer:1,
    explanation:'Secondary test (Jones II)\nOnly performed if the primary test is negative\n+ve test: fluorescein-stained saline is recovered from the nose indicating partial obstruction of the lacrimal drainage system\n- ve test: unstained saline is recovered indicating upper lacrimal (punctal or canalicular) dysfunction or lacrimal pump failure',
    objective:'Follow a negative primary Jones test with Jones II and interpret the two possible results.',
    source:'ophthalmology qb.pdf p.128, Q804 (Grade Gain, "Drugs and The Eye") — explanation box printed by the bank, transcribed verbatim. Supporting: ophthalmology.pdf p.257.'
  },
  {
    id:'opqb-t20-805', bank:'gradegain', module:'ophtho', chapter:'op-cornea',
    stem:'A patient has been self-using tetracaine for 1 week for pain relief. The most serious risk is:',
    options:['Mydriasis','Retinal toxicity','Corneal ulceration','Choroidal rupture'],
    answer:2,
    explanation:'Topical anaesthetics are for a single diagnostic instillation, never for analgesia, and this patient has been using one for a week. The book states the harm directly: repeated topical anaesthetics "inhibit mitosis and cellular migration and can lead to corneal ulceration and scarring" (ophthalmology.pdf p.258). Two mechanisms compound each other — the drug blocks the epithelial healing that would close the original defect, and by abolishing corneal sensation it removes both the pain that would make the patient rest the eye and the reflex tearing and blinking that protect the surface. The result is an anaesthetic abuse keratopathy: a persistent epithelial defect that enlarges, becomes infected, and scars, so the pain relief costs the patient the cornea. Option A is wrong because tetracaine is an anaesthetic with no autonomic action on the iris; it neither blocks the sphincter nor stimulates the dilator. Options B and D are the wrong compartment altogether — a topical drop does not reach the retina in any meaningful concentration, and a choroidal rupture is blunt trauma, not pharmacology. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Recognise topical anaesthetic abuse as a cause of non-healing corneal ulceration and scarring.',
    source:'ophthalmology qb.pdf p.128, Q805 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.258.'
  },
  {
    id:'opqb-t20-806', bank:'gradegain', module:'ophtho', chapter:'op-ret-dr',
    stem:'Adverse effect of IV fluorescein:',
    options:['Permanent retinal damage','Yellow skin/urine','Orbital cellulitis','Optic neuritis'],
    answer:1,
    explanation:'This is the systemic use of the dye — fundus fluorescein angiography, in which fluorescein is injected intravenously to image the retinal circulation in diabetic retinopathy, vein occlusion and macular disease. Because the dye circulates through the whole body before it is cleared by the kidneys, it discolours the patient: the skin takes on a transient yellow tinge and the urine turns deep yellow or orange for about a day, and the patient must be warned beforehand or the colour is alarming. The book lists this among the adverse effects of systemic fluorescein along with nausea and vomiting, and the rare but serious anaphylactic reaction that is the reason resuscitation facilities are required for the procedure (ophthalmology.pdf p.258). Option A is wrong because the dye is a passive contrast agent, not a toxin — it is the disease being photographed that damages the retina, not the fluorescein. Option C is wrong because orbital cellulitis is a bacterial infection spreading from the sinuses, unrelated to an intravenous dye. Option D is wrong because fluorescein has no demyelinating or inflammatory action on the optic nerve. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Warn a patient before fundus fluorescein angiography of transient yellow skin and urine, and know the serious adverse effect that requires resuscitation cover.',
    source:'ophthalmology qb.pdf p.128, Q806 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.258.'
  },
  {
    id:'opqb-t20-807', bank:'gradegain', module:'ophtho', chapter:'op-pupil',
    stem:'A 23-year-old healthy man presents for routine fundus examination. The ophthalmologist wants rapid onset and short duration mydriasis. The best drug for this purpose is:',
    options:['Atropine','Cyclopentolate','Tropicamide','Homatropine'],
    answer:2,
    explanation:'All four options are cholinergic-blocking agents and all four dilate; the question is decided entirely on the onset and duration column of the book\'s mydriatic table (ophthalmology.pdf p.259). Tropicamide is the shortest-acting of the group — it dilates within about 20 to 30 minutes and wears off within about 4 to 6 hours, which is exactly what a routine diagnostic fundus examination needs: the patient sees a dilated fundus today and can drive and read again the same evening. The other three are chosen when prolonged cycloplegia is the GOAL, not a side effect, and each is progressively worse for a diagnostic dilation. Homatropine lasts a day or more; cyclopentolate lasts about a day and is chosen for cycloplegic refraction in children, where paralysing accommodation is the whole point; atropine is the extreme, taking hours to peak and lasting up to one to two weeks, which is why it is reserved for cycloplegia in young children and for immobilising the iris in anterior uveitis, and why it would leave this healthy 23-year-old blurred and photophobic for a fortnight. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Choose the mydriatic by duration, and reserve the long-acting agents for cycloplegia and uveitis.',
    source:'ophthalmology qb.pdf p.128, Q807 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.259 (mydriatic table).'
  },
  {
    id:'opqb-t20-808', bank:'gradegain', module:'ophtho', chapter:'op-pupil',
    stem:'A mydriatic is chosen for routine fundus examination because of its rapid onset and short duration. That drug acts by:',
    options:['Stimulating dilator pupillae','Blocking sphincter pupillae','Paralyzing Müller muscle','Selective beta-1 agonist'],
    answer:1,
    explanation:'The bank prints this as a back-reference — "In the previous Q, the previous drug acts by" — and the drug in question is the short-acting mydriatic chosen for routine fundus examination in the preceding item; the stem above restates that item\'s printed description without naming its answer. The mechanism defines the whole class the book calls cholinergic-blocking mydriatics (ophthalmology.pdf p.259): they are antimuscarinics, and they dilate by blocking the muscarinic receptors of the sphincter pupillae, the circular parasympathetically-innervated muscle that constricts the pupil. Remove the sphincter\'s tone and the unopposed dilator pulls the pupil open; the same blockade at the ciliary muscle is what produces the cycloplegia that accompanies these drugs. Option A describes the OTHER mechanism of dilation, the adrenergic one — phenylephrine is the alpha-1 agonist that stimulates the radial dilator pupillae, and the book keeps it in a separate group precisely because it dilates without affecting accommodation. Option C is a different muscle in a different lid: Müller muscle is the sympathetically-innervated retractor of the upper lid, and paralysing it causes the partial ptosis of Horner syndrome, not mydriasis. Option D is wrong on both receptor and organ — beta-1 receptors are cardiac, and no beta-1 agonist has any pupillary action. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Separate the two routes to mydriasis: antimuscarinic block of the sphincter versus alpha-1 stimulation of the dilator.',
    source:'ophthalmology qb.pdf p.128, Q808 (Grade Gain, "Drugs and The Eye"). Back-reference to Q807, repaired in place from Q807\'s printed stem only — Q807\'s key is not named. Supporting: ophthalmology.pdf p.259, p.260.'
  },
  {
    id:'opqb-t20-809', bank:'gradegain', module:'ophtho', chapter:'op-refract',
    stem:'A 7-year-old child is brought for cycloplegic refraction. Best cycloplegic for him is:',
    options:['Tropicamide','Cyclopentolate','Atropine','Phenylephrine'],
    answer:1,
    explanation:'In infants, the combination of cyclopentolate hydrochloride 0.2% and phenylephrine hydrochloride 1.0% is the safest and most effective',
    objective:'Choose cyclopentolate for cycloplegic refraction in a child, and know the infant combination and its concentrations.',
    source:'ophthalmology qb.pdf p.128, Q809 (Grade Gain, "Drugs and The Eye") — explanation box printed by the bank, transcribed verbatim. Supporting: ophthalmology.pdf p.259.'
  },
  {
    id:'opqb-t20-810', bank:'gradegain', module:'ophtho', chapter:'op-refract',
    stem:'A cycloplegic is given to a 7-year-old child for cycloplegic refraction. The major risk of that drug\'s toxicity includes:',
    options:['Hypothermia','Bradycardia','Hallucinations and flushing','Severe miosis'],
    answer:2,
    explanation:'The bank prints this as a back-reference — "In the previous Q, the major risk of previous drug toxicity includes" — and the drug is the cycloplegic chosen for the child in the preceding item; the stem above restates that item\'s printed setting without naming its answer. Cycloplegics are antimuscarinics, and a drop that runs down the nasolacrimal duct is absorbed across nasal mucosa straight into the circulation, bypassing first-pass metabolism — a child\'s small body weight makes the systemic dose disproportionately large, which is why the book flags systemic toxicity for this class and why punctal occlusion after instillation matters (ophthalmology.pdf p.259, p.263). The picture is the classic anticholinergic syndrome, and every distractor here is its exact opposite. Central blockade gives restlessness, ataxia, disorientation and frank hallucinations; peripheral blockade of the sweat glands gives dry, hot, flushed skin. Option A inverts the thermal effect: blocked sweating causes HYPERthermia, not hypothermia. Option B inverts the cardiac effect: vagal blockade at the sinoatrial node causes tachycardia, not bradycardia. Option D inverts the pupil: the whole purpose of the drug is to block the sphincter, so the pupil is widely dilated and unreactive — severe miosis is what a cholinergic overdose such as pilocarpine or an organophosphate would produce. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Recognise systemic anticholinergic toxicity from topical cycloplegics in children: hallucinations, flushing, dry hot skin, tachycardia.',
    source:'ophthalmology qb.pdf p.128, Q810 (Grade Gain, "Drugs and The Eye"). Back-reference to Q809, repaired in place from Q809\'s printed stem only — Q809\'s key is not named. Supporting: ophthalmology.pdf p.259, p.263.'
  },
  {
    id:'opqb-t20-811', bank:'gradegain', module:'ophtho', chapter:'op-pupil',
    stem:'Phenylephrine 2.5% differs from tropicamide because:',
    options:['Causes cycloplegia','Does NOT affect accommodation','Causes permanent dilation','Never stings'],
    answer:1,
    explanation:'The two drugs dilate by opposite routes, and that is the whole of the difference. Tropicamide is an antimuscarinic: it blocks the sphincter pupillae AND the ciliary muscle, so mydriasis comes packaged with cycloplegia and the patient cannot accommodate until it wears off. Phenylephrine is an alpha-1 adrenergic agonist: it stimulates the radial dilator pupillae and does nothing to the ciliary muscle, so it dilates the pupil while leaving accommodation intact (ophthalmology.pdf p.260). That is why the book keeps the adrenergic mydriatics in a group of their own, and why phenylephrine is the agent of choice when the pupil must be opened but near vision preserved. Option A states the property phenylephrine specifically lacks — cycloplegia is tropicamide\'s, not phenylephrine\'s. Option C is wrong on both drugs: neither dilation is permanent, and phenylephrine 2.5% in fact wears off within a few hours. Option D is wrong on the facts — phenylephrine stings on instillation, which is one reason it is often preceded by a topical anaesthetic. Note also the systemic caution attached to this drug: the 10% strength can raise blood pressure and is avoided in cardiovascular disease, so 2.5% is the routine diagnostic concentration. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Contrast adrenergic and antimuscarinic mydriasis on accommodation, and name the concentration used diagnostically.',
    source:'ophthalmology qb.pdf p.128, Q811 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.260.'
  },
  {
    id:'opqb-t20-812', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'Decongestants may precipitate:',
    options:['Open-angle glaucoma','Keratoconus','Acute angle-closure glaucoma','Optic neuritis'],
    answer:2,
    explanation:'Ocular decongestants — naphazoline, phenylephrine, tetrahydrozoline — are alpha-adrenergic agonists sold over the counter to whiten a red eye by constricting the conjunctival vessels. The same alpha-1 action stimulates the dilator pupillae, so the pupil widens, and a mid-dilated pupil is the geometry that closes a narrow angle: the peripheral iris bunches into the angle recess and blocks trabecular access, while iris-lens apposition at the pupil margin adds pupil block. The book lists the precipitation of acute angle closure among the hazards of these agents (ophthalmology.pdf p.261), which is why an eye with a shallow anterior chamber should not be given them casually. Option A is wrong because open-angle glaucoma is defined by an OPEN angle with resistance at the trabecular meshwork itself; dilating the pupil does not create it, and by the same argument dilating a patient with established open-angle glaucoma is not the emergency that dilating an occludable angle is. Option B is wrong because keratoconus is a progressive corneal ectasia with no adrenergic mechanism. Option D is wrong because optic neuritis is inflammatory or demyelinating, unrelated to a topical vasoconstrictor. The other consequence of these drops is rebound vasodilation on withdrawal, which is what makes them self-perpetuating (p.261). Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Link over-the-counter alpha-agonist decongestants to pupil dilation, angle closure, and rebound vasodilation.',
    source:'ophthalmology qb.pdf p.129, Q812 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.261, p.260.'
  },
  {
    id:'opqb-t20-813', bank:'gradegain', module:'ophtho', chapter:'op-conj',
    stem:'A 16-year-old girl presents with itching, tearing, mild papillae. Best OTC combination drug:',
    options:['Naphazoline + antazoline','Timolol + brimonidine','Tropicamide + phenylephrine','Erythromycin + dexamethasone'],
    answer:0,
    explanation:'Itching is the symptom that makes an allergic conjunctivitis, and papillae are its sign; the combination the book names for this over-the-counter indication pairs a decongestant with an antihistamine — naphazoline plus antazoline (ophthalmology.pdf p.261). The logic of the pairing is that each half treats a different limb of the type I reaction: antazoline is an H1 antagonist and takes the itch, while naphazoline is an alpha-agonist vasoconstrictor and takes the redness and the lid swelling that come from vasodilation and leak. It is symptomatic and short-term treatment — the same page carries the rebound vasodilation caution, so these drops are not for chronic use. Option B is a glaucoma combination, a beta-blocker with an alpha-2 agonist, and it is neither over-the-counter nor anti-allergic. Option C is the additive mydriatic pair used to dilate a pupil for examination; it treats nothing and would leave this girl photophobic. Option D would be an actual error of practice: a topical steroid is prescription-only, and giving it for a benign itchy eye risks steroid-induced glaucoma and cataract, and the disaster of steroid given over an unrecognised herpes simplex keratitis. The book\'s longer-term alternative for this presentation is a mast-cell stabiliser or the dual-acting agent in the next question. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Choose an antihistamine-decongestant combination for acute allergic conjunctivitis and know why a steroid is not the OTC answer.',
    source:'ophthalmology qb.pdf p.129, Q813 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.261.'
  },
  {
    id:'opqb-t20-814', bank:'gradegain', module:'ophtho', chapter:'op-conj',
    stem:'For the same 16-year-old girl with itching, tearing and mild papillae, if we need to use a drug that reduces eosinophil chemotaxis, which of the following is best:',
    options:['Neomycin','Ketotifen','Diclofenac','Cyclopentolate'],
    answer:1,
    explanation:'The bank prints this as a back-reference — "In the previous Q, if we need to use a Drug that reduces eosinophil chemotaxis" — and the stem above restates the previous item\'s printed findings, which name only the patient and her signs, not its answer. Ketotifen is the dual-acting anti-allergic agent the book lists for allergic conjunctivitis (ophthalmology.pdf p.261), and it is the only option with any anti-allergic action at all. It works on three fronts: it antagonises H1 receptors for immediate relief of itch, it stabilises mast cells so the granules are not released in the first place, and it inhibits eosinophil chemotaxis and activation, which is the late-phase, cell-recruitment limb of the reaction that the question is pointing at. That third property is why it suits recurrent and seasonal disease where a pure antihistamine only chases symptoms. Option A is an aminoglycoside antibiotic, and the book\'s specific warning about it is the opposite of helpful here — neomycin is a common cause of contact sensitivity and can itself produce an itchy, red allergic reaction of the lids and conjunctiva (p.262). Option C is a topical NSAID: it blocks cyclo-oxygenase and helps pain and post-operative inflammation, but prostaglandins are not the mediator of the itch and it does nothing to eosinophils. Option D is a cycloplegic with no anti-inflammatory action whatever. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Identify ketotifen as the dual-acting antihistamine and mast-cell stabiliser that also inhibits eosinophil chemotaxis.',
    source:'ophthalmology qb.pdf p.129, Q814 (Grade Gain, "Drugs and The Eye"). Back-reference to Q813, repaired in place from Q813\'s printed findings only. Supporting: ophthalmology.pdf p.261, p.262.'
  },
  {
    id:'opqb-t20-815', bank:'gradegain', module:'ophtho', chapter:'op-cornea',
    stem:'A major contraindication to steroid with antibiotic combinations:',
    options:['Viral keratitis suspected','Age > 50','Diabetic patient','Wearing contact lenses'],
    answer:0,
    explanation:'The book\'s caution against fixed steroid-antibiotic combinations is that they must not be used where herpes simplex or a fungal infection is suspected (ophthalmology.pdf p.262). The reason is that the steroid suppresses local immunity and the antibiotic in the bottle does nothing against a virus or a fungus: in dendritic herpes simplex keratitis the steroid allows the epithelial dendrite to spread into a geographic ulcer and drives the infection into the stroma, with corneal melting and permanent scarring, and in a fungal keratitis it accelerates the same destruction. This is the single most damaging prescribing error in the chapter, and it is the reason a red eye is never treated with a combination drop before the cornea has been stained and examined. Option B is wrong because age alone contraindicates nothing; the age-related concern with steroids is the cumulative risk of posterior subcapsular cataract and steroid-induced ocular hypertension, which the book lists as complications of prolonged use (p.261), not as a contraindication at 50. Option C is wrong for the same reason — diabetes is a caution about wound healing and infection risk generally, not a stated contraindication here. Option D is wrong because contact lens wear is a reason to look hard for infective keratitis, and it is that suspicion, not the lens itself, that makes the steroid dangerous. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Withhold steroid-antibiotic combinations where herpes simplex or fungal keratitis is possible, and separate that from the complications of prolonged steroid use.',
    source:'ophthalmology qb.pdf p.129, Q815 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.262, p.261.'
  },
  {
    id:'opqb-t20-816', bank:'gradegain', module:'ophtho', chapter:'op-pupil',
    stem:'Best drug for maximum mydriasis in dark irides:',
    options:['Tropicamide alone','Phenylephrine alone','Tropicamide + phenylephrine','Atropine'],
    answer:2,
    explanation:'When maximum mydriasis is required, phenylephrine in combination with tropicamide is ideal because the effects are additive.\n- This combination is often used to dilate the pupil of a brown iris as well',
    objective:'Combine an antimuscarinic with an alpha-agonist for additive mydriasis in a heavily pigmented iris.',
    source:'ophthalmology qb.pdf p.129, Q816 (Grade Gain, "Drugs and The Eye") — explanation box printed by the bank, transcribed verbatim. Supporting: ophthalmology.pdf p.260.'
  },
  {
    id:'opqb-t20-817', bank:'gradegain', module:'ophtho', chapter:'op-conj',
    stem:'Rebound redness occurs with:',
    options:['Cyclopentolate','Tetrahydrozoline','Atropine','Ketotifen'],
    answer:1,
    explanation:'Tetrahydrozoline is one of the ocular decongestants the book groups with naphazoline and phenylephrine, and rebound vasodilation on withdrawal is the characteristic hazard of the whole group (ophthalmology.pdf p.261). The sequence is self-perpetuating: the alpha-agonist constricts the conjunctival vessels and the eye looks white, the vessels adapt to being held constricted, and when the drop wears off they dilate more than they did at baseline, so the eye is redder than before. The patient reads that as needing another drop, uses the bottle more often, and ends with a chronically injected eye — conjunctivitis medicamentosa — that only settles when the drops are stopped. This is why the book treats decongestants as short-term symptomatic agents. Option A is a cycloplegic; its adverse effects are blurring, photophobia and systemic anticholinergic toxicity, not rebound injection. Option C is the longest-acting cycloplegic and behaves the same way — no vasoconstrictor action, so nothing to rebound from. Option D is the dual-acting anti-allergic agent: ketotifen blocks histamine and stabilises mast cells rather than clamping the vessels, which is exactly why it is preferred for repeated use in allergic eye disease where a decongestant would set up this cycle. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Attribute rebound redness to the ocular decongestant class and explain why anti-allergic agents do not cause it.',
    source:'ophthalmology qb.pdf p.129, Q817 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.261.'
  },
  {
    id:'opqb-t20-818', bank:'gradegain', module:'ophtho', chapter:'op-insid',
    stem:'A 72-year-old diabetic with sudden central visual loss is diagnosed with wet age-related macular degeneration. First-line treatment:',
    options:['Timolol','Ranibizumab','Cyclopentolate','Atropine'],
    answer:1,
    explanation:'Wet, or neovascular, age-related macular degeneration is driven by choroidal new vessels growing under the macula in response to vascular endothelial growth factor; they leak and bleed, which is why central vision goes suddenly. The treatment is therefore aimed at the growth factor itself, and the book names the anti-VEGF agents as the treatment of wet AMD, ranibizumab among them (ophthalmology.pdf p.263). Blocking VEGF stops the new vessels growing, dries the subretinal and intraretinal fluid, and in a proportion of eyes recovers acuity rather than merely holding it — an outcome no previous treatment achieved. The other three options are drugs from earlier sections of this same chapter, and none of them acts on the retina at all. Timolol is a topical beta-blocker for glaucoma; it lowers intraocular pressure by reducing aqueous production and does nothing for a macular lesion. Cyclopentolate and atropine are cholinergic-blocking cycloplegics used for refraction in children and for immobilising the iris in uveitis; they would dilate this patient\'s pupil, which is needed to EXAMINE the macula, but they treat nothing. Note the distractor pattern the bank uses here — three plausible ophthalmic drugs, all in the wrong compartment. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Name an anti-VEGF agent as first-line treatment of wet AMD and explain the mechanism it targets.',
    source:'ophthalmology qb.pdf p.129, Q818 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.263.'
  },
  {
    id:'opqb-t20-819', bank:'gradegain', module:'ophtho', chapter:'op-insid',
    stem:'For the same 72-year-old diabetic diagnosed with wet age-related macular degeneration, the route of administration of the selected first-line drug is:',
    options:['Topical drops','Oral tablets','Intravitreal injection','Subcutaneous injection'],
    answer:2,
    explanation:'The bank prints this as a back-reference — "In the previous Q, route of administration of the selected drug" — and the stem above restates the previous item\'s printed findings, which name the patient and her diagnosis, not its answer. The anti-VEGF agents are given by intravitreal injection (ophthalmology.pdf p.263), and the route is dictated by the molecule and the target. These are large antibody-derived proteins; they cannot cross an intact cornea, so option A fails on molecular size before anything else, and the posterior segment is in any case beyond the reach of a topical drop. Given systemically, whether by mouth or subcutaneously, the drug would have to cross the blood-retinal barrier to reach the choroidal new vessels while circulating everywhere else in the body — that is both ineffective at the macula and the source of the systemic vascular adverse effects that the same page warns about, so options B and D trade efficacy for harm. Injecting directly into the vitreous cavity puts a high concentration next to the retina with a small systemic dose, and it is repeated at intervals because the drug is cleared and the neovascular drive returns. The trade-off is procedural risk — endophthalmitis, retinal tear, raised pressure — which is why the injection is done under sterile conditions in theatre. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Justify the intravitreal route for anti-VEGF therapy from the size of the molecule and the location of the target.',
    source:'ophthalmology qb.pdf p.129, Q819 (Grade Gain, "Drugs and The Eye"). Back-reference to Q818, repaired in place from Q818\'s printed findings only — Q818\'s key is not named. Supporting: ophthalmology.pdf p.263.'
  },
  {
    id:'opqb-t20-820', bank:'gradegain', module:'ophtho', chapter:'op-insid',
    stem:'For the same 72-year-old diabetic being treated for wet age-related macular degeneration, possible adverse effects of the selected drug include:',
    options:['Arrhythmia','Myocardial infarction','Retinal tear','Glaucoma'],
    answer:1,
    explanation:'The bank prints this as a back-reference — "In the previous Q, possible adverse effects of the selected drug include" — and the stem above restates the previous item\'s printed findings only. The key is the SYSTEMIC hazard of the drug, not the hazard of the procedure: although the dose is small and delivered into the eye, enough anti-VEGF agent reaches the circulation to matter, and the book lists systemic thromboembolic events including myocardial infarction among the adverse effects (ophthalmology.pdf p.263). The mechanism is coherent — VEGF maintains vascular endothelial integrity and nitric-oxide-mediated vasodilation, so blocking it systemically promotes thrombosis, which is why the risk is highest in exactly this patient, elderly and diabetic. Option C is the trap, and it is worth naming as a trap: a retinal tear is a real complication, but of the INJECTION, not of the drug, and the question asks for the drug\'s adverse effects. Option A is the systemic effect of a different drug in this chapter — topical beta-blockers reaching the circulation cause bradycardia and conduction disturbance, not the anti-VEGF agents. Option D is wrong as a drug effect: a transient intraocular pressure spike follows the volume injected and settles within minutes to hours, and the drug in this chapter that genuinely causes glaucoma is the corticosteroid. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Separate the systemic thromboembolic risk of anti-VEGF therapy from the procedural risks of the injection.',
    source:'ophthalmology qb.pdf p.129, Q820 (Grade Gain, "Drugs and The Eye"). Back-reference to Q818, repaired in place from Q818\'s printed findings only — neither Q818\'s key nor Q819\'s key is named. Supporting: ophthalmology.pdf p.263.'
  },
  {
    id:'opqb-t20-821', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'An 80-year-old male taking timolol drops complains of shortness of breath and bradycardia. Which action reduces systemic absorption the MOST?',
    options:['Closing eyes firmly','Pressing on medial canthus','Using dark glasses','Using ointments'],
    answer:1,
    explanation:'This patient is showing the systemic effects of a topical beta-blocker — bronchospasm and bradycardia — and the route by which they arise is drainage. A drop that leaves the conjunctival sac passes through the puncta into the canaliculi and the lacrimal sac, down the nasolacrimal duct, and is absorbed across the highly vascular nasal mucosa directly into the systemic circulation, bypassing the liver and the first-pass metabolism an oral dose would undergo. Occluding the puncta interrupts that path at its start. The book gives the manoeuvre and its duration: press over the medial canthus for 30 to 60 seconds after instillation (ophthalmology.pdf p.263). Option A is the weaker version of the same idea and it is why the question says MOST — gentle lid closure without punctal pressure does slow the lacrimal pump a little, but firm squeezing actively pumps tears down the duct and can make matters worse. Option C addresses photophobia and has no bearing on absorption. Option D changes the vehicle rather than the route; an ointment prolongs contact but is impractical for a glaucoma regimen and does not close the puncta. The definitive answer in a patient with airways disease is to change the drug — see the following question. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Teach punctal occlusion for 30 to 60 seconds as the manoeuvre that cuts systemic absorption of topical drugs.',
    source:'ophthalmology qb.pdf p.129, Q821 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.263, p.265.'
  },
  {
    id:'opqb-t20-822', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'A 65-year-old patient on timolol presents with worsening cough and wheezing. You recommend a safer drug which is:',
    options:['Pilocarpine','Betaxolol','Brimonidine','Tropicamide'],
    answer:1,
    explanation:'Timolol is a NON-selective beta-blocker, so it blocks beta-2 receptors in the bronchial smooth muscle as well as beta-1 in the heart; in a patient with reactive airways that produces the cough and wheeze described, and the book lists pulmonary and cardiac side effects for this class (ophthalmology.pdf p.265). The answer the question is looking for keeps the drug class and removes the offending receptor: betaxolol is cardio-selective, acting chiefly at beta-1, so it lowers intraocular pressure by reducing aqueous production with much less bronchospasm. Note what the key does NOT claim — cardio-selectivity is relative, not absolute, so betaxolol is safer rather than safe in asthma, and it is also somewhat less effective at lowering pressure than timolol. Option C is a genuinely reasonable clinical alternative, and it is worth saying why it is not the key here: brimonidine is an alpha-2 agonist with no airway action at all, but it is a change of class, whereas the question asks for the safer version of the drug the patient is already on. Its own systemic profile is drowsiness, dry mouth and hypotension, and it is avoided in infants. Option A lowers pressure by pulling on the trabecular meshwork but causes miosis, brow ache and dim vision, and is not the answer to a respiratory problem. Option D is a mydriatic; it does not lower pressure and in an occludable angle would raise it. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Substitute a cardio-selective beta-blocker when a non-selective topical beta-blocker causes bronchospasm, and know the limits of that selectivity.',
    source:'ophthalmology qb.pdf p.129, Q822 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.265, p.266.'
  },
  {
    id:'opqb-t20-823', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'Pilocarpine increases aqueous outflow through:',
    options:['Uveoscleral','Trabecular meshwork','Schlemm canal ONLY'],
    answer:1,
    explanation:'The bank prints only three options here — A, B and C, with no D — and that is the source\'s own layout, not a transcription loss. The book answers the question in one line: pilocarpine "lowers IOP by increasing aqueous outflow through the trabecular meshwork" (ophthalmology.pdf p.265). The mechanism is mechanical rather than chemical. Pilocarpine is a direct-acting cholinergic agonist; it contracts the ciliary muscle, whose longitudinal fibres insert into the scleral spur, and that traction pulls the scleral spur posteriorly and stretches the trabecular meshwork open, widening the intertrabecular spaces so conventional outflow improves. The same ciliary contraction produces the drug\'s well-known burdens — accommodative spasm with induced myopia and brow ache, and miosis with dim vision, which is why it is poorly tolerated for long-term use. Option A names the OTHER outflow route, the unconventional or uveoscleral pathway, and that is the pathway of the prostaglandin analogues, not of pilocarpine. Option C fails on the word ONLY: Schlemm canal is the collecting channel that lies immediately outside the meshwork, so aqueous does reach it, but the resistance that pilocarpine relieves is in the meshwork itself and naming the canal alone misplaces the site of action. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Explain how ciliary muscle contraction opens the trabecular meshwork, and separate conventional from uveoscleral outflow.',
    source:'ophthalmology qb.pdf p.130, Q823 (Grade Gain, "Drugs and The Eye") — printed with three options only, no D. Supporting: ophthalmology.pdf p.265.'
  },
  {
    id:'opqb-t20-824', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'A 34-year-old glaucoma patient using a newly prescribed topical medication presents with dry mouth, fatigue, headache, and noticeable drowsiness. The drug is known to cross the blood-brain barrier and lowers intraocular pressure by both reducing aqueous humor production and increasing uveoscleral outflow. What is the most likely mechanism of action of this medication?',
    options:['Alpha-1 agonist','Alpha-2 agonist','Beta blocker','Adrenergic antagonist'],
    answer:1,
    explanation:'Alpha-2 adrenergic agonists\n- Brimonidine tartrate is a relatively selective a2 agonist that lowers IOP by a presumed dual mechanism of decreased aqueous production and increased uveoscleral (non-trabecular meshwork) aqueous outflow.\n- Its systemic side effects are few but may include:\n1. Oral dryness\n2. Headache\n3. Fatigue\n4. Local allergic reaction.\n5. Drowsiness (as it is lipid soluble and crosses the blood-brain barrier)\nIn infants brimonidine carries the risk of producing severe hypotension and apnoea',
    objective:'Identify brimonidine from its dual pressure-lowering mechanism and its systemic profile, and know the infant contraindication.',
    source:'ophthalmology qb.pdf p.130, Q824 (Grade Gain, "Drugs and The Eye") — explanation box printed by the bank, transcribed verbatim. Supporting: ophthalmology.pdf p.266.'
  },
  {
    id:'opqb-t20-825', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'A 50-year-old woman on latanoprost reports brown darkening of her hazel eyes and long eyelashes. Mechanism of IOP reduction:',
    options:['↓ aqueous formation','↑ uveoscleral outflow','↓ episcleral venous pressure','↑ trabecular flow'],
    answer:1,
    explanation:'Latanoprost is a prostaglandin analogue, and the whole class lowers intraocular pressure by increasing outflow along the unconventional, or uveoscleral, pathway — aqueous passing through the ciliary muscle bundles and into the supraciliary and suprachoroidal spaces (ophthalmology.pdf p.266). The drug remodels the extracellular matrix between those muscle bundles, widening the spaces between them and lowering the resistance of a route that carries only a minority of outflow in the untreated eye. Two consequences follow that make this class first-line in open-angle glaucoma: the effect is large, and because it is once-daily and topical with almost no systemic action, it avoids the respiratory and cardiac problems of the beta-blockers. The cosmetic changes this patient describes are the class signature and are on the same page — increased iris pigmentation, which darkens a hazel or mixed-colour iris permanently and is the reason unilateral treatment produces visible heterochromia, and hypertrichosis, the lengthening, thickening and darkening of the lashes. Option A is the mechanism of the beta-blockers and the carbonic anhydrase inhibitors, which suppress aqueous production at the ciliary epithelium. Option C is not a mechanism any of the topical antiglaucoma classes use. Option D is the trabecular route, which is pilocarpine\'s, not the prostaglandins\'. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Attribute the pressure-lowering action of prostaglandin analogues to the uveoscleral pathway and recognise their cosmetic effects.',
    source:'ophthalmology qb.pdf p.130, Q825 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.266.'
  },
  {
    id:'opqb-t20-826', bank:'gradegain', module:'ophtho', chapter:'op-glauc',
    stem:'For the same 50-year-old woman on latanoprost, the side effect unique to that drug is:',
    options:['Miosis','Iris hyperpigmentation','Retinal artery occlusion','Diplopia'],
    answer:1,
    explanation:'The bank prints this as a back-reference — "In the previous Q, Side effect unique to previous drug is" — and latanoprost is named in the previous item\'s own STEM, so the stem above restates it without giving away that item\'s answer. Increased iris pigmentation is listed with the prostaglandin analogues and belongs to no other antiglaucoma class (ophthalmology.pdf p.266), which is what the word "unique" is testing. The change is a real increase in melanin content within the stromal melanocytes rather than a proliferation of them, it takes months, it is most obvious in mixed-colour hazel and green-brown irides where the darkening spreads outward from the pupil, and it is regarded as permanent — unlike the lash lengthening on the same page, which reverses when the drug is stopped. The practical consequence is that a patient treated in one eye only will develop visible heterochromia, and must be warned before the first bottle. Option A belongs to pilocarpine, whose ciliary and sphincter contraction gives miosis with dim vision and brow ache. Option C is not an effect of any drug in this chapter — retinal artery occlusion is embolic or thrombotic disease. Option D is not a topical drug effect; diplopia in this context would point to a motility or neurological cause. Note also the ocular surface effects that are shared rather than unique: conjunctival hyperaemia and periocular skin darkening occur with the whole class. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Name permanent iris hyperpigmentation as the effect specific to prostaglandin analogues and warn a patient started on unilateral treatment.',
    source:'ophthalmology qb.pdf p.130, Q826 (Grade Gain, "Drugs and The Eye"). Back-reference to Q825, repaired in place using only the drug name printed in Q825\'s stem — Q825\'s key is not named. Supporting: ophthalmology.pdf p.266.'
  },
  {
    id:'opqb-t20-827', bank:'gradegain', module:'ophtho', chapter:'op-neuro-optic',
    stem:'A 55-year-old man receiving long-term treatment for pulmonary tuberculosis presents with progressive, painless, bilateral decrease in central vision over several weeks. Fundus examination may appear normal initially, but visual field testing shows central or cecocentral defects, and color vision is reduced. What is the most likely ocular finding in this patient?',
    options:['Retinal detachment','Optic neuropathy','Iris atrophy','Keratitis'],
    answer:1,
    explanation:'The antituberculous drug at fault is ethambutol, which the book lists among the systemic medications with ocular effects (ophthalmology.pdf p.270), and the stem is a textbook description of its toxic optic neuropathy. Every element of the picture points to the optic nerve rather than the eye: the loss is bilateral and symmetrical because a drug reaches both nerves equally, painless and gradual because there is no inflammation, and it takes central acuity, colour vision and the centrocaecal field together because the toxin attacks the small-calibre papillomacular bundle fibres first. The normal early fundus is the diagnostic trap the question is built on — the damage is retrobulbar at first, so the disc looks healthy for weeks before it pales, and the diagnosis rests on acuity, colour testing and fields, not on ophthalmoscopy. The toxicity is dose- and duration-related and is reversible if the drug is stopped early, which is why patients on ethambutol need baseline and periodic acuity and colour vision checks. Option A is wrong because a retinal detachment is neither bilateral nor painless-and-symmetrical in this way, and the fundus would be abnormal. Option C is wrong because iris atrophy follows herpetic uveitis and trauma, not a systemic drug. Option D is wrong because keratitis is painful, red and unilateral or asymmetric, with a surface lesion on staining. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Recognise ethambutol toxic optic neuropathy from bilateral painless central loss with reduced colour vision and a normal early disc.',
    source:'ophthalmology qb.pdf p.130, Q827 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.270, p.187.'
  },
  {
    id:'opqb-t20-828', bank:'gradegain', module:'ophtho', chapter:'op-cornea',
    stem:'Drug that causes vortex keratopathy:',
    options:['Amiodarone','Hydroxychloroquine','Atropine','Mannitol'],
    answer:0,
    explanation:'Amiodarone\n- Amiodarone is a cardiac arrhythmia drug that has been associated with:\n1. Corneal deposits:\no Amiodarone also produces whorl-shaped, pigmented deposits in the corneal epithelium (cornea verticillate or vortex keratopathy).\no These deposits are dosage-related and reversible if the dosage is decreased, or the drug is discontinued entirely.\no These epithelial deposits rarely cause visual symptoms\n2. Optic neuropathy (non-arteritic AION)\no Patients present with mildly decreased vision,\no visual field defects, and bilateral optic disc swelling.\n2. Intracranial hypertension',
    objective:'Attribute vortex keratopathy to amiodarone and know that the deposits are dose-related, reversible and usually asymptomatic.',
    source:'ophthalmology qb.pdf p.130, Q828 (Grade Gain, "Drugs and The Eye") — explanation box printed by the bank, transcribed verbatim. The box numbers two items "2." and prints no "3."; it also prints "cornea verticillate" for cornea verticillata. Both reproduced as printed. Supporting: ophthalmology.pdf p.269.'
  },
  {
    id:'opqb-t20-829', bank:'gradegain', module:'ophtho', chapter:'op-insid',
    stem:"Drug causing bull's-eye retinopathy:",
    options:['Digoxin','Hydroxychloroquine','Glycerin','Neomycin'],
    answer:1,
    explanation:'Hydroxychloroquine sulfate and chloroquine phosphate, given long term for rheumatoid arthritis, systemic lupus erythematosus and related disorders, concentrate in melanin-containing tissue and damage the retinal pigment epithelium in a ring that spares the fovea itself — the bull\'s-eye macular lesion. The book\'s warning is about timing rather than appearance: the retinopathy is insidious, slowly progressive and usually irreversible, and the typical bull\'s-eye lesion does not become ophthalmoscopically visible until serious retinal damage has already occurred (ophthalmology.pdf p.269). That is why a baseline dilated examination with visual fields, colour vision and fundus photography is required before therapy starts, and why screening looks for paracentral field loss and colour defects rather than waiting for the fundus sign. Option A is the classic drug of a different visual toxicity — digitalis and digoxin cause disturbances of colour vision, characteristically a yellow tinge with haloes, and this is listed among the systemic medication effects (p.270); it does not scar the macula. Option C is a hyperosmotic agent given by mouth for an acute pressure rise; it acts osmotically over hours and has no retinal toxicity. Option D is a topical aminoglycoside whose relevant adverse effect is contact sensitivity of the lids and conjunctiva (p.262). Note the pairing with the preceding question: the same two antimalarials cause corneal deposits as well, but the sight-threatening lesion is this one. Written for this bank — ophthalmology qb.pdf prints no explanation here.',
    objective:'Attribute bull\'s-eye maculopathy to the antimalarials and justify baseline and periodic screening before the fundus sign appears.',
    source:'ophthalmology qb.pdf p.130, Q829 (Grade Gain, "Drugs and The Eye"). Supporting: ophthalmology.pdf p.269, p.270, p.262, p.267.'
  },
  {
    id:'opqb-t20-830', bank:'gradegain', module:'ophtho', chapter:'op-vissym',
    stem:'Sildenafil causes:',
    options:['Permanent blindness','Blue vision','Red vision','Central scotoma'],
    answer:1,
    explanation:'At the time of peak plasma levels of Sildenafil,, patients may experience transient, mild impairment of color discrimination, often noted as a blue color tinge of vision.',
    objective:'Recognise the transient blue tinge of vision at peak sildenafil levels as a dose-related, reversible effect.',
    source:'ophthalmology qb.pdf p.130, Q830 (Grade Gain, "Drugs and The Eye") — explanation box printed by the bank, transcribed verbatim, including the doubled comma after "Sildenafil". Supporting: ophthalmology.pdf p.270.'
  }
