// house-c15.draft.js — House bank chapter 15 "Squint", 17 entries.
// Printed count 17 (Q1–17, book pp.98–101; "16. Pediatric ophthalmology" banner
// confirmed at p.102). 0 printed explanation boxes, 0 figures — markers required
// = 17 − 0 = 17, and all 17 entries below carry it.
// FLAGGED FOLDS, verdict for the hub: ch.15 Q2 ↔ ch.14 Q5 (opmcq-c14-5) and
// ch.15 Q3 ↔ ch.14 Q7 (opmcq-c14-7) are within-bank cross-chapter reprints with
// the SAME findings and SAME keys — but NOT verbatim: both stems are reworded and
// ch.15 drops ch.14's fifth option ("None of the above"), printing four options.
// The A=D duplicated option survives in both printings. Both are drafted below;
// the hub decides and executes any fold.
// Back-reference repaired: opmcq-c15-6 (→ Q5) — the repaired stem restates
// FINDINGS only and was re-read against its own options and key by hand; it names
// neither "heterophoria" (Q5's key) nor "intermittent" (its own key).
// Defects: Q2/Q3 print identical options A and D; Q16 is an "except?" stem keyed
// "All of the above" (recorded in the entry, answer stays as printed); Q5's
// answer line prints "Answer C" with no colon; typos "strabisums"/"strabisumus"
// (Q4), "misalgnment" (Q7-B), "heterotrpia" (Q14-A) preserved in the staging
// record and repaired in stems/options here with the printed form recorded.
// Chapters: op-squint 13 (Q4–Q16) · op-neuro-motil 4 (Q1, Q2, Q3, Q17).

{ id:'opmcq-c15-1', bank:'house', module:'ophtho', chapter:'op-neuro-motil',
  stem:'A **30-year-old man** presents with **vertical diplopia that worsens when reading or walking downstairs**. He keeps his **head tilted to the left** to reduce the double vision. Examination shows **underaction of the right superior oblique muscle on downgaze**. What is the most likely diagnosis?',
  options:['Right oculomotor palsy','Left trochlear palsy','Right trochlear palsy','Right abducens palsy'],
  answer:2,
  explanation:'**The stem hands over the muscle — a weak RIGHT superior oblique is a RIGHT trochlear (IV) palsy — and every accompanying sign confirms the side.** The superior oblique is the depressor of the adducted eye, so its palsy costs the patient downgaze: **vertical diplopia worst on reading and descending stairs** (`ophthalmology.pdf p.183`; the squint chapter’s own line is "hypertropia and head tilt", `ophthalmology.pdf p.200`). The compensatory posture points the same way: the head tilts to the side **OPPOSITE** the palsy — tilting left lets the intact left-sided muscles level the eyes when the right intorter is out of action — so a **left head tilt marks a right superior oblique palsy** (`ophthalmology.pdf p.183`; the abnormal-head-posture rule "direction of action of paralysed muscle" is `L30) Squint II` slides 7–9). The full left-sided mirror of this case, worked finding by finding, is `opmcq-c14-7`; the head-posture logic is also tested from the Grade Gain side at `opqb-t15-680`.\n\n| Option | Why not |\n|---|---|\n| **Right oculomotor palsy** | Would add **ptosis**, an eye resting **down and out**, and possibly mydriasis (`ophthalmology.pdf p.200`) — none printed; and the superior oblique (the muscle named as weak) is a IV-nerve muscle, not a III-nerve one. |\n| **Left trochlear palsy** | Wrong side twice over: the underacting superior oblique is the **right** one, and a left palsy would tilt the head **right** (as in `opmcq-c14-7`). |\n| **Right abducens palsy** | A horizontal problem — esotropia, failed abduction, horizontal diplopia and a face **turn**, not a tilt (`ophthalmology.pdf p.200`; `opmcq-c14-5`). Nothing vertical about it. |\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Vertical diplopia worse on downgaze + head tilt AWAY from the affected side + underaction of the superior oblique = ipsilateral trochlear (IV) nerve palsy — here the right.',
  source:'ophthalmology MCQ.pdf p.98 (Ch.15 Q1)' },

{ id:'opmcq-c15-4', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'All of the following are causes of **strabismus** except?',
  options:['Paralytic strabismus','Hypertelorism','Intermittent exotropia','Refractive esotropia','None of the above'],
  answer:1,
  explanation:'**Hypertelorism causes PSEUDOstrabismus — the eyes only LOOK crossed; alignment is normal.** The book opens the chapter with exactly this trap: "Pseudostrabismus is common in young children" and its two named causes are **epicanthal folds** and **hypertelorism (increased distance between the eyes)**, with normal ocular alignment on testing (`ophthalmology.pdf p.197`); the deck teaches the same under "apparent squint" (`L29) Sqint I` slides 15–16). Every other listed condition sits on the book’s own roster of real strabismus: **paralytic strabismus** of the 3rd, 4th or 6th nerves (`ophthalmology.pdf p.200`), **intermittent exotropia**, typically at distance in bright light (`ophthalmology.pdf p.200`), and **refractive (accommodative) esotropia** in high hypermetropes aged 2–4 (`ophthalmology.pdf p.199`) — so "None of the above" fails because a genuine exception (B) exists. The corneal light reflex is what separates the fake from the real — centred in pseudostrabismus, displaced in a tropia — tested from the Grade Gain side at `opqb-t15-678`.\n\n*(The bank prints "strabisums" in the stem and "Paralytic strabisumus" as option A — repaired.)*\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Hypertelorism (like epicanthal folds) produces pseudostrabismus with normal alignment — it is not a cause of true strabismus; paralytic squint, intermittent exotropia and refractive esotropia are.',
  source:'ophthalmology MCQ.pdf p.98 (Ch.15 Q4; the bank prints "strabisums" in the stem and "Paralytic strabisumus" as option A — repaired here, printed forms recorded)' },

{ id:'opmcq-c15-5', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'A **30-year-old female** patient presents with a complaint of **visual confusion that happens at some times but not present all the time**. Examination revealed that **both eyes are aligned perfectly when both eyes are exposed**. However, when the **left eye is covered and re-exposed, it took a few seconds to return to its resting position**. Which of the following is the best term that describes the patient’s condition?',
  options:['Esotropia','Exotropia','Heterophoria','Heterotropia','None of the above'],
  answer:2,
  explanation:'**A deviation that exists only while binocular vision is interrupted — the covered eye drifting, then realigning once fusion is restored — is a LATENT squint: heterophoria.** The book’s definition is almost the stem verbatim: heterophoria "becomes manifest only if binocular vision is interrupted, i.e. when 1 eye is covered, that eye will drift to its position of rest. Once the cover is removed, the eye will realign" — the few seconds this patient’s left eye takes to re-straighten IS that realignment — and **a minor degree of heterophoria is normal for most individuals** (`ophthalmology.pdf p.198`). Her intermittent **visual confusion** fits the moments the phoria breaks down: confusion (with diplopia) is a named sequela of misalignment after the amblyopia window closes, roughly 8–10 years (`ophthalmology.pdf p.197`). The deck files the condition as "Latent Squint (Heterophoria)" — caused by errors of refraction or muscular imbalance; symptoms run from none through **muscular asthenopia** to **intermittent diplopia** (`L29) Sqint I` slide 17); treatment, when needed, runs glasses → orthoptic exercises → prisms → surgery (`L29) Sqint I` slide 19). The unmasking manoeuvre used here is the **cover–uncover test**, worked at `opqb-t15-653` and keyed again at `opmcq-c15-11`.\n\n| Option | Why not |\n|---|---|\n| **Esotropia / Exotropia** | Both are **manifest** deviations (inward and outward respectively, `ophthalmology.pdf p.197`) — but this patient is perfectly aligned with both eyes exposed. |\n| **Heterotropia** | "Another term for strabismus" — a **manifest** squint present with **both eyes open and uncovered** (`ophthalmology.pdf p.199`). The cover *revealed* a latent drift; nothing is manifest. |\n| **None of the above** | Heterophoria names it exactly. |\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Perfect alignment with both eyes open + drift of a covered eye + realignment seconds after re-exposure = heterophoria (latent squint); the tropias are manifest deviations.',
  source:'ophthalmology MCQ.pdf p.99 (Ch.15 Q5; the bank prints the answer line as "Answer C" with no colon)' },

{ id:'opmcq-c15-6', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'A patient complains of **visual confusion that happens at some times but not present all the time**. Examination reveals **perfect alignment when both eyes are exposed**, but an eye that is **covered and then re-exposed takes a few seconds to return to its resting position**. From the given data, which of the following is the most accurate classification for that patient’s condition?',
  options:['Comitant strabismus','Incomitant strabismus','Intermittent strabismus','Constant strabismus','None of the above'],
  answer:2,
  explanation:'**A deviation that comes and goes with fusion is INTERMITTENT — the book files heterophoria inside the intermittent strabismus spectrum by name.** The findings are Q5’s latent squint, and the book’s heterophoria paragraph states the classification directly: it "is included in the intermittent strabismus spectrum," manifest only when binocular vision is interrupted, with a minor degree normal for most individuals (`ophthalmology.pdf p.198`) — the same fact keyed again at `opmcq-c15-11` and `opmcq-c15-14`.\n\n| Option | Why not |\n|---|---|\n| **Comitant strabismus** | Comitant vs incomitant is the OTHER axis — whether the angle is equal in all directions of gaze (`ophthalmology.pdf p.198`, `opmcq-c15-7`). The stem gives no gaze-direction data at all; and with both eyes exposed there is no deviation to grade. |\n| **Incomitant strabismus** | Same objection — and incomitance means paralytic or restrictive disease (`ophthalmology.pdf p.198`), while this patient’s motility is normal. |\n| **Constant strabismus** | The opposite of what was found: alignment is perfect whenever both eyes are open and fusing. |\n| **None of the above** | The intermittent spectrum names it exactly (`ophthalmology.pdf p.198`). |\n\n**Back-reference repaired:** the bank prints the stem as "In the previous case, from the given data…" — the antecedent (Q5, `opmcq-c15-5`) is restated here as its printed **findings** only, not its diagnosis, so this entry stands alone without answering either question.\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Heterophoria is classified within the intermittent strabismus spectrum — not by the comitance axis, and never constant.',
  source:'ophthalmology MCQ.pdf p.99 (Ch.15 Q6; printed as a back-reference to Q5 — repaired by restating Q5’s findings)' },

{ id:'opmcq-c15-7', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'Which of the following is characteristic of **comitant strabismus**?',
  options:['Degree of misalignment varies with gaze','Degree of misalignment is equal in all directions of gaze','Caused by serious neurologic disorders','Caused by orbital disease or trauma'],
  answer:1,
  explanation:'**"Comitant" means the angle travels WITH the eyes — the deviation measures the same wherever the patient looks.** The book’s definition: in comitant strabismus "the angle of misalignment is equal in all directions of gaze" because **the extraocular muscles are functioning normally**; the fault is central fusion, not the motor apparatus (`ophthalmology.pdf p.198`; `L29) Sqint I` slide 20). The same definition is drilled from the Grade Gain side at `opqb-t15-664`, and its sibling fact (normal EOM function) is this chapter’s own `opmcq-c15-12`.\n\n| Option | Why not |\n|---|---|\n| **Degree varies with gaze** | That is the definition of **incomitant** strabismus (`ophthalmology.pdf p.198`) — the exact opposite. |\n| **Serious neurologic disorders** | The book says the reverse for the typical case: comitant squint in a child under 6 "is rarely associated with serious neurologic conditions" (`ophthalmology.pdf p.198`); nerve palsies produce **paralytic incomitant** squint (`ophthalmology.pdf p.200`). |\n| **Orbital disease or trauma** | Thyroid ophthalmopathy and orbital blowout fracture cause **restrictive incomitant** squint (`ophthalmology.pdf pp.198, 200`; `opmcq-c15-9`). |\n\n*(The bank prints "misalgnment" in option B — repaired; option A spells it correctly.)*\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Comitant strabismus = angle of misalignment equal in all directions of gaze; a varying angle, neurologic palsy or orbital disease/trauma all mark incomitant squint.',
  source:'ophthalmology MCQ.pdf p.99 (Ch.15 Q7; the bank prints "misalgnment" in option B while option A spells "misalignment" correctly — repaired, printed form recorded)' },

{ id:'opmcq-c15-8', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'A **2-year-old child** with **esotropia and amblyopia**. What is the most appropriate management for that child?',
  options:['Spectacles','Refractive surgery','Full cycloplegic correction with eye patching','Eye patching'],
  answer:2,
  explanation:'**This child has TWO problems and the key treats both: full cycloplegic (hypermetropic) correction for the esotropia, patching for the amblyopia.** The age stamps the likely diagnosis — **refractive (accommodative) esotropia** occurs in "high hypermetropic children usually between 2–4 years of age": the excessive accommodation needed to focus drags convergence with it (the near-reflex triad), and the deviation "is corrected by hypermetropic glasses" (`ophthalmology.pdf p.199`) — cycloplegic refraction being how a 2-year-old’s full hypermetropia is measured at all (the tutorial’s work-up lists "Refraction (cycloplegic)", `ophthalmology.pdf p.202`, a tutorial page marked "Skip in Final"). Patching is aimed at the amblyopia: occlude the good eye to force the brain to use the suppressed one, effective only inside the plastic window — amblyopia develops when squint begins **before 8–10 years**, which is also when patching can reverse it (`ophthalmology.pdf pp.197, 201`). The same glasses-plus-occlusion pairing is the keyed answer of Grade Gain’s accommodative-squint question `opqb-t15-650`, and the occlusion logic is drilled at `opqb-t15-666` and `opqb-t15-670`.\n\n| Option | Why not |\n|---|---|\n| **Spectacles** | Half the treatment — straightens the eyes but leaves the amblyopia untreated, and the vision loss becomes permanent once the window closes (`ophthalmology.pdf p.197`). |\n| **Refractive surgery** | Not on the book’s treatment list for childhood squint at all — that list is glasses, muscle surgery and patching (`ophthalmology.pdf p.201`); a 2-year-old’s refraction is still changing. |\n| **Eye patching** | The other half alone — treats the amblyopia while the uncorrected hypermetropia keeps driving the eye inward (`ophthalmology.pdf p.199`). |\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Accommodative-age esotropia with amblyopia: full cycloplegic hypermetropic correction treats the deviation AND occlusion treats the amblyopia — both, not either alone.',
  source:'ophthalmology MCQ.pdf p.99 (Ch.15 Q8)' },

{ id:'opmcq-c15-9', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'Which of the following is among the causes of **incomitant strabismus**?',
  options:['Blow-out fracture','3rd cranial nerve palsy','Thyroid eye disease','All of the above','None of the above'],
  answer:3,
  explanation:'**All three — incomitant squint has exactly two families, paralytic and restrictive, and the options cover both.** The book’s incomitant paragraph names these very examples: the angle "varies with the direction of gaze" and the cause "may be paralytic (e.g., **3rd cranial nerve palsy**) or restrictive (e.g., **thyroid ophthalmopathy**, **blowout fracture of the orbit**)" (`ophthalmology.pdf p.198`). The mechanisms: III palsy drops most of the motor supply, leaving exotropia and hypotropia (`ophthalmology.pdf p.200`, worked at `opmcq-c15-17`); thyroid eye disease stiffens and tethers the muscles; an orbital floor fracture entraps the **inferior rectus**, mechanically blocking elevation (`ophthalmology.pdf p.200`). "None of the above" inverts the truth — every listed cause qualifies. Comitant-vs-incomitant is the axis tested at `opmcq-c15-7` and `opmcq-c15-12`.\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Incomitant strabismus is paralytic (e.g. III nerve palsy) or restrictive (e.g. thyroid ophthalmopathy, orbital blowout fracture) — all three listed causes qualify.',
  source:'ophthalmology MCQ.pdf pp.99–100 (Ch.15 Q9; the stem and options A–B sit at the foot of book p.99, options C–E and the answer on p.100)' },

{ id:'opmcq-c15-10', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'What is the best management of a **diabetic patient with paralytic strabismus** due to poorly-controlled DM?',
  options:['Immediate surgery','Watchful waiting with good glycemic control for 12 months','Watchful waiting with good glycemic control for 6 months','None of the above'],
  answer:2,
  explanation:'**A diabetic (or traumatic) nerve palsy is given SIX MONTHS to recover on its own before anyone operates.** The book’s N.B. on paralytic strabismus: in cases due to trauma or diabetes, "spontaneous resolution within **6 months**" is expected — surgery is considered only if the palsy persists beyond that window (`ophthalmology.pdf p.201`). Diabetes heads the book’s cause list for paralytic squint (`ophthalmology.pdf p.201`, the list tested at `opmcq-c15-16`), and a diabetic microvascular palsy is exactly the kind that recovers as the nerve re-perfuses — so the management is control the diabetes and wait. The acute work-up side of a new palsy (rule out the sinister causes: investigate for diabetes, MRI brain) is drilled at `opqb-t15-656`.\n\n| Option | Why not |\n|---|---|\n| **Immediate surgery** | Operating on a deviation that may resolve by itself risks overcorrection once the nerve recovers; surgery waits out the 6 months (`ophthalmology.pdf p.201`). |\n| **12 months** | Twice the book’s printed window. |\n| **None of the above** | The 6-month option is the book’s own rule. |\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Diabetic (and traumatic) paralytic strabismus: watchful waiting with glycemic control for 6 months — spontaneous resolution is expected; surgery only for what persists.',
  source:'ophthalmology MCQ.pdf p.100 (Ch.15 Q10)' },

{ id:'opmcq-c15-11', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'Which of the following is true regarding **heterophoria**?',
  options:['It’s categorized under intermittent strabismus','It’s found in a minor degree in most normal individuals','It’s confirmed by cover-uncover test','All of the above','None of the above'],
  answer:3,
  explanation:'**All three statements are the book’s own heterophoria paragraph, near verbatim.** (1) It "is included in the **intermittent strabismus spectrum**" — the deviation exists only while binocular vision is interrupted (`ophthalmology.pdf p.198`; classified exactly so at `opmcq-c15-6`). (2) "A minor degree of heterophoria is **normal for most individuals**" (`ophthalmology.pdf p.198`; the same fact keys `opmcq-c15-14`). (3) The **cover–uncover test** is its confirming manoeuvre: cover one eye, the latent deviation appears behind the cover, and on uncovering the eye is seen to move rapidly back to regain fixation (`ophthalmology.pdf p.203`, a tutorial page marked "Skip in Final"; the deck teaches the same test on `L29) Sqint I` slide 18, and its phoria-vs-tropia readout is worked at `opqb-t15-653`). With three true statements, "None of the above" is triply wrong and "All of the above" is the only possible key.\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Heterophoria: intermittent-spectrum, minor degrees normal in most people, confirmed by the cover–uncover test — all three at once.',
  source:'ophthalmology MCQ.pdf p.100 (Ch.15 Q11)' },

{ id:'opmcq-c15-12', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'Which of the following is true regarding **comitant strabismus**?',
  options:['Misalignment varies with direction of gaze','Extraocular muscles are functioning normally','It may indicate a serious neurologic condition','None of the above'],
  answer:1,
  explanation:'**In comitant squint the motor apparatus is INNOCENT — the extraocular muscles are functioning normally; the fault is fusion.** That is the book’s definition: the angle of misalignment is equal in all directions of gaze precisely because the muscles all work (`ophthalmology.pdf p.198`; `L29) Sqint I` slide 20; the equal-angle half of the definition keys this chapter’s `opmcq-c15-7` — NOT a duplicate of this question: different menus, different keyed fact). Grade Gain drills the same definition at `opqb-t15-664`.\n\n| Option | Why not |\n|---|---|\n| **Misalignment varies with gaze** | The definition of **incomitant** squint (`ophthalmology.pdf p.198`). |\n| **Serious neurologic condition** | The book states the opposite emphasis: comitant strabismus in a child under 6 "is rarely associated with serious neurologic conditions"; it is **later-onset / incomitant** deviation that raises the neurologic alarm (`ophthalmology.pdf p.198`; the acute-palsy work-up is `opqb-t15-656`). |\n| **None of the above** | Statement B is true. |\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Comitant strabismus = normally functioning extraocular muscles (hence the equal angle); it rarely signals serious neurologic disease in young children.',
  source:'ophthalmology MCQ.pdf p.100 (Ch.15 Q12)' },

{ id:'opmcq-c15-13', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'Which of the following is true regarding **refractive esotropia**?',
  options:['It occurs in children with high hypermetropic refractive errors','It manifests at age of 2-4 years','It can be corrected by prescribing hypermetropic glasses','All of the above','None of the above'],
  answer:3,
  explanation:'**All three — the options ARE the book’s refractive-esotropia paragraph, split into thirds.** Refractive (accommodative) esotropia "occurs in **high hypermetropic** children usually between **2–4 years of age**": to see clearly the child must accommodate excessively, and accommodation drags convergence with it through the near-reflex triad, turning the eye in; the deviation "is **corrected by hypermetropic glasses**", which remove the accommodative drive (`ophthalmology.pdf p.199`; the deck’s accommodative-squint teaching is `L29) Sqint I` slides 27–31). Grade Gain tests the same package at `opqb-t15-675` and its management at `opqb-t15-650`; the glasses-plus-patching vignette when amblyopia joins in is this chapter’s `opmcq-c15-8`. Three true statements leave "All of the above" as the only key and sink "None of the above".\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Refractive esotropia: high hypermetropia, onset 2–4 years, corrected by hypermetropic glasses — all three together.',
  source:'ophthalmology MCQ.pdf p.100 (Ch.15 Q13)' },

{ id:'opmcq-c15-14', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'**Intermittent strabismus** is characterized by which of the following?',
  options:['It is also called heterotropia','It is manifest during binocular viewing','A minor degree is considered a normal variant','All of the above','None of the above'],
  answer:2,
  explanation:'**The keyed statement is the heterophoria fact: a minor degree of latent, intermittent deviation is NORMAL for most individuals.** Heterophoria — the type the book files inside the intermittent strabismus spectrum — carries the line "a minor degree of heterophoria is normal for most individuals" (`ophthalmology.pdf p.198`; the same fact is one leg of `opmcq-c15-11`).\n\n| Option | Why not |\n|---|---|\n| **Also called heterotropia** | Backwards — **heterotropia** is "another term for strabismus", the **manifest** deviation present with both eyes open (`ophthalmology.pdf p.199`); the latent, intermittent-spectrum condition is hetero**phoria** (`ophthalmology.pdf p.198`). One vowel, opposite meaning — the same phoria/tropia trap as `opmcq-c15-5`. |\n| **Manifest during binocular viewing** | The exact opposite of the definition: heterophoria "becomes manifest only if **binocular vision is interrupted**" — under cover, not during binocular viewing (`ophthalmology.pdf p.198`). |\n| **All of the above** | Fails because A and B are both false. |\n| **None of the above** | Fails because C is true. |\n\n*(The bank prints "heterotrpia" in option A — repaired.)*\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Within the intermittent spectrum, a minor degree of (latent) deviation is a normal variant; heterotropia means MANIFEST squint, and a phoria appears only when binocular vision is interrupted.',
  source:'ophthalmology MCQ.pdf pp.100–101 (Ch.15 Q14; stem and option A at the foot of p.100, options B–E and the answer on p.101; the bank prints "heterotrpia" in option A — repaired, printed form recorded)' },

{ id:'opmcq-c15-15', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'Which of the following is the type of strabismus caused by **long-standing poor vision**?',
  options:['Sensory strabismus','Restrictive strabismus','Paralytic strabismus','Incomitant strabismus','None of the above'],
  answer:0,
  explanation:'**An eye that cannot see loses its reason to stay aligned — that is SENSORY strabismus.** The book’s one-liner: sensory strabismus "is caused by **long-standing poor vision**" — fusion needs an image from each eye, and when one eye’s image is degraded (dense cataract, corneal scar, retinal disease) the brain stops holding that eye on target and it drifts (`ophthalmology.pdf p.200`; the deck’s sensory-adaptation teaching around `L29) Sqint I` slides 21–23 is the same physiology run in reverse). It is a **comitant** deviation — the muscles and nerves are intact.\n\n| Option | Why not |\n|---|---|\n| **Restrictive strabismus** | Mechanical — a tethered or entrapped muscle (thyroid ophthalmopathy, orbital floor fracture), not a visual cause (`ophthalmology.pdf p.200`). |\n| **Paralytic strabismus** | A 3rd/4th/6th cranial nerve palsy (`ophthalmology.pdf p.200`) — motor, not sensory. |\n| **Incomitant strabismus** | A classification term, not a cause — and the wrong one: incomitance covers the paralytic and restrictive families (`ophthalmology.pdf p.198`), while a sensory deviation, with working muscles, is comitant. |\n| **None of the above** | Sensory strabismus names it exactly. |\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Long-standing poor vision in one eye causes sensory strabismus — fusion fails for lack of an image, with muscles and nerves intact.',
  source:'ophthalmology MCQ.pdf p.101 (Ch.15 Q15)' },

{ id:'opmcq-c15-16', bank:'house', module:'ophtho', chapter:'op-squint',
  stem:'All of the following are among the causes of **paralytic strabismus** except?',
  options:['DM','Head trauma','Space occupying lesion in the brain','Congenital / idiopathic','All of the above'],
  answer:4,
  explanation:'**Every option A–D IS on the book’s cause list — the printed key "All of the above" can only be read as "there is no exception here".** The book’s causes of paralytic strabismus, in its own order: "1. **DM** 2. **Head trauma** 3. **Space occupying lesions in the brain and elevated intracranial pressure** 4. rarely, **congenital or idiopathic**" (`ophthalmology.pdf p.201`) — the options reproduce that list one-for-one. The clinical weight of the list: an acute palsy in an adult means investigate for diabetes and image the brain (`ophthalmology.pdf p.201`; drilled at `opqb-t15-656`), the diabetic case then earns its 6-month watchful wait (`opmcq-c15-10`), and raised intracranial pressure picks on the **sixth nerve** first — the cranial nerve most commonly affected by elevated ICP (`ophthalmology.pdf p.200`).\n\n**Printed defect, recorded not disputed:** an "except?" stem keyed **E "All of the above"** is self-contradictory as printed — an exception is asked for and the key answers that all four qualify. Since A–D are all genuine causes, no exception exists among them and E is the only option not naming a true cause; the `answer` stays E as the bank keys it.\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'The causes of paralytic strabismus are DM, head trauma, intracranial space-occupying lesions/raised ICP, and rarely congenital/idiopathic — all four; this printing keys "All of the above" on an "except" stem.',
  source:'ophthalmology MCQ.pdf p.101 (Ch.15 Q16; DEFECT as printed — an "except?" stem keyed "All of the above"; all four listed options are the book’s printed causes, p.201)' },

{ id:'opmcq-c15-17', bank:'house', module:'ophtho', chapter:'op-neuro-motil',
  stem:'Which of the following is true regarding **oculomotor nerve palsy**?',
  options:['It usually presents as exotropia and hypotropia with lid ptosis','Miosis can be present','Mydriasis can be present','A & B','A & C'],
  answer:4,
  explanation:'**A and C — the eye sits down and out under a droopy lid, and the pupil, if involved, goes WIDE, never small.** The third nerve drives four of the six extraocular muscles plus levator palpebrae plus the parasympathetic pupil, so its palsy is the book’s composite: "**exotropia and hypotropia** with **lid ptosis**" — the intact lateral rectus (VI) pulls the eye out, the intact superior oblique (IV) leaves it hypotropic — making option A true (`ophthalmology.pdf p.200`; `L30) Squint II` slides 11–13). The parasympathetic constrictor fibres ride the nerve’s surface, so their failure produces **mydriasis** — option C — and the book’s N.B. is the reason this matters: a **dilated pupil** with a third nerve palsy points at compression, classically an **aneurysm of the circle of Willis**, an emergency (`ophthalmology.pdf p.200`). The full palsy picture with the ptosis-masks-diplopia twist is worked at `opmcq-c14-11`.\n\n| Option | Why not |\n|---|---|\n| **Miosis can be present (B)** | Backwards — losing parasympathetic tone DILATES the pupil. A small pupil with lid droop is the **sympathetic** lesion, Horner syndrome, a different disease (partial ptosis, miosis; `ophthalmology.pdf p.200` gives III palsy mydriasis only — the Horner contrast is not taken from the course material). |\n| **A & B** | Carries the false miosis statement. |\n| **A alone / C alone** | Each true but incomplete — the key wants both. |\n\nWritten for this bank — ophthalmology MCQ.pdf prints no explanation here.',
  objective:'Oculomotor palsy: exotropia + hypotropia + ptosis, and mydriasis when the pupillary fibres are compressed (think circle-of-Willis aneurysm) — never miosis.',
  source:'ophthalmology MCQ.pdf p.101 (Ch.15 Q17; last question of the chapter — the "16. Pediatric ophthalmology" banner opens p.102)' }
