var S01_DRAFT_EXAM_EYE = [
{ id:'ophep-exam-eye-1', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Fundus examination is done by:',
  options:['Ophthalmoscopy','Biometry','Retinoscopy','Topography'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> Ophthalmoscopy (direct or indirect) allows visualization of the retina, optic disc, and macula.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Ophthalmoscopy is used to examine the fundus, including the retina, optic disc, and macula.',
  source:'Opthalmology endpoint.pdf p.66' },

{ id:'ophep-exam-eye-2', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Testing the visual field in a patient with hand motion vision is done by:',
  options:['Confrontation method','Automated perimetry','Light perception','Light projection'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> In patients with hand motion vision, visual fields are tested by light projection—determining the direction from which light is perceived. Automated perimetry requires better visual acuity.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Light projection is used for visual-field testing in patients with hand-motion vision.',
  source:'Opthalmology endpoint.pdf p.68' },

{ id:'ophep-exam-eye-3', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'The physiological blind spot is:',
  options:['Fovea centralis','Macula lutea','Optic disc','Peripheral retina'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> The physiological blind spot corresponds to the optic disc, where no photoreceptors are present. The fovea and macula are areas of maximum visual acuity, not blind spots.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'The optic disc creates the physiological blind spot because it contains no photoreceptors.',
  source:'Opthalmology endpoint.pdf p.70' },

{ id:'ophep-exam-eye-4', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'The following cranial nerve is tested by corneal sensation testing:',
  options:['Optic nerve','Trigeminal nerve','Abducent nerve','Trochlear nerve'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> Corneal sensation is mediated by the ophthalmic branch of the trigeminal nerve (cranial nerve V1). Loss indicates trigeminal dysfunction.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Corneal sensation tests the ophthalmic division of the trigeminal nerve.',
  source:'Opthalmology endpoint.pdf p.72' },

{ id:'ophep-exam-eye-5', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is located between the iris and lens?',
  options:['Posterior chamber','Anterior chamber','Vitreous cavity','Canal of Schlemm'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> The posterior chamber lies between the iris and the lens, filled with aqueous humor. The anterior chamber, by contrast, is located between the cornea and iris.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'The posterior chamber lies between the iris and the lens.',
  source:'Opthalmology endpoint.pdf p.74' },

{ id:'ophep-exam-eye-6', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which muscle is supplied by the trochlear nerve?',
  options:['Superior oblique','Superior rectus','Lateral rectus','Inferior oblique'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> The trochlear nerve (cranial nerve IV) supplies only the superior oblique muscle, which helps in depression and intorsion of the eyeball. It passes through a pulley-like structure called the trochlea.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'The trochlear nerve supplies the superior oblique muscle.',
  source:'Opthalmology endpoint.pdf p.76' },

{ id:'ophep-exam-eye-7', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'What does a visual acuity of 0.5 mean?',
  options:['6/12','6/6','6/18','6/24'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> A visual acuity of 0.5 means the patient can see at 6 meters what a normal person sees at 12 meters. It indicates mild visual impairment.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A decimal visual acuity of 0.5 corresponds to 6/12 vision.',
  source:'Opthalmology endpoint.pdf p.78' },

{ id:'ophep-exam-eye-8', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'How do you test the visual field in a patient who can only detect hand motion?',
  options:['Light perception','Light projection','Confrontation test','Snellen chart'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> If a patient can only detect hand movement, visual field testing is done by light projection. It helps assess whether the patient can identify the direction from which light enters.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Light projection assesses the visual field when vision is limited to hand movement.',
  source:'Opthalmology endpoint.pdf p.80' },

{ id:'ophep-exam-eye-9', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'When the corneal light reflex is seen in the center of the right eye and temporally in the left eye, this indicates:',
  options:['15° left esotropia','45° left esotropia','15° right exotropia','45° right exotropia'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> A temporal corneal reflex in the left eye means the eye is deviated outward (exotropia). The amount of displacement roughly corresponds to 15°.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A temporal corneal light reflex indicates exotropia of that eye.',
  source:'Opthalmology endpoint.pdf p.82' },

{ id:'ophep-exam-eye-10', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following represents the blind spot of the eye?',
  options:['Optic disc','Macula','Fovea','None of the above'],
  answer:0,
  explanation:'**The endpoint file prints this explanation:**\n\n> The optic disc is the part of optic nerve that is visible within the eye. It is the "blind spot" in the visual field.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'The optic disc is the anatomical basis of the visual-field blind spot.',
  source:'Opthalmology endpoint.pdf p.84, p.118' },

{ id:'ophep-exam-eye-11', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is the organism that most commonly contaminates fluorescein dye in case of prolonged storage?',
  options:['Staphylococcus aureus','Streptococcus pneumoniae','Pseudomonas aeruginosa','E-Coli'],
  answer:2,
  explanation:'**The endpoint file prints this explanation:**\n\n> Sodium fluorescein solution has a high susceptibility to bacterial contamination, especially by Pseudomonas aeruginosa (as it grows easily in fluorescein).\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'Prolonged storage of fluorescein solution particularly risks Pseudomonas aeruginosa contamination.',
  source:'Opthalmology endpoint.pdf p.86' },

{ id:'ophep-exam-eye-12', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'A patient complains of foreign body sensation, burning and redness of eye. Dry eye disease was suspected so tear film breakup time test was done and it was 13 seconds. Which of the following applies to that patient?',
  options:['Severe dry eye disease','Moderate dry eye disease','Mild dry eye disease','No dry eye disease'],
  answer:3,
  explanation:'**The endpoint file prints this explanation:**\n\n> Normal tear film breakup time (TBUT) is >10 seconds. Since the patient in the previous case has TBUT of 13 seconds, so he does NOT have dry eye.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'A tear film breakup time above the normal cutoff does not support dry eye disease.',
  source:'Opthalmology endpoint.pdf p.88' },

{ id:'ophep-exam-eye-13', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is ture regarding the iris in case of changed depth of anterior chamber?',
  options:['The iris becomes concave when the anterior chamber is shallow','The iris becomes convex when the anterior chamber is shallow','The iris becomes convex when the anterior chamber is deep','None of the above'],
  answer:1,
  explanation:'The anterior chamber is the space between the cornea anteriorly and the iris posteriorly. When this chamber is shallow, the iris is pushed or bowed forward, giving it a convex configuration. Therefore, the statement that the iris becomes convex when the anterior chamber is shallow is correct.\n\nA concave iris is the opposite contour, so the first option does not describe the iris in a shallow anterior chamber. The third option incorrectly links a convex iris to a deep anterior chamber; a deep chamber represents greater separation between the cornea and iris rather than the forward bowing described here. Because the second option is true, the final option is also incorrect.\n\nRecognising a shallow anterior chamber matters during examination. The lecture material describes a temporal penlight assessment in which a shadow on the nasal iris suggests a shallow chamber. Shallow chambers are associated with hypermetropia, angle-closure glaucoma, cataract, and perforated corneal ulcer. Where angle closure is suspected, pupillary dilatation should not be performed and urgent referral is indicated. By contrast, a deep anterior chamber is described with myopia, aphakia, and buphthalmos.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'A shallow anterior chamber is associated with a convex iris configuration.',
  source:'Opthalmology endpoint.pdf p.90' },

{ id:'ophep-exam-eye-14', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is true regarding the vitreous cavity?',
  options:['It\'s filled with a gel-like vascular structure called vitreous humor','It comprises about 1 /3 of the eye volume','It\'s mainly composed of water','All of the above'],
  answer:2,
  explanation:'The vitreous cavity is filled with vitreous humor, a gel-like structure that helps maintain the shape of the globe. The lecture material identifies vitreous humor as avascular and mainly composed of water, with collagen and hyaluronic acid also present. Thus, the statement that it is mainly composed of water is the correct choice.\n\nThe first option is wrong because it calls the vitreous structure vascular. Its avascular nature is a stated feature of vitreous humor. The second option is wrong because the vitreous cavity occupies a substantially larger portion of the eye than the fraction stated in that option. The final option cannot be correct because both the first and second statements are false; only the third statement is supported.\n\nThis distinction also separates the vitreous cavity from the fluid-filled chambers of the anterior segment. Aqueous humor is secreted by the ciliary body and circulates through the anterior and posterior chambers, whereas vitreous humor fills the posterior cavity and has a gel-like consistency. Age-related vitreous syneresis is described as degeneration and liquefaction of vitreous humor, which can lead to posterior vitreous detachment and may produce retinal traction, tears, or retinal detachment.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'The vitreous cavity contains an avascular gel-like humor that is mainly water.',
  source:'Opthalmology endpoint.pdf p.92' },

{ id:'ophep-exam-eye-15', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is NOT an-age related eye change?',
  options:['Dry eye','Larger, non-reactive pupil','Difficulty with night vision','Decreased visual acuity'],
  answer:1,
  explanation:'The age-related pupil change described in the lecture material is a smaller pupil with reduced responses to light and accommodation. Therefore, “Larger, non-reactive pupil” is not the age-related change listed and is the correct answer. The lack of reactivity is partly inconsistent with normal ageing, but the decisive contradiction is that the pupil becomes smaller rather than larger.\n\nDry eye is an age-related change because the conjunctiva progressively loses accessory lacrimal glands and goblet cells, reducing tear production. Difficulty with night vision is also described: delayed regeneration of visual pigment impairs dark adaptation. Decreased visual acuity is likewise an expected age-related effect of retinal vascular and neuronal loss, which also decreases contrast sensitivity and visual fields.\n\nOther age-related ocular changes in the lecture include lens yellowing and opacification, reduced trabecular outflow with gradual elevation of intraocular pressure, reduced corneal endothelial cell density, and vitreous syneresis. Involutional lid changes can produce ptosis, entropion, ectropion, and epiphora. These changes explain why ocular assessment remains important even when symptoms are subtle, as serious disease may be asymptomatic.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Normal ageing makes the pupil smaller and less reactive, not larger.',
  source:'Opthalmology endpoint.pdf p.94' },

{ id:'ophep-exam-eye-16', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is a pre--requisite for confrontation visual field testing?',
  options:['Minimum VA of 3/60 in the eye tested','Minimum VA> 3/60 in the eye tested','Minmum VA of 1/60 in the eye tested','Minimum VA >1/60 in the eye tested'],
  answer:2,
  explanation:'The stated minimum visual acuity prerequisite for confrontation visual-field testing is Minmum VA of 1/60 in the eye tested. This is therefore the correct option. Confrontation testing compares the patient’s visual field with that of the examiner and is part of the basic ocular examination when visual-field assessment is indicated.\n\nThe first and second options set a different, higher visual-acuity threshold and do not state the prerequisite given in the lecture material. The fourth option changes the requirement by making it greater than the listed minimum rather than stating the minimum itself. Although a patient with better acuity may be able to undergo confrontation testing, that wording is not the specified prerequisite. The spelling “Minmum” in the correct option is retained from the printed question.\n\nFor more profound reduction in vision, the lecture distinguishes light projection testing. That assessment determines the direction from which light is perceived and is used when visual acuity is below the level needed for confrontation testing. Automated perimetry is another visual-field method, but it is quantitative and requires better visual acuity than the low-vision approaches. Amsler grid testing instead assesses the central visual field.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Confrontation visual-field testing requires a minimum VA of 1/60 in the eye tested.',
  source:'Opthalmology endpoint.pdf p.96' },

{ id:'ophep-exam-eye-17', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is a method that is used mainly for checking the central visual field?',
  options:['Automated perimetry','Light projection','Amsler grid','Confrontation test'],
  answer:2,
  explanation:'The Amsler grid is used mainly to assess the central visual field, so it is the correct answer. It is listed among the methods of visual-field testing specifically for central-field assessment. This differs from tests designed for wider-field comparison or for patients with very poor vision.\n\nAutomated perimetry is incorrect because it is a quantitative visual-field method rather than the method identified mainly for central-field checking. It can provide detailed field assessment, but the question asks for the method chiefly directed at the central field. Light projection is incorrect because it is used in very low vision to establish the direction from which light is perceived. It does not assess the central field in the way an Amsler grid does. Confrontation testing is also incorrect because it compares the patient’s field with the examiner’s field and is used for general visual-field assessment rather than principally for the central field.\n\nVisual-field assessment is an important part of ocular examination alongside visual acuity, pupillary reactions, extraocular muscle function, and fundus examination. The choice of field test depends on the patient’s visual ability and the area of field being assessed: confrontation for general comparison, light projection in markedly reduced vision, automated perimetry for quantitative testing, and the Amsler grid for the central field.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'The Amsler grid is mainly used to assess the central visual field.',
  source:'Opthalmology endpoint.pdf p.98' }
,
{ id:'ophep-exam-eye-18', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is true regarding the indentation (Schiotz) tonometry?',
  options:['It provides the most precise measurement of IOP','It\'s inexpensive and simple to use','It measure the IOP directly','All of the above'],
  answer:1,
  explanation:'Schiotz tonometry is an indentation method. The lecture material describes it as simple and inexpensive, with no power source required, so option B is the true statement. It estimates pressure through the degree of corneal indentation; heavier weights and a conversion chart are used to confirm readings.\n\nOption A is wrong because the method is presented as a simple indentation technique, whereas the lecture identifies Goldmann applanation tonometry as the gold-standard measurement method. Option C is wrong because Schiotz tonometry measures indentation rather than pressure directly. Since A and C are incorrect, option D cannot be correct.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Schiotz tonometry is a simple, inexpensive indentation method rather than a direct or gold-standard IOP measurement.',
  source:'Opthalmology endpoint.pdf p.100' },

{ id:'ophep-exam-eye-19', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'What do you conclude, if during examination, an infant resists covering one of his eyes?',
  options:['The infant has amblyopia and the eye covered is the affected one','The infant has amblyopia and the eye covered is the good one','The infant is just irritable and needs to be calm','The i infant  has a serious ocular condition'],
  answer:1,
  explanation:'Resistance when one eye is covered indicates that the covered eye is the infant\'s better-seeing eye. Covering that eye forces use of the poorer eye, making the child resist the occlusion. Therefore, the conclusion in option B is that the infant has amblyopia and the covered eye is the good eye.\n\nOption A reverses the significance of the finding: covering an affected amblyopic eye would leave the better eye available for fixation and would not produce the same objection to occlusion. Option C dismisses a clinically useful observation without accounting for the selective resistance to covering one particular eye. Option D is too nonspecific; the finding supports the stated amblyopia interpretation rather than merely identifying an unspecified serious ocular condition.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Selective resistance to covering one eye in an infant suggests that the covered eye is the better-seeing eye.',
  source:'Opthalmology endpoint.pdf p.102' },

{ id:'ophep-exam-eye-20', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'The uveal tract includes all of the following except?',
  options:['Limbus','Iris','Ciliary body','Choroid'],
  answer:0,
  explanation:'The uveal tract is the middle vascular layer of the eye. Its listed components are the iris, ciliary body, and choroid. Therefore, limbus is the exception and option A is correct.\n\nOption B is wrong because the iris is specifically listed as a component of the uveal tract. Option C is wrong because the ciliary body is also part of that vascular layer and connects the iris anteriorly to the choroid posteriorly. Option D is wrong because the choroid is the posterior component of the uveal tract and provides blood supply and nutrients. The limbus instead belongs to the outer fibrous layer as the junction between cornea and sclera.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'The uveal tract consists of the iris, ciliary body, and choroid, while the limbus is part of the fibrous outer layer.',
  source:'Opthalmology endpoint.pdf p.104' },

{ id:'ophep-exam-eye-21', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'All of the following are characteristics of normal optic disc except?',
  options:['It has pink color','It has sharp margins','Average CID ration = 0.4-0.6','It\'s slightly oval in vertical directions'],
  answer:2,
  explanation:'Option C is the exception. The lecture describes a normal optic disc as pink with sharp margins and a central cup, giving the normal cup-to-disc figure separately. The wording in option C does not match that stated normal optic-disc description.\n\nOption A is a normal characteristic because the optic disc is described as pink. Option B is also a normal characteristic because normal disc margins are sharp; an abnormal margin would require further assessment in fundoscopy. Option D is compatible with the described disc appearance and is not the keyed exception. The assessment should distinguish the normal pink, sharp-margined disc from findings that raise concern, such as an enlarged cup-to-disc relationship or an important asymmetry between the discs.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'A normal optic disc is pink with sharp margins and an appropriate central cup-to-disc relationship.',
  source:'Opthalmology endpoint.pdf p.106' },

{ id:'ophep-exam-eye-22', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following extraocular muscles is responsible for the action (depression in adduction)?',
  options:['Superior rectus','Inferior rectus','Superior oblique','Inferior oblique'],
  answer:2,
  explanation:'The superior oblique is responsible for depression in adduction, so option C is correct. The muscle-action table and the cardinal positions of gaze both identify the superior oblique as the muscle tested when the eye is directed down and in.\n\nOption A, superior rectus, produces elevation in abduction rather than depression in adduction. Option B, inferior rectus, produces depression in abduction; it is tested down and out, not down and in. Option D, inferior oblique, produces elevation in adduction and is tested up and in. The direction of gaze is important because the lecture assigns different primary actions to the vertical muscles according to whether the eye is abducted or adducted.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'The superior oblique depresses the eye in adduction.',
  source:'Opthalmology endpoint.pdf p.108' },

{ id:'ophep-exam-eye-23', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following should be firstly done during examination of VA if the patient can\'t see the largest Snellen\'s letters?',
  options:['Ask the patient to count fingers','Test for hand motion detection','Reduce the distance between the patient and the chart','Check for light perception'],
  answer:2,
  explanation:'If the patient cannot see the largest Snellen letters, the first next step is to reduce the distance between the patient and the chart, making option C correct. The visual-acuity sequence in the lecture progresses through chart testing before moving to progressively more basic assessments of residual vision.\n\nOption A, counting fingers, is used when chart testing remains impossible after the distance has been reduced. Option B, hand-motion detection, follows counting-fingers testing when vision is poorer still. Option D, light perception, is assessed later if the patient cannot detect hand motion. These choices are not interchangeable: the sequence records the best level of vision that the patient can demonstrate, beginning with the least reduced test condition.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'When the largest Snellen letters cannot be seen, visual acuity should first be retested at a reduced chart distance.',
  source:'Opthalmology endpoint.pdf p.110' },

{ id:'ophep-exam-eye-24', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following best describes the grey line?',
  options:['A rigid fibrous structure forming skeleton of eyelid','It marks the separation of the lid into anterior and posterior leaflets','It has no surgical signifcance','All of the above'],
  answer:1,
  explanation:'**The endpoint file prints this explanation:**\n\n> N.B: Another line on the lid margin is the grey line which is an avascular line\n> marking the separation of the lid surgically into two leaflets: 1. An anterior leaflet composed of\n> the skin, subcutaneous tissue and the orbicularis muscle. 2. A posterior leaflet composed of the\n> tarsal plate and the palpebral conjunctiva.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*',
  objective:'The grey line is an avascular surgical landmark separating the eyelid into anterior and posterior leaflets.',
  source:'Opthalmology endpoint.pdf p.112' },

{ id:'ophep-exam-eye-25', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is the WHO definition of (legal blindness)?',
  options:['Uncorrected VA< 3/60 in the better seeing eye','Best-corrected VA <3/60 in the better seeing eye','Uncorrected VA= 3/60 in the better seeing eye','Best-corrected VA = 3/60 in the better seeing eye'],
  answer:3,
  explanation:'Option D gives the stated WHO definition of legal blindness: Best-corrected VA = 3/60 in the better seeing eye. The lecture places this definition under visual-acuity assessment and specifies both correction status and the better-seeing eye.\n\nOption A is wrong because it uses uncorrected visual acuity rather than best-corrected visual acuity. Option B includes best correction but does not reproduce the stated criterion. Option C has the stated equality but again uses uncorrected visual acuity, so it does not give the definition. The distinction matters because the definition is based on the best visual result achieved after correction, not on acuity before a refractive correction is considered.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'WHO legal blindness is defined using best-corrected visual acuity in the better-seeing eye.',
  source:'Opthalmology endpoint.pdf p.114' },

{ id:'ophep-exam-eye-26', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'What do you conclude when visual acuity improves with the pinhole than that recorded before?',
  options:['The patient has a refractive error that can only be treated by surgery','The patient has a refractive error that requires correction with glasses','The patient\'s visual acuity can\'t be corrected','The patient has a problem with accommodation reflex'],
  answer:1,
  explanation:'Improvement of visual acuity with a pinhole indicates refractive error, so option B is correct. The lecture explains that pinhole improvement supports refractive error and that glasses correct vision; this is why pinhole testing is useful after a reduced visual-acuity result.\n\nOption A is wrong because the lecture identifies optical correction with glasses, not surgery as the only treatment implied by a pinhole response. Option C is the opposite of the finding: improvement through the pinhole shows that the recorded acuity can improve under that optical condition. Option D is not the conclusion supplied by the pinhole test. The lecture contrasts pinhole improvement in refractive error with worsening through a pinhole in macular or retinal lesions.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Improvement in visual acuity with a pinhole supports refractive error requiring optical correction.',
  source:'Opthalmology endpoint.pdf p.116' },

{ id:'ophep-exam-eye-28', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following eye movements is termed (vergence)?',
  options:['Monocular eye movements','Binocular movements in the same direction','Binocular simultaneous movements in the opposite directions','None of the above'],
  answer:2,
  explanation:'Vergence is binocular simultaneous movement of the eyes in opposite directions, making option C correct. The lecture gives convergence and divergence as examples of vergence movements.\n\nOption A describes duction, which is movement of one eye in a single direction and is used when testing each eye separately. Option B describes version, in which both eyes move together in the same direction, such as dextroversion. Option D is wrong because option C precisely gives the lecture definition. The distinction between these movement types helps separate monocular muscle testing from coordinated binocular movements.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Vergence is binocular movement in opposite directions, as in convergence and divergence.',
  source:'Opthalmology endpoint.pdf p.120' },

{ id:'ophep-exam-eye-29', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is meant by (VA= 6/12)?',
  options:['The patient can recognize at 12 meters a symbol that a person with normal VA can recognize at 6 meters','The patient can recognize at 6 meters a symbol that a person with normal VA can recognize at 12 meters','The patient\'s visual power is reduced to half of its normal value','The patient\'s visual capacity is diminished to 2/3 of its normal value'],
  answer:1,
  explanation:'Option B correctly states the meaning of VA= 6/12: the patient recognizes at 6 meters a symbol that a person with normal visual acuity can recognize at 12 meters. The lecture presents visual acuity as a comparison with a standard eye and uses this same fraction as its example.\n\nOption A reverses the distances and therefore describes a different relationship. Option C reduces the notation to a percentage statement, but the lecture defines the fraction by the chart-distance comparison rather than by visual power. Option D likewise gives a percentage-style interpretation rather than the stated Snellen meaning. The numerator identifies the testing distance, while the denominator identifies the distance at which the standard eye can identify that optotype.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'A visual acuity of 6/12 means seeing at 6 meters what a standard eye sees at 12 meters.',
  source:'Opthalmology endpoint.pdf p.122' },

{ id:'ophep-exam-eye-30', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is meant by relative afferent pupillary defect (Marcus Gunn pupil)?',
  options:['When one pupil doesn\'t react consensually to light stimulation but reacts directly to it','When one pupil doesn\'t react directly to light stimulation but reacts consensually to it','When one pupil reacts to direct and consensual light stimulation but the other pupil doesn\'t react to it','None of the above'],
  answer:1,
  explanation:'A relative afferent pupillary defect, or Marcus Gunn pupil, is characterized by poor direct light reaction in the affected eye with a normal consensual reaction, so option B is correct. The lecture links this finding to an optic-nerve lesion and describes the swinging-flashlight test as the assessment method.\n\nOption A reverses the reactions: it describes loss of consensual response despite a direct response, not the stated RAPD pattern. Option C describes a broader absence of reaction in the other pupil and does not express the direct-versus-consensual distinction that defines the finding. Option D is incorrect because option B matches the lecture description. During the swinging-flashlight test, the affected eye dilates when the light is swung to it, supporting an afferent defect.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Marcus Gunn pupil is a relative afferent defect with poor direct but preserved consensual light response in the affected eye.',
  source:'Opthalmology endpoint.pdf p.124' },

{ id:'ophep-exam-eye-31', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following is the most posterior layer of the eyelid?',
  options:['Skin','Muscular layer','Tarsal plate','Palpebral conjunctiva'],
  answer:3,
  explanation:'The palpebral conjunctiva is the most posterior eyelid layer, so option D is correct. The eyelid-layer sequence proceeds from skin, through subcutaneous tissue and muscular layer, then the tarsal plate, to palpebral conjunctiva lining the inner surface of the lid.\n\nOption A is wrong because skin is the anterior, external layer. Option B is wrong because the muscular layer, containing orbicularis oculi, lies anterior to the tarsal plate. Option C is wrong because the tarsal plate forms the fibrous lid skeleton but lies anterior to the palpebral conjunctiva. The latter is the mucous membrane directly lining the inner lid surface and is therefore posterior in the anterior-to-posterior arrangement.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Palpebral conjunctiva is the posterior-most layer of the eyelid.',
  source:'Opthalmology endpoint.pdf p.126' },

{ id:'ophep-exam-eye-32', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'Which of the following tests can be used to test for color vision abnormalities?',
  options:['Snellen\'s chart test','Ishihara test','Stenon test','None of the above'],
  answer:1,
  explanation:'The Ishihara test is used for colour-vision testing, so option B is correct. The lecture identifies pseudoisochromatic plates as the Ishihara test and states that it is the standard test for colour vision.\n\nOption A is wrong because Snellen\'s chart measures distance visual acuity, not colour discrimination. Option C is not identified in the lecture as a colour-vision assessment. Option D is wrong because Ishihara testing is a listed test for colour vision abnormalities. The lecture also notes that testing should be performed in good natural light, with each eye tested separately and with near glasses if they are used.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Ishihara pseudoisochromatic plates are used to test colour vision.',
  source:'Opthalmology endpoint.pdf p.128' },

{ id:'ophep-exam-eye-33', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'In testing visual acuity, if the patient is unable to identify any letters on the Snellen chart you should next test for the ability to:',
  options:['Count fingers','Identify direction of hand movements','Identify position of a stationary light','Identify presence of a stationary ligh'],
  answer:0,
  explanation:'If the patient is unable to identify letters on the Snellen chart, the next test is counting fingers, making option A correct. The lecture gives counting fingers as the first alternative measure when chart letters cannot be read.\n\nOption B is a later assessment of residual visual function, used after counting-fingers testing is no longer possible. Option C concerns light projection, which the lecture places with very low visual ability rather than immediately after failure to identify chart letters. Option D is also not the next step in the stated sequence; light perception is tested after hand motion. The order of testing documents the greatest level of visual function the patient can demonstrate.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'Counting fingers is the next visual-acuity assessment when Snellen-chart letters cannot be identified.',
  source:'Opthalmology endpoint.pdf p.130' },

{ id:'ophep-exam-eye-34', bank:'endpoint', module:'ophtho', chapter:'op-intro-exam',
  stem:'A 30 year old woman notices that her left pupil is smaller than the right pupil. Her left eyelid droops intermittently. The lesion might be located in:',
  options:['Left orbit','Left neck','Left third cranial nerve','Left mediastinum'],
  answer:1,
  explanation:'The correct answer is option B, left neck. The combination of a smaller pupil on the affected side and ptosis points to sympathetic dysfunction, which the lecture associates with Horner syndrome. The lesion is therefore localized to the left-sided sympathetic pathway represented by the left neck option.\n\nOption A, left orbit, is not the keyed site for this sympathetic pattern. Option C is wrong because the lecture associates parasympathetic dysfunction and third-nerve palsy with anisocoria that is more apparent in bright light; the pupil in this vignette is smaller, not larger. Option D does not give the keyed localization. The clinically important distinction is between the smaller pupil of sympathetic dysfunction and the larger pupil expected with the parasympathetic dysfunction discussed in the lecture.\n\n*Written for this bank — Opthalmology endpoint.pdf prints no explanation here.*',
  objective:'A small pupil with ipsilateral ptosis suggests sympathetic dysfunction consistent with a left neck lesion.',
  source:'Opthalmology endpoint.pdf p.132' }
];
