/* Generated mechanically from the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json).
   Source pairs: unmarked p.798 through marked p.849.
   KEY CONVENTION: 0-based. `key` is an index into `opts` -- 0=A/a, 1=B/b, 2=C/c, 3=D/d, 4=E/e --
   taken directly from the staged marked-page key_index.
   `p` is the row's own UNMARKED page; the marked (answered) page is p+1. Numbering is by position, so the
   second printing of printed_q 20 (unmarked p.838) is n21 and printed_q 21..25 are n22..n26.
   `expl` is verbatim only for boxed rows (boxPrinted true); all other rows keep expl empty. */

var OPHEP_S11_STAGED = [

{ n:1, p:798, key:1,
  stem:"The following type of secondary glaucoma occurs as a consequence of central vein occlusion:",
  opts:["Pigmentary glaucoma","Neovascular glaucoma","Phacomorphic glaucoma","Angle recession glaucoma"],
  expl:"Central retinal vein occlusion (CRVO) can lead to retinal ischemia and release of VEGF, promoting new vessel growth on the iris and angle, causing neovascular (rubeotic) glaucoma.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.799), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s11 source, marked p.799; printed_q 1. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 1, 799",
},

{ n:2, p:800, key:3,
  stem:"The classical treatment of congenital glaucoma:",
  opts:["Long term miotics","Long term beta blockers","Laser treatment","Surgery"],
  expl:"The definitive treatment for congenital glaucoma is surgical (e.g., goniotomy or trabeculotomy). Medical therapy offers only temporary pressure reduction before surgery.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.801), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":3,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 3 (d), from the staged s11 source, marked p.801; printed_q 2. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 2, 801",
},

{ n:3, p:802, key:3,
  stem:"Sign of primary open angle glaucoma:",
  opts:["Ciliary congestion","Oval dilated","Absent red reflex","Large cup/disc ratio"],
  expl:"In primary open-angle glaucoma, the optic disc shows a large cup-to-disc ratio due to progressive loss of nerve fibers. Other findings include raised IOP and visual field defects.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.803), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":3,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 3 (d), from the staged s11 source, marked p.803; printed_q 3. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 3, 803",
},

{ n:4, p:804, key:0,
  stem:"A 55-year-old patient came to the clinic with frequent changes of the reading glasses. On examination, the visual acuity was 6/6 and the intraocular pressure was 28 mmHg in both eyes. Fundus examination showed a hemorrhage on the optic disc of the right eye and the cup to disc ratio was 0.8 in both eyes. Which of the following investigations is useful to confirm the diagnosis?",
  opts:["Automated perimetry","Fundus fluorescein angiography","Pentacam","Biometry"],
  expl:"Automated perimetry assesses visual field loss typical of glaucoma. It confirms the diagnosis suggested by elevated IOP and optic disc cupping.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.805), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s11 source, marked p.805; printed_q 4. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 4, 55, 6/6, 28, 0.8, 805",
},

{ n:5, p:806, key:0,
  stem:"The normal range for IOP as measured by applanation tonometry is:",
  opts:["10-21 mmHg","16 mmHg","12-17 mmHg","8-17 mmHg"],
  expl:"The normal intraocular pressure (IOP) measured by applanation tonometry ranges between 10 and 21 mmHg. Values outside this range may indicate glaucoma or ocular hypotony.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.807), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s11 source, marked p.807; printed_q 5. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 5, 10-21, 16, 12-17, 8-17, 10, 21, 807",
},

{ n:6, p:808, key:1,
  stem:"A 55-year-old patient presents with gradual, painless diminution of vision. Examination reveals an intraocular pressure of 31 mmHg. Fundoscopy shows optic disc cupping. What is the most appropriate management for this condition?",
  opts:["Trabeculotomy","Trabeculectomy","Goniotomy","Laser peripheral iridotomy"],
  expl:"Open-angle glaucoma with high intraocular pressure and optic disc cupping is treated surgically by trabeculectomy, which creates a new drainage pathway. It lowers IOP to prevent further optic nerve damage.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.809), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s11 source, marked p.809; printed_q 6. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 55, 31, 809",
},

{ n:7, p:810, key:0,
  stem:"The trabecular pathway is responsible for what percentage of aqueous drainage?",
  opts:["90%","50%","30%","10%"],
  expl:"About 90% of aqueous humor drains through the trabecular (conventional) pathway into Schlemm’s canal. The remaining 10% drains via the uveoscleral (unconventional) route.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.811), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s11 source, marked p.811; printed_q 7. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 7, 90%, 50%, 30%, 10%, 811",
},

{ n:8, p:812, key:0,
  stem:"Which fibers are most resistant to glaucomatous damage?",
  opts:["Papillomacular bundle","Superior arcuate fibers","Inferior arcuate fibers"],
  expl:"In glaucoma, the superior and inferior arcuate fibers are damaged first, leading to visual field loss in the corresponding areas. The papillomacular bundle, which carries fibers from the macula to the optic disc (central vision), is most resistant to glaucomatous damage and usually affected only in late stages.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.813), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s11 source, marked p.813; printed_q 8. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 8, 813",
},

{ n:9, p:814, key:0,
  stem:"A 60-year-old patient presents for routine eye examination. Visual field testing shows peripheral field defects. Intraocular pressure is elevated at 30 mmHg, and fundoscopy reveals optic disc cupping. What is the most likely diagnosis?",
  opts:["Glaucoma","Optic neuritis","Papilledema","Retinitis pigmentosa"],
  expl:"Elevated IOP, optic disc cupping, and peripheral field loss are classic features of chronic open-angle glaucoma. It is usually asymptomatic until late stages.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.815), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s11 source, marked p.815; printed_q 9. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 9, 60, 30, 815",
},

{ n:10, p:816, key:0,
  stem:"A 65-year-old patient presents with sudden onset severe eye pain, nausea, and seeing colored halos around lights. On examination, there is ciliary injection, a cloudy cornea, and a mid-dilated vertically oval non-reactive pupil. What is the most likely diagnosis?",
  opts:["Acute angle-closure glaucoma","Open-angle glaucoma","Anterior uveitis","Optic neuritis"],
  expl:"Sudden painful red eye, halos around lights, and mid-dilated pupil are hallmarks of acute angle-closure glaucoma. It is an ophthalmic emergency requiring immediate treatment.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.817), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s11 source, marked p.817; printed_q 10. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 65",
},

{ n:11, p:818, key:0,
  stem:"A 60-year-old patient with glaucoma presents for follow-up. You need to assess the extent of visual field loss and monitor progression.\nWhich investigation is most appropriate?",
  opts:["Automated perimetry","Fundus fluorescein angiography","Optical coherence tomography (OCT) only","Slit-lamp examination"],
  expl:"Automated perimetry is used to quantify visual field loss and monitor progression in glaucoma patients. It helps assess functional vision changes.",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.819), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s11 source, marked p.819; printed_q 11. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 11, 60, 819",
},

{ n:12, p:820, key:1,
  stem:"Which of the following is considered a visual field defect that is characteristic of glaucoma?",
  opts:["Floaters","Arcuate scotomata","Bitemporal hemianopia","Xanthopsia"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.821), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s11 source, marked p.821; printed_q 12. NO explanation box printed; expl empty.",
},

{ n:13, p:822, key:2,
  stem:"Which of the following is the best line of management of a diabetic patient presenting with acute angle closure glaucoma together with lower limb edema and dyspnea?",
  opts:["Alpha blockers","Topical mydriatics","Mannitol","Glycerine"],
  expl:"Medical treatment of acute angle closure glaucoma (to lower IOP, reduce pain, and clear corneal oedema in preparation for iridotomy).\nTopical medications: IOP lowering drugs (previously mentioned), miotics & Prednisolone.\nSystemic medications: Carbonic anhydrase inhibitors (for IOP lowering) & Osmotic agents: Mannitol (contraindicated in cardiac patients) and glycerine (contraindicated in diabetics).",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.823), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 2 (c), from the staged s11 source, marked p.823; printed_q 13. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 13, 823",
},

{ n:14, p:824, key:0,
  stem:"A patient with iridocyclitis was found to have WBC clumps on the back surface of the cornea. Which of the following might occur as a complication of that condition?",
  opts:["Glaucoma","Anterior synechiae","Hypotony","Corneal erosions"],
  expl:"Anterior uveitis can be complicated by 2ry glaucoma, Posterior synechiae, Complicated cataract, Calcific band keratopathy (if the iritis becomes chronic) especially in juvenile idiopathic arthritis & Macular oedema (if the iritis becomes chronic).",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.825), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s11 source, marked p.825; printed_q 14. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 14, 2, 825",
},

{ n:15, p:826, key:0,
  stem:"A 48-year-old female patient complains of diminished vision and severe pain in her left eye. Examination revealed marked ciliary injection, shallow anterior chamber, with iris bombe'. IOP was found to be 65 mm Hg. Which of the following is the most likely diagnosis?",
  opts:["Acute angle closure glaucoma","Subacute angle closure glaucoma","Chronic angle closure glaucoma","Primary open angle glaucoma"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.827), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s11 source, marked p.827; printed_q 15. NO explanation box printed; expl empty. Staging note: 48, 65, 827",
},

{ n:16, p:828, key:1,
  stem:"A 68-year-old male patient complains of seeing black spots in his visual field. History was taken and it showed that the patient also suffered migraine and nocturnal hypotension. IOP was measured and found to be 18 mmHg. Which of the following is the most likely diagnosis?",
  opts:["Primary open angle glaucoma","Normal tension glaucoma","Secondary open angle glaucoma","Primary angle closure glaucoma","Secondary angle closure glaucoma"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.829), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s11 source, marked p.829; printed_q 16. NO explanation box printed; expl empty. Staging note: 68, 18 mmHg, 829",
},

{ n:17, p:830, key:2,
  stem:"All of the following medications increase aqueous humor drainage except?",
  opts:["Topical cholinergics","Topical alpha adrenergics","Topical beta blockers","Topical prostaglandin analgoues"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.831), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 2 (c), from the staged s11 source, marked p.831; printed_q 17. NO explanation box printed; expl empty. Staging note: 17, 831",
},

{ n:18, p:832, key:1,
  stem:"Which of the following is considered a visual field defect that is characteristic of glaucoma?",
  opts:["Floaters","Arcuate scotomata","Bitemporal hemianopia","Xanthopsia"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.833), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s11 source, marked p.833; printed_q 18. NO explanation box printed; expl empty. Staging note: 18, 833",
},

{ n:19, p:834, key:0,
  stem:"What is the percentage of aqueous humor that is drained by the uveo scleral pathway?",
  opts:["10%","20%","30%","50%"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.835), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s11 source, marked p.835; printed_q 19. NO explanation box printed; expl empty. Staging note: 19, 10%, 20%, 30%, 50%, 835; option labels B and D print as \"8.\" and \"0.\" on the page (book label typo); options are 10%, 20%, 30%, 50%",
},

{ n:20, p:836, key:2,
  stem:"Which of the following is the best line of management of a diabetic patient presenting with acute angle closure glaucoma?",
  opts:["Alpha blockers","Topical mydriatics","Mannitol","Glycerine"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.837), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 2 (c), from the staged s11 source, marked p.837; printed_q 20. NO explanation box printed; expl empty. Staging note: 20, 837",
},

{ n:21, p:838, key:1,
  stem:"He complains of nausea and intermittent blurring of vision with halos. Palpation of the globe reveals it to be hard. What is the SINGLE most appropriate management?",
  opts:["Panretinal photocoagulation","Pilocarpine eye drops","Propranolol","Scleral buckling","Analgesia and rest"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.839), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s11 source, marked p.839; printed_q 20. NO explanation box printed; expl empty. Staging note: 20, 839; second question numbered 20 in the book (first is 836/837)",
},

{ n:22, p:840, key:1,
  stem:"A 44 year old man has sudden severe eye pain, red eye, visual blurring. Slit-lamp findings include shallow anterior chambers in both eyes with corneal epithelial oedema. What is the SINGLE most likely diagnosis?",
  opts:["Central retinal vein occlusion","Acute closed angle glaucoma","Uveitis","Iritis","Open angle glaucoma"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.841), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s11 source, marked p.841; printed_q 21. NO explanation box printed; expl empty. Staging note: 21, 44, 841",
},

{ n:23, p:842, key:4,
  stem:"A 27 year old female presents with sudden severe eye pain, vomiting, blurred vision, red eye, and fixed, dilated ovoid pupils. What is the SINGLE most initial investigation?",
  opts:["CT head","MRI orbits","Blood culture and sensitivity","Toxicology screen","Ocular tonometry"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.843), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":4,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 4 (e), from the staged s11 source, marked p.843; printed_q 22. NO explanation box printed; expl empty. Staging note: 22, 27, 843",
},

{ n:24, p:844, key:1,
  stem:"A 63 year old woman has progressive decrease in her visual acuity and peripheral visual field loss. She is shortsighted and needs to wear glasses. Pupils are normal. What is the SINGLE most likely diagnosis?",
  opts:["Cataract","Glaucoma","Retinal detachment","Iritis","Giant cell arteritis"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.845), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s11 source, marked p.845; printed_q 23. NO explanation box printed; expl empty. Staging note: 23, 63",
},

{ n:25, p:846, key:2,
  stem:"A 60-year-old comes to the emergency department due to a sudden onset of severe pain in her left eye with blurred vision, nausea, and vomiting. The symptoms began a few minutes ago, while she was watching a movie in a nearby theatre. Her temperature is 36.8 C (98.4 F), blood pressure is 140/90 mm Hg, pulse is 82/min, and respirations are 14/min. Examination reveals decreased visual acuity. Her left eye appears red, with a hazy cornea, shallow anterior chamber, and dilated, fixed pupil. Her left eye is stony hard to touch. What is the most likely diagnosis?",
  opts:["Primary open angle glaucoma","Conjunctivitis","Acute angle closure glaucoma","Anterior uveitis"],
  expl:"(Sudden onset of severe eye pain + nausea/vomiting + dilated pupil + usually following setting where the pupil has to be dilated e.g. movie theatres or during times of stress or due to drug intake)",
  boxPrinted:true,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.847), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s11 source, marked p.847; printed_q 24. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 24, 60, 36.8, C, 98.4, F, 140/90, mm, Hg, 82/min, 14/min, 847",
},

{ n:26, p:848, key:4,
  stem:"A 62-year-old man comes to the office due to sudden onset of pain and redness in the left eye. The patient also has photophobia, nausea, and a severe headache that has not responded to ibuprofen. There has been no trauma, and he has never had such an episode before. Medical history is unremarkable. On review of systems, the patient has had \"a mild cold\" for which he has been using an over-the-counter oral decongestant. Physical examination shows a non-reactive, mid-dilated left pupil. The eye appears red with conjunctival flushing. Which of the following is the best next step in evaluating this patient's condition?",
  opts:["CT scan of the head","Duplex studies of carotid artery","Fluorescein staining of the eye","Lumbar puncture","Tonometry"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s11 source (oph-ep-p1-s11-glaucoma.staging.json, marked p.849), 2026-09-18, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":4,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 4 (e), from the staged s11 source, marked p.849; printed_q 25. NO explanation box printed; expl empty. Staging note: 25, 62, 849",
},

];
