/* OCR-backed staging record. Generated from the staged s10 source
   (oph-ep-p1-s10-uveal-tract.staging.json).
   Source pairs: unmarked p.740 through marked p.787.
   KEY CONVENTION: 0-based. `key` is an index into `opts` -- 0=A/a, 1=B/b,
   2=C/c, 3=D/d, 4=E/e -- taken directly from the staged s10 JSON key_index.
   The JSON "page" is the MARKED page; `p` is the row's own UNMARKED page.
   `expl` is verbatim only for boxed rows (box_printed true); all other
   rows keep expl empty. `boxPrinted` mirrors the staged box_printed per row. */

var OPHEP_S10_STAGED = [

{ n:1, p:740, key:0,
  stem:"All of the following are sequelae of anterior uveitis EXCEPT:",
  opts:["Peripheral anterior synechiae","Occlusion pupillae","Complicated cataract","Corneal neovascularization"],
  expl:"Complications:\n- 2ry glaucoma\n- Posterior synechiae → (leads to irregular shape of the iris .. Tutorial)\n- Complicated cataract\n- Calcific band keratopathy (if the iritis becomes chronic) especially in juvenile idiopathic arthritis.\n- Macular edema (if the iritis becomes chronic)",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:2, p:742, key:1,
  stem:"D-shaped pupil is present in:",
  opts:["Iridodonesis","Iridodialysis","Posterior sychiae","Total sector iridectomy"],
  expl:"Iridodialysis is a separation of the iris root from the ciliary body, often due to trauma, giving a D-shaped pupil.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:3, p:744, key:0,
  stem:"A 32-year-old male patient presented with diminution of vision, photophobia, ocular pain and redness in his right eye. Examination of the eye showed ciliary injection, anterior chamber cells, keratic precipitates and aqueous flare. Which of the following is a possible line of treatment?",
  opts:["Steroid drops","Pilocarpine drops","Latanoprost drops","Topical anesthetic drops"],
  expl:"Anterior uveitis (iridocyclitis) is treated with topical corticosteroids to reduce inflammation. Cycloplegic agents may also be added for pain relief.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:4, p:746, key:0,
  stem:"Which of the following is part of the uveal tract?",
  opts:["Ciliary body","Lens","Sclera","Cornea"],
  expl:"The uveal tract consists of the iris, ciliary body, and choroid. These vascular layers provide nourishment and are involved in uveitis.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:5, p:748, key:0,
  stem:"A 28-year-old patient presents with sudden onset of unilateral eye redness, pain, and photophobia. Work-up reveals uveitis. Which systemic condition is most likely associated with this presentation?",
  opts:["Ankylosing spondylitis","Diabetes mellitus","Hypertension","Hyperthyroidism"],
  expl:"Anterior uveitis is commonly associated with HLA-B27 diseases such as ankylosing spondylitis. It presents with unilateral redness, pain, and photophobia.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:6, p:750, key:0,
  stem:"A 35-year-old patient presents with decreased vision, ocular pain, and a constricted pupil that reacts sluggishly to light. Slit-lamp examination confirms anterior uveitis. What is the first-line treatment for this condition?",
  opts:["Steroids","Antibiotics","Observation","Cycloplegics only"],
  expl:"Topical corticosteroids are the mainstay treatment for anterior uveitis to reduce inflammation. Cycloplegics may also be added to relieve pain and prevent synechiae.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:7, p:752, key:2,
  stem:"Which of the following is a cause of dilated fixed pupil?",
  opts:["Morphine","Horner syndrome","Stage 3 anaesthesia","Pontine hemorrhage"],
  expl:"Causes of dilated fixed pupil -> Trauma to the iris sphincter or the orbital parasympathetic nerves (traumatic mydriasis), Pharmacologic dilatation, Ciliary ganglion disease / damage, Oculomotor (III) Paralysis, Brain stem affection (dorsal midbrain syndrome), Stage III anaesthesia & Death (bilateral).",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 2 (c), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:8, p:754, key:3,
  stem:"Which of the following conditions is among the causes of secondary angle closure glaucoma?",
  opts:["Traumatic glaucoma","Inflammatory glaucoma","Steroid-induced glaucoma","Phacomorphic glaucoma"],
  expl:"Causes of secondary angle closure glaucoma → Uveitis, neovascular glaucoma (PDR, CRVO) & phacomorphic glaucoma.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":3,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 3 (d), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:9, p:756, key:0,
  stem:"What is the percentage of aqueous humor that is drained by the uveo-scleral pathway?",
  opts:["10%","20%","30%","50%"],
  expl:"The trabecular pathway is responsible for 90% of the aqueous outflow from the eye. On the other hand, the uveoscleral pathway is responsible for 10% of the aqueous outflow from the eye.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:10, p:758, key:1,
  stem:"Which of the following is true regarding sarcoidosis?",
  opts:["Caseating granuloma","Non-caseating granuloma","Non-granulomatous disease","Acute painful condition"],
  expl:"Note: Histopathology of sarcoidosis ocular lesions shows noncaseating granulomas.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:11, p:760, key:0,
  stem:"A 29-year-old man complains of eye pupil constriction, eyelid drooping and diminished unilateral sweating. Which of the following is the cause of that patient's condition?",
  opts:["Sympathetic affection","Parasympathetic affection","Motor dysfunction","Sensory dysfunction"],
  expl:"Horner syndrome → It is caused by dysfunction of the sympathetic supply. It is characterized by Miosis (with anisocoria mere in the dark), Ptosis and anhidrosis of the ipsilateral face and neck, Enophthalmos & Heterochromia of the iris in congenital cases.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:12, p:762, key:1,
  stem:"A 35-year-old male patient presented with floaters and blurry vision. Examination revealed snow balls and small banking. What is the best line of treatment for such a patient?",
  opts:["Spectacles","Intravitreal steroid injection","PRP","Surgery"],
  expl:"Signs of intermediate uveitis → Snowballs (aggregates of inflammatory cells in the inferior vitreous) & Snow banking (grey-white fibrovascular plaques on the inferior pars plana).\nMain treatment of uveitis → Steroids.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR. Printing defect note: printed_q:12 appears twice in the book (pdf pages 762/763 and 764/765); these are two different unrelated questions, numbered n:12 and n:13 respectively.",
},

{ n:13, p:764, key:3,
  stem:"A 35-year-old male patient was found to have posterior uveitis as a result of an infectious process. Which of the following is the most common cause of this patient's condition?",
  opts:["TB","HSV","Histoplasmosis","Toxoplasmosis","CMV"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":3,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 3 (d), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box.",
},

{ n:14, p:766, key:0,
  stem:"A 28-year-old female patient complains of ocular pain, excessive lacrimation together with diminished vision. Examination revealed keratic precipitates, hypopyon and ciliary injection with violaceous hue. Which of the following is the most likely diagnosis?",
  opts:["Iridocyclitis","Pars planitis","Choroiditis","None of the above"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box.",
},

{ n:15, p:768, key:1,
  stem:"A 35-year-old male patient presented with floaters and blurry vision. Examination revealed snow balls and small banking. What is the best line of treatment for such a patient?",
  opts:["A. Spectacles","B. Intravitreal steroid injection","C.PRP","D. Surgery"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. Fold note: this group is an exact content duplicate of n:12 and is folded into n:12.",
},

{ n:16, p:770, key:3,
  stem:"Which of the following is the innermost layer of the choroid?",
  opts:["Medium-diameter blood vessel layer","Large-diameter blood vessel layer","Choriocapillaris","Bruch's membrane"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":3,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 3 (d), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box.",
},

{ n:17, p:772, key:0,
  stem:"Which of the following is not true regarding the anatomy of uveal tract?",
  opts:["Iris stroma is located posterior of to iris pigment epithelial cells","Iris root is the outer edge of iris attached to sclera","Aqueuos humor secretion is done by pars plicata","Choroid is the most posterior layer of uvea"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box.",
},

{ n:18, p:774, key:1,
  stem:"Which of the following is the outermost layer of the choroid?",
  opts:["Medium-diameter blood vessel layer","Large-diameter blood vessel layer","Choriocapillaris","Bruch's membrane"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box.",
},

{ n:19, p:776, key:1,
  stem:"Vogt Koyanagi Harada syndrome requires all of the following criteria to be diagnosed except?",
  opts:["Absence of history of penetrating eye trauma","Unilateral granulomatous panuveitis","Neurological and auditory mar1festations","Absence of other ocular diseases"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box.",
},

{ n:20, p:778, key:1,
  stem:"Snow balls and snow banking are characteristic of which of the following diseases?",
  opts:["Anterior uveitis","Intermediate uveitis","Posterior uveitis","All of the above"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box.",
},

{ n:21, p:780, key:3,
  stem:"A 34 year old man has an acute painful, red right eye for the last 24 hours. He complains of blurring of vision. He has a past medical history of cervical spondylitis and is on chronic diclofenac treatment. On examination, his pupil is irregular in shape and he is very sensitive to light. What is the SINGLE most likely clinical diagnosis?",
  opts:["A. Acute close-angle glaucoma","B. Conjunctivitis","C. Episcleritis","D. Iridocyclitis","E. Keratitis"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":3,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 3 (d), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box.",
},

{ n:22, p:782, key:2,
  stem:"A 45 year old woman had her visual acuity checked at her local optician. Several hours later she presents with severe ocular pain and redness in her eye. He also complains of seeing coloured halos. What SINGLE anatomical structure is most likely to be involved?",
  opts:["A. Iris","B. Ciliary body","C. Anterior chamber","D. Posterior chamber","E. Cornea"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box.",
},

{ n:23, p:784, key:1,
  stem:"53 years old patient complaining of near vision problems. The patient is asthmatic and has some degree of heart block that is controlled medically. His visual acuity is 6/6 in both eyes. While examination you notice nuclear sclerosis in both eyes. IOP is 28 mmHg in his right eye and 30 mmHg in his left eye, the fundus examination revealed large cup/disc ratio in both eyes. Your diagnosis is POAG. You are going to prescribe medical treatment to him.\nWhat are group of drugs that should be avoided in that patient?",
  opts:["PG analogues","B blockers","Alpha adrenergic agonist","Carbonic anhydrase inhibitor"],
  expl:"Topical beta-blockers like timolol can cause bronchospasm and worsen heart block, so they should be avoided. Other agents like prostaglandin analogues are preferred.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

{ n:24, p:786, key:2,
  stem:"50 years old female patient came to her family doctor complaining of redness of her left eye. Examination showed 28 mmHg IOP, 6/24 VA, hazy cornea and pupillary constriction.\nThe most probable diagnosis is?",
  opts:["Bacterial conjunctivitis","Acute closed angle glaucoma","Acute iridocyclitis","Bacterial keratitis"],
  expl:"Inflammation of the iris and ciliary body causes photophobia, small pupil, and moderate rise in IOP. Cornea appears hazy due to keratic precipitates.",
  boxPrinted:true,
  keySource:"Recorded in the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s10 source (oph-ep-p1-s10-uveal-tract.staging.json); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from staged JSON, never from OCR.",
},

];
