/* Generated mechanically from the staged source (oph-ep-p2-s26-model-exam-5.staging.json).
   KEY CONVENTION: 0-based. `key` is an index into `opts`, taken directly from the staged
   marked-page key_index; key_letter position checked to agree (see mismatches.txt).
   `p` is the row's UNMARKED page, `mp` the marked (answered) page; markedOnly rows have p = mp.
   Numbering is by position. `fig` is true where either page stages figure:true.
   Folds are recorded in sec-oph.js, not here.
   `expl` is verbatim only for boxed rows (boxPrinted true); all other rows keep expl empty. */

var OPHEP2_S26_STAGED = [

{ n:1, p:2024, mp:2025, markedOnly:false, key:2,
  stem:"Lagophthalmos is:",
  opts:["wide palpebral fissure.","lid lag.","inability to close the palpebral fissure.","incomplete opening of the palpebral fissure."],
  expl:"Lagophthalmos is the failure of the eyelids to close completely, often due to facial nerve palsy or scarring. It can lead to exposure keratitis due to corneal drying.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2025), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"c",
},

{ n:2, p:2026, mp:2027, markedOnly:false, key:0,
  stem:"Symblepharon may be caused by:",
  opts:["chemical burn.","spring catarrh.","phlycten.","epidemic keratoconjunctivitis"],
  expl:"Symblepharon is adhesion between the bulbar and palpebral conjunctiva, commonly caused by chemical burns or severe conjunctival inflammation. The scarring process leads to fusion of the conjunctival surfaces.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2027), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"a",
},

{ n:3, p:2028, mp:2029, markedOnly:false, key:2,
  stem:"Astigmatism is NOT corrected by:",
  opts:["glasses.","contact lenses.","radial keratotomy.","LASIK"],
  expl:"Astigmatism is corrected with glasses, contact lenses, or LASIK, but not with radial keratotomy, which is designed mainly for myopia. It involves radial corneal incisions that don’t correct irregular curvature.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2029), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"c",
},

{ n:4, p:2030, mp:2031, markedOnly:false, key:2,
  stem:"Ptosis cannot be caused by:",
  opts:["third nerve palsy.","Horner’s syndrome.","large chalazion of the lower lid.","trauma"],
  expl:"Ptosis is drooping of the upper eyelid caused by conditions like third nerve palsy, Horner’s syndrome, or trauma. A chalazion of the lower lid doesn’t affect the upper lid’s position.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2031), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"c",
},

{ n:5, p:2032, mp:2033, markedOnly:false, key:1,
  stem:"Fluorescein angiography is used for studying:",
  opts:["orbital vessels.","retinal vessels.","lid vessels.","conjunctival vessels"],
  expl:"Fluorescein angiography highlights retinal and choroidal circulation, allowing assessment of vascular diseases like diabetic retinopathy or vein occlusion. It does not visualize orbital or conjunctival vessels.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2033), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:6, p:2034, mp:2035, markedOnly:false, key:1,
  stem:"Pars planitis is:",
  opts:["anterior uveitis.","intermediate uveitis.","posterior uveitis.","panuveitis."],
  expl:"",
  boxPrinted:false, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2035), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:7, p:2036, mp:2037, markedOnly:false, key:1,
  stem:"Inferior oblique muscle is the only:",
  opts:["elevator of the abducted eye.","elevator of the adducted eye.","depressor of the abducted eye.","depressor of the adducted eye"],
  expl:"The inferior oblique muscle elevates the eye when it is adducted. It also contributes to extorsion and abduction.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2037), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:8, p:2038, mp:2039, markedOnly:false, key:3,
  stem:"Phacolytic glaucoma may occur in:",
  opts:["immature senile cortical cataract.","nuclear cataract.","intumescent cataract.","hypermature senile cataract."],
  expl:"Phacolytic glaucoma occurs when lens proteins leak through the capsule of a hypermature cataract, causing secondary open-angle glaucoma. It results in inflammation and raised IOP.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2039), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"d",
},

{ n:9, p:2040, mp:2041, markedOnly:false, key:3,
  stem:"Ectropion can be due to:",
  opts:["scarring of the conjunctiva.","atrophic eye.","injury to the third nerve.","injury to the seventh nerve."],
  expl:"Ectropion is outward turning of the eyelid margin, often caused by facial nerve palsy (7th nerve). It leads to exposure and tearing due to poor lid closure.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2041), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"d",
},

{ n:10, p:2042, mp:2043, markedOnly:false, key:2,
  stem:"Topical corticosteroids are contraindicated in the following type of corneal ulcers:",
  opts:["catarrhal ulcer.","shield ulcer.","dendritic ulcer.","fascicular ulcer."],
  expl:"Corticosteroids worsen herpes simplex keratitis (dendritic ulcer) by promoting viral replication and corneal perforation. Antiviral therapy should be used instead.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2043), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"c",
},

{ n:11, p:2044, mp:2045, markedOnly:false, key:1,
  stem:"Post-traumatic diplopia may be due to:",
  opts:["iridodonesis.","iridodialysis.","angle recession glaucoma.","uniocular hyphema."],
  expl:"Iridodialysis is separation of the iris root from the ciliary body following trauma, which can cause monocular diplopia. It results in an additional pupil-like opening.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2045), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:12, p:2046, mp:2047, markedOnly:false, key:1,
  stem:"A right optic tract lesion results in:",
  opts:["right homonymous hemianopia.","left homonymous hemianopia.","bitemporal hemianopia.","binasal hemianopia."],
  expl:"A right optic tract lesion affects fibers from the left visual fields of both eyes, producing left homonymous hemianopia. This occurs after the optic chiasm.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2047), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:13, p:2048, mp:2049, markedOnly:false, key:1,
  stem:"The most conclusive test for diagnosing esotropia is:",
  opts:["corneal light reflex test.","cover test.","pin-hole test.","Worth's 4 dot test"],
  expl:"The cover test objectively detects latent or manifest squints (like esotropia) by observing eye movement when the fellow eye is covered. It is more reliable than the corneal reflex test.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2049), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:14, p:2050, mp:2051, markedOnly:false, key:3,
  stem:"A 70-year old woman complains of chronic tearing and discharge. Irrigation of the lower canaliculus produces a mucopurulent regurgitation from the upper canaliculus after distending the lacrimal sac. Which of the following statements is true?",
  opts:["Jones one testing will reveal dye in the nose","there is probably a common canalicular obstruction","this condition is usually cured permanently by antibiotics","DCR is the treatment of choice"],
  expl:"The mucopurulent regurgitation from the upper canaliculus after irrigation and distension of the sac indicates an obstruction in the nasolacrimal drainage system, typically at or beyond the lacrimal sac.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2051), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"d",
},

{ n:15, p:2052, mp:2053, markedOnly:false, key:1,
  stem:"Horner's syndrome is characterized by all of the following except:",
  opts:["miosis","widened palpebral fissure","slight enophthalmos","unilateral absence of sweating"],
  expl:"Horner’s syndrome presents with ptosis, miosis, enophthalmos, and anhidrosis. The palpebral fissure is narrowed, not widened.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2053), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:16, p:2054, mp:2055, markedOnly:false, key:2,
  stem:"23-year-old teacher complains that her right eye is red and irritated. You note moderate injection of the larger conjunctival vessels, watery discharge, and a palpable preauricular lymph node.\n\nBased on the above information, which of the following symptoms or facts might be elicited by careful history taking?",
  opts:["Blurred vision","Sore throat","Exposure to children with colds","Itching"],
  expl:"Viral conjunctivitis is highly contagious and often follows upper respiratory infections or contact with infected individuals, especially children. It presents with watery discharge and preauricular lymphadenopathy.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2055), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:17, p:2056, mp:2057, markedOnly:false, key:3,
  stem:"23-year-old teacher complains that her right eye is red and irritated. You note moderate injection of the larger conjunctival vessels, watery discharge, and a palpable preauricular lymph node.\n\nManagement consists of which of the following?",
  opts:["Topical mast cell stabilizer","Broad-spectrum antibiotic eyedrops","Referral to an ophthalmologist","Strict hygienic measure and cold compresses"],
  expl:"Treatment is supportive with hygiene, cold compresses, and avoiding spread. Antibiotics and steroids are unnecessary unless there is secondary infection.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2057), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"D",
},

{ n:18, p:2058, mp:2059, markedOnly:false, key:1,
  stem:"65-year-old man with history of a recent bronchitis awoke this morning with a red eye and has no other symptoms. He has no significant medical problems. On examination, the patient has a sector of the eye that is solid red without injection of the conjunctival vessels.\n\nWhat is the most likely diagnosis?",
  opts:["Scleritis","Subconjunctival hemorrhage","Early viral conjunctivitis","Pterygium"],
  expl:"A subconjunctival hemorrhage appears as a sharply demarcated red patch on the sclera without pain or inflammation. It is benign and resolves spontaneously.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2059), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:19, p:2060, mp:2061, markedOnly:false, key:2,
  stem:"23-year-old teacher complains that her right eye is red and irritated. You note moderate injection of the larger conjunctival vessels, watery discharge, and a palpable preauricular lymph node.\n\nFrom this information alone, what tentative diagnosis would you make?",
  opts:["Bacterial conjunctivitis","Vernal kerato-conjunctivitis","Viral conjunctivitis","Atopic allergic conjunctivitis"],
  expl:"Watery discharge, preauricular lymphadenopathy, and conjunctival injection are typical of viral conjunctivitis. It is self-limited and contagious.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2061), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:20, p:2062, mp:2063, markedOnly:false, key:1,
  stem:"65-year-old man with history of a recent bronchitis awoke this morning with a red eye and has no other symptoms. He has no significant medical problems. On examination, the patient has a sector of the eye that is solid red without injection of the conjunctival vessels.\n\nManagement would consist of which of the following?",
  opts:["Oral NSAIDs","Assurance and follow up","Topical steroid","Urgent referral to ophthalmologist"],
  expl:"No treatment is required; it resolves within 1–2 weeks. Patients should be reassured and checked for systemic causes like hypertension.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2063), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:21, p:2064, mp:2065, markedOnly:false, key:1,
  stem:"54-year-old woman with a red, painful eye and the patient is complaining of photophobia. When you examine her, you note that visual acuity is decreased in the affected eye and cornea appears opaque and hazy with positive fluoresceine staining. What is the most likely diagnosis?",
  opts:["Conjunctivitis","Corneal ulcer","Old corneal scar","Scleritis"],
  expl:"A corneal ulcer presents with pain, photophobia, decreased vision, and fluorescein uptake. It requires urgent antimicrobial therapy.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2065), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:22, p:2066, mp:2067, markedOnly:false, key:3,
  stem:"54-year-old woman with a red, painful eye and the patient is complaining of photophobia. When you examine her, you note that visual acuity is decreased in the affected eye and cornea appears opaque and hazy with positive fluoresceine staining. regarding your management, which of the following should be avoided?",
  opts:["Intensive topical antimicrobial eye drops","Topical cycloplegic eye drops","Scraping for culture and sensitivity","Topical steroid therapy"],
  expl:"Management to avoid in corneal ulcer → (D) Topical steroid therapy\nSteroids delay healing and can worsen corneal infections. The mainstay is topical antibiotics and supportive care.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2067), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"D",
},

{ n:23, p:2068, mp:2069, markedOnly:false, key:0,
  stem:"45-year-old man reports a 2-day history of redness, pain, and photophobia of his left eye. He denies any trauma to the eye, fluorescein staining reveals dendritic corneal ulcer.\n\nManagement would consist of which of the following?",
  opts:["Topical antiviral like acyclovir","Topical steroid therapy","Topical antibiotics","Assurance and follow-up in one week"],
  expl:"Herpes simplex keratitis is treated with topical antivirals, not steroids. Steroids can exacerbate viral replication.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2069), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"A",
},

{ n:24, p:2070, mp:2071, markedOnly:false, key:2,
  stem:"50 years old female patient came to her family doctor complaining of redness of her left eye. Examination showed 28 mmHg IOP, 6/24 VA, hazy cornea and pupillary constriction.\n\nThe most probable diagnosis is?",
  opts:["Bacterial conjunctivitis","Acute closed angle glaucoma","Acute iridocyclitis","Bacterial keratitis"],
  expl:"nflammation of the iris and ciliary body causes photophobia, small pupil, and moderate rise in IOP. Cornea appears hazy due to keratic precipitates.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2071), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:25, p:2072, mp:2073, markedOnly:false, key:1,
  stem:"60-year-old man notes sudden profound loss of vision in his right eye, with onset one hour ago. The patient has a past medical history of hypertension. On examination, the visual acuity is OD hand motion and OS 6/6. The pupil of the right eye shows RAPD. The direct ophthalmoscope shows that the red reflex is clear in both eyes. Fundus examination in the right eye reveals a white opacified retina with cherry red spot in the macular area. The left eye is normal. No other clinical manifestation. What is your diagnosis?",
  opts:["A. AION","B. CRAO","C. Optic neuritis","D. Retinal detachment"],
  expl:"Central retinal artery occlusion causes sudden, painless vision loss with a pale retina and cherry-red macula. It’s an ophthalmic emergency.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2073), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:26, p:2074, mp:2075, markedOnly:false, key:1,
  stem:"60-year-old man notes sudden profound loss of vision in his right eye, with onset one hour ago. The patient has a past medical history of hypertension. On examination, the visual acuity is OD hand motion and OS 6/6. The pupil of the right eye shows RAPD. The direct ophthalmoscope shows that the red reflex is clear in both eyes. Fundus examination in the right eye reveals a white opacified retina with cherry red spot in the macular area. The left eye is normal. No other clinical manifestation. Regarding your diagnosis, which of the following would be the most appropriate way of management?",
  opts:["Systemic steroid","AC paracentesis","Carotid doppler U/S","Anti-VEGF"],
  expl:"Immediate measures like ocular massage and anterior chamber paracentesis aim to dislodge the embolus and restore retinal perfusion. Carotid Doppler follows for cause assessment",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2075), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:27, p:2076, mp:2077, markedOnly:false, key:2,
  stem:"A healthy 48-year-old man complains of seeing \"floating black dots\" in the field of vision of his right eye for 2 days, associated with sensation of flashing light in the periphery of the visual field. Later on, he noticed a disturbance in the temporal field of vision of his right eye like \"curtain coming down\". His visual acuity is 6/6 in both eyes. Anterior segment examination is normal. The red reflex of the left eye is normal but in the right eye reveals area of grayish reflex. What is your diagnosis?",
  opts:["Vitreous hemorrhage","BRAO","Rhegmatogenous retinal detachment","Tractional retinal detachment"],
  expl:"Retinal tear allows vitreous fluid to accumulate under the retina, causing flashes and field loss described as a curtain. Urgent surgical repair is needed.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2077), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:28, p:2078, mp:2079, markedOnly:false, key:2,
  stem:"34-year-old woman notes acute vision loss in her left eye. She is in otherwise good health. On examination, her visual acuity is OD 6/6, OS 6/60. Defective color vision is noticed in her left eye. Examination of the pupillary light reflex reveals RAPD in the left eye. The anterior segment examination is normal. The red reflex is clear and fundus examination is normal in both eyes.\n\nWhat is your diagnosis?",
  opts:["A. AION","B. Optic atrophy","C. Retrobulbar optic neuritis","D. Papillitis"],
  expl:"Optic neuritis causes visual loss and color desaturation with a normal-appearing fundus initially (“the patient sees nothing, the doctor sees nothing”). It’s often associated with multiple sclerosis.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2079), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:29, p:2080, mp:2081, markedOnly:false, key:2,
  stem:"43 years old patient complaining of blurred vision. On detailed history the vision problem is mainly during doing his work on laptop. Visual acuity is 6/6 in both eyes with normal IOP. Examination of the anterior segment reveals nuclear sclerosis, while fundus examination is normal in both eyes.\n\nWhat do you recommend for this patient?",
  opts:["Glasses for distant vision correction","Preparing patient for phacoemulsification for nuclear sclerosis","Glasses for near vision correction","Assurance of the patient and scheduling follow up visits"],
  expl:"This is presbyopia due to loss of lens elasticity with age.\nReading glasses correct the near vision difficulty.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2081), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:30, p:2082, mp:2083, markedOnly:false, key:1,
  stem:"76-year-old man has noted visual distortion over the past week. His concern increased when he discovered that the distortion was in the right eye only. Straight lines viewed through his left eye remained straight. Visual acuity testing revealed OD 6/24, OS 6/6.\n\nWhat further tests will help determine the source of the patient's vision loss?",
  opts:["Colour vision test","Amsler grid test","Visual field test","OCT for optic nerve"],
  expl:"The Amsler grid detects central visual distortion typical of macular diseases like AMD. It helps localize macular dysfunction.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2083), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:31, p:2084, mp:2085, markedOnly:false, key:2,
  stem:"60 years old diabetic patient for more than 20 years is developing a nuclear cataract in his both eyes, and his visual acuity has decreased to OD 6/18 and OS 6/24. His vision bothers him while he is driving because he cannot read street signs. He went to an optometrist for new glasses but was told he needed cataract surgery. He was referred for cataract surgery in 2 weeks with a surgeon who has not examined his eyes. The patient asks your advice.\nWhat do you recommend to help this patient?",
  opts:["Proceed with the surgery to help prevent a car accident.","Advise him to defer cataract surgery for at least 6 month.","Refer the patient to ophthalmologist to determine the impact of cataract on decreased vision.","Assurance of the patient and advise him to follow up regularly"],
  expl:"",
  boxPrinted:false, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2085), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:32, p:2086, mp:2087, markedOnly:false, key:0,
  stem:"53 years old patient complaining of near vision problems. The patient is asthmatic and has some degree of heart block that is controlled medically. His visual acuity is 6/6 in both eyes. While examination you notice nuclear sclerosis in both eyes. IOP is 28 mmHg in his right eye and 30 mmHg in his left eye, the fundus examination revealed large cup/disc ratio in both eyes. You suspect that patient has POAG.\n\nWhat further tests will help you to confirm the diagnosis?",
  opts:["Visual field test","Fluoresceine angiography","Amsler grid test","OCT for macula"],
  expl:"Visual field testing detects the characteristic arcuate scotomas of glaucoma. It confirms functional loss from optic nerve damage.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2087), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"A",
},

{ n:33, p:2088, mp:2089, markedOnly:false, key:3,
  stem:"65 years old patient complaining of gradual decrease visual acuity in both eyes in the last 3 months. Medical history of diabetes for more than 20 years. Visual acuity is 6/24 in both eyes. Patient is pseudophakic in both eyes with clear media. Fundus examination revealed bilateral diabetic macular edema and mild NPDR.\n\nWhat further tests could help in diagnosis?",
  opts:["Visual field test","OCT for optic nerve","Amsler grid test","Fluoresceine angiography"],
  expl:"This test visualizes retinal microaneurysms and leakage at the macula. It helps guide laser or anti-VEGF treatment.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2089), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"D",
},

{ n:34, p:2090, mp:2091, markedOnly:false, key:2,
  stem:"65 years old patient complaining of gradual decrease visual acuity in both eyes in the last 3 months. Medical history of diabetes for more than 20 years. Visual acuity is 6/24 in both eyes. Patient is pseudophakic in both eyes with clear media. Fundus examination revealed bilateral diabetic macular edema and mild NPDR.\n\nWhat is the appropriate treatment for this patient?",
  opts:["YAG laser capsulotomy","PRP laser","Intravitreal Anti-VEGF","Oral antioxidant supplements"],
  expl:"Anti-VEGF injections reduce vascular permeability and macular swelling.\nThey are first-line therapy for diabetic macular edema.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2091), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:35, p:2092, mp:2093, markedOnly:false, key:1,
  stem:"53 years old patient complaining of near vision problems. The patient is asthmatic and has some degree of heart block that is controlled medically. His visual acuity is 6/6 in both eyes. While examination you notice nuclear sclerosis in both eyes. IOP is 28 mmHg in his right eye and 30 mmHg in his left eye, the fundus examination revealed large cup/disc ratio in both eyes. Your diagnosis is POAG. You are going to prescribe medical treatment to him.\n\nWhat are group of drugs that should be avoided in that patient?",
  opts:["PG analogues","B blockers","Alpha adrenergic agonist","Carbonic anhydrase inhibitor"],
  expl:"Topical beta-blockers like timolol can cause bronchospasm and worsen heart block, so they should be avoided. Other agents like prostaglandin analogues are preferred.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2093), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:36, p:2094, mp:2095, markedOnly:false, key:1,
  stem:"A 64-year-old man presented for evaluation of binocular horizontal diplopia that began 2 weeks earlier and was most bothersome when viewing at a distance. He noted that the diplopia was more prominent when he directed his gaze to the left but otherwise it was present “all the time.” He had a history of hypertension, diabetes mellitus, and dyslipidemia. On examination, of the patient’s left eye showed esodeviation and did not fully abduct, the fundus examination was normal. What is your diagnosis?",
  opts:["Myasthenia gravis","6th nerve palsy","3rd nerve palsy","Increase ICP"],
  expl:"Sixth nerve palsy causes horizontal diplopia and limited abduction due to lateral rectus weakness. It is often related to diabetes or hypertension.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2095), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:37, p:2096, mp:2097, markedOnly:false, key:2,
  stem:"45-year-old woman comes to the emergency center because of severe left sided headache and double vision that began the night before, immediately following vigorous exercise. As you examine her, she continues to complain of severe left-sided headache. Her neuro-ophthalmologic examination is normal, except that the left upper eyelid is ptotic; and the left pupil is dilated 3 mm more than the right and responds very poorly to light. Her motility looks grossly normal. What is your diagnosis?",
  opts:["Myasthenia gravis","Optic nerve disease","Third nerve palsy","Diabetic neuropathy"],
  expl:"Ptosis with a dilated, poorly reactive pupil indicates parasympathetic involvement of the oculomotor (III) nerve. The normal motility suggests partial or early third nerve palsy, often due to aneurysm or vascular compression.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2097), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:38, p:2098, mp:2099, markedOnly:false, key:3,
  stem:"A 34-year-old man presented to his family doctor complaining of some visual distortion, he had noticed in the past week intermittent period of double vision and mild ptosis, and then things went back to normal. He reported some difficulties in lifting things with his arm. He did not report any other neurologic symptoms. Ocular examination was normal except for mild ptosis appear with prolonged upgaze and improve with ice pack.\n\nWhat is the proper management for this case?",
  opts:["Assurance and follow up of the patient","CT orbit and lab investigation in form of T3, T4, and TSH","Topical steroid eye drops and follow up in one week.","Make an appointment with ophthalmology and neurology clinic"],
  expl:"",
  boxPrinted:false, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2099), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"D",
},

{ n:39, p:2100, mp:2101, markedOnly:false, key:1,
  stem:"45 years old woman presented to her family doctor complaining of diplopia. On examination there was retraction of upper eyelid of right eye, proptosis and limited ocular movement especially in up-gaze, with mild pain. Pupil of the right eye was slightly dilated and showed sluggish reaction to light compared to her left eye.\n\nWhat is your diagnosis?",
  opts:["Myasthenia gravis","Thyroid eye disease","3rd nerve palsy due to microvascular ischemic lesion","3rd nerve palsy due to aneurysm of the posterior communicating artery"],
  expl:"Proptosis, lid retraction, and restricted upgaze with mild pain are typical of thyroid eye disease due to autoimmune inflammation of extraocular muscles. The sluggish pupil helps rule out isolated nerve palsy.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2101), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:40, p:2102, mp:2103, markedOnly:false, key:3,
  stem:"Your neighbor, a 43-year-old woman, is cleaning her swimming pool. While she is pouring some concentrated algaecide into the pool, a large amount of this solution splashes into her right eye. When you hear her screams, you come to her aid less than 30 seconds after the injury.\n\nWhich of the following should you do first?",
  opts:["Bundle her into your car and speed off for the nearest emergency center.","Run back to your study to look up the specific antidote for algaecide.","Carefully examine her eye for evidence of ocular hyperemia.","Copious irrigation with water from the nearest source instructing her to hold her eyes open to flush out chemical."],
  expl:"Immediate and prolonged irrigation is the first and most critical step in any chemical eye injury. It reduces the contact time of the chemical with ocular tissues and prevents further damage.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2103), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"D",
},

{ n:41, p:2104, mp:2105, markedOnly:false, key:0,
  stem:"25-year-old man complaining of decreased vision and pain in his right eye after being involved in a fist fight. There are edema and ecchymosis of the eyelids. His visual acuity is OD 6/12 and OS 6/6, pupils are round and reactive, normal IOP and no restriction of ocular motility. On examination of the anterior segment, you notice a diffuse haze in the anterior chamber and early layering of blood inferiorly. Regarding your diagnosis; Which of the following would be the most appropriate treatment?",
  opts:["Bed rest in 45 degree and close follow up with an ophthalmologist.","Prescribe steroid drops and antiglaucoma drops, and tell the patient to keep his head elevated.","Hospitalization and immediately call for an ophthalmologist.","Refer to ophthalmologist for surgical evacuation as soon as possible."],
  expl:"",
  boxPrinted:false, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2105), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"A",
},

{ n:42, p:2106, mp:2107, markedOnly:false, key:1,
  stem:"28-year-old male patient has pain, tearing and blurred vision in his right eye. Earlier in afternoon, while he had been working on his car with a hammer and chisel, he noticed that something flying into his right eye. Examination revealed that visual acuity is 6/60 in the right eye. There is conjunctival hyperemia, the pupil seems to be peaked and pointing to the 7 o’clock position of the limbus. There is a small, dark, slightly elevated body at the 7 o’clock position of the limbus. The left eye is normal.\nWhich of the following would be the appropriate initial management for this situation?",
  opts:["Irrigation of the limbal foreign body","Application of a protective shield","Removal of the limbal foreign body using a cotton-tipped applicator","Removal of the limbal foreign body using forceps"],
  expl:"The peaked pupil and dark body at the limbus suggest a penetrating injury with intraocular foreign body. The eye should not be manipulated—apply a shield and refer urgently.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2107), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:43, p:2108, mp:2109, markedOnly:false, key:3,
  stem:"A recurrent bilateral conjunctivitis occurring with the onset of hot weather in young boys with symptoms of burning, itching, and lacrimation with large flat topped cobble stone papillae raised areas in the palpebral conjunctiva is diagnosed as:",
  opts:["Mucopurulent conjunctivitis","Trachoma","Phlyctenular conjunctivitis","Vernal keratoconjunctivitis"],
  expl:"Seasonal, recurrent allergic conjunctivitis in boys with cobblestone papillae on the upper tarsal conjunctiva is typical of vernal keratoconjunctivitis. It is an allergic inflammatory condition.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2109), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"D",
},

{ n:44, p:2110, mp:2111, markedOnly:false, key:3,
  stem:"Seeing colored halos of gradual onset and slowly progressive course in a young male with frequent changing glasses prescription is most probably:",
  opts:["Acute glaucoma","Senile cataract","Uveitis","Keratoconus"],
  expl:"Gradual onset of colored halos with frequent changes in glasses in a young person suggests irregular astigmatism due to keratoconus. It’s a progressive corneal ectatic disorder.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2111), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"d",
},

{ n:45, p:2112, mp:2113, markedOnly:false, key:1,
  stem:"A painful , tender , non-itchy localized redness of conjunctiva can be caused by which of the folloeing pathology ?",
  opts:["Bulbar spring catarrh","Episcleritis","Vascular pterygium","Phlyctenular conjunctivitis"],
  expl:"Localized, tender, non-itchy redness without discharge points to episcleritis, a benign inflammation of the episcleral tissue. It’s self-limiting and less painful than scleritis.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2113), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:46, p:2114, mp:2115, markedOnly:false, key:0,
  stem:"6 years old child presented with white pupil of his right eye that appeared for the first time since 2 months following trauma to the right eye with stick. The parents assure that the vision in the affected eye was completely normal in previous examinations prior to the trauma. Which of the following pathologies is the possible cause of leukocoria in this patient?",
  opts:["Cataract","Retinoblastoma","Retinopathy of prematurity","Corneal degeneration"],
  expl:"Sudden leukocoria (white pupil) appearing after trauma with prior normal vision is likely traumatic cataract. Retinoblastoma is excluded since vision was normal before trauma.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2115), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"A",
},

{ n:47, p:2116, mp:2117, markedOnly:false, key:0,
  stem:"A baby about 39 days old presents with excessive lacrimation and photophobia. He has large and hazy cornea in both eyes. His lacrimal system is normal. What is the probable diagnosis?",
  opts:["Congenital glaucoma.","Megalocornea","Keratoconus.","Hunter’s syndrome"],
  expl:"Photophobia, tearing, and a large hazy cornea in infancy are classic signs of congenital glaucoma due to increased IOP stretching the cornea. Early diagnosis prevents optic nerve damage.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2117), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"a",
},

{ n:48, p:2118, mp:2119, markedOnly:false, key:1,
  stem:"A middle aged female with recurrent joint pain gave past history of recurrent attacks of pain, redness and dropped vision in one eye. Recently she complained of similar attack. The most important diagnostic sign of activity is:",
  opts:["Festooned pupil","Aqueous flare and cells (iridocyclitis)","Pigmented KPs","Patches of iris atrophy"],
  expl:"Active uveitis (iridocyclitis) shows inflammatory cells and protein in the anterior chamber (“flare”). These indicate current activity requiring anti-inflammatory treatment.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2119), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:49, p:2120, mp:2121, markedOnly:false, key:3,
  stem:"A one-month old baby is brought with complaints of photophobia and watering. Clinical examination shows normal tear passages and clear but large cornea. The most likely diagnosis is:",
  opts:["Congenital dacryocystitis","Interstitial keratitis","Keratoconus","Buphthalmos"],
  expl:"An enlarged, clear cornea in a one-month-old with photophobia suggests buphthalmos, the infant form of congenital glaucoma. The enlarged eye results from raised IOP before scleral maturation.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2121), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"d",
},

{ n:50, p:2122, mp:2123, markedOnly:false, key:1,
  stem:"You have been referred a case of open angle glaucoma. Which of the following would be an important point in diagnosing the case?",
  opts:["Shallow anterior chamber","Optic disc cupping","Narrow angle","visual acuity and refractive error"],
  expl:"In open-angle glaucoma, optic disc cupping is a hallmark of progressive optic nerve damage due to increased IOP, even when the anterior chamber remains deep and open.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2123), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:51, p:2124, mp:2125, markedOnly:false, key:0,
  stem:"On examining the fundus of one patient, multifocal yellowish grey patches with well demarcated borders were seen. Also there are other well defined areas of chorioretinal atrophy with pigmented borders. Which one of the following is the most probable diagnosis for such presentation?",
  opts:["Choroiditis","Exudative retinal detachment","Retinitis pigmentosa","Retinal vasculitis"],
  expl:"Multifocal yellow-gray lesions with pigmented borders on the fundus indicate choroiditis, an inflammatory condition of the choroid and retina. These can lead to scarring and atrophy.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2125), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"a",
},

{ n:52, p:2126, mp:2127, markedOnly:false, key:2,
  stem:"Visual acuity of a 2-year-old child can be tested by:",
  opts:["Snellen’s chart","Landolt’s chart","Optokinetic drum","Electroretinogram"],
  expl:"For toddlers, visual acuity can be assessed using an optokinetic drum, which tests their ability to track moving stripes. It’s suitable for preverbal children.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2127), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"c",
},

{ n:53, p:2128, mp:2129, markedOnly:false, key:1,
  stem:"In pinhole test, the visual acuity gets better if the patient has:",
  opts:["Nuclear cataract","Error of refraction","Optic nerve lesion","Macular scar"],
  expl:"Improvement of vision with a pinhole test indicates refractive error, as the pinhole eliminates peripheral light rays and improves focus on the retina.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2129), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:54, p:2130, mp:2131, markedOnly:false, key:1,
  stem:"Photophobia can be due to:",
  opts:["Immature senile cataract","Corneal ulcer","Retinal detachment","Senile macular degeneration"],
  expl:"Photophobia occurs when the cornea is inflamed or ulcerated due to irritation of corneal nerves. It’s not seen in retinal or lens conditions.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2131), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:55, p:2132, mp:2133, markedOnly:false, key:1,
  stem:"Measuring corneal curvature is done using:",
  opts:["Pachymetry","Corneal topography","Gonioscopy","Biometry"],
  expl:"Corneal topography maps the curvature and shape of the cornea, useful for diagnosing keratoconus or planning refractive surgery.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2133), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"b",
},

{ n:56, p:2134, mp:2135, markedOnly:false, key:0,
  stem:"The normal range for intraocular pressure (IOP) as measured by applanation tonometry is:",
  opts:["10–21 mmHg","16 mmHg","12–17 mmHg","8–17 mmHg"],
  expl:"The normal IOP range is 10–21 mmHg; values outside this may indicate ocular hypertension or glaucoma.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2135), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"a",
},

{ n:57, p:2136, mp:2137, markedOnly:false, key:3,
  stem:"Applanation tonometry:",
  opts:["Can be performed using a Schiotz tonometer","Must be performed on a sitting patient","Is inaccurate on eyes with abnormal scleral rigidity","Is the most accurate method of measuring intraocular pressure"],
  expl:"Applanation tonometry (e.g., Goldmann) directly measures the force required to flatten a small corneal area, making it the most accurate method for IOP measurement.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2137), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"d",
},

{ n:58, p:2138, mp:2139, markedOnly:false, key:2,
  stem:"A 29 years old mechanic was hammering an iron object when he felt something hitting his right eye. On eye examination by the slit lamp, a sealed entry wound was seen in the right temporal cornea otherwise the rest of the anterior segment was free. What investigation is not advised in this condition?",
  opts:["CT eye and orbit","Plain X ray to the orbit","MRI","B scan ultrasound"],
  expl:"MRI is contraindicated if a metallic intraocular foreign body is suspected, as the magnetic field can move or heat the metal, causing serious damage.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2139), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"c",
},

{ n:59, p:2140, mp:2141, markedOnly:false, key:2,
  stem:"In the management of diabetic retinopathy, optimal glycemic control is targeted to achieve which of the following HbA 1 c levels?",
  opts:["5%","6%","7%","8%"],
  expl:"Optimal glycemic control in diabetic retinopathy aims for HbA1c around 7%, reducing the risk of progression and other microvascular complications.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2141), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:60, p:2142, mp:2143, markedOnly:false, key:0,
  stem:"A 22-year-old male complains of double vision. Examination revealed esotropia, inability to abduct the left eye and face turn to the left side. which of the following is the most likely diagnosis?",
  opts:["Left abducent palsy","Left trochlear palsy","Right abducent palsy","Left abducent palsy"],
  expl:"Inability to abduct the left eye with esotropia indicates left lateral rectus weakness due to left abducent (VI) nerve palsy.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2143), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"A",
},

{ n:61, p:2144, mp:2145, markedOnly:false, key:1,
  stem:"A 6-month-old child presented with epiphora due to nasolacrimal duct obstruction. Pressure over lacrimal sac caused reflux of purulent material from lacrimal punctum. What's the best management for that child?",
  opts:["Lacrimal sac massage only","Lacrimal sac massage and probing surgery if no response after 1 year of age","Immediate probing","Incision and drainage"],
  expl:"Most congenital nasolacrimal duct obstructions resolve with Crigler massage; probing is delayed until after 1 year if symptoms persist.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2145), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:62, p:2146, mp:2147, markedOnly:false, key:0,
  stem:"A 58-year-old male patient presents with complete lens opacification. What is the best tool used to visualize retina in that patient?",
  opts:["Ultrasonography","Ophthalmoscopy","Pachymetry","Pentacam"],
  expl:"When the lens is opaque, B-scan ultrasonography helps visualize the retina and posterior segment structures.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2147), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"A",
},

{ n:63, p:2148, mp:2149, markedOnly:false, key:2,
  stem:"A 65-year-old man visits the ophthalmologist with a complaint of noticing a brown ring in both eyes. From history, there was no blurred vision or any other complaint. Examination revealed bilateral grayish brown ring around the limbus and separated from the limbus by a clear scleral zone. Which of the following would be the most important next step to do for such a patient?",
  opts:["Urgent surgery","CT orbit","Lipid profile and reassurance","Massive steroid administration","Ophthalmoscopic examination"],
  expl:"A corneal arcus (gray-brown ring) is common in the elderly; however, a lipid profile is recommended to rule out hyperlipidemia.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2149), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:64, p:2150, mp:2150, markedOnly:false, key:null,
  stem:"Which of the following is the area mostly affected by dryness in case of inability to completely close the eyelids?",
  opts:["Middle 1/3 of the cornea","Upper 1/3 of the cornea","Lower 1/3 of the cornea","The whole cornea"],
  expl:"",
  boxPrinted:false, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2150), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:false, keyLetter:"",
},

{ n:65, p:2151, mp:2152, markedOnly:false, key:2,
  stem:"A 33-year-old woman presents with ptosis with S-shaped deformity of the upper eyelid. Examination revealed tenderness, edema and erythema of the outer third of the upper eyelid. What is the most likely diagnosis?",
  opts:["Acute dacryocystitis","Chronic dacryocystitis","Acute dacryoadenitis","Dry eye disease"],
  expl:"Tender swelling at the outer upper eyelid with S-shaped ptosis indicates inflammation of the lacrimal gland (dacryoadenitis).",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2152), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:66, p:2153, mp:2154, markedOnly:false, key:0,
  stem:"Corneal light reflex testing was performed on a patient. The light reflection was seen in the center of the right eye and in the temporal part of the pupil of the left eye. Which of the following is the significance of these findings?",
  opts:["15 degree left esotropia","15 degree left exotropia","45 degree left esotropia","45 degree left exotropia"],
  expl:"A temporal light reflex means the eye is deviated outward (exotropia). Each millimeter of displacement roughly equals 15 degrees of deviation.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2154), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"A",
},

{ n:67, p:2155, mp:2156, markedOnly:false, key:2,
  stem:"Which of the following is the most common cause of vision impairment?",
  opts:["Cataract","Gluacoma","Uncorrected refractive errors","Trachoma"],
  expl:"Globally, the most common cause of visual impairment is uncorrected refractive error (myopia, hyperopia, astigmatism).",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2156), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:68, p:2157, mp:2158, markedOnly:false, key:3,
  stem:"Orbital floor fractures are best assessed with which of the following diagnostic imaging modalities?",
  opts:["MRI","X ray","Ultrasound","CT coronal section","CT axial section"],
  expl:"Orbital floor fractures are best evaluated using CT coronal images, which clearly show the orbital floor and herniated tissues.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2158), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"D",
},

{ n:69, p:2159, mp:2160, markedOnly:false, key:2,
  stem:"A 80-year-old man presents to the GP with a complaint of severe eye pain, redness and decreased vision. Examination was carried out and it revealed that the redness had violet-bluish hue with scleral edema. Phenylephrine 10% was used topically for a few minutes but the redness didn't disappear. Which of the following would be the most appropriate next step in order to properly treat that patient?",
  opts:["Conservative management as it is a self-limited condition","Massive doses of steroids","Urgent referral to an ophthalmologist","Broad spectrum antibiotics"],
  expl:"Severe eye pain with bluish scleral hue unresponsive to phenylephrine suggests scleritis, which may be linked to systemic disease and needs urgent specialist care.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2160), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:70, p:2161, mp:2162, markedOnly:false, key:2,
  stem:"Which of the following is the best line of treatment used to control the acute inflammatory stage of thyroid eye disease?",
  opts:["Eye lubricants","Topical steroids","Systemic steroids","Decompressive surgery"],
  expl:"The acute inflammatory phase of thyroid eye disease responds best to systemic corticosteroids to reduce orbital inflammation.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2162), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:71, p:2163, mp:2164, markedOnly:false, key:2,
  stem:"Which of the following imaging modalities is absolutely contraindicated in a patient with intra-ocular metallic foreign body?",
  opts:["CT","X ray","MRI","Ultrasound"],
  expl:"MRI is absolutely contraindicated in cases of metallic intraocular foreign bodies due to magnetic movement and heating risks.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2164), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:72, p:2165, mp:2166, markedOnly:false, key:0,
  stem:"A 32-year-old woman sees an ophthalmologist as she suffers from eyelid drooping together with eye deviation outwards and downwards. Examination revealed unilateral mydriasis. Which of the following nerve paralysis is the cause of the patient's manifestations?",
  opts:["Oculomotor nerve","Trochlear nerve","Abducent nerve","Facial nerve"],
  expl:"Ptosis, “down and out” deviation, and a dilated pupil indicate oculomotor (III) nerve palsy, affecting most extraocular muscles and the sphincter pupillae.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2166), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"A",
},

{ n:73, p:2167, mp:2168, markedOnly:false, key:2,
  stem:"Which of the following increases the risk of central retinal vein occlusion?",
  opts:["Beta blockers","Steroids","Oral contraceptives","Anemia"],
  expl:"Central retinal vein occlusion risk increases with oral contraceptive use due to hypercoagulability and venous stasis.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2168), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:74, p:2169, mp:2170, markedOnly:false, key:1,
  stem:"Which of the following is considered a visual field defect that is characteristic of glaucoma?",
  opts:["Floaters","Arcuate scotoma","Bitemporal hemianopia","Xanthopsia"],
  expl:"Arcuate scotoma is a characteristic visual field defect in glaucoma, corresponding to damage of arcuate nerve fibers near the optic disc.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2170), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

{ n:75, p:2171, mp:2172, markedOnly:false, key:2,
  stem:"How can you differentiate between episcleritis and scleritis?",
  opts:["Using phenylephrine 2.5%, redness disappears in episcleritis","Using phenylephrine 2.5%, redness disappears in scleritis","Using phenylephrine 10%, redness disappears in episcleritis","Using phenylephrine 10%, redness disappears in scleritis"],
  expl:"Episcleritis vessels blanch with topical phenylephrine, while scleritis vessels do not, helping to distinguish between the two.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2172), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"C",
},

{ n:76, p:2173, mp:2174, markedOnly:false, key:1,
  stem:"Following ocular trauma, a patient presented with enophthalmos and anesthesia of lower eyelid, cheek, side of nose, upper lip, upper teeth and gums. Which of the following is the nerve that is most probably involved in the trauma and caused these manifestations?",
  opts:["Supraorbital nerve","Infraorbital nerve","Facial nerve","Glossopharyngeal nerve"],
  expl:"Orbital floor fractures commonly injure the infraorbital nerve, causing numbness of the lower eyelid, cheek, and upper lip.",
  boxPrinted:true, fig:false,
  keySource:"Recorded in the staged source (oph-ep-p2-s26-model-exam-5.staging.json, marked p.2174), read by a vision model. Not re-derived by this script.",
  keyLetterAgree:true, keyLetter:"B",
},

];
