/* Generated mechanically from the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json).
   Source pairs: unmarked p.1014 through marked p.1065.
   KEY CONVENTION: 0-based. `key` is an index into `opts` -- 0=A/a, 1=B/b, 2=C/c, 3=D/d, 4=E/e --
   taken directly from the staged marked-page key_index.
   `p` is the row's own UNMARKED page; the marked (answered) page is p+1. Numbering is by position;
   printed_q 1..26 run in order and none repeats. n18 (p.1048) is an exact cross-chapter reprint of live
   ophep-squint-10 (p.1094) and is folded at drafting; its row stays here.
   `expl` is verbatim only for boxed rows (boxPrinted true); all other rows keep expl empty. */

var OPHEP_S14_STAGED = [

{ n:1, p:1014, key:3,
  stem:"Consecutive optic atrophy occurs in:",
  opts:["Optic neuritis","Papilledema","Glaucoma","Retinitis pigmentosa"],
  expl:"Consecutive optic atrophy follows degenerative retinal diseases like retinitis pigmentosa, where retinal degeneration leads to secondary optic nerve atrophy. It differs from primary optic atrophy, which originates from optic nerve pathology.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1015), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":3,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 3 (d), from the staged s14 source, marked p.1015; printed_q 1. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 1, 1015",
},

{ n:2, p:1016, key:1,
  stem:"A pituitary adenoma produces:",
  opts:["Binasal hemianopia","Bitemporal hemianopia","A central scotoma","An arcuate scotoma"],
  expl:"A pituitary adenoma compresses the optic chiasm, where nasal fibers from both eyes cross, leading to bitemporal hemianopia (loss of temporal visual fields in both eyes).",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1017), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s14 source, marked p.1017; printed_q 2. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 2, 1017",
},

{ n:3, p:1018, key:0,
  stem:"Unilateral dilated pupil is not caused by:",
  opts:["Horner syndrome","Ocular trauma","Atropine toxicity","Third cranial nerve palsy"],
  expl:"Horner syndrome causes miosis (small pupil), not dilation. Dilated pupils result from third nerve palsy, ocular trauma, or exposure to anticholinergic agents like atropine.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1019), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1019; printed_q 3. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 3, 1019",
},

{ n:4, p:1020, key:2,
  stem:"Afferent pupillary defect is seen in:",
  opts:["Third nerve paralysis","Sympathetic paralysis","Optic atrophy","Lesions of the occipital cortex"],
  expl:"An afferent pupillary defect (Marcus Gunn pupil) occurs when the optic nerve is damaged, as in optic atrophy. The pupil constricts less when light is shone in the affected eye.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1021), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 2 (c), from the staged s14 source, marked p.1021; printed_q 4. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 4, 1021",
},

{ n:5, p:1022, key:0,
  stem:"A left optic tract lesion is manifested by:",
  opts:["Right homonymous hemianopia","Left homonymous hemianopia","Bitemporal hemianopia","Binasal hemianopia"],
  expl:"A left optic tract lesion affects the right visual fields of both eyes, producing right homonymous hemianopia.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1023), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1023; printed_q 5. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 5, 1023",
},

{ n:6, p:1024, key:0,
  stem:"Marcus Gunn pupil is found in which condition?",
  opts:["Compressive optic neuropathy","Glaucoma","Cataract","Retinal detachment"],
  expl:"A Marcus Gunn pupil (relative afferent pupillary defect) occurs in optic nerve lesions, such as compressive optic neuropathy. The affected eye shows reduced constriction to direct light.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1025), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1025; printed_q 6. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 6, 1025",
},

{ n:7, p:1026, key:0,
  stem:"A 55-year-old patient presents with ptosis, diplopia, and the eye deviated “down and out.” The pupil is dilated and non-reactive to light. What is the most common cause of this presentation?",
  opts:["Posterior communicating artery aneurysm","Diabetic neuropathy","Cavernous sinus thrombosis","Multiple sclerosis"],
  expl:"Aneurysm compressing the oculomotor nerve causes ptosis, “down and out” eye, and pupil dilation. This is an emergency due to risk of rupture and subarachnoid hemorrhage.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1027), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1027; printed_q 7. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 7, 55, 1027",
},

{ n:8, p:1028, key:1,
  stem:"A 60-year-old man presents with ptosis, miosis, and enophthalmos. Which investigation should be done to identify the cause?",
  opts:["Echocardiography","MRI thorax","MRI abdomen"],
  expl:"This presentation suggests Horner syndrome, which may result from a lesion along the sympathetic pathway commonly due to apical lung (Pancoast) tumor. Therefore, MRI of the thorax is the best investigation to identify the underlying cause.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1029), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s14 source, marked p.1029; printed_q 8. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 8, 60, 1029",
},

{ n:9, p:1030, key:1,
  stem:"A 45-year-old man presents with unilateral ptosis, anhidrosis, enophthalmos, and anisocoria that is more apparent in dim lighting. What is the most likely diagnosis?",
  opts:["Oculomotor nerve palsy","Horner syndrome","Myasthenia gravis","Adie’s pupil"],
  expl:"Horner syndrome is characterized by ptosis, miosis, anhidrosis,\nand enophthalmos. The anisocoria is more evident in dim light\nbecause the affected pupil fails to dilate.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1031), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s14 source, marked p.1031; printed_q 9. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 9, 45, 1031",
},

{ n:10, p:1032, key:0,
  stem:"An elderly patient presents with sudden visual loss, headache, jaw claudication, and scalp tenderness. Which investigation is most important to confirm the diagnosis?",
  opts:["ESR","CT brain","MRI orbit","Visual field testing"],
  expl:"Giant cell arteritis (temporal arteritis) presents with vision loss, jaw claudication, and scalp tenderness. ESR (and CRP) are crucial for diagnosis and should be checked immediately.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1033), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1033; printed_q 10. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 10, 1033",
},

{ n:11, p:1034, key:1,
  stem:"A 50-year-old patient presents with severe headache, nausea, and projectile vomiting. On ophthalmologic examination, bilateral blurred disc margins are noted. What is the most likely diagnosis?",
  opts:["Optic neuritis","Papilledema","Retinal detachment","Central retinal vein occlusion"],
  expl:"Bilateral blurred disc margins with symptoms of raised intracranial pressure indicate papilledema. It results from increased intracranial pressure causing optic disc swelling.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1035), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s14 source, marked p.1035; printed_q 11. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 11, 50, 1035",
},

{ n:12, p:1036, key:0,
  stem:"Most common cause of bilateral abducent nerve palsy?",
  opts:["Elevated intracranial pressure","Intracranial tumor","Trauma","Infection"],
  expl:"↑ Intracranial pressure causes downward traction on both abducens nerves as they run along the clivus, leading to bilateral abducent nerve palsy. It's the most common cause due to the long intracranial course of CN VI.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1037), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1037; printed_q 12. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 12, 1037",
},

{ n:13, p:1038, key:0,
  stem:"Cause of pinpoint pupil?",
  opts:["Organophosphorus poisoning","Mydriatics","Glaucoma","Horner syndrome"],
  expl:"Organophosphorus compounds inhibit acetylcholinesterase, leading to excess acetylcholine and constricted (pinpoint) pupils. Mydriatics and Horner syndrome cause dilated pupils instead.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1039), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1039; printed_q 13. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 13, 1039",
},

{ n:14, p:1040, key:0,
  stem:"A 60-year-old man reports sudden, transient, painless loss of vision in one eye lasting a few minutes, which resolved spontaneously. What is the most likely diagnosis?",
  opts:["Amaurosis fugax","Migraine without aura","Optic neuritis","Retinal detachment"],
  expl:"Amaurosis fugax is transient monocular vision loss caused by retinal ischemia, often from carotid artery emboli. Vision typically returns within minutes.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1041), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1041; printed_q 14. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 14, 60, one, 1041",
},

{ n:15, p:1042, key:0,
  stem:"A 65-year-old patient presents with sudden, painless, and persistent loss of vision in one eye. Fundus examination shows a pale retina with a swollen optic disc. What is the most likely diagnosis?",
  opts:["Anterior ischemic optic neuropathy","Central retinal vein occlusion","Optic neuritis","Retinal detachment"],
  expl:"This condition results from sudden interruption of blood supply to the optic nerve head, leading to a pale swollen disc and permanent vision loss. It is common in elderly patients with vascular risk factors.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1043), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1043; printed_q 15. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 15, 65, one, 1043",
},

{ n:16, p:1044, key:1,
  stem:"Which of the following is a condition characterized by tertiary syphilis with midbrain affection?",
  opts:["Horner syndrome","Argyll-Robertson syndrome","Oculomotor palsy","Dorsal midbrain syndrome"],
  expl:"Argyll-Robertson pupils → Tertiary syphilis with midbrain affection. It is bilateral (may be asymmetric). It is characterized by small irregular pupils with light-near dissociation. Investigations: serologic testing for syphilis and MRI of the brainstem.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1045), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s14 source, marked p.1045; printed_q 16. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 16, 1045",
},

{ n:17, p:1046, key:2,
  stem:"A 39-year-old male patient presented with unilateral miosis, lid drooping and apparent enophthalmos. Which of the following might be the cause for that presentation?",
  opts:["Dorsal midbrain syndrome","Argyll-Robertson syndrome","Horner syndrome","Oculomotor nerve palsy"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1047), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s14 source, marked p.1047; printed_q 17. NO explanation box printed; expl empty. Staging note: 17, 39, 1047",
},

{ n:18, p:1048, key:0,
  stem:"A 22-year-old male complains of double vision. Examination revealed esotropia, inability to abduct the left eye and face turn to the left side. which of the following is the most likely diagnosis?",
  opts:["Left abducent palsy","Left trochlear palsy","Right abducent palsy","Left abducent palsy"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1049), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1049; printed_q 18. NO explanation box printed; expl empty. Staging note: 18, 22, 1049",
},

{ n:19, p:1050, key:1,
  stem:"A 67-year-old female patient presented with acute unilateral diminished vision, jaw claudication and severe temporal headache. Which of the following is the most likely cause of that patient's condition?",
  opts:["Non-arteritic optic neuropathy","Anterior ischemic optic neuropathy","Optic neuritis","None of the above"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1051), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s14 source, marked p.1051; printed_q 19. NO explanation box printed; expl empty. Staging note: 19, 67, 1051",
},

{ n:20, p:1052, key:2,
  stem:"27-year-old female patient complains of lid drooping coupled with double vision. History revealed generalized weakness and fatigue. Ocular examination showed intact pupils with marked bilateral ptosis affection of ocular motility. Which of the following is the most probable diagnosis?",
  opts:["Oculomotor nerve palsy","Trochlear nerve palsy","Myasthenia gravis","Dorsal midbrain syndrome"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1053), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s14 source, marked p.1053; printed_q 20. NO explanation box printed; expl empty. Staging note: 20, 27, 1053",
},

{ n:21, p:1054, key:0,
  stem:"53 years old patient complaining of near vision problems. The patient is asthmatic and has some degree of heart block that is controlled medically. His visual acuity is 6/6 in both eyes. While examination you notice nuclear sclerosis in both eyes. IOP is 28 mmHg in his right eye and 30 mmHg in his left eye, the fundus examination revealed large cup/disc ratio in both eyes. You suspect that patient has POAG. What further tests will help you to confirm the diagnosis?",
  opts:["Visual field test","Fluoresceine angiography","Amsler grid test","OCT for macula"],
  expl:"Visual field testing detects the characteristic arcuate scotomas of glaucoma. It confirms functional loss from optic nerve damage.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1055), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s14 source, marked p.1055; printed_q 21. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 21, 53, 6/6, 28, 30, 1055",
},

{ n:22, p:1056, key:1,
  stem:"A 64-year-old man presented for evaluation of binocular horizontal diplopia that began 2 weeks earlier and was most bothersome when viewing at a distance. He noted that the diplopia was more prominent when he directed his gaze to the left but otherwise it was present “all the time.” He had a history of hypertension, diabetes mellitus, and dyslipidemia. On examination, of the patient’s left eye showed esodeviation and did not fully abduct, the fundus examination was normal. What is your diagnosis?",
  opts:["Myasthenia gravis","6th nerve palsy","3rd nerve palsy","Increase ICP"],
  expl:"Sixth nerve palsy causes horizontal diplopia and limited abduction due to lateral rectus weakness. It is often related to diabetes or hypertension.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1057), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s14 source, marked p.1057; printed_q 22. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 22, 64, 2, 6, 3, 1057",
},

{ n:23, p:1058, key:2,
  stem:"45-year-old woman comes to the emergency center because of severe left sided headache and double vision that began the night before, immediately following vigorous exercise. As you examine her, she continues to complain of severe left-sided headache. Her neuro-ophthalmologic examination is normal, except that the left upper eyelid is ptotic; and the left pupil is dilated 3 mm more than the right and responds very poorly to light. Her motility looks grossly normal.What is your diagnosis?",
  opts:["Myasthenia gravis","Optic nerve disease","Third nerve palsy","Diabetic neuropathy"],
  expl:"Ptosis with a dilated, poorly reactive pupil indicates parasympathetic involvement of the oculomotor (III) nerve. The normal motility suggests partial or early third nerve palsy, often due to aneurysm or vascular compression.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1059), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s14 source, marked p.1059; printed_q 23. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 23, 45, 3, 1059",
},

{ n:24, p:1060, key:3,
  stem:"A 34-year-old man presented to his family doctor complaining of some visual distortion, he had noticed in the past week intermittent period of double vision and mild ptosis, and then things went back to normal. He reported some difficulties in lifting things with his arm. He did not report any other neurologic symptoms. Ocular examination was normal except for mild ptosis appear with prolonged upgaze and improve with ice pack. What is the proper management for this case?",
  opts:["Assurance and follow up of the patient","CT orbit and lab investigation in form of T3, T4, and TSH","Topical steroid eye drops and follow up in one week.","Make an appointment with ophthalmology and neurology clinic"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1061), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":3,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 3 (d), from the staged s14 source, marked p.1061; printed_q 24. NO explanation box printed; expl empty. Staging note: 24, 34, 3, 4, one, 1061",
},

{ n:25, p:1062, key:1,
  stem:"45 years old woman presented to her family doctor complaining of diplopia. On examination there was retraction of upper eyelid of right eye, proptosis and limited ocular movement especially in up-gaze, with mild pain. Pupil of the right eye was slightly dilated and showed sluggish reaction to light compared to her left eye. What is your diagnosis?",
  opts:["Myasthenia gravis","Thyroid eye disease","3rd nerve palsy due to microvascular ischemic lesion","3rd nerve palsy due to aneurysm of the posterior communicating artery"],
  expl:"Proptosis, lid retraction, and restricted upgaze with mild pain are typical of thyroid eye disease due to autoimmune inflammation of extraocular muscles. The sluggish pupil helps rule out isolated nerve palsy.",
  boxPrinted:true,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1063), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s14 source, marked p.1063; printed_q 25. EXPLANATION BOX PRINTED -- expl transcribed verbatim from staged JSON, never from OCR. Staging note: 25, 45, 3, 3, 1063",
},

{ n:26, p:1064, key:3,
  stem:"A male patient 30 years old with visual acuity of 6/6 in both eyes. Twelve hours ago he presented with drop of vision of the left eye. On examination, visual acuity was 6/6 in the right eye and 6/60 in the left eye. Fundus examination showed blurred edges of the left optic disc. The most probable diagnosis is:",
  opts:["Raised intra cranial pressure","Raised ocular tension","Central retinal artery occlusion","Optic neuritis"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s14 source (oph-ep-p1-s14-neuro-ophthalmology.staging.json, marked p.1065), 2026-09-19, checked against the page image by two independent readers. Not re-derived by this script.",
  keypos:{"visualIndex":3,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 3 (d), from the staged s14 source, marked p.1065; printed_q 26. NO explanation box printed; expl empty. Staging note: 26, 30, 6/6, 6/6, 6/60, Twelve, 1065",
},

];
