var S08_DRAFT_CORNEA = [

{ id:"ophep-cornea-1", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"1. The cornea is composed of:", options:["3 layers","4 layers","5 layers","6 layers"],
  answer:2,
  explanation:"The cornea has five classic histological layers -- epithelium, Bowman's membrane, stroma, Descemet's membrane, and endothelium -- arranged from anterior to posterior, together forming the eye's clear, avascular refracting surface. Each layer contributes differently to strength, transparency, and the barrier function that protects the eye from infection.\n\n**The endpoint file prints this explanation:**\n> The cornea consists of five layers: epithelium, Bowman's membrane, stroma, Descemet's membrane, and endothelium. Each plays a role in maintaining transparency and refractive power.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"The cornea is composed of five layers: epithelium, Bowman's membrane, stroma, Descemet's membrane, and endothelium.",
  source:"Opthalmology endpoint.pdf p.581" },

{ id:"ophep-cornea-2", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"2. Regarding keratoconus:", options:["It presents by painless progressive diminution of vision but rapid drop of vision may also occur","Munson's sign occurs early in the disease","Pachymetry shows increased corneal thickness","Soft contact lenses may be used in moderate cases"],
  answer:0,
  explanation:"Keratoconus usually progresses slowly and painlessly as the cornea thins and steepens into an irregular, cone-shaped astigmatism, but a sudden drop in vision can occur if acute hydrops develops from a rupture in Descemet's membrane. Pachymetry in keratoconus shows progressive corneal thinning rather than thickening, and signs such as Munson's sign appear as the disease advances rather than early on; soft lenses lose their usefulness once the cornea becomes markedly irregular, when rigid or scleral lenses are needed instead.\n\n**The endpoint file prints this explanation:**\n> Keratoconus causes progressive, painless blurring due to corneal thinning and irregular astigmatism; acute hydrops can cause sudden vision drop. Corneal thinning (not thickening) is seen on pachymetry.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Keratoconus is usually painless and slowly progressive, but acute hydrops can cause a sudden drop in vision.",
  source:"Opthalmology endpoint.pdf p.583" },

{ id:"ophep-cornea-3", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"3. The keratometer is used to measure:", options:["Radius of curvature of the cornea","Thickness of the cornea","Diameter of the cornea","Clarity of the cornea"],
  answer:0,
  explanation:"A keratometer measures the anterior corneal curvature (radius of curvature), which is used to calculate corneal refractive power for contact lens fitting, intraocular lens power calculation, and detecting irregular astigmatism such as in keratoconus. It does not assess corneal thickness, diameter, or clarity -- those are measured respectively by pachymetry, direct caliper measurement, and slit-lamp examination.\n\n**The endpoint file prints this explanation:**\n> The keratometer (ophthalmometer) measures the anterior corneal curvature, which helps determine corneal power for contact lens fitting or intraocular lens calculation. Pachymetry measures thickness, not curvature.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"The keratometer measures the radius of curvature of the anterior cornea, not its thickness, diameter, or clarity.",
  source:"Opthalmology endpoint.pdf p.585" },

{ id:"ophep-cornea-4", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"4. Corneal blood staining is due to:", options:["Partial hyphema","Vitreous hemorrhage","Total hyphema","Total hyphema with prolonged rise in IOP"],
  answer:3,
  explanation:"Corneal blood staining is a complication of hyphema, occurring when red blood cells and haemoglobin breakdown products infiltrate the corneal stroma through the endothelium. This requires both a large, longstanding (typically total) hyphema and a sustained rise in intraocular pressure, which damages the endothelial pump and allows blood products to diffuse into the cornea; a partial hyphema or a normal-pressure hyphema alone does not produce it.\n\n**The endpoint file prints this explanation:**\n> Corneal blood staining occurs when total hyphema is accompanied by persistently high intraocular pressure, forcing red cells and hemoglobin into the cornea.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Corneal blood staining requires total hyphema combined with a prolonged rise in intraocular pressure.",
  source:"Opthalmology endpoint.pdf p.587" },

{ id:"ophep-cornea-5", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"5. The anterior chamber is abnormally deep in EXCEPT:", options:["Aphakia","Congenital glaucoma","Keratoconus","Perforated corneal ulcer"],
  answer:3,
  explanation:"The anterior chamber deepens whenever the iris-lens diaphragm moves posteriorly or the globe enlarges, and shallows whenever aqueous is lost or the diaphragm moves forward. Aphakia removes the lens and deepens the chamber; congenital glaucoma raises intraocular pressure and enlarges the globe (buphthalmos), also deepening it; and keratoconus, through progressive corneal thinning and forward protrusion, likewise increases anterior chamber depth. A perforated corneal ulcer instead causes aqueous leakage, so the chamber shallows or collapses rather than deepens, making it the exception.\n\n**The endpoint file prints this explanation:**\n> •Aphakia: Absence of the lens increases the anterior chamber depth.\n> •Congenital glaucoma: Elevated intraocular pressure enlarges the globe and deepens the anterior chamber.\n> •Keratoconus: Corneal thinning and protrusion result in a deeper anterior chamber.\n> •Perforated corneal ulcer: Causes leakage of aqueous humor, leading to a shallow or collapsed anterior chamber\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"A perforated corneal ulcer shallows the anterior chamber through aqueous leakage, unlike aphakia, congenital glaucoma, or keratoconus, which all deepen it.",
  source:"Opthalmology endpoint.pdf p.589" },

{ id:"ophep-cornea-6", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"6. Deficiency of which vitamin can cause corneal ulcers?", options:["Vitamin A","Vitamin C","Vitamin D","Vitamin E"],
  answer:0,
  explanation:"Vitamin A is essential for maintaining the corneal and conjunctival epithelium; its deficiency causes xerophthalmia, with conjunctival and corneal dryness, Bitot's spots, and keratomalacia, in which the softened cornea ulcerates and can melt. This remains an important cause of preventable blindness in malnourished children, and severe deficiency can progress rapidly to corneal perforation if untreated.\n\n**The endpoint file prints this explanation:**\n> Vitamin A deficiency causes xerophthalmia and keratomalacia, leading to corneal ulceration. It is common in malnutrition and can cause permanent blindness if untreated.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Vitamin A deficiency causes xerophthalmia and keratomalacia, which can progress to corneal ulceration and blindness.",
  source:"Opthalmology endpoint.pdf p.591" },

{ id:"ophep-cornea-7", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"7. A 45-year-old patient presents with severe facial pain and vesicular rash on the face. Involvement of which area indicates that the eye might also be affected?", options:["Tip of the nose","Cheek","Forehead","Earlobe"],
  answer:0,
  explanation:"In herpes zoster ophthalmicus, the virus reactivates in the ophthalmic (V1) division of the trigeminal nerve, which also supplies the nasociliary branch and, through it, the tip and side of the nose. Vesicles on the tip of the nose -- Hutchinson's sign -- indicate nasociliary nerve involvement and predict a substantially higher risk of ocular complications such as keratitis, uveitis, and scleritis, so their presence should prompt closer ophthalmic monitoring; involvement of the cheek, forehead, or earlobe does not carry this same implication.\n\n**The endpoint file prints this explanation:**\n> Involvement of the tip of the nose indicates Hutchinson's sign, showing nasociliary nerve involvement in herpes zoster ophthalmicus. This increases the risk of ocular complications.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Hutchinson's sign -- zoster vesicles on the tip of the nose -- signals nasociliary nerve involvement and a high risk of ocular complications.",
  source:"Opthalmology endpoint.pdf p.593" },

{ id:"ophep-cornea-8", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"8. A 30-year-old woman presents with sudden ocular pain after her 6-month-old child accidentally scratched her eye with a fingernail. What is the most appropriate immediate treatment?", options:["Topical antibiotics","Topical steroids","Observation","Cycloplegics"],
  answer:0,
  explanation:"A fingernail scratch typically produces a corneal abrasion, an epithelial defect at risk of secondary bacterial infection because the epithelial barrier has been breached. The appropriate immediate treatment is a topical antibiotic to prevent infective keratitis while the epithelium re-heals; topical steroids are avoided because they delay epithelial healing, and simple observation or cycloplegics alone do not address the infection risk, though a cycloplegic may be added for comfort.\n\n**The endpoint file prints this explanation:**\n> A corneal abrasion from a fingernail increases infection risk; thus, topical antibiotics are given to prevent bacterial keratitis. Steroids are contraindicated as they delay healing.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"A corneal abrasion is treated with topical antibiotics to prevent infection; steroids are avoided because they delay healing.",
  source:"Opthalmology endpoint.pdf p.595" },

{ id:"ophep-cornea-9", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"9. A 7-year-old boy with Down syndrome shows an angulation of the lower eyelid when looking downward. What is the name of this clinical sign?", options:["Munson's sign","Arlt's line","Kayser-Fleischer ring","Hutchinson sign"],
  answer:0,
  explanation:"Munson's sign is the V-shaped angulation, or tenting, of the lower eyelid margin produced when a patient with keratoconus looks down, caused by the conical, forward-protruding cornea pushing against the lid. It is a classic, if late, external sign of keratoconus, a condition with a recognised association with Down syndrome (in part from chronic eye rubbing). Arlt's line is a scarring line seen in trachoma, the Kayser-Fleischer ring is a copper deposit in Wilson's disease, and Hutchinson's sign relates to herpes zoster ophthalmicus -- none of these describe lower-lid angulation on downgaze.\n\n**The endpoint file prints this explanation:**\n> Munson's sign is the V-shaped indentation of the lower eyelid in downgaze seen in keratoconus. It occurs due to forward protrusion of the conical cornea.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Munson's sign -- V-shaped lower lid angulation on downgaze -- is caused by the conical cornea of keratoconus.",
  source:"Opthalmology endpoint.pdf p.597" },

{ id:"ophep-cornea-10", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"10. A 25-year-old woman presents with eye pain, tearing, and photophobia. She has a history of contact lens use. Fluorescein staining shows a corneal ulcer. What is she at risk for?", options:["Corneal perforation","Cataract","Glaucoma","Retinal detachment"],
  answer:0,
  explanation:"A contact-lens wearer with a fluorescein-positive corneal ulcer is at particular risk of microbial keratitis progressing to corneal melting and perforation, since contact lens wear predisposes to aggressive organisms such as Pseudomonas, which can cause a descemetocele and perforation within 24-48 hours if untreated. Perforation, in turn, risks endophthalmitis and permanent vision loss, which is why such ulcers are treated as an emergency; cataract, glaucoma, and retinal detachment are not the direct complications of an active corneal ulcer.\n\n**The endpoint file prints this explanation:**\n> A corneal ulcer, especially in contact lens users, can progress to perforation if untreated. This may lead to endophthalmitis and vision loss.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"An untreated corneal ulcer in a contact lens wearer risks progression to corneal perforation.",
  source:"Opthalmology endpoint.pdf p.599" },

{ id:"ophep-cornea-11", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"11. A young boy with Down syndrome presents to the ophthalmologist with conical protrusion and thinning of the cornea. Which of the following is a useful tool for decision making and management of that patient?", options:["Amsler's grid","CT orbit","Pentacam","None of the above"],
  answer:2,
  explanation:"In a young patient with keratoconus, corneal topography maps the curvature to demonstrate the classic asymmetric, inferior-steepening bowtie pattern, and pachymetry quantifies the corneal thinning; the Pentacam combines both of these (Scheimpflug-based topography and pachymetry) into a single device, and adds further anterior and posterior segment data that helps guide decisions such as suitability for collagen cross-linking, contact lenses, or keratoplasty. An Amsler's grid instead tests for central visual field distortion from macular disease, and CT orbit has no role in managing corneal ectasia.\n\n**The endpoint file prints this explanation:**\n> Investigations of keratoconus → Corneal topography (Map of corneal curvature is diagnostic), Pachymetry (measurement of the corneal thickness) & Pentacam (It gives, in addition to both topography and corneal thickness data, other data that help decision making and management of KC).\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"The Pentacam combines corneal topography and pachymetry data and is a key tool for keratoconus decision-making and management.",
  source:"Opthalmology endpoint.pdf p.601" },

{ id:"ophep-cornea-12", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"12. Which of the following is used to detect corneal abrasions?", options:["Flourescine dye","Steroids","Pachymetry","None of the above"],
  answer:0,
  explanation:"Fluorescein dye is a vital stain that pools in areas where the corneal epithelium has been breached, such as an abrasion, and fluoresces under cobalt-blue light, making the defect visible at the slit lamp. Steroids and pachymetry play no role in detecting an abrasion -- steroids are a treatment (and are generally contraindicated in epithelial defects), while pachymetry measures corneal thickness rather than surface integrity.\n\n**The endpoint file prints this explanation:**\n> Corneal epithelial defects (e.g. abrasions) are demonstrated by staining with 1% fluorescein sodium and viewing with cobalt blue filtered light.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Fluorescein staining under cobalt-blue light is used to detect corneal abrasions.",
  source:"Opthalmology endpoint.pdf p.603" },

{ id:"ophep-cornea-13", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"13. Which of the following is among the side effects that accompany the use of local anaesthetics?", options:["Corneal epithelial defect","Keratoconus","Corneal opacification","Retinal detachment"],
  answer:0,
  explanation:"Topical local anaesthetics numb the cornea but also inhibit epithelial healing and, with repeated or prolonged use, can cause a toxic anaesthetic keratopathy with persistent epithelial defects and stromal melting. Because of this, they are never prescribed for ongoing outpatient analgesia and are specifically avoided in conditions such as photokeratitis, where they would delay the epithelium's own recovery. They do not cause keratoconus, corneal opacification as a primary effect, or retinal detachment.\n\n**The endpoint file prints this explanation:**\n> Local anesthetics cause corneal epithelial defects; this is why they are not advised during the treatment of photokeratitis (as they delay the healing process by causing corneal epithelial defects)\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Topical anaesthetics cause corneal epithelial defects and delay healing, so they are never used for ongoing analgesia.",
  source:"Opthalmology endpoint.pdf p.605" },

{ id:"ophep-cornea-14", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"14. What is the initial management in case of chemical eye burn?", options:["Neutralization","Copious irrigation","Antibiotics","Eye patching"],
  answer:1,
  explanation:"The correct initial management of a chemical eye burn is immediate, copious irrigation with saline or water -- begun before any detailed examination, history-taking, or referral -- to dilute and remove the offending agent as quickly as possible, followed by a pH check to confirm neutrality. Neutralising agents are not used, since the reaction can add further chemical or thermal injury; antibiotics and patching have no role in this immediate phase.\n\nThe endpoint file's printed explanation box for this row does not answer this stem -- it describes management of an intra-ocular foreign body (also copious irrigation as an initial step, but for an unrelated presentation) rather than a chemical burn. This is a source mismatch, not evidence against copious irrigation being correct for a chemical burn: irrigation is in fact also the correct first step there.\n\n**The endpoint file prints this explanation:**\n> The initial management of a case presenting with an intra-ocular foreign body is copious irrigation. However, the definitive management of that case is surgical removal of the foreign body.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Immediate copious irrigation, not neutralization, antibiotics, or patching, is the initial management of a chemical eye burn.",
  source:"Opthalmology endpoint.pdf p.607" },

{ id:"ophep-cornea-15", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"15. What is the grade of chemical eye injury that is characterized by total loss of corneal epithelium and stromal haze obscuring iris details?", options:["Grade 1","Grade 2","Grade 3","Grade 4"],
  answer:2,
  explanation:"Chemical eye injuries are graded by the degree of corneal clouding and limbal ischaemia, which together predict prognosis. Grade 3 injury is defined by total loss of the corneal epithelium with stromal haze severe enough to obscure iris detail, together with one-third to one-half of the limbus showing ischaemia -- worse than Grade 1 (clear cornea, no ischaemia) and Grade 2 (hazy cornea but visible iris detail, under 30% ischaemia), and better than Grade 4 (opaque cornea, over 50% ischaemia), giving Grade 3 a guarded rather than good or poor prognosis.\n\n**The endpoint file prints this explanation:**\n> Grading of chemical eye injuries →\n> A. Grade 1: (excellent prognosis): Clear cornea (epithelial damage only) and no limbal ischaemia.\n> B. Grade 2: (good prognosis): Hazy cornea but with visible iris detail and less than 30% limbal ischaemia.\n> C. Grade 3: (guarded prognosis):\n> ● Total loss of corneal epithelium.\n> ● Stromal haze obscuring iris detail.\n> 1/3 to 1/2 limbal ischaemia.\n> D. Grade 4: (poor prognosis):\n> ● Opaque cornea.\n> ● More than 50% limbal ischaemia.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Grade 3 chemical eye injury shows total epithelial loss with stromal haze obscuring iris detail and one-third to one-half limbal ischaemia, carrying a guarded prognosis.",
  source:"Opthalmology endpoint.pdf p.609" },

{ id:"ophep-cornea-16", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"16. A patient with iridocyclitis was found to have WBC clumps on the back surface of the cornea. Which of the following might occur as a complication of that condition?", options:["Glaucoma","Anterior synechiae","Hypotony","Corneal erosions"],
  answer:0,
  explanation:"Keratic precipitates -- clumps of inflammatory cells deposited on the corneal endothelium -- are a sign of anterior uveitis (iridocyclitis). Chronic or recurrent anterior uveitis can be complicated by secondary glaucoma (from trabecular blockage by inflammatory cells or synechiae), posterior synechiae, complicated cataract, band keratopathy, and cystoid macular oedema. Anterior synechiae, hypotony, and corneal erosions are not the complications listed for this condition in this material.\n\n**The endpoint file prints this explanation:**\n> Anterior uveitis can be complicated by 2ry glaucoma, Posterior synechiae, Complicated cataract, Calcific band keratopathy (if the iritis becomes chronic) especially in juvenile idiopathic arthritis & Macular oedema (if the iritis becomes chronic).\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Anterior uveitis with keratic precipitates can be complicated by secondary glaucoma, among other listed sequelae.",
  source:"Opthalmology endpoint.pdf p.611" },

{ id:"ophep-cornea-18", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"18. Herpes simplex virus can cause all of the following ocular conditions except?", options:["Blepharitis","Keratitis","Scleritis","lridocyclitis"],
  answer:2,
  explanation:"Herpes simplex virus produces a broad spectrum of ocular disease: it can cause blepharitis (vesicular lid lesions), keratitis (both epithelial dendritic/geographic disease and stromal keratitis), and iridocyclitis as part of its stromal and immune-mediated involvement of the anterior segment. Scleritis is not a recognised herpes simplex association in this material -- scleritis and episcleritis instead appear as complications of herpes zoster ophthalmicus, which affects the ophthalmic trigeminal division more broadly rather than herpes simplex specifically, so scleritis is the exception here (this HSV-versus-scleritis distinction is outside knowledge -- not taken from the course material).\n\nWritten for this bank — Opthalmology endpoint.pdf prints no explanation here.",
  objective:"Herpes simplex virus causes blepharitis, keratitis, and iridocyclitis, but scleritis is not a recognised association.",
  source:"Opthalmology endpoint.pdf p.615" },

{ id:"ophep-cornea-19", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"19. Which of the following is the use of Seidel test?", options:["To detect corneal scarring","To detect corneal perforation","To detect corneal foreign body","All of the above"],
  answer:1,
  explanation:"The Seidel test uses concentrated fluorescein dye applied to a suspected corneal wound: if the globe is perforated, aqueous humour leaking from the wound dilutes the concentrated dye, producing a visible stream of lighter green fluorescence against the darker orange background stain -- a positive result. It is used specifically to detect corneal (or scleral) perforation and active aqueous leakage, not to assess corneal scarring or locate a foreign body (the Seidel test itself is not named in the lecture material -- not taken from the course material).\n\nWritten for this bank — Opthalmology endpoint.pdf prints no explanation here.",
  objective:"The Seidel test uses fluorescein dilution by leaking aqueous to detect corneal perforation.",
  source:"Opthalmology endpoint.pdf p.617" },

{ id:"ophep-cornea-20", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"20. Which of the following is the most important and prevalent complication of herpes zoster ophthalmicus?", options:["Cicatrisation of skin","Postherpetic neuralgia","Limbal atrophy","Vision loss"],
  answer:1,
  explanation:"Herpes zoster ophthalmicus can cause epithelial and disciform keratitis, neurotrophic keratopathy, scleritis, and episcleritis, but postherpetic neuralgia -- persistent pain in the affected dermatome after the rash resolves -- is its most prevalent long-term complication overall. The lecture lists postherpetic neuralgia among HZO's long-term complications alongside neurotrophic corneal anaesthesia; ranking it as the single most prevalent complication specifically reflects general epidemiology and is not itself ranked in the lecture (not taken from the course material for that specific ranking). Skin cicatrisation, limbal atrophy, and vision loss are recognised but less prevalent overall.\n\nWritten for this bank — Opthalmology endpoint.pdf prints no explanation here.",
  objective:"Postherpetic neuralgia is the most prevalent long-term complication of herpes zoster ophthalmicus.",
  source:"Opthalmology endpoint.pdf p.619" },

{ id:"ophep-cornea-21", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"21. A 21-year-old male patient complains of diminshed vision in the left eye. Examination revealed positive Munson's sign in the affected eye. Which of the following is the most likely diagnosis?", options:["Herpes zoster ophthalmicus","Calcific band keratopathy","Photokeratitis","Keratoconus","Corneal ulcer"],
  answer:3,
  explanation:"Munson's sign -- a V-shaped tenting of the lower eyelid on downgaze -- is produced by the forward, conical protrusion of the cornea characteristic of keratoconus, and its presence in a young adult with progressive, unilateral or asymmetric vision loss strongly supports that diagnosis. Herpes zoster ophthalmicus presents with dermatomal facial vesicles rather than this sign; calcific band keratopathy shows chalky corneal deposits; photokeratitis follows UV exposure with acute pain; and a corneal ulcer would typically show pain, redness, and fluorescein-positive epithelial loss rather than a lid sign, making keratoconus the diagnosis this sign points to.\n\nWritten for this bank — Opthalmology endpoint.pdf prints no explanation here.",
  objective:"Munson's sign, a lower lid V-shaped deformity on downgaze, points to keratoconus.",
  source:"Opthalmology endpoint.pdf p.621" },

{ id:"ophep-cornea-22", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"22. A 38-year-old male patient complains of eye pain, excessive tearing and redness. History is significant for severe unilateral facial pain that was followed by appearance of skin vesicles. Which of the following is the most likely diagnosis?", options:["Herpes simplex keratitis","Herpes zoster ophthalmicus","Calcific band keratopathy","Exposure keratopathy","Geronotoxon"],
  answer:1,
  explanation:"Severe unilateral facial pain followed by a vesicular skin rash, together with eye pain, tearing, and redness, is the classic presentation of herpes zoster ophthalmicus: reactivation of varicella-zoster virus in the ophthalmic (V1) trigeminal division produces a dermatomal vesicular eruption with accompanying ocular inflammation. Herpes simplex keratitis instead classically presents with a dendritic corneal ulcer without a preceding dermatomal facial rash; calcific band keratopathy and exposure keratopathy are chronic, non-eruptive conditions; and Geronotoxon (arcus senilis) is an asymptomatic lipid ring -- none of these fit this acute vesicular presentation.\n\nWritten for this bank — Opthalmology endpoint.pdf prints no explanation here.",
  objective:"Unilateral facial pain followed by vesicular rash with ocular involvement indicates herpes zoster ophthalmicus.",
  source:"Opthalmology endpoint.pdf p.623" },

{ id:"ophep-cornea-23", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"23. A 65-year-old man visits the ophthalmologist with a complaint of noticing a brown ring in both eyes. From history, there was no blurred vision or any other complaint. Examination revealed bilateral grayish brown ring around the limbus and separated from the limbus by a clear scleral zone. Which of the following would be the most important next step to do for such a patient?", options:["Urgent surgery","CT orbit","Lipid profile and reassurance","Massive steroid administration","Ophthalmoscopic examination"],
  answer:2,
  explanation:"A bilateral, grayish-brown ring at the limbus, separated from it by a clear zone of normal sclera, in an asymptomatic elderly patient is the classic description of arcus senilis, a lipid deposit in the peripheral cornea that is a physiological ageing change rather than a sight-threatening disease. The most useful next step is to check a lipid profile, since arcus can still reflect an underlying lipid disorder, and reassure the patient, rather than pursue invasive or unrelated investigations such as urgent surgery, CT orbit, ophthalmoscopy for this finding, or steroids, none of which have a role here.\n\nWritten for this bank — Opthalmology endpoint.pdf prints no explanation here.",
  objective:"A grayish-brown limbal ring with a clear scleral zone in an elderly patient is arcus senilis, managed with a lipid profile and reassurance.",
  source:"Opthalmology endpoint.pdf p.625" },

{ id:"ophep-cornea-24", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"24. A 29-year-old woman complains of eye redness, pain and blurred vision. After staining with fluorescein, examination revealed a dendritic ulcer in the affected eye. Which of the following is absolutely contraindicated in the treatment of that patient?", options:["Topical antiviral medications","Topical steroids","Prophylactic antibiotics","All of the above"],
  answer:1,
  explanation:"A dendritic ulcer on fluorescein staining is the hallmark of epithelial herpes simplex keratitis, caused by active viral replication within the corneal epithelium. Topical steroids are absolutely contraindicated at this stage because they suppress the local immune response and allow the virus to replicate further, which can convert a simple dendritic ulcer into a much larger, more destructive geographic ulcer and risk corneal perforation. Topical antivirals are the correct treatment, and prophylactic antibiotics, while sometimes added to prevent secondary bacterial infection, are not themselves contraindicated.\n\nWritten for this bank — Opthalmology endpoint.pdf prints no explanation here.",
  objective:"Topical steroids are absolutely contraindicated in epithelial (dendritic) herpes simplex keratitis because they worsen viral replication.",
  source:"Opthalmology endpoint.pdf p.627" },

{ id:"ophep-cornea-25", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"25. 54-year-old woman with a red, painful eye and the patient is complaining of photophobia. When you examine her, you note that visual acuity is decreased in the affected eye and cornea appears opaque and hazy with positive fluoresceine staining.What is the most likely diagnosis?", options:["Conjunctivitis","Corneal ulcer","Old corneal scar","Scleritis"],
  answer:1,
  explanation:"A red, painful eye with photophobia, decreased vision, and a cornea that appears opaque and hazy with positive fluorescein staining describes an active corneal ulcer: the epithelial defect over an infiltrate takes up fluorescein dye, and the associated stromal inflammation causes the haze and pain. This picture is distinct from simple conjunctivitis (which spares the cornea and vision), an old corneal scar (not painful or acutely photophobic), and scleritis (in which corneal fluorescein staining is typically negative), so corneal ulcer is the diagnosis, requiring prompt antimicrobial therapy.\n\n**The endpoint file prints this explanation:**\n> A corneal ulcer presents with pain, photophobia, decreased vision, and fluorescein uptake. It requires urgent antimicrobial therapy.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Pain, photophobia, decreased vision, and fluorescein-positive corneal haze indicate a corneal ulcer requiring urgent antimicrobial therapy.",
  source:"Opthalmology endpoint.pdf p.629" },

{ id:"ophep-cornea-26", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"26. 54-year-old woman with a red, painful eye and the patient is complaining of photophobia. When you examine her, you note that visual acuity is decreased in the affected eye and cornea appears opaque and hazy with positive fluoresceine staining. regarding your management, which of the following should be avoided?", options:["Intensive topical antimicrobial eye drops","Topical cycloplegic eye drops","Scraping for culture and sensitivity","Topical steroid therapy"],
  answer:3,
  explanation:"In managing this corneal ulcer, topical steroid therapy should be avoided until the infection is controlled, since steroids suppress the local immune response and can potentiate the infecting organism, delay epithelial healing, and worsen the corneal damage. Intensive topical antimicrobials remain the mainstay of treatment, cycloplegics are used for comfort and to prevent synechiae, and scraping for culture and sensitivity should be performed before starting therapy to guide and confirm the choice of antimicrobial -- none of these should be withheld, unlike steroids.\n\n**The endpoint file prints this explanation:**\n> Management to avoid in corneal ulcer → (D) Topical steroid therapy\n> Steroids delay healing and can worsen corneal infections. The mainstay is topical antibiotics and supportive care.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"Topical steroid therapy should be avoided in an active corneal ulcer because it can worsen the infection and delay healing.",
  source:"Opthalmology endpoint.pdf p.631" },

{ id:"ophep-cornea-27", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"27. 45-year-old man reports a 2-day history of redness, pain, and photophobia of his left eye. He denies any trauma to the eye, fluoresceine staining reveals dendritic corneal ulcer.\nManagement would consist of which of the following?", options:["Topical antiviral like acyclovir","Topical steroid therapy","Topical antibiotics","Assurance and follow-up in one week"],
  answer:0,
  explanation:"A short history of unilateral redness, pain, and photophobia with a dendritic ulcer on fluorescein staining, without a history of trauma, is characteristic of herpes simplex epithelial keratitis. The correct management is a topical antiviral such as acyclovir, since active viral replication in the epithelium is driving the ulcer; topical steroids are avoided because they promote viral replication and worsen the ulcer, plain topical antibiotics do not treat a viral infection, and simple reassurance risks progression to a larger geographic ulcer or perforation.\n\n**The endpoint file prints this explanation:**\n> Herpes simplex keratitis is treated with topical antivirals, not steroids. Steroids can exacerbate viral replication.\n\n*The expansion above this line is written for this bank; the box itself is the endpoint file’s own.*",
  objective:"A dendritic corneal ulcer without trauma is treated with topical antivirals such as acyclovir, never topical steroids.",
  source:"Opthalmology endpoint.pdf p.633" },

{ id:"ophep-cornea-28", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"28. A 35-year-old man complains of pain in his right eye for several days, watering, photophobia, and blurring of vision. These symptoms are recurrent. He also had an acute attack of the common cold the week before. The most probable cause is:", options:["Catarrhal conjunctivitis","Dendritic ulcer","Chronic dacryocystitis","Acute angle closure glaucoma"],
  answer:1,
  explanation:"Recurrent unilateral eye pain, watering, photophobia, and blurred vision are typical of recurrent herpes simplex epithelial (dendritic) keratitis, which relapses over a patient's lifetime once latency is established in the trigeminal ganglion. A preceding systemic illness such as a common cold is a recognised trigger for reactivation of latent herpes simplex virus (not taken from the course material), fitting this recurrent pattern better than catarrhal conjunctivitis (not typically recurrent in this way), chronic dacryocystitis (which presents with epiphora and a discharging punctum rather than these symptoms), or acute angle-closure glaucoma (an acute presentation with a fixed mid-dilated pupil and markedly raised pressure, not a recurrent course).\n\nWritten for this bank — Opthalmology endpoint.pdf prints no explanation here.",
  objective:"Recurrent eye pain and photophobia following an intercurrent illness suggest reactivation of herpes simplex dendritic keratitis.",
  source:"Opthalmology endpoint.pdf p.635" },

{ id:"ophep-cornea-29", bank:"endpoint", module:"ophtho", chapter:"op-cornea",
  stem:"29. A farmer suffered eye trauma from a tree branch, followed by photophobia and lacrimation. Examination of the cornea showed stromal infiltration. The etiological diagnosis is reached by:", options:["Fluorescein staining","Tonometry","Corneal biopsy","Corneal topography"],
  answer:0,
  explanation:"Plant or vegetable matter trauma is a classic risk factor for fungal keratitis, which often presents with photophobia, lacrimation, and stromal infiltration (feathery or satellite lesions) rather than a rapidly aggressive picture. Establishing the etiological diagnosis of an infective keratitis -- identifying the causative organism -- is properly done by corneal scraping with Gram stain and culture, extended incubation on Sabouraud agar for suspected fungal cases, and confocal microscopy in difficult cases; fluorescein staining only demonstrates the presence and extent of an epithelial defect over the infiltrate rather than identifying the organism, tonometry measures pressure, and corneal topography assesses curvature. The endpoint file's printed key for this row is fluorescein staining; that finding supports recognising that keratitis is present, but the organism-identifying step described here is scraping and culture rather than fluorescein staining -- the key is transcribed as printed, and this mismatch is noted rather than disputed.\n\nWritten for this bank — Opthalmology endpoint.pdf prints no explanation here.",
  objective:"Plant trauma with stromal infiltration is a classic setup for fungal keratitis, whose organism is properly identified by corneal scraping and culture rather than fluorescein staining.",
  source:"Opthalmology endpoint.pdf p.637" },

];
