/* OCR-backed staging record. Generated from the staged s07 source
   (s07-gemini-text.txt: Gemini vision on the rendered page images, cross-checked
   against independent OCR text for all 13 pages with zero unexplained mismatches).
   Source pairs: unmarked p.534 through marked p.559.
   KEY CONVENTION: 0-based. `key` is an index into `opts` -- 0=A/a, 1=B/b,
   2=C/c, 3=D/d, 4=E/e -- taken directly from the staged s07 JSON key_index.
   The JSON "page" is the MARKED page; `p` is the row's own UNMARKED page
   (p = page - 1; unmarked = 532+2n, marked = 533+2n for n:1..13).
   No separate keypos source for s7 (sec-oph.js ans:null) -- keyposIndex and
   agree are null; visualIndex is the staged key_index.
   `expl` is verbatim only for boxed rows (box_printed true, n:1-n:4); all other
   rows keep expl empty. `boxPrinted` mirrors the staged box_printed per row. */

var OPHEP_S07_STAGED = [

{ n:1, p:534, key:2,
  stem:"Which of the following is useful to differentiate between episcleritis and scleritis?",
  opts:["Phenylephrine 2.5% drops","Phenylephrine 5% drops","Phenylephrine 10% drops","Phenylephrine 20% drops"],
  expl:"Phenylephrine 10% causes blanching of superficial vessels in episcleritis but not in scleritis. This helps differentiate the two conditions clinically.",
  boxPrinted:true,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from s07-gemini-text.txt, never from OCR. no separate keypos source for s7 (sec-oph.js ans:null) Thematic overlap: n:1 and n:2 both test episcleritis-vs-scleritis differentiation with phenylephrine but with different option sets and different question angles -- NOT duplicates, no fold needed; both transcribed normally.",
},

{ n:2, p:536, key:0,
  stem:"To differentiate between scleritis and episcleritis, which test is used?",
  opts:["Phenylephrine 10%","Fluorescein staining","Schirmer test","Tonometry"],
  expl:"In episcleritis, the superficial vessels blanch with phenylephrine drops, while in scleritis, deeper vessels do not. This test helps distinguish between the two inflammatory conditions.",
  boxPrinted:true,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 0 (a), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from s07-gemini-text.txt, never from OCR. no separate keypos source for s7 (sec-oph.js ans:null) Thematic overlap: n:1 and n:2 both test episcleritis-vs-scleritis differentiation with phenylephrine but with different option sets and different question angles -- NOT duplicates, no fold needed; both transcribed normally.",
},

{ n:3, p:538, key:2,
  stem:"Which of the following conditions has the worst prognosis?",
  opts:["Diffuse scleritis","Nodular scleritis","Necrotizing scleritis","Episcleritis"],
  expl:"Necrotizing anterior scleritis is the most severe form of scleritis:\nCharacterized by severe pain and extreme scleral tenderness.\nWith or without necrosis and exposure of the choroid.\nScleromalacia perforans is a rare form of necrotizing anterior scleritis without pain.",
  boxPrinted:true,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 2 (c), from the staged s07 source (s07-gemini-text.txt); not re-derived here. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from s07-gemini-text.txt, never from OCR. no separate keypos source for s7 (sec-oph.js ans:null)",
},

{ n:4, p:540, key:2,
  stem:"Bluish discoloration of the eye sclera occurs in which of the following conditions?",
  opts:["Scleritis","Episcleritis","Osteogenesis imperfecta","Scleral tumor"],
  expl:"The sclera is whitish in colour but can attain a bluish discolouration due to thinning and subsequent transparency of scleral collagen, which allows increased visibility of underlying choroidal pigment. This can be seen in some conditions such as:\nMarfan syndrome.\nOsteogenesis imperfecta.\nBuphthalmos.",
  boxPrinted:true,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 2 (c), from the staged s07 source (s07-gemini-text.txt); not re-derived here. EXPLANATION BOX PRINTED per staged source -- expl transcribed verbatim from s07-gemini-text.txt, never from OCR. no separate keypos source for s7 (sec-oph.js ans:null)",
},

{ n:5, p:542, key:2,
  stem:"A 50-year-old man presents to the GP with a complaint of severe eye pain, redness and decreased vision. Examination was carried out and it revealed that the redness had violet-bluish hue with scleral edema. Phenylephrine 10% was used topically for a few minutes but the redness didn't disappear. Which of the following would be the most appropriate next step in order to properly treat that patient?",
  opts:["Conservative management as It is a self-limited condition","Massive doses of steroids","Urgent referral to an ophthalmologist","Broad spectrum antibiotics"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. no separate keypos source for s7 (sec-oph.js ans:null)",
},

{ n:6, p:544, key:2,
  stem:"A 35-year-old woman has a significant history of recurrent episcleritis. Which of the following would be most appropriate to do for this patient?",
  opts:["Prescribe steroids","Increase the dose of NSAIDs","Look for an underlying systemic inflammatory disease","Hospitalize and monitor closely"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. no separate keypos source for s7 (sec-oph.js ans:null)",
},

{ n:7, p:546, key:2,
  stem:"Which of the following eye conditions has the highest risk of retinal detachment and subsequent vision loss?",
  opts:["Episcleritis","Anterior scleritis","Posterior scleritis","Conjunctivitis"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 2 (c), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. no separate keypos source for s7 (sec-oph.js ans:null)",
},

{ n:8, p:548, key:0,
  stem:"Anterior scleritis is characterized by all of the following except?",
  opts:["Inflammation occurs anterior to origin of rectus muscles","It's more common than posterior scleritis","It may be either diffuse, nodular or necrotizing","None of the above"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. no separate keypos source for s7 (sec-oph.js ans:null) Direct human-verified page-image read (no vision or OCR) confirms option A verbatim reads \"Inflammation occurs anterior to origin of rectus muscles\"; transcribe exactly as printed even though the medical convention defines the anterior/posterior scleritis boundary at the rectus muscle insertion, not origin -- this wording mismatch is WHY option A is the correct except/false answer, not a transcription error to fix. Medical soundness of the key (A/index 0) checked and confirmed sound.",
},

{ n:9, p:550, key:1,
  stem:"How can you differentiate between episcleritis and conjunctivitis?",
  opts:["Using phenylephrine 2.5%, redness disappears in episcleritis","Using phenylephrine 2.5%, redness disappears in conjunctivitis","Using phenylephrine 10%, redness disappears in episcleritis","Using phenylephrine 10%, redness disappears in conjunctivitis"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 1 (b), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. no separate keypos source for s7 (sec-oph.js ans:null) Structural similarity: n:9 and n:11 share the same stem template (\"How can you differentiate between episcleritis and X, using phenylephrine 2.5%/10%\") but compare episcleritis to a DIFFERENT condition each (conjunctivitis vs. scleritis) and their option sets differ in 2 of 4 entries -- NOT an exact or near-miss shared menu (validator threshold is exactly-one-entry-different), so no forced cross-reference; both transcribed normally for the human reviewer.",
},

{ n:10, p:552, key:1,
  stem:"Which of the following has the worst prognosis ever?",
  opts:["Episcleritis","Scleritis","Conjunctivitis","Subconjunctival hemorrhage"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":1,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 1 (b), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. no separate keypos source for s7 (sec-oph.js ans:null)",
},

{ n:11, p:554, key:2,
  stem:"How can you differentiate between episcleritis and scleritis?",
  opts:["Using phenylephrine 2.5%, redness disappears in episcleritis","Using phenylephrine 2.5%, redness disappears in scleritis","Using phenylephrine 10%, redness disappears in episcleritis","Using phenylephrine 10%, redness disappears in scleritis"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:true,
  note:"KEY: 2 (c), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NUMBER CHECK: stem/options contain a number, unit, dose, exponent, arrow or dash; verify against the page image before drafting. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. no separate keypos source for s7 (sec-oph.js ans:null) Structural similarity: n:9 and n:11 share the same stem template (\"How can you differentiate between episcleritis and X, using phenylephrine 2.5%/10%\") but compare episcleritis to a DIFFERENT condition each (conjunctivitis vs. scleritis) and their option sets differ in 2 of 4 entries -- NOT an exact or near-miss shared menu (validator threshold is exactly-one-entry-different), so no forced cross-reference; both transcribed normally for the human reviewer.",
},

{ n:12, p:556, key:2,
  stem:"Which of the following conditions is described as a localized protrusion of the sclera, lined by uveal tissue, and appears blue in color?",
  opts:["Scleral nodule","Scleral papule","Staphyloma","None of the above"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":2,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 2 (c), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. no separate keypos source for s7 (sec-oph.js ans:null)",
},

{ n:13, p:558, key:0,
  stem:"All of the following are true regarding episcleritis except?",
  opts:["It causes severe eye pain","It causes photophobia","It's usually accompanied by tender episcleral nodules","It may be either simple or nodular"],
  expl:"",
  boxPrinted:false,
  keySource:"Recorded in the staged s07 source (s07-gemini-text.txt), 2026-09-16. Not re-run or re-derived by this script.",
  keypos:{"visualIndex":0,"keyposIndex":null,"agree":null},
  numberCheck:false,
  note:"KEY: 0 (a), from the staged s07 source (s07-gemini-text.txt); not re-derived here. NO EXPLANATION BOX PRINTED per staged source -- the draft explanation must be authored from source, not copied from a box. no separate keypos source for s7 (sec-oph.js ans:null) Direct human-verified page-image read (no vision or OCR) confirms option A verbatim reads \"It causes severe eye pain\". Medical soundness of the key (A/index 0) checked and confirmed sound.",
},

];